### ISSUE TITLE
CSRF: Beim Löschen von Footer-Portlets erscheint noch ein Warnhinweis

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1009]
![bildschirmfoto 2015-06-17 um 12 56 35](https://cloud.githubusercontent.com/assets/485600/8205417/cc33a064-14f0-11e5-87bf-14e04b5a2fa6.png)

**Comment by deiferni** [comment]
@phabegger ich kann das Problem nicht mehr reproduzieren. Portlets lassen sich bei mir lokal ohne die die CSRF-Bestätigung löschen. Ich schliesse daher den Issue.

**Comment by deiferni** [comment]
Ist im `master` schon behoben.
