### ISSUE TITLE
Übersetzung Benachrichtigungs-Typ verbessern

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1010]
Momentan wird für die Benachrichtgungs-Typen die gleiche Übersetzung verwendet wie für die entsprechenden Buttons in der Aufgaben-Übersicht. Besser wäre hier eine andere detailiertere Übersetzung (in der Vergangenheitsform) zu verwenden, z.B. "Aufgabe neu zugewiesen" anstatt "Neu zuweisen".

![screen shot 2015-06-17 at 15 26 35](https://cloud.githubusercontent.com/assets/736583/8209342/bafe1af6-150c-11e5-8046-be3aed59a478.png)

**Comment by lukasgraf** [comment]
Die transition `forwarding-added` ist noch nicht übersetzt.
