### ISSUE TITLE
Ungelesene Benachrichtigungen absteigend sortieren (neueste zuerst)

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1012]
Im notifications viewlet wäre es logischer, wenn die neusten Benachrichtigungen zuoberst erscheinen würden (wie z.B. auch in Mail-Clients).

Zum Vergleich noch ein Screenshot wie die Benachrichtigungen bei StackOverflow aussehen:

![stackoverflow_notifications](https://cloud.githubusercontent.com/assets/405124/8250305/9563e8d6-1672-11e5-954f-f8d116a705a6.png)

**Comment by phabegger** [comment]
:+1:

**Comment by phgross** [comment]
Ist bereits umgesetzt.
