### ISSUE TITLE
Quickupload: Performance für Upload in Dossiers mit vielen Dokumenten

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1030]
Die Performance für Quickupload in Dossiers mit vielen Dokumenten (=tausenden) soll verbessert werden.

Siehe [Maintlog Zug #20220](https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20220)

**Comment by deiferni** [comment]
Vorerst nur Analyse

**Comment by lukasgraf** [comment]
Closing, since maintlog issue was closed.
