### ISSUE TITLE
Status-Meldungen erscheinen bereits auf confirm-action view

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1034]
Wenn eine Aktion von `plone.protect` abgebrochen wurde, und der Benutzer mittels der `@@confirm-action` nach einer Bestätigung gefragt wird, werden eventuelle Status-Messages trotzdem bereits angezeigt:

![status_message_with_confirm](https://cloud.githubusercontent.com/assets/405124/8425528/d881c470-1f06-11e5-9a6f-372dcb487fbd.png)

Dies ist natürlich eine falsche Information, da, was auch immer gemäss Status-Message passiert sein soll, verhindert wurde. Der Grund dass diese trotzdem angezeigt werden ist vermutlich, dass die Status-Messages vom Request abhängig sind, und ein Rollback der Transaktion diesen nicht betrifft.

Eine Lösung könnte sein, in `plone/protect/auto.py` auf Status-Messages zu prüfen, diese aus dem Request zu entfernen und zwischenspeichern, und erst nachher wieder hinzuzufügen.

**Comment by deiferni** [comment]
Wird im neuen UI gelöst.
