### ISSUE TITLE
Beschlussnummer hinzufügen.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1065]
Für alle beschlossenen Anträge muss eine fortlaufende Nummer generiert werden. Demnach eine fortlaufende Nummerierung pro Periode pro Kommission.

Periode:
 - Muss pro Kommission manuell erstellt und abgeschlossen werden können.
 - Beim Abschluss wird gleich die neue Periode erstellt.
 - Freitext Feld für Perioden Bezeichnung
 - Zusätzliche Informationen (Start, Ende) 
 - Vorerst keine Prüfung ob Periode noch aktiv (so sind Nachbearbeitungen einer Periode noch möglich).
 - Die Sitzung müsste eine Relation zur Periode speichern.

Beschlussnummer:
 - Wir pro Traktandum pro Periode fortlaufend generiert.
 - Startpunkt: 1
 - Vergabe nach "Sitzungs-Beendung" (erster Abschluss eines Traktandums) 
 - Muss zwingend im Protokoll, Protokollauszug und im Stichwortverzeichnis ersichtlich sein.
 - Auch auf Proposal-Übersicht anzeigen

Offene Fragen: 
 - Conflict Problem

**Comment by phgross** [comment]
Es stellt sich die Frage ob die Traktanden fortlaufend oder eindeutig nummeriert sein müssen? Oder geht es generell nur um die Nummerierung der Beschlüsse?

@phabegger kannst du hierzu evtl. mehr Infos liefern?

**Comment by deiferni** [comment]
update: protect against concurrent modifications with: 
http://docs.sqlalchemy.org/en/rel_1_0/orm/query.html#sqlalchemy.orm.query.Query.with_for_update
