### ISSUE TITLE
Styling Bug in der Sitzungsansicht im Firefox

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1074]
![bildschirmfoto 2015-07-21 um 11 30 05](https://cloud.githubusercontent.com/assets/485755/8797475/f5236e4e-2f9b-11e5-88aa-1d2484985059.png)

**Comment by bierik** [comment]
Wurde dies anders umgesetzt? Ich habe diese Ansicht auf dem Master nicht mehr:
![bildschirmfoto 2015-08-10 um 17 26 56](https://cloud.githubusercontent.com/assets/1637820/9175286/197e35fa-3f85-11e5-99a5-cbc7dc851acf.png)

**Comment by deiferni** [comment]
Stimmt, die Elemente wurden in der Zwischenzeit verschoben. Auf Firefox schauts nun ok aus, der Issue erübrigt sich :wink:
