### ISSUE TITLE
Einspielung Release 3.4

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1078]
### Checkliste für die Einspielung des Release 3.4

- [x] `opengever.zug` Policies auf dem `master` überprüfen
- [x] Vor dem Release überprüfen ob wieder kaputte `ftw.mail.mail.Mail` Klassen vorhanden sind (Zug)
  `~/scripts/check_mail_class.py`  ausführen und allenfalls mit `~/scripts/fix_mail_class.py` korrigieren
- [x] Release-Branch `4.5-stable` erstellen
- [x] Vor dem Update einen [Oracle-Export](https://github.com/4teamwork/opengever.zug/wiki/Oracle#oracle-dumps-erstellen) erstellen (Zug) oder eine MySQL Dump der OGDS DB erstellen.
- [x] Im `src` benötigte Checkouts einmal klonen und für alle Mandanten ins `src` kopieren (wegen Problem mit `git clone`)
- [x] Vor länger dauernden Upgrades relevante Cron-Jobs deaktivieren
- [x] Mit Python `2.7.10` bootstrappen und buildouten
- [x] Upgrade-Step `opengever.base:default 4001` (modified seconds) patchen - so wie in `0000oglx10:/home/zope/eggs/opengever.core-4.0.9-py2.7.egg/opengever/base/upgrades/to4001.py`
- [x] `Memmon` stoppen!
- [x] Falls Instanzen im `fg` gestartet werden: In einem `screen` starten!
- [x] Instanzen starten, von `2.9.2` auf `3.0.5` updaten
    - [x] evtl. auf `opengever.zug` branch `boot-with-3.0` wechseln
- [x] Nochmals einen Oracle-Export erstellen (Zug)
- [x] `src/opengever.maintenance` updaten
- [x] OGDS-DB DSN in `production/production-base.cfg` auf `oracle+cx_oracle://`umstellen (Zug)
- [x] `plone.app.upgrade.v43.final.addScalingQualitySetting` patchen
- [x] `opengever.mail:default 4500` Upgrade-Step (update filename) patchen - so wie in `0000oglx10:/home/zope/eggs/opengever.core-4.5.1-py2.7.egg/opengever/mail/upgrades/to4500.py`
- [x] `opengever.mail:default 4501` Upgrade-Step (fix encoding) patchen - so wie in mail `/home/zope/eggs/opengever.core-4.5.1-py2.7.egg/opengever/mail/upgrades/to4501.py`
- [x] Teure Upgrade-Steps "zusammenfassen" (auskommentieren von Catalog-Updates die in späteren Upgrade-Steps sowieso nochmals gemacht werden) siehe #1046.
 - `opengever.document.upgrades.to4100.AddRemovedState` reindexObjectSecurity entfernen
 - `opengever.dossier.upgrades.to4201.py` reindexObjectSecurity auskommentieren
 - `opengever.dossier.upgrades.to4302.py` reindexObjectSecurity auskommentieren
- [x] `ftw.zopemaster` Problematik mit einloggen auf unterschiedlichen Mandanten lösen
- [x] Buildout auf `3.4.1` aktualisieren und buildouten
- [x] LDAPUserFolder Patchen
- [x] `Memmon` stoppen!
- [x] Falls Instanzen im `fg` gestartet werden: In einem `screen` starten!
- [x] Upgrade-Steps von `3.0.5` auf `3.4` ausführen (evtl. aus Performancegründen ohne `opengever.policy.base.4504` (Reindex ZCTextIndex))
    - [x] Für KOM-RPK alle Upgrades durchführen
    - [x] Upgrades für restliche Mandanten durchführen
- [x] OGDS-Synchronisierung durchführen (`group.active` wird sonst nicht initialisiert).
- [x] Ggf. OGDS Synchronisierung anpassen (Cronjob)
- [x] Ggf. `opengever.policy.base.4504` (Reindex ZCTextIndex) noch durchführen (evtl. Java VM von Tika mehr Memory geben) 
- [ ] HAProxy anpassen: content-creation requests serialisieren (siehe 4teamwork/opengever.ai#127)
- [x] Patch in `opengever/mail/mail.py`rückgängig machen
- [x] Ggf. gestoppte Cron-Jobs wieder aktivieren (Pack Cron Job, diesen aber erst nach Absprache mit Zug/Parallel wieder aktivieren!)
- [x] Bridge wieder starten
- [x] Ggf. cron job für leeren von `ogds-update.log` entfernen
- [ ] Neuen Manager User erstellen (Zug)
- [ ] Schulungssystem updaten (Zug)
- [x] Notification Default für  Weiterleitung hinzufügen Typ hinzufügen (Mail aktivieren).

### Tests nach dem Release

- [x] Autocomplete Widgets
- [x] Searchable Text (Suche, mit und ohne Umlaute)
- [x] ContentTree Widgets (darf keinen `KeyError` geben)
- [x] Aufgaben (mit Umlauten in Breadcrumbs)
- [x] Bridge
- [x] PDF Konvertierung
- [x] Tika
- [ ] Länge der Nummerngruppen im `sortable_title` prüfen (sollte von 6 auf 4 gewechselt haben)

**Comment by phgross** [comment]
### Probleme / Patches während dem Release:
 - `opengever.globalindex.upgrades.to4002.MigrateSubdossierColumnData`(Nicht synchronisierte Aufgaben)
