### ISSUE TITLE
ConflictErrors bei Content-Erstellung

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1117]
Bei der Erstellung von Plone-Content (`++add++` Formulare, Inbound-Mail oder QuickUpload) gibt es im Moment diverse `ConflictError`s:
- `Products.CMFUid.UniqueIdGeneratorTool.UniqueIdGeneratorTool` konfliktet bei der Erstellung einer initialen `CMFEditions` Version
- Das `PersistentMapping` unter dem key `ISequenceNumber.sequence_number` in den Annotationen des Portal-Objekts konfliktet weil [der Increaser erneut zugewiesen wird](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/sequence.py#L65)
- Beim gleichzeitigen Erstellen von Objekten konfliktet der `modified_seconds` Index im Katalog
- Beim parallelen Erstellen von Content im selben container konfliktet `IAnnotations(container)['plone.folder.ordered.order']`
- Beim gleichzeitigen Login mit dem selben User konfliktet das Datum des letzten Logins in irgendwelchen User-Properties (relevant für Last-Tests) 
### Instanzen
- 2 -> 4 probieren
- Queue in HaProxy logs anschauen

**Comment by lukasgraf** [comment]
Die Vorgehensweise um diese Probleme in den Griff zu kommen, muss mehrere Aspekte umfassen:

- Sichtbarkeit des Problems
  - Errbit -> **Sentry** Ablösung um `ConflictErrors` zu sehen
  - **Logstash**, um Einsicht darin zu haben welche unserer Deployments wieviele Benutzer haben, wieviele concurrent requests, etc.. + zeitlicher Verlauf dieser Metriken

- Performance
  - Auf einem System das gut performt dauern die Requests und damit die Transaktionen weniger lange, dementsprechend ist die Wahrscheinlichkeit für Konflikte kleiner.
  - Als erstes brauchen wir eine **Baseline**, um beurteilen zu können welche Art von GEVER-Deployment im Moment welche Last ohne grosse Probleme verarbeiten kann.
  - Dafür brauchen wir ein **Lasttest-Setup**. Dies umfasst zum einen eine entsprechende Policy mit grossem Ordnungssystem, einen Mechanismus um reproduzierbar (seeded) eine beliebige Menge an zufälligen Inhalten zu erzeugen, und Tooling das so aufgesetzte System dann unter Last zu setzen (z.B. etwas ähnliches wie [locust.io](http://locust.io/)).
  - Ideal wären Tests für Performance-Regressionen
  - Mit reproduzierbaren Lasttests hätten wir auch die Möglichkeit, die Performance von Umgebungen bei Kunden (physisch oder virtuell) mit einem Referenzsystem von uns zu vergleichen, und evtl. Empfehlungen abzugeben.

  - Generelle Performance von GEVER verbessern.
    - Quick-Win: Richtige caching header setzen (`plone.app.caching`, `ftw.theming`).
    - Evtl. Varnish. Der Zope Application-Server hat besseres zu tun, als CSS, Javascript und Bildchen auszuliefern.
    - Caching-Einstellungen für unsere Deployments *bewusst* vornehmen und optimieren (ZODB pickle cache, Blob-Caches, Memmon-Limits)
    - Caching in der Applikation. Gewisse Resultate von SQL-Queries cachen, tabbed-view helpers / transforms.
    - [`n+1 selects` Probleme](http://stackoverflow.com/questions/97197/what-is-the-n1-selects-issue) bei SQL-Queries vermeiden
    - Indexes in unseren SQL-DBs verwenden (#1169)

- Weniger unnötige Schreibzugriffe / Transaktionen
  - Der Einsatz von **Redis** für persönliche Einstellungen (#1253 ) wäre da ein Quick-Win

- **Solr / Elasticsearch**. Wenn der `SearchableText` beim Erstellen von Inhalten asynchron gerechnet werden könnte, würde das die Zeitdauer dieser Transaktionen signifikant verkürzen, und damit das Konfliktpotential reduzieren 
 
- **CMFEditions** ablösen

/cc @phabegger

**Comment by lukasgraf** [comment]
Weitere Schritte:
- @buchi auf AI Server noch gründlichere Performance-Tests machen (evtl. Fäbu) (siehe https://extranet.4teamwork.ch/support/gever-ai/tracker/163)
- @jone Mechanismus implmentieren für globale Counter in ZODB die
  - konfliktarm sind
  - eindeutige, fortlaufende IDs generieren können
- @lukasgraf Instanzen für AI von 2 auf 4 erhöhen
- @lukasgraf ein erstes Setup von `logstash` auf AI deployen
- @lukasgraf `plone.app.caching` in GEVER einsetzen und konfigurieren
- @lukasgraf minmales Setup für reproduzierbare Lasttests aufbauen
- @lukasgraf ggf. `collective.stats` einsetzen

**Comment by phgross** [comment]
Die Ablösung von CMFEditions wird im OGIP 30 Verbindliche Dokumentversion behandelt. 

Andere Arbeiten wären erst nach einer Neubeurteilung der Situation sinnvoll. Ich schliesse deshalb diesen Issue.
