### ISSUE TITLE
Autocomplete Widget: Einträge werden nicht korrekt abgewählt. 

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1121]
Das Autocomplete Widget macht den Anschein das bei einem Choice Field (Auftragnehmer bei einer Aufgabe) mehrere Personen gewählt werden können: 
Dies ist kann folgendermasser reproduziert werden: 
> nachdem man zuerst vergessen hat, einen anzuwählen (Resultate aber bereits gefiltert) was richtigerweise zu einem "Fehler" führt. Danach können aber fälschlicher Weise mehr als ein Auftragnehmer angegeben werden (siehe Screenshot).

![bildschirmfoto 2015-08-03 um 15 01 32](https://cloud.githubusercontent.com/assets/485755/9038003/0bda5148-39f1-11e5-8fcb-05d636fd55ae.png)

**Comment by lukasgraf** [comment]
Die Ursache für dieses Verhalten ist, dass die `<input />` Elemente welche über Page Templates gerendert werden und die, welche mittels Javascript Callback erzeugt werden, unterschiedliche Werte für `name="..."` haben (eine Variante mit einem `:list` Suffix, die andere ohne).

Dies ist sehr wahrscheinlich auf eine Änderung in `z3c.form` und/oder `z3c.formwidget.query` zurückzuführen.

Im Upstream `plone.formwidget.autocomplete` gab es diesbezüglich mal eine Anpassung: [d6e356d2: Only do list marshalling for multiple selection](https://github.com/plone/plone.formwidget.autocomplete/commit/d6e356d261171e0276090a8d70f26ba4aaa7244b) welche eine Unterscheidung zwischen Multi- und Single-Selection Widget macht, und davon abhängig ein `:list` anhängt oder nicht. Ich gehe davon aus, dass diese Anpassung als Folge der Änderung des Verhaltens in `z3c.form` / `z3c.formwidget.query` gemacht wurde.

Dies löst das Problem aber noch nicht: In `z3c.formwidget.query` wird [beim Setzen des `NOVALUE` Marker-Wertes (immer noch) ein Name mit einem hartcodieren `:list` Suffix verwendet](https://github.com/do3cc/zope/blob/master/z3c.formwidget.query/trunk/src/z3c/formwidget/query/widget.py#L185-L193). D.h. für Felder die `required` sind löst die Anpassung in `plone.formwidget.autocomplete` das Problem, aber dafür gehen Single-Selection widgets für Felder die *nicht* `required` sind dann nicht mehr (z.B. `responsible` im Advanced Search Form).

**Comment by lukasgraf** [comment]
Fazit: Können wir im Moment nicht auf eine Art und Weise lösen wo wir zuversichtlich sein können, dass wir nicht anderes Verhalten beinträchtigen.

Wir werden hier auf ein eigenes Widget wechseln müssen, unser Fork von `plone.formwidget.autocomplete` wir hier langsam aber sicher zum Problem.
