### ISSUE TITLE
Reference prefix not updated in catalog

### ISSUE THREAD

**Issue by shylux** [4teamwork/opengever.core#115]
Some places (treeportlet, dossier listing) keep the old reference prefix after a new prefix is set. The cause is the catalog which still holds the old values.

@phgross check how the reference prefix stuff should be handled.

**Comment by phgross** [comment]
Vorerst nur Konzept erarbeiten wie wir das Problem lösen wollen.

**Comment by phgross** [comment]
Die Problematik von lang dauernden Requests, bei Anpassungen an Ordnungspositionen mit viel Inhalt, wird vorerst "ignoriert".

Führt dies in den kommenden Monaten zu mehr Support Aufwand, können wir diese Problematik immer noch angehen.
