### ISSUE TITLE
plone.formwidget.autocomplete durch eigenes Widget ablösen

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1152]
Unser eigener Fork von `plone.formwidget.autocomplete` ist nicht mit dem Upstream nachgeführt, und verursacht einige Probleme (siehe z.B. #1121).

Wir sollten hier stattdessen unser eigenes Widget implementieren.

**Comment by phgross** [comment]
Wird im Rahmen der OGIP 15 Arbeiten in Angriff genommen.

**Comment by maethu** [comment]
Reicht noch nicht... Es muss auch noch ftw.referencewidget implementiert werden (Ersatz für contenttree widget)

**Comment by maethu** [comment]
@phgross Können wir den Fork bereits jetzt ablösen. 
Ich kann das nicht so genau sagen, da das contenttreewidget ebenfalls noch das autocompletewidget benötigt.

**Comment by phgross** [comment]
Hab mir das letze Woche angeschaut aus meiner Sicht gibt es hier kein Zusammenhang zwischen unserem Fork und dem Contenttree Widget. So weit ich gesehen habe, sollte die originale Version des plone.formwidget.autocomplete für das contenttreewidget funktionieren.

Ich kläre das im Verlaufe des Tages noch ab.

**Comment by maethu** [comment]
Wie sieht es hier nun aus?

**Comment by phgross** [comment]
@maethu siehe referenzierter PR
