### ISSUE TITLE
Inhaltstypen brauchen Container Klasse anstatt eigene Subklasse.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1160]
Im Moment brauchen die folgenden Inhaltstypen die Klasse `plone.dexterity.content.Container`:
- opengever.contact.contactfolder
- opengever.inbox.yearfolder
- opengever.inbox.inbox
- opengever.repository.repositoryroot
- opengever.tasktemplates.tasktemplatefolder

Dies verhindert saubere objektorientierte Lösungen, da die Klassen gar nicht angepasst werden können. Aktuelles Beispiel die `IsPastingAllowedView`.

**Comment by phgross** [comment]
Bis auf den Yearfolder und den Tasktemplatefolder, wurde dies bei allen Objekte implementiert. Bei den zwei genannten sehe ich zurzeit kein Bedarf. Sobald man aber ein entsprechenden Yearfolder oder TaskTemplateFolder Klasse benötigen würde, kann dies relativ einfach eingeführt und migriert werden (ftw.upgrade `migrate_class`). Ich schliesse deshalb diesen Issue.
