### ISSUE TITLE
`move_items` View - zu verschiebende Pfade können nachträglich angepasst werden

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1161]
Die zu verschiebenden Pfade werden als `#form-widgets-request_paths` als hidden input Felder gerendert. Die Werte können nachträglich verändert werden, so dass u.u. auch Elemente verschoben werden können, für die das nicht möglich sein sollte.

**Comment by phgross** [comment]
im neuen UI mit der API gelöst.
