### ISSUE TITLE
Beim kopieren und einfügen von Dossiers mit Dokumenten werden keine PDF Previews gerendert

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1186]
- Dossier inkl. Dokumente kopieren
- Kopiertes Dossier in eine Ordnungsposition einfügen

-> Für die Dokumente im eingefügten Dossier werden keine PDF Previews gerendert.

**Comment by deiferni** [comment]
Erste Analyse, der Request, der die PDFs zurückspielen sollte kommt bei Plone/Zope nicht als POST sondern als GET request ohne parameter an, obwohl er von opengever async definitiv nicht so abgeschickt wird, siehe https://github.com/4teamwork/opengever.async/blob/master/opengever/async/pdf.py#L164-L167

**Comment by phgross** [comment]
`opengever.async` bzw. `opengever.pdfconverter` wird mit opengever.bumblebee abgelöst. Ich schliesse dieses Ticket.
