### ISSUE TITLE
Zwei-Faktor-Authentifizierung einbinden

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1187]
Es soll in GEVER **Zwei-Faktor-Authentifizierung** implementiert werden (vorerst für EDK, siehe [EDK Tracker #3](https://extranet.4teamwork.ch/extern/0338-projekt-installation-onegov-gever-edk/0338-tracker-installation-onegov-gever-edk/3)).

Dazu habe ich [collective.googleauthenticator](https://github.com/collective/collective.googleauthenticator) getestet. Ich denke mit diesem Add-On kann das Grundsätzlich funktionieren, es gibt aber noch vieles zu tun und einige ungelöste Probleme:

- Nach dem Eingeben von Benutzername und Passwort, aber *vor* dem eingeben des Google-Tokens, ist der Benutzer in Plone bereits authentisiert. `portal_membership.getAuthenticatedMember()` gibt den Benutzer zurück, Permission-Checks sind erfolgreich, etc...

![verification](https://cloud.githubusercontent.com/assets/405124/9403995/ee971554-47eb-11e5-9b91-3fbf7b9f84cb.png)

Dies ist der Fall weil die `authenticateCredentials()` Methode des PAS Plugin von `collective.googleauthenticator` [`None` zurückgibt](https://github.com/collective/collective.googleauthenticator/blob/master/src/collective/googleauthenticator/pas_plugin.py#L116) für den Fall dass es die Authentisierung übernehmen will und den Redirect auf das Token-Verification Form auslöst.

PAS interpretiert das dann so, dass dieses Plugin die Credentials nicht authentisieren konnte, und [fragt das nächste in der Liste](https://github.com/zopefoundation/Products.PluggableAuthService/blob/master/Products/PluggableAuthService/PluggableAuthService.py#L654-L655). Dieses wird dann irgendwann das Plugin sein das die Credentials üblicherweise authentisiert, und aus Sicht von PAS ist die Authentisierung damit bereits erfolgreich, und der User ist angemeldet. 

Um dies zu verhindern, denke ich dass `authenticateCredentials()` zu diesem Punkt auf jeden Fall einen Wert zurückgeben muss, der nicht `None` ist. Für diese konkrete Condition würde `(None, None)` reichen, aber dann ist eine [spätere condition](https://github.com/zopefoundation/Products.PluggableAuthService/blob/master/Products/PluggableAuthService/PluggableAuthService.py#L666) nicht erfüllt. `('Anonymous', None)` *scheint* für den Moment den gewünschten Effekt zu haben, ist aber ein Hack der schlicht ein Implementierungsdetail von PAS ausnutzt.

- Das globale Aktivieren von 2FA funktioniert nicht richtig.
Die Checkbox im Controlpanel-Formular löst beim Speichern aus, dass entweder für alle User die 2FA aktiviert oder deaktiviert wird. Weil aber `plone.api.user.get_users()` keine User eines `LDAPUserFolder`s zurückliefern kann, wird dies in unserem Setup für keinen User aktiviert.

- Die [Condition `if 'user' in plugid`](https://github.com/collective/collective.googleauthenticator/blob/master/src/collective/googleauthenticator/pas_plugin.py#L87) ist falsch - dies führt dazu dass z.B. der LDAPUserFolder nicht berücksichtigt wird. Stattdessen sollten alle `IAuthenticator` plugins befragt werden, ausser natürlich dass Google Authenticator plugin selbst.

- Nach dem (manuellen) aktivieren von 2FA durch einen User sollte nicht auf die `@@personal-information` view redirected werden, diese wird bei uns nicht verwendet.

- `_SWALLOWABLE_PLUGIN_EXCEPTIONS` werden nicht abgefangen.

- Emergency-User scheint nicht respektiert zu werden

#### Kleinigkeiten

- Formular-Buttons im Google Authenticator Control-Panel führen zu `Unsaved changes - leave this page?` Abfrage im Browser und sind nicht richtig übersetzt.

- Nach erfolgreichem Anmelden wird eine custom status message verwendet statt die Standard-Message von Plone - deshalb ist diese auch nicht übersetzt.
 
- Enable 2FA Aktion sollte *oberhalb* von "Logout" sein. "Logout" sollte m.M.n. immer die unterste Aktion im Menü sein.

**Comment by lukasgraf** [comment]
Gemäss Besprechung mit @buchi:

Wir haben uns darauf geeinigt, dass
- das globale Flag für die Aktivierung wirklich als solches funktionieren soll. Es würde also in `authenticateCredentials()` der Registry-Eintrag geholt, und 2FA ist (sinngemäss) dann aktiv, wenn `globally_active or active_for_user`. 

- Um zu verhindern, dass der Benutzer nach Eingabe der Login-Credentials (aber vor der Eingabe des korrekten 2FA Tokens) bereits angemeldet ist, sollen in der `authenticateCredentials()` Methode des `collective.googleauthenticator` PAS Plugins die credentials "konsumiert" - sie werden also aus dem `credentials` dict gelöscht.

**Comment by phgross** [comment]
Dieses Feature sollte bis Ende Nov. Production Ready sein.

**Comment by lukasgraf** [comment]
Hier wird neu eine andere Lösung verfolgt (2FA via CAS-Portal).
