### ISSUE TITLE
Portlet assignments for Inbox, Templates and Contacts are missing on new setup

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1214]
On a newly set up GEVER from `4.5-stable`, but probably also `master`, the portlet assignments for the `Inbox`, `Templates` and `Contacts` global tabs are missing.

Once fixed this should probably be backported to `4.5-stable`.

**Comment by phgross** [comment]
Wie heute besprochen, werde ich die Ist-situation der einzeln Kunden kurz festhalten und einen Vorschlag erarbeiten.

Ziel ist, dass für alle Gever Kunden die gleichen Portlet Einstellungen vorhanden sind. Deshalb muss ein Vorschlag erarbeitet werden der von allen Kunden gut geheissen wird  (evtl. Feedback Forum) .

**Comment by phgross** [comment]
### Ist Situation:
#### Zug:
**Übersicht**: Treeportlet (v2)
**Ordnungssystem v1**: Treeportlet (v1)
**Ordnungssystem v2**: Treeportlet (v2)
**Eingangskorb**: Navigationsportlet (Startebene = 0)
**Vorlagen**: Treeportlet (v2)
**Kontakte**: Treeportlet (v2)

#### AI:
**Übersicht**: Treeportlet
**Ordnungssystem**: Treeportlet
**Eingangskorb**: Treeportlet
**Vorlagen**: Navigationsportlet (Startebene = 0)
**Kontakte**: Treeportlet

#### Saas
**Übersicht**: Treeportlet
**Ordnungssystem**: Treeportlet
**Eingangskorb**: Kein Portlet
**Vorlagen**: Navigationsportlet (Startebene = 1) oder Keinees
**Kontakte**: Kein Portlet
**Sitzungen**: Kein Portlet


### Soll
Folgendes ist aus meiner Sicht gegeben:
 - **Ordnungssystem(e)**: Treeportlet
 - **Vorlagen**: Navigationsportlet (da OneGov GEVER mittlerweile das verschachteln von Vorlagen unterstützt, muss dort die Struktur dargestellt werden).
 - **Eingangskorb**: Navigationsportlet beim (da abgeschlossene Weiterleitungen automatisch im Jahresordner _Abgeschlossen 2016_ landen, muss die Struktur dargestellt werden, sonst sind die Jahresordner und abgeschlossenen Weiterleitungen nicht mehr ersichtlich).

Demnach noch offen:
 - Persönliche Übersicht
 - Eingangskorb
 - Kontakte
 - Sitzungen

###Vorschlag:
**Übersicht**: Treeportlet (aktuelles Ordnungssystem)
(**Ordnungssystem v1**: Treeportlet (v1))
**Ordnungssystem v2**: Treeportlet (v2)
**Eingangskorb**: Navigationsportlet (Startebene = 1)
**Eingangskorb**: Navigationsportlet (Startebene = 1)
**Kontakte**: Kein Portlet
**Sitzungen**: Kein Portlet



@phabegger @deiferni @lukasgraf Was denkt ihr ?

**Comment by deiferni** [comment]
Finde den Vorschlag passend 👍  (Eingangskorb ist doppelt, ich nehme an, dass man einen mit Vorlagen ersetzten kann 😉 )

Nebenbemerkung: bei Sitzungen gehen wir im Moment davon aus, dass es keine Portlets hat. Wenn man das entgegen dem Vorschlag ändern möchte müsste man vermutlich auch die Styles anpassen oder überdenken.

**Comment by phgross** [comment]
Kleiner Nachtrag: 
Ich habe so eben bei einem Kunden mit Virtuellen Mandanten festgestellt das die Vergabe der Portlets bei mehreren Eingangskörben pro Admin Unit, sehr wichtig ist (siehe https://extranet.4teamwork.ch/support/0282-kunde-stadt-nidau/0282-tracker-support-stadt-nidau/25) 

Deshalb folgender Vorschlag für Eingangskörbe:
Eingangskorbordner -> Kein Portlet
Eingangskorb -> Jeder Eingangskorb erhält ein separates Portlet, mit der Einstellung `Zeige nur den Inhalt des aktuellen Ordners.`

**Comment by lukasgraf** [comment]
@phgross Ursprünglicher Vorschlag + Ergänzung bzgl. Eingangskorb passt 👍
