### ISSUE TITLE
Persistence issues with Mails

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1215]
There are some persistence issues with mails after migrating to the new `OGMail` classes that need to be debugged.

Mails having `no_subject` indexed as their title may or may not also be part of the same issue.

**Comment by deiferni** [comment]
Die fix-Scripts wurden letzte Woche auf allen betroffenen Mandanten ausgeführt. Bis heute sind keine Regressionen mehr aufgetreten. Wir gehen nun davon aus, dass wir alle Referenzen erwischt haben und deshalb keine Mails mit der falschen Klasse mehr erscheinen sollten.
