### ISSUE TITLE
Create a view that warms up Plone instances

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1219]
We desperately need a view that warms up Plone instances adequately so we can directly send customers to them after rebooting instances.

This means at least priming the ZODB cache by doing catalog queries for the most used objects, loading the front page and possibly alread render some often-used views.

**Comment by deiferni** [comment]
Done in https://github.com/4teamwork/opengever.maintenance/blob/1c6e113af2213a775148d320495f93532443b481/opengever/maintenance/browser/warmup.py#L30
