### ISSUE TITLE
Mails with escaped HTML in Preview

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1222]
Preview for some mails is broken in a very particular way:

The HTML displayed in the preview tab seems to have been escaped, so the HTML get's displayed literally instead of being rendered. Example: Laufnummer 2234 on SKA-ARCH

**Comment by phgross** [comment]
Mit der Bumblebee Vorschau existiert dieses Problem beim genannten Mail nicht mehr.
