### ISSUE TITLE
Fix broken Plone Lexicon

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1226]
The first version of the [upgrade-step in `opengver.policy.base:default 4504`](https://github.com/4teamwork/opengever.core/blob/bb51ea7cb3e1546513fd5b032a951678f5dd8693/opengever/policy/base/upgrades/to4504.py#L30-L36) was faulty because it didn't clear the ZCTextIndexes before rebuilding them. (The fix for the corresponding upgrade-step is in 4teamwork/opengever.core#1224).

After upgrading to 3.4 before the upgrade step was fixed, this lead to a situation where the Plone Lexicon is inconsistent with the ZCTextIndexes:

`ZCTextIndexes` don't store lists of strings for the indexed terms for a document, they store lists of word IDs (`wid`s). Those `wid`s refer to a particular [word in the index's lexicon](https://github.com/zopefoundation/Products.ZCTextIndex/blob/7fdbb65cf85b6e4b239a5b68c96b46fae093fa4a/src/Products/ZCTextIndex/Lexicon.py#L62-L66). [`getEntryForObject()`](https://github.com/zopefoundation/Products.ZCTextIndex/blob/7fdbb65cf85b6e4b239a5b68c96b46fae093fa4a/src/Products/ZCTextIndex/ZCTextIndex.py#L221-L228) then turns those `wid`s back to words.

In our case, it seems that some words are missing from the lexicon, [resulting in a `KeyError` when trying to look up that `wid` in `lexicon._words`](https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/55e6def26d617472924b0000).

As far as I can see, the only reliable way to fix this is to first clear the affected indexes and then rebuild them.

An logfile of the first analysis done with this script is at `0000oglx13:~/debug_logs/rid_key_errors_analysis_2015-09-15.log`. It seems that only the `document_author` and `searchable_filing_no` indexes are affected.

**Comment by lukasgraf** [comment]
Fix script:

```
bin/instance0 run ~/services/og-maintenance/src/opengever.maintenance/opengever/maintenance/scripts/fix_broken_indices.py
```

(Clears and rebuilds `document_author` and `searchable_filing_no` indexes).

**Comment by phgross** [comment]
Korrektur für alle Mandanten in Zug durchgeführt. 

@lukasgraf muss dieses Anpassung auch für weiter Deployments gemacht werden oder haben wir dazumal in der Zwischenzeit den Fehler in unserem Patch korrigiert?

**Comment by lukasgraf** [comment]
@phgross der eigentlich Upgrade-Step wurde in #1224 gefixt.

**Comment by phgross** [comment]
OK Danke für die Info. Dann kann der Issue geschlossen werden, denn #1224 ist ab Release `4.5.5` enthalten und die anderen Installation wurden mit `4.5.5` oder höher aktualisiert.
