### ISSUE TITLE
EditingDocument: ZEM download trotz CSRF Warnung.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1236]
Wird die `EditingDocument` view ohne valides authentication token aufgerufen, so erscheint zwar korrekterweise die CSRF Meldung, trotzdem wird fälschlicherweise der Download der ZEM Datei gestartet.

Dies passiert weil der Download mittels [IRedirector](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/browser/edit.py#L141) angeboten wird.

**Comment by deiferni** [comment]
Umsetzungsvorschlag: document-checkout auf die CSRF-Whitelist setzen weil nicht "gefährlich".
