### ISSUE TITLE
UX Verbesserungen Sitzungsansicht

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1256]
Ich habe mir zur aktuellen Sitzungsansicht einige Gedanken gemacht und gewisse Verbesserungsvorschläge als Mockups skizziert: 

Sitzung in Planung:
- Das Bearbeiten eines Protokolls soll dem Bearbeiten der Sitzung entsprechen, so kann einerseits der Bearbeiten Button zentral platziert werden anderseits die Contentmenübar entfernt werden.
- Das Hinzufügen von Traktanden/Abschnitte wird gruppiert und standardmässig ausgeblendet, so kann platz gesparrt werden und die Elemente lenken nicht vom zentralen Element, den Traktandenliste, ab.
![sitzung in planung](https://cloud.githubusercontent.com/assets/485755/10580721/2623e1c0-767f-11e5-9310-84e74f40fc8e.png)
Traktanend hinzufügen:
![sitzung traktanden hinzufugen](https://cloud.githubusercontent.com/assets/485755/10580722/262535fc-767f-11e5-9148-eb5e8e1b9d28.png)
Traktanden überarbeiten:
![traktanden uberarbeiten](https://cloud.githubusercontent.com/assets/485755/10580719/261fdf9e-767f-11e5-9d34-529060380233.png)

Sitzung durchgeführt
![sitzung durchgefuhrt](https://cloud.githubusercontent.com/assets/485755/10580718/261fa880-767f-11e5-8515-da2d76518908.png)

Sitzung abgeschlossen:
![sitzung abgeschlossen](https://cloud.githubusercontent.com/assets/485755/10580720/262252e2-767f-11e5-8eed-71f2902ccb4a.png)

Mockup Datei: https://drive.google.com/open?id=0B7pCc3EpN_p0Rlk5Z2VLdlhoZnM

@lukasgraf @bierik @deiferni Feedback willkommen.

**Comment by deiferni** [comment]
schon viel schöner und aufgeräumter :smile: :sparkles: 

Ein Paar Bemerkungen:

- Neu verlinken wir das zum Meeting gehörende Sitzungsdossier, das fehlt noch. Würde auf die linke Seite passen, z.B. zwischen Protokoll und Metadaten.
- Eventuell könnte man Abschnitte/Traktanden wieder auf zwei Zeilen aufteilen. Das Formular wird ja per default ausgeblendet. Ich finde die Zwei-Button Lösung optisch irgendwie nicht befriedigend.
- Die Protokollvorschau sollte auch zur Verfügung stehen, solange man noch kein Protokoll generiert hat.

Details, die wir auch später festlegen können:
- Das Protokoll sollte aktualisiert werden können, solange die Sitzung noch nicht abgeschlossen ist.
- Was ist mit Protokollauszügen? Keine mehr generieren sobald abgeschlossen? egal?

**Comment by phgross** [comment]
- Sitzungsdossier darstellen :+1: 
 - Abschnitte/Traktanden wieder auf zwei Zeilen :+1: 
 - Protokollvorschau: denke das sollte auch möglich sein :+1:
