### ISSUE TITLE
Meeting.get_url, no longer use committee's phycisal_path

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1259]
We want to remove `phycisal_path` from committee, thus `Meeting.get_url` must no longer use it. Instead pass the context (i.e. the committee) to `get_url` just as with the other wrapped objects.

**Comment by deiferni** [comment]
Also, in the meantine we have (partially) added an `SQLFormSupport` which should be used in all model classes that have forms.

**Comment by phgross** [comment]
Wird mit der grundlegenden Arbeiten (#3038 ) gelöst werden.
