### ISSUE TITLE
SPV: Unterstützung von Markdown bei der Eingabe von Texten

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1295]
Die Textauszeichnungen **fett** und *kursiv* funktionieren, aber irgendwie kriege ich keine Aufzählungen und Überschriften hin. Ich mag mich aber erinnern, dass das mal funktioniert hat.

Mache ich was falsch, oder ist etwas kaputt?

![bildschirmfoto 2015-11-04 um 20 48 42](https://cloud.githubusercontent.com/assets/485600/10949938/b851306c-8335-11e5-984d-7397d5a70db8.png)

**Comment by deiferni** [comment]
Ja, sollte eigentlich funktionieren, siehe https://github.com/senny/sablon/#markdown

**Comment by deiferni** [comment]
Auch überprüfen, ob die entsprechenden styles noch im template vorkommen

**Comment by deiferni** [comment]
Die entsprechenden styles haben in den templates gefehlt. Ich konnte das Problem lokal nicht reproduzieren. Habe deshalb die templates auf lab mit den aktuellen templates ersetzt.
