### ISSUE TITLE
Buttons verbessern

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1298]
![screen shot 2015-11-05 at 09 28 29](https://cloud.githubusercontent.com/assets/736583/10963305/b58608f2-839f-11e5-949b-2d92b9b60e1f.png)
- Hover fehlt
- Aktualisieren ( :arrows_counterclockwise: )*neben* dem protokoll anzeigen, damit wir auch direkt klar auf was sich der button bezieht

**Comment by phgross** [comment]
Erledigt
