### ISSUE TITLE
Statusicons Sitzung

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1301]
Im Moment haben die Stati einer Sitzung die folgenden Farbcodes:

![screen shot 2015-11-05 at 10 09 48](https://cloud.githubusercontent.com/assets/736583/10964166/7375f41c-83a5-11e5-912f-15810a01b145.png)
![screen shot 2015-11-05 at 09 59 22](https://cloud.githubusercontent.com/assets/736583/10964167/73779b6e-83a5-11e5-83f6-23118344eec8.png)
![screen shot 2015-11-05 at 10 09 58](https://cloud.githubusercontent.com/assets/736583/10964168/73786a44-83a5-11e5-81d5-c9ee58820970.png)

- wo ist grün? :see_no_evil:
- ich finde die task-statusicons etwas besser weil sie den progress deutlich aufzeichnen. grün-gelb-rot als ampel-analogie finde ich hier etwas heikel - was bedeutet nun z.B. rot genau? stop: ich kann nicht bearbeiten? stop: die sitzung ist noch nicht durchgeführt?
icons analog zu den tasks wären hier aus meiner sicht verständlicher:

![screen shot 2015-11-05 at 10 12 38](https://cloud.githubusercontent.com/assets/736583/10964392/2d4da438-83a7-11e5-83a1-bbbcf3c13af6.png)
![screen shot 2015-11-05 at 10 14 25](https://cloud.githubusercontent.com/assets/736583/10964393/2d4f2f6a-83a7-11e5-9f5c-d0ba770ce360.png)
![screen shot 2015-11-05 at 10 13 15](https://cloud.githubusercontent.com/assets/736583/10964394/2d50cf6e-83a7-11e5-858f-3a645efe0fb9.png)

**Comment by phgross** [comment]
Bin gleicher Meinung. Finde dein Vorschlag sehr gut.

Zudem wären die Status Icons auch für einzelne Anträge sehr hilfreich #934. Es wäre gut wenn das Status Icon eines Antrags dem Status Icon der Sitzung entsprechen würde.
