### ISSUE TITLE
Styling/Usability Protkollauszug generieren

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1304]
Die Seite zum erstellen von Protokollauszügen braucht noch etwas :heart: und :thought_balloon: 

Eventuell wäre die folgende Reihenfolge logischer:

1. Titel
2. Traktanden
3. Felder (Ausgangslage, ...)
4. Zieldossier

![screen shot 2015-11-05 at 11 02 09](https://cloud.githubusercontent.com/assets/736583/10965374/d14f6c1a-83ac-11e5-922a-9b3c3209483e.png)

**Comment by bierik** [comment]
@deiferni Wird diese view noch gebraucht? Sonst könnte man dieses Issue schliessen.

**Comment by deiferni** [comment]
Ja, wir habens noch nicht ausgebaut. Würde da aber nicht mehr investieren.
