### ISSUE TITLE
UX traktandieren box 

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1306]
Das Traktandieren ist neu als ganze Box expandable/collapsible :sparkles:. Wir sollten uns zusätlich zu dieser Verbesserung noch folgende Dinge überlegen:

- Sortierung: Antragsauflistung ist im Moment nicht alphabetisch sortiert, sondern vermutlich nach Erstellungszeitpunkt.
- Auflistung: Die Liste kann ganz schön lange werden bei vielen untraktandierten Anträgen. *Uns ist hier der Workflow der Kunden nicht klar, aber es ist durchaus denkbar, dass z.B. nur die jeweils kommende Sitzung traktandiert wird.* Würde ein durchsuchbares Dropdown dieses Problem gut lösen? Oder eine Searchbox?
- Das Traktandieren von Freitext / Erstellen von Abschnitten wäre eventuell klarer mit zwei separaten Eingabefeldern/Buttons?

![screen shot 2015-11-05 at 11 20 24](https://cloud.githubusercontent.com/assets/736583/10965730/3d24b8a8-83af-11e5-9aec-967f4f23f92a.png)

**Comment by phgross** [comment]
- Alphabetische Sortierung :+1:
- Auflistung: Wahrscheinlich müssen wir hier in Zukunft das GUI noch ein wenig anpassen oder verbessern. Ich erachte dies aber nicht als prioritär, und würde diese vorerst so belassen. Eine Optimierung (Combobox) oder ähnliches können wir immer noch nachliefern.
- Freitext Traktanden/Abschnitt :+1:
