### ISSUE TITLE
Buttons in Sitzungs/Protokollansicht mit Tooltips versehen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1311]
![bildschirmfoto_2015-11-09_um_14_25_53](https://cloud.githubusercontent.com/assets/485755/11034718/fc09602a-86ed-11e5-9956-414ce02ee302.png)

**Comment by phabegger** [comment]
Tooltipp-Texte:
- Ort
- Uhrzeit, separat dazu "Datum", siehe  
- Vorsitz (im obigen Screenshot nicht enthalten)
- Protokollführer (im obigen Screenshot nicht enthalten)
- Teilnehmende
- Sitzungsdossier
- Protokoll: "Neue Version als Worddokument generieren"
- Protokoll: "Protokoll herunterladen"
- Protokollauszüge: Plus-Symbol verwenden, Tooltipp = "Neuer Protokollauszug generieren"
