### ISSUE TITLE
Bilder bei Traktanden als Anhang hinzufügen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1323]
Diese Anforderung ergab sich in der Diskussion mit Benutzern. Sie arbeiten dort oft am Flipchart und machen am Schluss ein Foto, das sie unter Diskussion in das Protokoll hängen.

Das Bild müsste dann auch in das Sitzungsprotokoll rein.

**Comment by deiferni** [comment]
Mit der Umstellung auf Word nicht länger relevant.
