### ISSUE TITLE
Schatten bei aktiven dropdowns

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1330]
Sollte auch noch entfernt werden, als follow-up zu #1297

![screen shot 2015-11-11 at 14 05 31](https://cloud.githubusercontent.com/assets/736583/11091695/5efb647c-887d-11e5-8d8f-d95b515c7ba7.png)

**Comment by phgross** [comment]
Wie besprochen im Components-Mixin entfernen.

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/plonetheme.teamraum/commit/cdaabceb79ba64faeb0780eb9252450280ebfec6
