### ISSUE TITLE
Anträge müssen einzeln abgeschlossen werden können.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1356]
Aus der Sitzung-Ansicht müssen Traktanden einzeln abgeschlossen werden können.

-> Traktandum braucht auch einen Workflow
-> Referenz von Sitzung auf Periode nach Abschluss ersters Traktandum, damit weitere Traktanden in der gleichen Periode abgeschlossen werden

Abschluss heist:
 - Statuswechsel auf dem Traktandum
 - zusätzlicher Eintrag im Verlauf eines Antrages
 - Protokollauszug generieren bzw. aktualisieren und zurückspielen ins Ursprungsdossier.
 - Sitzung "beenden" falls noch nicht beendet. (Statuswechsel, Traktandenliste kann nicht mehr verändert werden).

Versandt heisst:
 - Statuswechsel auf dem Traktandum und Antrag.
 - Traktandum kann nicht mehr bearbeitet werden.

UX:
 - Weitere Aktionen in der Traktandenliste darstellen, falls für Benutzer möglich.

![bildschirmfoto_2015-11-16_um_11_43_32](https://cloud.githubusercontent.com/assets/485755/11180119/91c4a4d4-8c58-11e5-8558-1c04be029e1e.png)

**Comment by deiferni** [comment]
Teilweise erledigt, "wieder eröffnen" der schon abgeschlossenen Traktanden fehlt noch.
