### ISSUE TITLE
UX Antragsansicht überdenken und überarbeiten

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1358]
- Tabelle wird bei grossen Texten unübersichtlich.
- Wichtige Informationen sollten separat dargestellt werden.

**Comment by bierik** [comment]
Bitte mehr Informationen mit Screenshots. Hier ist sehr unklar in welche Richtung das Überarbeiten der Ansicht gehen soll.

@deiferni Weisst du mehr dazu?

**Comment by phgross** [comment]
Vorerst keine Anpassung geplant.
