### ISSUE TITLE
Stichwortverzeichnis implementieren

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1361]
Stichwortverzeichnis:
 - Dient als Nachschlagewerk im Papierform
 - Stichwort-Vergabe pro Geschäfte
 - Enthält:
  - Startseitennummer von der Sitzung
  - Beschlussnummer

Beispiel: https://basecamp.com/2768704/projects/7577904/todos/182940521?enlarge=164455388#attachment_164455388

**Comment by phgross** [comment]
Vorerst Konzept.

**Comment by deiferni** [comment]
Habe diesbezüglich mit Maya telefoniert. Sie schickt uns Beispieldokumente für das Stichwortverzeichnis.

**Comment by deiferni** [comment]
Gemäss erneutem Telefonat mit Maya sind Ihre Bedürfnisse mit https://github.com/4teamwork/opengever.core/issues/1373 abgedeckt (unter der Voraussetzung, dass auch Traktanden ohne Antrag ins Inhaltsverzeichnis aufgenommen werden können.
