### ISSUE TITLE
CommitteeContainer shows default byline

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1367]
The CommitteeContainer shows the default byline with creation/modification date. We should disable the byline since that information is irrelevant for us.

![screen shot 2015-11-17 at 12 23 05](https://cloud.githubusercontent.com/assets/736583/11210136/283d2292-8d26-11e5-8c17-c005f121f2b4.png)

**Comment by phgross** [comment]
:+1:
