### ISSUE TITLE
Traktandenliste generieren.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1372]
Es soll möglich sein eine Traktandenliste basierend auf einer Wordvorlage zu generieren/herunterzuladen. Diese muss nicht im Sitzungsdossier abgelegt werden.

https://feedback.onegovgever.ch/t/feedback-zur-neuen-aktuell-aufgestalteten-version-januar-2016/214

**Update**: generell scheint es sehr of der Use-Case zu sein, dass man bevor eine Sitzung startet eine Einladung/Traktandenliste/... generieren will.

**Comment by phgross** [comment]
Wurde mit #1863 implementiert.
