### ISSUE TITLE
Inhaltsverzeichnis erfassen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1373]
Es soll möglich sein Inhaltsverzeichnisse zu generieren. 
- Ordnungsposition-basiert
  - Alphabetisch
  - Nach Nummer
- Chronologisch nach Geschäft

Verwandt mit #1361.

**Comment by phgross** [comment]
Vorerst Konzept.

**Comment by deiferni** [comment]
### Umsetzungsvorschlag UI:
Neues Tab `Perioden` auf dem Gremium, dort werden alle Perioden dargestellt  inklusive Links für die Generierung von Inhaltsverzeichnissen

### Alphabetisch
- Gruppiert nach erstem Buchstabe/Ziffer des Antragstitel
- Sortiert nach Antragstitel
- Spalten:
  - Ordnungsposition Nr. des Ursprunggeschäfts
  - Antragstitel 
  - Sitzungsdatum 
  - Beschlussnummer
  - Seitennummer (Start der Sitzung)

### nach Ordnungsposition
- Sortiert alphabetisch nach Ordnungspositionstitel
- Gruppiert nach Ordnungsposition
- Spalten
  - Titel Ordnungssposition
  - Ordnungsposition Nr. des Ursprunggeschäfts
  - Antragstitel 
  - Sitzungsdatum 
  - Beschlussnummer
  - Seitennummer (Start der Sitzung)

### Weiteres
- Vorlage als neues Sablontemplate hinterlegen
- Dokument muss nicht in GEVER abgelegt werden, nur download
- Keine Seitennummerierung der Verzeichnisse nötig

**Comment by deiferni** [comment]
update: beim alphabetischen Inhaltsverzeichnis sollten auch Traktanden ohne Antrag berücksichtigt werden.
