### ISSUE TITLE
Protokollauszug Generieren: Auswahl des Zieldossiers nicht möglich

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1383]
Die Auswahl des Zieldossiers ist nur via Autocomplete Widget möglich. Die Anzeige der Baumstruktur wirft ein Fehler (siehe Anhänge).
![bildschirmfoto 2015-11-23 um 09 08 04](https://cloud.githubusercontent.com/assets/485755/11332019/02b31e82-91c2-11e5-9a2a-ede295074f9c.png)
![bildschirmfoto 2015-11-23 um 09 08 20](https://cloud.githubusercontent.com/assets/485755/11332018/02ac9116-91c2-11e5-848c-b283520d639c.png)

Bsp: https://lab.onegovgever.ch//sitzungen/committee-3/meeting-4/generate_excerpt

**Comment by deiferni** [comment]
Das Widget wird beim traversieren nicht gefunden. Das Problem kommt mir bekannt vor, kann mich aber nicht mehr an die Lösung erinnern. Weiss einer von euch mehr?

```
2015-11-24T15:13:13 ERROR Zope.SiteErrorLog 1448374393.320.148836206313 https://lab.onegovgever.ch/sitzungen/committee-3/meeting-10/generate_excerpt/++widget++form.widgets.dossier/@@contenttree-fetch
Traceback (innermost last):
  Module ZPublisher.Publish, line 70, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.formwidget.contenttree.widget, line 65, in __call__
  Module plone.formwidget.contenttree.widget, line 57, in validate_access
  Module OFS.Traversable, line 317, in restrictedTraverse
  Module OFS.Traversable, line 300, in unrestrictedTraverse
   - __traceback_info__: ([], '++widget++form.widgets.dossier')
AttributeError: ++widget++form.widgets.dossier
```

**Comment by deiferni** [comment]
Ich kann das Problem lokal nicht mehr reproduzieren. Nach dem update nochmals auf lab probieren.

**Comment by phgross** [comment]
https://lab.onegovgever.ch/sitzungen/committee-3/meeting-2/generate_excerpt

**Comment by bierik** [comment]
Kann das Problem lokal und auf lab nicht mehr reproduzieren.

**Comment by deiferni** [comment]
Lässt sich nicht mehr reproduzieren.
