### ISSUE TITLE
Growl-style message beim Speichern des Protokolls schlecht sichtbar

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1400]
die message zum erfolgreichen speichern des protokolles sollte als plone portal message dargestellt werden. die growl-style message ist viel zu kurz sichbar, da direkt nach dem darstellen ein neuer pageload ausgelöst wird.

![untitled](https://cloud.githubusercontent.com/assets/736583/11532001/1dde808e-9901-11e5-8c26-568a472538b2.gif)

**Comment by bierik** [comment]
Lösung in https://github.com/4teamwork/opengever.core/issues/1405 formuliert
