### ISSUE TITLE
Umbau von Speichern und Abbrechen Workflow für Protokoll

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#1405]
Speichern -> Auf meetingansicht
Verwerfen -> local storage leeren, auf meetingansicht
Schliessen -> auf meetingansicht

![bildschirmfoto 2015-12-03 um 11 30 21](https://cloud.githubusercontent.com/assets/1637820/11558159/46957220-99b1-11e5-971b-e8cf8ab51b82.png)

**Comment by phgross** [comment]
Wie besprochen :+1: 

Bitte nicht das Glocken Symbol verwenden, dies wird schon bereits für Benachrichtigungen verwendet.

Vielleicht eher sowas:
 - http://fortawesome.github.io/Font-Awesome/icon/exclamation-circle/
 - http://fortawesome.github.io/Font-Awesome/icon/exclamation-triangle/

**Comment by bierik** [comment]
@phgross Ja genau ich bin auch für die anderen Icons ich habe diese nur nicht gefunden :laughing:
