### ISSUE TITLE
Aktuelles Subdossier in Subdossier Auflistung enthalten

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1407]
Bei mehreren Subdossier Levels wird bei der Subdossiers Auflistung fälschlicherweise der aktuelle Kontext (Sudossier) auch aufgelistet.

![14-09-2015 14-27-06 1](https://cloud.githubusercontent.com/assets/485755/11594309/8f65922a-9aa9-11e5-899f-22d0aad29e98.jpg)

Befindet man sich auf einem Hauptdossier, so tritt dieses Problem nicht auf. Weil Hauptdossiers durch de `is_subdossier` Filter limitiert werden (siehe https://github.com/4teamwork/opengever.core/blob/master/opengever/tabbedview/browser/tabs.py#L199).

*Rapportierung:* `[INTERN] 3.2 OneGov GEVER  - Weiterentwicklung (Enhancement/Feature)`

**Comment by maethu** [comment]
@phgross Das Problem ist hier, dass der Catalog nicht anderes kann. 
Die einzige Lösung, welche ich sehe ist, dass noch einmal über das ganze Resultset iteriert wird und das entsprechende `brain` entfernt wird.

Nachteil:
- Nicht mehr lazy, also Performance.

Bei field, date und keyword indexes wäre ein `not` query möglich. Jedoch nicht bei path und uid index.

**Comment by phgross** [comment]
Sehe ich gleich,  ich schliesse diesen Issue.
