### ISSUE TITLE
Eingangskorb für Eingangskorb Benutzer editierbar

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1408]
Benutzer mit der Berechtigung auf den Eingangskorb  können diesen auch bearbeiten. Dies sollte vom System verhindert werden. 

Hinweis: Dies kann aber nicht über die `Modify Portal Content` Permission gesteuert werden, da Dokumente im Eingangskorb ja weiterhin editierbar sein müssen (Der Dokument Workflow aquired die `Modify Portal Content` Permissions)

Ref: https://extranet.4teamwork.ch/support/gever-ai/tracker/231

**Comment by maethu** [comment]
@phgross Wie stellt stellt man sich hier die Lösung vor?
IMHO muss  das über den Workflow gesteuert werden, also muss der Eingangskorb einen Placefulworkflow haben.
Dadurch muss die `Modify portal content` permission nicht mehr vererbt werden, sondern kann neu vergeben werden. 

Alternativ könnte die edit view vom Eingangskorb geschützt werden, dies würde aber nur die `View` schützen und nicht den Inhalt selbst.

**Comment by phgross** [comment]
@maethu wieso einen Placefulworkflow? Es handelt sich ja um separate Typen mit separaten Workflow. Wäre es nicht möglich eine seperate Edit Permission für Eingangskörbe `opengever.inbox.EditInbox` einzuführen?

**Comment by deiferni** [comment]
Der Wunsch besteht weiterhin (https://extranet.4teamwork.ch/support/gever-ai/tracker/231), ich denke wir sollten die Diskussion hier nochmals kurz aufnehmen, das Verhalten ist ja schon eher unschön. Separate edit permission könnte funktionieren 🤔.

Ich nehms zur Diskussion auf den nächsten Release.

**Comment by maethu** [comment]
@phgross @deiferni

Ich bin ein Fan vom Placefulworkflow:

Vorteile:
- Änderungen an den Berechtigungen vom default Workflow haben keinen Einfluss  auf den diesen Workflow. (dies kann auch als Nachteil ausgelegt werden, IMHO ist das aber ein Vorteil).
- Man die Möglichkeit das Verhalten nur in diesem Bereich anzupassen. 
- Explizite Trennung.
- Lawgiver?

Nachteil:
- Migration/Upgrade dauert länger.

**Comment by phgross** [comment]
@maethu Placefullworkflow ist ja gut und recht (setzen wir bei opengever.private auch ein), aber ist ja ein separater Typ, deshalb mein Frage https://github.com/4teamwork/opengever.core/issues/1408#issuecomment-302447514

**Comment by phgross** [comment]
Entscheid (nach Gespräch mit Jones): 

Für die Inbox soll ein PlacefulWorkflow mit eigenem Dokumentworkflow implementiert werden. Folgendes gilt es dabei zu beachten.
 - `Modify Portal Content` auf dem Eingangskorb nur noch für Manager
 - `inbox_document_workflow` vererbt die Permission `Modify Portal Content` nicht mehr, sondern vergibt sie der Rollen `Manager`, `Administrator` und `Editor`
 - Dokumente innerhalb eines `Jahresordner` sollen nicht mehr bearbeitet werden können
 - Beim Zuweisen einer Weiterleitung an ein Dossier (Dokumente werden kopiert) muss sichergestellt werden, dass die Dokumente den Standard Dokumenten Workflow besitzen.
