### ISSUE TITLE
Eingereichte Dokumente zur Bearbeitung sperren

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1421]
Eingereichte Dokumente sollen irgendwie als solche gekennzeichnet werden, also als *Kopie*. Sonst ist das verwirrend. Mindestens sollten sie nicht bearbeitbar sein.

**Comment by deiferni** [comment]
Vorschlag, Dokument mit eigenem Lock sperren und Hinweistext analog zum Protokoll einer Sitzung
![screen shot 2016-05-31 at 11 43 57](https://cloud.githubusercontent.com/assets/736583/15670335/2b911482-2725-11e6-9f97-f0de9d93e489.png)

@phgross wie siehst du das?

**Comment by phgross** [comment]
Finde dein Vorschlag (Hinweistext) so ok. Wie würdest du das "eigene Lock" implementieren ?

**Comment by deiferni** [comment]
@phgross analog https://github.com/4teamwork/opengever.core/pull/1622
