### ISSUE TITLE
E-Mail Adressen der Benutzer im Protokoll anzeigen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1426]
Die erfassten E-Mail Adressen der Benutzer soll zu Identifikationszwecken dargestellt werden.

**Comment by elioschmutz** [comment]
@deiferni 

Grundsätzliche Frage: mit oder ohne mailto?

Zum Format habe ich 4 verschiedene Varianten:

V1
---
<img width="587" alt="bildschirmfoto 2016-02-25 um 10 51 38" src="https://cloud.githubusercontent.com/assets/557005/13316015/46f0d400-dbae-11e5-8845-7017f120d414.png">

V2
---
<img width="609" alt="bildschirmfoto 2016-02-25 um 10 51 56" src="https://cloud.githubusercontent.com/assets/557005/13316014/46f04972-dbae-11e5-83f7-83ccc72f9338.png">

V3
---
<img width="577" alt="bildschirmfoto 2016-02-25 um 10 53 01" src="https://cloud.githubusercontent.com/assets/557005/13316034/59b047f6-dbae-11e5-80f7-79f53531b0af.png">

**Comment by deiferni** [comment]
Ich würde V1 mit link wählen
