### ISSUE TITLE
Nicht eingereichte Anträge im Dossier führen zu Fehler in Darstellung

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#1435]
https://lab.onegovgever.ch/ordnungssystem/raumplanung-bau-und-verkehr/hochbau/bewilligungs-und-bauverfahren/dossier-100#proposals

Endlosschlaufe.

**Comment by deiferni** [comment]
Danke fürs rapportieren!

Ist schon mit #1419 erfasst.
