### ISSUE TITLE
Fehler beim Hinzufügen einer Sitzung

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#1442]
User: sandro.ackermann
URL: https://lab.onegovgever.ch/sitzungen/committee-23

Reproduktion
1. Hinzufügen "Sitzung"
2. Datum eingeben
3. Weiter
:boom: 

Errör: 1449659302.280.0970456018537

**Comment by deiferni** [comment]
Danke fürs Reporten! :green_heart: 

Das ist ein Folgefehler von #1415, es können im Moment Kommissionen mit einer nicht-Leaf-Ordnungsposition erstellt werden, ohne, dass die Validation fehlschlägt. Die Ordnungsposition wird dann jedoch nicht persistent gespeichert.
Lösung: Kommission editieren und Leaf-Ordnungsposition auswählen. Fix mit Validation ist in Arbeit.
