### ISSUE TITLE
Komisches Verhalten beim Bearbeiten von einer Kommission

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#1444]
Der Wert vom Feld `Ablageposition`geht verloren. 

1. Neue Kommission hinzufügen
2. Kommission bearbeiten -> Titel anpassen.
3. Speichern
Ergibt:
![screen shot 2015-12-09 at 12 02 52](https://cloud.githubusercontent.com/assets/437933/11683860/f7c5f52c-9e6d-11e5-93cc-0da231e12392.png)

**Comment by deiferni** [comment]
Danke fürs Reporten! :green_heart: 

Das ist ein auch Folgefehler von #1415 :wink: , siehe auch Kommentar bei #1442. Mit einem korrekten Validator sollte das Problem bald gelöst sein.
