### ISSUE TITLE
Link vom Antrag zur Sitzung

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#1455]
Es wäre hilfreich, wenn man vom Antrag direkt auf das Gremium und die Sitzung verlinken könnte.
<img width="1006" alt="bildschirmfoto 2015-12-09 um 20 24 51" src="https://cloud.githubusercontent.com/assets/1231822/11696154/2eb98b3a-9eb3-11e5-97c1-5a1af06c8714.png">

**Comment by bierik** [comment]
@deiferni @phabegger Wie relevant ist diese Ansicht noch? Der Titel des Traktandums (Antrag) kann auf der Sitzung bearbeitet werden. Auch der Inhalt der jeweiligen Anträge ist im Protokoll ersichtlich und auch nur dort bearbeitbar? Welche Vorteile bringt diese Ansicht also noch?

**Comment by deiferni** [comment]
Die Ansicht ist immer noch relevant fürs initiale Erstellen des Antrags im Dossier. Dann kann man den Antrag noch nicht im Protokoll bearbeiten, weil er noch gar nicht eingereicht ist und daher auch nicht für eine Sitzung traktandiert sein kann.

**Comment by phabegger** [comment]
Diese Ansicht steht auch innerhalb eines Dossiers (im Ordnungssystem) zur Verfügung. Dort, wo der Antrag ursprünglich erfasst und eingereicht wurde. Von daher ist eine Verlinkung zur entsprechenden Kommission in der SVP sinnvoll.
