### ISSUE TITLE
Debugview für ProtocolData

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1462]
Es wäre toll wenn es auf einer Sitzung die Möglichkeit gäbe, die `ProtocolData` zu lesen, also das JSON welches dann auch dem Sablon übergeben wird. 
So könnten man bei Problem bei der Generierung, schneller und besser analysieren wo das Problem liegt.

Das ganze natürlich nur mit ModifyPortalContent Berechtigung.

**Comment by deiferni** [comment]
ganz genau das gibt es schon :smile: die view heisst `download_protocol_json`

https://github.com/4teamwork/opengever.core/blob/f5803d9ffed129afc6cf2a9d79f5e8d71a0037d9/opengever/meeting/browser/meetings/protocol.py#L93-L102

**Comment by phgross** [comment]
Hehe good to know! Merci
