### ISSUE TITLE
Policy template placeholder ersichtlich

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1463]
Das file `upgrades/configure.zcml` wird evtl. nicht ganz korrekt gerendert, die i18n-domain ist falsch.

```<configure
    xmlns="http://namespaces.zope.org/zope"
    xmlns:genericsetup="http://namespaces.zope.org/genericsetup"
    xmlns:upgrade-step="http://namespaces.zope.org/ftw.upgrade"
    i18n_domain="opengever.{{package.name}}">```

**Comment by elioschmutz** [comment]
Ist bereits so umgesetzt.

https://github.com/4teamwork/opengever.core/blob/master/opengever/policytemplates/policy_template/opengever.%2Bpackage.name%2B/opengever/%2Bpackage.name%2B/upgrades/configure.zcml.bob
