### ISSUE TITLE
Alle policies überprüfen und im initial-content title_de korrekt setzen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1472]
Ist im moment noch nicht überall korrigiert. gewisse inhalte sind nun übersetzt und sollten anstatt ein `title` ein `title_de` attribut haben.

**Comment by elioschmutz** [comment]
Zu überprüfende Policies:

- [ ] opengever.ai
- [ ] opengever.bs
- [ ] opengever.demo
- [ ] opengever.duerrenaesch
- [ ] opengever.edk
- [ ] opengever.framsteg
- [ ] opengever.ftw
- [ ] opengever.hpcdual
- [ ] opengever.htwchur
- [ ] opengever.kgkoeniz
- [ ] opengever.liesberg
- [ ] opengever.mumpf
- [ ] opengever.nidau
- [ ] opengever.phbern
- [ ] opengever.phvs
- [ ] opengever.sg
- [ ] opengever.sgdemo
- [ ] opengever.zug
- [ ] opengever.walenstadt
- [ ] opengever.koeniz

**Comment by elioschmutz** [comment]
Alle Policies sind angepasst.
