### ISSUE TITLE
Anzeige Dateigrösse (max) und die tatsächliche Gesamtgrösse gleich mit der Fehlermeldung

### ISSUE THREAD

**Issue by mtokmak** [4teamwork/opengever.core#1479]
Beim Versenden eines E-Mails via GEVER kommt eine Fehlermeldung, falls die Dateigrösse bzw. die tatsächliche Gesamtgrösse des E-Mails überschritten wird. Dem Benutzer fehlen jedoch diese Informationen (z.B. höchstens 5MB etc.).

![bildschirmfoto 2015-12-14 um 15 41 23](https://cloud.githubusercontent.com/assets/2045638/11817020/529232ce-a353-11e5-925a-0e77f88f523a.png)

Diese könnten bei der Fehlermeldung direkt angezeigt werden.

**Comment by phgross** [comment]
Zur Info: die maximale Versandgrösse ist konfigurierbar via plone registry.

**Comment by tarnap** [comment]
Here's the list of documents:
https://github.com/4teamwork/opengever.core/blob/master/opengever/mail/browser/send_document.py#L96

@phgross 
I propose to display the size of the documents and the maximum size.
Optionally the user can be warned if the files exceed the quota.

**Comment by tarnap** [comment]
After discussing this issue with @buchi :
Wait for `ftw.referencewidget` since the actually used widget is / will be deprecated / obsolete.
