### ISSUE TITLE
Add configurable administrator_group

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1492]
Usually we want to assign the Administrator role to a group in `portal_rolemanager.` A rolemanager_group is already configured in `opengever:registerDeployment` for each policy.

**Comment by phgross** [comment]
There is already a configuration option `administrator_group` on the `registerDeployment` directive.

See https://github.com/4teamwork/opengever.core/blob/master/opengever/setup/meta.py#L73
