### ISSUE TITLE
Verwandte Dokumente "bidirektional" anzeigen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1498]
Siehe Diskussion unter https://feedback.onegovgever.ch/t/verwandte-dokumente/167

Die Verwandtschaft von Dokumenten soll auf beiden Seiten angezeigt werden (unter verwandte Dokumente).

**Comment by phgross** [comment]
Für Dossiers wurde dies bereits umgesetzt, bitte auch für Dokumente in der Dokument-Detailansicht umsetzten:

![bildschirmfoto_2017-06-23_um_08_35_03](https://user-images.githubusercontent.com/485755/27469278-e9c4d2b8-57ee-11e7-9411-0923f5c134bf.png)
