### ISSUE TITLE
Verwandte Dokumente/Dossiers: Verlinkungen werden auf beiden Seiten angezeigt, sind aber nicht beidseitig editierbar

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1500]
Vorschlag: Das Widget zur Darstellung von Verknüpfungen im Bearbeitungsmodus so  erweitern, dass auch Verknüpfungen read-only dargestellt werden, die auf den aktuell bearbeitenden Inhalt zeigen.

Konkret: 
- Ich habe Inhalte A und B, wobei A eine Verknüpfung auf B gespeichert hat. In den Ansichten von A und B wird jeweils eine Verknüpfung auf B bzw. A angezeigt. 
- Bearbeite ich Inhalt B, wird keine Verknüpfung angezeigt, die ich bearbeiten kann (was technisch auch korrekt ist). 
- Gut wäre, wenn in diesem Fall zusätzlich auch die Verknüpfung A -> B angezeigt wird (nicht veränderbar).

Die beidseitige Darstellung von Verknüpfungen wurde in den Tickets #1498 und #841 diskutiert und teilweise umgesetzt.

**Comment by phgross** [comment]
Bei Dossiers wird die Verlinkung bereits auf beiden Seiten dargestellt. Bei Dokumente müsste dies noch angepasst werden.

**Comment by phgross** [comment]
Die Darstellung der verwandten Dokumente wird im Ticket #1498 behandelt. Ich schliesse diesen Issue.
