### ISSUE TITLE
Aktuelle Datetime Widget Implementation an die neue Clientsetige Implementation anpassen.

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#1501]
Die jetzige Widget Impelmentation im Plone kann nicht mit den Anforderungen von https://github.com/4teamwork/opengever.core/issues/1073 umgehen. Die Clientseitige Implementation löst das Problem im UI und überträgt danach die Daten in die jetzige HTML Struktur des Widgets -> https://github.com/4teamwork/opengever.core/pull/1474. Die neue Lösung soll nur noch ein Feld beinhalten. Die Eingabe geschieht durch ein Datetimepicker Widget auf dem Client und soll danach im Backend als Python Object parsed werden.
Um das Widget Serverseitig zu konfigurieren können `data` Attribute verwendet werden.

**Comment by phgross** [comment]
Überprüfen ob ftw.calendarwidget mittlerweile auch datetime anbietet, soviel ich weiss hat @mbaechtold hier eine Anpassung vorgenommen.

**Comment by mbaechtold** [comment]
@phgross, meinst du vielleicht eher `ftw.datepicker` (siehe https://github.com/4teamwork/ftw.datepicker/blob/master/docs/HISTORY.txt#L24)?

**Comment by phgross** [comment]
Ja genau, danke!

**Comment by phgross** [comment]
Wird mit #2587 umgesetzt.
