### ISSUE TITLE
Filename bei ZEM-Download mitliefern

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1502]
Damit der Office Connector zuverlässig die Applikation für das Dokument bestimmen kann, muss dieser den Dateinamen von GEVER erhalten, statt bloss den MIME-Type (die Zuordnung MIME-Type -> Extension kann mehrdeutig sein).

Dazu muss in GEVER die View überschrieben werden, welche die `*.zem` Datei erzeugt, so dass der Filename ebenfalls übermittelt wird.

@senny @buchi

Habt Ihr eine Präferenz wie genau diese Anpassung vorgenommen wird?

(Hier ein `*.zem` als Beispiel):

```
url:https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-16/document-33
meta_type:Dexterity Item
title:Mein Dokument
content_type:application/vnd.openxmlformats-officedocument.wordprocessingml.document
cookie:<guezlis>

<binary>
```

Ich sehe spontan zwei Möglichkeiten:

- Ein weiteres Feld `filename:` einführen
  - Führt dies zwangsläufig zu Inkompatibilität mit dem klassischen External Editor?
  - Falls ja, ist das für uns relevant?
- Eine URL wie z.B. `http://.../dossier-16/document-33/mein_dokument.docx` ausliefern, und in GEVER die entsprechenden Anpassungen vornehmen, dass eine solche auch funktioniert (ein WebDAV PUT müsste z.B. immer noch am richtigen Ort landen)

**Comment by senny** [comment]
@lukasgraf Für mich wäre klar ein Feld `filename` zu bevorzugen.

**Comment by lukasgraf** [comment]
Tendiere auch dazu, ist auf Seite GEVER definitiv viel einfacher umzusetzen.
