### ISSUE TITLE
Fehlerhafte Nummerierung beim Protokoll (Word)

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#1511]
Beim Generieren des Protokolls mit Sablon werden die Abschnitte mit nummeriert nicht aber im Inhaltsverziechnis.

[Protokoll-guggershornli-15-12-2015.docx](https://github.com/4teamwork/opengever.core/files/82812/Protokoll-guggershornli-15-12-2015.docx)

**Comment by deiferni** [comment]
Sobald die Sitzung abgeschlossen ist, oder ein Traktandum beschlossen wurde stehen die Nummern zur verfügung und werden auch wie erwartet in die Dokumente eingefügt. (Dies ist so korrekt).
