### ISSUE TITLE
Keine Berechtigung auf Kommission nach: "Hinzufügen -> Kommission -> Speichern"

### ISSUE THREAD

**Issue by senny** [4teamwork/opengever.core#1512]
Ich hatte heute auf https://lab.onegovgever.ch folgende Situation:

1. Anmelden als `yves.senn`
2. https://lab.onegovgever.ch/sitzungen
3. Hinzufügen -> Kommission
4. Formular ausfüllen + Speichern
5. Unzureichend Berechtigungen

Also ich konnte zwar eine neue Kommission erfassen. Diese wurde gespeichert (habe ich als `zopemaster` geprüft). Nach dem Speichern kann ich aber meine Kommission nicht anzeigen.

### Erwartung

Mir sollte "Hinzufügen Kommission" nicht zur Verfügung stehen oder meine erstellte Kommission sollte für mich sichtbar sein. Falls die Berechtigung hier über die LDAP-Gruppe geht sollte ich nur meine Gruppen wählen können.

**Comment by deiferni** [comment]
:+1: danke fürs raportieren, ja da besteht noch optimierungsbedarf

**Comment by elioschmutz** [comment]
@senny 
Kannst du das bitte nochmals überprüfen?
Ich kann diesen Fehler nicht mehr reproduzieren. Evt. wurde dieser schon behoben...

**Comment by senny** [comment]
@elioschmutz also ich hab das Problem nach wie vor...

**Comment by deiferni** [comment]
@elioschmutz das problem besteht noch, du musst die kommission für eine gruppe erstellen, der du nicht angehörst.

**Comment by elioschmutz** [comment]
@deiferni 

Den Issue werde ich folgendermassen lösen:
- Es können nur Gruppen ausgewählt werden, bei denen ich selbst ein Mitglied bin

Ein möglicher Usecase welcher dabei **nicht** mehr funktionieren würde, wäre:
- Ein Sachbearbeiter möchte ein Gremium für Bereichsverantwortliche erstellen.

Sofern dies OK ist, werde ich mit der Umsetzung beginnen.

**Comment by deiferni** [comment]
@elioschmutz ja das ist zu erwarten und stimmt für uns so
