### ISSUE TITLE
Protokoll-Download vs Protokoll-Vorschau/Debugging

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1515]
Der Download-Button könnte für die User verwirrend sein, weil er nicht den aktuellen Stand herunterlädt, sonder das Dokument neu rendert. So kann man u.U einen neuern Stand erhalten als im Moment in Gever gespeichert.

![screen shot 2016-01-11 at 10 20 33](https://cloud.githubusercontent.com/assets/736583/12230022/75a47592-b84d-11e5-9386-3109153b00b4.png)

Wir sollten die Funktionen "download" und "preview"/debugging für admins trennen.
cc @senny

**Comment by senny** [comment]
Ich finde für den Benutzer sollte es nur die Funktionen "Aktualisieren" und "Download" geben. Diese würden sich wie folgt verhalten:

**Aktualisieren:** Generiert das Dokument mit Sablon und speichert eine neue Version im GEVER ab.
**Download:** Lädt die neuste Version des Dokuments im GEVER herunter

So sollte keine Verwirrung entstehen. Für Entwickler und Administrationen könnte man sich eine "Preview" / "Dry Run" Funktion überlegen. Diese würde das Dokument generieren und direkt zum Browser senden, ohne etwas im GEVER abzulegen.
