### ISSUE TITLE
Fehlende Übersetzung 

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1518]
![screen shot 2016-01-11 at 17 34 10](https://cloud.githubusercontent.com/assets/736583/12239557/922637e6-b889-11e5-8e9a-6e755735e891.png)

**Comment by bierik** [comment]
Will be fixed through https://github.com/4teamwork/opengever.core/pull/1487/files#diff-dd7bc7d8623cb98c4757cfcf60faebcaL908
