### ISSUE TITLE
Status von Sitzungen darstellen

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#1526]
Bei meinen Demos ist es immer wieder vorgekommen, dass ich auf eine abgeschlossene Sitzungen gestossen bin und keien Traktanden hinzufügen konnte.

Der Status einer Sitzung sollte ersichtlich sein, sowohl in der Übersicht
(nächste Sitzungen) sowie in der Tabbed View.

![bildschirmfoto 2016-01-14 um 10 34 40](https://cloud.githubusercontent.com/assets/1231822/12320867/5994c69e-baab-11e5-93dc-aa448f9141de.png)
![bildschirmfoto 2016-01-14 um 10 39 34](https://cloud.githubusercontent.com/assets/1231822/12320868/599ada70-baab-11e5-84dc-a9d2eea95882.png)

**Comment by phabegger** [comment]
Dieser Punkt wurde bereits im [Feedback-Forum](https://feedback.onegovgever.ch/t/sitzungsstatus-in-der-sitzungsuebersicht-tabelle/204) gemeldet.

**Comment by elioschmutz** [comment]
@deiferni @phabegger @bbuehlmann @lukasgraf 

Der Status wurde bereits in das Sitzungs-Tab integriert.
=> siehe PR #1520

Für Sitzungen welche in der Box "Kommende Sitzungen" angezeigt werden, wird der Status noch nicht angezeigt.

Macht es Sinn, den Status bei den kommenden Sitzungen anzuzeigen?
Kommende Sitzungen sollten ja grundsätzlich im Status ``in Bearbeitung`` sein.
Für ältere Sitzungen besteht ja das Tab "Sitzungen" in welchem nach dem Status gefiltert werden kann.

Ich denke, dass diese Information im Übersichtstab nicht relevant ist und so die Übersicht unnötig überladen würde.

Was meint ihr dazu?

**Comment by deiferni** [comment]
:+1: Ich würde es auf der Übersicht vermutlich auch weglassen, du hast Recht, die Sitzungen sind ja höchstwarscheinlich alle `in Bearbeitung`. Wenn man mehr wissen will, erreicht man das Sitzungstab schnell über die Tabauswahl, oder über `mehr Anzeigen`.
