### ISSUE TITLE
Error-Reporting remote requests

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1541]
Wir haben mehrmals die Erfahrung gemacht, dass das error-reporting bei den remote-requests mangelhaft ist. Dies macht das debugging sehr mühsam.

Zwei Beispiele:
https://github.com/4teamwork/opengever.core/blob/master/opengever/task/browser/accept/utils.py#L152-L155
https://github.com/4teamwork/opengever.core/blob/4.5-stable/opengever/base/request.py#L29

Das Logging sollte verbessert werden und mehr Informationen zu den möglichen Fehlern liefern.

**Comment by phgross** [comment]
@deiferni was genau soll hier verbessert werden. 

Bei Problemen bei remote_requests ist es jeweils so, dass der hilfreiche Traceback jeweils im Log des fremden Mandanten landet.

**Comment by deiferni** [comment]
@phgross ganz genau. Es ist jeweils sehr umständlich die fehlgeschlagenen Remote-Requests aufgrund der Logs zu analysieren. Ich sehe hier 2 Möglichkeiten:
- Mehr infos über den Request loggen, sollte er fehlschlagen (admin-unit-id, target-view)
- Auf Seite der target-view nicht nur eine `OK` Response zurückgeben, sondern im Fehlerfall mehr Informationen zum Fehler, so dass diese dann anschliessend auch auf der anderen Seite des Requests geloggt werden können

**Comment by lukasgraf** [comment]
Sehr viel könnte schon dadurch erreicht werden, dass der response body in eine Variable im lokalen Scope extrahiert wird, z.B. in [`opengever.base.browser.wizard.storage`](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/browser/wizard/storage.py#L91-L93):

statt

```python
        if response.read().strip() != 'OK':
````
z.B. so:

```python
        response_body = response.read()
        if response_body.strip() != 'OK':
```

Dann schreibt **Sentry** den Inhalt von `response_body` gleich in's Event, und man hat die wichtigste Information zum debuggen schon mal. Das sieht dann z.B. so aus: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3129/events/88432/

(Siehe `response_body` in den locals unter dem Code, über dem Traceback ("Show more"))

**Comment by maethu** [comment]
@deiferni 
Ich habe [hier](https://sentry.4teamwork.ch/sentry/exceptiontest/issues/3209/) den traceback vom remote system als message hinzugefügt. Geht das in die richtige Richtung?

**Comment by deiferni** [comment]
as discussed:
- add a decorator on the receiver side, if possible
- also log to sentry on the receiver side

**Comment by maethu** [comment]
> as discussed:
> 
> - add a decorator on the receiver side, if possible
> - also log to sentry on the receiver side

Is implemented in #2958

**Comment by deiferni** [comment]
Closed by https://github.com/4teamwork/opengever.core/pull/2958
