### ISSUE TITLE
Antrags-Tab funktioniert nicht für grosse Anträge

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1542]
Da wir neu Markup darstellen kann die Tabelle nun recht komisch daherkommen:

![screen shot 2016-01-20 at 16 20 55](https://cloud.githubusercontent.com/assets/736583/12453078/d9f83f56-bf91-11e5-81e6-22c663a2a74d.png)

**Comment by lukasgraf** [comment]
Die Detailansicht für einen Antrag hat ein ähnliches Problem. Da wird aufgrund der zweispaltigen Darstellung sehr viel Platz verschenkt für Anhänge, dieser Platz würde besser für das Markup genutzt:

![proposal](https://cloud.githubusercontent.com/assets/405124/12556359/b5fc2b88-c385-11e5-8b43-c51fdda80e65.png)

**Comment by deiferni** [comment]
Auf Übersicht Spalten Ausgangslage und Antrag entfernen. Dafür neue Spalten hinzufügen:
- Laufnummer des Antrags (analog Dokument). 
- Link zur Sitzung, falls traktandiert
