### ISSUE TITLE
Policytemplate - Defaultwerte und Beschreibungen verbessern

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1545]
Die Beschreibungen und Defaultwerte beim erstellen einer Policy sind momentan nicht so hilfreich.
- [ ] Defaultwerte und Beschreibungen verbessern

**Comment by elioschmutz** [comment]
Übersicht der momentanen Attribute mit Beschreibung und Defaultwerte:

- Package title (e.g.: OneGovGever - customer foo): Example City
- Package name (opengever.PACKAGE_NAME): examplecity
- Package URL [https://github.com/4teamwork/opengever.examplecity]:
- Domain: examplecity.ch
- AdminUnit title [examplecity]:
- AdminUnit abbreviation [examplecity]:
- AdminUnit id [examplecity]:
- AdminUnit public_url [https://examplecity.ch]:
- AdminUnit site_url [https://examplecity.ch]: i
- AdminUnit IP: i
- OrgUnit title [examplecity]:
- OrgUnit id [examplecity]:
- Users group [og_examplecity_benutzer]:
- Inbox group [og_examplecity_sekretariat]:
- LDAP ou name [OpenGeverexamplecity]:
- Rolemanager group [og_examplecity_leitung]:
- Mail domain [examplecity.ch]:
- Mail from address [info@examplecity.ch]:
- Enable the casauth plugin? [False]:
- Enable tree favorites [False]:
- Enable activity feature [False]:
- Enable meeting feature [False]: true
- Enable docproperty feature [False]:
- Number of initial templates [0]:
- Maximum repository depth [3]:
- Reference prefix starting point [1]:
- Reference number formatter (dotted|grouped_by_three|no_client_id_dotted) [dotted]:
- Maximum dossier depth [1]:
- Maximum mail size (MB) [5]:
- "Preserved as paper" default [True]:

@deiferni Kannst du bitte die gewünschten Defaultwerte der Attribute bestimmen damit ich diese dann im Template übernehmen kann.

**Comment by phgross** [comment]
Ich habe gerade das `bin/generate-policy` durchgespielt, m.E. sind die Vorschläge ok. Die Werte werden ja in der Regel sowieso durch den PL definiert und in den Konfigurationsdateien festgehalten
