### ISSUE TITLE
Änderung Verlinkungen Office Connector in Footer

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#1550]
Verlinkungen zum Download des Office Connector anpassen (Footer), gemäss Vorschlag:

![bildschirmfoto_2016-01-22_um_10_08_36](https://cloud.githubusercontent.com/assets/11310148/12506903/86825c00-c0f2-11e5-8b54-08b68bb0e0af.png)

**Comment by phabegger** [comment]
Bitte für Mac-Version den Text auf "Office Connector (Mac)" ändern.

**Comment by phabegger** [comment]
Inzwischen nicht mehr aktuell, siehe #1715.
