### ISSUE TITLE
Refactor special handling of operations during GEVER setup to use IDuringSetup

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#1556]
Any special handling that's required for operations that happen during GEVER setup should be refactored to use the `IDuringSetup` marker interface introduced in #1510.

One such example is [disabling the creation of initial versions during setup](https://github.com/4teamwork/opengever.core/blob/60141345375b30ccf09fac33a282c2ba50b10eb3/opengever/setup/sections/versioning.py#L14-L29), there might be more.

**Comment by deiferni** [comment]
The code linked as an example has already been refactored as part of https://github.com/4teamwork/opengever.core/pull/2558

**Comment by deiferni** [comment]
Seems we've already refactored the issue, could not find any more special handling while scanning `opengever.setup`. I'll close.
