### ISSUE TITLE
Analyse/Verbesserungsvorschläge Aktenzeichen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1561]
Wie vorhin besprochen sind wir mit der Art wie Aktenzeichen generiert/gespeichert werden unzufrieden. Dazu ein paar Stichworte:
- Namen der Adapter/Interfaces sind verwirrend 
- Die API um Nummern zu setzen/generieren ist umständlich `IReferenceNumberPrefix(the_parent).set_number(the_object, number=u'7')`, besser wäre `ITheNiceInterface(the_object).set_number(7)`
- Die Nummern werden intern als String gespeichert, dies führt zu komischen Situationen so kann z.B. die Nummer `01` und `1` auf gleicher Stufe vergeben werden
- Der `ReferenceNumberPrefixAdpater` kann programmatisch schnell in einen inkonsistenten Zustand kommen weil nicht validiert wird
- Konzeptionelle Trennung zwischen Referenznummern (Daten) und Formatter (Repräsentation) ist evtl. nicht gut genug.
- Sortierung von Objekten nach Aktenzeichen: Wir haben auf den Formattern auch eine [Methode für den sort-key](https://github.com/4teamwork/opengever.core/blob/f9c3247247759f648715527eb9ce779b1efb68c4/opengever/base/interfaces.py#L110-L112) (Beispiel-[Implementierung](https://github.com/4teamwork/opengever.core/blob/f9c3247247759f648715527eb9ce779b1efb68c4/opengever/base/reference_formatter.py#L115-L143)) - diese kann im Moment aber nur Objekte mit vollständigen Aktenzeichen (Dokumente und Dossiers) sortieren, aber keine Ordnungspositionen. Evtl. wäre der bessere Ansatz, einen `sortable_reference` index zu machen in dem das AZ entsprechend Zero padded abgelegt wird.
  Uns würde eine etwas detailliertere Analyse der Situation und dann natürlich ein Verbesserungsvorschlag sehr interessieren

**Comment by jone** [comment]
Um die API und die Namen zu ändern müsste man wahrscheinlich über eine komplette Neu-Implementation nachgedacht werden, da wir nicht alles auf den Kopf stellen können ohne alles auf den Kopf zu stellen :wink: Ich bin mir nicht sicher, ob wir diese Kiste aufmachen wollen.

Grundsätzlich haben wir doch relativ viele Komponenten im Einsatz, was die ganze Aktenzeichen Geschichte nicht ganz einfach zum Verstehen macht..

--

Zum `01` vs `1` Problem:
Momentan kann `01` eingegeben werden, weil das Behavior für den Präfix ein `TextLine`-Feld definiert. Da jedoch die Zahl automatisch inkrementiert wird, müsste dies allenfalls als Text behandelt werden.

Die Frage ist, ob es Installation gibt oder geben könnte, wo der Präfix nicht aus einer Ganzzahl besteht (z.B. `1a`) und ob wir sowas überhaupt (weiterhin?) unterstützen wollen.

Wenn diese Frage mit Nein beantwortet werden kann, können wir darüber nachdenken, ob wir allenfalls das `TextLine`-Feld mit einem `Int`-Feld ersetzen. Dadurch ist `01` und `1` der gleiche Wert (da nach `int` konvertiert). Eine `01`-Darzustellen wäre weiterhin möglich, dies wäre die Aufgabe des Formatters.

**Comment by deiferni** [comment]
:coffee: heute kurz besprochen:

- Das Bedürfnis für ein Refactoring/Umbau besteht, ist jedoch im Moment nicht von extrem hoher Priorität
- Bei einem Umbau würde sich aufdrängen, dass die Nummern in Zukunft auch als solche behandelt werden können (`Int` vs `String`), dies muss zuerst abgeklärt werden
- Danach ist eine saubere konzeptionelle Trennung zwischen Formatter und Nummervergabe möglich

weiteres Vorgehen:
- ist/soll dokumentieren
- Konzept / use-cases schreiben, aus code extrahieren
- Abklärungen übers Feedbackforum

ein github Ticket ist dafür nicht mehr sinnvoll, weiteres auf einem anderen Kanal.

**Comment by lukasgraf** [comment]
Ein reines *Refactoring* der Codebasis (z.B. Renames (Klassen, Methoden), Korrigieren / Hinzufügen von Docstrings) um vorhandene Konzepte klar zu benennen und abzugrenzen, würden bereits einen grossen Gewinn mit minimalem Risiko bieten.

Ein solches Refactoring kann dann eine gute Basis für einen Umbau der Implementierung in einem späteren Schritt bilden, weil die Konzepte klarer sind.

Nur ein paar Beispiele:

`BasicReferenceNumber`

- [`append_local_number`](https://github.com/4teamwork/opengever.core/blob/b57235d43fa598baf709a6c9e49138ed080cfbba/opengever/base/reference.py#L38-L41) lügt - die Nummer wird prepended, nicht appended.
- [`get_number`](https://github.com/4teamwork/opengever.core/blob/b57235d43fa598baf709a6c9e49138ed080cfbba/opengever/base/reference.py#L23-L24) - welche Nummer genau? Viele Varianten. Datentyp?
- [`get_parent_numbers`](https://github.com/4teamwork/opengever.core/blob/b57235d43fa598baf709a6c9e49138ed080cfbba/opengever/base/reference.py#L43-L54) lügt - holt nicht nur Nummern von Parents, sondern fügt auch die eigene, lokale Nummer ein

`ReferenceNumberPrefixAdpater`

- [`get_prefix_mapping`](https://github.com/4teamwork/opengever.core/blob/b57235d43fa598baf709a6c9e49138ed080cfbba/opengever/base/adapters.py#L49-L53) - fast überall wo der Begriff `prefix` verwendet wird, ist eigentlich eine lokale Nummer gemeint (die, wenn überhaupt, ein "suffix" wäre). An anderen Ort wird das Konzept der lokalen Nummer bereits so genannt.
- [`set_number`](https://github.com/4teamwork/opengever.core/blob/b57235d43fa598baf709a6c9e49138ed080cfbba/opengever/base/adapters.py#L133-L148) - ist ein klassisches get-or-create.
- [`free_number(prefix)`](https://github.com/4teamwork/opengever.core/blob/b57235d43fa598baf709a6c9e49138ed080cfbba/opengever/base/adapters.py#L212-L220) - diese Funktion kann man benutzen, um zu prüfen ob eine Number noch frei ist, richtig?
- [`get_number`](https://github.com/4teamwork/opengever.core/blob/b57235d43fa598baf709a6c9e49138ed080cfbba/opengever/base/adapters.py#L116-L131) - `"return the reference number for the object, if no number is registred for this obj, we generate a new one."` - oh really?

Hier habe ich aufgehört, es sollte offensichtlich sein wie viel hier mit reinem Refactoring erreichbar ist, mit minimalem Risiko.

/cc @jone @deiferni

**Comment by deiferni** [comment]
äuä nid.
