### ISSUE TITLE
Detailansicht für Dokumente: Hochladen von Dokumenten per Drag'n'Drop ermöglichen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1562]
Folgender Use Case: 
- Ein bestehendes Dokument in OneGov GEVER muss durch eine externe Person überarbeitet/Korrektur gelesen/übersetzt werden. Diese Person hat keinen Zugriff auf OneGov GEVER
- Das Dokument wird deshalb durch den Benutzer per E-Mail an die externe Stelle versendet
- Das überarbeitete Dokument trifft später wieder beim Benutzer ein (E-Mail)
- Um die neue Version hochladen zu können, muss er das bestehende Dokument auschecken und in der Ansicht "Metadaten bearbeiten" eine neue Version hochladen. Am Schluss muss er das neue Dokument wieder einchecken. 

Speziell der Umweg über "Metadaten bearbeiten" ist umständlich und unlogisch. 

Wunsch: In der Detailansicht zu einem Dokument soll eine neue Version des Dokuments einfach per Drag'n'Drop hochgeladen werden können (ähnlich wie bei Dokumente-Reiter im Dossier). Der Umweg über "Metadaten bearbeiten" würde so entfallen.

**Comment by lukasgraf** [comment]
Eine mögliche Implementierung wäre also, dass das Dokument nach wie vor manuell ein- und ausgecheckt werden muss, aber im ausgecheckten Zustand das Ersetzen der aktuellen Arbeitskopie via Drag&Drop Upload durchgeführt werden kann. Danach kann das Dokument wie sonst auch eingecheckt werden, um eine neue Version zu erstellen, oder der Checkout widerrufen werden.

Ein Risiko sehe ich in im möglichen Zusammenspiel mit dem EE / OfficeConnector: Was, wenn der Benutzer das ausgecheckte Dokument sowohl mit dem EE öffnet und bearbeitet, wie auch mittels D&D upload die Arbeitskopie updated? Die eine Änderung wird zwangsläufig die andere Überschreiben, und der EE überschreibt die Arbeitskopie mit `PUT` meines Wissens auch dann, wenn er kein gültiges Lock hat (wird serverseitig von der Zope2 WebDav Implementierung nicht geprüft).

Evtl. können wir erkennen, dass eine Bearbeitung mittels EE im Moment stattfindet indem wir die Locks auf das Objekt untersuchen, und dann den D&D upload failen lassen. Aber dies ist mit einer Race-Condition verbunden, da das Lock des EE ablaufen kann, dann aber durch den EE refresht wird.  

@phabegger thoughts?

**Comment by phgross** [comment]
Mögliche Umsetzung und Konsequenzen (insbesondere bezüglich EE/OfficeConector Locks) abklären.

**Comment by phgross** [comment]
Ich habe die Funktionsweise des OfficeConnectors noch kurz mit Yves besprochen, der OfficeConnector überprüft beim Speichern/Zurückschreiben der Änderungen das Lock auf dem Server bzw. versucht es zu erneuern, falls dies nicht gelingt wird folgende Meldung dargestellt:
![bildschirmfoto 2016-04-26 um 09 26 50](https://cloud.githubusercontent.com/assets/485755/14810111/7b0be17c-0b91-11e6-9fbf-118d38bdc556.png)
Das Risiko das Änderungen, welche mit einem Drag'n'Drop Update gemacht wurden, von einer (noch) offenen OfficeConnector Session wieder überschrieben werden, ist also sehr gering, da der Benutzer mit einer entsprechenden Meldung informiert wird. Leider verhält sich der ExternalEditor diesbezüglich nicht so vorbildlich. 

Da dieses Feature primär von der EDK gewünscht und gebraucht wird (verwenden alle den OfficeConnector) und zudem in Zukunft der EE mit dem OfficeConnector abgelöst werden soll, schlage ich folgende Umsetzung vor:

- Dokument muss nach wie vor manuell aus- / und eingecheckt werden.
- Ein "ersetzen" der Datei  via Drag'n'Drop ist nur möglich solange ein Dokument vom aktuellen Benutzer ausgecheckt ist und kein aktives Webdav-Lock (OfficeConnector/ExternalEditor) für dieses Dokument ausgestellt ist.

@lukasgraf @deiferni habt ihr noch Bemerkungen/Bedenken? Würdet ihr evtl. dieses Feature mit einem Flag "schützen"?

**Comment by deiferni** [comment]
👍 
mit dem `EE` kann es ja auch nur zu Ärger kommen wenn das Webdav-Lock wegen Timeout erlischt. Soweit ich in Erinnerung habe ist dieses Timeout relativ hoch (mehrere Stunden). Weil das Dokument zusätzlich auch ausgecheckt werden muss kann es nicht sein, dass ein anderer User das Dokument "versehentlich" per D&D überschreiben kann. Ich denke die Wahrscheinlichkeit, dass es hier Konflikte gibt ist relativ klein, zudem kann ich mir gut Vorstellen, dass das Feature für alle Kunden interessant ist. Ich persönlich würde daher auf ein Flag verzichten.

**Comment by phgross** [comment]
Vorgeschlagen Umsetzung muss spät. für den Sommer Release implementiert werden.

**Comment by phgross** [comment]
@phabegger 

FYI: wir setzen dies für den Juni Release um.
