### ISSUE TITLE
Sitzung des Antrags Darstellen (Im Kommittee/Gremium)

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1566]
In der Ansicht des Gremiums im Register Antrag soll die  Ansicht um Sitzung erweitert werden

![screen shot 2016-02-01 at 14 30 37](https://cloud.githubusercontent.com/assets/736583/12718678/761b0a0a-c8f0-11e5-9180-db3cd3677d2a.png)

https://feedback.onegovgever.ch/t/feedback-zur-neuen-aktuell-aufgestalteten-version-januar-2016/214

**Comment by phgross** [comment]
Ist im April Release umgesetzt siehe https://dev.onegovgever.ch/fd/sitzungen/committee-1#submittedproposals
