### ISSUE TITLE
reference_number aus Katalog entfernen?

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#1570]
In den Katalog-Metadaten hat es eine `reference_number`.
Ich vermute dass dies nicht (mehr?) gebraucht wird, da der Wert eigentlich immer `Missing.Value` ist, zumindest bei allen meinen Stichproben.
Ich vermute wir können dies entfernen :eyes: :wink:

**Comment by deiferni** [comment]
Ja, den brauchst nicht mehr, kannst du das grad machen: :wink:?
