### ISSUE TITLE
Buildout Fehler im Zusammenhang mit plone.formwidget.autocomplete-1.2.2-20150803

### ISSUE THREAD

**Issue by slc4bfhch** [4teamwork/opengever.core#1575]
Beim Versuch gemäss Readme eine Development Installation aufzusetzen tritt bei der Ausführung von bin/buildout der folgende Fehler auf:

  Getting distribution for 'plone.formwidget.autocomplete==1.2.2-20150803'.
Error: Can't download http://psc.4teamwork.ch/dist/plone-formwidget-autocomplete/releases/1.2.2-20150803/plone.formwidget.autocomplete-1.2.2-20150803.zip: 401 Unauthorized

**Comment by phgross** [comment]
plone.formwidget.autocomplete fork is no longer used by opengever.core.
