### ISSUE TITLE
Offene Issues Translated-Title

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1589]
Dieses Ticket ist erstmal ein Container für kleinere und grössere Probleme mit dem Translated-Title:
- `obj.title` ist nun ein leerer string? ich würde eher ein property erwarten, das den titel der aktuellen sprache zurückgibt (unicode)
- `INameFromTitle` nicht überall überschrieben? (z.B. beim template-dossier)
- Zusätzliches Problem beim Repo-Folder, Titel mit/ohne Aktenzeichen.
- Repository-Folder im Excel-Sheet: `effective_title_de` vs. `title_de`

**Comment by lukasgraf** [comment]
Gedanken zu möglichen Verbesserung:

- Keine Implementierung nur für `Title`, sondern eine generische Implementierung
- Etwas wie ein `TranslatedFieldIndex`, der dann (für diesen Fall) nur `title` heissen würde, intern ein Dictionary für die indexierten Werte pro Sprache verwendet, und abhängig von der Sprache den richtigen Wert zurückgibt 
- Weg von Attributen `title_de`, `title_en` zu einem einzigen `title` Property (getter und setter), das den Wert in der richtigen Sprache liefert/setzt
- Evtl. einen eigenen `zope.schema` Feldtyp `TranslatedTextLine` - benutzt intern ein Dict, aber verhält sich sonst wie ein `TextLine` Feld
- Ein eigenes `z3c.form` Widget, das mit `TranslatedTextLine` umgehen kann
- Können wir uns evtl. an gewissen Orten `IContentListingObject` zunutze machen?

**Comment by deiferni** [comment]
Noch eine Ergänzung hierzu:

im Moment weiss ein `TranslatedTitleBrain` nicht, ob der dazugehörige Inhaltstyp übersetzt ist. Daher wird zuerst in jedem Fall versucht das übersetzten Feld auszulesen, der nicht-übersetzte `Title` ist also ein Fallback. Das ist vom Konzept her irgendwie auch nicht richtig, besser wäre einen unterschiedlichen code-path einzuschlagen abhängig von übersetztem/nicht übersetztem Inhalt.

**Comment by lukasgraf** [comment]
Ein weiteres Problem ist noch, dass auf dem Schema `ITranslatedTitle` beide Felder `required` sind, und nur auf Formular-Ebene (in `TranslatedTitleAddForm` / `TranslatedTitleEditForm`) das zweite Feld omitted wird, falls diese Sprache nicht aktiviert ist.

Dies führt dazu, dass bei programmatischer Content-Erstellung selbst dann beide Felder required sind wenn nur eine Sprache aktiviert ist.

**Comment by lukasgraf** [comment]
`self.context` auf der `TranslatedTitle` factory [wird nicht acquisition-unwrapped](https://github.com/4teamwork/opengever.core/blob/b4843a29b0c6630fa4c455b7035aabc0eaa6dc17/opengever/base/behaviors/translated_title.py#L55). Das heisst, wenn kein Wert gesetzt ist, wird, statt einen `AttributeError` zu produzieren, der Wert vom Parent acquired.

**Comment by maethu** [comment]
Bei Biel haben wir ebenfalls ein Lösung im Einsatz. Ich vergleiche die beiden Lösungen... und gebe Feedback.

**Comment by maethu** [comment]
Die Lösung von Biel ist ein herum gepatche:
--> https://github.com/4teamwork/biel.intranet/blob/master/biel/intranet/translated_title/monkey_patch.py

Mit einem eigene title_fr index --> https://github.com/4teamwork/biel.intranet/blob/master/biel/intranet/translated_title/indexer.py

Also quasi das was ihr hier ebenfalls beschrieben habt.

**Comment by maethu** [comment]
@deiferni Ich bin der Meinung, dass ein eigenes Feld/Widget und ein eigener Index die "schönste" Lösung ist, so müssen nicht diverse Methoden gepatched werden. 

Jedoch habe ich mir kurz die Code-Basis von einigen default Indexes angeschaut.... und ehrlich gesagt verstehe ich nicht so ganz wie das funktioniert, bzw. werde ich diesen Issue nicht während diesem Sprint alleine lösen können.

**Comment by buchi** [comment]
Ich würde einen eigenen Feldtyp mit entsprechendem Widget machen für mehrsprachige Felder wie z.B. in [collective.multilanguagefields](https://github.com/collective/collective.multilanguagefields) 

Der Catalog muss wohl oder übel gepatched werden, damit Brains mit mehrsprachigen Metadaten möglich sind.

Ein eigener Indextyp ist evtl. gar nicht nötig. Kommt drauf an, ob nach mehrsprachigen Feldern gesucht od. sortiert werden muss. Raptus hat das mal mit Archetypes gemacht: [raptus.multilanguagefields](https://github.com/Raptus/raptus.multilanguagefields)

**Comment by deiferni** [comment]
Der aktuelle Ansatz ist gut genug.
