### ISSUE TITLE
Anpassungen Workflow für Policyerstellung

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1619]
- [ ] Checkliste an Mr.Bob Fragen angleichen
- [ ] Policytemplate für SaaS optimieren
- [ ] Mr.Bob Fragen auf deutsch schreiben
- [ ] Installations-Guideline in Excel hinterlegen
  - [ ] Schritt für Schritt Anleitung mit Verweis auf wichtige Tabs
  - [ ] In Zeilen hinterlegen wo die Konfiguration in der Policy hinterlegt werden muss (z.B. Repository Excel)
- [ ] deployment-theta-... config aufnehmen

**Comment by phgross** [comment]
Die Policy Erstellung wurde in der Zwischenzeit dokumentiert (https://intern.onegovgever.ch/policies/ ) und teilweise angepasst/erweitert. Aus meiner Sicht sind keine weiteren Anpassungen notwendig.
