### ISSUE TITLE
Einchecken verhindern, solange die Datei noch geöffnet ist

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1636]
Falls ein Dokument zum Bearbeiten ausgecheckt und z.B. im Word Programm geöffnet ist, sollte es nicht möglich sein, gleichzeitig im Browser das Dokument einzuchecken. Es gilt hier ähnliche Probleme zu lösen wie beim Drag&Drop Upload für Dokument-Versionen (noch zu implementieren), dort sollten wir den D&D-Upload auch nicht zulassen, solange das Dokument im Office-Connector geöffnet ist.
Grundsätzlich ist das auch möglich, es gibt ein Lock des Office-Connectors. Hier kann es jedoch theoretisch zu timeouts kommen, das heisst das Lock verschwindet, obwohl das Dokument noch in Word/... geöffnet ist. 

Siehe auch https://github.com/4teamwork/opengever.core/issues/1562

**Comment by deiferni** [comment]
Wurde auch im Feedback-Forum thematisiert: https://feedback.onegovgever.ch/t/warnung-beim-einchecken-noch-geoeffneter-dokumente/210

**Comment by deiferni** [comment]
I think this would be something to keep in mind when chaning the GEVER-Side of the OC implementation, thus the assignment.

**Comment by Rotonen** [comment]
@deiferni wasn't this already closed by https://github.com/4teamwork/opengever.core/pull/3799 ?

**Comment by deiferni** [comment]
True dat.
