### ISSUE TITLE
Rolle auch für Vorsitz/Protokollführung darstellen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1655]
Im Moment wird im Protokoll nur die Rolle für Mitglieder dargestellt (In Klammern hinter dem Namen). Dies sollte auch bei Vorsitz/Protokollführung passieren.

**Comment by phgross** [comment]
@deiferni die sauberste Variante wäre hier, dass wir das gleiche Format wie bei den `participants` (siehe https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/protocol.py#L67-69) für die `presidency` und `secretary` verwenden würden. Also:

```
{
 "fullname": "Peter Muster",
 "role": "Stellvertretende Leitung"
}
```

Dies hätte aber zur Folge das auch alle Protokollvorlagen (Sablon Templates) angepasst werden müssten. Ist das vertretbar oder würdest du die bestehenden Attribute `presidency` und `secretary` beibehalten und zwei zusätzliche Attribute `secretary_role` und `presidency_role` einführen?

**Comment by deiferni** [comment]
@phgross ja das ist mir auch aufgefallen, das ist problematisch. Ich würde das unbedingt jetzt noch anpassen, wo die Anzahl an Vorlagen noch einigermassen überschaubar ist.
