### ISSUE TITLE
Listenansicht mit Auge ergänzen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1667]
- [ ] neue Spalte mit Augensymbol erstellen (gem. https://feedback.onegovgever.ch/t/pdf-konvertierung-und-generierung-von-vorschaubildern-von-dokumenten/12)
- [ ] klick auf Auge öffnet den Lesemodus
- [ ] Sortierung der Spalten soll nach Aktivierung / Deaktivierung des Features gleich bleiben

**Comment by deiferni** [comment]
Wir haben diskutiert und beschlossen, das Auge wegzulassen und dafür bei aktiviertem Bumblebee immer das Overlay zu öffnen.
