### ISSUE TITLE
Suchresultate mit Vorschau-Bilder

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1669]
- [x] Visuelle suche soll in Suchresultate eingebettet werden

Konzept muss noch mit @bierik erstellt werden

**Comment by deiferni** [comment]
Erster Vorschlag auf dem branch `deif-search-preview`, (og.core und plonetheme.teamraum)
@bierik das Styling ist noch etwas optimierungsbedürftig. Links können wir umhängen sobald das Overlay verfügbar ist, evtl dann auch in einem separaten PR.

**Comment by phgross** [comment]
Ist umgesetzt.
![bildschirmfoto 2016-05-17 um 08 36 12](https://cloud.githubusercontent.com/assets/485755/15313259/71165f92-1c0a-11e6-969c-5855ff43fc7c.png)

**Comment by phgross** [comment]
Noch ein kleines Problem bei Dokumenten mit sehr langem Titel:
![bildschirmfoto 2016-05-17 um 08 41 19](https://cloud.githubusercontent.com/assets/485755/15313398/34e65698-1c0b-11e6-81ab-da2a0ca86a2a.png)
