### ISSUE TITLE
Versionen-Reiter mit Vorschaubilder erweitern

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1670]
Der Reiter "Versionen" soll mit der Vorschaufunktion erweitert werden.

<img width="700" alt="bildschirmfoto 2016-04-05 um 14 25 58" src="https://cloud.githubusercontent.com/assets/557005/14281580/575f8416-fb3a-11e5-9072-2ec90e2289e1.png">

**Comment by elioschmutz** [comment]
Hat sich hier schon jemand Gedanken über das UI gemacht?

**Comment by elioschmutz** [comment]
Mockups erstellt mit @phgross 

![bildschirmfoto 2016-06-23 um 15 50 03](https://cloud.githubusercontent.com/assets/557005/16305484/60c54dac-395a-11e6-8bb7-ff07c5e11743.png)

![bildschirmfoto 2016-06-23 um 15 50 51](https://cloud.githubusercontent.com/assets/557005/16305485/60c67f06-395a-11e6-8757-8168c7cf3d15.png)

Bitte Variante auswählen

**Comment by phgross** [comment]
Ich würde mal mit Variante 1 Starten

**Comment by deiferni** [comment]
galerie ist auch aus meiner sicht nicht sinnvoll 👍
