### ISSUE TITLE
Installation ftw.bumblebee

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1672]
- [x] `ftw.bumblebee` Profil installieren
- [x] `plone.app.registry`-Feature-Flag erstellen ob Visuelle Suche aktiviert oder deaktiviert ist
- [x] Feature per Default deaktivieren
- [x] Utils-Methode erstellen welche überpfürt ob Bumblebee aktiviert oder deaktiviert ist
- [x] Upgradestep erstellen

`ftw.bumblebee` wird grundsätzlich immer Installiert und kann per Feature-Flag in der Registry aktiviert bzw. deaktiviert werden.

**Comment by jone** [comment]
Da `ftw.bumblebee` immer installiert wird und dies immer `collective.taskqueue` installiert, würde ich dann auch immer die taskqueue im Buildout konfigurieren.
Vorerst würde ich das direkt im `development.cfg` von `opengever.core` machen, später müssen wir das dann nach `gever-buildouts` verschieben.

**Comment by lukasgraf** [comment]
@jone: Keine starke Präferenz, aber wieso nicht gleich in's `ftw-buildouts`? Ist ja nicht's GEVER-spezifisches drin soweit ich gesehen habe.

Nebenbei finde ich's irgendwie doof von `collective.taskqueue`, dass es eine Standard-Konfiguration zu geben scheint die funktional ist (und damit ein default sein könnte), aber trotzdem in der `zope.conf` angegeben werden muss. :rage:

**Comment by jone** [comment]
Mögliche Problematik:
Wenn man die `zope.conf` erweitert aber `collective.taskqueue` (noch) nicht installiert hat, könnte es zu Fehlern führen (These => zu beweisen :wink: ).
Dies würde heissen dass wir erst ab einer bestimmten GEVER-Version das Buildout erweitern könnte.

Damit wir das Problem noch nicht jetzt lösen müssen hätte ich es vorerst im `development.cfg` gelöst, dann ist es auch im gleichen Branch / PR wie die Erweiterung.

Alternative:
Allenfalls könnte `ftw.bumblebee` die Konfiguration direkt beim Starten vornehmen, so dass wir das Buildout gar nicht anpassen müssen? Dies wäre natürlich noch besser.
Könnt ihr das allenfalls mal anschauen? Vielleicht mit einem startup hook / subscriber?

**Comment by lukasgraf** [comment]
Das `%import collective.taskqueue` hätte definitiv Potential für Probleme wenn `collective.taskqueue` nicht installiert ist ;) - sollte aber nicht passieren, wenn man in einem hypothetischen `ftw-buildouts/bumblebee.cfg` einfach die dependency auf `ftw.bumblebee` auch reinnimmt:

```ini
[instance]
eggs +=
    ftw.bumblebee
zope-conf-additional +=
    %import collective.taskqueue
    <taskqueue />
    <taskqueue-server />
``` 
(Aus dem `README` von `ftw.bumblebee`).

Ich hätte jetzt im `ftw-buildouts` einen branch gemacht und während der Entwicklung von diesem extended, aber im `development.cfg` im `opengever.core` ist auch ok für mich.

Die von dir vorgeschlagene Alternative klingt aber gut, denke das werde wir uns mal anschauen.

**Comment by jone** [comment]
Die Frage ist, ob man dann im deployment buildout config immer ein `bumblebee.cfg` extenden muss.
Wenn dies aber zum Standard gehören soll, würde ich das auch im [standard-deployment.cfg](https://github.com/4teamwork/gever-buildouts/blob/master/standard-deployment.cfg) - wobei dies dann automatisch bei _alten_ Installationen auch installiert würde, da `standard-deployment.cfg` nicht Versioniert ist (im Sinne von GEVER KGS Releases).
