### ISSUE TITLE
Mockups erstellen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1674]
Das Bumblebee wird für GEVER neu implementiert. Änderungen an der bestehenden Implementation für GEVER haben keine Auswirkung auf bestehende Installationen wie Teamraum oder zug.

- [x] Galerieansicht
- [x] Listenansicht
- [x] Dokumentansicht
Zusatätzlich zu den Detailinformationen möchte der Benutzer das Thumbnail des Dokuments sehen mit Link auf den Lesemodus.
- [x] Lesemodus (Overlay)

Für die o.g. Ansichten muss ein Mockup erstellt werden

Die Mockups können hier im Issue abgelegt werden, die Sourcedateien bitte im Basecamp ablegen

zu erledigen bis 08.04.2016

**Comment by elioschmutz** [comment]
Siehe für mehr Infos:

Spez Galieriedarstellung - #1665
Spez Detailansicht Dokument - #1668
Spez Lesemodus - #1666
Spez Listendarstellung - #1667

**Comment by deiferni** [comment]
Das haben wir erledigt. Siehe https://basecamp.com/2768704/projects/11858966/todos/244732253.
