### ISSUE TITLE
Taskqueue implementation verbessern

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1677]
- [ ] Analyse ob Startuphook möglich ist in `ftw.bumblebee` um die Taskqueue mit Python zu konfigurieren anstatt über buildout(siehe https://github.com/4teamwork/ftw.bumblebee/blob/master/README.rst => `Installation with buildout``
- [ ] Implementation Startuphook
- [ ] sonst Umsetzung mit einem `bumblebee.cfg` im `ftw-buildouts`. Branch existiert bereits: https://github.com/4teamwork/ftw-buildouts/tree/es-add-bumblebee-config

siehe Diskussion in #1672 betreffend Taskqeue.

@jone @lukasgraf

**Comment by elioschmutz** [comment]
@jone 

Habe mich bisschen durch das Rezept durchgeschlagen (https://github.com/plone/plone.recipe.zope2instance/blob/4dee34eaa99217c2b2d6479c1c3c9d45e5b30f90/src/plone/recipe/zope2instance/__init__.py). Auch habe ich mit ```from App.config import getConfiguration``` http://docs.plone.org/4/en/old-reference-manuals/buildout/additional.html#configuring-plone-products-from-buildout rumprobiert.

Lieder komme ich nicht zu einer Lösung.

Könntest du da nochmals nach einer möglichen Lösung suchen (Punkt 1 in der Taskliste)?

FYI @lukasgraf

**Comment by jone** [comment]
Eine andere, aufwändigere Lösung wäre ein anderes Queuing-System zu benutzen. Allgemein sind wir mit `collective.taskqueue` auch nicht nur happy: man kann z.B. die Queues und Jobs gar nicht verwalten.
Ein Problem ist z.B. dass wenn ein Job fehlschlägt ist er einfach weg, man kann ihn nicht requeuen.

Daher müssen wir irgendwann sowieso ein besseres Queuing-System entwickeln, das mit Transaktionen korrekt umgeht, robust ist und das wir über ein Control-Panel bedienen können.
Am liebsten wäre mir eine Lösung bei der wir nicht einen komplett neuen Stack einführen müssen.

Nur so ein gedanklicher Anstoss 😉

**Comment by lukasgraf** [comment]
@elioschmutz evtl. könnte als startup hook `zope.processlifetime.DatabaseOpenedWithRoot` verwendet werden ([Beispiel in `plone.app.theming`](https://github.com/plone/plone.app.theming/blob/27cd26fc50006e5b6186530de8bbde918965a9bf/src/plone/app/theming/plugins/configure.zcml#L13-L16)) - hab das aber noch nicht probiert.

**Comment by lukasgraf** [comment]
Die Default-Konfiguration von `collective.taskqueue` von aussen (statt über die `zope.conf`) zu providen, ist leider nicht einfach möglich:

- Die Queue wäre kein Problem, das wäre im wesentlichen eine Utility-Registrierung:
```python
from collective.taskqueue.taskqueue import LocalVolatileTaskQueue
provideUtility(LocalVolatileTaskQueue, ITaskQueue, name='default')
```
- Der Server ist hingegen ein Problem: Dies ist ein echter ZServer, der von `Zope2.Startup` selbst ausgelesen (aus der `zope.conf`) und konfiguriert wird. Dies passiert bevor irgendwelche Events gefeuert werden, sehe da also keine einfache Möglichkeit, sich einzuhängen.

**Comment by elioschmutz** [comment]
Momentan gibt es keine Möglichkeit zur Umsetzung.
