### ISSUE TITLE
GEVER Inhaltstypen IBumblebeeable machen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1680]
- [x] Documets IBubmlebeeable machen
- [x] ~~IGetFileData Adapter erstellen (siehe #1679)~~
- [x] Bumblebeeservice überschreiben, damit dieser nur requests an den Server schickt, wenn das Feature aktiviert ist (https://github.com/4teamwork/ftw.bumblebee/blob/master/ftw/bumblebee/service.py#L22)

**Comment by deiferni** [comment]
Ein erster Vorschlag ist eingecheckt: https://github.com/4teamwork/opengever.core/tree/deif-bumblebeeable-doc

kann aber gut sein, dass durch https://github.com/4teamwork/ftw.bumblebee/pull/68 noch Änderungen nötig sind
