### ISSUE TITLE
Kalender-Widget funktionert in IE nicht korrekt.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1684]
Kalender-Widget funktionert in IE (Version weiss ich nicht) nicht korrekt. Bitte mit Version IE 11 oder 10 testen.

@phabegger kannst du dich noch erinnern, was nicht funktioniert hat? Eine kurze Beschreibung wäre beim debugging eventuell hilfreich.

**Comment by phgross** [comment]
@deiferni wollen wir nun auf `ftw.datepicker` wechseln?

**Comment by deiferni** [comment]
im Prinzip ja, muss aber aus meiner Sicht nicht mehr in diesen Release. Im Moment wird das End-Datum für ein Meeting auf der Client-Seite noch intelligent vorbefüllt wenn sich das Start-Datum ändert, zudem wird schon beim Client verhindert, dass das End-Datum vor dem Start-Datum liegen kann. Evtl. lässt sich das ja auch übernehmen.

**Comment by phgross** [comment]
Abklären ob `ftw.datepicker` sinnvoll wäre und verwendet werden kann.

**Comment by deiferni** [comment]
Kurz getestet, man müsste das bisher verwendete "widget" ausbauen (`base/datetimepicker.js` und `meeting/datetimepicker.js`), danach könnte `ftw.datepicker` verwendet werden. Was, wie oben schon erwähnt, fehlt ist die Client-Seitige Logik, die dem User früh bewusst macht, dass das End-Datum der Sitzung nicht vor dem Start-Datum liegen darf. @bierik könnte man das aus deiner Sicht einfach in eine Lösung, die `ftw.datepicker` verwendet, einbauen?

**Comment by deiferni** [comment]
update: eventuell lässt sich auch http://www.daterangepicker.com/ verwenden
thx @elioschmutz

**Comment by bierik** [comment]
Da wir beim erstellen eines Meetings in der SPV fast immer nur ein Datum auswählen und die Range durch die Zeit definiert ist, ist aus meiner Sicht der `daterangepicker` nicht geeignet. Ich habe versucht beim Auswählen eines Startdatums, sofort das Enddatum gleich zu setzen. Leider bietet der Rangetimepicker keine Events um dies zu Tracken. Auch custom Events zu registrieren ist unmöglich, da die Library diese nicht nach oben propagieren lässt.
Es wäre sicher möglich mit zusätzlichen Aufwand dem `daterangepicker` das gewünschte Verhalten beizubringen aber ich denke somit enden wir wieder im selben Dilemma wie mit der jetzigen Lösung.

Die beste Lösung wäre aus meiner Sicht eine Kombination aus einem `normalen` Datepicker zum auswählen der Tages an dem das Meeting stattfinden und einem Slider um die Range auszuwählen. Der Slider ist fast jedem Benutzer bekannt und es ist einfach eine Zeitspanne darin einzugeben. Den Slider und das Zusammenspiel mit dem Kalender müsste man natürlich selbst bauen aber so hätten wir das Verhalten besser unter Kontrolle. Ausserdem sind die existierenden RangeTimePicker viel zu aufwändig und benötigen zusätzliche Libraries wie momen.js, bootstrap oder jQuery versionen, die wir nicht unterstützen.

Hier noch ein Beispiel wie so ein Slider aussehen könnte:
![screen shot 2016-11-03 at 17 39 46](https://cloud.githubusercontent.com/assets/1637820/19975618/e65acf46-a1ec-11e6-8873-1ef5fe7cdae5.png)

@deiferni @phgross @lukasgraf Was denkt ihr?

**Comment by deiferni** [comment]
Hmm wenn das alles so Mühsam ist tendiere ich im Moment eher dazu, das auf die gute alte Art zu lösen, und wieder nur Serverseitig zu validieren. Dem Plone-Benutzer ist das Konzept ja bekannt 😉 .

**Comment by bierik** [comment]
@deiferni Was ist jetzt hier die definitive Entscheidung?

**Comment by deiferni** [comment]
@bierik wir werden wieder den `ftw.datepicker` verwenden und serverseitig validieren 😖

**Comment by maethu** [comment]
@deiferni Ja? 
Die neue Version vom Datepicker Widget wird ebenfalls in der SPV verwendet.

**Comment by deiferni** [comment]
ja, hab nur meine tickets aufgeräumt 😉
