### ISSUE TITLE
Entschuldigte Teilnehmer einer Sitzung erfassen.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1688]
Es sollte möglich sein Entschuldigte Teilnehmer einer Sitzung zu erfassen.

**Comment by phabegger** [comment]
Gemäss Feedback-Forum https://feedback.onegovgever.ch/t/menue-fuer-eintrag-der-entschuldigten-abwesende-welche-sich-abgemeldet-haben/234

**Comment by phgross** [comment]
@deiferni further specify

**Comment by phgross** [comment]
Wurde bereits umgesetzt: Teilnehmer einer Sitzung können definiert werden bzw. Teilnehmer entschuldigt werden.
