### ISSUE TITLE
Neues Attribut Beschlussentwurf für Antrag

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1689]
Der Beschluss(-entwurf) muss bereits bei Antragstellung erfasst werden können. Dazu muss die Spalte im Modell verschoben werden.

**Comment by phgross** [comment]
Die Spalte `decision` kann nicht auf das Proposal Model verschoben werden, denn auch Freitext Traktanden (AgendaItems ohne Proposal Verknüpfung) müssen einen Entscheid haben.

Ich würde deshalb stattdessen ein Feld `proposed_decision` auf dem Proposal Model hinzufügen. Bei der Erstellung eines Traktandums, wird dann die `decision` automatisch mit der `proposed_decision` vorbefüllt. 

@deiferni irgendwelche Einwände ?

**Comment by deiferni** [comment]
oh 🙈 . Wir wollen ja auch einbauen, dass man Anträge versionieren kann (https://github.com/4teamwork/opengever.core/issues/1357) das geht schon in die Richtung. Versionierung ist aber vermutlich vom Aufwand her was Grösserers, daher würde ich das jetzt auch so implementieren wie du vorschlägst 👍
