### ISSUE TITLE
Deal with broken relations in relation catalog

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#169]
Currently, there's a few broken relations on some GEVER installations. Queries to the relation catalog yield `RelationValue` objects that are not marked `broken` (`isBroken()` returns false), but nevertheless are missing one or the other end of the relationship (`from_object` is `None` or results in a `KeyError` for example).

We should write a script to detect these, another to clean them up, and adjust any `related_items` indexers (for example in og.document) to gracefully deal with them.

**Comment by deiferni** [comment]
this looks done.
