### ISSUE TITLE
OGIP 36: Benachrichtigungen für die SPV

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1692]
Vollständige spez. ist als OGIP verfügbar: Gemäss https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2559/document-23306#overview

Harvest: _`Feature: Benachrichtigung SPV - OGIP 36`_

**Comment by phgross** [comment]
@Suweber kannst du dieses Thema mit @deiferni besprechen und einen Vorschlag ausarbeiten.

**Comment by deiferni** [comment]
this looks done 😄.
