### ISSUE TITLE
Druckansicht eines Antrags optimieren

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1704]
Siehe entsprechender Feedback-Eintrag https://feedback.onegovgever.ch/t/antrag-als-formular-oder-doku-generieren/232/4

Konkret:
- Antragsverlauf ausblende
- Tabelle auf erster Seite einblenden (speziell ein Problem bei kurzen Anträgen mit wenig Text)
- Textzeilen werden unten am Seitenrand zT. nicht ganz mehr dargestellt / abgeschnitten. Evtl. kann dies mit overflow:visible oder ähnlich korrigert werden: http://stackoverflow.com/questions/1312320/print-stylesheet-one-page-prints-and-cuts-off-remaining-text

**Comment by bierik** [comment]
Den Verlauf im print-modus zu entfernen sollte kein Problem sein.
Allerdings ein anständiges Ergebnis der Tabelle beim Drucken zu erzielen ist fast unmöglich.
Ich habe mir hier schon bei bern.ch und zg.ch ein Bein ausgerissen. Die PDF engines der Browser funktionieren nicht richtig und ich kann diese auch nicht kontrollieren.

Das CSS property zum kontrollieren von `page-breaks` funktioniert gemäss http://caniuse.com/#search=page-break und meiner Erfahrung nicht.
Tabellen sind dabei noch extra tückisch.

Ich würde hier einen pragmatischen Ansatz fahren und nur den Verlauf ausblenden in der Druckansicht ausblenden. Eine Generierung des Antrags in Word oder PDF wird sicher zu einem späteren Zeitpunkt aktuell werden.

**Comment by deiferni** [comment]
👍  zum pragmatischen Vorgehen

**Comment by phgross** [comment]
@bierik bitte für den nächsten Release umsetzten

**Comment by phgross** [comment]
@bierik bitte im Verlauf von nächster Woche umsetzen, Danke.

**Comment by deiferni** [comment]
There seems to be a regression (see https://extranet.4teamwork.ch/support/0339-support-kg-koeniz/0339-support-onegov-gever-evangelisch-reformierte-kirchgemeinde-koeniz/66), @bierik could you verify/double check?

**Comment by bierik** [comment]
Ich konnte das Problem weder auf Chrome noch IE11 noch Edge reproduzieren.
Screenshots vom aktuellen Master:

Chrome:
![screen shot 2017-03-31 at 09 12 27](https://cloud.githubusercontent.com/assets/1637820/24540142/2bb800bc-15f2-11e7-8cd8-5145b363b4b6.png)
![screen shot 2017-03-31 at 09 12 36](https://cloud.githubusercontent.com/assets/1637820/24540141/2bb6ae74-15f2-11e7-9b1c-41f285339dc6.png)

Edge:
![druckvorschau_edge_1](https://cloud.githubusercontent.com/assets/1637820/24540089/f43da24a-15f1-11e7-97f3-831a5bc38fbf.png)
![druckvorschau_edge_2](https://cloud.githubusercontent.com/assets/1637820/24540088/f43d4322-15f1-11e7-9cbb-f59a2f054f47.png)

IE11:
![druckvorschau_ie_11_1](https://cloud.githubusercontent.com/assets/1637820/24540106/030ff0ca-15f2-11e7-8b8f-2fb3a249ee4b.png)
![druckvorschau_ie_11_2](https://cloud.githubusercontent.com/assets/1637820/24540105/030fa0ac-15f2-11e7-8da3-7b340c222435.png)

**Comment by deiferni** [comment]
Mit der Umstellung auf Word nicht länger relevant.
