### ISSUE TITLE
Beschreibung einer Ordnungsposition unterhalb des Titels anzeigen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1706]
Gemäss Feedback https://feedback.onegovgever.ch/t/verweise-zwischen-ordnungspositionen/197/4

Allenfalls muss der Beschreibungstext auf zwei Zeilen begrenzt werden (oder aufklappbar gemacht werden).

**Comment by phabegger** [comment]
Ich wäre froh, wenn dieses Feature in Bälde umgesetzt werden kann. Aus meiner Sicht sollte dies relativ einfach umsetzbar sein, oder? /cc @phgross @deiferni

**Comment by phgross** [comment]
Ok, ist nun für den Juni Release vorgesehen.

**Comment by phgross** [comment]
@phabegger zur info ist umgesetzt. Ich habe mich dazu entschlossen nur eine Zeile darzustellen und stattdessen die komplette Description als Tooltip darzustellen. Ich denke so bleibt die Byline übersichtlicher. Siehe #1909
