### ISSUE TITLE
Footer bei Standardinstallationen von OneGov GEVER anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1715]
Bitte Footer überarbeiten (siehe Screenshot bzw. demo.onegovgever.ch). Die Adresse auch ändern - darf um den 20.05. aufgeschaltet werden.

Damit erübrigt sich eigentlich die Arbeiten in #1550 ...

![bildschirmfoto 2016-04-13 um 22 35 11](https://cloud.githubusercontent.com/assets/485600/14508625/ac643756-01c8-11e6-84ad-dac33ba9fae5.png)

**Comment by deiferni** [comment]
Für mich stellt sich die Frage ob es eine Option wäre im Rahmen dieser Anpassungen direkt das footer-portlet zu ersetzen, sprich `ftw.footer` auszubauen und unseren eigenen statischen Footer einzubauen. 

- Buchi hat ja im Rahmen der Peformanceanalyse festgestellt, dass der Footer relativ viel Rechenzeit braucht bei jedem Request, obwohl er bei uns nur statischen Inhalt darstellt
- Im Moment ist unser "Standard"-Footer bei allen policies dupliziert, Änderungen am Footer führen dazu, dass man unter Umständen bei jeder Policy einen Upgrade-Step für den Footer schreibt.
- Der zusätzliche Aufwand für den eigenen Footer sollte überschaubar sein, spart uns aber in Zukunft Zeit und verringert die Duplikation.
- wir brauchen die Funktionalität von `ftw.footer` eigentlich gar nicht, im Prinzip könnte man dort beliebige Portlets konfigurieren, auch Kontextabhängige.

Man müsste einfach sicherstellen, dass auch der neue Footer von Kunden bei Bedarf überschrieben werden kann.

**Comment by phabegger** [comment]
👍  - den Footer überschreiben wir für den Kunden, er muss es nicht selber können. Von daher kann es eine relativ statische (und damit effizientere) Implementierung sein. Aufpassen muss man sicher, wenn man die neue Implementierung bei den Kunden aktiviert, da sie teilweise angepasste Footer verwenden.

**Comment by phgross** [comment]
`ftw.footer` wurde entfernt und mit einem separaten Viewlet ersetzt, see #2454.
