### ISSUE TITLE
Standardabläufe: Verschieben von Aufgabenvorlagen nicht möglich

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1723]
![bildschirmfoto 2016-04-15 um 09 12 34](https://cloud.githubusercontent.com/assets/485600/14554168/554d58f2-02eb-11e6-9cc0-466a3f3d3971.png)

Packt man mit dem Mauszeiger den Handle zum Verschieben von Elementen, heisst es, Drag'n'Drop sei nicht möglich.

**Comment by phgross** [comment]
Die "Handle" Spalte wurde mit #2728 entfernt.
