### ISSUE TITLE
Falscher Titel beim Auslösen eines Standardablaufs (Wizard)

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1728]
Es steht "Aufgabenvorlage hinzufügen", sollte aber eigentlich "Standardablauf hinzufügen" oder noch besser "Standardablauf auslösen" heissen:

![bildschirmfoto 2016-04-16 um 10 39 23](https://cloud.githubusercontent.com/assets/485600/14580009/b58975fa-03bf-11e6-8cff-2d966baf651e.png)

Der Titel ist auch beim zweiten Schritt im Wizard falsch

**Comment by phgross** [comment]
Das Formular wurde mit #1944 überarbeitet und dabei wurde auch der Formular Titel geändert.
