### ISSUE TITLE
Erstellung Konzept für neue Colorbox

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1736]
- [ ] `ftw.colorbox` soll wegen diversen Mängel nicht für GEVER verwendet werden
- [ ] Blättern zwischen Dokumenten muss möglich sein
- [ ] Inhalte müssen per AJAX nachgeladen werden können
- [ ] Anzeige Anzahl Dokumente und das wievielte gerade angeschaut wird (Dokument 3 von 10)
- [ ] Übersetzbar in verschiedene Sprachen
- [ ] Requirements für Leseansicht: #1666 

Das Konzept wird mit folgenden Personen erstellt:

Umsetzung Frontend: @bierik 
Umsetzung Backend: @elioschmutz

Optisch und auch funktional richten wir uns an die von @bierik erstellten Mockups welche im Vorfeld bereits erstellt und von Seite GEVER abgesegnet wurden. Mehr dazu im Basecamp.

**Comment by bierik** [comment]
Requirements Engineering:

- Laden von iFrames und HTML Inhalten (asynchron).
- Initialisieren der Gallery mit mehren Inhalten
- Navigieren zwischen Inhalten
- Laden von weiteren Inhalten während das Overlay bereits geöffnet ist.
- Updaten von Seitenzahlen und Inhalten soll automatisch passieren.
- Batching
- Beim ersten Element wird der `zurück` Button disabled
- Beim letzten Element (kein weiterer Batch) wird der `nächste` Button disabled.

Anbei eine pseudo Implementation:

``` javascript
var items = [{
  "preview": "http://bumblebee.ch/i3hdh38geiewf3ofewudjhi",
  "meta": {
    "title": "Lorem",
    creator: {
      name: "Ersteller",
      "value": "zopemaster"
    }
  }
},
{
  "preview": "http://bumblebee.ch/i3hdh38geiewf3ofewudjhi",
  "data": {
    "peter": "Lorem",
    creator: {
      name: "Ersteller",
      "value": "zopemaster"
    }
  }
}];


var template = <div class="overlay">
  <div class="title">{{data.peter}} {{overlay.current}} / {{overlay.total}}</div>
  <button data-overlay-action="toggle"></button>
  <button data-overlay-action="close"></button>
  <aside class="overlay-sidebar"></aside>
  <a class="next" data-overlay-action="next"></a>
  <a class="prev" data-overlay-action="prev"></a>
</div>

function render(data) {
  return template(data);
};

function head(item) {

}

function tail(item) {
  // Call next batch
  appendItems();
}

function fetch(item) {
  return $.get(item.data("peter"));
}

function next() {

}

function prev() {

}

function close() {

}

function open() {

}

function appendItems() {

}

items = document.querySelector(".preview");

items = {
  "peter": "<p>meter</p>",
  "hansp": "<p>meter</p>",
  "meter": "<p>meter</p>",
  "pedro": "<p>meter</p>",
  "meter": "<p>meter</p>"
}

var overlay = new Overlay({
  items: items,
  options: {
    render: render,
    tail: tail,
    head: head
    fetch: fetch,
    cssClass: "overlay"
  }
});

overlay.open();
```
