### ISSUE TITLE
ftw.bumblebee mit RelStorage testen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1742]
- [ ] Bumblebeeintegration testetn mit Dexterity, Versionierung und RelStorage

Gewisse GEVER-Installationen laufen mit RelStorage. Es muss sichergestellt werden, dass `ftw.bumblebee` mit RelStorage umgehen kann.

**Comment by deiferni** [comment]
confirmed working, witnessed by @elioschmutz and @lukasgraf 😏 .
