### ISSUE TITLE
Import warning from openpyxl

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1753]
Warning:
```
/Plone/eggs/openpyxl-2.3.5-py2.7.egg/openpyxl/xml/__init__.py:15: UserWarning: The installed version of lxml is too old to be used with openpyxl
  warnings.warn("The installed version of lxml is too old to be used with openpyxl")
```
The current pinned version of lxml `2.3.6` (pinned by http://dist.plone.org/release/4.3.2/versions.cfg) is too old for using `openpyxl` in the newest version `2.3.5`.

The dependency to `openpyxl` has been introduced by the XLS Rework (#1735)

**Comment by phgross** [comment]
I've seen the following solution:
 - Pinning up `lxml` from `2.3.6` to `3.3.1.0` seems to work fine ... (Just an test failure 😉 )

Pinning down `openpyxl` is not a option, even the version `1.8.0`, where the lxml support is introduced,  looks for the lxml version `3.3.1.0`

@lukasgraf what do you think?

**Comment by lukasgraf** [comment]
@phgross as discussed: I'm generally in favour of bumping `lxml`, but let's not take that risk just yet but wait for the next release, and do it early in the release cycle so we have enough time to test it.

**Comment by lukasgraf** [comment]
I also get another warning (during tests, not during bootup. For example `bin/test -t test_task` ):
```
openpyxl-2.3.5-py2.7.egg/openpyxl/styles/styleable.py:189: UserWarning: Use formatting objects such as font directly
  warn("Use formatting objects such as font directly")
```

**Comment by lukasgraf** [comment]
@phgross as discussed, let's target this for `Release Juli, Release Sommer 2016`
