### ISSUE TITLE
Neues Produkt: ftw.showroom

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1755]
- [x] neues Produkt `ftw.showroom` erstellen: https://github.com/4teamwork/ftw.showroom
- [x] Umsetzung gemäss Konzept: https://github.com/4teamwork/opengever.core/issues/1736
- [x] Gute API Doku mit Besipiele erstellen

**Comment by deiferni** [comment]
This Product has been released 🎉
