### ISSUE TITLE
Bumblebee LayoutPolicy erstellen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1761]
- [x] "namespacing" der styles mittels `feature-bumblebee` klasse auf body, siehe: https://github.com/4teamwork/opengever.core/blob/master/opengever/document/browser/layout.py#L6-L17
- [x] Klasse nur bei aktivem Feature einfügen

Momentan wird in GEVER die `plone.app.layout.globals.layout.LayoutPolicy` Klasse für Dokumente überschreiben. Die `DocumentishLayoutPolicy` fügt für Dokumente u.U. eine neue Body-Klasse hinzu.

Die Bumblebee-Klasse sollte, sofern das Feature aktiviert ist, überall im GEVER eingefügt werden.

Deshalb wird eine `GeverLayoutPolicy(LayoutPolicy)` erstellt welche die Feature-Klasse behandelt. Die `DocumentishLayoutPolicy` erbt anschliessend von der `GeverLayoutPolicy`.

Bsp:

``` python

from plone.app.layout.globals.layout import LayoutPolicy
from opengever.bumblebee import is_bumblebee_feature_enabled


class GeverLayoutPolicy(LayoutPolicy):
    """Fügt u.A. die Bumblebee Klasse hinzu.
    """
    def bodyClass(self, template, view):
        body_class = super(DocumentishLayoutPolicy, self).bodyClass( template, view)

        if is_bumblebee_feature_enabled:
            body_class = ' '.join((body_class, 'feature-bumblebee'))
    
        return body_class


class DocumentishLayoutPolicy(GeverLayoutPolicy):
    """Momentane Implementation wird beibehalten
    """

**Comment by elioschmutz** [comment]
@deiferni Kannst du das kurz so Bestätigen oder ggf. einen Gegenvorschlag erstellen?

Ich würde dann gleich mit der Implementation beginnen, damit ich `plonetheme.teamraum` auf diese Klasse ausrichten kann. Somit wäre auch sichergestellt dass das ganze Bumbelbeecss keinen Einfluss auf das restliche GEVER hat...

**Comment by deiferni** [comment]
@elioschmutz so würde ichs auch machen 👍 

die `GeverLayoutPolicy` wäre vermutlich in `opengever.base` am besten platziert

**Comment by phgross** [comment]
@elioschmutz, @deiferni

Zur Info: Wir überschreiben die LayoutPolicy neben Dokumente auch für Meetings und Tasks (müsste demnach auch gleich angepasst werden). https://github.com/4teamwork/opengever.core/search?utf8=%E2%9C%93&q=bodyClass

**Comment by elioschmutz** [comment]
👍  super! Danke!
