### ISSUE TITLE
Workflow status queries

### ISSUE THREAD

**Issue by shylux** [4teamwork/opengever.core#177]
It is currently only possible to query one single state of, for example, a dossier.

A use case would be to query every dossier with an open state.

To achive this we need:
- [ ] A place to store a list of all available states of a type. This list should also provide information if the state is a closed or a open one. Implementation possibly in the init file with a dictionary.
- [ ] A utility class. Used for tasks like "give me all possible states of type x, y and z".

**Comment by phgross** [comment]
Currently solved with constants as `DOSSIER_STATES_OPEN`, `DOSSIER_STATES_CLOSED`, https://github.com/4teamwork/opengever.core/blob/master/opengever/dossier/base.py#L39.

At the moment that solution is fine, so I'll close this issue.
