### ISSUE TITLE
Falsche Sortierung nach Frist bei Standardabläufen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1794]
Der Auftrag mit Frist von 45 Tagen sollte zuoberst oder zuunterst aufgelistet werden (je nach Sortierung).

![bildschirmfoto 2016-05-08 um 12 32 47](https://cloud.githubusercontent.com/assets/485600/15097363/28f0ce34-1519-11e6-97e4-05546e069206.png)

Siehe auch https://demo.onegovgever.ch/vorlagen/baugesuch#tasktemplates

**Comment by phgross** [comment]
Die Auflistung der Aufgabenvorlagen ist seit der Umsetzung von OGIP 26 immer nach der vordefinierten Reihenfolge sortiert. Die Spalte `Frist in Tagen` ist nicht mehr sortierbar.
