### ISSUE TITLE
Titel eines Standardablaufs kann nicht mehr bearbeitet werden

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1795]
Getestet auch mit zopemaster-User. Der Menüpunkt "Bearbeiten" wird nicht angezeigt. Konkret: Ich möchte den Titel des Standardablaufs umbenennen.

![bildschirmfoto 2016-05-08 um 12 37 11](https://cloud.githubusercontent.com/assets/485600/15097386/bff2d700-1519-11e6-8710-fdc5899e9b76.png)

**Comment by phgross** [comment]
Zurzeit sieht der Workflow von Standardabläufen vor, dass nur inaktive Standardabläufe bearbeitet werden können. Aus meiner Sicht ist diese Einschränkung unnötig, @phabegger was denkst du?

**Comment by phabegger** [comment]
Ja, aus meiner Sicht unnötig.
