### ISSUE TITLE
Kommission deaktivieren

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1805]
Kommissionen sollen deaktiviert werden können, so dass sie nicht mehr im Kommissionen-Tab der Sitzungen und als Auswahlmöglichkeit für Anträge zur Verfügung stehen. Schon bestehende Anträge dürfen nicht bei einer deaktivierten Kommission eingereicht werden.

**Comment by phgross** [comment]
@deiferni würdest du den Workflow Status  auf dem Plone Objekt abbilden und der aktuelle Status jeweils im SQL abbilden oder nur ein "SQL Workflow".

Ich persönliche tendiere zu Variante 1, da wir so auch gleich die Permissions entsprechend anpassen können.

**Comment by phgross** [comment]
Kurz besprochen, ich werde dem Model ein SQL Status hinzufügen.
