### ISSUE TITLE
Document-Actions zum Auschecken/bearbeiten verbessern

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1812]
Falls das ein Dokument schon ausgecheckt ist wird weiterhin ein Button `Auschecken/Bearbeiten` dargestellt. Dies ist relativ verwirrend, da das Dokument ja bereits ausgecheckt ist, besser wäre es den Button in diesem Fall `erneut Bearbeiten` oder evtl. nur `Bearbeiten` zu benennen.

Betrifft:
- Dokument Übersicht
- Bumblebee Overlay

![screen shot 2016-05-18 at 11 12 27](https://cloud.githubusercontent.com/assets/736583/15353455/71fedd28-1ce9-11e6-8aac-bf4536586f9c.png)

**Comment by Rotonen** [comment]
How'd this let a user retry a transient Office Connector failure?
