### ISSUE TITLE
Dossierübersicht: Dokumentenlinks zeigen auf Detailansicht anstatt Overlay

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1833]
Mit der Implementierung von Bumblebee hat man sich dazu entschieden Dokumente jeweils im `ftw.showroom` Overlay zu öffnen. Dies wurde für die Dokumentauflistungen auch so umgesetzt.

Nun habe ich aber bemerkt das die aufgelisteten Dokument in der Dossier Übersicht nach wie vor auf die Detailansicht verlinken.

Ich bin der Meinung das wenn wir die Dokumentauflistungen ändern, alle Dokument Links angepasst werden müssen, ansonsten führt das zur Verwirrung. @deiferni @phabegger @elioschmutz  was denkt ihr?

**Comment by elioschmutz** [comment]
👍  finde ich auch. Da sollten wir konsequent sein.

**Comment by deiferni** [comment]
👍 schliesse mich da an. Siehe auch https://github.com/4teamwork/opengever.core/issues/1823, bei der SPV gibt es die gleiche Fragestellung.
