### ISSUE TITLE
Bumblebee: Bedienelemente besser anordnen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1834]
Die aktuelle Anordnung der Bedienelemente auf der rechten Seite ist optisch nicht ansprechend und wirk unaufgeräumt:

![bildschirmfoto 2016-05-24 um 19 40 58](https://cloud.githubusercontent.com/assets/485600/15514044/7eb2c658-21e7-11e6-9d0d-ccf53f47c6db.png)

Ich schlage vor, die Bedienelemente oberhalb darzustellen (wie z.B. bei Google):

![ohne titel 2](https://cloud.githubusercontent.com/assets/485600/15514083/a1b2b104-21e7-11e6-834a-9e2a899b1f3e.png)

Die Details (Metadaten) kann man standardmässig ausblenden und nur bei Bedarf anzeigen:

![bildschirmfoto 2016-05-24 um 19 43 01](https://cloud.githubusercontent.com/assets/485600/15514114/c8ef2824-21e7-11e6-8250-a089b211e997.png)

Alternativ können wir die wichtigsten Metadaten unterhalb der Bedienleiste oben immer einblenden (siehe gelber Kasten):
![ohne titel 2](https://cloud.githubusercontent.com/assets/485600/15514213/4fc81c66-21e8-11e6-91a4-e58edd24e7b1.png)

**Comment by bierik** [comment]
@deiferni @phgross @elioschmutz Das war mein erster Vorschlag 😉 .
Unsere Diskussion hatte dort ergeben, dass der User Mühe haben könnte die Aktionen nur an den Icons zu erkennen. Ich denke das Erkennen der Aktionen sollte kein Problem sein, wenn wir gute Icons dafür finden/machen können. Und vielleicht zusätzlich ein Hilfetext in der Form eines Tooltips.
@phabegger Die Idee mit den wichtigsten Metadaten im gelben Kasten finde ich gut. Was wären deiner Meinung nach die wichtigsten? Der Titel wird ja schon in der obersten Liste angezeigt.

**Comment by deiferni** [comment]
@phabegger und ich haben das (gestern?) beim Kaffee kurz diskutiert mit dem Beschluss zuerst eimal Kundenfeedback einzuholen und dann zu entscheiden ob und inwiefern man das UI noch anpassen will/muss.

**Comment by deiferni** [comment]
da ist man ja jetzt dran 😉
