### ISSUE TITLE
Kein Blättern-Pfeil anzeigen, wenn ich nicht blättern kann...

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1836]
Siehe Screenshot. Ist das 8. und letzte Dokument in der Auflistung. Zwar kriege ich einen Pfeil nach rechts angezeigt, kann aber nicht mehr zum nächsten Dokument blättern. In diesem Fall Pfeil bitte ausblenden. Weiter verwirrend ist, dass die Gesamtanzahl von Dokumenten nicht angezeigt wird, so merke ich erst recht nicht, dass ich nicht mehr weiterblättern kann... Siehe #1835 

Bei my.tr.com funktioniert dies bereits so.

![bildschirmfoto 2016-05-24 um 19 59 44](https://cloud.githubusercontent.com/assets/485600/15514616/3bd72db2-21ea-11e6-8929-9d47c00e4c6e.png)

**Comment by elioschmutz** [comment]
Siehe: https://github.com/4teamwork/ftw.showroom/issues/22

**Comment by bierik** [comment]
@elioschmutz Ich habe dier https://github.com/4teamwork/ftw.showroom/issues/22 zugewiesen. Wenn die Pfeile unbedingt nächste Woche umgesetzt werden sollen, kann man dies auch in der Integration in der `head` und `tail` funktion umsetzten.
