### ISSUE TITLE
Sortierreihenfolge in Dokumente-Reiter wird in Vorschau nicht respektiert

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1838]
Habe unter https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/interne-organisation/planung-und-organisatorisches/dossier-2#documents-proxy nach Titel sortiert, Vorschau-Ansicht blieb unverändert...

Ich habe den Eindruck, dass zumindest auf dev.onegovgever.ch die Sortierreihenfolge nicht persistiert wird (?)

**Comment by elioschmutz** [comment]
Das stimmt, die Sortierreihenfolge wird seit neustem nicht mehr persistiert.

Habe dazu ein neues Ticket erstellt: https://github.com/4teamwork/opengever.core/issues/1850

Die Sortierung sollte dann automatisch auch für die Galerieansicht übernommen werden.

- [ ] die Sortierung von https://github.com/4teamwork/opengever.core/issues/1850 muss auch für die Galerieansicht übernommen werden

**Comment by elioschmutz** [comment]
Die Sortierreihenfolge für die Listenansicht wird wieder persistiert.

Die Sortierreihenfolge der Listenansicht soll jedoch nicht für die Galerieansicht übernommen werden (besprochen mit @jone und @deiferni).

Das grundsätzliche Problem ist, dass die Galerieansicht nicht sortierbar ist. Eine Übernahme der Sucheinstellungen für die Galerieansicht würde der Benutzer verwirren, da dieser anschliessend in der Galerieansicht nirgends die Sortierreihenfolge einsehen bzw. ändern könnte. Zudem wäre das UI sehr umständlich, da der Benutzer jeweils zur Listenansicht wechseln müsste um die Reihenfolge zu ändern.

Für die Implementierung einer Sortierung für die Galerieansicht habe ich ein neues Ticket erstellt:

https://github.com/4teamwork/opengever.core/issues/1892
