### ISSUE TITLE
Papierkorb: No view registered for: tabbedview_view-trash-gallery

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1839]
Galerie im Papierkorb funktioniert noch nicht
![bildschirmfoto 2016-05-24 um 20 18 59](https://cloud.githubusercontent.com/assets/485600/15515133/dfe8c422-21ec-11e6-90bc-7a6e6df11032.png)

**Comment by deiferni** [comment]
Duplikat: https://github.com/4teamwork/opengever.core/issues/1814
