### ISSUE TITLE
Bei Overlay-Ansicht von nur einer Datei keine Navigationsinformationen darstellen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1841]
Wenn in der Overlay-Ansicht nicht zurück oder vorgeblättert werden kann (z.B., wenn ich das Overlay durch Anklicken des Thumbnails in der Detailansicht einer Datei aufrufe), sollen weder Navi-Pfeile noch die 1 (es gibt ja nur 1!) angezeigt werden (oder dann 1/1 anzeigen):

![bildschirmfoto 2016-05-24 um 20 24 18](https://cloud.githubusercontent.com/assets/485600/15515333/ede9d588-21ed-11e6-8a8d-99636b7e131a.png)

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/ftw.showroom/pull/24
