### ISSUE TITLE
Vorschau einer Datei in einer E-Mail wird nicht angezeigt

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1842]
Zudem: Klicke ich die Word-Datei an, lade ich sie runter, statt zum Overlay zu gelangen:

![bildschirmfoto 2016-05-24 um 20 33 48](https://cloud.githubusercontent.com/assets/485600/15515549/fb581fd0-21ee-11e6-8c87-6494f0c8b5a2.png)

Siehe https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/interne-organisation/planung-und-organisatorisches/dossier-2/ogip-15#preview

**Comment by phgross** [comment]
Evtl. schwierig umzusetzen, kurze Analyse ob Umsetzung möglich.

**Comment by phgross** [comment]
Das direkte extrahieren von enthaltenen Anhänge und separate Aufgaben an den Bumblebee Dienst erachte ich als relativ aufwändig, deshalb würde ich dies vorerst nicht umsetzten --> Roadmap.
