### ISSUE TITLE
Galerie-Ansicht im Dokumente-Reiter zeigt E-Mails nicht an

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1843]
Zumindest ein Platzhalter müsste angezeigt werden, idealerweise natürlich eine Vorschau der EML-Datei. Auf keinen Fall dürfen E-Mail-Inhalte in der Galerie-Ansicht ganz ausgeblendet werden!

Anzahl Dokumente in der klassischen Dokumentauflistung in einem Dossier muss gleich gross sein wie Anzahl Dokumente in Galerie-Ansicht!

**Comment by phabegger** [comment]
PS: ZIP-Dateien werden bereits auch in der Galerie-Ansicht anzeigt (obwohl keine Vorschau vorhanden), was ok wäre.

**Comment by phgross** [comment]
Zumindest ein Platzhalter muss zwingend vorhanden sein.

Siehe hierzu auch die Diskussion bezüglich EML-Konvertierung (https://basecamp.com/2768704/projects/7760630/todos/151942219)
