### ISSUE TITLE
Frage: Vorschau von ausgecheckten Dokumenten

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1844]
Wird in GEVER ein Dokument zur Bearbeitung ausgecheckt und verändert, dürfen die Änderungen (in der working copy) für andere Personen erst sichtbar werden, wenn das Dokument wieder eingecheckt wurde. 

Die bestehende Aktion "Kopie herunterladen" lädt jeweils das letzte zuletzt eingecheckte Dokument runter, niemals die Working Copy.

Ist dies mit der PDF-Vorschau jetzt auch noch so gelöst/gewährleistet? Bitte überprüfen.

**Comment by phgross** [comment]
Die PDF Vorschau für ausgecheckte Dokumente steht nicht mehr zur Verfügung sobald das Dokument reindexiert wurde.

Es ist zwar korrekt das keine Vorschau für die WorkingCopy zur Verfügung steht, da andere Benutzer als der aktuelle Bearbeiter, die Änderungen noch nicht einsehen dürfen. Aus meiner Sicht sollte aber sichergestellt werden, dass das PDF der aktuellen Version (nicht die WorkingCopy) zur Verfügung steht.

**Comment by deiferni** [comment]
Update hierzu: es wird auch von der Working-Copy ein Preview erstellt, und zwar sobald man Word (oder was auch immer) schliesst und der OfficeConnector die Datei hochgeladen hat. D.h. hier besteht unbedingt Handlungsbedarf.

**Comment by deiferni** [comment]
Damit man das einfach umsetzen kann braucht es Anpassungen in ftw.bumblebee (u.a. https://github.com/4teamwork/opengever.core/issues/1781)
