### ISSUE TITLE
Suchergebnisse: Overlay-Ansicht eines Dokuments erscheint nicht immer

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1845]
Suche ich nach einem Begriff und sortiere die Trefferliste ein paar Mal um (Datum / alphabetisch), öffnet ein Klick auf ein Thumbnail die Overlay-Ansicht nicht mehr....

![bildschirmfoto 2016-05-24 um 20 49 35](https://cloud.githubusercontent.com/assets/485600/15516039/38e48314-21f1-11e6-8fa0-8ee02d803bef.png)

**Comment by deiferni** [comment]
closed with https://github.com/4teamwork/opengever.core/pull/1876
