### ISSUE TITLE
Falsche Nummerierung in Overlay bei Suchergebnissen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1846]
Beispiel: 

Ich klicke in der folgenden Ansicht auf das Thumbnail des ersten Treffers:

![bildschirmfoto 2016-05-24 um 20 52 50](https://cloud.githubusercontent.com/assets/485600/15516114/969a1348-21f1-11e6-9354-1884071401d8.png)

Ich erwarte nun, dass oben neben dem Titel eine "1" steht (ist ja der erste Treffer), komischerweise erscheint aber eine "2"...

![bildschirmfoto 2016-05-24 um 20 53 09](https://cloud.githubusercontent.com/assets/485600/15516146/cb144d8c-21f1-11e6-96e1-703958bcb8b4.png)

**Comment by elioschmutz** [comment]
In der Suche wir der Titel sowie das Bild als Showroom-Item initialisiert. D.h. egal ob auf den Link oder das Thumbnail geklickt wird, das Overlay wird geöffnet. 

Der Showroom erkennt jedoch nicht, dass es sich um das selbe Dokument handelt. Er behandelt jedes Showroomitem als eigenständiges Dokument. Dieses Verhalten ist in der jetzigen implementation auch korrekt. 

Deshalb wird beim Beispiel oben die Nummer 2 Angezeigt. Dies ist korrekt, da der Textlink die Nummer 1 hat.

---------------

Um dieses Problem zu lösen könnten wir folgendes Umsetzten:

In der Suche wird lediglich das Thumbnail mit dem Overlay verknüpft. Der Titel des Dokuments verlinkt weiterhin direkt auf das Dokument.

Grundsätzlich versuchen wir zwar die Textlinks auch mit dem Overlay zu verknüpfen. Das haben wir bis jetzt konsequent gelöst.

In diesem Fall könnten wir das Verhalten so begründen, dass wir ein Thumbnail anzeigen. Wenn ein Thumbnail und ein Textlink dargestellt werden, ist jeweils das Bild mit dem Overlay und der Text mit der Detailansicht verknüpft.

---------------

Eine andere Möglichkeit wäre dem Showroom das umgehen mit gleichen Links beizubringen. Diese Veränderung benötigt jedoch auch wieder genauere Analysen und ein Konzept, zumal der Showroom auch nicht für diesen Usecase erstellt wurde.

Eine einfachere und meiner Meinung nach sinnvolleren Lösung wäre die Möglichkeit, dass der Showroom das Blättern einfach deaktiviert.

So wird z.B. in der Suche (oder evt. auch in anderen Ansichten) das Overlay immer noch geöffnet wenn auf das Thumbnail oder den Textlink geklickt wird, jedoch werden die verschiedenen Dokumente nicht mehr miteinander Verknüpft.

@deiferni @phgross @lukasgraf @bierik Was denkt ihr dazu? Welchen Weg würdet ihr einschlagen?

**Comment by deiferni** [comment]
Ich denke die Verknüpfung des Overlays mit dem Titel der Dokumente sollten wir so konsistent wie möglich implementieren. So verhält sich das UI bei "gleichen" Elementen gleich, ich denke das fördert auch die Usability. Daher würde ich nicht nur die Thumbnails verlinken, sonder immer beide Elemente der Suchresultate.

NB: beim Blättern erscheinen mit der aktuellen Implementation das gleiche Dokument auch doppelt, das ist sicher auch nicht gewünscht. 

Ich würde daher sicher auch zuerst die Blätterfunktion deaktivieren. 

Als zweiten Schritt kann man sich überlegen ob es Sinn macht im `Showroom` Support für Items mit mehrfacher Räpresentation auf der Page einzubauen.

Wie sehen das die anderen?

**Comment by elioschmutz** [comment]
Folgende Tasks sind für die Umsetzung zu erledigen:

- [ ] Issue https://github.com/4teamwork/ftw.showroom/issues/23
- [ ] Anpassung Markup in `search.pt` gem. https://github.com/4teamwork/ftw.showroom/issues/23
