### ISSUE TITLE
Dokumente, die nur in Papierform vorliegen...

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1847]
... haben kein treffendes Vorschau-Bild:
![bildschirmfoto 2016-05-24 um 20 59 12](https://cloud.githubusercontent.com/assets/485600/15516339/a06ea522-21f2-11e6-922b-0999adee2c0d.png)
Sollte wohl eher etwas wie das sein:
![search](https://cloud.githubusercontent.com/assets/485600/15516358/b5bdb4ae-21f2-11e6-896c-944fdebb0510.jpg)

**Comment by elioschmutz** [comment]
Kannst du bitte nochmal ein neues Fallback-Image für Dokumente in Papierform machen.

**Comment by deiferni** [comment]
Ein rotes Icon würde ich persönlich nicht verwenden, wir haben das mit dem Fehler-icon ausprobiert und das Icon ist dann schon sehr dominant. Im Moment gibt es drei verschiedene Vorschau-Bilder-"Icons":

Vorschaubild noch nicht erstellt:
![screen shot 2016-05-31 at 09 37 36](https://cloud.githubusercontent.com/assets/736583/15666931/b5df359a-2713-11e6-9158-a7c3564cfa39.png)

Dokument nur in Papierform:
![screen shot 2016-05-31 at 09 38 17](https://cloud.githubusercontent.com/assets/736583/15666910/a013df54-2713-11e6-9433-115cc953f8cb.png)

Service nicht ereichbar, Vorschaubild nicht verfügbar:
![screen shot 2016-05-31 at 09 38 36](https://cloud.githubusercontent.com/assets/736583/15666913/a3ac6712-2713-11e6-9b9e-0cc4d12894c4.png)

@phabegger ich schliesse diesen Issue, wenn du oder aufgrund von Kundenfeedback ein Icon ändern willst oder eine bessere Idee hast können wir Ihn gerne wieder eröffnen.
