### ISSUE TITLE
Sortierreihenfolge in Dokument-Reiter wird nicht mehr persistiert

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1850]
Die Dokumentreihenfolge wird nicht mehr persistiert (auf test.opengever.ch funktionert es noch).

Wenn auf einem Dokumentreiter z.B. nach Laufnummer sortiert wird, sollte diese Sortierung gespeichert werden und bei einem späteren Zugriff auf diesen Reiter wieder verwendet werden.

![record](https://cloud.githubusercontent.com/assets/557005/15531099/b32b0168-2258-11e6-9614-a0e5a68fd5ba.gif)

Dieses funktionier leider nicht mehr.

- [x] Soriterreihenfolge in Dokuement-Reiter muss persitiert werden (siehe test.opengever.ch)

**Comment by deiferni** [comment]
Analyse: der `documents-proxy` ist schuld. 

der gridstate wird ausgelesen vom key `'ftw.tabbedview-openever.dossier-tabbedview_view-documents-[userid]'` jedoch unter dem key `'ftw.tabbedview-openever.dossier-tabbedview_view-documents-proxy-[userid]`gespeichert.

Vorschlag, diesen Spezialfall im `DossierGridStateStorageKeyGenerator` lösen und in der `get_key` methode dafür sorgen, dass für beide views der gleiche key verwendet wird.
