### ISSUE TITLE
Geschäftsregel für Dossierabschluss konfigurierbar machen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1871]
Neben der aktuellen Geschäftsregel für den Dossierabschluss soll es künftig auch möglich sein, Dossier abzuschliessen, ohne dass die Dokumente in Subdossiers verschoben werden müssen, sofern bereits Subdossiers existieren.

Oder verständlicher formuliert: Mit der neuen Regel wird nicht mehr geprüft, ob Dokumente _sauber_ abgelegt wurden. 

Die bestehende Geschäftsregel kann weiterhin ausgewählt und konfiguriert werden.

Siehe https://feedback.onegovgever.ch/t/geschaeftsregel-dossier-abschliessen-konfigurierbar-machen/56

*Rapportierung:* `[INTERN] 3.2 OneGov GEVER  - Weiterentwicklung (Enhancement/Feature)`

**Comment by lukasgraf** [comment]
Gemäss Besprechung mit @phabegger:
Den oben beschriebenen Fall für den Moment nicht speziell behandeln.
