### ISSUE TITLE
Nummer vom aktuellen Dokument wird im Batch falsch angezeigt

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1874]
Der Showroom zeigt im Overlay jeweils die Nummer des aktuellen Dokuments sowie das Total an. Die Nummer des aktuellen Dokuments wird vom Showroom automatisch ermittelt da dieser jeweils weiss, vieviele Dokumente es vorher gibt. Dies ist möglich weil wir mit einem Stream arbeiten (Gallery-View).

In der Listenansicht ist dies jedoch nicht mehr der Fall. Die Tabelle funktioniert mit Batching und der Benutzer hat die Möglichkeit z.B. direkt auf Seite Nr. 233 zu Springen und dort ein Dokument mit der Nummer 11656 zu öffnen. Vorherige Dokumente werden nie geladen. Der Showroom kann das aktuelle Dokument somit nicht korrekt ermitteln.

Wir haben also folgende Probleme:

- Der Showroom wurde für einen Stream entwickelt und nicht für ein Batching
- In der Tabelle muss irgendwie ersichtlich sein, das wievielte Dokument das aktuelle Dokument vom Gesamten ist

@jone @deiferni @phgross @bierik Leider sind diese Änderungen nicht einfach so möglich. Der Showroom wurde nicht für das Batching entwickelt. Um eine solche Änderung im Showroom zu implementieren bräuchten wir ein neues Konzept (auch in Verbindung mit der ftw.table) sowie @bierik für die Umsetzung im Showroom. 

Dies wäre frühestens in KW 23 möglich da @bierik noch im Urlaub ist.

Gibt es da andere Lösungswege? Oder erstmal einen Workaround?

Hier noch ein GIF mit dem Problembeschrieb:

![record](https://cloud.githubusercontent.com/assets/557005/15738354/30c35bea-28ab-11e6-9134-9c95387b3d84.gif)

**Comment by jone** [comment]
Ich denke man muss dem "register" dingens ein Offset beibringen. Dieses Offset muss man beim initialisieren angeben.
Das Offset wäre in obigem Beispiel `20`. Wenn mit `prev` zusätzliche Items einfügt muss man dies natürlich beachten (z.b. in `prepend` das `offset` verkleinern).

Das offset könnte z.B. als Konfiguration beim Initialisieren übergeben werden.

**Comment by deiferni** [comment]
See also https://github.com/4teamwork/ftw.showroom/issues/28
