### ISSUE TITLE
No longer display refused tasks as active

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1885]
![screen shot 2016-06-06 at 10 58 01](https://cloud.githubusercontent.com/assets/736583/15816915/9ef08bce-2bd5-11e6-91d5-9e799f61f295.png)

Refused seems to be a final state like cancelled. So we should no longer include refused tasks in the active listings. Ok?

Also see: https://feedback.onegovgever.ch/t/abgelehnte-aufgabe-abschliessen/224

**Comment by phgross** [comment]
Der Status `abgelehnt`, resp. die Transition `ablehnen` dient grundsätzlich dazu den Fall `Ich kann die Aufgabe (zurzeit) nicht erledigen, weil abwesend oder keine Zeit etc..` abzubilden. Es ist im Grunde genommen ein Aufforderung an den Auftraggeber, ein anderer Auftragnehmer zu suchen oder die Aufgabe zu stornieren oder abzuschliessen. 

Grundsätzlich ist es demnach so, dass eine abgelehnte Aufgabe für den Auftragnehmer zwar nicht mehr `aktiv` ist, aber für den Auftraggeber sollte sie durchaus noch aktiv sein, von Ihm wird ein Entscheid bezüglich weiters Vorgehen erwartet. Deshalb wird der Status `abgelehnt` auch nicht als Endstatus einer Aufgabe angesehen. 
Da wir bei den Statusfilter nicht unterscheiden können ob die Ansicht nun als `Auftragnehmer` oder `Auftraggeber` angeschaut wird, musste ein Entscheid gefällt werden für welchen Typ User (Auftragnehmer oder Auftraggeber) die Auflistung optimiert werden soll. Wir haben uns dazumal aus verschieden Gründen für den Auftraggeber entschieden.

**Comment by deiferni** [comment]
Wir zuerst hier diskutiert: https://feedback.onegovgever.ch/t/abgelehnte-aufgabe-abschliessen/224, danach neuer Issue
