### ISSUE TITLE
Display checked-out/locked information in overlay

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1894]
The document-overview shows that a document is checked out out (and/or locked) by a certain user. This information is currently missing in the overlay.

![screen shot 2016-06-07 at 15 22 20](https://cloud.githubusercontent.com/assets/736583/15859089/d94fd2b8-2cc3-11e6-8a76-956b5caf9643.png)

I think we should display in the overlay that a document is checked out (and by whom). Otherwise the checkout buttons are missing but it is unclear why. We should also display the lock part, since we use that (especially in `opengever.meeting`) to lock documents permanently for some reason.

*quick&dirty mockup:*

![screen shot 2016-06-07 at 15 28 58](https://cloud.githubusercontent.com/assets/736583/15859235/8f624dba-2cc4-11e6-8cb2-fc28ca5f71ab.png)

**Comment by elioschmutz** [comment]
closed by #1923
