### ISSUE TITLE
Anpassung Galerieansicht/Detailansicht für IBumblebeeable-Objekte

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#1912]
Momentan wird das `IBumblebeeable` Interface für alle Objekte verwendet, welche in der Galerieansicht angezeigt werden sollen. Die `ftw.bumblebee`-API wird momentan auch für jedes `IBumblebeeable`-Objekt direkt verwendet wie z.B. in der Detailansicht oder in der Suche.

Momentan sind dies:

- `ftw.mail.mail`
- `opengever.document.document`

Zurzeit werden Mails vom Bumblebee nicht unterstützt und bei Dokumenten ist es möglich, dass diese nur in Papierform aufbewahrt werden.

Um nun eben diese Mails und Dokumente z.B. in der Galerie darstellen zu könne, müssen diese als `IBumblebeeable` markiert werden obwohl sie es garnicht sind.

Für die Darstellung der Thumbnails verwenden wir anschliessend die `ftw.bumblebee` Funktionen welche wir in GEVER überschreiben müssen um die o.g. Objekte speziell behandeln zu können. Wir lassen somit `ftw.bumblebee` Sachen erledigen, obwohl wir schon im voraus wissen, dass dies garnicht möglich ist.

z.B:
- https://github.com/4teamwork/opengever.core/blob/master/opengever/bumblebee/__init__.py#L28
- https://github.com/4teamwork/opengever.core/blob/master/opengever/bumblebee/__init__.py#L49

Um diese Design-Problematik beheben zu können benötigen wir einen neuen GEVER-Spezifischen Adapter für Objekte welche eine Vorschau haben (egal ob Bumblebee oder ein statisches Preview-Image).

Bsp. `IGeverVisualRepresentation`

Dieser Adapter stellt diverse Funktionen für das Thumbnail usw. zur Verfügung. Der Adapter entscheidet anschliessend auch, ob ein File mit `ftw.bumblebee` weiterbearbeitet werden muss oder nicht.

Die Galerieansicht, sowie die Detailansichten oder die Suche verwenden anschliessend nur noch den GEVER-Adapter anstatt direkt Funktionen von `ftw.bumblebee`

@deiferni @jone

**Comment by deiferni** [comment]
Die Mail-Vorschau ist nun auch supported.
Das Refactoring hat sich hat sich mit dem Refactoring von ftw.bumblebee (https://github.com/4teamwork/ftw.bumblebee/pull/96) und  dem Umbau der Link-Generierung (https://github.com/4teamwork/opengever.core/pull/1974) vorerst erledigt.

Das nicht-digital verfügbare sollten wir jedoch umsetzen, dazu ein neuer Issue: https://github.com/4teamwork/opengever.core/issues/1976
