### ISSUE TITLE
"Fallback"-Images im Overlay schlecht positioniert

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1917]
Betroffen sind Dokumente die nur auf Papierform verfügar sind.
![screen shot 2016-06-13 at 13 25 16](https://cloud.githubusercontent.com/assets/736583/16005945/688c73b4-316a-11e6-93a1-5cec012922c7.png)
Vermutlich ist auch das Bild, das bei fehlender Bumblebee-Preview dargestellt wird betroffen

**Comment by deiferni** [comment]
We have decided to wait for https://github.com/4teamwork/ftw.bumblebee/issues/90 and the display the iframe only when there is a chance that we get a bumblebee image

**Comment by bierik** [comment]
not reproducible

<img width="1348" alt="bildschirmfoto 2016-07-05 um 17 28 39" src="https://cloud.githubusercontent.com/assets/1637820/16590002/ff7e6c38-42d5-11e6-8da3-4e4e675d88e4.png">

**Comment by deiferni** [comment]
Dossier öffnen -> Hinzufügen -> Dokument (Titel angeben, kein File angeben) -> Speichern

![screen shot 2016-07-05 at 17 33 48](https://cloud.githubusercontent.com/assets/736583/16590180/c11710de-42d6-11e6-8ff6-766a9711f090.png)

**Comment by phgross** [comment]
Platzhalter für Dokumente welche nur in Papierform vorhanden sind, erscheint gar nicht mehr.

**Comment by elioschmutz** [comment]
Mit dem neusten `master`-Branch wird wieder das korrekte Bild angezeigt.
