### ISSUE TITLE
Personen erstellen/bearbeiten

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1928]
Nach dem Modellvorschlag müssen die Relationen zu den Feldern (Adresse, Telefon, ...) korrekt erstellt werden können.

Siehe https://github.com/4teamwork/opengever.core/issues/1926

**Comment by elioschmutz** [comment]
Mockupbeispiele für Personen
![edit-v2](https://cloud.githubusercontent.com/assets/557005/16688110/abb0c47c-451c-11e6-9f90-7a4b397db12e.png)

![show](https://cloud.githubusercontent.com/assets/557005/16688109/abae0a2a-451c-11e6-9e24-8f6f3f746c1e.png)
