### ISSUE TITLE
Organisationen erstellen/bearbeiten

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1929]
Nach dem Modellvorschlag müssen die Relationen zu den Feldern (Adresse, Telefon, ...) korrekt erstellt werden können.

Siehe https://github.com/4teamwork/opengever.core/issues/1926

**Comment by phgross** [comment]
Zurzeit sind keine Arbeiten am Kontaktmodul geplant. Weitere Arbeiten müssten neu koordiniert und definiert werden (Stichwort VueJS, neues Frontend etc.) ich schliessen diesen Issue.
