### ISSUE TITLE
Z.T. Preview PDF nur mit Text "You are being redirected" drin...

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1938]
Irgendwie kriege ich auf lab.onegovgever.ch z.T. komische Preview PDFs:

![bildschirmfoto 2016-06-16 um 22 48 21](https://cloud.githubusercontent.com/assets/485600/16132688/8624253c-3414-11e6-883a-4e300b296d5c.png)

You are being redirected zeigt dabei auf
http://lab.onegovgever.ch/YnVtYmxlYmVl/assets/missing/preview-a58421bab7d7a03200378d9d45a0e82ba926445cac9b6a008b801affca361827.html

Wenn ich das Dokument als PDF herunterladen, klappt es prima.

**Comment by phgross** [comment]
Wir vermuten das diese Meldung aufgrund einer fehlenden Apache Konfiguration auftrat, da fälschlicherweise auf HTTP anstatt HTTPS redirected wurde. Die Konfiguration wurde bereits vor einigen Tagen korrigiert, @phabegger konntest du den Fehler nochmals reproduzieren, sonst schliessen wir das Ticket.

**Comment by phgross** [comment]
Scheint nicht der Fall zu sein, ich schliesse dieses Ticket.
