### ISSUE TITLE
Metadatum Laufnummer nicht in Overlay einblenden

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1939]
Muss nicht separat angezeigt werden, da bereits im Aktenzeichen enthalten.

![bildschirmfoto 2016-06-16 um 22 54 14](https://cloud.githubusercontent.com/assets/485600/16132905/8cb2ceac-3415-11e6-8ac0-6dcf38fc0a98.png)

**Comment by phgross** [comment]
Wurde mit der Überarbeitung des Overlays bereits umgesetzt.
