### ISSUE TITLE
Beschreibungsfeld einer Datei im Overlay anzeigen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1940]
Im Moment wird nur der Titel angezeigt. Bitte auch Beschreibungsfeld einblenden/anzeigen. Ich schlage vor, gleich unterhalb des Titels einzublenden (falls vorhanden)

![bildschirmfoto 2016-06-16 um 22 58 47](https://cloud.githubusercontent.com/assets/485600/16133005/f6da5444-3415-11e6-8436-300402932aaf.png)

**Comment by phgross** [comment]
Wurde mit dem neuen Overlay umgesetzt ![bildschirmfoto 2017-11-30 um 16 59 45](https://user-images.githubusercontent.com/485755/33440291-e4becf74-d5ef-11e7-85dd-dba5bcf19129.png)
