### ISSUE TITLE
Vorschau bei ausgecheckten, überarbeiteten Dokumenten nicht korrekt

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#1942]
Ich checke ein Dokument aus und überarbeite es mit dem Office Connector. Nach Beendigung meines Editors schreibt der Office Connector das Dokument zurück.

Gehe ich nun zum ausgecheckten Dokument zurück, wird nach wie vor die gleiche Vorschau wie vor der Veränderung angezeigt, was verwirrend ist. Ich hätte jetzt erwartet, dass ich ein aktualisiertes Vorschaubild erhalte.

Ich schlage vor, in diesem Fall entweder gar keine Vorschau mehr anzuzeigen (da keine aktuelle vorhanden). Oder eine neue Vorschau rechnen lassen - allerdings darf die dann nur bei mir (als "Auschecker") angezeigt werden, nicht für die anderen Benutzer.

![bildschirmfoto 2016-06-16 um 23 00 58](https://cloud.githubusercontent.com/assets/485600/16133211/f011ffb2-3416-11e6-9715-4081ee528735.png)

**Comment by phgross** [comment]
Duplikat von #2992 ich schliesse deshalb diesen Issue.
