### ISSUE TITLE
Dokumentansicht: Aktionen nicht sinnvoll umgebrochen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#1962]
Mit der Aktivierung von Bumblebee werden bei einem kleineren Bildschirm (13") die Dokument-Aktionen `Dokumente auschecken` oder `Kopie Herunterladen`  nicht sinnvoll umgebrochen.

<img width="877" alt="bildschirmfoto 2016-06-23 um 09 12 26" src="https://cloud.githubusercontent.com/assets/485755/16294855/7fcb4e90-3923-11e6-9456-cc2c1d29b2ac.png">

**Comment by phgross** [comment]
Ähnliches Problem bei einem eingereichten Dokument:

![bildschirmfoto 2016-06-24 um 11 49 41](https://cloud.githubusercontent.com/assets/485755/16334528/c3b0f23e-3a01-11e6-8e21-79e5517e9010.png)

Bitte auch gleich korrigieren.

**Comment by lukasgraf** [comment]
Dies sollte am ehesten so angepasst werden, dass die Leerzeichen zwischen Wörtern mit `&nbsp;` vor Umbruch geschützt werden, und dafür nach dem Pipe-Symbol `|` mit `&shy;` eine Sollbruchstelle definiert wird.

**Comment by elioschmutz** [comment]
`&shy;` kann hier leider nicht verwendet werden. Dies ist ein Softumbruch und fügt bei einem Umbruch ein `-` ein was für Worttrennungen verwendet werden sollte.

Das Problem kann aber ganz einfach mit bisschen CSS gelöst werden. Hier ein Beispiel:

Wenig Platz:
![bildschirmfoto 2016-06-28 um 15 53 01](https://cloud.githubusercontent.com/assets/557005/16418051/868c6f42-3d48-11e6-9f3a-fd6fbb890068.png)

Viel Platz:
![bildschirmfoto 2016-06-28 um 15 54 48](https://cloud.githubusercontent.com/assets/557005/16418090/b050ef2e-3d48-11e6-8447-1c3ea16abe2b.png)

@phgross @lukasgraf ist das für euch i.O wenn ich das so Umsetze?

**Comment by elioschmutz** [comment]
Oder so, was mir persönlich noch besser gefällt:

Version 2
=======
![bildschirmfoto 2016-06-28 um 15 58 40](https://cloud.githubusercontent.com/assets/557005/16418240/3eca5556-3d49-11e6-8324-4caf4c9b4062.png)

**Comment by elioschmutz** [comment]
Habe V2 umgesetzt. Siehe PR oben.
