### ISSUE TITLE
Don't register non digitally available documents with bumblebee

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1976]
Those will never ever have a preview, so we should not register them with bumblebee in the first place.

**Comment by elioschmutz** [comment]
"Dokumente in Papierform" werden nie in Bumblebee abgespeichert.

Da "Dokumente in Papierform" keine Checksumme haben, werden diese implizit auch nicht in Bumblebee registriert:

https://github.com/4teamwork/ftw.bumblebee/blob/master/ftw/bumblebee/document.py#L88

@deiferni kannst du das bestätigen?

**Comment by deiferni** [comment]
Ah, ja das kann sein, das ist aber im Moment eher ein Eide-Effect dieses Statements, d.h. der Code macht per Zufall das, was wir wollen.

Wir müssen das unbedingt explizit noch irgendwo reinprogrammieren 😉  und durch einen Test beschreiben (falls noch nicht vorhanden), so dass es auch klar verständlich wird. Ich würde vorschlagen die `is_convertable` Methode des `IBumblebeeDocument` Adapters zu überschreiben. Afaik haben wir schon einen Adapter für opengever.document.document.
