### ISSUE TITLE
Prevent multiple clicks on schedule button

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#1990]
Currently the schedule button can be clicked multiple times if the users is fast enough (or if the response is too slow) which leads to an error.

sentry: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/493/

We should prevent that by e.g. displaying a spinner while the request is processed.

Adding some `sleep` to the schedule functions makes this easier to reproduce:
```diff
diff --git a/opengever/meeting/browser/resources/meeting.js b/opengever/meeting/browser/resources/meeting.js
index 13924c1..e06932c 100644
--- a/opengever/meeting/browser/resources/meeting.js
+++ b/opengever/meeting/browser/resources/meeting.js
@@ -306,7 +306,17 @@

     this.render = function(data) { return self.template({ proposals: data.items }); };

+    function sleep(milliseconds) {
+      var start = new Date().getTime();
+      for (var i = 0; i < 1e7; i++) {
+        if ((new Date().getTime() - start) > milliseconds){
+          break;
+        }
+      }
+    }
+
     this.schedule = function(target) {
+      sleep(2000);
       return $.post(target.attr("href")).done(function() { $("#filter-proposals").val(""); });
     };
```

**Comment by bierik** [comment]
@deiferni a tip:
I would use the `network throttling` for testing this kind of issues in the chrome developer tools:
![screen shot 2016-09-16 at 10 45 22](https://cloud.githubusercontent.com/assets/1637820/18580297/03b108ca-7bfb-11e6-9632-a53ad5efd954.png)

**Comment by deiferni** [comment]
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/493/
