### ISSUE TITLE
Navigation Protokollierung funktioniert nicht mehr

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2002]
Durch click auf die Navi konnte man direkt zu den entsprechenden Punkten springen. Dies scheint nicht mehr zu funktionieren.

![screen shot 2016-07-07 at 12 02 39](https://cloud.githubusercontent.com/assets/736583/16649761/ba54bf02-443a-11e6-8f16-7f5c1401bc45.png)

**Comment by bierik** [comment]
Fixed through https://github.com/4teamwork/opengever.core/pull/2007
