### ISSUE TITLE
Vorschau für protokoll nicht verfügbar weil locked

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2004]
Es muss der lock-type überprüft werden, bei den `opengever.meeting` spezifischen locks kann eine Vorschau dargestellt werden, nur falls das Dokument durch einen User gesperrt/ausgecheckt wurde darf die Vorschau nicht aktualisiert werden.

**Comment by phgross** [comment]
@deiferni prüfen.

**Comment by deiferni** [comment]
Nicht mehr Aktuell. Soweit ich sehe funktioniert die Vorschau für:
- Protokoll (In der Sitzung)
- Protokollauszug (Im Ursprungsdossier)
auch wenn sie vom System gesperrt sind.
