### ISSUE TITLE
opengever.pdfconverter an bumblebee anpassen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2020]
`opengever.pdfconverter` soll nur dann aktiv sein, wenn `ftw.bumblebee` nicht aktiviert ist. D.h. man müsste die `PDFCONVERTER_AVAILABLE` import booleans so umschreiben, dass sie auch noch `is_bumblebee_feature_enabled` berücksichtigen; `PDFCONVERTER_AVAILABLE and not is_bumblebee_feature_enabled()`, oder direkt in eine Funktion auslagern.

**Comment by lukasgraf** [comment]
@deiferni und zusätzlich vorhandene Funktionalität in `opengever.pdfconverter` konditional von der Verfügbarkeit von Bumblebee machen, z.B. Event-Handler.
