### ISSUE TITLE
set_default_with_acquisition does not support falsy values as a fallback default

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2029]
Because [`set_default_with_acquisition` is using `None`](https://github.com/4teamwork/opengever.core/blob/b8ab7ddb02bb87b624a92f69bf2c8669d97dad5b/opengever/base/behaviors/utils.py#L158) instead of a sentinel value, and checks for [`if field._acquisition_default`](https://github.com/4teamwork/opengever.core/blob/b8ab7ddb02bb87b624a92f69bf2c8669d97dad5b/opengever/base/behaviors/utils.py#L186), `None` or other falsy values cannot be used as fallback defaults.

**Comment by lukasgraf** [comment]
Still relevant: https://github.com/4teamwork/opengever.core/blob/master/opengever/base/acquisition.py#L76

**Comment by deiferni** [comment]
No longer relevant with default value patches in place.
