### ISSUE TITLE
Mail/Dokument-Titel mit Whitespace komisch umgebrochen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2046]
Scheint Dokumente ohne Datei und Mails zu betreffen
![screen shot 2016-07-21 at 15 12 50](https://cloud.githubusercontent.com/assets/736583/17023868/c6b3896a-4f55-11e6-9ff6-6bbe61f19524.png)

**Comment by phgross** [comment]
Kann ich nicht reproduzieren oder mir fehlen die nötigen Informationen:

 - in welcher Ansicht besteht dieses Problem?
 - auf lab oder Dev reproduzierbar?

**Comment by deiferni** [comment]
Lässt sich nicht mehr reproduzieren.
