### ISSUE TITLE
collective.quickupload doesn't abort transaction on upload failure

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2053]
When `collective.quickupload` encounters an exception during file creation, [it catches the (any) exception](https://github.com/collective/collective.quickupload/blob/9e0eff60b3a5b908cd82d9b2ec7e9daa978faca6/collective/quickupload/browser/quick_upload.py#L771-L775) and sends a proper JSON failure message back to the client.

It does not however abort the transaction. This leads to the transaction still being committed (because the excetion was handled), and might result in half-processed documents being left behind (missing full text indexing, missing doc properties update).

An easy way to reproduce this issue is to upload the attached password protected DOCX document:
[protected_document.docx](https://github.com/4teamwork/opengever.core/files/377775/protected_document.docx)

**Comment by deiferni** [comment]
See https://github.com/collective/collective.quickupload/pull/59
