### ISSUE TITLE
Recognize password protected documents

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2054]
⚠️ Estimation refers to further evaluation, not a final implementation yet ⚠️ 

---

We should attempt to recognize password protected documents and enable us to deal with them gracefully. We might want to:
- suppress updating doc properties for protected DOCX documents
- avoid sending password protected documents to Tika for full text indexing
- disallow uploading password protected documents to GEVER alltogether

Currently, this isn't handled at all, and uploading a password protected document like the attached DOCX will lead to `BadZipeFile` errors, for example when trying to update doc properties.

[protected_document.docx](https://github.com/4teamwork/opengever.core/files/377783/protected_document.docx)

**Comment by lukasgraf** [comment]
Using `python-magic` it seems we could at least recognize password protected DOCX documents, but not PDFs:

```python
>>> import magic
>>>
>>> magic.from_file("/Users/lukasgraf/Documents/SampleDocuments/protected.docx")
'CDFV2 Encrypted'
>>>
>>> magic.from_file("/Users/lukasgraf/Documents/SampleDocuments/protected.pdf")
'PDF document, version 1.4'
>>>
```

**Comment by lukasgraf** [comment]
Related: #2053

**Comment by phgross** [comment]
@phabegger wie wollen wir mit solchen Dateien umgehen, in meinen Augen wäre es sinnvoll wenn solche Dateien gar nicht erst im GEVER abgelegt werden könnten. Wollen wir die Frage im Feedback-Forum diskutieren?

**Comment by phgross** [comment]
Feedback-Forum Diskussion abwarten.

**Comment by Rotonen** [comment]
http://pybrary.net/pyPdf/pythondoc-pyPdf.pdf.html#pyPdf.pdf.PdfFileReader.isEncrypted-attribute

**Comment by lukasgraf** [comment]
**Besprechung mit @buchi**:
- Lieber keine Lösung die auf einer Standalone-Verwendung von Tika (also `ftw.tika`) basiert. Da wir Solr mittelfristig für jedes GEVER-Deployment einsetzen wollen, wäre das eine unnötige Zweispurigkeit
- `file` utility bzw. [`libmagic`](https://linux.die.net/man/3/libmagic) basierende Python bindings evaluieren - in aktuellen Versionen können diese evtl. Passwortgeschützte Dokumente erkennen
- Andere Python-Libraries die binäre Dokumente selbst parsen sind nicht bedenkenlos einsetzbar: Wenn das Parsen von binären Dateiformaten nicht robust genug implementiert ist, kann dies zu hässlichen Problemen führen wie Memory-Leaks, Unbounded memory growth, sehr hohe Laufzeit, ...
- `ftw.solr` liefert bei einer nicht erfolgreichen Solr-Response bereits die Information zurück, dass das Dokument nicht indexiert werden konnte, weil es verschlüsselt ist. Challenge: Die Volltext-Extraktion in Solr passiert erst sehr spät (post commit hook)
