### ISSUE TITLE
Mailadressen-Ansicht und Mailadressen Editformular nach Contact-View verscheiben

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2058]
Momentan können z.B. Email-Adressen nur im Editformular von einem Kontakt hinzugefügt bzw.  bearbeitet werden. Im Add-Form ist das bearbeiten oder hinzufügen nicht möglich, da der Kontakt noch nicht existiert und somit die Relationen nicht hergestellt werden können.

Damit ein Benutzer eine E-Mailadresse hinzufügen kann müsste er:
1. Einen Kontakt erstellen und diesen abspeichern
2. den Kontakt wieder bearbeiten und die E-Mailadressen nacherfassen

zudem ist das Edit-Formular für den Benutzer sehr verwirrend, da sich das Verhalten der Formulare je nachdem ändert. So ist z.B. beim das Hauptformular für Kontakt-Attribute ein normales z3c-Form welches mit dem "Speichern"-Button abgespeichert oder mit dem "Abbrechen"-Button abgebrochen werden kann. Die restlichen Formulare wie eben das Formular für die Mailadressen sind hingegen Handlebars-Templates welche per AJAX jede Änderung direkt in der DB abspeichern. Ein Benutzer wird diese unterschiede nich erkennen.

Aus diesen Gründen wurde entschieden, dass wir die Handlebars-Formulare wieder aus der Edit-View vom Kontakt entfernen und dafür eine Inline-Editierung direkt in der Default-View eines Kontaktes anbieten.

Mit einem Knopf kann der Benutzer zwischen dem Editiermodus Umschalten und die Adressen direkt bearbeiten.
- [ ] Formular von der Edit-View zur default-View verscheiben
- [ ] Umschalten von Editier/View Modus für Adresen implementieren
- [ ] Generisches Delete-Promt als Handlebars-Template
- [ ] Tests

**Comment by phgross** [comment]
Zurzeit sind keine Arbeiten am Kontaktmodul geplant. Weitere Arbeiten müssten neu koordiniert und definiert werden (Stichwort VueJS, neues Frontend etc.) ich schliessen diesen Issue.
