### ISSUE TITLE
OGDS-Updater doesn't fully support nested groups yet

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2083]
If using an ActiveDirectory LDAP Plugin to access Microsoft AD, the `members` property may not only contain users, but also (nested) groups.

**Comment by phgross** [comment]
@lukasgraf ist aus meiner Sicht erledigt, oder?

**Comment by lukasgraf** [comment]
Still open (AI)

**Comment by deiferni** [comment]
Das Ticket dazu wurde geschlossen.
