### ISSUE TITLE
Avoid XSS vulnerabilities when not using templating engines to produce HTML

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2085]
In some places, we produce HTML without using a templating engines (e.g. [in `opengever/base/contentlisting.py](https://github.com/4teamwork/opengever.core/blob/f503356ecbab66972b551041b17d2c4ed3a83f2c/opengever/base/contentlisting.py#L122)

When HTML resulting from such hand-made templating is inserted in templates using `tal:content="structure ..."` there is the potential for an XSS vulnerability if any of the parameters are user-controlled

**Comment by phgross** [comment]
Das Problem im contentlisting wurde durch #2080 behoben.

Ich lasse den Issue aber noch offen damit wir im Rahmen des nächsten Releases, die restlichen `tal:content="structure ..."` noch überprüfen können.
