### ISSUE TITLE
Importscript für Kontakte

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2090]
Für das neue Kontakt-Modul im GEVER benötigen wir ein Importscript.

- [x] Daten müssen als CSV importiert werden können
- [x] Script soll über `bin/instance run` gestartet werden können
- [x] für jede Tabelle wird ein eigenes CSV existieren (person, organisation, mail, address...)
- [ ] gelöschte Daten müssen erkannt werden
- [ ] bestehende Daten müssen aktualisiert werden

**Comment by elioschmutz** [comment]
PR: https://github.com/4teamwork/opengever.core/pull/2097

**Comment by elioschmutz** [comment]
@phgross wie sieht es aus mit diesem Issue? Ist das nun auf Eis gelegt? Kann ich mich als Assignee vorerst entfernen?

**Comment by lukasgraf** [comment]
@elio has been closed via #2097

**Comment by elioschmutz** [comment]
👍  super! Merci
