### ISSUE TITLE
SaaS activate bumblebee

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2095]
1. install release, execute upgradesteps

2. calculate bumblebee_checksum for all documents (also reindexes `object_provides`) - cannot handle conflicts
`bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/bumblebee_installation.py -m reindex`
_took 124 secs for 1243 documents_

3. calculate history/archive checksums for all documents - cannot handle conflicts
`bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/bumblebee_installation.py -m history`
_took 207 secs for 1243 documents_

4. activate bumblebee in registry (or do so through the web)
`bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/bumblebee_installation.py -m activate`

5. store all documents in bumblebee - can handle conflicts (so this can be done during production and will resume, it will show a placeholder for all documents not yet stored)
`bin/instance run src/opengever.maintenance/opengever/maintenance/scripts/bumblebee_installation.py -m store`
_took 234 secs for 1243 documents_

**Comment by phgross** [comment]
Release deployed on test.onegovgever.ch/fd and bumblebee activated:

2) _took 56 sec for 531 documents_ 
3) _took 35 sec for 531 documents_ 
5) _took58 sec for 531 documents_
