### ISSUE TITLE
update documentation "Kurzreferenz OneGov GEVER"

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2102]
Einstellung Listen in Word-Styles

In den Sitzungs- und Protokollverwaltungs-Dokumenten können Bullet-Lists (unordered) sowie Numbered-Lists (ordered) erstellt werden. Diese müssen vorgängig in den Word-Styles definiert werden, damit diese dann in den automatisch generierten Protokollen aus OneGov GEVER korrekt angezeigt werden. Diese kann folgendermassen eingestellt werden:

1.	Gehen Sie auf Format / Style...
2.	Klicken Sie bei „List“ auf „All Styles“ 

![bild-1](https://cloud.githubusercontent.com/assets/20790360/17859293/4b4eb176-6889-11e6-8698-c17ecabd7b97.png)

3.	Wir stellen zuerst die Number-List ein. Daher wählen Sie oben bei „Styles“ in der Liste „List Number“ an und klicken Sie anschliessend auf Bearbeiten/Modify.

![bild-2](https://cloud.githubusercontent.com/assets/20790360/17859312/5c8d9dda-6889-11e6-892a-f7dc88840d9c.png)

4.	Es öffnet sich eine neue Maske. Zuunterst finden Sie das Dropdown „Format“. Wählen Sie dort Numbering an, um die weiteren Einstellungen vorzunehmen.

![bild-3](https://cloud.githubusercontent.com/assets/20790360/17859326/700b4bc8-6889-11e6-9cdb-9ea57553772a.png)

5.	In der neuen Maske wählen Sie unter „Outlined Numbered“ die unten blau umrandete Aufzählungs-Liste aus. Bestätigen Sie zweimal mit „OK“ (Bei der Maske „Bullets and Numbering“ sowie bei „Modify Style.)

![bild-4](https://cloud.githubusercontent.com/assets/20790360/17859410/ca28d63e-6889-11e6-9523-ea98cc5a2d11.png)

6.	Nun stellen wir die Bullet-List ein. Unter „List“ wählen Sie wieder „All Styles“ an, oben können Sie „List Bullet“ anwählen und klicken anschliessend wieder auf Modify/Bearbeiten. 
7.	Unter „Outline Numbered“ wählen Sie die unten im Printscreen blau umrandete Liste. Klicken Sie anschliessend auf Customize/Anpassen.

![bild-5](https://cloud.githubusercontent.com/assets/20790360/17859338/7c0f7642-6889-11e6-8c76-7d1c6c3f26b0.png)

8.	Wie Sie sehen können, wird per Default pro Level ein anderes Sonderzeichen eingesetzt. Zur Vereinheitlichung können Sie nun auf jedem Level jeweils unter „Number style“ den kleinen Bullet-Point anwählen. Bestätigen Sie wieder zweimal mit „OK“. (Bei „Customize und Bullets and Numbering“, bei „Bullets and Numbering“ sowie bei „Modify Style“.)

![bild-7](https://cloud.githubusercontent.com/assets/20790360/17859352/89664708-6889-11e6-8bf3-19cbc56c141d.png)

9.	Wenn Sie wieder auf der Übersicht sind, sehen Sie, dass die „List Number“ sowie die „List Bullet“ nun in den „Styles in Use“-Liste sind. Zum Abschluss können Sie die beiden neuen Listen-Einstellungen noch mit „Apply/Anwenden“ bestätigen.

**Comment by deiferni** [comment]
@livschal thanks, docs are now updated published
