### ISSUE TITLE
suggestion help text meeting template

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2103]
Wie besprochen ein Vorschlag, wie die Hilfetexte für die Sitzungs- und Protokollverwaltungs-Vorlage lauten könnte. Kann teilweise noch kürzen, falls zu lang oder ausschmücken, wenn zu kurz.

Rechtsgrundlage: Beschrieb der rechtlichen Grundlage, worauf der Antrag abgestützt ist

Ausgangslage: Herleitung des Antrages, IST-Situation

Antrag: Konkreter Beschrieb des Antrages mit allen relevanten Informationen

Erwägungen: Beschrieb zusätzlicher Informationen und/oder weiterführenden Überlegungen, welche für Entscheidungsträger zum Beschluss des Antrages relevant sind

Diskussion: Festhalten der während in Sitzung diskutierten Punkte

Beschlussentwurf: Beschrieb wie Beschluss gemäss Partei, welche Antrag eingereicht hat, lauten soll

Beschluss: Festhalten des in Sitzung definierten und finalen Beschlusses

Veröffentlichung in: Angabe, wo Beschluss kommuniziert werden soll (z.B. Pressemitteilung auf Website, Zeitung, intern etc.)

Zu eröffnen an: Auflistung aller an Antrag beteiligten Stellen und Personen, welche primär über Beschluss informiert werden müssen

Kopie z.K.: Auflistung aller sekundär zu informierenden Stellen und Personen

**Comment by deiferni** [comment]
Nicht mehr länger relevant #2829.
