### ISSUE TITLE
Feld Öffentlichkeitsstatus (public_trial) ist beim Bearbeiten einer Ordnungsposition nicht sichtbar

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2110]
Getestet auf demo.onegovgever.ch 
![bildschirmfoto 2016-08-24 um 17 11 35](https://cloud.githubusercontent.com/assets/20790360/17936066/db125868-6a1d-11e6-89a4-350d4fd87c75.png)

- Ist dies bewusst auf der Bearbeitungsmaske ausgeblendet? 
- Wenn die Excel-Vorlage eingelesen wird, wid diese Information trotzdem hinterlegt, auch wenn nicht sichtbar?

**Comment by lukasgraf** [comment]
@livschal das ist richtig, das ist Absicht 😜 

Dies wurde gemäss OGIP-6 umgesetzt: https://my.teamraum.com/workspaces/onegov-gever-innovation-session/improvement-proposals/ogip6-umsetzung-offentlichkeitsgesetz/

> **2.4.4 Mutation der Metadaten zum Öffentlichkeitsstatus**
>
> Die Metadaten zum Öffentlichkeitsstatus sollen nur noch auf Ebene Dokument (reguläre
Dokumente und E-Mails) geändert werden können. Auf allen anderen Objekttypen werden
die beiden Metadaten zum Öffentlichkeitsstatus ausgeblendet und haben keine Funktion
mehr. Neu erstellte Objekte des Typs Ordnungsposition oder Dossier werden intern mit dem
konfigurierten Defaultwert für das Feld „Öffentlichkeitsstatus“ erstellt, **der Wert wird aber wie
beschrieben im User-Interface ausgeblendet und hat keine Funktion mehr. Für diese
Objekte wird das Feld auch in der Byline und in den Eigenschaften ausgeblendet.**

Bezüglich der Excel-Vorlage sollte es sich also so verhalten, dass ein eventuell im Excel-Sheet vorhandener Wert ignoriert wird (und stattdessen der Default verwendet wird).

**Comment by phabegger** [comment]
Für mich stellen sich hier Folgefragen: 

- Wo wird der aktuell eingestellte Öffentlichkeitsstatus angezeigt? Nur noch auf den jeweilig erzeugten Dokumenten (unter Eigenschaften)?
- Der Öffentlichkeitsstatus muss offenbar pro Mandant als Default hinterlegt werden. Müsste damit auch in unsere Checkliste, oder?

Zusammenfassend kann man festhalten, dass die Spalte Öffentlichkeitsstatus in der Excel-Vorlage gar nicht mehr benötigt wird. Ich schlage vor, dass diese entfernt wird (neuer Issue erstellen?). Dies verwirrt nur den Kunden.

**Comment by lukasgraf** [comment]
@phabegger 
> Wo wird der aktuell eingestellte Öffentlichkeitsstatus angezeigt? Nur noch auf den jeweilig erzeugten Dokumenten (unter Eigenschaften)?

Genau. Nach dem ÖffG gibt es nur noch für dokumentartige Objekte das Konzept eines Öffentlichkeitsstatus, und er wird auch nur auf diesen noch dargestellt.

> Der Öffentlichkeitsstatus muss offenbar pro Mandant als Default hinterlegt werden. Müsste damit auch in unsere Checkliste, oder?

Ist bereits drin. Sheet "Konfiguration", Zeile 19, "Öffentlichkeitsstatus".

> Zusammenfassend kann man festhalten, dass die Spalte Öffentlichkeitsstatus in der Excel-Vorlage gar nicht mehr benötigt wird. Ich schlage vor, dass diese entfernt wird (neuer Issue erstellen?). Dies verwirrt nur den Kunden.

Stimmt, die wird tatsächlich nicht mehr benötigt. Ist entfernt (79f6e631).
