### ISSUE TITLE
Testing: Create a common content fixture to speed up tests

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2114]
Our test suite currently takes way too long to run (~20min), so much so that it negatively affects productivity.

We should attempt to create a layer that includes a content fixture with commonly used content so that it doesn't need to be set up / torn down in each test.

**Comment by phgross** [comment]
The content fixture has been introduced in the last months (see https://github.com/4teamwork/opengever.core#example-integration-test-with-browser).
