### ISSUE TITLE
Copying a mail creates a version by mistake

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2127]
During the bumblebee activation we detected some mails with versions. The reason for this wrong version, mails are not versionable, is the `create_initial_version` event handler in og.base (see https://github.com/4teamwork/opengever.core/commit/8a69d541)

**Comment by phgross** [comment]
@tarnap please double check if that issue still exists.

**Comment by tarnap** [comment]
It has been fixed with PR #2778
