### ISSUE TITLE
Update Vorlage Ordnungssystem

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2148]
Wie besprochen bitte überprüfen, ob folgendes, welches wir für Nidau definiert haben, generell gilt. Die jeweiligen Stellen sind im Doc. rot markiert.
- retention_period : Muss in jedem Feld ein Wert sein?
- archival_value: Hat ein Child den Status "Noch nicht geprüft", "Anbieten", "Archivwürdig", "Nicht archivwürdig" oder "Sampling", muss sein Parent zwingend den Status "Nicht geprüft" haben.
- valid_from: Pflichtfeld
- valid_until: Kein Pflichtfeld

[ordnungssystem-edit-ls.xlsx](https://github.com/4teamwork/opengever.core/files/463960/ordnungssystem-edit-ls.xlsx)

**Comment by phgross** [comment]
Dieser Issue ist nicht mehr aktuell: Die aktuelle [Ordnungssystem Vorlage](https://github.com/4teamwork/opengever.core/blob/master/opengever/examplecontent/profiles/repository_minimal/opengever_repositories/ordnungssystem.xlsx) ist im Readme verlinkt.
