### ISSUE TITLE
Styling error-messages Dokument nicht korrekt

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2156]
Styles fehlen:

![screen shot 2016-09-14 at 16 31 31]
(https://cloud.githubusercontent.com/assets/736583/18516336/d5ad2fc0-7a98-11e6-8b96-86ec3968a7ec.png)

Reproduzieren:
- Dossier öffnen
- Dokument hinzufügen
- Speichern ohne Datei und Titel anzugeben

Sollte analog der sonstigen Fehler gestyled werden:

![screen shot 2016-09-14 at 16 32 48](https://cloud.githubusercontent.com/assets/736583/18516363/ea791568-7a98-11e6-9a49-57da4d313c35.png)

**Comment by bierik** [comment]
@deiferni Irgendetwas ist hier ganz faul

"korrektes" Markup:
![screen shot 2016-09-16 at 10 30 51](https://cloud.githubusercontent.com/assets/1637820/18579958/fbfb4cdc-7bf8-11e6-8c7c-fcbf4e810ca5.png)

Das Markup bei einer Fehlermeldung die funktioniert sieht völlig anders aus. Aber auch hier sind 4 leere `div`s.

falsches Markup:
![screen shot 2016-09-16 at 10 34 32](https://cloud.githubusercontent.com/assets/1637820/18580006/55d98c50-7bf9-11e6-8458-e758d24144f3.png)

Bei der `document hinzufügen`-view sieht das Markup völlig anders aus.

Hast du da eine Idee. Ich denke du kennst dich hier mit `z3c.form` besser aus als ich.

**Comment by deiferni** [comment]
Die Bedingung wird nicht wie sonst mit einem Field-Validator geprüft sondern mit einer Invariante (http://docs.plone.org/external/plone.app.dexterity/docs/advanced/validators.html#invariants). Dies weil mehrere Felder betroffen sind. Dadurch wird die Fehlermeldung auch nicht für ein bestimmtest Feld gerendert, sonder global für das Formular. Dafür müsste man nun auch noch styles definieren.
