### ISSUE TITLE
Neue Funktionalität: Persönliches Dossier bzw. Persönliche Ablage

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2158]
### Beschreibung

Jedem Benutzer soll eine Möglichkeit geboten werden, wichtige persönliche Dokumente in einem persönlichen Bereich im GEVER abzulegen und GEVER like weiterverarbeiten zu können.

Dabei gelten folgende Regeln:
- Der Zugriff in den persönlichen Bereich ist nur für den entsprechenden Benutzer oder `Manager` möglich
- Das Verschieben von Inhalt aus dem Ordnungssystem in die persönliche Ablage ist nicht möglich.
- Das Referenzieren von Dokumente in der persönlichen Ablage aus dem Ordnungssystem ist nicht möglich.
- Die Inhalte der persönlichen Ablage sind über die Such auffindbar, selbstverständlich nur für den entsprechenden Benutzer.
- Aufgaben und Anträge aus persönlichen Dossier sind nicht möglich.
- Das Verschieben von Dokumente ins Ordnungssystem ist möglich.
### Vorschlag Umsetzung:

Allgemein gilt:
- Feature muss via Flag aktiviert/deaktiviert werden können

Neuer Typ `HomeFolder`
- Wird bei Erst-Anmeldung eines Benutzers automatisch erstellt
- Leseberechtigung ist auf den `Owner`  (entsprechender Benutzer) und `Manager` eingeschränkt
- Verhält sich gleich wie ein Ordnungsposition, will heissen:
  - Listet alle enthaltenen Dossiers in einem Tab `Dossier` auf
  - Können Dossiers hinzugefügt werden (nur `HomeDossiers`)

Neuer Dossiertyp `HomeDossier`:
- Können Dokumente, Mails und Subdossier enthalten
- Verwendet Dossier Workflow
- Können nur Dokumente, Mails und Subdossier enthalten
- Besitzt eine Mail-In Adresse

UI:
- Neuer Reiter `Persönliche Ablage` in der Persönlichen Übersicht der alle HomeDossiers auflistet
  
  _Alternative:_
- Neuer Hauptreiter `Persönliche Ablage`
- Kein Portlet auf der linken Seite.
### Weiter Infos:

Die PHVS setzt aktuell bereits ein [Persönliches Dossier](https://github.com/4teamwork/opengever.phvs/blob/master/opengever/phvs/homefolder.py) ein, diese Funktionalität soll mit der hier skizzierten Lösung abgelöst werden. 
Zur Info Zahlen der PHVS (Stand September 2016):
- Aktuell 383 HomeFolders
- Aktuell 1652 HomeFolder Dossiers
### Offene Fragen
- Welche Metadaten Felder sollen für die HomeFolders, HomeDossiers zur Verfügung stehen?
### Mögliche Erweiterungen
- Der Platz soll via Quota Pro Benutzer limitiert werden können.

**Comment by phgross** [comment]
@phabegger @lukasgraf @deiferni seht ihr alternativen zu meinem Umsetzungsvorschläge oder weitere Risiken/Probleme?

**Comment by deiferni** [comment]
tönt grundsätzlich 👍 

- Wie sieht es mit löschen von Inhalten aus? Oder anders gefragt soll der HomeFolder auch den GEVER-Richtlinien unterliegen und der Nachvollziebarkeit dienen, oder sieht man das hier weniger strikt und könnte löschen von Dokumenten/HomeDossiers erlauben? Evtl. ist es aber auch einfacher dies genau gleich wie bei den Dossiers/Dokumenten, die im Ordnungssystem abgelegt sind, zu handhaben und kein löschen zu erlauben.
- nur noch zur Klarheit würde ich erwähnen wo werden die HomeFolders erstellt werden. Würdest du dafür einen `HomeFolderContainer` in der Plone-Site erstellen? 
- Der Homefolder müsste für den Benutzer erreichbar sein damit man Plone-Ish Inhalte hinzufügen kann, d.h. nur die Dossiers auflisten wird vermutlich nicht genügen?

**Comment by phgross** [comment]
**Löschen:**
Löschen würde ich gleich handhaben wie im Ordnungssystem. Zu einem späteren Zeitpunkt kann mann sich immer noch überlegen, ob wir gelöschte Objekte periodisch tatsächlich entfernen wollen.:
 - Heisst Dokumente können in den Papierkorb verschoben werden und wenn generell erlaubt "gelöscht" werden. 
 - Dossiers können storniert werden

**Ablage der HomeFolder:**
- Ja genau das wäre ein simples TranslatedTitle Container Objekte.

**Zugriff auf HomeFolder:**
 - Genau wenn die UI Variante Persönliche Übersicht gewählt wird müsste man wohl den Hauptreiter Übersicht in "Arbeitsplatz" / "Persönlich" oder so ähnlich umbenennen, so dass Dossiers dort hinzugefügt werden können. Aber evtl. wäre _Variante 2 (eigener Hauptreiter)_  übersichtlicher.

**Comment by phgross** [comment]
Offene Fragen oder Ideen:
- Aktenzeichen
- Laufnummer
- Spezialbehandlung
- Idee "Referenzen beim Kopieren" entfernen
- Wie kann ein Paste verhindert werden
- Evtl. kann durch den Einsatz von Placefull Workflows ein Implementieren eines separaten Typs verhindert werden.

Entscheide zusammen mit Pascal:
- Metadaten gleich wie normale Objekte
- UI: Separater Reiter `Meine Ablage`

**Comment by phgross** [comment]
Implemented with #2192
