### ISSUE TITLE
Recover from failed officeconnector officeatwork states

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2166]
Offer a way to recover from various possible client-side failure states (officeatwork/word crashes, ...) where user-action is required.

Suggestion: add a button to abort the creation for such cases. Mockup:

![screen shot 2017-09-18 at 10 50 25](https://user-images.githubusercontent.com/736583/30534595-295f29be-9c5f-11e7-9a95-2ee0acfa1dad.png)

Unclear: should there also be a retry button to retry creating the document or do we want to omit that for now?

**Comment by phgross** [comment]
Wird geschlossen. Siehe Begründung im Epic #3379
