### ISSUE TITLE
Add separate syles/statusmessage for shadowdocuments

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2167]
Shadow-documents created as temporary placeholder for documents (that are being created by officeatwork) should have different styles to visually distinguish them from normal documents.

We should probably not use an officetwork specific icon though since it may be possible that an integration with other templating tools may use the `shadow-state`, too.

Suggestion: custom status-message:
![screen shot 2017-09-18 at 10 50 25](https://user-images.githubusercontent.com/736583/30534625-49e9e78c-9c5f-11e7-83f7-afa47f8f77ed.png)

and an additional hint in the overview file row:
![screen shot 2017-09-18 at 10 54 50](https://user-images.githubusercontent.com/736583/30534715-bb39d622-9c5f-11e7-8ce4-1bf6d8cbe2cd.png)

**Comment by phgross** [comment]
Wird geschlossen. Siehe Begründung im Epic #3379
