### ISSUE TITLE
Use a Text column instead of String column for the addresses Street column.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2171]
Input from @phabegger 

> Kann ich auch mehrzeilige Adressen erfassen?
> 
> Dringend nicht, aber wichtig. Speziell bei Orgs hat man häufig Adressen, die sich über mehrere Zeilen erstrecken. Ihr habt Euch doch bei der Konzeption an der Kontakt-App von Apple bedient. Dort ist das Strassenfeld auch mehrzeilig. Ich schlage vor, dass wir auch auf Textfield wechseln.

**Comment by deiferni** [comment]
Man muss hier einfach beachten, dass DocProperties in Word nicht mehrzeilig sein können. Es könnte also beim erstellen von Vorlagen mit solchen Adresssen zu Formatierungsproblemen kommen. Eventuell wäre es besser diese Anforderung über ein Feld Zusatzzeile/Postfach abzudecken?

**Comment by phgross** [comment]
Zurzeit sind keine Arbeiten am Kontaktmodul geplant. Weitere Arbeiten müssten neu koordiniert und definiert werden (Stichwort VueJS, neues Frontend etc.) ich schliessen diesen Issue.
