### ISSUE TITLE
Erfassung abwesender Mitglieder

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2180]
Es soll möglich sein die Abwesenden Mitglieder im Protokoll auszuweisen. 

Dazu müssten die nicht als anwesend markierten Mitglieder separat in den Protokolldaten zur Verfügung gestellt werden.

**Comment by phgross** [comment]
@deiferni prüfen ob bereits umgesetzt.

**Comment by deiferni** [comment]
This has been implemented in https://github.com/4teamwork/opengever.core/pull/5108 and when rewriting meetings to use word.
