### ISSUE TITLE
Berechtigungskonzept SPV

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2182]
Im Moment können die Berechtigungen für Gremien aufgrund einer LDAP-Gruppe vergeben werden.

Die soll so angepasst werden, dass die normalen GEVER Berechtigungen auf dem Kommittee gebraucht werden können. Ebenfalls sollen die principals, die Zugriff auf das Gremium haben im SQL mitgeführt werden, u.U. analog `TaskPrincipals`.

**Comment by phgross** [comment]
@deiferni further specify

**Comment by deiferni** [comment]
We have implemented several different roles for `Committee` and `CommitteeContainer`.
