### ISSUE TITLE
Sitzungsvorbereitung, download Sitzungsunterlagen als zip

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2183]
Die Sitzungsunterlagen sollen zip heruntergeladen werden können. Dieses müsste mindestens beinhalten:
- (Vor)Protokoll
- Traktandenliste
- Alle Beilagen (AgendaItems Attachments)

**Comment by maethu** [comment]
- [ ] ZIp-Struktur überlegen

**Comment by maethu** [comment]
Wurde implementiert.
