### ISSUE TITLE
Sperrung einzelner Dokumente für gewisse Mitarbeiter

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2184]
Im Rahmen der SPV besteht der Wunsch, einzelne Dokumente und Anträge für gewisse Mitarbeiter zu sperren, da diese direkt davon betroffen sein könnten. Um dies zu ermöglichen müssten die Workflows erweitert werden, so dass sie die `Sharing page: ...` Permissions verwalten.

Uns stellt sich die Frage ob das sinnvoll ist, aus unserer Sicht ist das über die Berechtigungen auf Dossierstufe, bzw. eingeschränkte Berechtigungen für Personalfragen auf Ordnungssystemstufe schon abgedeckt.

**Comment by phgross** [comment]
Kann mit einem geschützten Dossier (OGIP 23) und einem Antrag aus diesem Dossier gelöst werden. Zudem können heikle Daten als Anhang und nicht im Antragsdokument selbst verfasst werden.
