### ISSUE TITLE
Missing validation in form to add template dossiers

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2199]
It is not validated whether the specified path is a template dossier. I probably could create a document based on another document in a dossier. We should not pass available paths to the client but generate a token for the templates instead.

**Comment by phgross** [comment]
I did not unterstand this issue. @deiferni please add some more information. thx

**Comment by deiferni** [comment]
No longer relevant, since https://github.com/4teamwork/opengever.core/pull/2356 we now use the `TableChoice` widget to select the template-dossier.
