### ISSUE TITLE
Bad icon alignment in task workflow icons

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#2223]
<img width="874" alt="bildschirmfoto 2016-10-07 um 06 52 17" src="https://cloud.githubusercontent.com/assets/1637820/19182886/ebe193d2-8c75-11e6-8aef-234e41d532b9.png">

**Comment by phgross** [comment]
Bitte wie besprochen korrigieren, dabei bitte beachten:
 - Darf keinen Einfluss auf Dossier oder sonstige Auflistungen haben
 - Anträge, Weiterleitungen und Aufgaben alle gleich stylen
 - SCSS 😉
