### ISSUE TITLE
Aktivierung von PloneHotfix 20160830

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2225]
Für die Aktivierung des Plone Hotfixes (Products.PloneHotfix20160830) müssen noch einige Anpassungen insbesondere an Formularen gemacht werden. Dies Tickets fasst die Arbeiten zusammen.

bekannte Issues:
- [ ] https://github.com/4teamwork/opengever.core/issues/2222

**Comment by jone** [comment]
@phgross noch aktuell? Ich glaube der Hotfix ist in der neusten Version aktiviert.

**Comment by lukasgraf** [comment]
@jone korrekt, Hotfix ist aktiviert und Probleme (soweit bekannt) behoben.
