### ISSUE TITLE
IntegrityError when re-submitting rejected proposal with attachments

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2234]
Under certain conditions it is possible that a `SubmittedDocument` entry won't be deleted when a submitted proposal is rejected.

**Comment by deiferni** [comment]
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/703/

**Comment by elioschmutz** [comment]
@deiferni I cannot reproduce this error. The last error has been thrown 5 months ago.

Perhaps, this issue is already fixed. Can I close this issue?

**Comment by deiferni** [comment]
We've never been able to reproduce that reliably 😞 , so
