### ISSUE TITLE
Dossier workflow column has extra padding

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2239]
The padding is broken for the dossier workflow column. There is extraneous padding on the left side.

Up-to-date `opengever.core`, up-to-date `plonetheme.teamraum`.

![dossier_padding](https://cloud.githubusercontent.com/assets/405124/19409494/cb53ba7c-92d4-11e6-9848-dfa04b791805.png)

Im assuming this is related to https://github.com/4teamwork/plonetheme.teamraum/pull/471 and/or https://github.com/4teamwork/plonetheme.teamraum/pull/470

**Comment by deiferni** [comment]
Fixed by reverting changes in https://github.com/4teamwork/plonetheme.teamraum/pull/473.
