### ISSUE TITLE
Download copy overlay JS is broken

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2240]
The "download copy" overlay isn't shown as an overlay anymore, and as a result of than, it's styling is also missing.

On `master`, current versions of `opengever.core` and `plonetheme.teamraum`.

![download_copy](https://cloud.githubusercontent.com/assets/405124/19409541/f7705b5a-92d5-11e6-981e-1251f454f5b9.png)

**Comment by deiferni** [comment]
Closes via https://github.com/4teamwork/opengever.core/pull/2243.
