### ISSUE TITLE
private visible but not reachable from breadcrumbs

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2244]
When i am logged in as a normal user i can see the element `private` in the breadcrumbs. If i click on it i will get a 403.
Since this will be the case for all users i'd suggest to hide `private` from the breadcrumbs (i.e. implement `IHideFromBreadcrumbs` in `PrivateRoot`).

@phgross what do you think?

![screen shot 2016-10-20 at 09 19 48](https://cloud.githubusercontent.com/assets/736583/19549756/692e0606-96a6-11e6-954d-ed74c014c7ba.png)

**Comment by phgross** [comment]
👍
