### ISSUE TITLE
Fix root-content creation permissions for Administrator

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2246]
Currently an `Administrator` can create root content (Template-Folder, Inbox, ...), this should be possible for `Manager` only.

**Comment by elioschmutz** [comment]
@deiferni 

Removing the permission `Add portal content` for the specific roles is not enough. The add menu is still available but the user is not able to add some content.

I have to remove all the "Add xxx" permissions (i.e. `opengever.inbox: Add Inbox`) for the specific roles.

Is there another way? Or is it ok if I adjust all this permissions in the `rolemap.xml` in ?`opengever.base`

**Comment by deiferni** [comment]
@elioschmutz yeah i'd say that's  the correct way of doing it, you should not remove the `add portal content` permission for admins, but the content-type specific permission to add the root content types (repo-root, inbox/inbox-container, inbox, contacts-thingy and committee-container). be careful with template-folders/dossiers, they should be addable inside other template-folders/dossiers.
