### ISSUE TITLE
use newer version of raven

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2255]
Currently `raven` is pinned to version `5.10.0` which leads to the following message being displayed:

![screen shot 2016-10-31 at 08 28 33](https://cloud.githubusercontent.com/assets/736583/19847076/60e4bb42-9f44-11e6-8240-14a883780b5e.png)

Thus we we should update to a newer `raven` version in one of our next releases.

**Comment by phgross** [comment]
We curently use the version `5.32.0` of raven.
