### ISSUE TITLE
Activate bumblebee reduced layout

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2277]
The Bumblebee App supports now a `reduced` layout which activates some nice pdf.js functionalities (zoom, toc ,,,)

I've activated the `reduced` layout for test purpose on lab.onegovgever.ch.

![bildschirmfoto 2016-11-09 um 16 27 06](https://cloud.githubusercontent.com/assets/485755/20143486/740b70f6-a699-11e6-8d52-5983f1acbce5.png)

**Comment by deiferni** [comment]
https://basecamp.com/2768704/projects/13482340/todos/305000579

**Comment by phgross** [comment]
The reduced layout ist now used on every productive GEVER deployment.
