### ISSUE TITLE
Show spinner while TOC is generated

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2280]
Generating a TOC can take a while (several seconds). We should display a spinner and deactivate the button when it has been clicked/while a TOC is being generated in order to improve the UI and to prevent impatient users from clicking too furiously and blocking all instances.

![screen shot 2016-11-10 at 17 07 22](https://cloud.githubusercontent.com/assets/736583/20184231/41936618-a768-11e6-9c35-a62932238078.png)

**Comment by Rotonen** [comment]
Should there also be a dedicated instance pool/range for known slow requests separated on the webfront level?

**Comment by deiferni** [comment]
@Rotonen i think the approach here should be to have a separate queue for such things.
