### ISSUE TITLE
Verhindern, dass überlappende Periode erstellt werden können

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2283]
Zeitspannen der Perioden können sich im Moment überlappen, ich denke man sollte das verhindern.

![screen shot 2016-11-14 at 10 53 46](https://cloud.githubusercontent.com/assets/736583/20260176/bfbfe294-aa58-11e6-81d6-561b5c6ece33.png)

**Comment by phgross** [comment]
Vermutlich kein Problem, evtl. sogar bei gewissen Umständen notwendig.
