### ISSUE TITLE
Default data incorrectly uses datetime as document_date for some documents

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#2286]
![image](https://cloud.githubusercontent.com/assets/935317/20270325/edb67432-aa86-11e6-831d-23ddd5064221.png)

The offending documents are listed above.

**Comment by tarnap** [comment]
@Rotonen 
I feel a little bit lost here

How can I reproduce the list?
How where the documents added?

**Comment by Rotonen** [comment]
@tarnap https://github.com/4teamwork/opengever.core/blob/5c20181426fe279a16eb952973a737501475160b/opengever/examplecontent/hooks.py#L136

I suspect something is fishy in the creation of the meetings.

**Comment by tarnap** [comment]
@Rotonen 
What's the header of the date column?

**Comment by tarnap** [comment]
I found this:
https://github.com/4teamwork/ftw.builder/blob/master/ftw/builder/builder.py#L135

**Comment by tarnap** [comment]
After discussing with @jone, we came to the conclusion, that it's probably not a date vs datetime object issue but rather an issue with the format string.

@Rotonen 
What listing is responsible for these dates?
Do you have a URL?

**Comment by tarnap** [comment]
I went to `Kurzinfo Hans Baumann` and set a pdb breakpoint, to test the attributes of the document:


![document dates](https://user-images.githubusercontent.com/194114/27587756-dacd6356-5b45-11e7-85a2-aae9efd27187.gif)

**Comment by Rotonen** [comment]
@tarnap I'm starting to have a loose recollection this might have been in the dossier or document report (`.xlsx` or `.pdf`) functionality. My bad for not doing the bug report proper originally.

As discussed, this is probably safe to ignore this for now.
