### ISSUE TITLE
Create specification for OGGBundle

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2304]
Write the specification for the OGGBundle format used for UBit -> GEVER imports.

![oggbundle2](https://cloud.githubusercontent.com/assets/405124/20590261/65d29b88-b222-11e6-904e-042966eb814c.png)

The bundle will contain a collection of *binary files*, a *`configuration.json`* and *JSON documents* with content for the following types:

 - Repository Roots
 - Repository Folders
 - Dossiers
 - Documents (incl. Mails)

Also:

- Permissions
- Parent/Child Pointer

**Comment by deiferni** [comment]
First spec has been generated. Other updates will follow in separate, more specific issues.
