### ISSUE TITLE
Rework/cleanup task response implementation

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2320]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

- [ ] Remove POI relicts 
- [ ] Remove stale code
- [ ] Rework response storages, are the lightweight objects still necessary
- [ ] Harmonize with ResponseDescription

**Comment by phgross** [comment]
Abwarten auf #4786

**Comment by deiferni** [comment]
Closed via https://github.com/4teamwork/opengever.core/pull/5921
