### ISSUE TITLE
Fehler bei "Dokument aus Vorlage" wenn Dokument nur in Papierform vorhanden ist

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2360]
Es gibt ein Fehler bei "Dokument aus Vorlage" wenn Dokument nur in Papierform vorhanden ist

![screen3](https://cloud.githubusercontent.com/assets/557005/20836042/eb7f5402-b89d-11e6-8dbd-ec82a0e2a52d.gif)

**Comment by phgross** [comment]
Vorlagen ohne Datei sollten nicht in der `Vorlagen` Auflistung im Formular `Dokument aus Vorlage erstellen` erscheinen. 

Für die Überprüfung kann `digitally_available` von `IDocumentMetadata` verwendet werden.

**Comment by tarnap** [comment]
Implemented @phgross solution:

![do not list templates without digitally available document](https://user-images.githubusercontent.com/194114/27337750-a44a3402-55d3-11e7-8f8a-008057734cc5.gif)

Tests to be written
