### ISSUE TITLE
Performance-Issue bei Dossiers aus Dossiertemplates

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2382]
Dossiers aus einem Template zu erstellen dauert extrem lange.

Hier ein Beispiel mit einem Template von ~35 Dossiers welches  ~20 Sekunden dauert:

![screen3](https://cloud.githubusercontent.com/assets/557005/20931109/5577959c-bbd0-11e6-9591-a68d907a19d7.gif)

**Comment by deiferni** [comment]
IMO this has been addressed in the meantime.
