### ISSUE TITLE
Visuelle Unterscheidung im Breadcrumb zwischen Ordnungssystem und Dossier

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2389]
Dies wurde am Innovation Day 2016 als Verbesserungswunsch eingebracht. Man könnte aus meiner Sicht das Icon der Inhalte im Breadcrumb mit einblenden.

**Comment by phgross** [comment]
@bierik könntest du hierzu kurz mögliche Vorschläge erarbeiten, wie das aussehen könnte.

**Comment by bierik** [comment]
@phgross Anbei ein Vorschlag von mir.
Sobald in der Pathbar ein neuer Typ erscheint also z.B. von Ordnungssystem nach Dossier wird mit einem kleinen Abstand diese Gruppe gekennzeichnet und mit dem Icon gezeigt welcher Typ gerade in der Breadcrumb ist.

<img width="1367" alt="screen shot 2017-05-18 at 16 52 53" src="https://cloud.githubusercontent.com/assets/1637820/26208532/a02be8d2-3bea-11e7-83e0-d2cf402f9eaf.png">

**Comment by phabegger** [comment]
Kannst Du noch ein Beispiel machen, wo nur das Hauptdossier mit Icon angezeigt wird? Ohne zusätzliche Abstände, @bierik ?

**Comment by phabegger** [comment]
Ich habe inzwischen die Diskussion ins Feedback-Forum verlagert, siehe https://feedback.onegovgever.ch/t/breadcrumb-path-brotkruemelpfad-visuell-aufwerten/547

**Comment by phgross** [comment]
@bierik bitte folgende Vorschläge skizzieren und im Feedback Forum platzieren
 - Nur Haupt-Dossier fett
 - Nur Ordnungspositionen fett
 - Nur bei Hauptdossier Icon
 - Kevin's Hipster Variante (DropDown)
 - Weitere Ideen (siehe auch Feedback Forum)

**Comment by bierik** [comment]
@phgross 

Hauptdossier fett:
<img width="1438" alt="hauptdossier_fett" src="https://user-images.githubusercontent.com/1637820/26935891-7936143a-4c6d-11e7-8215-202baa923cdb.png">

Ordnungsposition fett:
<img width="1304" alt="ordnungspositionen_fett" src="https://user-images.githubusercontent.com/1637820/26935903-7fcf5504-4c6d-11e7-8391-c958a50cb063.png">

Dossier icon:
<img width="1307" alt="dossier_icon" src="https://user-images.githubusercontent.com/1637820/26935914-875f397e-4c6d-11e7-9071-2bb02804caa6.png">

Hipster Variante:
![gever breadcrumbs](https://user-images.githubusercontent.com/1637820/26935929-91b1388c-4c6d-11e7-8c50-26a47caf9c55.png)
<img width="1305" alt="hipster" src="https://user-images.githubusercontent.com/1637820/26935941-9819e58e-4c6d-11e7-95a9-a944b4035a5c.png">

**Comment by phgross** [comment]
@bierik Danke für die Screenshots, kannst du Sie gleich selber im Feedback Forum Posten. Inkl. Erklärung, falls nötig. thx

**Comment by phabegger** [comment]
Hipster-Variante finde ich im Grundsatz auch interessant, allerdings hätte ich es eher wie bei zg.ch "designed", https://www.zg.ch/online-dienstleistungen/bildung-und-schule

- Statt "Böxchen" um die Elemente "Pfeile" verwenden.

- Das erste Element im Breadcrumb sollte die genaue Position im OS anzeigen, also "0.7.1. Kommission für Rechtsfragen", statt "Finanzdepartement". Wenn man die Position dann aufklappt wird, wird der OS-Pfad "rückwärts" angezeigt... Also wäre der Eintrag "Ordnungssystem" zu unterst, nicht zuoberst.

- Was passiert, wenn man auf "Jahresdossier" klickt? Eher nicht aufklappbar machen, dies verwirrt. Oder was sollte hier passieren?

**Comment by bierik** [comment]
@phabegger Ich mache noch eine weitere Variante mit deinen Anregungen.

Unter dem Jahresdossier würden dann die Subdossiers erscheinen. Hier wahrscheinlich auch das unterste subdossier anzeigen und das Jahresdossier zu unterst analog Ordnungssystem.

**Comment by bierik** [comment]
Angepasste Hipster-Variante

![gever breadcrumbs](https://user-images.githubusercontent.com/1637820/27134328-86927022-5115-11e7-842a-95ee9cf0059f.png)

**Comment by bierik** [comment]
@phabegger noch eine Variante mit den Subdossier ausgeklappt

![gever breadcrumbs subdossier](https://user-images.githubusercontent.com/1637820/27136232-1643fb5a-511b-11e7-8d6a-ef771f1dbd8c.png)

**Comment by phabegger** [comment]
@bierik Ganz ordentlich, vielen Dank. Falls es Dir nicht zu viel Aufwand gibt, hätte ich gerne noch folgende minimale Changes, bevor ich sie ins Forum stelle:

- Icons etwas kleiner (falls möglich) - sie wirken etwas gross
- "Finanzdepartement" bitte aus Liste entfernen (wäre Mandantenname)
- Mockups in einen vollständigen Screenshot von OGG reinmachen (so wie in den anderen Screenshots)
- Dossier-Dropdown so positionieren, dass die Texte linksbündig untereinander passen (also "Projektleitung" direkt unter "Protokolle und Sitzungen". Dafür muss es nicht bündig mit rechtem Pfeil aufhören.
- Richtige Dossiernamen verwenden (Nicht "Phasellus" irgendwas...). Konkret: Jahresdossier => "Geschäfte Rechtsfragen 2017", "Phasellus nec sem in" => "Sitzung Januar 2017", "Phasellus ullamcorper ipsum" => "Anhang Antrag 13"

**Comment by bierik** [comment]
@phabegger 
![gever breadcrumbs](https://user-images.githubusercontent.com/1637820/27171140-c8d4c764-51b0-11e7-98b8-b15caad3cca4.png)
![gever breadcrumbs subdossier](https://user-images.githubusercontent.com/1637820/27171141-c8ede0c8-51b0-11e7-91eb-dc151e0bebd4.png)

<img width="1910" alt="gever-breadcrumbs-dossier" src="https://user-images.githubusercontent.com/1637820/27171145-cd58eb26-51b0-11e7-9a98-03066033cd87.png">
<img width="1910" alt="gever-breadcrumbs-ordnungssystem" src="https://user-images.githubusercontent.com/1637820/27171144-cd542226-51b0-11e7-934d-6b8821163f92.png">

**Comment by phgross** [comment]
@bierik Hipster Vorschlag ist ok, bitte umsetzen.

Bitte folgendes beachten:
- Dossiers nicht groupieren (aufklappbar)
- Schönere "Pfeile" verwenden (siehe Kommentar von Jérome im Feedback Forum)
