### ISSUE TITLE
Übersetzung von "private" im Bereich Persönliches Dossier

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2391]
Vorschlag: "private" => "Persönliche Ablage"

![bildschirmfoto 2016-12-07 um 13 23 54](https://cloud.githubusercontent.com/assets/485600/20967608/9f8c5176-bc80-11e6-9db0-c3cfd5e15b09.png)

**Comment by deiferni** [comment]
Wir haben den Eintrag komplett ausgeblendet, https://github.com/4teamwork/opengever.core/pull/2395
