### ISSUE TITLE
Eigenes Icon für persönliche Ablage

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2392]
Im Moment erscheint noch das Blatt (Ordnungsposition). Könnte man da was anderes nehmen?
![bildschirmfoto 2016-12-07 um 13 27 12](https://cloud.githubusercontent.com/assets/485600/20967676/0132d756-bc81-11e6-85bf-e83ff406a19c.png)

**Comment by phgross** [comment]
@phabegger Ja das wäre relativ einfach möglich, hättest du ein Vorschlag für ein passendes Icon http://fontawesome.io/icons/ ?

**Comment by phabegger** [comment]
Ein paar Vorschläge, bin allerdings kein Spezialist:
http://fontawesome.io/icon/user-secret/
http://fontawesome.io/icon/user-circle/
http://fontawesome.io/icon/user-circle-o/

Könnte man allenfalls auch ein neues Icon kreieren, z.B. das Dossier-Icon ergänzt mit einer Person?

**Comment by phgross** [comment]
User-circle finde ich am passendsten.
