### ISSUE TITLE
Fehlermeldung bei Klick in Breadcrumb "private"

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2393]
Klick auf "private"...

![bildschirmfoto 2016-12-07 um 13 30 27](https://cloud.githubusercontent.com/assets/485600/20967806/6c2591c0-bc81-11e6-92b4-fd448490f11d.png)

führt zu Fehlermeldung "Unzureichende Berechtigung".

Vorschlag: Breadcrumb-Part nicht verlinken oder automatisch auf persönliche Ablage weiterleiten.

**Comment by deiferni** [comment]
duplicates https://github.com/4teamwork/opengever.core/issues/2244
