### ISSUE TITLE
In der persönlichen Übersicht Ordnungssystem nicht darstellen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2394]
Links erscheint immer das Ordnungssystem, was aber keinen Sinn macht. Dafür würde man eher mehr Platz benötigen für die tabellarische Auflistung von Pendenzen.

Vorschlag: OS ausblenden unter Übersicht.

![bildschirmfoto 2016-12-07 um 13 38 55](https://cloud.githubusercontent.com/assets/485600/20968038/99ee1874-bc82-11e6-9765-35d752add7ae.png)

**Comment by deiferni** [comment]
@pascal wir haben das schon mal sehr ausführlich diskutiert/aufgeschrieben, siehe: https://github.com/4teamwork/opengever.core/issues/1214, es wäre gut wenn du dich dort auch noch einbringen könntest.

**Comment by phgross** [comment]
Wir haben im Rahmen von #1214 die Portlets ausführlich diskutiert und sind zum Schluss gekommen das auf der Persönlichen Übersicht der Baum Sinn macht.
