### ISSUE TITLE
Protokollauszug: Erwägungen anstatt Überlegungen

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2400]
Wenn ein Protokollauszug unten links in der SPV-Übersicht generiert werden möchte, steht anstatt "Erwägungen" --> "Überlegungen".
![bildschirmfoto 2016-12-08 um 14 28 32](https://cloud.githubusercontent.com/assets/20790360/21011736/e3302006-bd52-11e6-93fb-ed1dcd4e4a01.png)

**Comment by deiferni** [comment]
Nicht mehr länger relevant #2829.
