### ISSUE TITLE
Vorlagen: Vorlagen in Ordner verschieben

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2401]
Wenn im Vorlagen-Tab ein neuer Ordner erstellt werden möchte, können bestehende Dokumente nicht in den Ordner verschoben werden. (Weder verschieben noch kopieren/einfügen).

- [x] Dokumente im Vorlagen-Tab müssen verschoben werden können

**Comment by phgross** [comment]
@elioschmutz bitte abklären ob das Formular `move_item` hierzu verwendet werden könnte?
