### ISSUE TITLE
Vorlagen-Dossier: Federführend

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2402]
Wenn ein neues Vorlagen-Dossier erstellt wird, ist das Feld "Federführend" auch zwingend auszufüllen, aber dies ist unter dem Tab "Common" versteckt und daher nicht auf den ersten Blick ersichtlich. Dadurch klickt User auf speichern und es kommt ein Fehler. --> Könnte das Feld ins Tab "Inhalt" verschoben werden?

**Comment by deiferni** [comment]
Zudem fehlende Übersetzung, "common" -> Allgemein

**Comment by elioschmutz** [comment]
Der Fix für die Übersetzung ist hier #2741 

Das Verschieben des Feldes "Federführend" macht m.E. keinen Sinn. Das Feld ist Teil des IDossier-Behaviors und wird auch so im Add/Edit-Form vom Dossier dargestellt.
Es wäre eher sinnvoll, wenn die Titelfelder ebenfalls im Allgemein-Tab dargestellt werden. Diese Anpassung ist jedoch viel Aufwändiger. Sobald `directives.order_before(fieldname='*')` verwendet wird (was bei title_de und title_fr) der Fall ist, wird das Feld automatisch im Default-Fieldset (Inhalt) angezeigt. D.h., dass die Reihenfolge der Felder nicht explizit angegeben werden können. Zudem wäre die Feldreihenfolge der Felder für `opengever.inbox.inbox` und 'opengever.repository.repositoryfolder` durcheinander. Auch konzeptionell würde es Probleme geben. Die Inbox z.B. definiert seine Felder über die Schema-Klasse und nicht über ein Behavior. Somit werden die Felder der Inbox immer vorher angezeigt.

Da die Felder in der momentanen Darstellung im GEVER konsistent angezeigt werden und eine Feldanpassung viele Seiteneffekte mit sich ziehen würde, schlage ich vor, das Feld Federführend nicht zu verschieben.

@deiferni Wie siehst du das?

**Comment by deiferni** [comment]
Seh ich auch so. Mittlerweile wurde:
- Pre-Fill für `Federführend` gelflickt
- Tab-Übersetzung geflickt

Alles weitere ist nicht nötig, ich schliesse daher den Issue.
