### ISSUE TITLE
Antrag: Anhang nachreichen

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#2403]
Wird in einem Antrag nachträglich ein Anhang nachgereicht (unter Sitzungen / Antrag), wird dieser im Dossier nicht angezeigt resp. nicht rüberkopiert:
![bildschirmfoto 2016-12-08 um 14 42 17](https://cloud.githubusercontent.com/assets/20790360/21012097/b5a66684-bd54-11e6-8ee0-a61cfa2c0393.png)
![bildschirmfoto 2016-12-08 um 14 42 09](https://cloud.githubusercontent.com/assets/20790360/21012098/b5ab749e-bd54-11e6-810f-3486783d160b.png)

**Comment by elioschmutz** [comment]
Dies ist kein Bug.

Dieses Verhalten ist gewünscht. Dokumente, welche in einem Gremium einem Antrag hinzugefügt werden sollen nicht in das Dossier zurückgespielt werden.
