### ISSUE TITLE
Add validation check to datepicker widget  to disallow dates before 1900

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2435]
Because python datetime can handle dates before 1900, it shouldn't be possible to insert dates before 1900.

ValueError: year=1016 is before 1900; the datetime strftime() methods require year >= 1900

https://sentry.4teamwork.ch/sentry/onegov-gever/issues/1340/

```
ValueError: year=1016 is before 1900; the datetime strftime() methods require year >= 1900
(12 additional frame(s) were not displayed)
...
  File "home/zope/eggs/plone.api-1.5-py2.7.egg/plone/api/validation.py", line 70, in wrapped
    return f(*args, **kwargs)
  File "home/zope/eggs/plone.api-1.5-py2.7.egg/plone/api/portal.py", line 232, in get_localized_time
    request=request,
  File "home/zope/eggs/Products.CMFPlone-4.3.2-py2.7.egg/Products/CMFPlone/TranslationServiceTool.py", line 89, in ulocalized_time
    context, domain, request)
  File "home/zope/eggs/Products.CMFPlone-4.3.2-py2.7.egg/Products/CMFPlone/i18nl10n.py", line 206, in ulocalized_time
    mapping[key] = time.strftime('%' + key)
  File "DateTime/DateTime.py", line 1551, in strftime
    microseconds).strftime(format)

ValueError: year=1016 is before 1900; the datetime strftime() methods require year >= 1900
```

**Comment by maethu** [comment]
I thought I can solve it with the new ftw.datepicker widget. 
Bud the widget itself supports selectable dates by default until 1950. But it's not possible to disallow manual input of dates before 1900. 

I guess a field validator should handle this.

**Comment by maethu** [comment]
Ahh just found a way to implement it in the widget. heheyyy!!

**Comment by maethu** [comment]
The  "min. year 1900" has been implemented in https://github.com/4teamwork/ftw.datepicker/pull/12/files
Version 1.2.0

<img width="506" alt="screen shot 2017-02-22 at 08 59 43" src="https://cloud.githubusercontent.com/assets/437933/23202274/964b7dc8-f8dd-11e6-8619-c50840be334a.png">

Updating ftw.datepicker  to 1.2.0  is part of #2587 https://github.com/4teamwork/opengever.core/pull/2587/commits/9015309e626809f492babdf2987b37b85dddf0f6

**Comment by phgross** [comment]
Wird mit #2587 korrigiert.
