### ISSUE TITLE
Fehlende Übersetzung Add participant bei Beteiligungen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2448]
Siehe Screenshot, Button unten.

![bildschirmfoto 2016-12-22 um 18 55 47](https://cloud.githubusercontent.com/assets/485600/21435150/68738188-c878-11e6-89c3-a147616552e8.png)

**Comment by elioschmutz** [comment]
Fixed in: https://github.com/4teamwork/opengever.core/commit/5a33d6db66e6c463056d68d1d632fb67cb2aee67
