### ISSUE TITLE
Dossierabschluss: Abschlussmaske wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2449]
Vermutlich ging dies beim Weglassen der Ablage-Abfrage verloren (gemäss @phgross).

Siehe Screenshot alt:
![image24](https://cloud.githubusercontent.com/assets/485600/21435622/14b19334-c87b-11e6-821a-85ccb1149825.png)

**Comment by phgross** [comment]
Stand jetzt: Das Abschlussformular wird zurzeit nur dargestellt, wenn das Feature `Ablagenummer` aktiviert ist (zurzeit nur Kanton Zug). Ist das Feature deaktiviert so wird das Abschlussdatum automatisch vergeben.

@phabegger Es ist unklar ob die Abschlussmaske überhaupt dargestellt werden soll, oder das Datum einfach automatisiert gesetzt werden soll. Ich würde vorschlagen hierzu im Feedback Forum einen Thread zu eröffnen. Dabei ist wichtig zwischen Installationen mit aktivierten oder deaktiviertem Ablagenummer-Feature unterschieden werden.

**Comment by phabegger** [comment]
Evtl. habe ich hier etwas mit #1871 vermischt.

Soweit ich Dich verstehe, wird im Moment das Abschlussdatum immer automatisch errechnet, ohne Möglichkeit des Benutzers, dieses zu ändern. Da dies produktiv bereits so genutzt wird, würde ich hier im Moment nichts unternehmen und erst wieder reagieren, falls dies über das FF gewünscht wird (durch User).

**Comment by phgross** [comment]
Ja genau. Ok, dann schliesse ich diesen Issue.
