### ISSUE TITLE
Aufgabe: Erledigungsdatum nicht bearbeitbar machen (oder ganz ausblenden)

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2450]
Beim Hinzufügen einer neuen Aufgaben kann ich das Erledigungsdatum setzen:

![bildschirmfoto 2016-12-22 um 22 41 07](https://cloud.githubusercontent.com/assets/485600/21441409/3330ef5e-c898-11e6-82cc-58fd2c752265.png)

**Comment by elioschmutz** [comment]
@deiferni gibt es Situationen, in denen der Benutzer das Erledigungsdatum selbst setzten darf/kann?

Falls nein, werde ich das Feld im Edit-Form ausblenden.

**Comment by deiferni** [comment]
@elioschmutz aus meiner Sicht macht es höchstens Sinn, das aus dem Add-Form zu entfernen, im Edit-Form sollte man meiner Meinung nach das Datum noch anpassen können.
