### ISSUE TITLE
Unicode Fehler bei E-Mails mit Emojis im Subject

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#2462]
Fehler entstand beim Import des folgenden Mails:

[wg-letzte-chance-23f0-d83cdfc3-sicher-dir-deinen.eml.zip](https://github.com/4teamwork/opengever.core/files/699016/wg-letzte-chance-23f0-d83cdfc3-sicher-dir-deinen.eml.zip)

Danach habe ich das Mail in den Papierkorb gelegt.

https://lab.onegovgever.ch/ordnungssystem/fuehrung/kommissionen-mit-selbstaendigen-verwaltungsbefugnissen/kommission-c/ressorts/dossier-479/wg-letzte-chance-23f0-d83cdfc3-sicher-dir-deinen#overview
N
Zeit
11.01.2017 14:44
Benutzername
sandro.ackermann (sandro.ackermann)
Anfrage URL
https://lab.onegovgever.ch/ordnungssystem/fuehrung/kommissionen-mit-selbstaendigen-verwaltungsbefugnissen/kommission-c/ressorts/dossier-479/trashed
Fehlertyp
ValueError
Fehlerwert
unichr() arg not in range(0x10000) (narrow Python build)
Traceback (innermost last):

Module ZPublisher.Publish, line 70, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module opengever.trash.trash, line 116, in __call__
Module opengever.trash.trash, line 61, in trash
Module Products.CMFCore.CMFCatalogAware, line 88, in reindexObject
Module Products.CMFCore.CatalogTool, line 301, in reindexObject
Module Products.CMFPlone.CatalogTool, line 353, in catalog_object
Module Products.ZCatalog.ZCatalog, line 476, in catalog_object
Module Products.ZCatalog.Catalog, line 339, in catalogObject
Module Products.ZCTextIndex.ZCTextIndex, line 180, in index_object
Module plone.indexer.wrapper, line 65, in __getattr__
Module plone.indexer.delegate, line 18, in __call__
Module collective.dexteritytextindexer.indexer, line 89, in dynamic_searchable_text_indexer
Module ftw.mail.mail, line 183, in __call__
Module ftw.mail.mail, line 144, in convert_to_text
Module ftw.mail.mail, line 171, in convert_to_text
Module Products.PortalTransforms.TransformEngine, line 173, in convertTo
Module Products.PortalTransforms.Transform, line 198, in convert
Module Products.PortalTransforms.libtransforms.retransform, line 30, in convert
Module Products.PortalTransforms.transforms.html_to_text, line 18, in sub_func
ValueError: unichr() arg not in range(0x10000) (narrow Python build)

**Comment by elioschmutz** [comment]
Das Problem liegt nicht grundsätzlich an Emojis sondern am Runner Emoji 🏃 im Angehängten Email. Dieser Emoji ist als HTML Entity eingefügt (\&#127939;) und nicht wie der Wecker Emoji ⏰ als UTF-8-String (=E2=8F=B0).

Die html_to_text transform versucht, den Runner-Emoji Unicode-ID mit unichr(127939) zu einem Unicodezeichen aufzulösen (siehe https://github.com/plone/Products.PortalTransforms/blob/2.1.2/Products/PortalTransforms/transforms/html_to_text.py#L18).

Python2.7 wird standardmässig mit dem veralteten UCS2 (siehe https://de.wikipedia.org/wiki/Universal_Coded_Character_Set) Zeichensatz kompiliert(siehe https://docs.python.org/2.7/c-api/unicode.html) welcher lediglich UTF-16 Zeichen abbildet. Das Runner-Emoji jedoch benötigt den UCS4 Zeichensatz welcher explizit beim Kompilieren von Python geladen werden muss oder in Python3 standardmässig verwendet wird (https://docs.python.org/3.4/c-api/unicode.html) und UTF-32 Zeichen abbilden kann. 

Überprüfen des geladenen Zeichensatzes:
```
When built with --enable-unicode=ucs4:

>>> import sys
>>> print sys.maxunicode
1114111
When built with --enable-unicode=ucs2:

>>> import sys
>>> print sys.maxunicode
65535
```

UCS4 oder Python3 zu verwenden ist m.E. keine Option.

Tests mit eigenen Mails haben funktioniert: 

![screen2](https://cloud.githubusercontent.com/assets/557005/23864251/3569da92-0812-11e7-93b0-0d12026e5cac.gif)

Wie auch bereits am Anfang erklärt, liegt das Problem nur daran, dass der Runner-Emoji als HTML-Entität eingefügt wurde.

Somit kommen für mich zwei Lösungsvorschläge in Frage:

Lösungsvorschlag 1:
Der Fehler wird nicht weiter behandelt da es nur in Ausnahmefällen zu einem Fehler führt. Es ist extrem selten, dass ein Emoji Mail verwendet wird und dieses auch noch im Gever hochgeladen wird.

Lösungsvorschlag 2:
Patchen der `html_to_text` transform-Methode in https://github.com/plone/Products.PortalTransforms/blob/2.1.2/Products/PortalTransforms/transforms/html_to_text.py#L18 damit die Unicode-IDs ausserhalb des geladenen Charaktersets nicht mit unichr() konvertiert werden. Ein lokaler Test hat gezeigt, dass wenn die HTML-Entität nicht zu einem Unicodezeichen konvertiert wird, der Browser alles korrekt darstellt. Ich kann jedoch nicht ganz einschätzen was dies sonst noch für Impacts haben kann. Vorallem wenn es um die Suche/Sortierung oder Security geht.

@deiferni @jone was sagt ihr dazu? Welche Variante kommt für euch in Frage? Gibt es evt. noch andere Möglichkeiten?

**Comment by jone** [comment]
Ich sehe dies genau gleich:
Ich würde nichts machen (Lösung 1) und beobachten wie oft es auftritt.

Tritt das Problem öfter auf ist die Lösung 2 sicher eine gute Lösung.

**Comment by deiferni** [comment]
Ist im Moment für mich in Ordnung, mittelfristig wäre es aber sicher eine Überlegung wert unsere Pythons mit UCS4 zu bauen.

**Comment by buchi** [comment]
Die Aussage, dass Python im UCS2 Build nicht alle Unicode Zeichen darstellen kann, ist nicht korrekt.
Wenn ein Unicode-Zeichen nicht als UTF16-Zeichen dargestellt werden kann, wird ein sogenanntes Surrogate Pair aus zwei UTF16 Zeichen gebildet.

Beispiel 🏃:
```python
print u'\U0001f3c3'  # Unicode
print '\xf0\x9f\x8f\x83' # Bytestring
```
 
Das Problem ist also, dass die Konvertierung von HTML-Entities für Unicode Zeichen >65535 nicht funktioniert. Dies kann wie folgt behoben werden:

[html_to_text.py#L19](https://github.com/plone/Products.PortalTransforms/blob/master/Products/PortalTransforms/transforms/html_to_text.py#L19) ersetzen mit:
```python
res = ("\\U%08x" % int(ent[1:])).decode('unicode-escape')
```

Ich würde die html_to_text Transform in Products.PortalTransforms fixen. Falls wir nicht auf die neuste Version upgraden können, dann in opengever.core die Transform überschreiben.

**Comment by phgross** [comment]
Ich habe noch überprüft wieso überhaupt der `html_to_text` verwendet wird anstatt TIKA. Der Grund liegt im `[SearchableTextExtender](https://github.com/4teamwork/ftw.mail/blob/master/ftw/mail/mail.py#L129-L183)` des ftw.mails. 

Dieser ist aus Sicht GEVER unnötig und falsch. Stattdessen sollte der `[SearchableTextExtender](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/indexers.py#L59-L89)` verwendet werden. Dieser würde einerseits für die Volltextindexierung TIKA verwenden anderseits aber auch zusätzliche Metadaten wie Laufnummer etc. indexieren. 

Am Besten wäre es wenn der SearchableTextExtender anstatt für das `IDocumentSchema` Interface auf das Schema `IBaseDocument` registriert würde, so würde er sowohl für Dokumente wie auch Mails verwendet. Der Zugriff aufs file müsste anstatt `self.context.file` via `get_file()` erfolgen.

@elioschmutz kannst du diese Anpassung implementieren?

**Comment by elioschmutz** [comment]
👍 werde ich so umsetzten.

**Comment by lukasgraf** [comment]
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3646/
