### ISSUE TITLE
Don't install opengever.policy.base twice

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2478]
Currently `profile-opengever.policy.base:default` is a `metadata.xml` dependency of policy profiles as well as installed explicitly by `GeverDeployment` when it is registered as a `base_profile`.

We should define how this should be installed in the fugure, a suggestion:
- no longer let `GeverDeployment` install `profile-opengever.policy.base:default`
- only add it as a `metadata.xml` dependency of the policies, this ensures that the upgrades are installed in correct order (regarding `ftw.upgrade`'s topogical ordering)

Things to consider:
- also always install `profile-opengever.policy.base:mimetype` in `GeverDeployment`
- `ftw.tika` is currently a policy dependency, move that to core? affects local dev, though.

**Comment by phgross** [comment]
Solved via #2570
