### ISSUE TITLE
Papierkorb defekt in "Meine Ablage"

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2480]
*Vorgehen*
- Meine Ablage öffnen
- Dossier dossier erstellen
- Dokument hochladen
- Im Dokumente-Tab des Dossiers das Dokument auswählen
- "In den Papierkorb verschieben"

*Falsches Resultat*
- Status message `Sie haben keine Objekte ausgewählt`
- Dokument nicht in Papierkorb verschoben

*Erwartet*
- Dokument im Papierkorb

**Comment by elioschmutz** [comment]
@jone ich kann das Problem nicht wie du beschrieben hast reproduzieren. Bei mir erscheint lediglich ein Berechtigungsfehler:

![screen2](https://cloud.githubusercontent.com/assets/557005/23753910/7354842c-04db-11e7-9ded-36f7a0ae9a70.gif)

Ich werde im Rahmen dieses Issues den Berechtigungsfehler beheben.

**Comment by jone** [comment]
@elioschmutz ja, ich habe bereits beide Verhalten gesehen ("nichts ausgewählt" und "Berechtigungsfehler")..
