### ISSUE TITLE
Meine Ablage: Fehler beim Abschliessen eines Subdossiers

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2483]
Wenn ich in einem Dossier in "Meine Ablage" ein Subdossier abschliesse (Aktionen => abschliessen), tritt ein Nümmerlifehler auf.

**Comment by phgross** [comment]
Soeben auf dev.onegovgever.ch getestet, der Abschluss von Privaten Subdossiers funktioniert, ich schliesse diesen Issue.
