### ISSUE TITLE
API: opengever.private.dossier nicht dokumentiert

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2484]
Ich konnte keine Dokumentation für `opengever.private.dossier` (Meine Ablage) finden.

**Comment by lukasgraf** [comment]
Du meinst das Schema für diesen portal type, unter "Inhaltstypen"? Nicht die Doku für die Funktionalität (die wäre unter https://docs.onegovgever.ch/user-manual/meine_ablage/).

**Comment by jone** [comment]
Ja, ich meine die API-Doku des Typs.
