### ISSUE TITLE
API: addable types

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2485]
Mein Script erhält eine URL zu einem beliebigen Dossier und soll dort ein Subdossier erstellen.
Welchen Typ muss ich wählen (business case, spezialdossier, private dossier) bzw. wie finde ich heraus welche Typen ich dort hinzufügen darf?

Erwartung: z.b. ein `addable_types`, welches mir sagt, was ich hinzufügen darf.

**Comment by phgross** [comment]
@jone Die Addable types sind via `@types` endpoint ersichtlich.

GET Request auf `http://localhost:8080/fd/ordnungssystem/raumplanung-bau-und-verkehr/@types` liefert:
```
    {
        "@id": "http://localhost:8080/fd/@types/opengever.inbox.container",
        "addable": false,
        "title": "Eingangskorb Ordner"
    },
    {
        "@id": "http://localhost:8080/fd/@types/opengever.meeting.submittedproposal",
        "addable": false,
        "title": "Eingereichter Antrag"
    },
    {
        "@id": "http://localhost:8080/fd/@types/opengever.dossier.businesscasedossier",
        "addable": true,
        "title": "Geschäftsdossier"
    },

**Comment by jone** [comment]
Ja 👍 Mir war nicht bewusst dass `@types` context-abhängig verwendet werden kann und dass es gefiltert ist.
