### ISSUE TITLE
Remove ftw.footer/add custom footer in certain policies

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2492]
Work done here is required in all policies because of the following PR: https://github.com/4teamwork/opengever.core/pull/2454

- [x] opengever.bs
- [x] opengever.ai
- [x] opengever.sg
- [x] opengever.zug (https://github.com/4teamwork/opengever.zug/pull/247)
- [x] dev (4tw)
- [x] test (4tw)
- [x] nightly (4tw)
- [x] lab (4tw)
- [x] opengever.demo
- [x] opengever.hpcdual
- [x] opengever.nidau
- [x] opengever.phvs
- [x] opengever.phbern
- [x] opengever.edk
- [x] opengever.kgkoeniz
- [x] opengever.duerrenaesch
- [x] opengever.htwchur
- [x] opengever.bistumbasel
- [x] opengever.liesberg
- [x] opengever.mumpf
- [x] opengever.framsteg
- [x] opengever.ftw
- [x] opengever.ubit

**Comment by elioschmutz** [comment]
Following packages ase testet for the version-information-column:

- [x] opengever.bs
- [x] opengever.ai
- [x] opengever.sg
- [ ] opengever.zug
- [ ] dev (4tw)
- [ ] test (4tw)
- [ ] nightly (4tw)
- [ ] lab (4tw)
- [ ] opengever.demo
- [ ] opengever.hpcdual
- [ ] opengever.nidau
- [ ] opengever.phvs
- [ ] opengever.phbern
- [ ] opengever.edk
- [ ] opengever.kgkoeniz
- [ ] opengever.duerrenaesch
- [ ] opengever.htwchur
- [ ] opengever.bistumbasel
- [ ] opengever.liesberg
- [ ] opengever.mumpf
- [ ] opengever.framsteg
- [ ] opengever.ftw
- [ ] opengever.ubit

**Comment by phgross** [comment]
opengever.zug PR is done as well. I'll close that issue.
