### ISSUE TITLE
Improve exception handling

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2501]
Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`

Currently SPV throws some assertion-errors. These should be replaced with proper Exceptions that describe the problem. This is especially true for sablon-errors that occur often.

**Comment by phgross** [comment]
@deiferni further specify

**Comment by phgross** [comment]
@deiferni further specify or close, please.

**Comment by deiferni** [comment]
Proper exceptions for sablon have been introduced in https://github.com/4teamwork/opengever.core/pull/4935. We'll keep the other `asserts`, they are mostly workflow related and will go away once/if we implement plone workflows.
