### ISSUE TITLE
Create downtime/maintenance page

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2525]
Please create a sinlge-page html downtime page, should:
- include onegov gever logo
- should be simple
- include downtime message:
> Momentan werden Wartungsarbeiten durchgeführt, wir sind in Kürze wieder für Sie da.
> 
> Besten Dank für Ihr Verständnis!

Please add it to https://github.com/4teamwork/opengever.maintenance in a `maintenance-page` directory

**Comment by deiferni** [comment]
update, should also display messages in french, i'd just display the messages next to each other:

(please add placeholder for french text, ill get translations)

**Comment by bierik** [comment]
@deiferni Hier ein erster Entwurf: http://codepen.io/bierik/pen/GrdvWP?editors=1100
