### ISSUE TITLE
Error in meeting.js

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#2545]
@bierik 
With this change you introduced a new error. 
At least on my machine...

<img width="669" alt="screen shot 2017-02-09 at 15 51 59" src="https://cloud.githubusercontent.com/assets/437933/22789583/ac6aa682-eee3-11e6-9b7e-c05815fe0f62.png">

Error:
<img width="467" alt="screen shot 2017-02-09 at 16 21 18" src="https://cloud.githubusercontent.com/assets/437933/22789625/d14cc9f8-eee3-11e6-93cf-fd29f65ead68.png">

**Comment by Rotonen** [comment]
Introduced here:
https://github.com/4teamwork/opengever.core/pull/2523
