### ISSUE TITLE
Test / Analyse PloneHotfix20161129

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#2550]
**Fixes plone.app.discussion DiscussionItems View permission:**
- Fixes the `comment_review_workflow` itself
- Fixes all created DiscussionItems

_Conclusion:_ 
opengever is not affected, sonce there are no DiscussionItems in use, nor the mentioned workflow. 

**Recursively remove copied items without View permission**
- After clone or paste an object, it recursively removes all objects without View permission from the copy.

⚠️ _Conclusion:_ 
- Potential different behavior, if an user copies a structure and does not have the view permission in every subelement because of ` __ac_local_roles_block__ = True`. This may result in a incomplete copy of the object. 
- Pontential different behavior, because the copied content is created in the initial worfklow state and the user may no longer has access to some content.

According to @lukasgraf the first scenario ist plausible in gever, the second one not, since the visibility is in all workflow states the same. 

**Remove several DocString from zope.interface.... Classes/Methods to prevent publishing**
``` 
element_methods = [
    'getDoc',
    'getName',
    'getTaggedValue',
    'getTaggedValueTags',
    'queryTaggedValue',
    'setTaggedValue',
]
interface_methods = [
    'changed',
    'dependents',
    'direct',
    'extends',
    'get',
    'getBases',
    'getDescriptionFor',
    'implementedBy',
    'interfaces',
    'isEqualOrExtendedBy',
    'isOrExtends',
    'names',
    'namesAndDescriptions',
    'providedBy',
    'queryDescriptionFor',
    'subscribe',
    'unsubscribe',
    'validateInvariants',
    'weakref',
]
```

_Conclusion:_
Cannot see any problems.

**Comment by phgross** [comment]
Der Hotfix `20161129` wird mit dem nächsten Release installiert und wurde auf dev.onegovgever.ch bereits installiert und getestet.
