### ISSUE TITLE
Test / Analyse Products.PloneHotfix20170117

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#2554]
**A reflected Cross Site Scripting attack (XSS) in the ZMI (``manage_findResult``).**

The patch adds a a `html_quote` to a input element in dtml file.

```diff
-  <INPUT TYPE="TEXT" NAME="obj_ids:tokens" SIZE="30" VALUE="<dtml-var "' '.join(obj_ids or [])">">
+  <INPUT TYPE="TEXT" NAME="obj_ids:tokens" SIZE="30" VALUE="<dtml-var "' '.join(obj_ids or [])" html_quote>">
```  

Conclusion:
Gever does no depend on this dtml view. 

**Accessing private content via ``str.format`` in through-the-web templates and scripts.**

It is possible to access all attributes thru string format with restricted Python. 

Example:

```
<div tal:content="python: 'Context class: {0.__class__} some text'.format(context)" />
```
Results in: `Context class: <class 'Products.CMFPlone.Portal.PloneSite'> some text`

But it should not be possbile to access `__class__` in RestrictedPython. 

In comparison (access `__class__` directly):
``` 
<div tal:content="python: 'Context class: {0} some text'.format(context.__class__)" />
```

Results in:
``` compilation failed
zope.tal.taldefs.TALError: Python expression error:
Line 1: "__class__" is an invalid attribute name because it starts with "_". in expression u"python: 'Context class: {0} some text'.format(context.__class__)"
``` 

Conclusion:
The above example results in a `ERR_TOO_MANY_REDIRECTS` with the Patch installed.  
IMHO this is no the expected behavior after installing the patch, but OK. it's no longer accessible.

_I was not able to found any code using the attribute access in `str.format`  in GEVER._
There's one template ["macros.pt"](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/browser/templates/macros.pt#L64) which uses `str.format` but without attribute access. 

Finally, after installing the patch:
- All tests are green.
- I was not able to produce any problems regarding this patch. 

👍

**Comment by phgross** [comment]
Der Hotfix `20170117` wird mit dem nächsten Release installiert und wurde auf dev.onegovgever.ch bereits installiert und getestet.
