### ISSUE TITLE
Aktennotiz: SearchableText wird bei Aktualisierung Kommentarfeld nicht aktualisiert

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2574]
Bearbeite ich das Kommentarfeld über das Symbol in der Byline, wird nach dem Speichern offenbar der SearchableText nicht aktualisiert. 

Bearbeite ich jedoch danach das Dossier (über "Bearbeiten") und speichere es wieder, findet dann die Volltextsuche den eingegebenen Kommentar.

**Comment by maethu** [comment]
Mit der restapi hat es noch funktioniert. Ging leider vergessen, als ich auf einen eigene Endpoint umgestellt habe. Der SearchabelText wird nun aktualisiert. Siehe #2582
