### ISSUE TITLE
Generalize and unify our zip exporters

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#2591]
We're currently building more and more subproduct specific zip exporters. Most of those build on top of tabbedview so we should be able to just generalize a bit and have an opengever.zipexport subproduct.

We should the very least extract a common core and share that across the exporters.

**Comment by deiferni** [comment]
There is already a searate package (https://github.com/4teamwork/ftw.zipexport) for that purpose 😉

**Comment by Rotonen** [comment]
Yes, but why do we keep rebuilding the same kinds of serializers on top of that one instead of genralizing the solution?

**Comment by deiferni** [comment]
At the moment we do it at one place in `opengever.meeting` where some extra work is required before zipping, like generating some files that are not (and should not be) available as plone content for example. Also collecting the files for the zip cannot follow a content hierarchy as the decision of what to include in the export is based on the relational SQL model.

I don't think that what we have enough code to justify another layer on top of `ftw.zipexport` at the moment as it is only used differently in one place (afaik). Please let me know if you disagree 😉 , or how/what you would have generalized?
