### ISSUE TITLE
Dossier aus Dossiervorlage: Es können keine neuen Schlagworte erfasst werden

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2599]
Die Dossiervorlage wurde so konfiguriert:

![bildschirmfoto 2017-02-21 um 16 35 21](https://cloud.githubusercontent.com/assets/485600/23171785/d4dc9584-f853-11e6-9b07-ff3af349daac.png)

Ich hätte in diesem Fall erwartet, dass ich bei Dossiers, die ich über diese Vorlage erzeuge, selber Schlagworte vergeben kann.

**Comment by maethu** [comment]
Das würde ich auch erwarten.

**Comment by maethu** [comment]
@phabegger 

Ich kann mit deinem User (pascal.habegger) neue Stichworte erfassen. 

<img width="1413" alt="screen shot 2017-02-21 at 16 59 45" src="https://cloud.githubusercontent.com/assets/437933/23172785/3f948622-f857-11e6-9296-1314a1ebfad5.png">

**Comment by maethu** [comment]
test user war `hugo.boss`

**Comment by maethu** [comment]
Irgendwie komisch:
Gestern konnte ich das Problem mit dir noch reproduzieren. Nun  nicht mehr. 

Vorlage ist wie folgt konfiguriert:
<img width="613" alt="screen shot 2017-02-22 at 09 48 10" src="https://cloud.githubusercontent.com/assets/437933/23203718/115719a4-f8e4-11e6-8581-b2d107753648.png">

![p1](https://cloud.githubusercontent.com/assets/437933/23203848/8fcbb132-f8e4-11e6-9c84-bfb269e6c273.gif)
