### ISSUE TITLE
Subject-Widget auch für Inhaltstyp Dokument und E-Mail aktivieren

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2600]
![bildschirmfoto 2017-02-21 um 16 42 46](https://cloud.githubusercontent.com/assets/485600/23172132/08a734fe-f855-11e6-822a-f92d1c30ce30.png)

**Comment by elioschmutz** [comment]
Dev-Info: https://github.com/4teamwork/opengever.core/pull/2539/commits
