### ISSUE TITLE
Dossiervorlage: Schlagworte mit Umlauten werden nicht angezeigt

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2604]
Hier die Dossiervorlage: 
![bildschirmfoto 2017-02-21 um 17 19 02](https://cloud.githubusercontent.com/assets/485600/23173657/314fca24-f85a-11e6-8065-129f2a9b12c2.png)

Hier das erzeugte Dossier:
![bildschirmfoto 2017-02-21 um 17 19 31](https://cloud.githubusercontent.com/assets/485600/23173629/15462db4-f85a-11e6-8f0f-c29dbc6402d2.png)

Schlagwort "Grösstes Baugesuch" fehlt.

**Comment by maethu** [comment]
Es bestand die Möglichkeit, dass Stichwörter mit Umlauten nicht als reguläre "Terms" im Vocabulary erkannt wurden. Wahrscheinlich wurde das Stichwort bereits auf der Vorlage nicht korrekt gespeichert. Durch das Update von heute (22.02.2017) sollte das Problem behoben sein.
