### ISSUE TITLE
Schlagworte in Dossiers, die über Dossiervorlage erstellt wurden, werden nicht gespeichert

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2605]
1. Dossier aus Dossiervorlage:

![bildschirmfoto 2017-02-21 um 17 29 55](https://cloud.githubusercontent.com/assets/485600/23174086/8c444210-f85b-11e6-8225-236cb16cf1e5.png)

2. Dossier speichern

![bildschirmfoto 2017-02-21 um 17 30 40](https://cloud.githubusercontent.com/assets/485600/23174099/938f9344-f85b-11e6-9565-a6aecc785508.png)

3. Dossier bearbeiten

![bildschirmfoto 2017-02-21 um 17 30 51](https://cloud.githubusercontent.com/assets/485600/23174109/9e19ce9c-f85b-11e6-9571-046f3591d763.png)

=> es werden keine Schlagworte mehr angezeigt.

**Comment by phabegger** [comment]
Getestet auf DEV-System.

**Comment by maethu** [comment]
Wurde in #2622 gelöst.
