### ISSUE TITLE
Schlagworte sind nicht suchbar

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2606]
Ich bearbeite ein Dossier und füge neues Schlagwort "beta" hinzu:

![bildschirmfoto 2017-02-21 um 17 39 30](https://cloud.githubusercontent.com/assets/485600/23174481/d08839f8-f85c-11e6-9fa4-e7c2e5fea3b0.png)

Die Suche nach "beta" findet jedoch das Dossier nicht.
![bildschirmfoto 2017-02-21 um 17 39 46](https://cloud.githubusercontent.com/assets/485600/23174510/e5eade22-f85c-11e6-9b67-5743cff938a4.png)

**Comment by maethu** [comment]
Info: Im Code `dexteritytextindexer.searchable('keywords')` sollte aktiviert sein. 
Ist allenfalls ein Bug im `dexteritytextindexer`

**Comment by maethu** [comment]
Es ist kein BUG, sondern ein "missing Feature". Widgets, welcher per Direktive konfiguriert sind, werden nicht berücksichtigt.

**Comment by lukasgraf** [comment]
@maethu Vorschlag: Für den Moment die Keywords einfach selbst im [schon bestehenden `IDynamicTextIndexExtender`](https://github.com/4teamwork/opengever.core/blob/master/opengever/dossier/indexers.py#L118-L152) für Dossiers anhängen?
