### ISSUE TITLE
Aktennotiz: Falls viel Text vertikal, wird dies nicht angezeigt (Chrome, Mac)

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2608]
Siehe https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-39#overview

![bildschirmfoto 2017-02-21 um 22 26 53](https://cloud.githubusercontent.com/assets/485600/23185787/edd731f8-f884-11e6-9cdf-21cd9923cb06.png)

Es ist nicht sichtbar, dass hier noch mehr Text in der Notiz oder dem Kommentar enthalten ist.

**Comment by maethu** [comment]
@phabegger 

hmm es muss noch an etwas anderem liegen: 
Ich habe mit OSX und Chrome/FF einen Scroll-Balken.

<img width="907" alt="screen shot 2017-02-23 at 08 43 16" src="https://cloud.githubusercontent.com/assets/437933/23249408/8369b7ca-f9a4-11e6-8178-1017a35dfd4f.png">

**Comment by maethu** [comment]
Nach Absprache mit Pascal, hist hier zu.
