### ISSUE TITLE
Namensgebung Titel Aktennotiz und Darstellung

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2609]
![bildschirmfoto 2017-02-21 um 22 30 45](https://cloud.githubusercontent.com/assets/485600/23185928/76083d4c-f885-11e6-9dc9-f8516ce091f8.png)

Bitte Titel umbenennen zu "Kommentar zu Dossier "...""

Und als Überschrift stylen, ohne underline.

**Comment by maethu** [comment]
- [ ] Bitte Titel umbenennen zu "Kommentar zu Dossier "..."" -- >829c4a5
- [ ] Und als Überschrift stylen, ohne underline. --> https://github.com/4teamwork/plonetheme.teamraum/commit/120808524ac2bdf78dfa8543b4e2777eb9b89a43
