### ISSUE TITLE
Bearbeiten Dossier: Beim Kommentarfeld standardmässig mehr Zeilen einblenden

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2610]
Aktuell werden nur 2 Zeilen angezeigt:

![bildschirmfoto 2017-02-21 um 22 34 14](https://cloud.githubusercontent.com/assets/485600/23186054/f8e5ce1e-f885-11e6-8273-52638bed94be.png)

Siehe https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-39/edit?_authenticator=70adf9e784251342418f6c7d6049340b60e3fa86

=> gleich viele Zeile wie bei Beschreibung anzeigen.

**Comment by maethu** [comment]
Wurde in https://github.com/4teamwork/plonetheme.teamraum/commit/aa9c10e1e3de367ed57994e6b30b822eee23331a gelöst.
