### ISSUE TITLE
Styling von Buttons bei Aktennotiz anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2611]
Siehe 
![bildschirmfoto 2017-02-21 um 22 36 52](https://cloud.githubusercontent.com/assets/485600/23186149/639b8852-f886-11e6-8ff5-6c76568b1df9.png)

=> Gleich stylen wie andere Buttons in OneGov GEVER, z.B. wie bei Bearbeiten-Formular:

![bildschirmfoto 2017-02-21 um 22 38 31](https://cloud.githubusercontent.com/assets/485600/23186182/7fa3d324-f886-11e6-92b5-7e1b566dc165.png)

- gleiche Grösse, Farben, etc.

**Comment by maethu** [comment]
Wurde in:
- https://github.com/4teamwork/plonetheme.teamraum/commit/2e9ddfc50fcc7f0918ae98823ad892741edb96ed
und 
- b8cea27
gelöst
