### ISSUE TITLE
Hinweis auf Aktennotiz bei Byline im Dossier anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2612]
"Dossier Kommentar" durch "Kommentar" ersetzen.

![bildschirmfoto 2017-02-21 um 22 40 19](https://cloud.githubusercontent.com/assets/485600/23186322/034c9a94-f887-11e6-87cd-9b15c093fbbe.png)

**Comment by maethu** [comment]
In 60a3feb angepasst
