### ISSUE TITLE
Position und Grösse des Kommentars / Aktennotiz anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2614]
Aktuelle Implementierung reagiert zu wenig auf Grössenveränderungen bei Browser. Siehe z.B.  hier:

![bildschirmfoto 2017-02-21 um 22 51 41](https://cloud.githubusercontent.com/assets/485600/23186763/7f598cfe-f888-11e6-8861-a0a1cec6bb47.png)

Ich hätte erwartet, dass das Overlay horizontal zentriert bleibt (siehe Verhalten bei Wunderlist, Notiz bei ToDo), scheint aber irgendwie fix zu sein. 

Aus meiner Sicht muss das Fenster höher als breit sein, siehe z.B. bei Wunderlist:

![bildschirmfoto 2017-02-21 um 22 54 28](https://cloud.githubusercontent.com/assets/485600/23186836/d0d2af84-f888-11e6-80ec-a892a59b9a30.png)

**Comment by maethu** [comment]
Im Moment verhält sich das Overlay wie alle Plone-Overlays. 
Ich schaue mal was sich da machen lässt. Die Overlays sind by design im Moment nicht responsive.

**Comment by maethu** [comment]
Die Positionierung wurde verbessert. 
Leider konnte ich das nicht für alle Overlays übernehmen :-( 

Gelöst in:
- ef0ca58
- https://github.com/4teamwork/plonetheme.teamraum/commit/1a2ac50a976635c8e7a8f08bde821739d5e4d297

**Comment by maethu** [comment]
![p3](https://cloud.githubusercontent.com/assets/437933/23261112/29eb4cbe-f9d5-11e6-8a2a-c9dab21dbcc8.gif)
