### ISSUE TITLE
No separate tab "Ablage"

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2629]
There is currently only one field in that tab, could we move that field to the other tab?

![screen shot 2017-02-27 at 11 14 08](https://cloud.githubusercontent.com/assets/736583/23357410/eb439a78-fcdd-11e6-8acb-b10cc1a4bec5.png)

**Comment by elioschmutz** [comment]
@deiferni Same here like in #2632. We decided to reuse exactly the same schema like in the dossier. This change would be against this decision.

**Comment by deiferni** [comment]
same here, i agree.
