### ISSUE TITLE
Add Description for checkboxes on Dossier-Templates

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2630]
The two checkboxes that manipulate labels should have a short descriptiton.

![screen shot 2017-02-27 at 11 16 17](https://cloud.githubusercontent.com/assets/736583/23357496/4560ae74-fcde-11e6-9007-6e02a069f89d.png)

**Comment by phgross** [comment]
![bildschirmfoto 2017-05-01 um 09 25 21](https://cloud.githubusercontent.com/assets/485755/25574588/1f35e338-2e50-11e7-8bcb-0fcf63c0c590.png)

Wurde mit #2750 erledigt.
