### ISSUE TITLE
Issues with IE11 on Keyword-Widget

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2631]
![ie11_shit](https://cloud.githubusercontent.com/assets/736583/23363530/5af1efc4-fcfb-11e6-94af-5a29e38885b5.png)

After typing 1-3 characters the text-field looses focus, and focus has to be reset to the field.

There is an error when deleting content with backspace.

_I created the issue in here for tracking purposes, even though a solution will most likely go into https://github.com/4teamwork/ftw.keywordwidget_

**Comment by elioschmutz** [comment]
Hint: Fehler wurde bereits in einem anderen Kundenprojekt behoben: https://github.com/4teamwork/ivbe.intranet/issues/200

**Comment by elioschmutz** [comment]
Fixed by: https://github.com/4teamwork/ftw.keywordwidget/pull/6
