### ISSUE TITLE
Rename field title to template title

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2632]
When adding a dossier template the title (Titel) field should be called template title (Titel der Vorlage).

![screen shot 2017-02-27 at 14 59 13](https://cloud.githubusercontent.com/assets/736583/23363950/646e8ce0-fcfd-11e6-8bf9-63409edd037b.png)

**Comment by elioschmutz** [comment]
@deiferni sure?

If we change it, we would have to rename all the fields, i.e. description to template description for consistently reasons.

Also we decided to use the exact same schema as the dossier. So this changes would be against this decision, too. 

In addition, if I would read "template title" i would suppose that this is only the title of the template and not of the generated dossier.

In the current implementation, we are consistent with document templates, too.

So in my opinion for all this reasons, we should not change the title!

**Comment by deiferni** [comment]
title won't be changed. does not make sense.
