### ISSUE TITLE
Update ConstrainTypeDeciders used in policies

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#2639]
With #2638, the `DefaultConstrainTypeDecider` now respects the registry setting. This makes customization of the dossier nesting depth for the standard dossier type in policies easier, since it's now enough to set the registry setting, and the Adapter can be dropped.

Also, the way certain policies override the adapter leads to dropping the configuration for private dossiers, so those need to be fixed if the private dossier feature is enabled for those deployments.

**Comment by phgross** [comment]
Policies to adjust:
- [ ] opengever.zug
- [ ] opengever.ai
- [ ] opengever.sg
- [ ] opengever.edk
- [ ] opengever.hpcdual
- [ ] opengever.phvs

**Comment by phgross** [comment]
@elioschmutz please remove the DefaultConstrainTypeDecider in the policies.

**Comment by elioschmutz** [comment]
@deiferni Pls take another look at the PRs related to this issue.

**Comment by deiferni** [comment]
✅
