### ISSUE TITLE
Fehler bei Schlagwörter mit Leerschlag 

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2655]
Beim Hinzufügen von Schlagwörter mit einem Leerschlag wird ein `unicode`-error generiert.

![screen2](https://cloud.githubusercontent.com/assets/557005/23513810/a9da083a-ff65-11e6-8cc7-65504c481a48.gif)

**Comment by deiferni** [comment]
Also fixed in https://github.com/4teamwork/ftw.keywordwidget/pull/8, was a duplicate of https://github.com/4teamwork/opengever.core/issues/2656, as suspected.
