### ISSUE TITLE
Fehler bei Schlagwörtern wenn nur ein Schlagwort eingegeben wird

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2656]
Wird nur ein Schlagwort eingegeben, wird ein `unicode`-Error generiert:

Ein Schlagwort:
![screen2](https://cloud.githubusercontent.com/assets/557005/23514268/220cd46c-ff67-11e6-8199-c194295ed195.gif)

Zwei Schlagwörter:
![screen2](https://cloud.githubusercontent.com/assets/557005/23514307/3e14b29c-ff67-11e6-8f2d-555ecf097bad.gif)

Siehe auch #2655

**Comment by elioschmutz** [comment]
Fix in https://github.com/4teamwork/ftw.keywordwidget/pull/8

**Comment by deiferni** [comment]
Fixed in https://github.com/4teamwork/ftw.keywordwidget/pull/8.
