### ISSUE TITLE
Schlagwörter werden nicht im Dossier gespeichert

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2658]
Werden Schlagwörter eingegeben und anschliessend mit einem Validation-Error gespeichert, müssen die Schlagwörter erneut eingegeben werden (siehe #2657).

Werden diese Schlagwörter erneut eingegeben und anschliessend ohne Validation-Error gespeichert, werden diese jedoch nicht auf dem Objekt gespeichert. Zusätzlich hinzugefügte Schlagwörter werden jedoch korrekt gespeichert.

![screen2](https://cloud.githubusercontent.com/assets/557005/23514625/290ee858-ff68-11e6-937d-c5f77a978702.gif)

**Comment by deiferni** [comment]
This has been fixed in https://github.com/4teamwork/ftw.keywordwidget/pull/10, but now the keywords may be duplicated 😲

**Comment by deiferni** [comment]
more in  https://github.com/4teamwork/ftw.keywordwidget/issues/11
