### ISSUE TITLE
Mail-In: Schöne Fehlermails

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2663]
Es wäre schön, wenn wir die Mail-In Fehlermails.
Hier ein Beispiel aus my.teamraum.com:
![e77f0706-b67c-11e3-96ea-13f41653dde1](https://cloud.githubusercontent.com/assets/7469/23669753/a2e2a6be-0365-11e7-868a-2188dbe97a59.png)

Dies wurde im PR https://github.com/4teamwork/my.teamraum/pull/438 eingebaut, dort sind verschiedene Problem illustriert. Notwendig dafür ist https://github.com/4teamwork/ftw.mail/pull/15 .

Ist das Mailing in GEVER standardisiert, im Sinne eines "main-templates" für mails?

**Comment by deiferni** [comment]
Ich fände das sinnvoll, im Moment antwortet bei uns das Mail Delivery System mit dem bekannten:

> I'm sorry to have to inform you that your message could not
> be delivered to one or more recipients. It's attached below.
> 
> For further assistance, please send mail to postmaster.
> 
> If you do so, please include this problem report. You can
> delete your own text from the attached returned message.
