### ISSUE TITLE
Kontingent für die persönliche Ablage

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2664]
Die in #2158 eingeführte persönliche Ablage soll neu kontigentiert werden können.

**Idee:**
Die Benutzer sollen sparsam mit der persönlichen Ablage umgehen. Sie soll verwendet werden um Geschäfte vorzubereiten, nicht als Ersatz für das Home-Laufwerk.

**Konzept:**
1. Das Kontingent gilt pro Benutzer, also pro persönliche Benutzerablage (`opengever.private.folder`).
1. Die Kontingentierung ist optional und wird global für alle Benutzer gleich konfiguriert (keine Erhöhung pro Benutzer vorgesehen) (`portal_registry`).
1. Es kann ein Soft- und ein Hard-Limit konfiguriert werden.
1. Es werden die Primärdaten (=Blobs) der Typen "Dokument" und "Mail" gezählt.
1. Voraussichtlich werden Versionen nicht gezählt, einerseits aus technischen Gründen (Komplexität), andererseits ist dies nicht zentral (siehe Idee).
1. Eine Aktion / View `Nutzung` ~~Ein Tab `Kontingent`~~ wird auf der persönlichen Ablage eingeblendet, welche~~s~~ den Verbrauch und die Limits anzeigt.
1. Es gibt kein Admin-Panel (wäre problematisch bei vielen Benutzern): ein administrativer Eingriff ist nicht vorgesehen, da durch das Hard-Limit das Kontingent erzwungen wird.
1. Wird das *Soft-Limit* überschritten, so erscheint ab dann auf jeder Seite immer eine Warnmeldung (analog `ftw.globalstatusmessage`).
1. Wird das *Hard-Limit* überschritten so können keine Dokumente oder E-Mails [1] mehr erstellt werden: es werden Fehlermeldungen angezeigt.
1. Dokumente im Papierkorb zählen nicht gegen das Soft- oder Hard-Limit.
1. Verschieben von Dokumenten / Dossiers sollte auch bei erreichtem Hard-Limit noch möglich sein, sofern das Quota nicht erhöht wurde.

[1] Dies sollte in #2663 berücksichtigt werden.

(Gehört zu `Feature: Persönliches Dossier / Ablage`)

**Comment by lukasgraf** [comment]
Finde ich grundsätzlich tiptop so. 👍

Ergänzungen:
- Dokumente im Papierkorb zählen nicht gegen das Soft- oder Hard-Limit
- Verschieben von Dokumenten / Dossiers sollte auch bei erreichtem Hard-Limit noch möglich sein (Berücksichtigen beim Mechanismus für die Prüfung des Limits (Events?))
- *so erscheint ab dann auf jeder Seite immer eine Warnmeldung* - könnte nerven. Soll es allerdings auch. Mal sehen wie das ankommt. :man_shrugging:

**Comment by phgross** [comment]
👍 Tiptop. 

Die Warnmeldung auf jeder Seite, könnte tatsächlich recht nervig sein, anderseits haben die Benutzer ja auch die Möglichkeit etwas dagegen zu tun.

**Comment by jone** [comment]
Merci für die Ergänzungen.

**ftw.quota**
`ftw.quota` basiert auf einem schemaextender adapter, funktioniert also im Moment nur für Archetypes. Daher ist der Value von `ftw.quota` gering, bzw. man müsste viel ändern. Daher würde ich dies direkt im GEVER bauen.

**Technisches**
In `ftw.quota` wird die Usage-Zahl auf dem Qutoa-Container geführt und laufend addiert / subtrahiert, quasi ein Cache. Die Gefahr besteht, dass diese Zahl inkonsistent wird, z.B. bei Fehler in der Applikation (Manipulation per Script, Modified-Event nicht gefeuert, ...).

Eine andere Variante wäre, dies mit dem Katalog Metadatum `getObjSize` laufend zu berechnen. Dies wird einfach sehr teuer: für die Status-Message ("Soft-Limit überschritten") würde es pro Request ein Catalog-Query über den Home-Folder benötigen, wobei dann effektiv alle Brains geweckt würden.

Da mir die Katalog-Variante zu teuer scheint und die Performance grundsätzlich negativ beeinflusst werde ich vorerst den Cache-Ansatz von `ftw.quota` verfolgen.

**Comment by deiferni** [comment]
👍 

Ich schliesse mich den Bedenken bei der überall sichtbaren Statusmessage an, eventuell wäre es sinnvoller, diese nur im persönlichen Bereich darzustellen?

**Comment by jone** [comment]
Die Statusmessage auf den persönlichen Bereich zu limitieren ist vermutlich das beste und sollte einfach machbar sein 👍
