### ISSUE TITLE
Allow to add response without a state change to tasks

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2666]
A user should be able to add a response to a task without changing the review state, for example to add a small update of the current status.

It should be visible in the process listing as all the other responses.

**Comment by elioschmutz** [comment]
Spez:

- [ ] Button with text "Comment" / "Kommentieren"
- [ ] Click on the button will open a form (no overlay) like the transition-actions
- [ ] Ever user with edit-permission can add a comment
- [ ] Closed tasks can be commented as well.

The GUI will looks like below:

![bildschirmfoto 2017-03-21 um 16 21 37](https://cloud.githubusercontent.com/assets/557005/24156932/4cf7c3bc-0e58-11e7-8393-977b334523ec.png)

![bildschirmfoto 2017-03-21 um 17 09 48](https://cloud.githubusercontent.com/assets/557005/24157267/390df99c-0e59-11e7-9052-bde2ac2d6979.png)

**Comment by deiferni** [comment]
> Closed tasks can be commented as well.

I agree, but tasks in a closed dossier should no longer be comment-able.

Also, i would add the comment button on the right side to keep the current button positions.

**Comment by elioschmutz** [comment]
👍  i updated my spez. with your input
