### ISSUE TITLE
Reset end date when reactivating a dossier

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2667]
The `end` date of a dossier should be cleared when a dossier gets reactivated.

**Comment by phabegger** [comment]
Bei der Wiedereröffnung des Dossiers bleibt im Moment das Feld "Ende" befüllt, das Feld muss jedoch geleert werden.

**Comment by deiferni** [comment]
@phabegger da gibts schon einen pull-request dazu, siehe link oben 😉
