### ISSUE TITLE
Bewertungsliste als Excel: Dateiname anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2675]
Heisst im Moment immer disposition_report.xls. Vorschlag: bewertungsliste_angebot_xy.xls .

![disposition_report](https://cloud.githubusercontent.com/assets/485600/23757570/824ba26a-04e7-11e7-8bf3-2df12bedac2e.png)

**Comment by yindao50** [comment]
good

**Comment by phgross** [comment]
@njohner bitte anpassen.

Kleiner Hint: `opengever.disposition.browser.excel_export`
Dokumentation zum Aussonderungsmodul findest du hier https://docs.onegovgever.ch/admin-manual/aussonderung/

**Comment by phgross** [comment]
Closed via #3634
