### ISSUE TITLE
Fehler beim Rendern der Contentactions bei Ansicht eines Angebots mit Rolle Archivar

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2676]
Eingeloggt als Archivar: Im Overlay können Content Actions nicht angezeigt werden:

![skizze_aussonderung](https://cloud.githubusercontent.com/assets/485600/23758089/e92696f6-04e8-11e7-8da8-c45fb48411b1.png)

**Comment by phgross** [comment]
Fehler kann in der neusten Versionen auf dev.onegovgever.ch nicht mehr reproduziert werden, ich schliesse den Issue
