### ISSUE TITLE
Unzureichende Berechtigung nach "Bewertung finalisieren" durch Archivar

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2677]
![skizze aussonderung fehler](https://cloud.githubusercontent.com/assets/485600/23758353/cc443ed4-04e9-11e7-8344-9525663cd75a.png)

=> Die Bewertung wird nicht finalisiert!

**Comment by phabegger** [comment]
Führe ich die gleiche Aktion als "Records Manager" durch, klappt es.

**Comment by phgross** [comment]
@phabegger weisst du noch bei welchem Angebot die Aktion "Bewertung finalisieren" nicht klappt? Ich kann die Probleme mit dem Benutzer `peter.archivar` nicht reproduzieren. Siehe https://dev.onegovgever.ch/fd/ordnungssystem/disposition-13#overview

**Comment by phgross** [comment]
Fehler wurde mit den Anpassungen am Angebots- und Dossierworkflow im PR #2731 behoben.
