### ISSUE TITLE
Unzureichende Berechtigungen bei Aktion "Archivieren" in der Rolle Archivar

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2679]
Siehe Screenshot.

![skizze_aussonderung fehler archivierung](https://cloud.githubusercontent.com/assets/485600/23759109/19f2ac9a-04ec-11e7-9aa5-1888db79e822.png)

Als Records Manager steht diese Aktion nicht zur Verfügung

**Comment by phabegger** [comment]
Das Selbe passiert übrigens auch, wenn ich das Angebot "ablehne".

**Comment by phgross** [comment]
Fehler wurde mit den Workflow Anpassungen im PR #2731 behoben.
