### ISSUE TITLE
Löschprotokoll: Keine Ablieferungsnummer

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2682]
Bei der Ansicht des Löschprotokolls fällt mir auf, dass keine Ablieferungsnummer vergeben wird. Hätte wer? die eintragen müssen? Falls ich das hätte machen müssen, müsste ich darauf hingewiesen werden (vor dem Löschen).
![ablieferungsnummer](https://cloud.githubusercontent.com/assets/485600/23760267/762b0180-04ef-11e7-9d03-cae0c2253972.png)

**Comment by phgross** [comment]
Die Ablieferungsnummer ist nicht obligatorisch und kann von einem Archivar bei der Bewertung, also vor dem finalisieren angepasst werden.

Erich hat sich für das Feld Ablieferungsnummer auch eine prominentere Darstellung (direkt auf der Angebots-Ansicht) gewünscht. Ich erachte das aber nicht als super kritisch, daher eher April und nicht März Milestone, @phabegger was denkst du?

**Comment by phgross** [comment]
Ich habe einen separater Issue für die Platzierung des Feldes Transfernummer eröffnet. Ich schliesse diesen Issue, da die Ablieferungsnummer im Löschprotokoll korrekt dargestellt wird.
