### ISSUE TITLE
Tabbedview: Fehlerhafter etag

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#2688]
Es wurde festgestellt, dass der `etag` der tabbedview fälschlicherweise `None` sein kann.
Fix: https://github.com/4teamwork/ftw.tabbedview/pull/67

**Comment by deiferni** [comment]
Fixed by https://github.com/4teamwork/ftw.tabbedview/pull/69 and/or https://github.com/4teamwork/ftw.tabbedview/pull/67
