### ISSUE TITLE
Multiline editor should look nicer for checking in with a comment

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#2690]
![screen shot 2017-03-10 at 15 13 51](https://cloud.githubusercontent.com/assets/935317/23798290/3c9d12ea-05a4-11e7-9c22-442c19b05eaa.png)

Currently it does not even look like a multiline editor. Should also limit the width to some maximum?

**Comment by phabegger** [comment]
I suggest to limit it in width and increase its height.
