### ISSUE TITLE
Footer bei Standardinstallation OGG anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2692]
![unbenannt](https://cloud.githubusercontent.com/assets/485600/23799597/62067896-05a9-11e7-902e-90cc77837b82.PNG)

Neu: 
- [Office Connector (Windows und Mac)](https://www.4teamwork.ch/office-connector)
- "Benutzerhandbuch" ersetzen durch "Benutzerhandbücher"

**Comment by elioschmutz** [comment]
closes by #2769
