### ISSUE TITLE
Format der Archivdatei von JPG sollte TIFF sein

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2701]
![bildschirmfoto 2017-03-10 um 20 09 52](https://cloud.githubusercontent.com/assets/485600/23809348/a1e33d40-05cd-11e7-95d4-e445a4a03ee3.png)

**Comment by phgross** [comment]
Bumblebee unterstützt zurzeit die Konvertierung von JPEG nach TIFF nicht. Dies müsste zuerst seitens von Bumblebee implementiert werden. Anschliessend müsste auch GEVER-seitig bei der Konvertierung das gewünschte Format abhängig vom Filetypen angepasst werden (siehe https://github.com/4teamwork/opengever.core/blob/master/opengever/document/archival_file.py#L28).

Ich erachte es nicht als realistisch das die Anpassung im Bumblebee noch diese Woche angepasst werden kann, ich entferne deshalb den März Milestone.

**Comment by phgross** [comment]
Zurzeit sind diesbezüglich noch Abklärungen im Gange. Es ist nicht genau klar wie mit Bildern umgegangen werden soll. Ich schliesse deshalb diesen Issue vorerst.
