### ISSUE TITLE
Verwirrende Aktion "Zusätzlichen Anhang einreichen" auf Dokument

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2702]
Diese Aktion habe ich auf allen Dokumenten in einem offenen Dossier:

![bildschirmfoto 2017-03-10 um 20 13 27](https://cloud.githubusercontent.com/assets/485600/23809501/3654c6d8-05ce-11e7-8b83-6bf448eab1c4.png)

Sehr verwirrend - braucht es diese Aktion wirklich? Falls ja, dann eher "An einen Antrag anhängen" oder so. Ist ja nicht ein Anhang, sondern ein Dokument.

Allerdings verwirrt dann folgende Eingabemaske:

![bildschirmfoto 2017-03-10 um 20 16 30](https://cloud.githubusercontent.com/assets/485600/23809580/7986e7a6-05ce-11e7-9d93-b9a3d4e8829f.png)

- Maske hat keinen Titel (sollte wohl heissen: "Dokument xy an Antrag anhängen")

- "Anhänge einreichen" wäre dann wohl "Dokument an Antrag anhängen". Der Antrag muss dann separat eingereicht werden (?)

**Comment by phgross** [comment]
@deiferni prüfen ob noch notwendig. Danach bitte Vorschlag für Titel der Aktion sowie Formulartitel liefern.

**Comment by phgross** [comment]
Wurde mit #4606 umgesetzt und in der Zwischenzeit nun auch zu `Zusätzliche Beilagen einreichen` umbenannt.
