### ISSUE TITLE
Spaltenbreite Checkboxen bei Aufgabenauflistungen zu gross

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2720]
Getestet mit Windows Edge (ist aber auch in IE so):

Die Spalte mit den Checkboxen ist viel zu breit:
![tabelle-spaltenbreite aufgaben](https://cloud.githubusercontent.com/assets/485600/23862000/1882730e-080c-11e7-9e9e-4b8c5f1eb504.png)
Besser: Fixe Spaltenbreite 

Bei Dokumentauflistungen ist dies besser:

![spaltenbreite-dokumente](https://cloud.githubusercontent.com/assets/485600/23862373/1a510726-080d-11e7-8487-e6e8cff0e64d.png)

Allerdings kann ich in der Spalte mit den Checkboxen auch gruppieren etc., was keinen Sinn macht (bzw. einen Fehler generiert!). 

Besser: 
- Dropdown-Menü von ExtJS auf dieser Spalte ganz ausblenden
- Spalte nicht "resizeable" machen

Möglicherweise tritt das Problem auch bei anderen Tabellenauflistungen auf - bitte prüfen.

**Comment by deiferni** [comment]
This issue may have already been addressed with https://github.com/4teamwork/opengever.core/pull/2684

**Comment by deiferni** [comment]
Update: only the size has been adressed, drop-down to perform actions is still visible on at least documents and tasks tabs in personal overview. Dossier may be affected, too.

**Comment by elioschmutz** [comment]
Grundsätzlich wird das Dropdown-Menu für die Checkbox-Spalte bereits ausgeblendet:

![screen1](https://cloud.githubusercontent.com/assets/557005/23895591/952a6cb4-08a6-11e7-9506-3c82ce9eac03.gif)

Sobald jedoch eine andere Spalte sortiert wird, wird auch das Dropdown-Menu für die Checkbox-Spalte angezeigt:

![screen1](https://cloud.githubusercontent.com/assets/557005/23895638/bbda2e80-08a6-11e7-9174-caf5be2bd1fd.gif)

Der Fehler lässt sich nur durch das Zurücksetzten der Tabellenkonfiguration wieder beheben. Einen Pagereload behebt das Problem nicht. Das Zurücksetzten der Tabellenkonfiguration ist jedoch keine Option. Zudem würde es das Problem nur temporär beheben.

Mein Lösungsvorschlag wäre, lediglich die Gruppierung für die Checkbox auszuschalten. Dieses Feature steht der `ftw.table` leider noch nicht zur verfügung. @jone hat dazu jedoch schonmal einen Commit erstellt (https://github.com/4teamwork/ftw.table/commit/d83bfb30a0f21c53bec92c2e05044aa844dd0293). Diesen können wir für die neuste `ftw.table` Version verwenden.

Mit diesem Fix wäre das Verhalten folgendermassen:
- bei einer neuen Tabelle oder bei einer Tabelle mit einer zurückgesetzten Konfiguration wird kein Dropdown-Menu angezeigt
- bei einer veränderten Tabelle wird zwar das Dropdown-Menu angezeigt, der Benutzer kann jedoch nicht danach Gruppieren/Sortieren

![screen1](https://cloud.githubusercontent.com/assets/557005/23895909/cb90728e-08a7-11e7-8c54-74b71def01b8.gif)

Eine andere Lösung steht momentan nicht zur Verfügung.

@deiferni @phabegger seid ihr mit diesem Lösungsvorschlag einverstanden?

**Comment by deiferni** [comment]
Wäre für mich grundsätzlich ok, aber für den Benutzer etwas unschön.

Eine Alternative, die ich mir auch noch vorstellen könnte wäre das Menu für gewisse Spalten GEVER-Seitig per CSS auszublenden. Vielleicht schafft man es durch ein paar "einfache" Anpassungen, dass die generierte CSS-Klasse des Spalten-Headers immer gleich ist. Z.b. indem man die eine id als Konfiguration bei der Definition der Spalte mitgeben kann, die dann ausgelesen und gesetzt wird, anstatt bisher column_name, oder `__name__` der angegebenen `transform`. z.B.:

```python
    columns = (
        {'column_id': 'really_really_unsortable_checkbox',
         'column': '',
         'column_title': '',
         'transform': path_checkbox,
         'sortable': False,
         'width': 30},
```

https://github.com/4teamwork/ftw.table/blob/master/ftw/table/utils.py#L244-L255 schaut vielsversprechend für Anpassungen in `ftw.table` aus.

**Comment by deiferni** [comment]
Btw, im Moment kann ichs für einzelne Spalten mit folgendem CSS ausblenden:
```css
tr.x-grid3-hd-row {
  .x-grid3-td-path_checkbox {
    a.x-grid3-hd-btn{
      display: none;
    }
    div.x-grid3-sort-icon {
      display: none;
    }
  }
}
```

**Comment by elioschmutz** [comment]
Die erste Lösung würde kein valides HTML generieren.

Die zweite Lösung wäre allenfalls eine Alternative wobei es für den Benutzer schöner wäre, jedoch nicht für Entwickler :trollface:  

Darf das Menu explizit für alle path_checkboxes ausgeblendet werden? Gibt es keine Usecases bei denen das Menu trotzdem angezeigt werden soll?

Falls ja, würde ich diese Lösung umsetzten.

**Comment by deiferni** [comment]
wie meinst du:

> Die erste Lösung würde kein valides HTML generieren.

?

`.x-grid3-td-path_checkbox` ist nur ein (schlechtes) Beispiel wie mans für genau eine Tabelle/Tab erreicht. Das Problem ist, dass der Name der Transform-Methode (in diesem Fall `path_checkbox`) als Klassenname der Header-Spalte der gerenderten Tabelle gebraucht wird, und nicht etwas, das wir bei allen Tabellen/Spalten bei denen wir die Drop-Downs deaktivieren wollen, gleich konfigurieren können. So müssten wir die Styles für alle unterschiedlichen Checkbox-Helper Methoden duplizieren was nicht sinnvoll ist.

**Comment by elioschmutz** [comment]
Sorry, habe falsch überlegt. Dachte, dass die ID dann für jede Zelle übernommen werden sollte und es hätte dann mehrere gleiche IDs gegeben => dem ist jedoch nicht so 😉 

Hier kurz zusammenfassend:

Lösung 1:
- bestehender Commit 4teamwork/ftw.table@d83bfb3 für `ftw.table` übernehmen
- Gruppierung für die Checkbox-Spalte ausschalten

Lösung 2:
- `ftw.table` mit der Funktion `column_id` erweitern
- `column_id` für die Checkboxes setzten
- mit CSS das Menu ausblenden

Der Aufwand von Lösung 2 ist grösser da ich die `ftw.table` erweitern muss. Bei der Lösung 1 ist bereits alles vorhanden dafür ist das Menu für den Benutzer weiterhin sichtbar.

Entscheid?

**Comment by deiferni** [comment]
ok - dann bin ich für 1).

**Comment by phabegger** [comment]
Ich auch 👍
