### ISSUE TITLE
Einstellungen Spaltenbreite Versionentabelle bei Dokumenten wird nicht persistiert

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2721]
Ich habe die Spalte mit dem Kommentarfeld sehr breit gemacht, aber meine Einstellungen werden nicht gespeichert - beim nächsten Aufruf des Versionen-Tabs ist die Spalte wieder zu schmal.

![spaltenbreite-versionen-persistieren](https://cloud.githubusercontent.com/assets/485600/23862936/aa32722a-080e-11e7-80dd-819f436b3acd.png)

Bei übrigen Tabellenauflistungen funktioniert es dagegen prima.

**Comment by phabegger** [comment]
Nachtrag: Die Spalteneinstellungen werden auch nicht bei Journal-Tab (bei Dokument) gespeichert.

Getestet auf dev.onegovgever.ch, mit meinem persönlichen Benutzer.

**Comment by elioschmutz** [comment]
- [ ] Spaltenbreite im Versionen-Tab soll gespeichert werden 
- [ ] Spaltenbreite im Journal-Tab (bei Dokumenten) soll gespeichert werden

**Comment by elioschmutz** [comment]
@phgross This Issue is fixed. Just buildout and try it 😉
