### ISSUE TITLE
Draggable-Spalte entfernen

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2726]
Es gibt eine spezielle Draggable-Spalte welche nur in Tasktemplates und Tasktemplatefolders verwendet wird:

![bildschirmfoto 2017-03-14 um 11 34 28](https://cloud.githubusercontent.com/assets/557005/23896593/3acde94a-08aa-11e7-990c-d8066533ce7e.png)

Wie mit @jone besprochen, wurde die Spalte ursprünglich dazu verwendet, Aufgaben innerhalb eines Aufgaben-Vorlagen-Ordners zu sortieren, damit z.B. die Aufgabe "Benutzer im AD erfassen" vor "mit Benutzer einloggen" dargestellt wird. Dieses Konzept hat jedoch nie funktioniert. Sobald der Aufgabenordner in einem Dossier erstellt wird, werden die Aufgaben nicht mehr sortiert dargestellt. 

Somit ist diese Funktion überflüssig. Da es die Sortierung bereits einige Jahre für die Aufgabenvorlagen gibt, scheint die Funktion auch niemand zu benutzen.

- [x] die draggable-Spalte mit dem Helper `helper.draggable` entfernen

@deiferni @jone ok für euch?

related Issue #2720

**Comment by deiferni** [comment]
👍

**Comment by jone** [comment]
👍
