### ISSUE TITLE
Löschen von Dossiervorlagen?

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2739]
Ich kann zwar Dossiervorlagen hinzufügen und bearbeiten, aber nicht löschen bzw. in den Papierkorb verschieben. 

Dies sollte jedoch möglich sein (wie es bereits bei den Dokumentvorlagen möglich ist).

![dossiervorlagen-loschen](https://cloud.githubusercontent.com/assets/485600/23945190/de493e5a-0975-11e7-9c4e-678b80104d70.PNG)

Bitte daran denken, dass dies bei Ordnungspositionen, die bestehende Einschränkungen auf die gelöschte Dossiervorlagen habe, dies möglicherweise zu Problemen führen kann (da Vorlage nicht mehr vorhanden).

- [x] Allow remove dossiertemplates

**Comment by phgross** [comment]
@elioschmutz bitte analysieren und kurz ein Vorschlag für die "Referenzproblematik" erarbeiten.

**Comment by elioschmutz** [comment]
**1. Umsetzung**

- [ ] 1.1  DossierTemplate muss das ITrashable-Behavior implementieren
- [ ] 1.2 Papierkorb-Tab im Vorlagen-Ordner anzeigen (siehe Punkt 2.1)
- [ ] 1.3 Papierkorb für Dossiers kompatibel machen
  - [ ] 1.3.1 Papierkorb-Tabelle im Vorlagen-Ordner anpassen, damit diese nur gemeinsame Attribute anzeigt
  - [ ] 1.3.2 Delete-Transition für Dossier Templates hinzufügen (Workflow-Anpassung!!!), evt. sogar eigener Workflow für DossierTemplates erstellen (muss genauer Analysiert und besprochen werden)
  - [ ] 1.3.3 Grundsätzliche Generalisierung von opengever.trash. Das Modul ist an vielen Orten nicht mit Dossiers kompatibel da es spezifische attribute von Dokumenten verwendet.
- [ ] 1.4 Anpassungen in View: `dossier_with_template` damit gelöschte Dossiers berücksichtigt werden (siehe Punkt 3.3)

Alle Anpassungen am Papierkorb (Punkte 1.2 und 1.3) müssen nur gemacht werden, wenn der Papierkorb auch angezeigt werden soll.

**2. Fragen:**

2.1 Der Papierkorb wird momentan nicht in den Vorlagen angezeigt. D.h. Dokumentvorlagen im Papierkorb können momentan nicht komplett gelöscht oder wiederhergestellt werden. Ist dies eine bewusste Entscheidung?

**3. Referenzproblematik:**

3.1 Da im GEVER grundsätzlich nichts gelöscht wird, wird es auch keine Probleme mit den Referenzen geben.

3.2 Problematischer ist, dass Dossiers (DossierTemplates) grundsätzlich gelöscht werden sollen. Dies war im GEVER nicht vorgesehen und wurde somit an vielen Orten nicht berücksichtigt. So müssen  Workflowanpassungen gemacht werden und das opengever.trash modul muss umgebaut werden.

3.3 Zusätzlich wird es Probleme im UI geben. U.u. sieht ein Benutzer keine Vorlagen zur Auswahl obwohl unter "Vorlagen" jede Menge Vorlagen erfasst sind. Folgende Punkte werden bei der Umsetzung berücksichtigt.

- eine Dossiervorlage im Papierkorb kann unter "Dossier aus Vorlage" nicht ausgewählt werden (standard GEVER-Verhalten)
- eine Dossiervoralge im Papierkorb kann nicht als "erlaubte Dossiervorlage" in einer Ordnungsposition ausgewälht werden (standard GEVER-Verhalten)
- bereits erlaubte Dossiervorlagen in einer Ordnungsposition, welche zu einem späteren Zeitpunkt in den Papierkorb verschoben wurden, bleiben beim Bearbeiten der Ordnungsposition bestehen und müssen beim Speichern des Formulars nicht geändert werden. Wird jedoch nach neuen Vorlagen gesucht, kann diese nicht erneut ausgewählt werden. (standard GEVER-Verhalten)
- wird ein "Dossier aus Vorlage" erstellt gibt es verschiedene Varianten welche berücksichtig werden müssen:

![dossieraustemplate](https://cloud.githubusercontent.com/assets/557005/25421492/745a56ce-2a5d-11e7-9d23-8d4f64e76d90.png)

**Comment by elioschmutz** [comment]
Besprechung mit @phgross:

**Version 1 wird nicht umgesetzt**

Version 1 war auf Basis vom Papierkorb. Dossiers sollten in den Papierkorb verschoben werden können. Das Modul opengever.trash hätte hierbei eine zentrale Rolle gespielt. Es wurden verschiedene Probleme bzw. hohe Aufwände bei dieser Variante festgestellt:
- opengever.trash ist nicht für Dossiers gemacht und müsste grundsätzlich überarbeitet werden
- rekursives löschen von Dossiers müsste implementiert werden (ITrashed-interface)
- Papierkorb-Tab muss angepasst werden da dieses für Dokumente ausgelegt ist
- Dossiers haben keinen Workflow und können somit nicht wie Dokumente "workflowbasiert" gelöscht werden. Weitere Probleme wären somit im Papierkorb-Tab zu erwarten

**Version 2 ausgearbeitet mit @phgross:**
Die zweite Variante basiert auf dem aktivieren/deaktivieren von Dossiervorlagen wie dies bereits in  Ordnungspositionen umgesetzt ist. Dazu benötigt es weniger Anpassungen in anderen GEVER-Modulen v.a. im opengever.trash. Dies minimiert den Aufwand massiv. Auch die Probleme mit dem Papierkorb-Tab bleiben uns erspart. Zusätzlich wurde die "Dossier aus Vorlage"-Ansicht bei inaktiven Vorlagen gegenüber V1 stark vereinfacht.

- [ ] Eigener Workflow für Dossiervorlagen:
  - [ ] Berechtigungen einer inaktiven Vorlage gem abgeschlossenem Dossier
![workflow](https://cloud.githubusercontent.com/assets/557005/25439025/88b92d50-2a9b-11e7-80c8-7117cc4ace13.png)

- [ ] Auflistung von Dossiervorlagen:
    - [ ] neuer Statusfilter wird angezeigt: alle | aktiv
    - [ ] Standardmässig werden nur aktive Vorlagen angezeigt
    - [ ] neue Spalte in Auflistung: Status (zeigt den Workflow-Status an)

- [ ] Byline Dossiervorlagen
    - [ ] Status anzeigen gem. Dossiers

- [ ] Ordnungsposition
    - [ ] Feld Einschränkung: nur aktive Vorlagen dürfen ausgewählt werden können

- [ ] "Dossier aus Vorlage"-Ansicht:

![flowchartdiagram1](https://cloud.githubusercontent.com/assets/557005/25439822/d6debbd8-2a9d-11e7-889b-8f4f3b5b8880.png)

@phabegger Bitte bestätige das Konzept von **Version 2** wenn für dich alles i.O. ist.

**Comment by phgross** [comment]
@phabegger Was denkst du zu Variante 2) Aktivieren und deaktivieren von Dossiervorlagen, aber kein Löschen. Hast du Einwände?

**Comment by phabegger** [comment]
Aus meiner Sicht kann man auch das Löschen erlauben - das "Nicht-Löschen-Können" beschränkt sich auf alle "geschäftsrelevanten Daten", die sich in den Ordnungssystemen befinden. Im Bereich "Vorlagen" (sowie der persönlichen Ablage) darf das Löschen möglich sein bzw. ist u.U. sogar erwünscht.

Wenn man wirklich eine Unterscheidung zwischen Aktiv und Inaktiv machen möchte, dann muss trotzdem möglich sein, inaktive Dossiervorlagen zu löschen. 

Wäre das Löschen nicht relativ einfach zu implementieren? Oder drohen hier mögl. Sicherheitslücken?

**Comment by elioschmutz** [comment]
**Version 3: Direktes Löschen**

Die dritte Version soll das direkte Löschen von Dossiertemplates ermöglichen.

Folgende Aufgaben sind für die Umsetzung nötig:

- [ ] Workflowanpassungen
  - [ ] der Templateordner hat bereits einen eigenen Workflow welcher mit der `Löschen`-Berechtigung erweitert werden kann

- [ ] Actions anpassen
  - [ ] Löschen-Action für Objekte im Vorlagenornder aktivieren

- [ ] Back-Ref-Check
  - [ ] Referenzierte Objekte (z.B. in "erlaubte Dossiervorlagen") dürfen nicht gelöscht werden können

Diese Anpassung hat zur Folge, dass alle Inhalte im Vorlagenordner gelöscht werden können.
Der Papierkorb ist somit überflüssig und kann entfernt werden.

- [ ] Papierkorb
  - [ ] Papierkorb-Tab im Vorlagenordner entfernen
  - [ ] alle Papierkorbactions entfernen

=> Ich befürworte das Entfernen des Papierkorbes. Für den Benutzer gibt es dann im Vorlagen-Ordner einfach die Möglichkeit etwas zu erstellen oder zu löschen.

Soll diese Funktion weiterhin verfügbar sein gibt es folgendes zu beachten:

- Dokumente im Vorlagenordner sind vom gleichen Inhaltstyp wie die Dokumente im Ordnungssystem

Wir können somit das Löschen von Dokumenten nicht über den Workflow unterbinden.

Es gibt folgende Möglichkeiten um dieses Problem zu lösen:

- Placeful-Workflow für den Vorlagen-Ordner oder
- Eigener Dokument-Template Inhaltstyp (bevorzugt)

Hinweis: Ein eigener Dokument-Template-Typ ist sowieso zu empfehlen da wir so eine klare Trennung zwischen "OG-Dokumenten" und "Vorlagedokumente" erreichen können. Dies Typen unterscheiden sich sowohl vom Verwendungszweck wie auch vom Workflow.

**Comment by elioschmutz** [comment]
@phgross @phabegger oben findet ihr die Version 3, direktes Löschen

**Comment by phabegger** [comment]
Scheint mir alles sehr kompliziert zu sein... Welche der drei Varianten lässt sich am einfachsten umsetzen? 

Vielleicht hilft es, meinen "Use Case" zu beschreiben: Ich möchte bestimmte Dossiervorlagen unter Vorlagen sowie in Aktion "Dossier aus Vorlage" nicht mehr angezeigt erhalten, weil ich die Dossiervorlage nicht mehr benötige. Ob sie nun gelöscht, im Papierkorb oder aktiv/inaktiv gesetzt wird, ist nicht so wichtig, Hauptsache, sie wird mir nicht mehr angezeigt und sie kann nicht mehr verwendet werden (bei "Dossier aus Vorlage").

Welche der drei Variante würde aus eurer Sicht meinen UC am "schnellsten" lösen? Falls mit Workflow aktiv / inaktiv: Wäre dies nun so ein Anwendungsfall für LawGiver, @phgross?

**Comment by elioschmutz** [comment]
Die schnellste und einfachste Variante ist **Variante 3** mit entfernen des Papierkorbes.

In einem weiteren Schritt kann dann immer noch ein eigener Dokument-Template-Typ mit eigenem Workflow erstellt werden.

Auch für die Einheitlichkeit ist Variante 3 sehr gut. So steht für jeden Typ innerhalb des Template-Ordners die Löschen-Funktion zur Verfügung.

**Comment by phabegger** [comment]
Ok, dann schlage ich vor, dies so umzusetzen. Die Gefahr ist höchstens, dass man irrtümlich was löscht - es gibt ja aber vorher noch eine Warnung. Später könnten wir uns ja noch an den Workflow machen.
