### ISSUE TITLE
Add trash icon which removes the complete text in the note overlay.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2755]
![bildschirmfoto 2017-03-17 um 14 44 58](https://cloud.githubusercontent.com/assets/485755/24045715/505e89c2-0b20-11e7-9f66-6e2c8a9b6b09.png)

If CMD+A / CTRL+A to select the complete text would also be nice, but its not urgent.

**Comment by maethu** [comment]
CMD+A / CTRL+A works fine?? it's a textarea.

**Comment by phgross** [comment]
Ah you're right, but there is a bug with the focus. when opening the Overlay and presssing CMD + a it selects the complete Browser page, because the focus is not in the textarea.

**Comment by maethu** [comment]
currently... pending. Setting focus is necessary, we're not yet sure about the `del` button.

**Comment by maethu** [comment]
According to the discussion in basecamp...

<img width="881" alt="screen shot 2017-03-20 at 14 53 39" src="https://cloud.githubusercontent.com/assets/437933/24102678/07de2c48-0d7d-11e7-8944-b6c00126eacd.png">


We implement both.
