### ISSUE TITLE
EscapeDossier-Template title-help on display

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2759]
1)
![screen shot 2017-03-20 at 16 02 07](https://cloud.githubusercontent.com/assets/736583/24105899/a488a632-0d86-11e7-8e0c-3216c38c2b17.png)

2) 
![screen shot 2017-03-20 at 16 01 48](https://cloud.githubusercontent.com/assets/736583/24105900/a489fa28-0d86-11e7-9cf1-5435d4668deb.png)

(we already have an `escape_html` function)

**Comment by elioschmutz** [comment]
closed by #2763
