### ISSUE TITLE
Don't display Field "Neuer Eintrag" when creating dossiers from template

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2760]
The field appears in the add-form when creating a dossier from a template:

![screen shot 2017-03-20 at 16 17 26](https://cloud.githubusercontent.com/assets/736583/24107822/15d978de-0d8c-11e7-98b5-18cfb70d9579.png)

The field should not appear. Also, when "Schlagwortkatalog einschränken" is selected, this allows to bypass the restriction and new keywords can be added nevertheless in the add-form.

**Comment by maethu** [comment]
@deiferni Fixed with new ftw.keywordwidget release 1.1.4 https://github.com/4teamwork/kgs/commit/acd6e6ca77c5017d5165270381f0eb56c7d9f268

**Comment by deiferni** [comment]
thanks! 👍
