### ISSUE TITLE
Kommentarfunktion wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2767]
Die neue Kommentarfunktion scheint nicht korrekt zu funktionieren:

![bildschirmfoto 2017-03-21 um 08 58 58](https://cloud.githubusercontent.com/assets/557005/24137576/aa22ef9c-0e14-11e7-9d2c-5d070e27bcc9.png)

- [ ] Condition von "Edit" / "Create" spans müssen angepasst werden

**Comment by deiferni** [comment]
bei mir lokal scheints zu klappen ... wie kann ich das reproduzieren?

kannst du kurz verifizieren, dass du beim plonetheme.teamraum auf dem aktuellen stand bist, und dass alle upgrade-steps installiert sind?

**Comment by elioschmutz** [comment]
`plonetheme.teamraum` war nicht aktuell 👍  funktioniert nun alles wie gewünscht.
