### ISSUE TITLE
Federführend nicht mehr änderbar bei Dossiererstellung

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#2802]
Alice ist sich nicht sicher ob sie, oder Bob Federführend ist. In der Maske "Dossier hinzufügen" stellt sie zuerst sich, dann B, dann wieder sich ein. Dabei ergibt sich der Fehler wie im Screenshot. Zum Schluss sind beide Radio-Buttons aktiv. Das System übernimmt A als Federführend.

Diesen Fehler konnte Herr Leyvraz im lab.ogg.ch reproduzieren.

Ablauf
Standard A
Klick auf B
Klick auf A -- Beide ausgewählt.

Nur durch erneutes suchen des Namens A wieder einstellbar.

![federfuhrend zwei radiobuttons](https://cloud.githubusercontent.com/assets/11310148/24539830/9f39588a-15f0-11e7-8266-bbd6c3715563.png)

**Comment by jounsiboss** [comment]
Bitte Kommentar im Ticket hinterlegen wenn gefixt, Danke.

https://extranet.4teamwork.ch/support/0282-kunde-stadt-nidau/0282-tracker-support-stadt-nidau/36

**Comment by elioschmutz** [comment]
Fix in https://git.4teamwork.ch/opengever/plone.formwidget.autocomplete/merge_requests/5/

**Comment by phgross** [comment]
@elioschmutz Mergerequest is merded, please make a PR for adding the `plone.formwidget.autocomplete` to the `development-packages` in the sources.cfg

**Comment by elioschmutz** [comment]
I made a new release: 1.2.2.post20170412 and pinned it in kgs/develop.cfg 👍
