### ISSUE TITLE
The tooltip has JS performance issues with unexpected AJAX returns

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#2825]
When accessing a tooltip view of a document, the javascript throws a hissy fit if something unexpected, like the login prompt, is returned instead.

```at XMLHttpRequest.d (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (eval at <anonymous> (++resource++plone.app.jquery.js:2))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))))), <anonymous>:4:18318)```

This trashes the CPU enough to grind my development machine down to a halt.

**Comment by bierik** [comment]
reproduction steps:

1) open a document proxy tabbedview
2) open a separate tab and log out there
3) hover the tooltip open on the first tab

**Comment by bierik** [comment]
Currently it's not possible to track a redirect -> http://stackoverflow.com/questions/282429/returning-redirect-as-response-to-xhr-request/2573589#2573589

We're getting a 200 for the rails portal anyway.

So better approach would be to register a publisher event and detect if the request is an XHR-Request. Additionally if the user is not logged in zope could raise an unauthorized.

**Comment by phgross** [comment]
@bierik Wie ist der Stand hier?

**Comment by bierik** [comment]
@phgross Wir sollten das noch zusammen anschauen

**Comment by phgross** [comment]
@bierik Bitte überprüfe wie das `ftw.tabbedview` "gelöst" wurde.
