### ISSUE TITLE
Löschjournal bei Aussonderung: Gleiche Schriftart wie bei Dossierübersicht

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2827]
Scheint im Moment noch Default-LaTeX-Font zu sein, sollte gleich sein wie bei übrigen generierten PDF-Dokumenten aus LaTeX (normalerweise Arial).

**Comment by phgross** [comment]
@phabegger Wo hast du das festgestellt? Auf dem SG Testsystem wird das Löschprotokoll korrekt mit Wappen und auch dem Arial Font gerendert.

<img width="668" alt="bildschirmfoto 2017-04-06 um 16 35 21" src="https://cloud.githubusercontent.com/assets/485755/24759838/0e89ea6a-1ae7-11e7-93f5-0c7d8d823cea.png">

**Comment by phgross** [comment]
Das Löschprotokoll wurde bereits abgenommen, ich schliesse diesen Issue.
