### ISSUE TITLE
Lange Dokumenttitel ragen im Dossier über den "Rand" hinaus

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#2871]
Fortsetzung von: https://github.com/4teamwork/plonetheme.teamraum/pull/530

Der Fehler besteht weiterhin im IE11.

- [x] Lange Dokumenttitel müssen auch im IE11 korrekt angezeigt werden.

Basecamp: https://basecamp.com/2768704/projects/12554551/todos/300700191

**Comment by elioschmutz** [comment]
PR: https://github.com/4teamwork/plonetheme.teamraum/pull/546

**Comment by phgross** [comment]
Solved via https://github.com/4teamwork/plonetheme.teamraum/pull/546
