### ISSUE TITLE
Inaktive Ordnungspositionen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2875]
Es wäre praktisch wenn inaktive Ordnungspositionen ausgeblendet oder zumindest anders markiert (graue Schriftfarbe) wären in der Baumdarstellung.

**Comment by phgross** [comment]
@bierik Bitte Vorschlag Screenshot erarbeiten. Ausblenden ist aber keine Option.

Zusätzlich könnten Rubriken anders markiert werden als restliche Ordnungspositionen.

**Comment by bierik** [comment]
<img width="315" alt="screen shot 2017-05-18 at 16 03 43" src="https://cloud.githubusercontent.com/assets/1637820/26206130/3ed0c680-3be4-11e7-9149-ec26365e0a82.png">
<img width="312" alt="screen shot 2017-05-18 at 16 07 04" src="https://cloud.githubusercontent.com/assets/1637820/26206133/3ed80076-3be4-11e7-9469-f864560d59c0.png">
<img width="307" alt="screen shot 2017-05-18 at 16 04 14" src="https://cloud.githubusercontent.com/assets/1637820/26206135/3eda09d4-3be4-11e7-93c1-bbbe121e13ae.png">
<img width="300" alt="screen shot 2017-05-18 at 16 06 46" src="https://cloud.githubusercontent.com/assets/1637820/26206132/3ed7dc54-3be4-11e7-89af-7ae38692a7cc.png">
<img width="305" alt="screen shot 2017-05-18 at 16 08 00" src="https://cloud.githubusercontent.com/assets/1637820/26206134/3ed96934-3be4-11e7-819d-f3da642a86c0.png">
<img width="305" alt="screen shot 2017-05-18 at 16 08 16" src="https://cloud.githubusercontent.com/assets/1637820/26206131/3ed78c9a-3be4-11e7-9ae1-61697a383776.png">

**Comment by phgross** [comment]
- Die Unterscheidung mit Fett / normal finde ich sehr gut.
- Variante 4 gefällt mir persönlich am Besten, schlicht und selbsterklärend.

@phabegger was denkst du  ?

**Comment by phabegger** [comment]
Auch Screenshot Nr. 6. Allerdings bin ich nicht sicher mit dem Fett - es wirkt nun so, als sei eine bestimmte OP wichtiger als andere. Ich würde Fett weglassen. Kannst Du hierzu auch noch ein Beispiel machen? Und noch eines, wo alle Rubriken Fett sind? (ist dann wohl zu "fett"... :smirk:)

**Comment by bierik** [comment]
Hier das Beispiel mit allen Leafnodes fett:
Sieht aus Sicht von mir und @phgross nicht gut aus
<img width="343" alt="screen shot 2017-06-07 at 15 25 44" src="https://user-images.githubusercontent.com/1637820/26880673-7aff5156-4b95-11e7-9ab1-21ab16bceec9.png">

@phabegger Umsetzung Screenshot Nr.6 ohne fett ja oder nein

**Comment by phabegger** [comment]
Siehe Diskussion im Feedback-Forum, https://feedback.onegovgever.ch/t/optimierung-darstellung-ordnungssystem/566

**Comment by bierik** [comment]
Ich bin sehr dankbar für den Beitrag von `jeki`.
Ich bin ganz seiner Meinung. Warum sollten die Benutzer die Ordnungspositionen inaktiv setzen? Werden diese nicht mehr gebraucht oder sind sie einfach weniger wichtig?
Ich glaube @phabegger hat mal erwähnt, dass viele Benutzer sowieso nur mit den Favoriten arbeiten, da der ganze Baum ab einer gewissen Grösse unübersichtlich wird.

Vielleicht wollen die Benutzer die Ordnungspositionen auch nur auf eine Art archivieren. Sie werden nicht mehr gebraucht aber löschen kommt natürlich auch nicht in frage. Somit könnte man eine Art Ordungspositionen-Friedhof machen.

So kann der Benutzer im aktiven Baum die Ordnungspositionen archivieren und allenfalls aus dem Archiv wiederbeleben.

**Comment by bierik** [comment]
@phabegger ping

**Comment by phabegger** [comment]
Siehe Diskussion im Feedback-Forum. Fett kommt allgemein nicht gut an, daher wohl ganz weglassen. Inaktive ausgrauen, sie dürfen nicht ausgelassen werden.
