### ISSUE TITLE
UX improvements for OC interactions

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#2876]
It is not feasible to display a splash screen OC-side when most of the interactions take less than a second.

Currently we have no way to do a callback from OC back to JS so we'd have to fake this a bit.

Ideas include alert boxes and/or button disables and/or file action button pressdown graphics and/or replacing the file action icon with a spinner for a couple of seconds.

1. File action buttons (document overview, bumblebee overlay, document tooltip)
2. Multiattach (dossier documents proxy)

@buchi has good ideas for this, so do have a discussion with him when approaching this.

**Comment by bierik** [comment]
We decided to display a spinner inside the button when the user clicked on it. Through an endpoint the current document status will be polled because we have no direct callback from the office connector. See https://github.com/4teamwork/opengever.core/issues/2888 for the endpoint specification.
