### ISSUE TITLE
Endpoint for document to get the current status.

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#2888]
We need an endpoint on the document to get the current status. We have to know if the document is checked out by a user or not. In order to improve the UX (https://github.com/4teamwork/opengever.core/issues/2876) this endpoint is used for polling the current document status.
The best would be to have a JSON-Response with just the boolean. `true` if the document is checked in and otherwise `false`.

**Comment by Rotonen** [comment]
I'll also put at least the document title and/or URL there to make it more obvious what one is dealing with.
