### ISSUE TITLE
Bumblebee overlay background does not scale when vertically space constrained

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#2893]
See screenshot:

![2017-05-01_bumblebee_overlay](https://cloud.githubusercontent.com/assets/935317/25579480/8afdfa9c-2e78-11e7-984d-a37a6b7f3093.png)

**Comment by bierik** [comment]
This will be fixed through https://github.com/4teamwork/opengever.core/pull/2847
