### ISSUE TITLE
Disable obsolete checkout action.

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#2905]
The obsolete checkout action in the header section should no longer be activated.
<img width="960" alt="screen shot 2017-05-03 at 14 22 50" src="https://cloud.githubusercontent.com/assets/1637820/25660373/35aa5c58-300c-11e7-9a28-9afecbc639b1.png">

**Comment by phgross** [comment]
Currently the `Auschecken / Bearbeiten` FTI action, does not respect the OfficeConnector feature flag.

In my opinion the doubled action, the `Auschecken/Bearbeiten` is already part of the document_actions, is not necessary. I would remove the action from the FTI action. 

Besides that i would also move the `wiederrufen` action from the current position to the document-actions
<img width="872" alt="bildschirmfoto_2017-05-08_um_19_43_30" src="https://cloud.githubusercontent.com/assets/485755/25817169/c784bcb8-3426-11e7-90c5-02580e6e6bfa.png">

@lukasgraf @deiferni what do you think ... ?

**Comment by phgross** [comment]
Todos: 
 - [] Remove the `Auschecken/Bearbeiten` portal_type action (opengever.document.document.xml) 
 - [] Remove the `Widerrufen` portal_type action (opengever.document.document.xml) 
 - [] Add the widerrufen document action as shown in the image above (the action should only be visible when a cancel is possible)
