### ISSUE TITLE
"-" char is not displayed correctly in search results

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/opengever.core#2921]
When the search lists a result containing the "-" char in its title, the char is displayed without spacing to the next character. In most cases, this moves it right into the next letter.

Example:
<img width="388" alt="screen shot 2017-05-11 at 15 13 54" src="https://cloud.githubusercontent.com/assets/16755391/25951051/d45a521c-365c-11e7-8763-8913ed04d620.png">

**Comment by phgross** [comment]
Kann ich im neuesten Release nicht mehr reproduzieren.

![bildschirmfoto 2017-06-20 um 09 13 17](https://user-images.githubusercontent.com/485755/27320975-c4a16e86-5598-11e7-9f98-04d30a216d41.png)

**Comment by raphael-s** [comment]
Ich kann dies weiterhin reproduzieren, z.B. auf dev.onegovgever.ch:

<img width="1440" alt="screen shot 2017-06-23 at 16 55 34" src="https://user-images.githubusercontent.com/16755391/27487780-f6d07980-5834-11e7-93ee-b6bd35dfecc8.png">

**Comment by phgross** [comment]
@raphael-s Danke fürs erneute Abklären! 👍  @tarnap kannst du dir das genauer ansehen.

**Comment by tarnap** [comment]
The text is split into spans. Separated by orphan text elements.
Since the spans have a `{ margin-left: -3px; }` the spacing between the text elements and the spans is reduced.

![sali-sali-sali](https://user-images.githubusercontent.com/194114/27576280-c9b9cf42-5b1c-11e7-879e-167496c0c908.png)

**Comment by tarnap** [comment]
@phgross do we fix this with CSS (by adding a style which removes the margin for these elements) or shall I try to find out, why the text is split into different spans?

**Comment by phgross** [comment]
@tarnap i would fix the CSS, but doublecheck why we added the `margin-left: -3px;` statement.

**Comment by tarnap** [comment]
This is the commit responsible for the `margin-left: -3px;`
https://github.com/4teamwork/plonetheme.teamraum/commit/b3b16ef8edc545884eb831207b8f802260736ea2

**Comment by tarnap** [comment]
This quickfix solves the issue: https://github.com/4teamwork/plonetheme.teamraum/commit/410e8f4a8c6964204de20d49dca5913d21874422

Works with IE as well and there seems to be no BUG:
<img width="1920" alt="screen shot 2017-06-27 at 10 29 19" src="https://user-images.githubusercontent.com/194114/27578303-083a01e0-5b24-11e7-915e-6ff329808fb2.png">

@phgross I'll create a new file, what name do I pick? search_list.scss

**Comment by tarnap** [comment]
Fun fact: With `margin-left: initial;` the spans disappear!

![funny](https://user-images.githubusercontent.com/194114/27578576-d0e6b9bc-5b24-11e7-8704-bfac11ddadd1.png)

**Comment by tarnap** [comment]
@phgross This is a funny behaviour, sometimes the spans appear, sometimes they don't:

![funny2](https://user-images.githubusercontent.com/194114/27579025-5e1c2c8a-5b26-11e7-83f9-7d15401b7e6c.gif)
