### ISSUE TITLE
Hamburger-Menü zum Aus-/Einblenden des Ordnungssystems einbauen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2957]
Siehe Vorschlag gemäss https://feedback.onegovgever.ch/t/ordnungssystem-mit-hamburger-menue-ausblenden/524/5

Wichtig ist, dass das Ordnungssystem standardmässig eingeblendet ist und vom Benutzer bewusst ausgeblendet werden kann. 

Der so frei werdende Raum soll dann vom Hauptbereich (Dossieransicht) etc. in der ganzen Breite genutzt werden. Zudem sollte sich die benötigte Lade- und Anzeigezeit im Browser für eine Seite ohne eingeblendetes Ordnungssystem nochmals verbessern.

**Comment by bierik** [comment]
@phgross Variante 1
<img width="1920" alt="screen shot 2017-05-24 at 10 10 04" src="https://cloud.githubusercontent.com/assets/1637820/26393184/54baa3ec-4069-11e7-987d-e65a7007f1e9.png">
<img width="1918" alt="screen shot 2017-05-24 at 10 06 46" src="https://cloud.githubusercontent.com/assets/1637820/26393183/54b7ab42-4069-11e7-84f4-e69f3d5b9bd9.png">

**Comment by phgross** [comment]
Die Diskussion im Feedback Forum wurde geführt, man bevorzugt eine allgemeine Lösung für alle Bereiche. 

@bbuehlmann hast du noch Feedback zum Vorschlag von Kevin?

**Comment by bierik** [comment]
Im Feedbackforum wurde nach einer generischen Lösung gesucht. D.h. es soll nicht nur das Ordnungssystem ausgeklappt werden können, sondern auch andere Sidenavigationen wie z.B. Vorlagen. Zu dem Zweck habe ich eine weitere Variante erarbeitet. Diese habe ich mit @phgross diskutiert.
In dieser Variante geht es darum den Pfeil und die zugeklappte Sidenavigation besser ersichtlich zu machen. Ausserdem müssen die anderen Navigationen analog zum Ordnungssystem angepasst werden. D.h. bei der Sidenavigation mit den Vorlagen muss auch der Portletansatz verfolgt werden damit die Sidenavigation konsistent daher kommt. Anbei mein Vorschlag wie das ganze Aussehen könne:
<img width="1315" alt="ordnungssystem_ausgeklappt" src="https://cloud.githubusercontent.com/assets/1637820/26682992/a1f04660-46e2-11e7-8009-3d38ff1fba35.png">
<img width="1315" alt="ordnungssystem_eingeklappt" src="https://cloud.githubusercontent.com/assets/1637820/26682993/a1f5e6e2-46e2-11e7-92c2-21965052161f.png">

**Comment by bbuehlmann** [comment]
Sieht gut aus! :+1:

**Comment by phabegger** [comment]
Danke, @bierik - ist das nun die generische Lösung oder spezifisch fürs Ein- und Ausblenden des OS? Falls generisch, müsste der Tooltipp "Ordnungssystem ausklappen" je nach Situation anders heissen, z.B. "Navigation ausklappen". Ist dies richtig?

- Der graue linke Balken stört mich optisch etwas - ich frage mich, ob es nicht besser wäre, dieses Bedienelement in die Hauptnavigation oben zu integrieren.

- Das Ein- und Aufklappen "linke Spalte" sollte sich eigentlich gleich verhalten wie in der Overlay-Ansicht von Bumblebee mit den Bedienelementen in der rechten Spalte. Dort kann ich ja auch die Spalte wegen mehr oder weniger Platz ein- und ausblenden. Allerdings verwenden wir dort im Moment das Symbol "i".

**Comment by phgross** [comment]
Folgende Dinge stören mich bei der zweiten Variante:
 - Das Aktionen Menü - horizontaler Bereich (Bearbeiten/Aktionen) sieht nun auch anders aus und das Styling passt nicht mehr zu den styles der Tabs etc.
 - Der grau linke Balken stört mich optisch, da er relativ prominent ist.

Von den zwei Varianten bevorzuge ich die 1. Variante, da es sich besser ins bestehende Design integriert ... Aber vielleicht findet man noch eine passendere Lösung ...

**Comment by bierik** [comment]
@phgross @phabegger 
Es ist nur ein Mockup. Ich weiss, dass die Animation nicht perfekt ist 😉 
![gever-revealing-ordnungssystem](https://user-images.githubusercontent.com/1637820/27175828-b508ca4a-51c0-11e7-9ceb-536e53df0071.gif)
<img width="1178" alt="screen shot 2017-06-15 at 11 50 39" src="https://user-images.githubusercontent.com/1637820/27175821-afe235ba-51c0-11e7-9cc3-7cc3ebbfcebb.png">
<img width="1177" alt="screen shot 2017-06-15 at 11 50 28" src="https://user-images.githubusercontent.com/1637820/27175820-afdf5bce-51c0-11e7-83c5-2f471aaed5a2.png">

**Comment by phabegger** [comment]
Animation ist super!!! Mich stört jedoch, dass das Hamburger-Menü im eingeklappten Zustand im linken Rand Platz weg nimmt - in der Menüleiste fände ich es besser untergebracht.

Ausserdem soll ja das Hamburger-Menü die gesamte linke Spalte aus- und einblenden - ggw. ist es im OS-Portlet untergebracht. Wie funktioniert es dann im Bereich Eingangskorb, wo ich in der linken Spalte kein OS habe???

**Comment by bierik** [comment]
@phabegger: @phgross und ich meinen, dass man nun das `portlet` im Eingangskorb gleich aussehen lassen kann wie das `portlet` im Ordnungssystem. Somit ist es auf jeder Seite konsistent und der Benutzer erkennt das pattern wieder um die linke Spalte auszublenden.
Das könnte dann etwa so aussehen:
<img width="1118" alt="screen shot 2017-06-16 at 08 59 36" src="https://user-images.githubusercontent.com/1637820/27215518-f01ffa98-5271-11e7-9b8b-78e50b5d06b1.png">
Und analog bei den Vorlagen:
<img width="1164" alt="screen shot 2017-06-16 at 09 03 02" src="https://user-images.githubusercontent.com/1637820/27215610-5bf44882-5272-11e7-87e0-9aa0468332dd.png">

@phgross und ich waren der Meinung, dass es für den Benutzer verwirrend ist, wenn das Hamburgermenu in der Navigation erscheint. So hat man das Gefühl, dass die Navigation weggeklappt wird und nicht der Inhalt im Portlet.

**Comment by phgross** [comment]
Wir warten hier zu. Wird mit den allgemeinen Frontend-Diskussionen aufgenommen.

**Comment by deiferni** [comment]
@phabegger möchte das wieder auftun.

**Comment by deiferni** [comment]
Mit @phabegger abgesprochen, kann geschlossen werden.
