### ISSUE TITLE
Keine sprechende URLs bei Ordnungspositionen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2960]
Zurzeit werden für Ordnungspositionen sprechende URLs verwendet. Da Ordnungspositionen unbenannt werden können, die ID aber nicht geändert wird, führt das immer wieder zu Problemen. Deshalb stellt sich die Frage ob man nicht grundsätzlich auf Ordnungspositionen verzichten möchte.

**Comment by phabegger** [comment]
Dieser Punkt kommt in konkreten Projekten immer wieder auf. Aus folgenden Gründen: 

- Keine "information disclosure" über sprechende URLs
- Beim Umbenennen von Ordnungspositionstiteln wird die ID nicht angepasst, entspricht also nicht mehr dem Titel
- Bei mehrsprachigen Ordnungssystemen müsste die ID je nach Sprache anders aussehen

Deshalb soll die ID die (relative) Ordnungspositionsnummer neu darstellen.

Was muss bei einer derartigen Anpassung alles berücksichtigt werden?
- Umbenennen / Verschieben von bestehenden OPs
- Import von Ordnungssystemen ab Excel-Vorlage
- Anpassen von bestehenden Nummern über den "Präfix-Manager"?
- Migration von OS in bestehenden Systemen?

@phgross Bitte weiter abklären.

**Comment by phgross** [comment]
Wird mit `OGIP 31 Vereinheitlichung der ID von Ordnungspositionen` behandelt. Ich schliesse diesen Issue.
