### ISSUE TITLE
Fehlende deutsche Übersetzungen in Dossier Übersicht

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#2965]
![bildschirmfoto_2017-05-18_um_15_45_59](https://cloud.githubusercontent.com/assets/485755/26205138/2697440c-3be1-11e7-9f76-2ac88ef012d1.png)

Vermutete Ursache: chameleon

**Comment by Rotonen** [comment]
My initial suspicion is of this being a chameleon slot redefinition issue again.

**Comment by deiferni** [comment]
closed by https://github.com/4teamwork/opengever.core/pull/2970
