### ISSUE TITLE
remove flash fallback for quickupload

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2971]
The quickupload flash fallback ist still active, even though flash upload is not enabled in ourcollective.quickuploads control panel. it seems that the swf file gets embedded unconditionally by a piece of javascript (https://github.com/collective/collective.quickupload/blob/master/collective/quickupload/browser/static/swfobject.js). It seems that having flash enabled leads to confusing messages in firefox: https://feedback.onegovgever.ch/t/adobe-flash-plugin-firefox-wer-kennt-diese-meldung-umfrage/541/5.

**Comment by maethu** [comment]
Flash wird von Addons geladen :-)

- 1. collective.js.extjs --> wird mit https://github.com/4teamwork/collective.js.extjs/pull/3 entfernt
- 2. collective.quickupload --> Wird in #3033 entfernt.
