### ISSUE TITLE
Vorschau von E-Mails hat Darstellungsfehler (Umlaute)

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2987]
Konkretes Beispiel: 
E-Mail in Dossier https://gever.4teamwork.ch/ordnungssystem/0/322/2/dossier-302/dossier-1840

Das E-Mail wurde direkt über OGG versendet (Aktion "E-Mail versenden"). Umlaute werden nicht korrekt dargestellt.

**Comment by siegy22** [comment]
@phabegger siehe https://github.com/4teamwork/bumblebee/issues/35#issuecomment-304590336

**Comment by siegy22** [comment]
Dieser Issue wird weiter auf https://github.com/4teamwork/bumblebee/issues/35 getrackt. Denke nicht, dass es Sinn macht auf dem opengever.core repo einen Issue zu haben, der nur Bumblebee selbst betrifft.
