### ISSUE TITLE
Vorschau von ausgecheckten Dokumenten in der Detail-Ansicht wird nicht aktualisiert

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2992]
Dies ist verwirrend: 

1. Ich klicke bei einem Dokument auf `Auschecken/Bearbeiten` und bearbeite das Dokument in Word.

2. Ich schliesse Word, wodurch OC das Dokument wieder in OGG speichert. Ich checke bewusst nicht ein, weil ich die Bearbeitung des Dokuments später noch fortsetzen möchte (am gleichen Tag, am nächsten Morgen).

3. Gehe ich nun wieder auf das ausgecheckte Dokument, um daran weiter zu arbeiten, zeigt mir die Vorschau eine veraltete Version des Dokuments an. Dies verunsichert mich sehr, da ich am Dokument grössere Veränderungen vorgenommen habe und die Vorschau anders aussehen sollte. Hat etwas das Zurückspeichern mit OC nicht funktioniert? 😬 

Gleiche Rückmeldungen haben ich von @bbuehlmann oder diversen Kunden erhalten.

Vorschlag Varianten:

1. Bei jedem Speichern eine neue Vorschau rechnen. So wird es in teamraum gelöst. Könnte allerdings zu einem Problem bei Installationen werden, die noch External Editor verwenden (der speichert regelmässig alle paar Sekunden).

2. Vorschau bei ausgecheckten Dokumenten ganz ausblenden und Hinweis anbringen: "Vorschau des Dokuments ist im Moment nicht verfügbar, da das Dokument zur Bearbeitung ausgecheckt wurde."

3. Vorschau bei ausgecheckten Dokumenten so belassen, allerdings zusätzlich den Hinweis anbringen: "Die angezeigte Vorschau entspricht der letzten eingecheckten Version des Dokuments und ist möglicherweise nicht aktuell." (o.ä.).

**Comment by phgross** [comment]
Variante 1) Ist problematisch bzw. kompliziert. Da Änderungen am Dokument erst nach dem Checkin für alle sichtbar sein dürfen, müsste sichergestellt werden dass die aktualisierte Version nur für den Benutzer welcher am Dokument arbeitet sichtbar ist.

**Comment by phabegger** [comment]
Hierzu eine Verständnisfrage: Wird für andere Benutzer nicht jeweils die zuletzt eingecheckte Version (bzw. deren Vorschau) angezeigt? Die neuste gespeicherte Dokumentversion besitzt ja dann einen anderen Hashwert, oder nicht?

**Comment by deiferni** [comment]
@phabegger aktueller Stand: Im Moment können wir nur einen Hashwert pro Dokument speichern. Solange das Dokument ausgecheckt ist, wird dieser im Moment nie aktualisiert, darum sieht man die Vorschau der letzten Version.

Ich finde Vorschlag 1) ist aus Usability-Gründen erstrebenswert, die anderen Varianten sind irgendwie unbefriedigend insbesondere für den Bearbeiter des Dokumentes. Wir müssen aber beachten was @phgross schreibt, die Vorschau des das Dokumentes darf für die anderen Benutzer erst aktualisiert werden, sobald das Dokument vom Bearbeiter eingecheckt wird. 

Vorschlag: Dem Bearbeiter eine eigenes Vorschaubild darstellen, diese Vorschau wird bei jedem Speichern neu gerechnet. Den anderen Benutzern wie jetzt schon die Vorschau der zuletzt eingecheckten Version darstellen. Ist aber technisch etwas aufwändiger weil das bisher so kein Use-Case von bumblebee und  insbesondere `ftw.bumblebee` ist. Sollen wir das abklären?

Alternative: Variante 2, dem Bearbeiter keine Vorschau darstellen.

**Comment by deiferni** [comment]
Ist mittlerweile möglich.
