### ISSUE TITLE
Responsive Design: Navigationspunkte "Übersicht" und "Meine Ablage" fehlen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2993]
![bildschirmfoto 2017-05-31 um 19 31 34](https://cloud.githubusercontent.com/assets/485600/26645307/dcc04a66-4637-11e7-8296-13f7c1dfa493.png)

In der Navigation erscheinen "Übersicht" und "Meine Ablage" nicht.

Getestet unter https://dev.onegovgever.ch/fd#mydossiers

**Comment by phgross** [comment]
Siehe auch #410

**Comment by phgross** [comment]
Ursache für die fehlenden Aktionen in der mobilen Ansicht, ist das `ftw.mobilenavigation` die Navigation selbst anhand containment zusammenbaut. Für für das Toplevel müsste aber wohl eher die `portal_tabs` verwendet werden. So wie in der Haupt-Navigation in der normalen Ansicht auch.

@maethu `ftw.mobilenavigation` wird auch bei diversen anderen Projekten eingesetzt, kannst du abschätzen ob man eine entsprechende Anpassung im ftw.mobilenavigation machen könnte oder das zu viele Probleme mit sich bringt ?

**Comment by maethu** [comment]
@phgross Wir benutzen dieses Modul nur nich selten. In der Regel bauen wir ftw.mobile ein. 

z.B bei bern.ch war der Aufwand ca. 3 PT.

**Comment by phgross** [comment]
@maethu `ftw.mobile` ist zurzeit keine Option da dies `ftw.theming` benötigt. Ich schaue mal ob eine Anpassung von `ftw.mobilenavigation` möglich wäre.

**Comment by phgross** [comment]
@maethu könnest du kurz überprüfen ob man dem ftw.mobilenavigation beibringen könnte, dass es auf oberster Stufe die `portal_tabs` anstatt die enthaltenen Objekte für die mobile Navigation verwendet?

**Comment by maethu** [comment]
@phgross Ja kann man --> Man müsste diese Liste erweitern. https://github.com/4teamwork/ftw.mobilenavigation/blob/master/ftw/mobilenavigation/browser/navigation.py#L72

Ich kenne aber das Ding auch nicht mehr so gut, ist ja ururururalt.

**Comment by maethu** [comment]
Vorschlag:

"Übersicht" und "Meine Ablage" könnte man auch separate Aktion im Mobiel-Menu anzeigen.

**Comment by phgross** [comment]
@maethu ich würde zurzeit eine simple Anpassung im `ftw.mobilenavigation` bevorzugen. Das Aussehen und UI  auf mobile Geräten werden wir zu einem späteren Zeitpunkt wohl grundlegender überarbeiten.

**Comment by maethu** [comment]
@phgross 
Gelöst in 
https://github.com/4teamwork/ftw.mobilenavigation/pull/45
