### ISSUE TITLE
Beim Ausdrucken mit PDF.js wird im Edge nicht die ganze Seite ausgedruckt

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2994]
Scheint ein IE-Problem zu sein.

**Comment by phabegger** [comment]
Scheint ein Problem des Drucken-Knopfs von PDF.js zu sein, und zwar im IE.

**Comment by bierik** [comment]
@phabegger Ich kann das Problem weder auf dem IE11 noch auf dem Edge reproduzieren.

- PDF in der Vorschau geöffnet
- Auf Drucken-Knopf von PDF.js geklick
- Im Edge in der Druckvorschau sieht alles gut aus
- Im IE11 habe ich mit `Druck nach PDF` ein PDF generiert, da die Druckvorschau dort nicht verfügbar ist -> dieses PDF hat auch gut ausgesehen

Kannst du mir noch konkret sagen welches PDF bei St.Gallen dieses Problem produziert

**Comment by phgross** [comment]
Wir benötigen eine Beispiel Dokument. Su klärt zurzeit ab, via Support Issue.

**Comment by phgross** [comment]
@bierik ich konnte das Problem im IE mit folgendem Dokument https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-16/document-33?searchterm=word#overview reproduzieren, kannst du dir das nächste Woche genauer anschauen?

**Comment by phgross** [comment]
@bierik was ist hier der Stand? Konntest du die geplante Bumblebee Anpassung nun testen. Wäre dir dankbar um eine Status-Update, thx

**Comment by bierik** [comment]
@phgross @siegy22 Ich habe einen Fork des pdfjs_viewers von yves gemacht -> https://github.com/4teamwork/pdfjs_viewer-rails und versucht pdf.js auf den neusten Release zu updaten.
Gemäss changelog von pdf.js werden diverse print issues spezifisch für IE gefixt. Deshalb denke ich, dass ein update hier sehr von Nutzen ist.
Mit dem neusten Release wird aber auch der Buildprozess von pdf.js mit webpack gemacht, was das Einbinden der javascript library in die rails app sehr viel schwieriger gestaltet.

pdf.js verwendet webworker. So wie momentan pdf.js in die rails app integriert ist können diese webworker gar nicht funktionieren und ich schlage vor, dass hier ein anderer Ansatz zum Einbinden der javascript library verfolgt werden sollte.

Bis anhin wurde das `pdf.combined.js` in die Railsapp eingebunden. Laut der doku von pdfjs funktionieren mit diesem Ansatz die webworker aber nicht. Auch wurden einige Issues reportet, in denen der Buildprozess mit Webpack fehler aufweist -> https://github.com/mozilla/pdf.js/issues/8057
https://github.com/mozilla/pdf.js/pull/8058

Ich würde vorschlagen ein javascript package zu machen, welches den webworker und das pdf sauber laden kann wie es hier auch dokumentiert ist -> https://gist.github.com/fcingolani/3300351

**Comment by bierik** [comment]
Ich habe mir mit @siegy22 noch einmal 2 Stunden Zeit genommen.
Letztendlich haben wir eine Lösung gefunden und den PR beim pdfjs viewer repo erstellt, welcher die pdfjs version updated und die Druck-Issues löst.
Wir warten noch auf sennys Rückmeldung.

-> https://github.com/senny/pdfjs_viewer-rails/pull/34

**Comment by bierik** [comment]
Wir haben das repo forked https://github.com/4teamwork/pdfjs_viewer-rails da senny noch keine Zeit hatte den PR anzuschauen. Das update wurde mit https://github.com/4teamwork/pdfjs_viewer-rails/pull/2 gemacht und das Drucken auf dem IE funktioniert wieder.

**Comment by siegy22** [comment]
Ich habe nun den `pdfjs_viewer-rails` neu released und beim Bumblebee rauf gepinnt, dann aufs Staging deployt. (lab.onegovgever.ch's bumblebee)

Der Bug wurde von PDF.js gefixt, hier die Dokumente im Vergleich:

Mit dem Dokument von @phgross (dev gever):
[alte_pdfjs_version.pdf](https://github.com/4teamwork/opengever.core/files/1292439/alte_pdfjs_version.pdf)

Gleiches Dokument auf lab gever:
[neue_pdfjs_version.pdf](https://github.com/4teamwork/opengever.core/files/1292438/neue_pdfjs_version.pdf)

Ich werde wahrscheinlich heute Abend den produktiven Bumblebee zusätzlich updaten, damit alle (vorallem SaaS Kunden) diesen Patch erhalten.

@phabegger Wer hat das gemeldet? Müsste man evtl. noch eine konkrete Bumblebee on-site Installation updaten?

**Comment by phabegger** [comment]
@siegy22 Dies wurde von SG gemeldet, ist aber inzwischen dort korrigiert => @bierik hat das korrigiert.

**Comment by siegy22** [comment]
@phabegger es wurde zwar von @bierik korrigiert, jedoch noch nicht im Bumblebee master eingebunden und deployt. (Habe mich hier gefragt warum der Issue bereits geschlossen ist).
