### ISSUE TITLE
Anderes Mail-Icon in Dokumentauflistungen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#2995]
In Dokumentauflistungen innerhalb von Dossiers fallen Mails durch ihre grauen Icons optisch stark ab - alle übrigen Dokumente besitzen dort ein farbiges Icon:

![bildschirmfoto 2017-06-01 um 07 49 33](https://cloud.githubusercontent.com/assets/485600/26666186/e3ef0c5c-469e-11e7-83c1-1ca1f45a020b.png)

(siehe https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-16#documents-proxy) 

Bitte Vorschlag für ein anderes Icon für Mail machen, das man in Auflistungen anzeigen könnte.

**Comment by bierik** [comment]
@phabegger Ich habe hier einen ersten Vorschlag. Ich habe versucht das neue E-Mail icon in die bestehende Icon-Familie aufzunehmen und mich dabei am Outlook Icon orientiert, darum die Farbe Gelb.
Wurde bereits mit @phgross besprochen. Er ist damit einverstanden.

<img width="1327" alt="screen shot 2017-06-01 at 11 39 04" src="https://cloud.githubusercontent.com/assets/1637820/26674310/585ac56a-46c0-11e7-910a-b4f2cc974189.png">

**Comment by phgross** [comment]
@bierik bitte prüfen ob wir nicht gleiche alle mimetype Icons aktualisieren wollen.

**Comment by bierik** [comment]
Ich habe eine Anfrage an einen Designer auf fiverr.com gemacht. Um zu schauen ob wie uns Icons machen lassen können.

**Comment by bierik** [comment]
Der Designer von fiverr.com hat sich gemeldet und mit einige sketches gesendet. Ich habe diese hacky in die Dokumentenauflistung integriert.
Dies war seine letze Antwort mit seinen Überlegungen zum Design der Icons:
> There's nothing much we can do considering the icon size. 32x32 is pretty small, so all we can do is color coding and using already recognizable things such as colored corners and small letter badges. I made these and with a little tweaking I think they would look great. All of the others would use the same default shape to make them look like they're from the same pack, with different additions (colors, badges...)

![screencapture-dev-onegovgever-ch-fd-1497453781732](https://user-images.githubusercontent.com/1637820/27140708-85ce9f24-5126-11e7-8c6d-ee18ebcf3c83.png)

@buchi @phabegger Was sagt ihr dazu

**Comment by buchi** [comment]
Ich finde das Word-, Excel- und PowerPoint Icon gut. Klar erkennbar und auch kein offensichtlicher Klon. Würde also die restlichen Icons im gleichen Stil machen lassen. Wichtig ist, dass wir keine Icons vergessen. Man weiss ja nie wie lange der Fiver Typ aktiv ist.

**Comment by bierik** [comment]
@buchi @phabegger Soll ich nun die Icons bei fiverr.com in Auftrag geben?

**Comment by buchi** [comment]
von mir aus 👍 
ist ja finanziell kein Thema

**Comment by bierik** [comment]
<img width="1023" alt="screen shot 2017-06-30 at 14 38 27" src="https://user-images.githubusercontent.com/1637820/27735741-6afc394a-5da1-11e7-8531-f0935347a44c.png">

**Comment by phgross** [comment]
@bierik wie siehts hier nun aus, du solltest doch eigentlich ein "Screenshot" mit den neuen Icons erstellen, damit wir den Vorschlag auf dem Feedback-Forum platzieren können?

Zudem bräuchten wir noch ein Icon für OneNote Dateien. Kannst du das auch noch bestellen?
