### ISSUE TITLE
Fix word-break for overviews

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#2996]
At the moment the attribute table on a a document overview is set to `word-break: break-all`. This of course will then break words between any letters. I think that looks quite ugly and makes the overview unreadable. If i recall correctly we've done that to enable word-break for the filename. 

![screen shot 2017-06-01 at 10 34 18](https://cloud.githubusercontent.com/assets/736583/26671868/55dd3d8a-46b7-11e7-9e10-230c4e7dbb67.png)

I'd suggest to implement `word-break` as follows:
- `normal` for non-filename rows
- `break-all` for the filename

@bierik thoughts/suggestions?

**Comment by bierik** [comment]
@deiferni We already spent about 5 hours to make it work in bern.web -> https://github.com/4teamwork/bern.web/pull/1259

The hyphenation is very fragile and I will need about another 4 hours to integrate it properly without breaking other stuff.

And I would need some help and another 4 hours to figure out where we want to activate the hyphenation.

**Comment by deiferni** [comment]
as just discussed, we'll leave the hyphenation out for now and just fix it as discussed in the issue. that will simplify.

**Comment by deiferni** [comment]
we should make sure to address this issue in the next release. it starts to annoy customers.

![screen shot 2017-09-20 at 09 39 12](https://user-images.githubusercontent.com/736583/30632159-6d5a9ba6-9de7-11e7-8122-e285c33b49d4.png)
