### ISSUE TITLE
Aufgabe > Neu zuweisen > neues AutoComplete gibt Fehler

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3010]
Beim Testen des neuen AutoCompletes bei Aufgabe neu zuweisen, kam folgender Fehler:

IntegrityError('(psycopg2.IntegrityError) null value in column "actorid" violates not-null constraint\nDETAIL: Failing row contains (84, null).\n',) (Also, the following error occurred while attempting to render the standard error message, please see the event log for full details: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (raised as a result of Query-invoked autoflush; consider using a session.no_autoflush block if this flush is occurring prematurely) (psycopg2.IntegrityError) null value in column "actorid" violates not-null constraint DETAIL: Failing row contains (84, null). [SQL: "INSERT INTO watchers (id, actorid) VALUES (nextval('watchers_id_seq'), %(actorid)s) RETURNING watchers.id"] [parameters: {'actorid': None}])

URL oben war folgende: https://dev.onegovgever.ch/fd/ordnungssystem/bevoelkerung-und-sicherheit/einwohnerkontrolle/allgemeines/dossier-286/task-47/@@assign-task

**Comment by phgross** [comment]
@maethu kannst du dir das anschauen?

**Comment by maethu** [comment]
@phgross Hmm bei mir hats natürlich geklappt. 

@livschal Kannst du mir sagen, welchen Benutzer du ausgewählt hast?

**Comment by livschal** [comment]
@maethu habe es mir einfach in einem anderen mandaten zugewiesen (von afi zu ratskanzlei oder steuerverwaltung) dann wirfts diesen fehler. hab's noch mit zuweisen an phippu aber anderer mandat versucht; da gehts. --> also einfach wenn ich es mir selber in einem anderen mandanten zuweisen möchte, kommt der fehler.

**Comment by maethu** [comment]
@livschal danke für die info

**Comment by maethu** [comment]
nach Absprache mit @phgross sollte es gar nicht möglich sein andere Benutzer von anderen Mandanten auszuwählen 😄

**Comment by livschal** [comment]
@maethu dachte ich mir fast ;) aber könnt ihr dies irgendwie vorgängig abfangen, dass ich mich selber gar nicht auswählen kann?

**Comment by maethu** [comment]
Ich werde es so anpassen, dass nur Benutzer aus dem eigene Mandanten ausgewählt werden können.
