### ISSUE TITLE
Ordnungssystem Baum: jeweils nur aktive Position ausgeklappt darstellen.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3012]
> Navigiert man im OS und klickt dann (irgendwann) auf ein Dossier und arbeitet darin, so bleibt das Ordnungssystem immer "offen" (sprich: so, wie der Benutzer es gerade mittels der Dreiecke geöffnet oder geschlossen hat).

> Ziel wäre nun, OGG so anzupassen, dass beim Arbeiten in einem Dossier oder Dokument im OS links nur diejenige Rubrik geöffnet ist, wo das entsprechende Dossier/Dokument liegt. Der Rest soll automatisch zugeklappt werden.

@bierik bitte prüfen ob dies möglich wäre.

**Comment by phabegger** [comment]
Beachte auch aktuelle Diskussion im Feedback-Forum: https://feedback.onegovgever.ch/t/darstellung-des-ordnungssystems-im-balken-links/475

**Comment by phgross** [comment]
Scrollposition wurde korrigiert. Auf das zuklappen von "nicht aktiven Positionen" wird zurzeit verzichtet.
