### ISSUE TITLE
Aufgabenauflistungen die Spalte "Dossier" verlinken

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3013]
Müsste ähnlich wie bei Dokumenten gelöst werden, siehe https://github.com/4teamwork/opengever.core/blob/033e68ae4de64908e89cd7726cf516f26ec5ce8b/opengever/document/browser/redirect_to_parent_dossier.py#L9

- [x] Spalte "Dossier" von Tasklistings verlinken
- [x] Spalte "Subdossier" von Tasklistings verlinken

**Comment by elioschmutz** [comment]
@phgross Nur die Spalte "Dossier" oder auch die Spalte "Subdossier"? Es gibt für beides eine Spalte...

**Comment by phgross** [comment]
Ich würde es gleich für beide spalten machen ...

**Comment by elioschmutz** [comment]
- [x] Spalte "Dossier" von Tasklistings verlinken
- [x] Spalte "Subdossier" von Tasklistings verlinken
