### ISSUE TITLE
Falls eine msg Datei vorhanden ist, sollte diese Datei zur PDF-Vorschau verwendet werden

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3023]
Seit dem PR #2948 wird bei Msg Uploads nun auch die msg Datei in einem separaten Feld gespeichert. Nun soll die Bumblebee Integration so angepasst werden, dass für die PDF-Vorschau bei E-Mails die msg Datei verwendet werden soll, falls diese vorhanden ist.

- [x] .msg-Files für die visuelle Suche verwenden

**Comment by phgross** [comment]
@elioschmutz bitte prüfen ob und wie das möglich wäre.

**Comment by elioschmutz** [comment]
@phgross Ja, das ist möglich. Der Bumblebee unterstützt bereits die Konvertierung von .msg-Objekten:

- https://github.com/4teamwork/ftw.bumblebee/blob/master/ftw/bumblebee/mimetypes.py#L25

Integration:

- Für Mails benötigen wir eine spezifischere Implementation des `DXBumblebeeDocument`-Adapters, welche das neue Feld berücksichtigt

**Comment by phgross** [comment]
@elioschmutz bitte umsetzen.
