### ISSUE TITLE
Neue Spalte "Aktenzeichen" bei Dokumentauflistungen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3027]
Die bestehenden Dokumentauflistungen sollen mit einer zusätzlichen Spalte "Aktenzeichen", ähnlich wie das bei Dossiers der Fall ist ergänzt werden.

**Comment by tarnap** [comment]
![screen shot 2017-06-20 at 09 54 43](https://user-images.githubusercontent.com/194114/27322665-40602228-559f-11e7-9f3c-f9e9bfc36a15.png)
![screen shot 2017-06-20 at 09 55 58](https://user-images.githubusercontent.com/194114/27322666-40654ab4-559f-11e7-9f5b-75e775d69d94.png)
