### ISSUE TITLE
Dokument aus Vorlage öffnet Office Connector mit dem alten Protokoll

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#3044]
Wenn ein Dokument aus einer Vorlage erstellt wird, so wird dies anschliessend mit dem alten office Connector Protokoll geöffnet. Es kann somit nicht direkt eingecheckt werden nach dem Beenden.

**Comment by phgross** [comment]
Beim Formular `Dokument ab Vorlage` wird das Flag `is_officeconnector_checkout_feature_enabled` nicht beachtet. Es sollte aber gleich funktionieren wie bei `checkout_documents` (siehe https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/checkout.py#L75-L85).

Bitte auch gleich alle anderen External Editor Views prüfen (werden alle als redirect mit IRedirector registriert).

**Comment by tarnap** [comment]
Settings:
![screen shot 2017-06-21 at 17 33 28](https://user-images.githubusercontent.com/194114/27392799-e5f56c8a-56a7-11e7-9157-483d6796c315.png)

What happens:
![screen shot 2017-06-21 at 17 30 39](https://user-images.githubusercontent.com/194114/27392704-9d13403c-56a7-11e7-8015-28d0c515f667.png)

**Comment by tarnap** [comment]
The form schema can be found in `opengever/dossier/templatefolder/form.py`, it is called `ICreateDocumentFromTemplate`.
It is used in `SelectTemplateDocumentWizardStep`.

**Comment by tarnap** [comment]
Inserted `pdb` in `opengever.officeconnector.helpers.create_oc_url` to compare the calls when checking out a document (working use case) or creating one from template (raises previously mentioned error).

# Document checkout:

Context:
![screen shot 2017-06-22 at 07 40 42](https://user-images.githubusercontent.com/194114/27418891-3298aac2-571e-11e7-9d53-9d2d964c8edc.png)

Request:
![screen shot 2017-06-22 at 07 41 09](https://user-images.githubusercontent.com/194114/27418897-3ad5c2d8-571e-11e7-8434-eb406142a30e.png)

In this case the request method is `GET`

# New Document from template:

Context:
![screen shot 2017-06-22 at 07 54 13](https://user-images.githubusercontent.com/194114/27419225-ffca14f8-571f-11e7-891a-430d61858270.png)

Request:
![screen shot 2017-06-22 at 07 52 36](https://user-images.githubusercontent.com/194114/27419232-07aeee5a-5720-11e7-9a5c-4f0ab5f734b8.png)

**Comment by tarnap** [comment]
`opengever.officeconnector.helpers.parse_documents` tries to access the `request['BODY']` to parse the document.
When creating a document from template, the document is passed as context and its path does not need to be parsed from the body.

**Comment by tarnap** [comment]
The following seems to work: https://github.com/4teamwork/opengever.core/commit/7e50134a9978fe87177b778486585a70aee37948

![use officeconnector](https://user-images.githubusercontent.com/194114/27423465-f34d4d64-5731-11e7-8cb6-72e8955781dd.gif)
