### ISSUE TITLE
Darstellung von Beschreibung in Aufgaben verbessern (Zeilenumbrüche, Links)

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3054]
Siehe https://feedback.onegovgever.ch/t/zeilenumbrueche-in-aufgaben-darstellen/588/3

Mich interessiert eine technische Abklärung, was diesbezüglich möglich. In der aktuellen Version von OGG ist die Darstellung von längeren Arbeitsanweisungen unübersichtlich.

Scheint ein Textfeld zu sein, nicht eine DC-Description: 
https://github.com/4teamwork/opengever.core/blob/2ef69bcd1270018a250b843b91df9f4eea253d71/opengever/task/task.py#L143-L149

Evtl. eine andere portal_transform verwenden? Wichtig: Es dürfen keine Sicherheitslücken eingebaut werden, wenn das Textfeld "anders" interpretiert wird.

**Comment by phabegger** [comment]
Nachtrag: evtl. Tranformation auf 'text/-x-web-intelligent'?

**Comment by phgross** [comment]
@phabegger ja hierfür kann der Transform `text/x-web-intelligent` verwendet werden. 

@tarnap bitte die Darstellung der Beschreibung sowie die Antworttexte im Verlauf entsprechend anpassen. Siehe auch https://docs.plone.org/develop/plone/misc/html.html#converting-plain-text-to-html 

![bildschirmfoto_2017-07-03_um_13_27_12](https://user-images.githubusercontent.com/485755/27791017-66ff4cca-5ff3-11e7-90c2-e1136a597800.png)

**Comment by deiferni** [comment]
Nebenbemerkung: falls das die auch im Extranet verwendete Transform ist müsste man vermutlich etwas nachbessern, insbesondere werden Links am Ende eines Satzes falsch erkannt. Oft/meistens ist das Satzzeichen dann auch Teil des Links, was diesen kaputt macht.

➡️  test-case einbauen 😉

**Comment by tarnap** [comment]
> Es sollten zudem alle URL's auch klickbar gemacht werden. Lange URL's sollten gekürzt werden.

Is this kind of functionality already implemented somewhere?

**Comment by phabegger** [comment]
Ja, im Extranet nehme ich an

Nachtrag: Bei den versendeten Aufgaben-E-Mail-Benachrichtigungen wäre es natürlich auch nice, wenn Zeilenumbrüche respektiert würden... (separater Issue?)

**Comment by phgross** [comment]
@tarnap siehe [Kommentar](https://github.com/4teamwork/opengever.core/issues/3054#issuecomment-312725393) von Pascal. Bitte auch gleich in den E-Mail Benachrichtigungen korrigieren.

**Comment by tarnap** [comment]
Using `text/x-web-intelligent` does the following:
![description_text_to_html](https://user-images.githubusercontent.com/194114/27826304-cad2aebc-60b2-11e7-9ba3-edb8520f7bb9.png)

Using `text/-x-web-intelligent` does the following:
![description_text_to_html_ii](https://user-images.githubusercontent.com/194114/27827815-691ddf0a-60b9-11e7-9a7a-f91315883154.png)

Similar yet different results

**Comment by phgross** [comment]
hmm ok 😄  So, please use `text/x-web-intelligent`

**Comment by tarnap** [comment]
Testcases proposed by @deiferni 
https://extranet.4teamwork.ch/support/0xxx-support-test/tracker-support-test/7/view

**Comment by tarnap** [comment]
I just noticed this:
https://github.com/plone/plone.transforms/blob/ac34269d47719ee05ab7e4e0810e27df5f27a009/plone/transforms/text/web_intelligent.py#L7-L12

`plone.intelligenttext` is not buildout and therefore not available.
I'm adding it to see if this fixes our failing testcases

**Comment by tarnap** [comment]
After installation of `plone.intelligenttext` the issue persists.
I created the following issue: https://github.com/plone/plone.intelligenttext/issues/4

In the meantime the tests are skipped.
