### ISSUE TITLE
Add copy action to objects which can be copied

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3058]
Currently its only possible to copy a copyable object in its listings, it should also be possible to copy an object on its detail view:

Example for documents:
![bildschirmfoto_2017-06-27_um_08_47_13](https://user-images.githubusercontent.com/485755/27574109-4902871a-5b15-11e7-8f20-8d43fd8f10f4.png)

**Comment by tarnap** [comment]
It's not as easy as it looks!
The standard Plone copy action does not work for us, see:
![copy action](https://user-images.githubusercontent.com/194114/27591694-bcfacc26-5b52-11e7-9e09-72cff4d37fb2.gif)
