### ISSUE TITLE
Journalisierung bei Download von Dokumentversionen: Version mitjournalisieren

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3075]
Aktuell wird, wenn eine ältere Version eines Dokuments heruntergeladen wird, dies im Journal mit "Download Kopie" im Journal eingetragen. Um die Nachvollziehbarkeit zu verbessern, wäre es besser, hier auch die genaue Version mitzugeben, also zB. die Versionsnummer: "Download Kopie Version xy".

Lässt sich das umsetzen, @phgross ?

Referenz aus Feedback-Forum: https://feedback.onegovgever.ch/t/zip-export-journalisieren/53

**Comment by phgross** [comment]
@phabegger kann für zukünftige Downloads von Versionen angepasst werden.

**Comment by tarnap** [comment]
Implemented the following way:
![version in journal](https://user-images.githubusercontent.com/194114/27737170-7200b6de-5da7-11e7-94cf-111acb15e433.gif)
