### ISSUE TITLE
Kopie herunterladen bei E-Mails: Verhalten anpassen bei vorhandenen msg-Dateien

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3076]
Siehe https://feedback.onegovgever.ch/t/unterschiedliche-renditions-von-e-mails-verfuegbar-machen/584/5

Kopie herunterladen lädt je nach Situation MSG (falls msg vorhanden) oder EML (nur eml vorhanden) herunter (in dieser Reihenfolge).

Wichtig: Download muss journalisiert werden (inkl. Information, ob msg oder eml heruntergeladen wurde). M.W. werden Downloads bereits journalisiert, allerdings noch ohne Formatangabe.

**Comment by maethu** [comment]
@phabegger Im Moment ist es so, dass der Benutzer wählen kann, ob die MSG-Datei, oder das EML heruntergeladen werden soll. 

Mit dieser Anpassung wäre es nicht mehr möglich das konvertierte EML herunterzuladen. 
Ausserdem wäre das Feld `Quelldatei im *.msg Format vor der Konvertierung` überflüssig und muss entfernt werden. 

Bitte noch einmal bestätigen, dass...:
- es ist nicht mehr möglich sein soll die konvertierte EML-Datei herunterzuladen.
- das Feld `Quelldatei im *.msg Format vor der Konvertierung` entfernt werden soll. 


Ich bin der Meinung, dass die aktuelle Lösung mit zwei separaten Felder gut ist und es nur die Unterscheidung brauch, ob der Benutzer das EML, oder MSG heruntergeladen hat.

**Comment by deiferni** [comment]
Das Feld `original_message` bitte nicht entfernen, das wird gebraucht 😓 . Es ist im Moment nur für `Manager` sichtbar, wir haben es mit der Motivation zum debuggen des D&D uploads eingebaut. Es wird aber neu auch in anderen, noch offenen, issues benötigt werden, z.B. https://github.com/4teamwork/opengever.core/issues/3023.

**Comment by phgross** [comment]
@maethu Der Download, nicht aber die Speicherung der E-Mail Datei soll angepasst werden.
Für ein E-Mail soll nach wie vor ein EML generiert und abgelegt werden, auch wenn es sich beim E-Mail um eine *.msg Datei handelt. 

Wieso meinst du dass das Feld `Quelldatei im *.msg Format vor der Konvertierung` überflüssig wird?

**Comment by maethu** [comment]
Mit @phgross diskutiert.
Anscheinend wird die MSG-Datei nur den Admins angezeigt. 

- Der `normale` GEVER Benutzer hat keine Auswahl. Es wird falls vorhanden die MSG-Datei ausgeliefert.

**Comment by phabegger** [comment]
@maethu War mir doch noch - ich habe nicht gesehen, dass ich beide Formate runterladen kann... Gemäss Feedback aus dem Forum will eigentlich niemand das EML, wenn das MSG noch vorhanden ist...

**Comment by maethu** [comment]
Ich habe nun am Journal nichts geändert, da der normale GEVER User kein Wahl hat was heruntergeladen wird.

In #3076 wir nun aber, falls vorhanden, das MSG-File zum Download angeboten

**Comment by phabegger** [comment]
@maethu ist im journal ersichtlich, ob er/sie das eml bzw. das msg runtergeladen hat? dies spielt schon eine rolle.

**Comment by maethu** [comment]
@phabegger Nein. Der Benutzer kann ja nicht wählen, was er herunterlädt. GEVER liefert nun neu das MSG aus, falls es da ist. im GUI wird dem Benutzer auch nur noch das MSG-File angeboten. 

Soll das trotzdem im Journal erscheinen?

**Comment by phgross** [comment]
@phabegger wünscht du hier trotzdem eine Unterscheidung im Journal, obwohl der Benutzer selber gar nicht entscheiden kann?

**Comment by phabegger** [comment]
Ja. Entweder "Download als MSG" oder "Download als EML". Es ist sonst nicht klar, was "Download Kopie" bedeutet (Nachvollziehbarkeit).
