### ISSUE TITLE
Search results markup varies, depending on the action

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#3077]
# Problem
The titles of the listing in the search results vary depending on the search used.
Sometimes the titles are wrapped in spans, sometimes they're not.

Wrapped:
![spanned](https://user-images.githubusercontent.com/194114/27676265-92f832ea-5cad-11e7-8536-c4d85c0ffbc2.png)

Unwrapped:
![unspanned](https://user-images.githubusercontent.com/194114/27676266-92fabf7e-5cad-11e7-9eb6-b9259470bea1.png)

# Further research

The titles are wrapped using the "upper form" or directly calling the URL (ergo, passing the text to be searched as GET parameters):
![form_top_rendered](https://user-images.githubusercontent.com/194114/27676473-59a366ee-5cae-11e7-876f-ac48aa4b7c3a.png)
![form_top](https://user-images.githubusercontent.com/194114/27676474-59a6c546-5cae-11e7-94a3-fea94614c07e.png)

The titles are not wrapped using the form in the "content":
![form_content_rendered](https://user-images.githubusercontent.com/194114/27676801-aa26efb8-5caf-11e7-845d-dcd2e97a6b1d.png)
![form_content](https://user-images.githubusercontent.com/194114/27676800-aa25833a-5caf-11e7-9d3c-cf1c99854bd0.png)

# Screen recording

Here's the whole behaviour:
![funny2](https://user-images.githubusercontent.com/194114/27579025-5e1c2c8a-5b26-11e7-83f9-7d15401b7e6c.gif)

**Comment by elioschmutz** [comment]
``highlightSearchTerms`` wird nur bei einem Pagereload ausgeführt
https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_ecmascript/jquery.highlightsearchterms.js#L212

Die Suche über AJAX führt ``highlightSearchTerms`` nicht erneut aus:
https://github.com/plone/plone.app.search/blob/1.1.x/plone/app/search/search.js#L16

Leider gibt es auch keine Events, welche für das erneute ausführen von ``highlightSearchTerms`` nach der Suche verwendet werden können.

@bierik siehst du einen Weg, wie nach ``pullSearchResults`` die Funktion ``highlightSearchTerms`` mit der gleichen Konfiguration wie bei der Initialisierung (https://github.com/plone/Products.CMFPlone/blob/master/Products/CMFPlone/skins/plone_ecmascript/jquery.highlightsearchterms.js#L216) erneut ausgeführt werden kann, ohne dass die ganzen Plone-Module angepasst werden müssen?

**Comment by elioschmutz** [comment]
Mit @bierik diskutiert.

Eventlistener auf Ajaxrequest gem. https://github.com/4teamwork/opengever.core/blob/master/opengever/bumblebee/browser/resources/bumblebee.js#L196 erstellen.
