### ISSUE TITLE
Neues Feld "Externe Referenz" auf Dossiertypen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3080]
Siehe Diskussion https://feedback.onegovgever.ch/t/dossier-mit-indexiertem-feld-fremdzeichen-erweitern/370/20

Weitere Anforderungen an dieses Feld:
- Feld kann Text/Ziffern/etc. enthalten - je nach Anwendungsfall ist der enthaltene Wert anders aufgebaut.
- Nach diesem Feld sollte gesucht werden => richtiger Index-Typ wählen!
- Evtl. kann der gleiche Index wie bei "Fremdzeichen" auf Stufe Dokument verwendet werden.
- Vorschlag englisch: "external reference"
- Das Feld "Externe Referenz" muss über API gesetzt und abgefragt werden können.

**Comment by mbaumi** [comment]
Ich fände es nützlich, wenn das Feld auch in der Dossierübersicht als "Spalte" angezeigt und sortiert werden kann. Bspw. bei Personaldossiers in grösseren Organisation kann es vorkommen, dass mehr als 1 Person denselben Namen/Vornamen hat. 

In der Übersicht (bspw. Personaladministration) erhält man mit der Spalte eine wichtige Zusatzinformation und kann die "richtige Person" selektieren.

**Comment by phgross** [comment]
@tarnap Bitte folgendes umsetzten:
 - [ ] Zusätzliches TextLine Feld `external_reference` zum `IDossier` behavior hinzufügen.
 - [ ] API Schema Docs updaten

**Comment by tarnap** [comment]
@phgross welchem fieldset sollte `external_reference` hinzugefügt werden?
Folgende stehen zur Auswahl:
- `common`: keywords, start, end, comments ...
- `filing`: filing prefix, container type, number of containers ...

**Comment by phgross** [comment]
@tarnap Habe mich noch mit Pascal besprochen, bezüglich dem separaten Index:

Es soll ein separater Index `external_reference` hinzugefügt werden. Ein Suchfeld wird vorerst nicht implementiert, eine Abfrage ist vorerst nur via API möglich.

Der Index soll neben dem neu hinzugefügten Feld  external_reference bei Dossiers, auch bei Dokumenten den Wert des Feldes `Fremdzeichen` indexieren.

**Comment by mbaumi** [comment]
@phgross was bedeutet "ein Suchfeld wird vorerst nicht implementiert". Wir der Wert über die Suche nicht gefunden, oder wird keine Facette für "external_reference" erzeugt oder ...

Ergänzende Frage: Wird eine Spalte für den Wert "external_reference" bspw. auf Ordnungsposition für die darin enthalten Dossiers (in Tabbed View) angezeigt?

Gerade für das Beispiel der Personaldossiers bei Köniz, ist es in der Praxis aus meiner Sicht sinnvoll, dass die Spalte "external_reference" im Tabbed View (s. erg. Frage oben) erscheint. Damit kann nach der Nr. sortiert und auch gefiltert werden.

**Comment by tarnap** [comment]
@mbaumi: Das Feld "external_reference" wird schon in der Suche gefunden, doch wird über die normale Suche eine Volltextsuche gemacht. Dies führt dazu dass deren Werte bearbeitet aufgefunden werden, z.B. wird "beispiel-text" unter "beispiel" und "text" gefunden. Daher sind die Suchresultate nicht umbedingt eindeutig.

Erwünscht ist ein weiteres Suchfeld, welches dieses Feld eindeutig findet.
