### ISSUE TITLE
Eliminate possibly dead opengever.sharing.behaviors.IStandard

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3095]
Investigate and eliminate possibly dead behavior `opengever.sharing.behaviors.IStandard` which is not assigned to any content type and thus seems unused.

**Comment by elioschmutz** [comment]
@deif The behavior itself is not assigned to a context, but it will be used to display fallback-roles on objects not providing the `IDossier` behavior:

- https://github.com/4teamwork/opengever.core/blob/master/opengever/sharing/browser/sharing.py#L84
- https://github.com/4teamwork/opengever.core/blob/master/opengever/journal/handlers.py#L93

therefore I would not remove it.

**Comment by deiferni** [comment]
Fair enough, not dead in that case. That code seems used indeed.
