### ISSUE TITLE
Aufgabe an anderen Mandant mit Bearbeitung in dessen Dossier

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3097]

**Comment by livschal** [comment]
Wenn ich eine Aufgabe (Typ: Prüfung/Kenntnisnahme) an eine Person eines anderen Mandaten zuweise und die Option anwähle, diese in einem Dossier in dessen Mandaten zu bearbeiten, wechselt der Status im ursprünglichen Mandaten nicht auf abgeschlossen, sondern bleibt auf erledigt.

1. Aufgabe erstellen: Auftragnehmer AFI, Auftraggeber RK
2. Aufgabe akzeptieren, 2. Option anwählen, dass Aufgabe in Ratskanzlei erledigt wird > dadurch wird Aufgabe kopiert und GEVER wechselt auf RK. 
3. Aufgabe wird dort erledigt und abgeschlossen.
4. Wird wieder auf AFI gewechselt, ist die Aufgabe im Status erledigt, kann aber nicht abgeschlossen werden. Zudem kommt im Verlauf die Info, dass die Aufgabe abgeschlossen sei.
--> Dies  ist bei einer Hauptaufgabe der Fall (https://dev.onegovgever.ch/fd/ordnungssystem/bevoelkerung-und-sicherheit/einwohnerkontrolle/falldossiers/dossier-350/task-84#overview) aber auch bei Unteraufgaben (https://dev.onegovgever.ch/fd/ordnungssystem/bevoelkerung-und-sicherheit/einwohnerkontrolle/falldossiers/dossier-350/dossier-352/task-82/task-83#overview)

**Comment by phgross** [comment]
Ich konnte das Problem reproduzieren (Stand Master): Der Status wird zwar korrekt auf den Successor bzw. Predecessor synchronisiert, das entsprechende Pendant wird aber im Globalindex nicht aktualisiert. Ich arbeite nun an einer Korrektur.

@livschal Danke für die gute Beschreibung.
