### ISSUE TITLE
Float the login failure flash message with the login box

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3099]
Currently the flash message is at the top and the login box in the centre of the screen.

It would be easier to visually parse what is going on if the flash message is displayed relative to the login box rather than at a static distance from the top.

![screen shot 2017-07-10 at 14 12 17](https://user-images.githubusercontent.com/935317/28017523-f1f87f0a-6579-11e7-8b5d-c5a927c94c9d.png)

**Comment by bierik** [comment]
The GEVER user never sees this form. Because we use the portal everywhere. /cc @phgross
