### ISSUE TITLE
SPV: Gremium erstellen failt

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3100]
Wenn ich auf dev.onegovgever.ch ein Gremium erstellen möchte, kommt untenstehender Fehler. Name und Vorlagen kann ich hinterlegen, aber wenn ich die Periode (1.1.17-31.12.17 resp. 1.8.17-31.12.17) speichern möchte kommt folgender Fehler:
![bildschirmfoto 2017-07-10 um 15 31 34](https://user-images.githubusercontent.com/20790360/28020482-e9066fbe-6584-11e7-9808-c4715f855f61.png)
--> habe es bei zwei Gremien mit unerschiedlicher Periode und Ablage-Position versucht.

**Comment by phgross** [comment]
@deiferni kannst du dir das kurz anschauen ?

**Comment by livschal** [comment]
Nachtrag @deiferni : bei Sitzung hinzufügen passiert das gleiche:
![bildschirmfoto 2017-07-10 um 15 52 49](https://user-images.githubusercontent.com/20790360/28021369-e44b4e1a-6587-11e7-8957-0ff80ccf3976.png)

**Comment by deiferni** [comment]
Problem beim erstellen der Gremien auf dev ist manuell korrigiert worden.

Problem beim Erstellen der Sitzungen hat eine andere Ursache, siehe https://github.com/4teamwork/opengever.core/issues/3102.

Hintergrundinfos zum Gremien-Problem:
im Upgrade-Step https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/upgrades/to4618.py#L24 fehlt die `Sequence` in der Column `id`. Deshalb wurde die `Sequence` nie erstellt. Weil alle anderen System jedoch erst später aktualisiert wurden und dort die Tabelle mit dem Upgrade https://github.com/4teamwork/opengever.core/blob/master/opengever/policy/base/upgrades/to4200.py erstellt wurden tritt das Problem nur auf `dev` auf. Ich habe manuell korrigiert in dem ich die `Sequence` mit folgendem Statement erstellt habe:

`create sequence periods_id_seq start 10;`

**Comment by deiferni** [comment]
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3540/
