### ISSUE TITLE
Vorlagen: Anzeigefehler

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3105]
Wenn ich ein Dokument aus Vorlage wähle, zeigt es mir je nach dem nur die Checkboxen nicht an oder manchmal auch der Typ der Vorlage nicht (kann nicht reproduzieren wann welcher Fall auftritt).

![bildschirmfoto 2017-07-11 um 06 50 19](https://user-images.githubusercontent.com/20790360/28051562-8ef2c0d2-6605-11e7-8a05-1391e32e3e40.png)
![bildschirmfoto 2017-07-06 um 14 21 26](https://user-images.githubusercontent.com/20790360/28051563-8efa2ad4-6605-11e7-98bb-9b590f18c39d.png)

Und innerhalb der Vorlagen ist das Anzeige-Menu schwarz hinterlegt, bei welchem ich zwischen Liste und Anzeige einzelne Dokumente wählen kann.
![bildschirmfoto 2017-07-11 um 06 37 13](https://user-images.githubusercontent.com/20790360/28051576-9bdf0706-6605-11e7-860f-4c6994cfa072.png)

**Comment by livschal** [comment]
Problem tritt via Remote und wenn ich mich lokal auf dem Windows-Gerät anmelde auf.

**Comment by phgross** [comment]
@bierik kannst du dir das mal ansehen? Problem tritt nur im IE11 auf.

**Comment by bierik** [comment]
Der Fehler kann nur auf unserer Windows Chüschda reproduziert werden. Auf dem Support Laptop mit IE11 alles i.O.
