### ISSUE TITLE
Anzeigefehler bei "Anhänge extrahieren"

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3106]
Wenn ich ein Mail via Mailin in ein Dossier schicke und danach die Anhänge extrahieren / speichern möchte, kommt folgender Anzeigefehler:

![bildschirmfoto 2017-07-11 um 06 59 24](https://user-images.githubusercontent.com/20790360/28051753-a6c6182a-6606-11e7-9cd7-a0fe89593330.png)

**Comment by phgross** [comment]
@livschal ich vermute das dies nur ein temporäres Problem von "RemoteDesktop" war und eigentlich nichts mit dem GEVER zu tu hat. @livschal könntest du kurz überprüfen ob u die Probleme reproduzieren kannst, wenn du dich am Gerät selber anmeldest.

**Comment by livschal** [comment]
@phgross jap ist wirklich nur via remote so. schliesse daher das ticket.
