### ISSUE TITLE
Resolve end date does not respect first level document dates

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3107]
While archiving a dossier, the earliest possible end date does not respect documents stored on dossier-root-level.

Documents may be on dossier-root when:
- there is no subdossier
- the resolving is configured to be `lenient` (https://github.com/4teamwork/opengever.core/pull/2972)

**Comment by phgross** [comment]
@elioschmutz schlage vor das wir das kurz zusammen anschauen, bevor du loslegst ...

**Comment by jone** [comment]
This is actually not true: there is no such bug.
I assumed that there is a bug because [only documents of `subdossier` are respected](https://github.com/4teamwork/opengever.core/blob/8c4011c8439448d8972f58306402c57dbf0b5fe7/opengever/dossier/base.py#L267).
What I didn't realize is that the main dossier is included in `subdossiers` and therefore its documents are actually included.

@elioschmutz will simplyfy the method anyway, since the business rule is quite simple:
*The earliest possible end date must be after all document dates and all dossier start and end dates.*
