### ISSUE TITLE
Speed up checkin / checkout

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3124]
The checkin-checkout-manager executes [`self.document.reindexObject()`](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L153) on changes, which also reindexes the searchable text etc.

It think we could only reindex the relevant indexes, probably `self.document.reindexObject(idxs=['checked_out'])`.

- Find out which indexes actually change
- Only index those indexes
- Update all 3 places in the checkin/checkout-manager.

**Comment by phgross** [comment]
Sounds reasonable. Deos Office Connector also updates the SearchableText when uploading the changed document 🤔 ? Otherwise the reindex of SearchableText is necessary when checking in a Document.

**Comment by phgross** [comment]
I've checked doublechecked the current behavior.
 - Office Connector updates the searchable Text also when replacing the file via the edit form.
 - But replacing the document via D'n'D does not updated the SearchableText.

**Comment by phgross** [comment]
Solved via #3311
