### ISSUE TITLE
Update `plone.app.jquery` to version 1.11.2

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3138]
See
 - https://community.plone.org/t/latest-usable-jquery-for-plone-4-3-1-11-3/2242
 - https://pypi.python.org/pypi/plone.app.jquery/1.11.2
    > Note that this 1.11 version is not officially used by any Plone version. Use at your own risk/discretion. Plone 4.3 uses 1.7.x.

Try out and double check if a update to the `plone.app.jquery 1.11.2` is possible ...

**Comment by lukasgraf** [comment]
Closes: #3060

**Comment by elioschmutz** [comment]
@phgross Is there a specific issue or a missing feature with the current version? Or do you want to upgrade it just to be up-to-date?
