### ISSUE TITLE
Proposal: i18n translations on the frontend

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#3177]
This proposal is about having translations on the frontend. We need translations on the javascript side for widgets for example.

As discussed with @lukasgraf there are various restrictions to do that.

Restrictions:
- We don't want to have duplicated translations. Already existing translations in plone or GEVER must be available in the javascript stack.
- gever and all other translations in the omelette have a size of about 8mb gzipped. So there should be a strategy fetching these translations without downloading all 8mb at once.
- The translations must be cacheable
- The cache must be invalidated when a new label is added.
- There must be a smart and easy to use API on the javascript side for getting these translations
- The translations must be available in all Handlebars templates
- The plone community should benefit from a reliable solution because the frontend stack is growing rapidly there

Attempt:
We build a REST endpoint for getting the translations.
This endpoint serves all translations for a specific domain e.q: `@i18n?domain=opengever.meeting`. The language can be extracted from the `Accept-Language` header. The caching is done by the browser and controlled through a cache header.
So every time a new domain is requested by the client the endpoint has to deliver this domain.

Translations which are just consumed by the frontend are tracked in a separate `.pot` file `frontend-translations.pot`.

In the javascript we could have a special directive such as `t{label_something, opengever.core}` or a function `t('label_something', 'opengever.core)` for getting these translations.

The javascript then injects a `<script src="@i18n?domain=opengever.core"></script>` tag for every domain needed.

The discussion results out of the following pull request where we tried to solve this problem:
https://github.com/4teamwork/opengever.core/pull/3168

@lukasgraf do you have something to add
@maethu @jone @buchi you are very welcome to contribute

**Comment by jone** [comment]
This sounds reasonable.

How does the JS load the translation catalog?
a) the catalog is always loaded on page load
b) the catalog is loaded on the first request of a translation in the catalog

With b) there should be some promises (or callbacks 😉 ) involved because it could take some time and should not block..

**Comment by bierik** [comment]
Plone 5 has already implemented some sort of an endpoint for translations. So lets build the same using the plone REST API:
backend: https://github.com/plone/plone.app.content/blob/master/plone/app/content/browser/i18n.py
frontend: https://github.com/plone/mockup/blob/master/mockup/js/i18n.js

**Comment by jone** [comment]
This is not using the rest api , it's just a view returning some bytes.

**Comment by bierik** [comment]
@jone 
> So lets build the same using the plone REST API 😉

**Comment by jone** [comment]
👍 yes

**Comment by lukasgraf** [comment]
@bierik now that the new frontend is underway, could you at some point check if this is still relevant?
I get the feeling that the new frontend now mostly manages its own translations for the most part, and there is little to no overlap with translations used in the backend.

**Comment by phgross** [comment]
outdated.
