### ISSUE TITLE
Verschachtelte Darstellung der Vorlagen

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3189]
Bitte umsetzen gemäss: https://feedback.onegovgever.ch/t/verschachtelte-darstellung-der-vorlagen/147/2

Ausgangslage:
- Vorlagen können in versch. Ordner abgelegt werden
- Wird die Option "Dokument hinzufügen aus Vorlage" gewählt, werden aber alle Vorlagen unstrukturiert dargestellt.
- Wunsch der GEVER-Community ist, diese Struktur auch dort beizuhalten.

![bildschirmfoto 2017-07-27 um 15 11 02](https://user-images.githubusercontent.com/20790360/28671789-2e029faa-72de-11e7-96be-c19202599aa5.png)
![bildschirmfoto 2017-07-27 um 15 11 10](https://user-images.githubusercontent.com/20790360/28671808-3a164bca-72de-11e7-86a3-e3d33614dd1d.png)

Ref: https://basecamp.com/2768704/projects/13732725/todos/337385250

**Comment by deiferni** [comment]
@livschal wir sind bei der Umsetzung davon ausgegangen, dass die Benutzer grosse Probleme beim *finden* der Vorlagen haben. Deshalb in einem ersten Schritt ein Suchfeld. Dies sollte die Problematik deutlich entschärfen. Falls immer noch eine Struktur gewünscht wird evtl. zweiter Schritt …
