### ISSUE TITLE
Keywordwidget creates also a keyword for the search string

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3195]
Steps to reproduce the problem:
 - Edit a Dossier/Document
 - Input search string "Geh", to find the existing keyword "Geheimes Dossier"
 - Select the existing keyword "Geheimes Dossier"
 - Save

![keyword widget issue](https://user-images.githubusercontent.com/485755/28711664-a6f69ba0-7388-11e7-823c-be83dc972974.gif)

Problem could be reproduced on [test.onegovgever.ch](https://test.onegovgever.ch/fd/ordnungssystem/soziale-sicherheit/ahv-iv-und-zusatzleistungen/allgemeines/dossier-23#overview)

**Comment by maethu** [comment]
Fixed in https://github.com/4teamwork/ftw.keywordwidget/pull/21

**Comment by phgross** [comment]
@maethu 👍. Could you add a PR which updates the version pinning in the versions.cfg as soon you have created a new version ...

**Comment by maethu** [comment]
ftw.keywordwidget = 1.3.3 behebt das Problem.
