### ISSUE TITLE
Remove grok

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3205]
This issue is meant as an overview for the ongoing process to replace grok with zcml registrations. 

:white_large_square: = todo
:pencil2:  = in progress
:ballot_box_with_check:  = PR in review
:white_check_mark:  = PR merged

:white_check_mark: activity, @elioschmutz (#3244)
:white_check_mark: advancedsearch, @phgross
:white_check_mark: api ()
:white_check_mark: base, @elioschmutz (#3521)
:white_check_mark: bumblebee, @elioschmutz (#3248)
:white_check_mark: bundle ()
:white_check_mark: contact, @elioschmutz (#3269)
:white_check_mark:   core, @elioschmutz (#3528)
:white_check_mark: debug, @elioschmutz (#3255)
:white_check_mark: disposition, @elioschmutz  (#3267)
:white_check_mark: document, @elioschmutz (#3503, #3522)
:white_check_mark: dossier, @elioschmutz (#3508)
:white_check_mark: examplecontent ()
:white_check_mark: globalindex, @elioschmutz (#3272)
:white_check_mark: inbox, @elioschmutz (#3472)
:white_check_mark: journal, @elioschmutz (#3276)
:white_check_mark: latex, @elioschmutz (#3288)
:white_check_mark: locking, @elioschmutz (#3280)
:white_check_mark: mail, @elioschmutz (#3281)
:white_check_mark:  meeting, @elioschmutz (#3524)
:white_check_mark: officeatwork, @elioschmutz (#3499)
:white_check_mark: officeconnector ()
:white_check_mark: ogds.base, @lukasgraf (#3277)
:white_check_mark: policy ()
:white_check_mark:  policytemplates, @elioschmutz (#3525)
:white_check_mark: portlets ()
:white_check_mark: private, @elioschmutz (#3481)
:white_check_mark: quota ()
:white_check_mark: repository, @elioschmutz (no PR)
:white_check_mark: setup ()
:white_check_mark: sharing, @elioschmutz (#3284)
:white_check_mark: sphinx ()
:white_check_mark: tabbedview, @phgross
:white_check_mark: tabbedview fetch views entfernen, @elioschmutz (#3246)
:white_check_mark: task, @elioschmutz (#3497)
:white_check_mark: tasktemplates, @elioschmutz (#3286)
:white_check_mark: testing ()
:white_check_mark: trash, @phgross (#3315)
:white_check_mark: usermigration ()
:white_check_mark: TranslatedTitle, @elioschmutz  (#3269)
:white_check_mark: Doublecheck for grok `form.default_value`, `plone.directives.form`, plone.directives.dexterity`, @elioschmutz (#3521)

Other Packages:

:white_check_mark: opengever.maintenance, @elioschmutz (https://github.com/4teamwork/opengever.maintenance/pull/93)
:white_check_mark: opengever-deployments, @elioschmutz (not grokked)
:white_check_mark: opengever.loadtesting, @elioschmutz (https://github.com/4teamwork/opengever.loadtesting/pull/8)
:white_check_mark: opengever.hatchery, @elioschmutz (https://github.com/4teamwork/opengever.hatchery/pull/10)
:white_check_mark: opengever.ftw, @elioschmutz (https://github.com/4teamwork/opengever.ftw/pull/50)
:white_check_mark: opengever.bsmigration, @elioschmutz (not grokked)
:white_check_mark: opengever.ogds.models, @elioschmutz (not grokked)
:white_check_mark: opengever.pdfconverter, @elioschmutz (https://github.com/4teamwork/opengever.pdfconverter/pull/16)

Policies

:white_check_mark: opengever.kgkoeniz, @elioschmutz (https://github.com/4teamwork/opengever.kgkoeniz/pull/30)
:white_check_mark: opengever.framsteg, @elioschmutz (https://github.com/4teamwork/opengever.framsteg/pull/7)
:white_check_mark: opengever.demo, @elioschmutz (https://github.com/4teamwork/opengever.demo/pull/46)
:white_check_mark: opengever.domas, @elioschmutz (https://github.com/4teamwork/opengever.domas/pull/2)
:white_check_mark: opengever.zug, @elioschmutz (https://github.com/4teamwork/opengever.zug/pull/260)
:white_check_mark: opengever.nidau, @elioschmutz (https://github.com/4teamwork/opengever.nidau/pull/16)
:white_check_mark: opengever.bs, @elioschmutz (https://github.com/4teamwork/opengever.bs/pull/41)
:white_check_mark: opengever.phbern, @elioschmutz (https://github.com/4teamwork/opengever.phbern/pull/22)
:white_check_mark: Trashed opengever.sgdemo, @elioschmutz (https://github.com/4teamwork/opengever.sgdemo/pull/4)
:white_check_mark: opengever.htwchur, @elioschmutz (https://github.com/4teamwork/opengever.htwchur/pull/9)
:white_check_mark: opengever.liesberg, @elioschmutz (https://github.com/4teamwork/opengever.liesberg/pull/14)
:white_check_mark: opengever.mumpf, @elioschmutz (https://github.com/4teamwork/opengever.mumpf/pull/10)
:white_check_mark: opengever.duerrenaesch, @elioschmutz (https://github.com/4teamwork/opengever.duerrenaesch/pull/26)
:white_check_mark: opengever.phvs, @elioschmutz (https://github.com/4teamwork/opengever.phvs/pull/110)
:white_check_mark: opengever.ai, @elioschmutz (https://github.com/4teamwork/opengever.ai/pull/189)
:white_check_mark: opengever.hpcdual, @elioschmutz (https://github.com/4teamwork/opengever.hpcdual/pull/11)
:white_check_mark: opengever.sg, @elioschmutz (https://github.com/4teamwork/opengever.sg/pull/207)

**Comment by deiferni** [comment]
this seems done 🎉
