### ISSUE TITLE
Wrong dossier-reference-number on proposal after moving dossier.

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3234]
After moving a dossier, the `dossier_reference_number` cached in the proposal's SQL is not correct: the dossier part is missing.
This issue might appear when subscribers are in wrong order.
The problem was discovered in test, a production problem was not verified at this point.

https://github.com/4teamwork/opengever.core/blob/cb75d8d399dfe043e448960a206ba76fe59a95e0/opengever/meeting/tests/test_proposal.py#L276-L278

/cc @deiferni

**Comment by Rotonen** [comment]
Figured out the what.

This fires first:
https://github.com/4teamwork/opengever.core/blob/c73afefd0549c0d7cfc2c7cc810fe6b7306fede5/opengever/meeting/handlers.py#L74
https://github.com/4teamwork/opengever.core/blob/c73afefd0549c0d7cfc2c7cc810fe6b7306fede5/opengever/meeting/proposal.py#L638-L639

But blindly assumes this to have already fired first:
https://github.com/4teamwork/opengever.core/blob/c73afefd0549c0d7cfc2c7cc810fe6b7306fede5/opengever/dossier/handlers.py#L57

Still slightly mystified as to how to proceed as explicit event ordering is not a thing in Plone and the solutions I can think of would duplicate the work done in the dossier event handler.

**Comment by lukasgraf** [comment]
@Rotonen
> ... as explicit event ordering is not a thing in Plone

A pattern that's been emerging from this fact is that event handlers should, whenever possible, be written so they're idempotent. Then they can be invoked multiple times in a manner that's at least safe.

If we can make sure the `save_reference_number_prefix()` handler guarantees idempotency, it could be explicitely invoked from the place in `proposal.py` that relies on it having fired, no? Tagging the request in some way and checking for that before firing again could be a generalizable approach independent of what exactly a specific handler does.

`</thinking out loud>`

**Comment by Rotonen** [comment]
On the same vein - the description of `zope.event` says:

```
A very simple event-dispatching system on which more sophisticated event dispatching systems can be built. 
```

We could have actual use-cases for being able to inject stuff with before and after hooks and the likes.

But for the actual issue at hand, I'd still like to figure out how to avoid the unnecessary reindex, but I suppose there are not many good options here.

**Comment by lukasgraf** [comment]
The repeated reindexing should be collapsed into just one operation by `collective.indexing`.

What about

```python
@only_once
def my_handler(obj, event):
    # ....
```
And `@only_once` (or `@at_most_once` maybe) would tag the request with some unique discriminator based on `wrapped_func.__name__`...
