### ISSUE TITLE
Adapterregistrierung

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#3264]
# Einleitung

In einem früheren Schritt wurde entschieden, dass wir neu Decorators und nicht mehr ZCML für die Adapter-Registrierung verwenden und alle bestehenden Adapter-Regsitrierungen im GEVER dementsprechend anpassen.

# Problem
Nun bin ich auf folgendes Problem gestossen:

Ein Objekt, welches bereits ein Interface implementiert und anschliessend ein zusätzliches Interface über den `implementer`-Decorator erhält stellt anschliessend beide Interfaces zur Verfügung. Ein Adapter kann somit nicht mehr registriert werden, da das zur providende Interface nicht mehr eindeutig ist. Hier ein Beispiel zur Verdeutlichung:

## Beispiel 1

```python
from zope.component import adapter
from zope.interface import implementer
from zope.interface import implements
from zope.interface import Interface


class IBase(Interface):
    """
    """


class Base(object):
    """
    """
    implements(IBase)


class IAdapterTest(Interface):
    """
    """


@implementer(IAdapterTest)
@adapter(Interface, Interface)
class Child(Base):
    """
    """
    def __init__(self, obj, req):
        pass

```

```xml
<configure
    xmlns="http://namespaces.zope.org/zope"
    xmlns:browser="http://namespaces.zope.org/browser"
    i18n_domain="opengever.dossier">

  <adapter factory=".adapters.Child" />

</configure>

```
Wird folgender Fehler verursachen:

```
TypeError: Missing 'provides' attribute
```

## Lösung 1

Das Problem kann behoben werden, wenn das Interface über ZCML angegeben wird. Zope weiss dann, dass es genau dieses Interface als Adapter registrieren soll:

```python
from zope.component import adapter
from zope.interface import implements
from zope.interface import Interface


class IBase(Interface):
    """
    """


class Base(object):
    """
    """
    implements(IBase)


class IAdapterTest(Interface):
    """
    """


@adapter(Interface, Interface)
class Child(Base):
    """
    """
    def __init__(self, obj, req):
        pass
```

```xml
<configure xmlns="http://namespaces.zope.org/zope">

  <adapter factory=".adapters.Child"
                  provides=".adapters.IAdapterTest" />

</configure>

```

# Weiterführende Informationen
Hier noch ein kleiner Ausschnitt aus der Adapter-Direktive, damit verständlich wird, was im Hintergrund geschieht:

```python
def adapter(_context, factory, provides=None, for_=None, permission=None,
            name='', trusted=False, locate=False):

    if for_ is None:
        if len(factory) == 1:
            for_ = zope.component.adaptedBy(factory[0])

        if for_ is None:
            raise TypeError("No for attribute was provided and can't "
                            "determine what the factory adapts.")

    for_ = tuple(for_)

    if provides is None:
        if len(factory) == 1:
            p = list(zope.interface.implementedBy(factory[0]))
            if len(p) == 1:
                provides = p[0]

        if provides is None:
            raise TypeError("Missing 'provides' attribute")

```

# Alternativer Lösungsvorschlag 1
Werden die Adapter nur über ZCML registriert, werden wir diese Probleme nicht haben.

```python
from zope.interface import implements
from zope.interface import Interface


class IBase(Interface):
    """
    """


class Base(object):
    """
    """
    implements(IBase)


class IAdapterTest(Interface):
    """
    """


class Child(Base):
    """
    """
    def __init__(self, obj, req):
        pass

```

```zcml
<configure xmlns="http://namespaces.zope.org/zope">

  <adapter factory=".adapters.Child"
           provides=".adapters.IAdapterTest"
           for="* *" />

</configure>

```

Da dieses Problem des öfteren auftreten wird und das Ziel dieser Umstellung u.A. auch die Vereinheitlichung sein sollte, finde ich es besser, wenn wir auf eine Variante setzten, die immer funktioniert. Deshalb schlage ich vor, dass wir die Adapter-Registrierung in Zukunft einheitlich über ZCML und nicht mehr über Decorators machen.

# Alternativer Lösungsvorschlag 2
Als Mischform, und damit man trotzdem direkt erkennt, dass es sich um einen Adapter handelt, können wir den `for`-parameter (`@adapter`) als Direktive angeben und alles weitere im ZCML.

@jone @phgross Bitte um Rückmeldung, mit welcher Variante wir fortfahren wollen.

Ich bin für eine der beiden Alternativ-Vorschläge.

**Comment by jone** [comment]
Ich denke das geht das ganze @4teamwork/gever Team etwas an 😉 

Es ist auch etwas Geschmackssache, welchen Stil wir verwenden.
Persönlich finde ich den Decorator-Stil (`@adapter`, `@implementer`) am schönsten.
Es ist aber so, dass dies die Factory beschreibt, nicht die Registrierung der Factory in der Component-Registry, daher geht dies nur wenn es nicht uneindeutig ist.

Ich fände also die Variante am besten, dass wir `@adapter` und `@implementer` verwenden, solange dies geht und aber mit einem ZCML `provides=""` eindeutig machen wenn die Decorator nicht ausreichen.

Der Nachteil einer reinen ZCML-Variante ist auch, dass die `implements`-Interfaces dann nur auf der Component-Registrierung gespeichert sind und nicht mehr auf der Factory, das heisst auf einer Subklasse wird u.U. das `implements`-Interface der Superklasse fehlen.

**Comment by phgross** [comment]
> Ich fände also die Variante am besten, dass wir @adapter und @implementer verwenden, solange dies geht und aber mit einem ZCML provides="" eindeutig machen wenn die Decorator nicht ausreichen.

👍   ZCML raised ja ein TypeError und verhindert so ein Neustart, es gibt also keine Konsequenzen welche man beim Entwickeln nicht bemerken würde und später zu Problemen führen würde.

@lukasgraf @Rotonen @deiferni Habt ihr Einwände, wäre gut wenn wir hier möglichst rasch ein Entscheid fällen könnten, damit Elio mit dem "ungroken" weiter machen kann.

**Comment by deiferni** [comment]
Mein Geschmack würde es vorziehen, wenn wir einen Stil wählen dem man immer folgen kann, also alles ins `zcml` tun. Damit wäre dann auch immer klar wo die Adapterregistrationen eines (Sub-)Packages zu finden sind. Eventuell wäre ein `adapters.zcml` ja eine Option?

Kann aber auch mit der Mischform leben falls wir uns dafür entscheiden 😉 .

**Comment by lukasgraf** [comment]
@phgross + @jone sehe das gleich, und würde darum auch die Mischform bevorzugen. Decorators solange möglich, `provides=` im ZCML nur dann wenn's nicht eindeutig ist.

**Comment by elioschmutz** [comment]
Ich sehe dabei einige Nachteile:

1. Es ist nicht einheitlich (bzw. wir haben schon jetzt ausnahmen)
2. Die Ausnahmen müssten/sollten kommentiert werden. Es werden andere Entwickler daran arbeiten und entweder den Standard nicht erkennen, sich wundern warum es manchmal anders ist oder selbst zu diesem Fehler stossen und unnötig Zeit mit debugging verlieren
3. Wenn später in einer Parent-Klasse ein Interface implementiert wird, wird die Subklasse nicht mehr funktionieren.

Den Fehler wird man sicher bemerken, wie @phgross schon gesagt hat, aber ich finde es unnötig wenn wir es im vornherein verhindern können.

**Comment by elioschmutz** [comment]
Ok. Da die Anderen auch die Mischform (alles mit `@adapter` und `@implementer` und bei ausnahmen im `zcml` als `provides` angeben) bevorzugen, werde ich damit weiterfahren.

@4teamwork/gever hat noch jemand Einwände/Hinweise/Kommentare dazu? Ansonsten werde ich heute mit dieser Variante weiterarbeiten.
