### ISSUE TITLE
Empty subdossiers are missing in a ZIP Export

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3285]
GEVER Dossier:
![bildschirmfoto_2017-08-16_um_15_08_15](https://user-images.githubusercontent.com/485755/29364779-ecdd96bc-8294-11e7-803b-6392324a807f.png)

ZIP Export:
![bildschirmfoto 2017-08-16 um 15 09 05](https://user-images.githubusercontent.com/485755/29364813-03e1022c-8295-11e7-8bc8-f26923c88453.png)

**Comment by elioschmutz** [comment]
This is a `ftw.zipexport` issue. I created a new issue in the responsible module: https://github.com/4teamwork/ftw.zipexport/issues/44

**Comment by phgross** [comment]
@elioschmutz please make a release of ftw.zipexport and create a PR which updates the pinning in the `versions.cfg` and closes this issue.
