### ISSUE TITLE
Also display mime-type icon for references

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3316]
Currently references don't display a mime-type icon. After a short discussion with @phgross we concluded that it should.

- the current link-icon is not particularly good and it looks more like an empty file but not like a link (i would expect something with an arrow or maybe link-chains)
- the mime-type icon should be well known and it displays (useful) information about the file-type in a quick memorable way

![screen shot 2017-08-28 at 08 16 50](https://user-images.githubusercontent.com/736583/29761378-4b89f272-8bc9-11e7-99b0-f4d699c768f3.png)

**Comment by phgross** [comment]
Has been implemented with a separate icon addition for referenced documents.
