### ISSUE TITLE
Rename Committee Group label, clarify intent

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3325]
The label is a bit confusing at the moment, it should state that the selected group is granted the `CommitteeResponsible` role on a committee.

- title: Gremien-Verantwortliche
- description: Diese Berechtigungsgruppe kann die Kommission bearbeiten und einsehen.

<img width="502" alt="screen shot 2017-08-29 at 12 51 24" src="https://user-images.githubusercontent.com/736583/29817585-d7726ba8-8cb8-11e7-8a21-db5ebb8a8cee.png">

**Comment by phgross** [comment]
@deiferni Vorschlag für Text mit Su besprechen.
