### ISSUE TITLE
Neue Dossiervorlagen: Schlagworte können nicht immer hinzugefügt werden

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3335]
Getestet auf DEV und Chrome: 
- Neue Dossiervorlage hinzufügen, mit Schlagwort "gurkensalat" oder ähnlich
- Dossiervorlage speichern
- Schlagwort wird nicht gespeichert

In gewissen Konstellationen funktioniert es, meistens aber nicht. Evtl. spielt es eine Rolle, ob es das Schlagwort bereits gibt oder nicht.

**Comment by phgross** [comment]
@maethu kannst du dir das ansehen? Konnte das Problem auf den neu aktualisierten DEV System reproduzieren, #3327 ist dort installiert.

![schlagworte issue](https://user-images.githubusercontent.com/485755/29912154-fbc5bbbc-8e30-11e7-8711-74d13ae8ad78.gif)

**Comment by maethu** [comment]
Schaue es heute noch an.

**Comment by maethu** [comment]
Argh sry...my bad. 
Ich habe im Release 1.3.3 durch einen Fix einen neuen Bug introduced und in 1.3.4 verpasst den zu flicken. 💸 ➡️ 🐖 


Ist nun in 1.3.6 `wirklich` behoben. 

![keywords](https://user-images.githubusercontent.com/437933/29957415-a5e6b8d2-8eed-11e7-9818-04c59eb0b88a.gif)
