### ISSUE TITLE
Css issue when adding word-proposals.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3342]
checkbox and label are not displayed on the same line.

![screen shot 2017-09-04 at 10 35 22](https://user-images.githubusercontent.com/736583/30018409-09f236dc-915d-11e7-80d9-ae1b99ffc05e.png)

**Comment by phgross** [comment]
@deiferni ist that still an Issue? Should no longer be available with SPV 2.0 ...

**Comment by phgross** [comment]
No longer an issue.
