### ISSUE TITLE
Schema-migration tracking table can't deal with orphaned upgrade

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3354]
The SchemaMigration tracking table `opengever_upgrade_version` can't handle `ftw.upgrade`s orphaned upgrade steps. It only tracks the most recent version of a profile's schema migrations. Problematic situation:

- SchemaMigration A, version 1
- SchemaMigration B, version 2

The SchemaMigration B Pull-Request is merged first. We execute the upgrades, the tracking-table version is 2. 
Then we merge Pull-Request for Schemamigration A. The upgrade is discovered by `ftw.upgrade`  but since the tracking-table version is at 2 already, the upgrade won't be installed.

Proposed changes:
Also let the tracking-table track each installed upgrade-step and not only the last version for each profile. That way it behaves the same way as `ftw.upgrade`.

**Comment by phgross** [comment]
@jone could you take a look here in the next weeks, would be great to solve this issue with the january release.
