### ISSUE TITLE
Strange/wrong encoding of search term in search box

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#336]
Can be reproduced like this:
![bildschirmfoto 2014-06-24 um 22 25 28](https://cloud.githubusercontent.com/assets/485600/3377286/db9ab95c-fbdd-11e3-85d3-942d2e577ad8.png)

Hitting return will transform the search term in a weird way:
![bildschirmfoto 2014-06-24 um 22 25 39](https://cloud.githubusercontent.com/assets/485600/3377296/efb3c730-fbdd-11e3-91e5-45c695dcc4c1.png)

**Comment by phgross** [comment]
Only reproducible with safari ...

**Comment by phgross** [comment]
In aktueller Version nicht mehr reproduzierbar, auch mit Safari nicht.
