### ISSUE TITLE
Zeilenumbrüche in E-Mail Benachrichtigung bei Aufgaben

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#3365]
Die Zeilenumbrüche sollten ebenfalls in der E-Mail Benachrichtigung bei Aufgaben sichtbar sein.

**Comment by phgross** [comment]
Die E-Mail Benachrichtigung wird im Rahmen des OGIP 29 verbessert. Wir werden diesen Punkt gleich dort angehen.
