### ISSUE TITLE
responsible_org_unit field should be Choice, not TextLine

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#3376]
The `responsible_org_unit` field of the [`IResponsibleOrgUnit` behavior](https://github.com/4teamwork/opengever.core/blob/17b1b45cea2c3560103c76a061c47698977e6d4b/opengever/repository/behaviors/responsibleorg.py#L8-L23) should be a `Choice` field (instead of `TextLine`), and be backed by a vocabulary of the available Org Units.

This would prevent invalid org unit IDs from being entered.

**Comment by Rotonen** [comment]
@lukasgraf what do we do with the already-input org unit IDs out there?

**Comment by lukasgraf** [comment]
@Rotonen we would need to sanitize those beforehand, and, if any invalid ones are found, clean those up after checking back with the customer in question.

**Comment by Rotonen** [comment]
As we're unsure as to whether or not clients need to extend this beyond the rigidly configured org units, this would need to be a `ChoicePlus` field, but as `ftw.keywordwidget` should receive a once over before we put anything else on top of that, I'm unassigning from the milestones and moving onto something else.

Ref. https://github.com/4teamwork/ftw.keywordwidget/issues/32

**Comment by lukasgraf** [comment]
This is currently such low priority that we're dropping this.
