### ISSUE TITLE
Create endpoint to generate OC officeatwork url.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3380]
The endpoint is called first and generates the oc: protocol URL with the action and with information about the second endpoint. it should be called after initiating the creation in gever with `document_from_officeatwork`. This is the first thing that needs to be done to implement a new OC action.

See 
https://github.com/4teamwork/opengever.core/blob/ad7e26d303648b6b0081682490d06898f164bb8c/opengever/officeconnector/service.py#L57-L71 for an url endpoint example.

Suggested names:
class: `OfficeConnectorOfficeAtWorkURL`
endpoint: `oaw_create_document_url`
action: `oaw_create_document`

Example payload snippet:
```json
{
  "action": "oaw_create_document",
  "url": "https://gever.example.com/plonesite/oaw_create_document",
  "document": "65429a0898b040c69ff572847e79b0dc"
}
```

**Comment by phgross** [comment]
Wird geschlossen. Siehe Begründung im Epic #3379
