### ISSUE TITLE
Create endpoint to generate OC officeatwork payload.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3381]
The endpoint to generate OC officeatwork payload is called second, after #3380, and delivers a payload with information about the action and with metadata. The file should contain:
- url to the document for OfficeConnector
- url to call when creation is aborted on the client side (`document-remove-shadow-url`)
- document-metadata, more or less equivalent to list of available doc-properties, for the document, see https://docs.onegovgever.ch/admin-manual/docproperties/list/

See https://github.com/4teamwork/opengever.core/blob/ad7e26d303648b6b0081682490d06898f164bb8c/opengever/officeconnector/service.py#L156-L185 for a payload implementation.

Suggested names:
class: `OfficeConnectorOfficeAtWorkPayload `
endpoint: `oaw_create_document`

Example payload snippet:
```json
{
    "document-url": "my.gever.ch/mysite/myrepository/mydossier/mydocument-1",
    "document-remove-shadow-url": "my.gever.ch/mysite/myrepository/mydossier/mydocument-1/remove_shadow",
    "properties": {
       "ogg.dossier.title": "Foo",
       "ogg.dossier.reference_number": "foo/12334"
    }
}

See also #3386 for how to provide contact properties.

**Comment by phgross** [comment]
Wird geschlossen. Siehe Begründung im Epic #3379
