### ISSUE TITLE
Add DELETE endpoint for shadow-state documents.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3383]
When creating a document with officeatwork the creation may fail or be aborted client-side. For that case we need a service `remove_shadow` (use the `DELETE` method) that is registered for documents and allows to remove them. The url will then be called by OfficeConnector. Thus the url to that endpoint must also be provided in #3381.

**Comment by Rotonen** [comment]
This could still be actually relevant for Oneoffixx: we probably need a way to reap stale shadow documents. Documents can end up in that state, if the chosen template is broken.
