### ISSUE TITLE
Unify table selects on the extract attachment view.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3388]
For consistency's sake the table-selects of the view to extract attachments from a mail should be normalised to look like the other selects. 
- add comma
- add total count

should look like:
![screen shot 2017-09-18 at 17 12 37](https://user-images.githubusercontent.com/736583/30549231-8d873280-9c94-11e7-94d6-78c085c0c2dd.png)

looks like:
![screen shot 2017-09-18 at 17 12 27](https://user-images.githubusercontent.com/736583/30549230-8d85aa3c-9c94-11e7-885e-a71c5ab57544.png)

**Comment by phgross** [comment]
Closed via #3715
