### ISSUE TITLE
Trash: partial reindex optimization

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3390]
When trashing and untrashing items, the complete item is reindexed:
https://github.com/4teamwork/opengever.core/blob/f12ba0274c4ce293d04656677cb6cede7f6324ba/opengever/trash/trash.py#L70
https://github.com/4teamwork/opengever.core/blob/f12ba0274c4ce293d04656677cb6cede7f6324ba/opengever/trash/trash.py#L79

I doubt that this is necessary.
This is can easily be improved by selecting the indexes which are affected by trashing, e.g. with:
```python
self.context.reindexObject(idxs=['object_provides', 'bla'], update_metadata=True)
```

1. Identify affected indexes, whitelist those indexes.
2. Inspect metadata, decide whether metadata requires updating, update code accordingly.
3. Consider extracting reindexing in order to use the same path for trashing and untrashing.

**Comment by phgross** [comment]
the indexes `trashed`, `object_provides`  should be enough
