### ISSUE TITLE
OGGBundle Import in mehreren Schritten ermöglichen. 

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3435]
Use Case: Die Migration eines neuen Mandanten soll in zwei Schritten durchgeführt werden können:
**Schritt 1**: Ordnungssystem inkl. Positionen, Dossiers inkl. Dokumente
**Schritt 2**: Restliche Dossiers inkl. Dokumente

Zurzeit kann OGGBundle keine Dossiers in ein bestehendes Ordnungssystem einfügen, deshalb sollte OGGBundle entsprechend erweitert werden.

### Variante 1:
Vor dem Import wird das OGUID-Path Mapping des `OGUIDResolvers` mit allen bereits existierenden Objekte generiert. So müssen bei Schritt 2 nur noch die neuen Inhalte des Bundles enthalten sein.

_Vorteile:_ 
 - Anpassung des Bundle Konzeptes ist überschaubar

_Nachteile:_
 - Funktioniert nur bei Container welche auch via OGGBundle erstellt wurden. OGGBundle Migrationen in ein bestehendes Ordnungssystem wären so nach wie vor nicht möglich.
 
### Variante 2:
OGGBundle wird so erweitert, dass er neben der `parent_oguid` auch eine Auflösung anhand des Aktenzeichens unterstützt. Für die Durchführung von Schritt 2, müsste demnach ein weiterer Schritt implementiert werden, der anhand der mit gelieferten Referenznummern, das entsprechende Aktenzeichen generiert.

_Vorteile:_
- OGGBundle Migrationen in ein bestehendes Ordnungssystem wären möglich.

_Nachtteile:_
- OGGBundle Import unterstützt zwei verschiedene Arten von "Parent-Pointers"
- Migrationsprozess (Transmogrifier Konfiguration) wird komplexer

@lukasgraf Ich persönliche tendiere zu Variante2, wie siehst du das? Siehst du noch bessere Varianten oder mögliche Stolpersteine bei der Umsetzung?

**Comment by lukasgraf** [comment]
@phgross Ich glaube nicht, dass Variante 1 so viel einfacher zu implementieren ist - die Anpassungen wären ungefähr die gleichen, nur was als Key für den neuen Parent-Pointer verwendet wird ist anders. Ich würde daher auch zur Variante 2 tendieren.

Unabhängig davon welche Variante wir wählen, wird es zentral sein, dass der Lookup vom Newstyle-Parent-Pointer eines Items auf das Parent-Plone-Objekt effizent gemacht werden kann. Dies bedeutet, dass z.B. das Aktenzeichen auf eine Art und Weise indexiert sein muss, dass wir mit den Infos aus dem zweiten Bundle zuverlässig danach querien können.

Eine theoretische Alternative ohne Indexierung wäre evtl., zuerst alle Ordnungspositionen in ein Mapping Aktenzeichen -> Physical Path abzufüllen.

Schlussendlich müsste die Logik hier durch etwas ersetzt werden, das das Bundle nach dem Physical Path eines Items aufgrund des Aktenzeichens fragt:
https://github.com/4teamwork/opengever.core/blob/e8a532fe812fb066b15f03a5967d6cc27ab13909/opengever/bundle/sections/constructor.py#L122-L125

**Comment by phgross** [comment]
Wurde mit #3511 und #3536 #3538 umgesetzt.
