### ISSUE TITLE
Attach to outlook action not working on inbox documents listing

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3443]
![bildschirmfoto 2017-09-28 um 09 16 01](https://user-images.githubusercontent.com/485755/30953819-dcad246e-a42d-11e7-9a5b-ceef1609bceb.png)

The action raises an JS error.

**Comment by tarnap** [comment]
There was a service missing for the inbox. A default has been implemented to avoid further errors.

![no_error_message](https://user-images.githubusercontent.com/194114/31652769-946bd0d6-b320-11e7-806e-730886d10c0e.gif)
