### ISSUE TITLE
Editing lock prevents from checkout

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3445]
*Problem:*
When a document has an edit-lock owned by the current user, it is not allowed to checkout. This leads to strange behavior:
1. the checkout-action may be visible, even though the user is not allowed to use it (caching?)
2. the user has no visual feedback that he/she has an edit-lock on the document, thus unable to resolve the problem of not beeing able to checkout.

*Reproduction:*
- Go to a document
- Click on "Edit", but do not save nor cancel
- Click on the document in the pathbar, navigating back without releasing the edit-lock

Problem 1: the checkout action is still visible:
![bildschirmfoto 2017-09-28 um 09 32 36](https://user-images.githubusercontent.com/7469/30954456-87061acc-a430-11e7-8b2a-da7c5835986e.png)
I suspect a caching problem: the edit-lock is not part of the cache key.

- Click on checkout

Problem 2: it's not possible to checkout, but the user does not know why because we don't tell the user that there is an unreleased edit-lock:
![bildschirmfoto 2017-09-28 um 09 32 45](https://user-images.githubusercontent.com/7469/30954496-ae1d9b4e-a430-11e7-84a6-a54dc1eef9e8.png)
(the checkout action disappears at this point because the statusmessage causes a cache key invalidation, I guess)

**Comment by phgross** [comment]
Wird mit #3478  gelöst werden.

**Comment by Rotonen** [comment]
Already closed by https://github.com/4teamwork/opengever.core/issues/3478
