### ISSUE TITLE
Breadcrumb: 1 Element soll wegfallen

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3449]
Das erste Element bei der klickbaren Breadcrumb soll bei 1-Admin-Unit Sites mit nur einem Mandant oder bei nur Virtuellen Mandanten weggenommen werden. Siehe auch: https://feedback.onegovgever.ch/t/breadcrumb-path-brotkruemelpfad-visuell-aufwerten/547/21

**Comment by phgross** [comment]
@tarnap bitte umsetzen:

hint:
```python
opengever.ogds.base.utils import ogds_service
ogds_service().has_multiple_admin_units()
```

**Comment by tarnap** [comment]
# Setup with multiple admin units

![multiple_admin_unit_ordnungssystem](https://user-images.githubusercontent.com/194114/31336142-da6d5766-acf5-11e7-990d-6a0af65d4352.png)
![multiple_admin_unit_root](https://user-images.githubusercontent.com/194114/31336143-da88e92c-acf5-11e7-9b81-1386cf352bf1.png)

# Setup with single admin unit

![single_admin_unit_ordnungssystem](https://user-images.githubusercontent.com/194114/31336145-da9ba0ee-acf5-11e7-9761-4ff0a7f726c1.png)
![single_admin_unit_root](https://user-images.githubusercontent.com/194114/31336144-da968c9e-acf5-11e7-8608-6c72618d75e0.png)

**Comment by livschal** [comment]
@phgross können das die Kunden die es betrifft ab dem nächsten Release beziehen oder ab sofort? (damit ichs korrekt im FF poste...)

**Comment by phgross** [comment]
@livschal die Anpassung ist im nächsten Release enthalten und nicht konfigurierbar.
