### ISSUE TITLE
Überlauf von Texten bei Aufgaben

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3450]
Lange Texte in Aufgaben brechen nicht um:

![c1267d0c0e8e4fc983328bafb48a6203f2681729](https://user-images.githubusercontent.com/20790360/31004403-897a4ed0-a4f4-11e7-82e0-3f5944fafa44.png)

https://feedback.onegovgever.ch/t/ueberlauf-von-texten-in-aufgaben/719

**Comment by tarnap** [comment]
`nowrap` (unten rechts) führt dazu, dass es keine Zeilenumbrüche gibt.

![this_is_breaking_the_whitespace_wrap](https://user-images.githubusercontent.com/194114/31131407-623dd134-a85a-11e7-9ad3-889bd57d075e.png)

**Comment by livschal** [comment]
@tarnap so wie im bild finde ich in ordnung. verstehe jedoch nicht ganz wie du meinst "bündig zu sich selbst"?

**Comment by tarnap** [comment]
@livschal: Ich mache ein screenshot der beiden Varianten, dann verstehst du was ich meine.

**Comment by livschal** [comment]
gemäss Input @phgross bitte erstere Variante umsetzen. danke @tarnap !
