### ISSUE TITLE
i18n tripwire glob doesn't cover packages with three components

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#3458]
This glob doesn't cover package structures deeper than two packages deep:

https://github.com/4teamwork/opengever.core/blob/e8a532fe812fb066b15f03a5967d6cc27ab13909/test-i18n-de.cfg#L49-L50

So packages like `opengever/ogds/base` or `opengever/portlets/tree` aren't matched.

**Comment by lukasgraf** [comment]
Should set `globalstar` shell option (add `shopt -u globstar` to top of the script)

**Comment by phgross** [comment]
@Rotonen please update on occasion
