### ISSUE TITLE
Fehler bei Anzeige der Anträge in Dossiers

### ISSUE THREAD

**Issue by fguyer** [4teamwork/opengever.core#3468]
Unter dem Reiter "Anträge"  (In beliebigen Dossiers) lädt und lädt die Seite ohne Ergebnisse zurück zu geben. Problem lässt sich lösen in dem man via dem Zahnrädchen die Tabellenkonfiguration zurücksetzt.

Für weitere Infos siehe: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3581/

**Comment by phgross** [comment]
Der Fehler tritt aufgrund einer "outdateden" Tabellenkonfiguration im `ftw.dictstorage` auf. Der SQLTableSource sollte diesbezüglich robuster werden.

Bevor das sort_on attribute für die Sortierung verwendet wird, sollte überprüft werden ob überhaupt ein solche Spalte existiert (siehe https://github.com/4teamwork/opengever.core/blob/master/opengever/tabbedview/sqlsource.py#L52)

@tarnap
