### ISSUE TITLE
Check for unused PostgreSQL sequences

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#3477]
It seems the Sequence `proposal_history_id_seq` is only ever added in an upgrade step, but not used/created any more on a new install.

This sequence, and maybe others, should probably be removed via an upgrade-step.

**Comment by Rotonen** [comment]
Didn't we agree we'll not chase minor database cruft accumulation at this point? Or why is this open, assigned and on the next milestone again?

**Comment by deiferni** [comment]
to answer your question
