### ISSUE TITLE
Warnung bei Check-In eines Dokuments wenn es noch ein WebDav-Lock gibt

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#3478]
Wenn ein Benutzer ein Dokument mit Office Connector bearbeitet, so kann er das Dokument immer noch manuell einchecken. Mach er dies, so ist das Lock dann kaputt und muss vom Administrator aufgelöst werden.

Um dies zu verhindern, solle eine Warnung erscheinen wenn ein Benutzer ein Dokument einchecken möchte, welches noch durch einen WebDav-Lock geschützt ist. 

Bei Einchecken mit Kommentar erscheint zwar eine Warnung, jedoch zu wenig aussagekräftig.
 
Bei Einchecken OHNE Kommentar erschien KEINE Warnung, was dann zum angesprochenen Problem führt

![mein brief finanzdirektion fd spv](https://user-images.githubusercontent.com/1231822/31267966-9001920a-aa7a-11e7-85f7-6197820a88c5.png)

**Comment by buchi** [comment]
@Rotonen Could you look at this one asap?

**Comment by Rotonen** [comment]
Bumped this to be next up in my queue.

**Comment by bbuehlmann** [comment]
![checkin fixes](https://user-images.githubusercontent.com/1231822/33170187-afdbd3ea-d047-11e7-9f33-a7f1e4850b64.png)

![checkin fixes 1](https://user-images.githubusercontent.com/1231822/33170191-b28dffd2-d047-11e7-9159-c7100bfd7874.png)

![checkin fixes 2](https://user-images.githubusercontent.com/1231822/33170193-b4ca72b2-d047-11e7-8012-9ac0f39b8dc0.png)

**Comment by buchi** [comment]
@4teamwork/gever 
PING! Dieses Issue ist extrem dringend!!! Wir haben immer wieder Supportfälle wegen dem. Der Benutzer kann diese Situation nicht selbständig lösen.
