### ISSUE TITLE
Neue Rolle Dossier-Verwalter

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#3490]
- [x] Neue Rolle `Dossier-Verwalter` erstellen
- [x] Neue Berechtigung `Dossier schützen` erstellen
- [x] Darstellen der neuen Rolle im Freigabe-Tab (+ Info)
- [x] `Dossier-Verwalter` erhält Berichtigung `Dossier schützen` wenn Ordnungsposition im Status `Aktiv` ist

**Comment by elioschmutz** [comment]
@phgross Ist das korrekt, dass die Rolle `Dossier-Verwalter` auf folgenden Inhaltstypen vergeben werden kann?:

- Repo-Root
- Repo
- Dossier

Oder soll die Rollenvergabe auf Stufe `Dossier` unterbunden werden?

**Comment by phgross** [comment]
Ich würde die Vergabe der Rolle `Dossier-Verwalter` auf Stufe Dossier unterbinden.
