### ISSUE TITLE
Doc Properties seem outdated

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3547]
I suspect that the doc properties are not always updated correctly:
- Given a document titled "Foo", which is a word document with a doc property showing the title "Foo"
- I copy the document in Plone, resulting in a new document titled "copy of Foo"
- I edit the metadata of the document and change the title to "Bar"
- I checkout and office-connect the document
- The doc property has still the content "copy of Foo", even when I update the doc properties manuall (contextmenu); I would have expected it to be "Bar"
- When I checkin the document, then checkout and edit again, the property is updated to "Bar"

Configuration:
- The office-connector-checkout-feature is enabled (gever.4teamwork.ch).

Thoughts:
- It may be that the oc-checkout doesn't update the properties correctly before downloading the document (to be proofed).

⚠️ I didn't play this exact scenario through; it's more an interpretation of my experience.

**Comment by Rotonen** [comment]
I'll grab this as this is relevant to the polish of the GEVER side Office Connector stack related to the implementation of the officeatwork features. Good catch.

Office connector currently uses a form for uploading, so should that not actually take care of all this?

**Comment by deiferni** [comment]
@Rotonen the current implementation to update doc properties is event handler based on checkout/checkin of the document IIRC.

**Comment by Rotonen** [comment]
Office Connector uses the normal checkin endpoint currently. I'm in the process of porting the API / user story tests to our integration test stack so it'll be easier to tackle this after that by adding the relevant assertion.

**Comment by jone** [comment]
@Rotonen I have the impression that it works well on checkin, but it does not on checkout. So uploading isn't the issue (it actually fixes the problem).

**Comment by Rotonen** [comment]
@jone so the metadata edit form does not do what it is supposed to do? IMO checking out should not update or reindex anything, but check out whatever is currently stored as-is.

**Comment by jone** [comment]
@Rotonen that's an design decision; I think that it was done on checkout time and not on metadata save time up to now.
I think it isn't that bad that it is done on checkout, because we must expect that things are updated (e.g. new title) without firing the event handlers, because we often forget to properly fire a modified event in scripts, upgrade steps, etc.

**Comment by phgross** [comment]
Duplikat von #3692
