### ISSUE TITLE
Private Dossiers status `storniert` entfernen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3570]
Todos: 
 - Status inkl. Transitions entfernen aus 
 - Upgradestep für bestehende stornierte Inhalte
 - Upgradestep für Workflow Änderung

**Comment by tarnap** [comment]
# TODO

- Remove the "Stornieren" action
![stornieren_action_is_displayed](https://user-images.githubusercontent.com/194114/32726639-edc38822-c879-11e7-983b-0efcdcc5ecf5.png)

**Comment by tarnap** [comment]
Upgrade Step:
![upgrade state vom inactive to active](https://user-images.githubusercontent.com/194114/32733593-fdfac0e6-c88f-11e7-874e-303beefe9dd6.gif)
