### ISSUE TITLE
Create initial content for meeting word feature

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3603]
We don't have initial content for the meeting-word feature yet. So whenever a developer creates a new plone site for development she has to create that content manually. 

We should create word-meeting intitial content in `opengever.examplecontent`. 
The following is a non-exhaustive list of what should be amended:

- at least one proposal template to create new proposals
- committee container has required templates (proposal templates and sablon templates) that are needed, create and link those
- some word-proposals
- maybe re-purpose an existing committee for the word feature and put some submitted word proposals into that committee
- create at least one meeting in aforementioned commitee and add proposal based and also ad-hoc agenda items
- …

**Comment by tarnap** [comment]
So much for linked templates:
![linked_templates](https://user-images.githubusercontent.com/194114/33012786-3b1f4fda-cde2-11e7-9cdf-e081ae3daac6.png)

**Comment by tarnap** [comment]
@deiferni: You want me to add a paragraph as well, don't you?

**Comment by tarnap** [comment]
@deiferni: mhh... how do I add schedule ad-hoc agenda items in the example content? https://github.com/4teamwork/opengever.core/blob/b0ca6aa6558c3e3025acea2247bc79a276e82a96/opengever/meeting/model/meeting.py#L427

**Comment by deiferni** [comment]
@tarnap yes thank you!

i would suggest to enable the word-meeting feature for development, we will get rid of the old implementation soon, so having word enabled should be the default in any case. this will also solve your problem with the initial content, you can simply use `schedule_ad_hoc`.
