### ISSUE TITLE
Listing the members of an empty group on a dossier sharing tab fails

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3605]
There should probably be some empty iterable or none guard in there.

Clicking on 'Angemeldete Benutzer' in our local dev content triggers this.

**Comment by phgross** [comment]
@tarnap Please add a fallback to the `list_groupmembers` view, when the given groupid does not exist. Display a message like `Gruppe "gruppe_die_es_nicht_gibt" konnte nicht gefunden werden.`

**Comment by tarnap** [comment]
Is this what you see?
![empty_group_bug](https://user-images.githubusercontent.com/194114/34712267-864169c8-f522-11e7-8cfb-d5dfea6a233b.png)
