### ISSUE TITLE
Add view and button to revive the bumblebee preview.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3619]
Sometimes creating a bumblebee preview image/thumbnail/overlay image fails and in rare circumstances this leaves bumblebee in an inconsistent state (GEVER-side). Also due to a bug some cached bumblebee document checksums may not be up to date, see https://github.com/4teamwork/opengever.core/pull/3617 for example. It also may happen that the bumblebee service is down temporarily and the documents can't be registered.

At the moment these documents won't show a preview until the document is modified and thus triggers a bumblebee update. 

We would like to add a button to "revive" the preview as a stop-gap measure so that an `Administrator` or `Manager` can attempt to reset bumblebee state and make sure a preview image is rendered again.

"reviving" should perform the following actions:
- re-calculate bumblebee checksum
- store in bumblebee

can most likely be implemented by using something from`IBumblebeeDocument`.

**Comment by phgross** [comment]
@tarnap please add the action and browserview, should look like this:

<img width="864" alt="bildschirmfoto_2017-11-20_um_08_00_17" src="https://user-images.githubusercontent.com/485755/33006009-efc29740-cdc8-11e7-9ffb-2cc2f31a3346.png">
