### ISSUE TITLE
"Fehler" in der Dokumentation von Teamaufgaben

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3636]
In der Dokumentation der Teaumaufgaben steht:
> Mittels den Teamaufgaben können Aufgaben an AD-Gruppen adressiert werden. Dazu wird die AD-Gruppe vom Administrator als Team in OneGov GEVER erfasst und entsprechend benennt.

Das stimmt so nicht ganz. Teams können nur von Managern, also von 4teamwork erstellt werden. Das ganze soll via Service Request funktionieren.

**Comment by livschal** [comment]
done: https://github.com/4teamwork/opengever.core/pull/3648 @phgross
