### ISSUE TITLE
Auschecken und Bearbeiten nur bei unterstützen Dokumentformaten

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#3665]
Zur Zeit wird der "Auschecken/Bearbeiten" Knopf bei allen Dokumentformaten dargestellt.
Das macht keinen Sinn, weil die Bearbeitung in Office Connector nur mit bestimmten Formaten/Programmen funktioniert.

**Comment by phgross** [comment]
Vorschlag: 
 - [ ] Registry Setting mit einer Liste von unterstützten contentTypes
 - [ ] Falls Registry Eintrag nicht supported wird soll die Aktion grau erscheinen, aber mit einem zusätzlichen Info versehen sein. z.B. mit einem kleinen Icon mit genauen Tooltip Beschreibung `Dieses Dokumentformat wird vom Office Connector nicht unterstützt und kann deshalb nicht direkt bearbeitet werden.`
 - [ ] Stattdessen soll die Aktion `Auschecken` angeboten werden.

**Comment by phgross** [comment]
@njohner Bitte entsprechend umsetzen.

**Comment by njohner** [comment]
My bad, this issue should not have been closed by the merge in `plonetheme.teamraum`.
