### ISSUE TITLE
Extend OGGBundle with additional property for `dossier_manager` permission

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3672]
Similar we did for the excel import (see #3652) also the OGGBundle should be extended for repositoryfolders and dossiers.

**Comment by elioschmutz** [comment]
@phgross should it be possible to set the `reading` and `reading_and_writing` fields of a dossier, too? In other words, should it be possible to protect a dossier through the bundler or only to set the `DossierManager`-role?

**Comment by phgross** [comment]
No, for now setting the `DossierManager` is enough ...
