### ISSUE TITLE
Doc properties not updated on checkout.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3692]
**preconditions**
- the registry setting `opengever.officeconnector.interfaces.IOfficeConnectorSettings.direct_checkout_and_edit_enabled` is `True`
- the registry setting `opengever.dossier.interfaces.ITemplateFolderProperties.create_doc_properties` is `True`

**steps to reproduce the problem**
- create a dossier
- create a document from template in that dossier, template must have doc-properties, use e.g. "Allgemeine Word-Vorlage mit Metadaten" from example-content (if you edit locally, make sure document is checked-in before proceeding to next step)
- rename dossier that contains the document
- checkout document again
- view document doc-properties of document in word, `ogg.dossier.title` is still set to the old dossier title

**expected outcome**

doc-property `ogg.dossier.title` in word should be set to the new dossier title.

`ogg.dossier.title` is just an example, the problem exists for all doc-properties.
 
**suspected cause**

the doc-properties may be updated too late i.e. after the document is downloaded. the journal entry that indicates that doc-properties are updated shows up after the checkout journal entry.

**Comment by elioschmutz** [comment]
@deiferni This is what happens behind the scenes:

Analysis
======
1. The officeconnector downloads the document (https://github.com/4teamwork/OfficeConnector/blob/b281b10638234504ff8e014441e4a5b7212b160f/officeconnector/controller.py#L217)
2. After downloading it, the officeconnector will checkout the documents (https://github.com/4teamwork/OfficeConnector/blob/b281b10638234504ff8e014441e4a5b7212b160f/officeconnector/controller.py#L257)

In step 2, the docproperties gets updated
=> https://github.com/4teamwork/opengever.core/blob/master/opengever/document/handlers.py#L9 triggered by the `ObjectCheckedOut` event in https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L102

This behavior would explain why we get old docproperties. But fixing the order in the officeconnector would not solve all the problems. The same issue occurs if you download a copy of the document. The `download`-view will be used for both, the "download a copy" action and also from the office-connector to download documents:
https://github.com/4teamwork/opengever.core/blob/2a020e31b827006ac11708fdaddd3b608e6d7fa8/opengever/document/browser/download.py#L24
But this view does not update the doc-properties.

Solution
======
In my opinion, we should fix the issue in the download-view.

But I think, just updating the doc-properties in this view will cause another issue.
- What, if a user has no edit-permission on the document?
  - Should I update the doc-properties within a security-manager with edit-permission?
  - Or can it be dangerous in some cases?
  - Or is it better to just update the properties if the user has the required permission?

Question
=======
@deiferni 

1. Do you agree with my solution?
2. What do you think about the user-permission problem

**Comment by deiferni** [comment]
@elioschmutz thanks for the detailed analysis!

1. no 😉 

i think the problem is that officeconnector performs these actions in the wrong order. i would expect the following to happen:

- checkout
- doc-property-update
- download

the download-view (the one that is also exposed as "Kopie herunterladen") must not change the file itself (it is a GET request). 

after a brief discussion with @buchi we think that this problem should be tackled on the office-connector side, so this issue does not required further action for now.

**Comment by elioschmutz** [comment]
@deiferni 👍

**Comment by Rotonen** [comment]
@elioschmutz thank you, well dug up.
