### ISSUE TITLE
Responsible should be required when delegating tasks.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3713]
When delegating tasks one or more responsibles can be selected. The responsible field is `required` according to the schema definition and thus also styled as required in the UI:

![screen shot 2017-12-01 at 11 30 06](https://user-images.githubusercontent.com/736583/33478852-02fb46c0-d68b-11e7-9bed-318b090d12ed.png)

However i can proceed without selecting a delegate. When i submit the next form i will create no subtasks and therefore not actually delegate the task. ![screen shot 2017-12-01 at 11 30 45](https://user-images.githubusercontent.com/736583/33478873-1bbbee94-d68b-11e7-826c-ab8c861bcd99.png)

Steps to reproduce:
- create a task
- accept the task
- hit the delegate button (the `@@delegate_recipients` view/form will open)
- press next 

Actual outcome:
- the wizard will proceed to step 2 (`@@delegate_metadata` view/form is rendered)

Expected behaviour:
- validation error, at least one responsible should be selected

**Comment by phgross** [comment]
Closed via #3812
