### ISSUE TITLE
Allow Admins (and Managers) to unlock documents locked by webdav.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3716]
This is a recurring support issue. At the moment solving this issue also includes a developer, which must perform the unlock. This is time-consuming and unnecessary.

We want to improve this situation and allow an `Administrator` (and `Manager`) to unlock a document. The `Administrator` is usually the person that decides if the unlock is justified (e.g. when a user left for holidays and forgot close officeconnector and checkin the document) and then opens the support issue.

A `WebDAV` locked document should be unlockable (for `Administrator` and `Manager`) just the same way as the document is unlockable when another user opens the `Edit medatata` view on a document:
![screen shot 2017-12-01 at 13 49 35](https://user-images.githubusercontent.com/736583/33483545-99c2d4b6-d69e-11e7-9ce6-896f8e5e0c2c.png)

For documentation purposes a short description of the current unlock process:
- create a locked document, checkout and edit the document, and keep officeconnector open.
- officeconnector will create a `WebDAV` lock. you should see the following info messages on the document overview:
![screen_shot_2017-12-01_at_12_32_36](https://user-images.githubusercontent.com/736583/33482255-6df4c930-d698-11e7-8f42-fa2a1900dcf5.png) The marked messages is the one displayed for the `WebDAV` lock.
- to force-unlock the `WebDAV` a `Manager` must open the **Zope** control panel, then navigate to `/Control_Panel/DavLocks/manage_main`
- in the form fill in the path relative to zope for the document's **parent**, e.g. `/fd/ordnungssystem/fuehrung/kommunikation/allgemeines/dossier-1/` and submit
- the lock can then be removed in the following form:
![screen shot 2017-12-01 at 13 38 35](https://user-images.githubusercontent.com/736583/33483197-f5c50a60-d69c-11e7-8f93-c305dda58459.png)

**Comment by lukasgraf** [comment]
Also note that we already have a `@@lock_maintenance` view in `opengever.maintenance`.

This could probably be fleshed out.

**Comment by njohner** [comment]
from @deiferni 
as discussed
- verify that both checkin views (with and without comment) remove the locks
- verify that this behavior is tested
- make sure that forcing checkin (checking in documens checked out by other users) is based on the `opengever.document: Force Checkin` permission
- actions in the file action button listing should check if they are still executable
- make sure that the (force) checkin action is also visible in the file action button listing:

<img width="1001" alt="screen shot 2018-02-27 at 13 30 05" src="https://user-images.githubusercontent.com/736583/36728908-a7c6eeee-1bc2-11e8-9e6b-1c7b6d61cbd7.png">

**Comment by deiferni** [comment]
As just discossed, we're gonna implement this anyway but bump it to `2018.3` as the more urgent parts are covered by https://github.com/4teamwork/opengever.core/pull/4040.
