### ISSUE TITLE
Port content stats, indexer tests etc. prone-for-fixture-failures tests to functional tests

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3726]
Any tests which break as an unintended side effect of volatility of touching the the integration test fixtures should be ported to funcional tests to stay out of the way.

There are at least a few content stats tests and a few indexer tests peppered around which would be nice to catch.

Ref. https://github.com/4teamwork/opengever.core/pull/3725 for a fine example.

**Comment by Rotonen** [comment]
@phgross FYI I took the liberty of initiative here before @njohner gets frustrated with this particular one.

**Comment by njohner** [comment]
Two other cases that should be made more robust against fixture changes. 
Thanks @Rotonen  

https://github.com/4teamwork/opengever.core/blob/master/opengever/bumblebee/tests/test_overlay_adapter_mail.py#L68

https://github.com/4teamwork/opengever.core/blob/master/opengever/mail/tests/test_indexers.py#L41

**Comment by Rotonen** [comment]
@phgross @njohner am I to coach / collaborate / hijack the branch here?

**Comment by njohner** [comment]
I am just working on other things these days, as this did not look too urgent to me...

**Comment by Rotonen** [comment]
So I'll just hijack this sometime in January.

**Comment by njohner** [comment]
@Rotonen 
I'm jobless just now so I'll start porting these

**Comment by njohner** [comment]
I think the fixture is pretty stable now, and we've ported most tests to the integration layer, so do we still want to port these tests back to the functional layer?

**Comment by Rotonen** [comment]
Once we get the sequential runs and sequential runs of all modules to work again, I have a helper script for shortcutting this locally a bit.

```
function list-gever-modules {
	for package in opengever plonetheme
	do
		for module in "$package"/*/
		do
			echo "$package"."$(basename "$module")"
		done
	done
}

function amend-gever-fixture {
	for module in $(list-gever-modules)
	do
		until bin/test -x --layer integration -m "$module"
		do
			read -r -p 'Fix the failure above and press Enter.'
		done
	done
}

function test-gever-modules {
	for module in $(list-gever-modules)
	do
		until bin/test -x -m "$module"
		do
			read -r -p 'Fix the failure above and press Enter.'
		done
	done
}
```

So yes, this one is obsolete at this point.
