### ISSUE TITLE
🚧 Workspace in default content

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/opengever.core#3747]
As @deiferni said, we should probably add the new workspace content to the plone site root by default. 

This requeires an upgrade step, which we will not yet implement while the new feature is not yet finished. 

Once the feature is finished and completely implemented, we should discuss adding it to the default content.

**Comment by jone** [comment]
@raphael-s The examplecontent is only used for development. The root should only be added to a production site on purpose manually. We should not do that in an uprade step.

**Comment by deiferni** [comment]
@jone we currently have the strategy (with the exception of `opengever.meeting`) to always add roots, but then make them invisible by setting the permissions accordingly. This has the following advantages:

- Have homogenous deployements
- Makes activating the feature easier as one does not have to think about creating required content for the feature to work

we don't need to do this now, but should think about it eventually. that what iirc this ticket is for 😉 .

**Comment by jone** [comment]
Sure, lets keep this Issue open.
🚧 We are not yet sure if we suggest to use the workspace feater in the regular GEVER-installations or in standalone installations. Therefore I'd like to wait with that until we have a reasonable decision :wink.

**Comment by Rotonen** [comment]
No discussion has surfaced.
