### ISSUE TITLE
OGIP 17: Icons for workspace content types

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/opengever.core#3750]
# New icons
We need icons for the content types introduced in the workspace feature.
- WorkspaceRoot --> Fontawesome `project-diagramm`
- Workspace --> Fontawesome `project-diagram`
- WorkspaceFolder --> Fontawesome `folder-open`

# Font Awesome update
The `project-diagamm` ist not available in Version 4.5. It was introduced in version 5.0.13.
Fontawesome needs to be updated.

# Documentation
Also the README has no documentation about the icons.
- [ ] There was some documentation in the plonetheme.teamraum README, which needs to be merged into the GEVER README.
- [ ] Add documentation on how to add further fontawesome icons

**Comment by tarnap** [comment]
Updating to FontAwesome 5.0.13 was not possible after 4 hours of work.
Many Icons are not available anymore in the free Version of Fontawesome.

**Comment by phgross** [comment]
Wurde mit #4669 umgesetzt
