### ISSUE TITLE
Teamaufgaben/Teams: Inaktive Checkbox wird bei der Bearbeitung eines Teams automatisch auf aktiv gesetzt

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#3751]
- Wenn ein bestehendes inaktives Team bearbeitet wird, setzt es automatisch die Checkbox auf aktiv.

- Dies habe ich auf https:geverelearning.sg.ch festgestellt.

- Leider konnte ich auf unseren Test-Systemen kein Printscreen erstellen, da ich über zu wenig Berechtigung verfüge um ein Team bearbeiten zu können.

**Comment by jounsiboss** [comment]
https://dev.onegovgever.ch/fd/kontakte#teams

**Comment by phgross** [comment]
@deiferni any idea why it's necessary to re-update the widgets after injecting data (see https://github.com/4teamwork/opengever.core/blob/master/opengever/base/browser/modelforms.py#L98-L100)?

As far as I See this triggers again a value getting by `z3c.form.widget.update` which overwrites the injected value with the default or missing value.

**Comment by deiferni** [comment]
@phgross this should not happen, if that is indeed the case. If i remember correctly the widget that renders dropdown selects did not update the selected value correctly. we may need to improve the implementation though, maybe overriding `extract` would be the way to go.
