### ISSUE TITLE
Meeting Zip Export action with a json containing the meeting's structure

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#3752]
## Purpose:
Exporting a meeting to (for instance) _grimlock_.

## Proposed solution:
The "Als Zip-Datei exportieren" action can be extended (subclassed).

<img width="1767" alt="screen shot 2017-12-08 at 10 07 11" src="https://user-images.githubusercontent.com/194114/33758840-4fc38c36-dc00-11e7-804f-0c94c487db74.png">

In addition to the files of the meeting, a `json` shall be included, which contains the meetings metadata and structure.

**Comment by tarnap** [comment]
Draft of the `json` generated by the Zip-Export action:

``` json
{
    "committee": "<pk>",
    "concluded": "<date>",
    "location": "<location>",
    "start": "<date>",
    "agenda_items": [
        {
            "title": "<title>",
            "number": "<number>",
            "proposal": "<filename>",
            "attachments": [
                {
                    "title": "<title>",
                    "file": "<filename>",
                },
            ],
        },
        ...
    ],
    "proto:col": "<filename>",
}
```

**Comment by tarnap** [comment]
# Open questions

## Committee reference on serialized meeting
When serializing the meeting, one could think of adding a reference to the committee.
This reference could be the committee's name or it's database primary key.

This following situations need to be discussed:
- There are several committees with the same title -> title cannot be used as unique identifier
- Meetings are imported from several clients (Mandanten) -> the primary key cannot be used as unique identifier

A possible solution is to import the meeting on a view related to the committee the meeting belongs to.
In that case we don't need to export the committee's identifier to resolve the meeting relation.
This might lead to user errors (the meeting is imported into a wrong committee).

**Comment by jone** [comment]
- The "oguid" is unique over all admin units (clients).
- I would also include the meeting title.
Otherwise it looks good 👍

**Comment by tarnap** [comment]
## Required

Additionally to the metadata defined before, a link to the bumblebee preview is required.

**Comment by tarnap** [comment]
This is a WIP
Check current state in: 
https://github.com/4teamwork/opengever.core/tree/pv-add_json_to_export_action
