### ISSUE TITLE
Datumseingabe im Format 1.10.17 ist nicht möglich

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3757]
Mit dem aktuellen Datumswidget ist es offenbar nicht möglich, obiges Datum zu erfassen - das Widget verhält sich hier seltsam.

Details hier: 
https://basecamp.com/2768704/projects/13732725/todos/326333397

**Comment by bierik** [comment]
@phabegger Ich habe keinen Zugriff auf obige Basecamp URL.

**Comment by deiferni** [comment]
May be a duplicate of https://github.com/4teamwork/opengever.core/issues/3757

**Comment by deiferni** [comment]
Confirmed, closing as a duplicate of https://github.com/4teamwork/opengever.core/issues/4020.
