### ISSUE TITLE
Statustext beim Kopieren von Objekten anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3758]
Nach dem Kopieren eines Elementes wird dem Benutzer die Meldung "Die selektierten Objekte wurden kopiert." angezeigt.

Dies ist für die Benutzer nicht ganz klar. Besser wäre zB. "Die selektierten Objekte wurden in die Zwischenablage kopiert"

**Comment by phgross** [comment]
Closed via #3821
