### ISSUE TITLE
Zip-Export: Antragsdokumente fehlen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3765]
<a href="https://github.com/bbuehlmann"><img src="https://avatars1.githubusercontent.com/u/1231822?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [bbuehlmann](https://github.com/bbuehlmann)**
_Tuesday Nov 28, 2017 at 11:00 GMT_
_Originally opened as https://github.com/4teamwork/gever/issues/164_

----

Wenn ich ein Zip-Export einer Sitzung mache, so erwarte ich, dass auch alle Antragsdokumente exportiert werden. Je nach Anwendungsfall möchte ich pro Traktandum einen Ordner haben oder nur das Protokoll. Es wäre deshalb praktisch, wenn bei Zip-Export jeweils die ganze Struktur exportiert wird.

Beispiel ist hier: https://spv.onegovgever.ch/sitzungen/committee-7/meeting-130/view

Hier erwarte ich, dass die Antragsdokumente auch exportiert werden. Es werden jedoch nur die Traktandenliste sowie das Protokoll exportiert.

**Comment by deiferni** [comment]
<a href="https://github.com/bbuehlmann"><img src="https://avatars1.githubusercontent.com/u/1231822?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bbuehlmann](https://github.com/bbuehlmann)**
_Tuesday Nov 28, 2017 at 13:02 GMT_

----

Jetzt funktioniert es plötzlich??

**Comment by deiferni** [comment]
<a href="https://github.com/jone"><img src="https://avatars3.githubusercontent.com/u/7469?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jone](https://github.com/jone)**
_Tuesday Nov 28, 2017 at 13:18 GMT_

----

@bbuehlmann kann es sein dass es bei Ad-Hoc-Traktanden funktioniert aber nicht bei Traktanden aus Anträgen? Oder Umgekehrt?

**Comment by deiferni** [comment]
<a href="https://github.com/bbuehlmann"><img src="https://avatars1.githubusercontent.com/u/1231822?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bbuehlmann](https://github.com/bbuehlmann)**
_Tuesday Nov 28, 2017 at 13:28 GMT_

----

Ja genau, offenbar funktioniert es mit Ad-Hoc Traktanden nicht. Siehe hier: 

https://spv.onegovgever.ch/sitzungen/committee-7/meeting-132/view

**Comment by tarnap** [comment]
Gelöst mit https://github.com/4teamwork/opengever.core/pull/3867/commits/d4e31fec627f86f50d9927e81de0dfdfbb4ef06e
