### ISSUE TITLE
Zwischentitel/Abschnitte nicht immer neu erfassen.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3766]
Abschnitte müssen im Moment für jede Sitzung immer neu erfasst werden.

Es besteht der Wunsch diese z.B. von einer vorherigen Sitzung, Sitzungs-Vorlage zu übernehmen

Weitere Plone-Inhalte sollen hinzugefügt werden: `MeetingTemplate`, `ParagraphTemplate`.

`MeetingTemplate` beinhaltet eine Liste von `ParagraphTemplate`s.

# Sitzungsvolagen

Dieser ist in den Vorlagen zu erfassen:
<img width="960" alt="screen shot 2018-06-22 at 09 56 27" src="https://user-images.githubusercontent.com/194114/41764923-d8aa7c98-7602-11e8-989a-0e30b8efbbd4.png">

![screen shot 2018-06-12 at 16 24 10](https://user-images.githubusercontent.com/194114/41296534-6f46581e-6e5d-11e8-88d3-656c6407fb82.png)

# Sitzungsvorlage Erstellen / Bearbeiten

Beim auswählen einer Sitzungsvorlage, kommt dann folgende Ansicht:
![screen shot 2018-06-12 at 16 37 36](https://user-images.githubusercontent.com/194114/41297323-2e5274a8-6e5f-11e8-8101-230678d6b7b1.png)

# Sitzung erfassen

Beim erfassen einer Sitzung, sollten die Sitzungsvorlagen, die dem Kommittee zur Verfügung stehen aufgelistet werden.
Ist eine Vorlage ausgewählt, so werden die Zwischentitel / Abschnitte aus der Sitzungsvorlage übernommen.
Es soll auch möglich sein, keine Vorlage auszuwählen und mit einer leeren Sitzung zu starten.
![screen shot 2018-06-12 at 16 45 44](https://user-images.githubusercontent.com/194114/41297863-66d25284-6e60-11e8-931f-39ec75890ecb.png)

Ref: https://basecamp.com/2768704/projects/13732725/todos/340577830

**Comment by tarnap** [comment]
Ich habe folgenden Vorschlag:

Wir lassen beim erstellen einer Sitzung zu, dass der Benutzer eine Andere Sitzung als Vorlage wählen kann:
<img width="622" alt="screen shot 2018-06-09 at 11 54 32" src="https://user-images.githubusercontent.com/194114/41190311-5ccc677e-6bdc-11e8-909f-b1aba58fd6e2.png">

Dann wird eine neue Sitzung mit den selben Traktanden (ohne Anträgen) erstellt.
Sollten weitere Ad-Hoc Traktanden oder Zwischentitel vorhanden sein, können diese nach der Erstellung der Sitzung durch den Benutzer entfernt werden.

So muss nicht ein weiteres Objekt gepflegt werden und erlaubt "dynamische" Vorlagen:
Einer unserer Kunden hat rotierende Zwischentitel für Ihre "Ressorts".
Diese rotieren, damit nicht immer derselbe Ressort zuletzt oder zuerst an der Reihe ist.

Somit  ergibt sich:
```
Sitzung 1     Ressort A., Ressort B., Ressort C.
Sitzung 2     Ressort B., Ressort C., Ressort A.
Sitzung 3     Ressort C., Ressort A., Ressort B.
```

Sollte die letzte Sitzung als Vorlage gewählt werden können, so muss immer nur ein Ressort verschoben werden.

Was hält ihr davon?

**Comment by tarnap** [comment]
Vorschlag: Die letzte Sitzung dieses Gremiums ist schon ausgewählt.

Fragen: Welche Sitzungen dürfen im Widget gewählt werden?
- Alle Sitzungen des Gremiums?
- Alle Sitzungen auf welche der Gemeindeschreiber (Lese-) Zugriff hat?

**Comment by tarnap** [comment]
Passender Eintrag bei Basecamp Köniz
https://basecamp.com/2768704/projects/13732725/todos/340577830
