### ISSUE TITLE
Protokollauszug: Unterscheidung von Auszügen anhand Dateiname schwierig

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3767]
<a href="https://github.com/jone"><img src="https://avatars3.githubusercontent.com/u/7469?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jone](https://github.com/jone)**
_Tuesday Oct 10, 2017 at 08:01 GMT_
_Originally opened as https://github.com/4teamwork/gever/issues/135_

----

Wenn ich mehrere Protokollauszüge erstelle und diesen verschiedene Titel gebe, kann ich sie anhand des Dateinamens nicht ausinanderhalten. Dies ist vor allem beim Versand im Mailprogramm auffallend.

<img width="1408" alt="bildschirmfoto 2017-10-10 um 09 59 53" src="https://user-images.githubusercontent.com/7469/31375471-f91e1f04-ada1-11e7-89f7-531877f68a65.png">

**Comment by deiferni** [comment]
<a href="https://github.com/deiferni"><img src="https://avatars2.githubusercontent.com/u/736583?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [deiferni](https://github.com/deiferni)**
_Tuesday Dec 12, 2017 at 08:48 GMT_

----

Dateiname und Titel sollten synchronisiert werden 🤔 .

**Comment by deiferni** [comment]
I'd say this is at least related to https://github.com/4teamwork/opengever.core/issues/3767 which should tackle this issues for all filenames.

**Comment by deiferni** [comment]
_(isn't a bug though)_

**Comment by njohner** [comment]
Yes I think we can leave that aside for now

**Comment by phgross** [comment]
Problem wurde mit #4553 gelöst oder zumindest entschärft. Keine weiteren Anpassungen geplant.
