### ISSUE TITLE
Protokollgenehmigung

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3768]
<a href="https://github.com/Suweber"><img src="https://avatars0.githubusercontent.com/u/31923504?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Suweber](https://github.com/Suweber)**
_Tuesday Oct 24, 2017 at 12:54 GMT_
_Originally opened as https://github.com/4teamwork/gever/issues/142_

----

Das Protokoll der vergangenen Sitzung sollte auf möglichst direktem Weg für die nächste Sitzung tratkandiert werden können (Link, PDF auf bzw. aus Sitzungsdossier?). In der Regel ist das Protokoll das erste Traktandum der Sitzung (Gemeinderat, Parlament, Kommissionen) welches behandelt bzw. genehmigt werden muss. 

Lösungsvorschlag:

- Sobald die Sitzung abgeschlossen wurde wird ein Link/Button `Antrag Protokollgenehmigung erstellen` dargestellt. Mit diesem kann ein Antrag zur Genehmigung des Protokolls im Sitzungsdossier erstellt werden. (analog zum Button `Aufgabe erstellen` eines Protokollauszuges) ![screenshot 2018-11-28 at 16 22 48](https://user-images.githubusercontent.com/736583/49162064-685e8100-f32a-11e8-931c-0d928f2ffd33.png)

- Nach click auf den Link wird die Maske zur Erstellung eines Antrags eingeblendet. Folgende Felder werden zusätzlich Vorausgefüllt:
  - Gremium: Gremium der aktuelle Sitzung
  - Titel: Protokollgenehmigung + Titel der aktuellen Sitzung
  - Anhänge:  Protokoll der aktuellen Sitzung
Der Antrag wird im Sitzungsdossier der aktuellen Sitzung erstellt. Sobald er eingereicht wurde steht er bei weiteren Sitzungen zur Traktandierung zur Verfügung.
![screenshot 2018-11-28 at 16 30 04](https://user-images.githubusercontent.com/736583/49162574-7234b400-f32b-11e8-957d-6595591c2767.png)

**Comment by deiferni** [comment]
<a href="https://github.com/phgross"><img src="https://avatars0.githubusercontent.com/u/485755?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [phgross](https://github.com/phgross)**
_Tuesday Dec 12, 2017 at 08:45 GMT_

----

Offene Fragen:
 - Soll das Protokoll der letzten Sitzung als Anhang mitgeführt werden oder ist das nicht nötig? 
 - Was spricht gegen ein AdHoc Traktandum.

**Comment by deiferni** [comment]
Siehe auch https://gever.4teamwork.ch/ordnungssystem/3/2/2/1/dossier-1763/document-25419

**Comment by deiferni** [comment]
aktualisiert mit Lösunsvorschlag aufgrund Kundenwunsch in https://extranet.4teamwork.ch/support/gemeinde-walenstadt/tracker/43 und https://extranet.4teamwork.ch/support/gemeinde-walenstadt/tracker/44

**Comment by Suweber** [comment]
Da es sich um einen immer wiederkehrenden, gleich zu behandelnden "Akt" handelt (das Protokoll muss formell genehmigt werden), wäre eine direkt unterstützte Protokollgenehmigung sehr willkommen. Gegen ein Ad-hoc Traktandum spricht grundsätzlich nichts. Ausser vielleicht, dass der gleiche Schritt immer wieder manuell erledigt werden muss. Der Kunde empfindet dies als unnötig, da das Traktandum Protokollgenehmigung ja immer wieder traktandiert werden muss.
