### ISSUE TITLE
Autocompletion bei Keyword- und Datetimepicker-Widget deaktivieren

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3772]
<a href="https://github.com/jone"><img src="https://avatars3.githubusercontent.com/u/7469?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jone](https://github.com/jone)**
_Wednesday Nov 08, 2017 at 07:50 GMT_
_Originally opened as https://github.com/4teamwork/gever/issues/155_

----

**durchgeführte Aktionen in einzelnen Schritten**
Im Firefox:
Beim Hinzufügen von Mitgliedern in den Datumsfeldern eine Zahl eingegeben.
 Browser macht Vorschlag (bereits eingegebenes Datum). 
 Cursortaste nach unten
 Enter
**erwartetes Ergebnis**
vorgeschlagenes Datum wird übernommen
**tatsächlich aufgetretenes Ergebnis**
heutiges Datum wird übernommen

[Datumsfeld-Vorschlag-annehmen.docx](https://github.com/4teamwork/gever/files/1452976/Datumsfeld-Vorschlag-annehmen.docx)

**Comment by deiferni** [comment]
<a href="https://github.com/phgross"><img src="https://avatars0.githubusercontent.com/u/485755?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [phgross](https://github.com/phgross)**
_Tuesday Dec 12, 2017 at 08:28 GMT_

----

![bildschirmfoto 2017-12-12 um 09 27 58](https://user-images.githubusercontent.com/485755/33874360-c5f40072-df1e-11e7-84c5-81a7ce95c4aa.png)

**Comment by elioschmutz** [comment]
@phgross weisst du, welches Datum hier genau gemeint ist? Beim Hinzufügen eines Mitgliedes kann ich kein Datum hinzufügen...

**Comment by deiferni** [comment]
hmm, ich denke hier ist das hinzufügen einer Mitgliedschaft auf einem Gremium gemeint
![screen shot 2018-06-07 at 10 48 04](https://user-images.githubusercontent.com/736583/41088640-514de58c-6a40-11e8-96ac-fde2baa7bdb8.png)

ist eventuell nur unter Win so?

**Comment by tarnap** [comment]
Unter Chrome funktioniert es unter Mac Os nicht:
![select](https://user-images.githubusercontent.com/194114/41172942-9fec83ae-6b55-11e8-9024-7ecc27c9b7d0.gif)
Was ist das eigentlich für ein Feld über dem select widget?

Unter Firefox funktioniert die Auswahl wie erwartet.

**Comment by tarnap** [comment]
https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

Using `autocomplete="false"` on the input or form should to the Trick!

https://pythonhosted.org/z3c.form/form.html#changing-widget-attribute-values
