### ISSUE TITLE
Antrag erstellen aus Tabbedview

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3775]
<a href="https://github.com/jone"><img src="https://avatars3.githubusercontent.com/u/7469?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jone](https://github.com/jone)**
_Wednesday Oct 04, 2017 at 14:43 GMT_
_Originally opened as https://github.com/4teamwork/gever/issues/119_

----

Ich möchte gerne in der Tabbedview mehrere Dokumente auswählen können und dann direkt einen Antrag erstellen, analog Aufgabe. Die Dokumente sollen dann direkt als Anhang vorausgewählt sein.

![bildschirmfoto 2017-10-04 um 16 41 04](https://user-images.githubusercontent.com/7469/31181998-fcc0ccf2-a922-11e7-9512-d8895eda0042.png)

**Comment by phgross** [comment]
Aktion steht mit dem Release 2018.4 zur Verfügung.
