### ISSUE TITLE
Zusätzliche Rolle `Member Area Administrator`

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#3816]
Anstatt die Rolle `Administrator` soll eine zusätzliche Rolle `Member Area Administrator` für den Zugriff auf Private Bereiche geschaffen werden.

Folgende Anpassungen sind deshalb zu implementieren:
 - [ ] `opengever_private_folder` workflow überarbeiten, so dass nicht der Administrator sondern der `Member Area Administrator` für den Zugriff berechtigt wird.
 - [ ] `opengever_private_dossier` workflow überarbeiten, so dass nicht der Administrator sondern der `Member Area Administrator` für den Zugriff berechtigt wird.
 - [ ] Eigener Placeful Workflow `opengever_private` mit separatem `private_document_workflow` und `private_mail_workflow`: Dabei sollen nur die Rollen `Owner`, `Member Area Administrator` sowie `Manager` berechtigt werden.
 - [ ] Aktivieren des placeful workflows für den Bereich `Meine Ablage` (rekursiv)

@deiferni @lukasgraf or @jone any concerns, additional todos?

**Comment by jone** [comment]
Macht es sinn, die Workflows gleich mit Lawgiver zu machen?

**Comment by jone** [comment]
In #3679 habe ich die OGIP-17 Workflows beschrieben. Dort habe ich das gleiche Problem mit dem Dokument-Workflow.
Um eine Placeful-Workflow-Policy-Config zu vermeiden habe ich geplant neue Rollen zu verwenden, die noch nicht verwendet werden. So können wir beim Dokumente-Workflow einfach mehr Rollen hinzufügen und so bewirken dass der gleiche Workflow in mehreren Umgebungen unterschiedlich funktionieren kann. Nur so als Input falls dies hier die Sache erleichtern würde.

**Comment by phgross** [comment]
@jone Nein das Problem ist ja, dass die Administrator Rolle standardmässig berechtigt ist, obwohl Sie das im persönlichen Bereich nicht sein soll.

Ich erachte es nicht als sinnvoll, bei gewissen Dokumenten ein normaler Workflow und bei gewissen ein Lawgiver workflow einzusetzen, dass wird sonst noch komplizierter.

**Comment by jone** [comment]
Macht sinn 👍
