### ISSUE TITLE
Alphabetische Sortierung von verwandten Dossiers

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3825]
Gemäss diesem [Thema im FF](https://feedback.onegovgever.ch/t/verlinkte-dossiers-in-der-dossieruebersicht/758) wird eine alphabetische Sortierung der verlinkten/verwandten Dossiers in einem Dossier gewünscht. Bitte dies entsprechend umsetzen.

**Comment by livschal** [comment]
@deiferni wird dies ab dem nächsten Release zur Verfügung stehen?

**Comment by deiferni** [comment]
@livschal ja, mit `2018.2`, sorry milestone war nicht korrekt gesetzt.
