### ISSUE TITLE
Icon für JSON-Dateien hinzufügen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3829]
Wir haben intern relativ viele JSON-Dateien abgelegt (z.B. bei Migrationen aus Extranet). Hier fehlt ein passendes Icon - bitte ein derartiges "organisieren", auch wenn es primär nur von uns verwendet werden wird.

Z.B. https://gever.4teamwork.ch/ordnungssystem/0/320/dossier-2268/document-21165#overview

**Comment by phgross** [comment]
Wir haben eins für `Code`, m.E. könnten wir dieses verwenden.

**Comment by bierik** [comment]
@phabegger Was meinst du zu @phgross Vorschlag?

**Comment by deiferni** [comment]
stand: icon in auftrag bei 🎨 .
