### ISSUE TITLE
Anpassung inhaltlich: "Schlagworte" durch "Schlagwörter" ersetzen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3830]
Plural von Schlagwort (im Sinn von Deskriptor) ist Schlagwörter, nicht Schlagworte.

Siehe https://de.wikipedia.org/wiki/Schlagwort_(Linguistik)

**Comment by tarnap** [comment]
@phabegger, @phgross:
So etwas ähnliches hatten wir bereits. Es wurden "Worte" statt "Wörter" verwendet.

Ich habe noch diesen hier gemacht:
<img width="960" alt="screen shot 2018-05-16 at 08 41 07" src="https://user-images.githubusercontent.com/194114/40100648-fb132c3e-58e4-11e8-863a-abd97cd1e402.png">

Nach diesem Fix sollten keine weiteren solchen (ähnlichen) Fälle vorkommen.

**Comment by tarnap** [comment]
Ich darf nicht nur im opengever Ordner suchen, es hat auch Einträge in den docs etc:

Ich habe noch "Stichworte" gefunden:
<img width="961" alt="screen shot 2018-05-16 at 09 30 48" src="https://user-images.githubusercontent.com/194114/40102947-2001913c-58ec-11e8-9053-ed4d67d9bffd.png">

@phabegger, @phgross: Geht es hier Inhaltlich um Worte oder um Wörter?
