### ISSUE TITLE
Display User-Details in an Overlay.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#385]
Could the user details be displayed as an overlay? Like the members-of-a-group-view?

**Comment by phgross** [comment]
Ich würde darauf verzichten, die Benutzer Details Ansicht in einem Overlay darzustellen. Dies würde insbesondere bei einer Gruppen-Ansicht, welche auch bereits in einem Overlay dargestellt wird, zu einem komischen verhalten führen.

![bildschirmfoto 2017-04-28 um 09 27 59](https://cloud.githubusercontent.com/assets/485755/25518671/0047f7f2-2bf5-11e7-93e3-d7104daaba7c.png)
