### ISSUE TITLE
Port existing integration tests to use the inactive dossier fixture

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#3857]
In #3764 we have added an inactive dossier containing an inactive document and task. We should make use of this in existing tests which use inactive elements.

A list of possible candidates is:
- [x]  `opengever.basetests.test_archival_file_form.TestEditArchivalFormAccess`
- [ ]  4 times in `opengever.dossier.tests.test_activate.TestDossierActivation`
- [ ]  `opengever.dossier.tests.test_base.TestDateCalculations`
- [ ]  `opengever.dossier.tests.test_deactivate.TestDossierDeactivation`
- [ ]  `opengever.dossier.tests.test_navigation.TestNavigation`
- [ ]  `opengever.dossier.tests.test_resolve.TestResolving`
- [x]  15 times in `opengever.officeconnector.tests.test_api.TestOfficeconnectorAPIDisabled`
- [x]  37 times in `opengever.officeconnector.tests.test_templates`
- [x]  9 times in `opengever/tabbedview/tests/test_dossier_listing`
- [x]  `opengever.disposition.tests.test_inactive_dossiers_are_always_not_archival_worthy`
- [ ]  `opengever.disposition.tests.TestDestructionForNotArchivedDossiers`
- [ ]  3 times in `opengever.disposition.tests.TestDispositionEditForm`
- [ ]  14 times in `opengever.disposition.tests.TestDispositionOverview`
- [ ]  `TestContentStatsIntegration` if we port it back to integration layer

**Comment by njohner** [comment]
*  4 times in `opengever.dossier.tests.test_activate.TestDossierActivation`: We would also need an inactive subdossier to port these tests

**Comment by njohner** [comment]
We have made use of the inactive dossier in all integration tests where it could be used and moved some tests to the integration layer.
The whole disposition module is in the functional layer and not that easily moved, so that would be a bit more work. Whether these have priority to be ported is unclear to me.

**Comment by Rotonen** [comment]
The disposition tests are amongst the least recently touched and also amongst the slowest running functional tests - I see value in tackling those, but would wait for wider approval on that.

**Comment by phgross** [comment]
I would say:
Let's open a separate Issue for converting the `dispositions` tests in to intergration tests, for 2019.1 release, Prio 2. and close this one.

@njohner could you do that?

**Comment by njohner** [comment]
We opened a new issue for the conversion of the `dispositions` tests to the integration layer: #5133
