### ISSUE TITLE
Download copy on document version overlay downloads current file

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3863]
Steps to Reproduce:

- Create Document with multiple versions
- Go to versions tab, open "Preview" for a non-recent version
- Click "Kopie herunterladen" in the Preview overlay

Actual outcome:
The most recent version of the file is downloaded.

Expected outcome:
The version for which the preview is rendered should be downloaded.

**Comment by Rotonen** [comment]
https://github.com/4teamwork/opengever.core/blob/master/opengever/document/browser/templates/macros.pt#L74

https://github.com/4teamwork/opengever.core/blob/master/opengever/document/browser/actionbuttons.py#L78
