### ISSUE TITLE
Sharing and info view should display group title, if available.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#3864]
The sharing view and tab currently display the group id for all groups that have been configured in `@@sharing` (Aktionen -> Freigabe).

Sharing-Tab:
![screen shot 2018-01-16 at 13 19 05](https://user-images.githubusercontent.com/736583/34988951-ecbd5a74-fac0-11e7-8f44-ca7cacdf9d4d.png)

Sharing-View:
![screen shot 2018-01-16 at 13 27 36](https://user-images.githubusercontent.com/736583/34989016-267d25aa-fac1-11e7-8914-8b70d25eeb53.png)

- Instead of displaying the `group_id` only, the group title should be displayed, when available. This could be achieved by using the `label` method on `Group`, for example.
- Also preserve the `group_id` for debugging purposes, for example by using it as `title` of the html element or by adding it in brackets, similar to user.

See:
- label method
 https://github.com/4teamwork/opengever.ogds.models/blob/1d64efb3db926e0eb811e81fbf5c43da37707641/opengever/ogds/models/group.py#L70
- sharing view implementation
 https://github.com/4teamwork/opengever.core/blob/master/opengever/sharing/browser/sharing.py
- ogds sync that also syncs group title, if available https://github.com/4teamwork/opengever.core/pull/3638

https://basecamp.com/2768704/projects/13732725/todos/325803930

**Comment by Rotonen** [comment]
I'm currently under the impression this one is already baked into the existing functionality already based on https://github.com/4teamwork/opengever.core/commit/d65538b205e59dae70e21d16abe0a61fb11f5886.

So it should already have done that in the first place?

**Comment by deiferni** [comment]
Why has this been closed? Clearly the implementation as specified above (actually **USE** the title in the sharing view and info tab) is missing. WTF?

**Comment by Rotonen** [comment]
To my current standing understanding it does `Title (id)` as in `fa Users Group (fa_users)` in the test here:

https://github.com/4teamwork/opengever.core/blob/a9fb62c9cba4c3a3cb157579ff0b7443a6800b18/opengever/sharing/tests/test_sharing_integration.py#L207

When it does not have a title available, it'll only display the id.

**Comment by deiferni** [comment]
i can't get that to work on my local dev instance though, also could not find a PR with the implementation 🤔
