### ISSUE TITLE
Detect "Fuzzy" translations with CI job.

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3902]
The translation CI job should fail when there are "fuzzy"-Translations.

Fuzzy translation can cause Plone to not load this translation file at all, or only partially, leading to missing translations.

Fuzzy translation can be detected like this:
```sh
git grep '#, fuzzy' opengever/**/*.po
```

**Comment by deiferni** [comment]
Duplicates https://github.com/4teamwork/opengever.core/issues/2506
