### ISSUE TITLE
Ansicht einer Aufgabe: Richtiges Dokument-Icon bei Anhängen anzeigen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#3908]
Ist aus meiner Sicht ggw. broken:
![skizze 7](https://user-images.githubusercontent.com/485600/35513239-ac0fbade-0502-11e8-93ac-0f0913ecb0d6.png)

In obigem Beispiel sollte das Word-Icon angezeigt werden.

**Comment by deiferni** [comment]
As discussed, we will display an additional link-icon on top of the mimetype icon, something like
![screen shot 2018-03-08 at 15 48 42](https://user-images.githubusercontent.com/736583/37157117-3107a5d2-22e8-11e8-8324-8b5cc3852495.png)
