### ISSUE TITLE
Ensure the open pdf in new tab functionality still works with bumblebee 2018.1

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3911]
There is a small chance the content disposition header changes may have impacted this functionality. This should be verified.

**Comment by Rotonen** [comment]
Ref. https://github.com/4teamwork/opengever.core/issues/2213

**Comment by Rotonen** [comment]
Should this branch of configurability also end up in our release validation scripts?

**Comment by deiferni** [comment]
yes, it seems to work as expected  🎉 .
