### ISSUE TITLE
Mandantenübergreifende Aufgabe: Bearbeitung in bestehendem Dossier kommt Fehler

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#3924]
Wenn ich auf 

https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-480/task-140

die Aufgabe akzeptiere (ich bin Simona Reinhard aus der Ratskanzlei und möchte eine Aufgabe aus meinen Eingangskorb, welche vom Amt für Informatik reinkam) und die Option "in einem bestehenden Dossier auf Ratskanzlei bearbeiten" bekomme ich folgende Fehlermeldung: 1517497112.140.183430493171 

Bitte anschauen, ich möchte am Mittwoch gerne (endlich) die mandantenübergreifenden Aufgaben neu dokumentieren. merci!

![bildschirmfoto 2018-02-01 um 16 05 02](https://user-images.githubusercontent.com/20790360/35685356-c7504ea8-0769-11e8-9967-ebc2579702cd.png)

**Comment by livschal** [comment]
Fehler tritt auch bei zur Kenntnisnahme auf, wenn simona.reinhard eine Aufgabe abschliessen will: 
![bildschirmfoto 2018-02-07 um 08 42 39](https://user-images.githubusercontent.com/20790360/35904321-f9d3d502-0be2-11e8-9e21-0d1168c18993.png)

**Comment by deiferni** [comment]
@livschal das Problem sollte nun behoben sein (auf `dev`)

Siehe https://github.com/4teamwork/opengever.hatchery/issues/20
