### ISSUE TITLE
Go through where we use the icons and fit the new icons in

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3927]
The new icons are a bit larger, so they're cropped or bulging or such in many places.

**Comment by deiferni** [comment]
Could you provide a bit more details, where are the icons not correct?

**Comment by Rotonen** [comment]
The bumblebee overlay (issue on the top left) is a good example of the kind of cropping happening:

![screen shot 2018-02-08 at 12 14 52](https://user-images.githubusercontent.com/935317/35970207-cf235b74-0cc9-11e8-908e-920f5c5fc98b.png)

Could not currently find others in a quick click-through. This should probably added to the validation scripts for manual testing so we can catch them all at least for a point release?
