### ISSUE TITLE
Test isolation failure for tasks

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#3928]
I had a test failure in a sequential test run of the whole suite in `test_reassign_task_in_progress_state_to_a_team_isnt_possible (opengever.task.tests.test_assign.TestAssignTask)`.

```
AssertionError: Lists differ: ['Team responsibles are only a... != []

First list contains 1 additional elements.
First extra element 0:
'Team responsibles are only allowed if the task or forwarding is open.'

- ['Team responsibles are only allowed if the task or forwarding is open.']
+ []
```

Superficially seems like some leak in the workflow state of a fixtured task.

**Comment by Rotonen** [comment]
The quickest way to locally reproduce I found: `bin/test -m opengever.task`

**Comment by Rotonen** [comment]
Slightly quicker: `bin/test --layer ActivityLayer --layer integration -m opengever.task`

**Comment by jone** [comment]
Fast reproduction: 
```
./bin/test -t test_activity_actor_is_current_user -t test_reassign_task_in_progress_state_to_a_team_isnt_possible
```
