### ISSUE TITLE
Login-Dialog bei Click auf Link in Word

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#3933]
Word 16.9.1 (Office 365); GEVER 2017.7.8

Wenn in einem Word-Dokument auf einen Link aufs GEVER geklickt wird, so versucht Word neu die Authentifizierung durchzuführen:
<img width="1275" alt="bildschirmfoto 2018-02-05 um 14 52 37" src="https://user-images.githubusercontent.com/7469/35809892-43de0316-0a8a-11e8-9bf5-173dc21c8b76.png">

Vermutlich macht dies Word, weil Plone mit 401 antwortet und im WWW-Authenticate-Header basic-Auth vorschlägt, was Word anscheinend neu kann 😞 
```sh
$ curl -X HEAD -I https://gever.4teamwork.ch/
HTTP/1.1 401 Unauthorized
Date: Mon, 05 Feb 2018 14:03:49 GMT
Server: Zope/(2.13.26, python 2.7.14, linux2) ZServer/1.1
Bobo-Exception-Line: 118
Content-Length: 1345
Bobo-Exception-Value: See the server error log for details
Bobo-Exception-File: subscribers.py
Bobo-Exception-Type: <class 'AccessControl.unauthorized.Unauthorized'>
Content-Type: text/html; charset=utf-8
WWW-Authenticate: basic realm="Zope"
Set-Cookie: serverid=p01; path=/; HttpOnly; secure
```

Das Verhalten kann bei anderen Plone-Sites reproduziert werden, indem ein Link auf eine nicht veröffentlichte Ressource verwendet wird. Es kann anscheinend mit Port 8080 nicht reproduziert werden.

**Vorgehen:**
Wir sollten versuchen, den WWW-Authenticate header zu entfernen. Dies kann u.U. durch das deaktivieren gewisser PAS-plugins erreicht werden.

**Comment by deiferni** [comment]
Problem kann mit https://extranet.4teamwork.ch/dev/0999-projekt-my.teamraum.com-intern/tracker/65 gelöst werden. Alles weitere in https://extranet.4teamwork.ch/betrieb/tracker/753.
