### ISSUE TITLE
Scan-in auch für Benutzer erlauben, die den Eingangskorb nicht sehen können

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4044]
Der `scan-in` Endpoint is im Moment so gebaut, dass der Benutzer Rechte auf dem Eingangskorb braucht, in den er scant. Dies soll so angepasst werden, dass Benutzer auch in Eingangskörbe scannen können, die sie nicht sehen. Siehe https://github.com/4teamwork/opengever.core/blob/a0de2c334954d8c2bc4dddd75e2a4c87d77c6c9c/opengever/api/scanin.py#L50-L66.

Dazu sind folgende Anpassungen am scan-in nötig: 
- neue Permission scan-in für den Eingangskorb implementieren
- Restriktion lockern, scan-in auch für Benutzer erlauben, die den Eingangskorb nicht sehen können, jedoch prüfen ob Benutzer die entsprechende Permissions hat. (Zu bestimme: Default-Rollenzuweisung im `rolemap.xml` oder nur Konfiguration pro Kunde?)

gemäss https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/20

Also when touching this please tackle the CSRF parsing error that surfaces during testing, e.g.: `bin/test-cached -t test_scanin_to_inbox` will log:
```  Running:
    1/1 (100.0%)error parsing dom, failure to add csrf token to response for url http://nohost/plone/@scan-in
    error parsing dom, failure to add csrf token to response for url http://nohost/plone/@scan-in
```
This could be a s simple as changing the response content-type to non `text/html`.

**Comment by Rotonen** [comment]
Initial suspicion: if something falls through `_no_content_marker` it'll be `text/html` per default for us:

https://github.com/plone/plone.restapi/blob/ff4101e6dec887384aae8e35d0fa0345a024ac7f/src/plone/restapi/services/__init__.py
