### ISSUE TITLE
"Auschecken/Bearbeiten" zu "Auschecken und Bearbeiten" ändern

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#4051]
Bitte gemäss https://feedback.onegovgever.ch/t/auschecken-und-bearbeiten/901/5 den Button "Auschecken/Bearbeiten" in "Auschecken und Bearbeiten" ändern.

**Comment by livschal** [comment]
@deiferni / @phgross wo kann ich das testen? ist das auch ab release 2018.2 verfügbar?

**Comment by phgross** [comment]
@livschal Nein, siehe der angewählte Milestone:
![_auschecken_bearbeiten__zu__auschecken_und_bearbeiten__andern_ _issue__4051_ _4teamwork_opengever_core](https://user-images.githubusercontent.com/485755/38609652-eda7018c-3d7e-11e8-87dd-0c85d124e762.png)
