### ISSUE TITLE
Finalisieren der automatischen Aktualisierung der Vorschaubilder

### ISSUE THREAD

**Issue by siegy22** [4teamwork/opengever.core#4052]
In meiner IPA Zeit habe ich Bumblebee mit WebSockets ausgestattet, weil die ganze Konvertierung asynchron passiert. So kann eine Client app von Bumblebee sich verbinden und die Bilder automatisch neu laden, ohne dabei die ganze Seite erneut laden zu müssen. So wird die User Experience um ein vielfaches verbessert. Ich habe eine erste Frontend Implementierung im GEVER bereits erledigt. (auf dem `lab_21042017` branch)

Nun soll das ganze finalisiert werden um das produktiv nutzen zu können. 

Leider sind wir hier im Serverbereich noch sehr eingeschränkt, da es ein Problem im Zusammenhang mit Apache und Passenger für die WebSocket Unterstützung gibt. (https://github.com/phusion/passenger/issues/1202)

Vorschlag zur Lösung im Serverbereich:
1. [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) in Kombination mit Apache und Puma für den Rails Server.
2. Nginx in Kombination mit Passenger (da funktionieren die WebSockets, ohne weitere Konfiguration)
3. Nginx in Kombination mit Puma.

@buchi kannst du bitte hier die Vor- und Nachteile der verschiedenen Lösungen sowie die benötigte Zeit kurz Aufführen?

Dieser Issue (Schätzungen etc.) behandelt jedoch nur die Javascript Integration, ich schätze hier den Aufwand auf ca. 1 AT.

**Comment by Rotonen** [comment]
+1 for option 3 - that has served me well in production for a couple of years in past projects.

**Comment by buchi** [comment]
Nginx + Puma it is.

Wir müssen zuerst unser Puppet so vorbereiten, dass wir GEVER deployments mit nginx konfigurieren können.

**Comment by siegy22** [comment]
Meine Ursprüngliche Schätzung von 8h, ist wohl nicht ausreichend um das fertigzustellen.
Ich glaube, dass mir hier auch ein bisschen die Erfahrung mit dem GEVER Produkt/workflow gefehlt hat, und sich dadurch das ganze etwas verzögert hat. Unter anderem, hat sich das auch verzögert, weil noch `ftw.showroom` und `ftw.bumblebee` Anpassungen benötigt haben.

Diese 8h sind nun fast aufgebraucht, jedoch sind noch folgende Punkte offen:
- Profile anpassen (javascript files)
- Tests schreiben 

@deiferni Was denkst du wie lange dauert das noch, bis es gemergt werden kann? Ich hätte hier auf ca. 4h geschätzt, ist das ausreichend?
Wenn das für dich ok ist, kannst du gleich den estimate anpassen.

**Comment by deiferni** [comment]
@siegy22 hmja ich hab mal das estimate auf 3 getan. neuer zielrelease dann aber höchstwahrscheinlich `2018.3`. ebenfalls so angepasst.

**Comment by phgross** [comment]
Closed via #4053

**Comment by deiferni** [comment]
Weiter mit https://extranet.4teamwork.ch/betrieb/tracker/757
