### ISSUE TITLE
Team-Erstellung durch `Administrator` erlauben.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4054]
Im Moment lassen sich Teams nur durch einen `Manager` erstellen, bearbeiten. Dies soll so angepasst werden, dass auch ein `Administrator` diese Berechtigungen hat.

Motivation:
- Verbesserung der Usability für Kunden
- Supportanfragen und solange nur wird Teams erfassen können wird es viele Supportanfragen diesbezüglich geben
- Dogfooding: die Funktionalität wurde bei uns intern getestet und ist ready

Umsetzung:
- Neue Permissions `opengever.contact.AddTeam` und `opengever.contact.EditTeam` erstellen
- `TeamAddForm` und `TeamEditForm` mit entsprechender permission schützen
- Im `rolemap.xml` permission `Administrator` und `Manager` zuweisen

**Comment by phgross** [comment]
@Rotonen the `add-team` action still checks on `Manage portal content` (see https://github.com/4teamwork/opengever.core/blob/master/opengever/core/profiles/default/types/opengever.contact.contactfolder.xml#L64), so the add action will and had never been showed up for `Administrator`, which was the idea behind this issue. Never tested locally ? 😕

Could you implement a fix immediately, we need to backport it to `2018.3` and create a hotfix release. (Productive release tomorrow)

**Comment by Rotonen** [comment]
@phgross my bad, missed the action.
