### ISSUE TITLE
Moving documents out of private area doesn't update security after workflow changes

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4070]
**Steps to reproduce**:

- As `User A`, add a document to a dossier in your private area
- Still as `User A`, create a dossier in the public repository
- Move the document into the dossier in the public repository
- Switch to `User B`
- Try to view the document as `User B`

**Expected results**:
- `User B` can view the document, since it's in a dossier he may view

**Actual results**:
- `User B` doesn't have view permission on the moved document.

---

The reason for this is that documents below a `PrivateRoot` have a placeful workflow (`opengever_private_document_workflow`). Once they are moved out of the private area, their workflow is the regular `opengever_document_workflow`. However, Plone doesn't automatically update the object security once the workflow changes.

We therefore need to make sure that object security is updated if any object is moved or copied.

**Comment by deiferni** [comment]
Closed by https://github.com/4teamwork/opengever.core/pull/4092
