### ISSUE TITLE
Sitzungsapp Integration in SPV

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#4081]
- Featureflag für Knopf (Nur Word-SPV)
- Konfiguration Ziel App (Grimlock)
- Authentisierung über Cookie von Portal.
- Alles Synchron
- Bestehender ZIP-Export um Metadaten ergänzen mit Metadaten.

**Comment by tarnap** [comment]
Die Sitzungsapplikation hat bereits ein REST endpoint, welches erlaubt einem Gremium Sitzungen hinzuzufügen.

Um dies sinnvoll zu testen empfehle ich die Sitzungsapplikation lokal einzurichten.
Siehe hierfür https://github.com/4teamwork/grimlock/tree/master/backend#setup

Nach dem Aufsetzen und Starten der Sitzungsapplikation kann die Swagger Dokumentation verwendet werden um die benötigte Payload zu sehen und testen.

Die Swagger-Doku ist (bei laufender Sitzungsapplikation) unter http://localhost:8000/docs/ zu finden.

Bitte beachte, dass die Dokumentation erst zugänglich ist, wenn dein Benutzer berechtigt ist diese zu sehen.
Besuche dafür http://localhost:8000/cas/login/

# Doku
<img width="1072" alt="screen shot 2018-04-17 at 16 49 07" src="https://user-images.githubusercontent.com/194114/38877639-692ea26c-425f-11e8-8ac4-186c1f760ac9.png">

# Import Endpoint
<img width="921" alt="screen shot 2018-04-17 at 16 49 37" src="https://user-images.githubusercontent.com/194114/38877641-694a32b6-425f-11e8-8afb-8807b5294aa7.png">

**Comment by tarnap** [comment]
# Proposal

<img width="1072" alt="screen shot 2018-04-19 at 10 27 48" src="https://user-images.githubusercontent.com/194114/38980148-5bf98108-43bc-11e8-931c-a0ff5202456f.png">

**Comment by tarnap** [comment]
The export view needs to know the endpoint (URL) where to export the Zipfile.
Since every committee has its own endpoint, it's best to store the URL on the committee as supplementary field.
This field should only be editable by managers.

**Comment by tarnap** [comment]
Server to server communication and authorization mechanism:

Grimlock requires either a session cookie from the GEVER portal or a login to authenticate the user and start an authenticated session (with a cookie).

<img width="961" alt="screen shot 2018-04-20 at 09 31 05" src="https://user-images.githubusercontent.com/194114/39036389-968b7c4c-447d-11e8-8ac9-4fb133dfa6ce.png">

The GEVER exporting the meeting to Grimlock needs to be authenticated by Grimlock.
Grimlock needs to know what user is performing the request from GEVER.

This can be accomplished with a shared application secret and a request context containing the user (similar to duplexer).

**Comment by tarnap** [comment]
Branch containing the related code:
https://github.com/4teamwork/opengever.core/tree/pv-export_meetings_to_grimlock

**Comment by phgross** [comment]
m.E. ist zurzeit nicht definiert, wie sich GEVER am Grimlock authentisieren soll für den Import der Sitzungsdaten ins Grimlock. 

@jone @buchi ich wäre euch dankbar, wenn ihr dies bei Gelegenheit diskutieren und definieren könntet. 

Issue wird verschoben, da Spezifikation noch unklar.

**Comment by jone** [comment]
Ich schlage vor, auf Seite Grimlock die Token-Authentication des Django Restframeworks zu verwenden:
http://www.django-rest-framework.org/api-guide/authentication/#tokenauthentication

Ich würde in Grimlock einen Service-User (z.B. "GEVER") anlegen und das Token dieses Users in GEVER konfigurieren.

Wenn möglich würde ich dass anschliessend mit "RemoteUserAuthentication" ( http://www.django-rest-framework.org/api-guide/authentication/#remoteuserauthentication) kombinieren, so dass auf Seite Grimlock die Requests im Namen und im Security-Context des effektiven Users, der geklickt hat, ausgeführt wird.
Wenn dies nicht kombinierbar ist würde ich alles im Namen des Service-Users machen und auf Seite GEVER sicherstellen dass nur zugelassene User den Button klicken können.

**Comment by phgross** [comment]
Eine direkte Verbindung von GEVER zu Grimlock, ist zurzeit nicht geplant. Mit #4954 konnten die Bedürfnisse der Kunden soweit erfüllt werden.
