### ISSUE TITLE
Update Force checkin documentation

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#4083]
We should complement the documentation on Force checkin to:
* State that force checkin will unlock locked documents
* That doing this will eventually cause conflicts for the person having the document open in office connector
* Update the screenshots as the `Checkin with comment` button will now be available, and not only the action in the menu (when applicable, i.e. for Administrators)

See https://github.com/4teamwork/opengever.core/pull/4040#pullrequestreview-101922204
and issue #3716

**Comment by phgross** [comment]
Done via #4226
