### ISSUE TITLE
Check-in-anyway can be circumvented via table actions

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4091]
The "check in anyway" safeguard can be accidentaly circumvented by choosing one of the `"Mit Kommentar einchecken"` or `"Ohne Kommentar einchecken"` actions on a table in the documents tab (for checkin in documents *en masse*).

**Steps to reproduce**

- Check out several documents using OfficeConnector
- Keep them open on the client side
- Select those documents in the `Documents` tab and choose the `"Ohne Kommentar einchecken"` action

![mass_check_in](https://user-images.githubusercontent.com/405124/37774049-74757eaa-2ddf-11e8-82f0-084e4d45fc75.png)

A possible solution should deal with the following apect:
- If the user is presented with a "check in anyway" option, it should be clear to him, which documents this applies to (only a subset of the selected documents may be in the "still open on client side" state). IMHO this is a piece of information the user needs to make an educated decision.

**Comment by buchi** [comment]
It shouldn't be possible to checkin locked documents through "Weitere Aktionen" -> ".. einchecken".
It doesn't matter if the user chooses with or without comment. If multiple documents are selected, checkin of locked documents should fail.

Checkin for locked documents should be only possible for a single document using the checkin form
