### ISSUE TITLE
demo.onegovgever.ch: Footer anpassen

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#4097]
Die Policy befindet sich im Repository https://github.com/4teamwork/opengever.demo/

Bitte am Footer anpassen: 

- Spalte "Über OneGov GEVER": Eintrag Innovation Day entfernen. Swiss Made Software weiterhin verwenden
- Spalte "Optionen":
  - Zusätzlich folgender Eintrag: "OneGov GEVER Drag’n’Drop for Outlook": https://www.4teamwork.ch/blog/neue-integration-onegov-gever-drag2019n2019drop-for-outlook
- Spalte "Dokumentation": 
  - "Anwender-Dokumentation": https://docs.onegovgever.ch/user-manual/
  - "Entwickler-Dokumentation": https://docs.onegovgever.ch/dev-manual/
  - "Feedback Forum": https://feedback.onegovgever.ch
  - API: https://docs.onegovgever.ch/dev-manual/api/
- Kontakt: Bei Adresse noch "Schweiz" ergänzen (unterhalb von 3013 Bern). Supportnummer "+41 31 511 04 04" (mit Landesvorwahl). E-Mail-Adresse korrigieren: support@4teamwork.ch

**Comment by deiferni** [comment]
(wird mit den nächsten update der demo aktiv, denke in max. 2-3 wochen)
