### ISSUE TITLE
OGIP 32: REST API for favorites

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#4102]
In order for the frontend to manage favorites, REST API endpoints for favorites should be added.
Endpoints. All endpoints must be personalized (user_id must be current user).

Endpoints:
- `@toggle-favorite` - add to / remove from my favorites - on any dexterity object; should return `True` when the context is now a favorite.
- `@list-favorites` - list of all my favorites
  - `title`
  - `icon_class` (e.g. `icon-dokument_word`)
  - `url` (https://dev.onegovgever.ch/fd/resolve_oguid/fd:1863868334 ; requires #4101 )
  - `tooltip_url` (only for documents; https://dev.onegovgever.ch/fd/resolve_oguid/fd:1863868334/tooltip ; requires #4101 )
  - returns results for _all_ admin units
- `@list-repository-favorites`
  - will replace the current [repository favorites endpoint](https://github.com/4teamwork/opengever.core/blob/026471b04ac1b4a1b68275283ad823e40ea36204/opengever/portlets/tree/favorites.py#L72)
  - returns all favorites of repository folders on the current admin unit for the current user
  - represents favorites as list of UIDs in order to be compatible with the navigation implementation
  - returns results only for the _current_ admin unit
- `@remove-favorite`
  - remove a favorite (e.g. by `oguid`)
  - should support removing favorites on other admin units, thus should not be a context-aware endpoint; maybe use on site root
- `@rename-favorite`
  - change the title of a favorite
  - must set the `title_personalized` flag to true

_harvest: `Feature: Favoriten (OGIP 32)`_

**Comment by lukasgraf** [comment]
@jone please use hyphens (`@toggle-favorite` instead of `@toggle_favorite`, etc..)  for the endpoint names, so that they're consistent with `plone.restapi`. See [Conventions > Attribute names in URIs](http://plonerestapi.readthedocs.io/en/latest/conventions.html#attribute-names-in-uris)

**Comment by jone** [comment]
@lukasgraf sure, thanks for the hint!

**Comment by phgross** [comment]
Favorite Endpoints wurden mit #4133 umgesetzt.
