### ISSUE TITLE
OGIP 32: manage favorites

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#4108]
The user should be able to manage the personal favorites, therefore we build a managment view.

- implement with VueJS
- accessible via favorites menu from #4107
- list favorites from `@list-favorites` (#4102), including favorites of other admin units
- show tooltip for documents (`tooltip_url`) on hover
- show object type icon
- show admin unit title
- reorder favorites with drag'n'drop
- remove favorite (`@remove-favorite`, #4102)
- change favorite title (`@rename-favorite`, #4102)

![3 1](https://user-images.githubusercontent.com/7469/37980353-344cac3a-31eb-11e8-9de5-c199d4754e00.png)

_harvest: `Feature: Favoriten (OGIP 32)`_

**Comment by maethu** [comment]
Frontend branch: https://github.com/4teamwork/opengever.core/tree/mle-favorites-frontend
