### ISSUE TITLE
OGIP 32: update documentation

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#4110]
The documentation must be updated to include the new features of OGIP 32.

_harvest: `Feature: Favoriten (OGIP 32)`_

**Comment by phgross** [comment]
@livschal das neue Feature ist unterdessen umgesetzt und auf DEV eingespielt. Kannst du die Dokumentation entsprechend erweitern und anpassen.
Das Feature wurde gemäss OGIP umgesetzt.
