### ISSUE TITLE
OGIP 26 Sequentielle Abläufe

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4122]
OGIP: https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2007/document-19606
Rapportierung: `Sequentielle Aufgaben - OGIP 26`

**Comment by phgross** [comment]
OGIP 26 wurde umgesetzt und auf dem DEV eingespielt. Fachliche QS folgt nächste Woche durch Su.
