### ISSUE TITLE
OneOffixx: Dokument aus Vorlage Formular

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#4134]
Ähnlich wie bestehendes Formular `document_with_template`.
Zusätzliches Auswahlfeld für Vorlagengruppe.

![bildschirmfoto 2018-04-09 um 13 36 03](https://user-images.githubusercontent.com/270502/38495747-0b4c3804-3bfb-11e8-90be-a3b4b6112faf.png)

Liste der verfügbaren Vorlagen über WebAPI von OneOffixx abfragen.
Nur Vorlagen der ausgewählten Gruppe anzeigen.
Spalten "Erstellt von"  und "Zuletzt Bearbeitet" nicht anzeigen. Evtl. gibt es seitens OneOffixx sinnvolle Metadaten zum Anzeigen.

WebAPI ist hier dokumentiert.
https://o10005.oneoffixx.com/webapi/swagger/

Eintrag im Hinzufügen-Menu: Dokument aus OneOffixx-Vorlage

Bei Submit Dokument erstellen im State `shadow-state`.
ID der ausgewählten Vorlage in Annotations auf dem Dokument speichern.

Danach Aufruf von `oc:<JWT>`
Falls möglich via Redirect oder sonst mit JS.

https://github.com/4teamwork/opengever.core/blob/938725eee60b0d0f27e0e56fcd66cec11773dc2c/opengever/base/redirector.py#L94-L104

Ähnlich wie `officeconnector_checkout_url` View.
z.B.
http://localhost:8080/fd/ordnungssystem/1/1/dossier-14/document-201/officeconnector_oneoffix

**Comment by njohner** [comment]
Documentation is now on https://o10002.oneoffixx.com/webapi/swagger/

**Comment by phgross** [comment]
First part of the API calls, but without authorization `pg_oneoffixx_api`
