### ISSUE TITLE
OneOffixx: View zum Erstellen/Download des Connect XML

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#4135]
XML-Dokument gemäss Schema (http://docs.oneoffixx.com/connect/de/xml-schema/) erstellen.
Download über Dokument-View `oneoffix_connect_xml`

Falls Dokument nicht im `shadow-state` -> 404
`TemplateId` aus Annotations, falls keine `TemplateId` Element weglassen

OGG Metadaten als `CustomInterfaceConnector` übergeben.
Siehe: http://docs.oneoffixx.com/connect/de/functions/custominterface/
Beispiel:
```xml
<Function name="CustomInterfaceConnector" id="70E94788-CE84-4460-9698-5663878A295B">
  <Arguments>
    <Interface Name="OneGovGEVER">
      <Node Id="ogg.document.title">My Document</Node>
      <Node Id="ogg.document.reference_number">FD 9.5.0 / 1 / 201</Node>
      <Node Id="ogg.document.sequence_number">201</Node>
    </Interface>
  </Arguments>
</Function>
```

Zusätzliche können diese als DocProperties übergeben werden.
(siehe http://docs.oneoffixx.com/connect/de/functions/metadata/)

```xml
<Function name="MetaData" id="c364b495-7176-4ce2-9f7c-e71f302b8096">
  <Arguments>
    <Value key="ogg.document.title" type="string">My Document</Value>
    <Value key="ogg.document.reference_number" type="string">FD 9.5.0 / 1 / 201</Value>
    <Value key="ogg.document.sequence_number" type="string">201</Value>
  </Arguments>
</Function>
```

Beispiel:
http://docs.oneoffixx.com/connect/de/usecases/create-document/

Update:
 - use lxml to generate the xml.

**Comment by Rotonen** [comment]
Please do both `CustomInterfaceConnector` and `MetaData`.

Things I'd like to have for OfficeConnector in the XML:

Within `<OneOffixxConnectBatch />`:

I want the result XML file flushed out in any case. I'd not like for Oneoffixx to get rid of the input XML file for me.
```
<Settings>
  <Add key="KeepConnector">true</Add>
  <Add key="CreateConnectorResult">true</Add>
  <Add key="CreateConnectorResultOnError">true</Add>
</Settings>
```

Within `<OneOffixxConnect />`:

I need the template id. The language code identifier is mandatory.
```
<Arguments>
  <TemplateId>06149cd5-efe1-47e5-a822-993fa1b65ef0</TemplateId>
  <LanguageLcid>2055</LanguageLcid>
</Arguments>
```

Within `<Commands />`:

We do not want to open the editor via Oneoffixx.
```
<Command Name="DefaultProcess">
  <Parameters>
    <Add key="Start">false</Add>
  </Parameters>
</Command>
```

We want to flush the template out onto a document.
```
<Command Name="ConvertToDocument" />
```

I'll fill in the filename, so it should be left empty.
```
<Command Name="SaveAs">
  <Parameters>
    <Add key="Filename">%userprofile%\Desktop\foobar\foo.docx</Add>
    <Add key="Overwrite">true</Add>
    <Add key="CreateFolder">true</Add>
    <Add key="AllowUpdateDocumentPart">false</Add>
  </Parameters>
</Command>
```
