### ISSUE TITLE
OneOffixx: oc_oneoffixx Service

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#4137]
Similiar to OfficeConnectorCheckoutPayload.

Lives on the site root and operates via the document UUID.
https://github.com/4teamwork/opengever.core/blob/c723c47a8e668b9f9b35e9ba827a330e77260ba1/opengever/officeconnector/configure.zcml#L61-L68

https://github.com/4teamwork/opengever.core/blob/c723c47a8e668b9f9b35e9ba827a330e77260ba1/opengever/officeconnector/service.py#L88-L128

Includes `oneoffixx-connect-xml-url` defined in #4135

**Comment by Rotonen** [comment]
Rather just have the oneoffix creation payload open a browser with a checkout-redirect to the freshly created document and completely avoid having to build this?

**Comment by Rotonen** [comment]
Deemed unnecessary.
