### ISSUE TITLE
UnicodeDecodeError in TabbedView

### ISSUE THREAD

**Issue by mbaechtold** [4teamwork/opengever.core#4141]
Gemeldet durch Kunde im Extranet Ticket https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/46

Traceback im Sentry: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/5537/

Ursache ist das Zeichen `\uf04a` in `task.text`

**Comment by tarnap** [comment]
https://stackoverflow.com/questions/23981635/how-to-convert-u-uf04a-to-unicode-in-python

This is a special character!
