### ISSUE TITLE
Allow pending data migrations to be tagged via an upgrade step

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4150]
🚧 once this is implemented:
- [x] tag the upgrade added in https://github.com/4teamwork/opengever.core/pull/4553/ as deferrable

Develop a mechanism that allows upgrade steps to tag a Plone site with the fact that a particular data migration still needs to be done.

---
**Rationale**
Sometimes, when we fix an issue in code, the problem is solved for new content created using the fixed code, but old objects still might need to be fixed / migrated. We usually defer this process and perform it using a script in `opengever.maintenance`, in order to decouple it from deploying the actual upgrades.

We separate these data migrations from upgrades because these data migrations are potentially long running, and prone to surprises that are hard to test for.

---

We could however just tag the deployment with the fact that a particular data migration still needs to be done (by introducing a **unique identifier for that specific data migration**). That would be extremely quick, and not prone to any surprises, and could therefore easily be done from an upgrade step.

The data migration script in `opengever.maintenance` then would be tied to that unique identifier, and set it to done once it's performed its job. That would allow us to:

- Keep track of what deployments data migrations have already been executed
- Make sure we don't miss any
- Get a historical record for each deployment of what data migrations have been run, and when
- Provide the basis for a more automated execution of data migrations

See #2290 (Scheduled maintenance tasks) for a broader overview regarding automation of tasks like these.

**Comment by deiferni** [comment]
parts of this will be tackled in https://github.com/4teamwork/ftw.upgrade/issues/165
