### ISSUE TITLE
Favorites frontend doesn't handle outdated state properly

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4164]
If the backend state of a favorite changed in the background, and the client side information in a tab is outdated, the frontend doesn't handle the HTTP responses properly, and therefore doesn't correctly update the favorite graphic.

**Steps to reproduce**
- Create a favorite for a dossier
- Open the same dossier in two tabs
- Remove the favorite in one tab
- Try removing it in the other tab:
  - The HTTP `DELTE` request gets answered with `404` (because the fav was already removed). The frontend interprets that as `fail`, and doesn't properly update the graphic/state.

The frontend should also expect a `404`, and consider that a `success`.

The same problem might exist in the reverse direction (adding a favorite).

![favorites_delete](https://user-images.githubusercontent.com/405124/38856993-576cd9fe-4228-11e8-89bc-783ceb1a7a52.gif)

**Comment by phgross** [comment]
Probleme wurden noch im PR #4513 behoben (siehe https://github.com/4teamwork/opengever.core/pull/4153#issuecomment-382004516)
