### ISSUE TITLE
Standardablauf um Feld "Typ" erweitern

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4170]
Der Standardablauf soll um ein Feld `Typ` mit den Werten `Parallel` und `Sequentiell` erweitert werden.

![image](https://user-images.githubusercontent.com/485755/38913507-56e1e444-42db-11e8-89fa-77e32bdfb968.png)

Todos:
 - [ ] Schema erweitern
 - [ ] Typ in der Byline eines Standardablaufs darstellen

**Comment by elioschmutz** [comment]
@phgross Das Todo sieht momentan nur vor, dass der Typ ausgewählt werden kann und dass dieser in der Byline angezeigt werden soll.

- Was ist mit der Funktion selbst? Soll/Muss die nicht implementiert werden? Falls doch, gibt es da eine Spez?
- Soll der Typ nur in der Byline des Standardablauf-Folders angezeigt werden? Und nicht z.B. noch im "Auswahl Standardablauf"-Formular?
