### ISSUE TITLE
Bearbeiten von *.xlsm Dateien z.T. nicht möglich

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4180]
Ursache für die Probleme ist der Mimetype Check in der `is_office_connector_editable` Methode ( https://github.com/4teamwork/opengever.core/blob/master/opengever/document/document.py#L262), welcher case sensitive implementiert ist.

Beim fehlerhaften Dokumente wurde aber der Mimetype `application/vnd.ms-excel.sheet.macroenabled.12` gesetzt. In der Konfigurationsliste steht aber nur die Schreibweise `application/vnd.ms-excel.sheet.macroenabled.12`.

@lukasgraf @Rotonen würdet ihr die Überprüfung case insensitive machen oder muss man dieses Dokument noch genauer untersuchen?

[Extranet Issue](https://extranet.4teamwork.ch/support/gever-ai/tracker/301)

**Comment by Rotonen** [comment]
Huh? Did you copy paste the wrong mimetype for the other?

```
>>> 'application/vnd.ms-excel.sheet.macroenabled.12' == 'application/vnd.ms-excel.sheet.macroenabled.12'
True
```

But trivial input lowercasing should indeed do the trick in regards to normalization as far as I can see.

```
`return self.content_type().lower() in api.portal.get_registry_record('opengever.officeconnector.interfaces.IOfficeConnectorSettings.officeconnector_editable_types')`
```

**Comment by deiferni** [comment]
side note: in that case please also lower-case the values read from the registry or make sure the registry is always lower cased. it currently contains mixed case entries which would break.

**Comment by lukasgraf** [comment]
👍 for case-insensitive comparisons.
