### ISSUE TITLE
Dokumentation OGIP 26 sequentielle Standardabläufe

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4183]
Folgende Kapitel müssen überarbeitet bzw. neu erfasst werden:
- Aufgaben (ablehnen von Aufgaben, storniert --> abbrechen, Neu Stati) 
- Standardabläufe (sequentielle Abläufe, Formular etc.)

**Comment by phgross** [comment]
@livschal das Feature ist nun fertiggestellt und auf dem DEV System eingespielt. Du kannst das Feature nun dokumentieren ... (das ganze wurde gemäss OGIP 26 umgesetzt).

**Comment by livschal** [comment]
done, siehe hier: https://github.com/4teamwork/opengever.core/pull/4618
