### ISSUE TITLE
Antragsdokumente als Anhang anderer Anträge zulassen.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4192]
Im Moment können die Antragsdokumente eines anderen Antrags im selben Dossier nicht als Anhang eines Antrags ausgewählt werden. Dies soll korrigiert werden, Anträge und ihre Dokumente sollen ebenfalls in der Liste der möglichen Anhängen eines (neuen) Antrags erscheinen.

![screen_shot_2018-04-19_at_14_21_51](https://user-images.githubusercontent.com/736583/38991186-1a8aed76-43dd-11e8-8586-7b07863acf5f.png)

Ref: https://basecamp.com/2768704/projects/13732725/todos/340578316

**Comment by Rotonen** [comment]
Closed via https://github.com/4teamwork/opengever.core/pull/4375
