### ISSUE TITLE
move plonetheme.teamraum -> opengever.core as namespace package.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4198]
A quick experiment already exists in https://github.com/4teamwork/opengever.core/tree/deif-vendorize-pttr.

IIRC the following things need to be done:
- [x] copy package 😄 
- [x] adapt `setup.py`
- [x] adapt manifest
- [x] inlcude tests
- [x] drop plonetheme.teamraum subsite tests
- [x] port plonetheme.tamraum dev toolchain (not done in experiment)
- [x] optional: start removing non-GEVER content

Please first copy and commit the whole `plonetheme.teamraum` package though and then expose changes in separate commits. Don't put everything into one commit as i have done on the experimental branch.

**Comment by lukasgraf** [comment]
Icons are still missing. I fixed the missing SCSS, but originals from `plonetheme/teamraum/resources/   images  /icons/` are still missing.
