### ISSUE TITLE
Update Solr to 7.3

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4209]
Solr 7.3 was recently released. We should update, in order to fix full text extraction for EML mails.

---
(EML E-Mails currently don't get their `SearchableText` indexed, Tika in Solr 7.2 fails with `java.lang.NoClassDefFoundError: org/apache/james/mime4j/stream/MimeConfig$Builder`.)

This seems to be resolved in Solr 7.3:
https://issues.apache.org/jira/browse/SOLR-11622

**Comment by lukasgraf** [comment]
Requires 4teamwork/ftw.solr#118

**Comment by phgross** [comment]
`ftw.solr` 2.1.2 has been pinned with #4289 and installed on the DEV. We'll now test the new version on `opengever.ftw` first. Work done for now.
