### ISSUE TITLE
Searching for contact in add participation form does not work

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4213]
When searching for an existing contact via the Keywordwidget, all existing contacts are returned.

Problem:
 - The `_extend_terms_with_contacts`  in the `UsersContactsInboxesSource` queries the catalog filtering on the `SearchableText`, but if SOLR is enabled no `SearchableText` index exists.

See https://github.com/4teamwork/opengever.core/blob/master/opengever/ogds/base/sources.py#L637 and https://github.com/4teamwork/opengever.core/blob/master/opengever/ogds/base/sources.py#L427

Contact feature flag needs to be disabled.

Solution:
 - Queries the SOLR instead of the catalog to fetch the catlaogs when SOLR is enabled

**Comment by tarnap** [comment]
I found this after some guessing:
<img width="962" alt="screen shot 2018-04-24 at 10 53 06 1" src="https://user-images.githubusercontent.com/194114/39176705-bd83f54e-47ad-11e8-8b9d-ab8256ee8244.png">

How do I activate Solr and delete the existing index?
