### ISSUE TITLE
Add `today` to sablon fields

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#4216]
The date of generation is required in the agenda item list.
Since date fields are not updated when the sablon process is run, the current date needs to be passed as additional field.

The date output format needs to be determined.

## Please read discussion:
https://basecamp.com/2768704/projects/13732725/todos/339163209#comment_614401493

**Comment by tarnap** [comment]
The date format could be taken from the registry.
Do our customers use this fields?

<img width="689" alt="screen shot 2018-05-25 at 17 54 09" src="https://user-images.githubusercontent.com/194114/40554030-c4615870-6044-11e8-93b8-fc601e51758a.png">

**Comment by tarnap** [comment]
I propose to activate the `override_dateformat` and set these values to something, the customers can use.

**Comment by deiferni** [comment]
@tarnap i would not use `override_dateformat` as that will/might 🤔  also change the format in the UI. I would decouple formatting the date in the UI from formatting the date in generated word files as  the requirements are most likely different. instead i would add a new registry entry that can be set to override whatever we use as a default.

I would insert the data at the same place we insert the other data. Have a look at https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/protocol.py#L50-L53, that should be used for all templates.

**Comment by lukasgraf** [comment]
@tarnap exactly what @deiferni said ⬆️ 😉

**Comment by deiferni** [comment]
Ok so the formating will be solved with https://github.com/4teamwork/opengever.core/issues/4193
