### ISSUE TITLE
Anpassen des Dokument Dateinamens

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4217]
Zurzeit noch ein Platzhalter, endgültige Spezifikation folgt noch.

Spezifikation:
- Der Dateinamen wird auf 100 Zeichen erweitert
- Dateinamen von bestehenden Dokumenten wird aktualisiert (Upgradestep)
- Normalisierung: 
  - Sonderzeichen (`\`, `/` etc.) sollen entfernt werden
  - Gross und Klein Schreibung soll erhalten bleiben
  - Leerzeichen sollen bestehen bleiben (evtl. müssen Sonder-Leerzeichen auch normalisiert werden)
  - Umlaute sollen wie gehabt normalisiert werden (`ä` wird zu `ae` etc.)

siehe [Feedback-Forum Diskussion](https://feedback.onegovgever.ch/t/dateinamen-und-dokumenttitel/917)

**Comment by deiferni** [comment]
Input hierzu, ich habe das vor einiger Zeit kurz angeschaut. Wir brauchen einen `IIDNormalizer` um den Dateinamen zu normalisieren, man könnte vermutlich auf einen `IFileNameNormalizer` umstellen.

**Comment by lukasgraf** [comment]
Vorschlag für endgültige Spezifikation:

---

The filename will be normalized by substituting special characters that aren't considered safe, and [transliterating](https://en.wikipedia.org/wiki/Transliteration) commonly used non-ASCII characters from German and French with their best equivalent.

Normalization is performed by applying these steps in order:

- **Custom transliteration** of German Umlauts and other common special characters
  - `Ä` -> `Ae`
  - `Ü` -> `Ue`
  - `Ö` -> `Oe`
  - `ä` -> `ae`
  - `ü` -> `ue`
  - `ö` -> `oe`
  - `&` -> `+`

- **Fallback transliteration** of non-ASCII letters

  Other non-ASCII letters will be transliterated using the [Unidecode module](https://pypi.org/project/Unidecode/).
  This will result in sensible transliterations for French letters with diacritics and other common languages.

  Examples:

  - `é` -> `e`
  - `è` -> `e`
  - `à` -> `a`
  - `ç` -> `c`

  - `ñ` -> `n`
  - `æ` -> `ae`

- **Safe punctuation characters** will be preserved:
  - `-` (dash)
  - `_` (underscore)
  - `.` (period)
  - `,` (comma)
  - `+` (plus sign)
  - ` ` (space)
  - `=` (equals sign)
  - `(`
  - `)`

- Every other non-ASCII character will be **replaced with a space**
- All **consecutive spaces** will be replaced by a single space
- Total length will be **truncated to 100 characters**
