### ISSUE TITLE
Zuletzt bearbeitete Dokumente darstellen.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4218]
Spez: https://gever.4teamwork.ch/ordnungssystem/3/2/2/1/dossier-2634/document-23853

**Comment by lukasgraf** [comment]
Umsetzung gemäss Spez.

Der Fokus soll zuerst auf den zuletzt bearbeiteten Dokumenten liegen - wie die zur Zeit ausgecheckten Dokumente integriert werden, muss noch genauer angeschaut werden (diese in eine gruppierte Auflistung zu kombinieren, hat den Nachteil dass ausgecheckte Dokumente immer in beiden Gruppen aufgelistet würden).

**Comment by phgross** [comment]
Closed via #4391
