### ISSUE TITLE
TaskTransitionController.all_subtasks_finished does not handle successor pairs.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4230]
The current [`all_subtasks_finished`](https://github.com/4teamwork/opengever.core/blob/master/opengever/task/browser/transitioncontroller.py#L565) check in the transition controller, currently only checks for subtasks of the current task but it should also check for subtasks on the successor or predecessor if there are some. 

Otherwise it can lead to confusing failures when trying to resolve a task on the predecessor site, with subtasks on the successor site. 

https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20377

**Comment by tarnap** [comment]
# Challenge
When working with multi admin setups, tasks may span over several admin
units.

We assume to have two admin units: FD and RK

Anton creates a task in FD and gives it to Berta in RK
At the same time, Anton delegates the task to Carlos and David in FD
When Berta tries to resolve the task, the subtasks delegated to Carlos
and David should be checked for completeness as well.

Therefore the check on Berta's side should get all the subtasks from
Berta's and Anton's task.

# Behaviour with 19047ed
When Anton delegates the task to Carlos and David, the resolve button for Berta is not displayed anymore.

<img width="1920" alt="screen shot 2018-05-24 at 11 30 39" src="https://user-images.githubusercontent.com/194114/40477377-936f0d74-5f46-11e8-8be3-464310a70502.png">

# Questions
What should happen on Berta's side, when the subtask by Carlos and David are resolved?
