### ISSUE TITLE
Dokument ersetzen

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#4234]
Auf Basis Inputs Feedbackforum https://feedback.onegovgever.ch/t/dokument-ersetzen/870/8 soll der Vorgang eines Dokumentes zu ersetzen folgendermassen umgesetzt werden:

- Neues Dokument reinziehen
- Popup-Frage: Wollen Sie das Dokument X mit dem neuen ersetzen (als neue Version)? Ja/Nein.
- Auschecken (einchecken im Hintergrund automatisch)

**Comment by phgross** [comment]
im neuen UI gelöst.
