### ISSUE TITLE
Error bei Aufgaben und Anträgen, physical_path zu lang

### ISSUE THREAD

**Issue by raphael-s** [4teamwork/opengever.core#4235]
See -> https://extranet.4teamwork.ch/support/gever-ai/tracker/302
Sentry -> https://sentry.4teamwork.ch/sentry/onegov-gever/issues/5595/

Der `physical_path` für Aufgaben und Anträge ist zu kurz. Am besten wäre hier eine Text-Column ohne Beschränkung der Länge zu verwenden.

Bitte auch überprüfen ob noch weitere Inhalte den `physical_path` in einer 256 Zeichen langen Spalte speichern und falls ja korrigieren.

**Comment by deiferni** [comment]
Update: das Problem ist nicht der Titel, sondern `physical_path`. Dieser ist auch auf 256 Zeichen begrenzt, d.h. man kann ihn mit einer sehr langen Ordnungsposition schon füllen. Ich denke wir sollten hier eine Umstellung auf `Text` in Erwägung ziehen.

**Comment by Rotonen** [comment]
Inidices on text fields are full of gnarly.

Here is one such approach:
https://www.postgresql.org/message-id/opsdu638jlcq72hf%40musicbox

**Comment by deiferni** [comment]
i'm expecting we mostly do equality checks and maybe wildcard searches with the wildcard on the rightmost side of the string.

the example is 14 years old  😂, also i'm not sure if that is the same use-case (it seems a bit theoretical), they talk about storing a checksum in a separate column for performance reasons 🤔.

**Comment by jounsiboss** [comment]
Betrifft auch https://extranet.4teamwork.ch/support/gever-ai/tracker/304

**Comment by maethu** [comment]
Wurde nun ebenfalls bei https://extranet.4teamwork.ch/support/stadt-nidau/tracker-gever/102 gemeldet.
