### ISSUE TITLE
Subdossier cannot be closed / resolved if parent dossier contains documents

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#4260]
If a dossier contains documents.

![bildschirmfoto 2018-05-02 um 16 59 33](https://user-images.githubusercontent.com/194114/39531089-b584766a-4e2a-11e8-91ec-9d03bd20e6c2.png)

And one of its sub-dossiers is closed:
![bildschirmfoto 2018-05-02 um 16 59 50](https://user-images.githubusercontent.com/194114/39531124-c8cf8d18-4e2a-11e8-8398-9e9532bed238.png)
![bildschirmfoto 2018-05-02 um 17 00 02](https://user-images.githubusercontent.com/194114/39531125-c8f43500-4e2a-11e8-9dd6-735dce440695.png)

Then an error occurs:
![bildschirmfoto 2018-05-02 um 17 00 12](https://user-images.githubusercontent.com/194114/39531216-f7fff974-4e2a-11e8-8909-1eb439697721.png)

See also: https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/254

**Comment by phgross** [comment]
Die Geschäftsregel, welche überprüft, dass alle Dokumente und Aufgaben in Subdossiers versorgt sind sofern Subdossiers existieren, soll **nur** auf Stufe Hauptdossier überprüft werden.

**Comment by tarnap** [comment]
# Workflow transitions for the dossier
<img width="1072" alt="screen shot 2018-05-25 at 08 25 40" src="https://user-images.githubusercontent.com/194114/40529461-3ae06108-5ff5-11e8-96cf-a3b68ff459fe.png">

# The transition
<img width="961" alt="screen shot 2018-05-25 at 08 28 22" src="https://user-images.githubusercontent.com/194114/40529546-b44d4c86-5ff5-11e8-9510-8a7772c99bd1.png">

# The adapter
<img width="961" alt="screen shot 2018-05-25 at 08 28 35" src="https://user-images.githubusercontent.com/194114/40529552-bd930ccc-5ff5-11e8-9c25-e52149ceedec.png">
