### ISSUE TITLE
Abklären: Update TIKA, Unterstützung für Suche von  *.msg Mails

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4262]
Currently searchable text is not extracted by tika/`ftw.tika`. It may not be supported yet in the tika version we use. Also `application/vnd.ms-outlook` seems not to be in `ftw.tika`s list of supported mime-types: https://github.com/4teamwork/ftw.tika/blob/acd87cdf0e5f2c294e365b8bad25ec9f5eac0d97/ftw/tika/mimetypes/__init__.py

we should:
- check what version of tika enables support for outlook
- maybe even use the latest version (1.18 at the time of writing)
- check if that newer tika is supported by `ftw.tika`, if not add support
- enable the new tika version for gever in either https://github.com/4teamwork/gever-buildouts/blob/master/tika-standalone.cfg or maybe even https://raw.githubusercontent.com/4teamwork/ftw-buildouts/master/tika-jaxrs-server.cfg

_This ticket will be obsolete should we decide to quickly switch to SOLR instead._

Ref: https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/58

**Comment by phgross** [comment]
We plan to quickly switch to SOLR so it should be obsolete. I'll move it to the next release so we can double check ...

**Comment by phgross** [comment]
Wir werden längerfristig bei allen Installation auf die SOLR Suche umstellen. Ich sehe hier also kein Bedarf `ftw.tika` zu erweitern/aktualisieren und schliesse deshalb den Issue.
