### ISSUE TITLE
Required Sablon templates on container

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#4267]
The section sablon template is required on the committee container, even though they're optional in the code:

![screen shot 2018-05-07 at 15 25 00](https://user-images.githubusercontent.com/194114/39704179-d624a35c-520a-11e8-8142-f4aed55e6aa2.png)

**Comment by deiferni** [comment]
Closed by https://github.com/4teamwork/opengever.core/pull/4302
