### ISSUE TITLE
IDossierResolveProperties not visible in the configuration view/endpoint

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4280]
The configuration view should also display all resolve properties:
 - purge_trash_enabled
 - journal_pdf_enabled
 - archival_file_conversion_enabled
 - resolver_name

**Comment by tarnap** [comment]
<img width="587" alt="screen shot 2018-05-16 at 09 00 08" src="https://user-images.githubusercontent.com/194114/40101387-8f1fa9aa-58e7-11e8-8742-a2a6b0013c12.png">

**Comment by tarnap** [comment]
The configurations are listed in `opengever/base/configuration.py`.

**Comment by tarnap** [comment]
Result:
<img width="957" alt="screen shot 2018-05-16 at 15 44 05" src="https://user-images.githubusercontent.com/194114/40120682-182474c8-5920-11e8-9a61-20f0c677ffba.png">
