### ISSUE TITLE
Fix icons for documents with mime-types wich do not match the (upper / lower) case

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#4281]
See: https://extranet.4teamwork.ch/support/ph-vs/tracker/506

The documents have lower case mimetypes while the getIcon index has camelcase entries:
<img width="961" alt="screen shot 2018-05-08 at 14 33 21" src="https://user-images.githubusercontent.com/194114/39757345-d81ae64a-52cc-11e8-9858-bc30b91b41ac.png">

A solution is probably to find the getIcon indexer and making the registry mimetype check case insensitive.

**Comment by phgross** [comment]
@Rotonen no those documents are recently uploaded and regular documents. We got the same problem in AI with lower cased contenttypes. It seems that case of the contenttype is browser or OS specific for the macro-office-documents. But in my opinion it does not matter how the contentype gets different, the check for the getIcon index should be case insensitive (see also https://stackoverflow.com/questions/12869278/are-mimetypes-lowercase-case-insensitive)
