### ISSUE TITLE
Compile SASS at instance bootup time

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4317]
As libsass has Python libraries available and we've vendored in the theme again, we could tie it tighter into the normal development / deployment workflow and not commit the compiled outputs into the repo.

https://sass-lang.com/libsass

**Comment by phgross** [comment]
Ich verschiebe diesen Issue aufgrund der [Besprechung des Architekturteams](https://gever.4teamwork.ch/ordnungssystem/3/5/3/dossier-2515/document-25476#overview). Wir können die Situation in einigen Monaten nochmals besprechen, analysieren.

**Comment by Rotonen** [comment]
We're moving to use a separate frontend product, this approach is now dead in the water.
