### ISSUE TITLE
Langer Dokument-Kommentar

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#4323]
Erhält ein Dokument einen langen Kommentar, kann dieser nirgends wirklich gut gelesen werden. Daher soll beim Journal-Tab beim drüberhovern der Kommentar als Tooltipp (Alt-Text)dargestellt werden. Mehr Infos siehe hier: https://feedback.onegovgever.ch/t/einchecken-kommentar-nicht-vollstaendig-sichtbar/1014/2 Aktuell wird dort auch abgeklärt, ob zusätzlich in der Vorschau-Ansicht der Kommentar auch angezeigt werden soll.

**Comment by tarnap** [comment]
Gemäss https://feedback.onegovgever.ch/t/einchecken-kommentar-nicht-vollstaendig-sichtbar/1014/5 funktioniert dies bereits im Journal-Tab und muss nur im Versionen-Tab umgesetzt werden.
