### ISSUE TITLE
Dokument drucken aus Vorschau via Browsermenu nicht korrekt

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#4328]
![image](https://user-images.githubusercontent.com/31923504/40352814-2b11beee-5db0-11e8-8bea-220d93c1fad6.png)
![image](https://user-images.githubusercontent.com/31923504/40352896-60ac7346-5db0-11e8-92d3-8c1320c2c705.png)
Drucken via Druckersymbol oben rechts funktioniert.

**Comment by njohner** [comment]
In chrome and in Safari, the browser print button will lead to printing the menu. For printing the document there is a print button which works fine so I don't think we need to fix anything here.
