### ISSUE TITLE
Ordnungssystem-Favoriten styling französisch unschön

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4336]
Styling der Tabs im Nav-Portlet sind unschön bei zu langen Titeln, insbesondere französisch:

<img width="331" alt="screen shot 2018-05-22 at 16 41 17" src="https://user-images.githubusercontent.com/736583/40369859-36d80452-5ddf-11e8-876f-5b4a6b20aabf.png">

**Comment by phgross** [comment]
@bierik es scheint im Firefox und IE 11 noch ein Problem zu geben, kannst du dir das anschauen, wäre gut wenn wir das diese Woche noch korrigieren könnten. 

![image](https://user-images.githubusercontent.com/485755/44454489-fcb69a80-a5fb-11e8-88e0-4ca1f848408c.png)

**Comment by bierik** [comment]
Auf IE11 und Firefox getested. Konnte ich nicht reproduzieren.

<img width="1544" alt="screen shot 2018-10-24 at 14 42 11" src="https://user-images.githubusercontent.com/1637820/47430950-13fc3a80-d79b-11e8-9691-7408ec6287f9.png">

**Comment by bierik** [comment]
Wurde bereits korrigiert
