### ISSUE TITLE
Title padding for add forms got messed up in 2018.3

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4347]
Somehow the padding for the title in add forms got messed up at some point 2018.3:

---

### Before

![padding_before](https://user-images.githubusercontent.com/405124/40486695-42a1c2a8-5f62-11e8-8995-f166c0149f1e.png)

---

### After (current `master`)

![padding_after](https://user-images.githubusercontent.com/405124/40486698-46210c86-5f62-11e8-9d1f-4bc588bfa6d0.png)

---

**Comment by bierik** [comment]
![screen shot 2018-07-04 at 10 10 23](https://user-images.githubusercontent.com/1637820/42265003-99537350-7f72-11e8-9e43-41d6637ec7d7.png)

Ein `inline-block` sollte das Problem lösen. Nur sollte der Stern innerhalb des `h1` elements platziert werden. @phgross könntest du das versuchen ob das möglich ist?

**Comment by phgross** [comment]
@bierik ich habe das abgeklärt, das Stern-Symbol könnte nur mit sehr viel Aufwand und Änderungen an zentralen Templates ermöglicht werden. Könntest du nochmals prüfen, ob ein anderer Ansatz möglich wäre?
