### ISSUE TITLE
Favorites-Button is inconsistently styled

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#4354]
The styling of the favorites button is inconsistent with the other buttons such as the notifications button and the search button.
![bildschirmfoto 2018-05-24 um 22 21 58](https://user-images.githubusercontent.com/7469/40511751-01c41f30-5fa1-11e8-8918-a803b9348609.png)

To me it looks as if the focus is on the favorites button, or as if it had an active state.

The buttons should all be styled the same. If the current style is hard to implement, the style of all buttons can be changed.

**Comment by bierik** [comment]
Es geht in diesem Issue nur um das Aussehen des Knopfes und nicht um die verschiedene Art der Implementation. Dieses Problem können wir in einem separaten Issue attackieren.
