### ISSUE TITLE
Flyup Menupunkte vom "Weitere Aktionen"-Button werden in der Dokumentenauflistung fehlerhaft angezeigt.

### ISSUE THREAD

**Issue by fguyer** [4teamwork/opengever.core#4357]
![image](https://user-images.githubusercontent.com/8034330/40543077-1ea18d86-6023-11e8-9509-2abadfc1e1f7.png)

**Comment by tarnap** [comment]
Ich kann dies nicht reproduzieren.
Bei @fguyer erscheint es wie im Issue gezeigt.
Bei mir ist das Dropdown ein Dropdown:
<img width="964" alt="screen shot 2018-05-31 at 15 44 55" src="https://user-images.githubusercontent.com/194114/40785717-98aa050c-64e9-11e8-8b98-c9f267e554c5.png">

Was mache ich falsch?
