### ISSUE TITLE
Solr-Resultate wirken unberechenbar

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4363]
Soeben in `gever.4teamwork.ch` festgestellt:

(LiveSearch wie auch reguläre Suche)

- Ich suche das Excel-Sheet mit dem Titel `Aufwände Release 2018.3` (AZ ` ftw 3.2.2.1 / 14 / 24362`)
- Beim tippen von `aufwä` in der Livesearch erscheint dieses Dokument zuerst
- Sobald ich aber weiter präzisize (`aufwände`), fliegt das Dokument komplett raus
- Inbesondere wenn ich nach `aufwände release` oder gar `aufwände release 2018.3` suche, hätte ich erwartet dass dieses Dokument hoch gescored wird, da die Begriffe direkt im Titel vorkommen

---

Zusätzlich lässt sich anhand dieses Begriffs ein Problem mit dem Batching-Demonstrieren: Die Suche nach `aufwände` liefert zur Zeit 303 Treffer - navigiert man aber auf Seite 12 des Batches, werden auf einmal 0 Resultate angezeigt.

**Comment by buchi** [comment]
Das Problem mit dem Batching wird durch einen zu kleinen Heap verursacht.
Der Standardwert von 512 MB ist für grössere Installationen zu klein und muss unbedingt angepasst werden. Ich habe gever.4teamwork.ch nun wie folgt konfiguriert:  `jvm-opts = -Xms512m -Xmx2048m -Xss256k`

**Comment by buchi** [comment]
Beim Dokument mit dem Titel "Aufwände Release 2018.3" ist das ä als precomposed Unicode (NFD) erfasst. Anscheinend kann Solr dies nicht korrekt normalisieren. `<charFilter class="solr.ICUNormalizer2CharFilterFactory"/>` sollte das Problem lösen.

**Comment by buchi** [comment]
@deiferni eher nicht. Die Test- und Demosysteme brauchen das z.B. nicht.
