### ISSUE TITLE
Attachment are not displayed on dnd uploaded mails

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4366]
It seems that the eml -> msg conversion stuff drops the attachments. The attachments are not displayed and extracting them is also not possible. The attachment information on the original_message (`*.msg`) is still there.

Example: https://dev.onegovgever.ch/fd/ordnungssystem/bildung/andere-schulen/musikschule/dossier-526/document-1484#overview

[Extranet Issue](https://extranet.4teamwork.ch/support/staatsarchiv-kanton-basel-stadt/tracker/46)

**Comment by Rotonen** [comment]
Got everything running locally and cannot reproduce. More details on the exact path required - this probably has something to do with the exact structure of the original .eml.

Initial guess: some send-side clients might be problematic in how they formulate multipart emails and the addin and/or gever do(es) not handle all the permutations available.

Dropping chasing this for now.

**Comment by phgross** [comment]
Problem wurde gelöst mit einem neuen Build von msgconvert, siehe Extranet Issue für mehr Infos
