### ISSUE TITLE
Document date not persisted in some cases.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4368]
Extranet Issues: 
 - https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20367
 - https://extranet.4teamwork.ch/support/staatsarchiv-kanton-basel-stadt/tracker/44

**Comment by lukasgraf** [comment]
There were display issues on the widget level that got fixed with #4739

The default values still need to be persisted though, I created a follup up issue for this: #4811
