### ISSUE TITLE
Add an ability to fixturize SQL objects

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4369]
Currently in our integration tests we can only fixturize Plone objects.

Should be a fairly straight forward process of building the required serializers and deserializers for the lookup table.

https://github.com/4teamwork/opengever.core/blob/a3e06cec25e61fe3461be1ed9243cd4a0781e333/opengever/testing/fixtures.py#L1289-L1328
https://github.com/4teamwork/opengever.core/blob/a3e06cec25e61fe3461be1ed9243cd4a0781e333/opengever/testing/integration_test_case.py#L236-L262

**Comment by deiferni** [comment]
The relational database is already dumped to `var/test-db-caches/dump.sql`. I'd say we can already do this. Please reopen if you disagree.
