### ISSUE TITLE
E-Mail overview does not list any attachments

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#437]
![bildschirmfoto 2014-07-31 um 08 48 35](https://cloud.githubusercontent.com/assets/485600/3760798/d5e383c8-187e-11e4-9d4a-18515e5a125e.png)

However, attachments are shown in the preview tab

*Rapportierung:* `[INTERN] 3.2 OneGov GEVER  - Weiterentwicklung (Enhancement/Feature)`

**Comment by phgross** [comment]
Meiner Meinung nach ist die Informationen ob Attachments enthalten sind und wenn ja welche, bei einem Mail sehr zentral. Zudem ist davon auszugehen das bei den meisten Benutzern die Übersicht als StandardTab definiert ist, also die "erste Ansicht".

Ich denke diese Unterschied zwischen Mail und Dokument macht hier durchaus Sinn.

Vorschlag:
![bildschirmfoto 2015-05-22 um 15 56 24](https://cloud.githubusercontent.com/assets/485755/7771916/22ae488c-009b-11e5-9ef4-666583a23ad4.png)

@lukasgraf was denkst du? Wollen wir via Feedback Forum bei den Kunden nachfragen?

**Comment by phgross** [comment]
@lukasgraf @phabegger was denkt ihr?

**Comment by phabegger** [comment]
Finde ich gut. Werden von den Anhängen Previews generiert? Oder anders gefragt: Was passiert, wenn ich auf einen der Anhänge klicke, @phgross ?

**Comment by phgross** [comment]
Previews von Anhängen erachte ich als kompliziert. Vorerst nur darstellen der Anhänge umsetzten.

**Comment by phabegger** [comment]
Bitte die Darstellung der Auflistung von Anhängen gleich machen wie in Screenshot in #1842. Die Anzeige der Vorschau bei Attachments wird auch in #1842 behandelt
