### ISSUE TITLE
Schlagworte auf Dokument-Detailansicht nicht ersichtlich

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4370]
Die Schlagwörter eines Dokumentes sollten, ähnlich wie in der Dossierübersicht auch auf der Dokument-Detailansicht dargestellt werden. 

# Soll
![bildschirmfoto_2018-05-28_um_17_53_16](https://user-images.githubusercontent.com/485755/40622096-1ccf4ffa-62a0-11e8-8c4b-beda8f4eedb7.png)

**Comment by tarnap** [comment]
There is a behaviour for the dossier:
https://github.com/4teamwork/opengever.core/blob/9b7278b40241bbdb763eb88aeeed858042dc2016/opengever/dossier/behaviors/dossier.py#L55-L65

There is also a behaviour for the document:
https://github.com/4teamwork/opengever.core/blob/9b7278b40241bbdb763eb88aeeed858042dc2016/opengever/document/behaviors/metadata.py#L71-L81

I guess, I just need to add the behaviour to the metadata rows:
https://github.com/4teamwork/opengever.core/blob/9b7278b40241bbdb763eb88aeeed858042dc2016/opengever/document/browser/templates/overview.pt#L10-L13

And probably here:
https://github.com/4teamwork/opengever.core/blob/9b7278b40241bbdb763eb88aeeed858042dc2016/opengever/document/browser/overview.py#L148-L149

**Comment by tarnap** [comment]
# Taadaa

<img width="959" alt="screen shot 2018-05-30 at 08 03 36" src="https://user-images.githubusercontent.com/194114/40701899-096afb80-63e0-11e8-8154-bb4f0c5b576e.png">

<img width="958" alt="screen shot 2018-05-30 at 08 03 23" src="https://user-images.githubusercontent.com/194114/40701915-111fe2c8-63e0-11e8-882e-532d62932c57.png">
