### ISSUE TITLE
Erstellen von Platzhalter Dokumenten erschwert

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4371]
Will man ein Platzhalter Dokument in einem Dossier ablegen, um z.B. ein Dokument aus einem anderen Dossier zu referenzieren, so muss die Option `in Papierform aufbewahrt` angewählt werden, dies ist im Falle eines Platzhalter-Objekt falsch. Die Validierung des Feldes `in Papierform aufbewahrt` müsste so angepasst werden, das nicht nur das Feld `Datei` sondern auch die verwandten Dokumente überprüft werden.

**Comment by phgross** [comment]
@livschal könnte man im FBF erwähnen, dass dieses Problem in einem kommenden Release behoben wird.

**Comment by phgross** [comment]
@livschal ja genau.

**Comment by tarnap** [comment]
Relevant: https://feedback.onegovgever.ch/t/verknuepfung-links-auf-dokumente/900/9

**Comment by tarnap** [comment]
There is a `FileOrPaperValidator`:
https://github.com/4teamwork/opengever.core/blob/9b7278b40241bbdb763eb88aeeed858042dc2016/opengever/document/behaviors/metadata.py#L176-L215

The related documents come from here:
https://github.com/4teamwork/opengever.core/blob/9b7278b40241bbdb763eb88aeeed858042dc2016/opengever/document/behaviors/related_docs.py#L10-L36

**Comment by tarnap** [comment]
Also: should this ask for a document name or should it take the name of the related document?
<img width="957" alt="screen shot 2018-05-30 at 08 59 57" src="https://user-images.githubusercontent.com/194114/40704360-22518b02-63e8-11e8-8eed-b6803b35bbbb.png">
