### ISSUE TITLE
Create Icon for status `skipped`

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#4379]
We need a new icon for the task status state skip.
It should be based on the fontawesome icon step-forward: 
https://fontawesome.com/icons/step-forward?style=solid

and similar to the other status icons, see `icon-status` files in:
https://github.com/4teamwork/opengever.core/tree/master/plonetheme/teamraum/resources/images/icons

**Comment by phgross** [comment]
hi @bierik, könntest du das Icon bis nächste Woche erstellen? thx
