### ISSUE TITLE
Map the gever_administrators LDAP group to the global Administrator role for examplecontent

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4387]
We do not currently have a convenient way to have users with the Administrator role for local development.

**Comment by lukasgraf** [comment]
Could be done along these lines:
https://github.com/4teamwork/opengever.core/blob/0667dfde9635457be388c8a5ab7a2c49bf9e71e4/opengever/setup/creation/orgunit.py#L49-L51
