### ISSUE TITLE
Ordnungspositionen werden nicht korrekt sortiert.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4398]
[Extranet Issue](https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/70)

Der SortableTitle Indexer (`Products.CMFPlone.CatalogTool.sortable_title`) limitiert den Inhalt des sortable_titles auf 40 Zeichen, durch den vierstelligen 0 prefix welcher bei allen Nummern hinzugefügt wird, führt dies zu einer Limite von nur 5 Nummern. Dies ist bei Ordnungspositionen zu knapp:

**Auszug Analyse Debugging:**
```
self.context.Title
'1.1.1.5.1.1. Dienstzweig Abfallbewirtschaftung und Deponie (AD)'
from Products.CMFPlone.CatalogTool import sortable_title
(Pdb) sortable_title(self.context)()
'0001.0001.0001.0005.0001.00...ponie (ad)'
```

### Lösung:
- [x] Einen separaten `sortable_title` indexer für Ordnungspositionen erstellen, welcher bei der Berechnung der `MAX_SORTABLE_TITLE` Limite, die Aktenzeichennummer nicht beachtet.
 - [ ] Upgradestep der den sortable_title indexer für alle Ordnungspositionen neu berechnet

**Comment by tarnap** [comment]
Sounds nice. Ich schaue es mir morgen im Zug and und komme allenfalls mit Fragen auf dich zu.

**Comment by deiferni** [comment]
Interessanterweise hat man in https://github.com/4teamwork/opengever.core/pull/4429 keinen Upgradestep geschrieben.

**Comment by lukasgraf** [comment]
Wir haben dies besprochen, und entschieden hier noch einen Schritt weiter zu gehen:

- Wir wollen das Limit für den `sortable_title` grundsätzlich anheben, auf einen sehr hohen Wert der eigentlich nicht mehr dazu führen sollte, dass der `sortable_title` überhaupt trunkiert wird. (Anheben auf `opengever.base.model.CONTENT_TITLE_LENGTH` (255) + ein bisschen reserve für das Zero-Padding).
- Dies soll für alle Objekt-Typen gelten, dementsprechend würden wir den `sortable_title` indexer neu auch für alle Objekte überschreiben (und nicht bloss für Ordnungspositionen)
- Dadurch sollte es auch nicht nötig sein, `MAX_SORTABLE_TITLE` von Plone zu patchen, sondern wir können dies direkt in unserem eigenen Indexer steuern
- Danach ein Upgrade-Step, der
   - Den `sortable_title` index für alle Objekte neu rechnen (aber nur den Index, und spezifisch noch in Solr indexiert)
   - `deferrable` ist
