### ISSUE TITLE
Französiche Übersetzung fehlt bei Aufgaben

### ISSUE THREAD

**Issue by bbuehlmann** [4teamwork/opengever.core#4403]
<img width="677" alt="ubersetzung aufgaben" src="https://user-images.githubusercontent.com/1231822/40958097-549e7c46-6898-11e8-8f1c-0222753d47f7.png">

**Comment by phgross** [comment]
Das Problem liegt in der Sprache. Es wurde `fr-ch` ausgewählt, die vdexvocabularies wurden aber nur nur für `fr` übersetzt. @deiferni @njohner war `fr-ch` eine bewusste Entscheidung?

Siehe auch https://github.com/4teamwork/opengever.phvs/blob/master/opengever/phvs/profiles/default/portal_languages.xml#L4

**Comment by njohner** [comment]
Also es handelt sich hier um demo? Denn war das nicht eine Bewusste Entscheidung. Das müssen wir wohl im Profile noch setzen.
