### ISSUE TITLE
Tab Anträge auf Ordnungspositionen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4411]
Mit https://github.com/4teamwork/opengever.core/pull/3868 wurden Dokumente und Aufgaben auf Ordnungspositionen dargestellt. Für Anträge soll nun auch ein solches Tab eingebaut werden da hier sehr ähnliche Anforderungen bestehen.

- Tab nur darstellen, wenn das `meeting` Feature aktiviert ist.
- Neues Flag, damit Tab deaktiviert werden kann (Analog Dokumente/Aufgaben) auch wenn `meeting` Feature aktiv ist. Per Default soll das Tab aber erscheinen (aber nur falls `meeting` Feature aktiv).
- Neue Spalte Dossier im Antrags-Tab, so dass direkt zum Dossier navigiert werden kann
- Reihenfolge beachten, gleich wie im Dossier, sprich nach Aufgaben-Tab
- In Gever-Config (`IGeverSettings`) View aufnehmen, z.B. als Option `repositoryfolder_proposals_tab`

Ref: https://basecamp.com/2768704/projects/13732725/todos/349420332#comment_626191116.

**Comment by Rotonen** [comment]
@deiferni while mulling over the columns, a thought arises - do they actually want quick access to the proposals or to the proposal documents? As in list proposals and have a column to link to the proposal documents? Or the other way around?

**Comment by deiferni** [comment]
yes, but the proposal document would already be visible in the documents tab which is also available globally (introduced in a recent release). But i like the idea of adding a column for the proposal document. @Rotonen could you spin this off into a separate issue.
