### ISSUE TITLE
OGIP 36: Erfassung neuer Rollen & NotificationDefaults in opengever.activity

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4413]
- Erfassung neuer Rollen Antragssteller: `PROPOSAL_ISSUER_ROLE` und 
Gremien-Verantwortlicher:  `COMMITTEE_RESPONSIBLE_ROLE` in https://github.com/4teamwork/opengever.core/blob/7ed3dbf6aa29eea4f28d8bbb3513726332260e04/opengever/activity/roles.py.
- Erfassung/Definition neuer Defaults für die folgenden Arten von Benachrichtigung:
  - Benachrichtigung per default an Antragssteller:
    - Antrag zurückgewiesen
    - Antrag traktandiert
    - Antrag beschlossen (bzw. Protokollauszug an Antragsteller/Antragsdossier zurückgesendet , ⚠️  OGIP erwähnt hier u.U. 2 unterschiedliche Aktionen, richtig ist aber nur **eine** Aktion)
    - Antrag kommentiert
  - Benachrichtigung per default an Gremien-Verantwortliche:
    - Neuer Antrag eingereicht
    - (Eingereichter-) Antrag kommentiert
    - Anhänge eingereichter Antrag aktualisiert
- Upgrade-Step für neue Defaults
Als Inspiration kann https://github.com/4teamwork/opengever.core/commit/a7e0ca000e0c2c7b83fb5acacd47c4a24f3d1d27 und https://github.com/4teamwork/opengever.core/pull/2784 dienen.

Harvest: _`Feature: Benachrichtigung SPV - OGIP 36`_

**Comment by elioschmutz** [comment]
@deiferni Momentan unterscheidest du die Benachrichtigung für `Eingereichter Antrag kommentiert` und `Antrag kommentiert`.

Sehe ich das richtig, dass diese Unterscheidung nicht nötig ist?

Ein Antrag hat lediglich einen Antragssteller und ein eingereichter Antrag hat zusätzlich einen Gremiumsverantwortlicher. Wenn nun ein nicht eingereichter Antrag kommentiert wird, erhält auch nur der Antragssteller eine Benachrichtigung und wenn der Antrag eingereicht ist, wird der Gremiumverwantwortlicher als Watcher für den Antrag registriert. Ein neuer Kommentar benachrichtigt anschließend beide, den Antragssteller und den Gremium-Verantwortlichen...

siehst du das auch so?

**Comment by deiferni** [comment]
@elioschmutz ja ich habe im Issue die Benachrichtigungen separat pro Benutzerkreis aufgelistet. Darum ist das Kommentieren zweimal da. Mit den Benachrichtigungen ist es genau so wie du schreibst.

Zu den Gremien-Verantworklichen: dies ist ja über eine LDAP-Gruppe eingestellt. Es können also auch mehrere Benutzer sein.
