### ISSUE TITLE
Create script to validate schema conformance

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4440]
Create a script that checks all content (reachable through catalog) for schema conformance, and shows which objects contain invalid values according to their schema(s).

It should be possible to just use `Field.validate()` of `zope.schema` fields for this.

Along the lines of:

```
for obj in objects:
    schemas = iterSchemata(object)
        for name, field in getFieldsInOrder(schema):
            field_instance = field.bind(obj)
            value = field_instance.get(obj)
            field_instance.validate(value)
```

The [`SchemaDumper`](https://github.com/4teamwork/opengever.core/blob/master/opengever/base/schemadump/schema.py#L32-L70) could also serve as a template to get started with this.

Also needs to consider **versions**!

**Comment by Rotonen** [comment]
It should also flag content suffering from this:
https://github.com/4teamwork/opengever.core/issues/4376

**Comment by phgross** [comment]
https://github.com/4teamwork/opengever.maintenance/pull/149

**Comment by njohner** [comment]
This was closed in https://github.com/4teamwork/opengever.maintenance/pull/149
