### ISSUE TITLE
Locks are not visible for the user who created the lock

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#4454]
Locks created through the web interface or through the REST API are note visible for the user who created the lock. The locking information is only shown if the user can not safely unlock the item.

WebDAV locks are always treated as not safely unlockable because of a different lock type.

The locking information should be shown always if a document is locked.
There's an unlock button that should be shown only for administrators.

**Comment by Rotonen** [comment]
Stashing the relevant template here for an easy pick-up later: https://github.com/plone/plone.locking/blob/master/plone/locking/browser/info.pt
