### ISSUE TITLE
OGIP 26: Auslösen von Standardablauf wirft Fehler

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4458]
Beim Auslösen eines Standardablaufs, welcher Vorlagen enthält, die Eingangskörbe als Autragnehmer definiert kommt es beim Darstellen des "Auftragnehmer auswählen" Schrittes zu einem LookupError. Siehe https://sentry.4teamwork.ch/sentry/onegov-gever/issues/7373/

**Comment by deiferni** [comment]
https://github.com/4teamwork/opengever.core/blob/dfa9d9ba18b81078d53a4dc5904914d407735155/opengever/task/util.py#L203 may help you here
