### ISSUE TITLE
OGIP 26: Abbruch eines kompletten Standardablaufs ermöglichen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4463]
Für den Auftraggeber soll es möglich sein, eine Aufgabe abzubrechen (früher stornieren genannt) und somit den kompletten Standardablauf abzubrechen. Dies soll aber nur auf der Hauptaufgabe möglich sein:

 - Beim Abbrechen eines Standardablaufs sollen alle Unteraufgaben abgebrochen werden.

**Comment by njohner** [comment]
Either I misunderstand this one, or it already works

**Comment by njohner** [comment]
Ok this already works!
