### ISSUE TITLE
Document checked out state im Favoriten Menü stimmt nicht

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4567]
Bei der Dokument-Auflistung im Favoriten-Menü stimmt der checked-out-state (oranger Kreis) nicht. Er wird einmal beim Erstellen des Favorits bestimmt, und verbleibt dann für immer so.

(Ursprungs-Issue: 4teamwork/opengever.ftw#72)

### Schritte zur Reproduzierung
- Dokument in GEVER hochladen
- Favorit auf Dokument setzen
- Dokument auschecken

-> Das Dokument hat überall den richtigen checked-out-state "ausgecheckt" (oranger Kreis), ausser im Favoriten-Menü.

![favoriten_checked_out_state](https://user-images.githubusercontent.com/405124/42497859-f70256a8-842a-11e8-9a0e-c72fddfd5e54.png)

---

### Analyse

Das Problem hier ist, dass die [`icon_class` im SQL gespeichert wird](https://github.com/4teamwork/opengever.core/blob/3e9509988db2d35852ec17d0c6a96def01a9c80c/opengever/base/model/favorite.py#L46). Diese wird beim initialen erstellen eines Favoriten einmal bestimmt, und dann permanent [so gesetzt](https://github.com/4teamwork/opengever.core/blob/3e9509988db2d35852ec17d0c6a96def01a9c80c/opengever/base/favorite.py#L35).

Die CSS Klassen für Inhaltstypen in GEVER sind aber dynamisch - je nach State kommen da noch weitere Klassen dazu.

### Mögliche Lösungen
- Der `@favorite` Endpoint holt seine Informationen nicht bloss aus dem SQL, sondern macht auch noch ein Katalog-Query. Das würde aber nur für Mandanten-lokale Favoriten funktionieren, nicht Mandanten-übergreifende.
- Bei den [`ObjectCheckedOutEvent`](https://github.com/4teamwork/opengever.core/blob/3e9509988db2d35852ec17d0c6a96def01a9c80c/opengever/document/checkout/manager.py#L100) / [`ObjectCheckedInEvent`](https://github.com/4teamwork/opengever.core/blob/3e9509988db2d35852ec17d0c6a96def01a9c80c/opengever/document/checkout/manager.py#L176) werden jeweils alle betroffenen Favoriten im SQL aktualisiert
- Die Icons im Favoriten-Menü werden so zurechtgestutzt, dass sie keinen State enthalten. Das würde aber auch nicht wirklich richtig funktionieren: Ein Dokument in GEVER kann prinzipiell auch den Typ ändern (word -> excel), dann wär's immer noch falsch.

**Comment by jone** [comment]
Ich würde klar die Variante Events bevorzugen, da wir bereits den Titel aktualisieren; siehe #4109 und #4140.
Wenn checkout / checkin / cancel auch jeweils ein modified-event auslösen könnte es ausreichen, einfach zu dem Titel auch die CSS-Klasse zu aktualisieren.

Challenge: wenn ich es richtig verstanden habe bedeutet ausgefüllter Kreis dass ich es selber ausgecheckt habe, ein Kreis mit Lock jedoch dass jemand anderes es ausgecheckt hat. Das müsste beim Indexieren vermutlich berücksichtigt werden, d.H. es müsste quasi in fremdem Kontext neu indexiert werden..

**Comment by lukasgraf** [comment]
@jone wir haben's auch gerade nochmals besprochen, und sehen auch diese Variante als einzige wirkliche Lösung. Und danke für den Challenge 😜 - das muss tatsächlich speziell berücksichtigt werden, sollte aber möglich sein.
