### ISSUE TITLE
OGIP 36: Subject von Benachrichtigungsmail nicht korrekt

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4585]
Benachrichtigungsmail von Anträgen z.B. die Aktion "Anhänge eingereicht" wird mit dem Subject `GEVER Aufgabe: {Titel}` versandt.
<img width="930" alt="bildschirmfoto 2018-07-12 um 14 22 01" src="https://user-images.githubusercontent.com/485755/42632909-14a216a2-85df-11e8-826e-4fb651f20495.png">

**Comment by elioschmutz** [comment]
Der  `PloneNotificationMailer` (https://github.com/4teamwork/opengever.core/blob/master/opengever/activity/mail.py#L33) vom `opengever.activity` hat als Betreff-Präfix "GEVER Task" hardcodiert.

Wir können entweder

1. ein generisches Präfix, z.B. "GEVER Aktivität" (Vorschläge sind willkommen) verwenden oder
2. alles umbauen, damit dieses Präfix über ein Acitvity-Object gesetzt werden kann (relativ viel Aufwand. Dazu gibt es bereits Tickets z.B. https://github.com/4teamwork/opengever.core/issues/4544) oder
3. anhand des `Activity.kind` den richtigen Text holen => gehört m.M.n nicht dorthin

@phgross was soll umgesetzt werden?

**Comment by phgross** [comment]
Vorschlag 1) finde ich ok.

Von einem spezifischen Subject je nach Aktivitätstyp würde ich vorerst absehen.
