### ISSUE TITLE
Styling des Buttons `Folgeantrag erstellen` verbessern

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4586]
<img width="886" alt="bildschirmfoto 2018-07-12 um 14 14 03" src="https://user-images.githubusercontent.com/485755/42633140-ced663de-85df-11e8-83df-bf0d493c0d9a.png">

Der Button wirkt etwas verloren. @deiferni ist die Trennung der Buttons bewusst?

**Comment by bierik** [comment]
@phgross Kannst du bitte prüfen ob es technisch möglich ist im Template die beiden Knöpfe zusammen zu bringen?

**Comment by phgross** [comment]
@deiferni demnach die Aktion nach wie vor auf separater Zeile platzieren?

**Comment by deiferni** [comment]
Ich würde dazu tendieren gleiche Zeile + Icon.
