### ISSUE TITLE
UnicodeDecodeError: Beim Darstellen des Journal Tabs in einem Dossier

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4587]
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/3975/

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 92: ordinal not in range(128)
(9 additional frame(s) were not displayed)
...
  File "apps/eggs/zope.i18n-3.7.4-py2.7.egg/zope/i18n/__init__.py", line 126, in translate
    return util.translate(msgid, mapping, context, target_language, default)
  File "apps/eggs/zope.i18n-3.7.4-py2.7.egg/zope/i18n/translationdomain.py", line 78, in translate
    msgid, mapping, target_language, default, context)
  File "apps/eggs/zope.i18n-3.7.4-py2.7.egg/zope/i18n/translationdomain.py", line 140, in _recursive_translate
    text = interpolate(text, mapping)
  File "apps/eggs/zope.i18n-3.7.4-py2.7.egg/zope/i18n/__init__.py", line 164, in interpolate
    return _interp_regex.sub(replace, text)
  File "apps/eggs/zope.i18n-3.7.4-py2.7.egg/zope/i18n/__init__.py", line 159, in replace
    return unicode(mapping.get(param1 or param2, whole))

UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 92: ordinal not in range(128)
```

**Comment by Rotonen** [comment]
Somehow we end up with journal vents where the title mapping of a document having a `str` with non-ASCII instead of `unicode` as the value of `title`.

**Comment by Rotonen** [comment]
That's actually quite simply by having had documents the title of which has been a string instead of unicode:
https://github.com/4teamwork/opengever.core/blob/eb1157b639545d9030dc95135819e051b4565e2f/opengever/journal/handlers.py#L325

**Comment by Rotonen** [comment]
So, seems like meeting excerpts had non-unicode titles at some point and the upgrade step will not clean up the dossier journal entries.

https://github.com/4teamwork/opengever.core/blob/eb1157b639545d9030dc95135819e051b4565e2f/opengever/core/upgrades/20180619143343_make_sure_excerpt_document_title_is_unicode/upgrade.py
