### ISSUE TITLE
Detailansicht Anträge: Falsches Icon?

### ISSUE THREAD

**Issue by tarnap** [4teamwork/opengever.core#4637]
Bei der Ansicht eines Antrags erschein ein Icon für ein Dossier (Ordner):

<img width="1072" alt="screen shot 2018-07-24 at 15 13 23" src="https://user-images.githubusercontent.com/194114/43188971-c7036c86-8ff5-11e8-8876-88e17b83f74f.png">

**Comment by njohner** [comment]
The problem is only in the proposal templates. For a proposal the icon is ok:
<img width="1208" alt="screen shot 2018-07-25 at 17 35 58" src="https://user-images.githubusercontent.com/7374243/43211270-6fec070a-9031-11e8-8d3d-79140f6c7610.png">
