### ISSUE TITLE
Copy/paste does not seem to work properly in R2.8

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#464]
I selected a few items and "copied" them:
![bildschirmfoto 2014-08-06 um 21 15 27](https://cloud.githubusercontent.com/assets/485600/3832535/7fad7318-1d9e-11e4-9125-c6a4fd055726.png)

As a side note: Copying things doesn't show a status message which is kinda weird...

Then I open a subdossier and want to insert the "copied" objects:
![bildschirmfoto 2014-08-06 um 21 17 30](https://cloud.githubusercontent.com/assets/485600/3832553/b0e055a4-1d9e-11e4-8cd8-443961ca003e.png)
=> no insert action is given...

I noticed that after repeating the steps above (copying things), the action "Einfügen" is suddenly show. Weird.

**Comment by deiferni** [comment]
cannot reproduce this any longer. if the problem persists please open a new issue.
