### ISSUE TITLE
Mehrere "Weitere Aktionen" auf gleicher Zeile.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4644]
Ich sehe mehrere der  "Weiteren Aktionen" auf der gleichen Zeile. Ich denke nicht, dass dies die Übersichtlichkeit fördert 😉.

Styling scheint nicht mehr korrekt angewendet zu werden, die einzelnen Aktionen sollten auch eine grössere Highlight-Area haben (ganze Zeile). 

![screen shot 2018-07-26 at 11 54 52](https://user-images.githubusercontent.com/736583/43255686-d4af428a-90ca-11e8-9ca1-a0cbb2e8aa0b.png)

**Comment by phgross** [comment]
Duplikat von #4611 wird mit #4640 behoben 😉
