### ISSUE TITLE
Mail edit form shows unnecessary locked message

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4662]
When editing a mail (`ftw.mail.mail`), an unnecessary **lock message** is shown even if the user owning the lock is the one currently editing it:

![mail_edit_locking](https://user-images.githubusercontent.com/405124/43577235-99a935de-964b-11e8-8af1-ee03ffb2db07.png)

This has been fixed for the document edit form in #4607, but it seems this doesn't apply to mails yet.

**Comment by njohner** [comment]
Right this is the same as #4598
