### ISSUE TITLE
Re-assigning forwardings in Inbox takes too long

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4683]
There's a performance issues where re-assigning forwardings in Inbox takes way longer than it should (dozens of seconds, up to minutes).

A cursory analysis showed that data is synced to OGDS multiple times during the execution of the re-assignment. It's yet unclear though whether that's the actual root cause of the performance problem.

See https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/244

**Comment by phgross** [comment]
Wurde mit #4757 entschärft. Zudem habe ich ein Folge Issue erstellt siehe #4759
