### ISSUE TITLE
Test isolation failure in plonetheme.teamraum functional tests

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4725]
Quick reproduction:

```
$ bin/test -m plonetheme.teamraum
--- snip ---
Total: 23 tests, 0 failures, 2 errors, 0 skipped in 35.040 seconds.
```

**Comment by phgross** [comment]
@Rotonen there are several issues here, where not addressed by the plonetheme.teamraum integration:
 - [ ] The SearchboxViewlet customization inside plonetheme.teamraum is useless, its customized in gever itself. -> Remove inlcuding the test_searchbox tests.
 - [ ] The TEAMRAUMTHEME testing layers should be eliminated and the tests be refactored to use gever integrationtests or gever functional tests

Besides that i wonder if those plonetheme tests are realy run on jenkings, please also doublecheck.

**Comment by Rotonen** [comment]
https://ci.4teamwork.ch/builds/182248/tasks/296360
cmd-f `plonetheme`

The tests run just fine on the CI, if not run in isolation. Some other layer teardown leaks in a way to have the failures not manifest. And this is the problem to be addressed here.

This ticket is from a bunch of results I found via a script which ran all the modules separately to test for isolation issues.
