### ISSUE TITLE
Favorite button incorrectly styled in "view metadata" view and for paragraph templates

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4747]
The **favorite button ☆** in the "view metadata" views of most (all?) content types gets incorrectly wrapped onto the next line:

![favorites_btn_metadata](https://user-images.githubusercontent.com/405124/44201524-bb307600-a149-11e8-813d-91308d52e680.png)

Example: https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/view

This is also true when viewing (and not editing) paragraphtemplates, see http://localhost:8080/fd/vorlagen/meetingtemplate-1/paragraphtemplate-2

---

Instead it should look like it does on the overview view:

![favorites_btn_overview](https://user-images.githubusercontent.com/405124/44201523-ba97df80-a149-11e8-8afa-334ba37d6768.png)

Example: https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse#dossiers

**Comment by njohner** [comment]
It is also wrongly styled when looking at a folder content:
http://localhost:8080/fd/ordnungssystem/fuehrung/kommunikation/allgemeines/dossier-1/folder_contents

**Comment by phgross** [comment]
@njohner folder_contents is not accessible for regular users (only managers), so no need to care about folder_contents
