### ISSUE TITLE
Clicking twice on the radio widget column on a table radio widget sorts once on the title

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4751]
1) The radio widget column should not be sortable
2) Why does it sort only every second click?

![2018-08-16-sorting](https://user-images.githubusercontent.com/935317/44219563-ac16eb80-a17c-11e8-83cb-9c4197a2192d.gif)

**Comment by Rotonen** [comment]
Cannot figure out how that'd work either. Having a subtree modification breakpoint on the `<th>` element points at jQuery, but cannot figure out what is going on.

**Comment by phgross** [comment]
Sees to be fixed in master (see https://dev.onegovgever.ch/fd/ordnungssystem/ressourcen-und-support/ict/eforms/dossier-568/document_with_template)
