### ISSUE TITLE
OGIP 46: Zusätzliches Feld `Persönliche Aufgabe`

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4763]
- [x] Task Schema wird um Checkbox Field `Persönliche Aufgabe` erweiteren
 - Nur in AddForm ersichtlich 
 - Standardmässig nicht aktiviert
- [x] Erweitern des Globalindex Schemas um zusätzliche Spalte
- [x] Berechtigungsvergabe anpassen:
 - Keine Vergabe der Stellvertreter Berechtigung bei persönlichen Aufgaben.
- [x] Byline um Attribut persönlich ergänzen
- [x] ~Separates Icon für persönliche Aufgaben~ (ausgelagert in Issue https://github.com/4teamwork/opengever.core/issues/4951)

Zusätzlich:
- [x] Feature-Flag `private_task_feature` standardmässig aktiviert

**Comment by elioschmutz** [comment]
@phgross Die implementation des Feature-Flags ist nirgends aufgelistet.

Soll ich das Feature-Flag im Rahmen dieses Issues implementieren?

- [ ] Feature-Flag `private_task_feature`
- [ ] Standardmässig deaktiviert

**Comment by phgross** [comment]
@elioschmutz ja macht Sinn, aber standardmässig aktiviert.

**Comment by elioschmutz** [comment]
@phgross Ok. Noch eine Frage zur Byline:

Soll die Eigenschaft "Persönlich: Ja/Nein" bei aktivierten Feature immer angezeigt werden, oder nur, wenn die Aufgabe persönlich ist?

**Comment by phgross** [comment]
Ich würde die Option nur bei persönlichen Aufgaben anzeigen

**Comment by elioschmutz** [comment]
Ok. Eine weitere Frage:

Kann/darf eine persönliche Aufgabe einem Eingangskorb zugewiesen werden?

**Comment by phgross** [comment]
Wurde mit #4957 umgesetzt.
