### ISSUE TITLE
OGIP 46: Rechte Überprüfung bei Aufgaben Auflistungen.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4765]
Die Auflistungen Alle Aufgaben, Alle erteilten Aufgaben in der persönlichen Übersicht sowie die Aufgaben Auflistung auf Stufe Dossier dürfen nur noch Aufgaben, welche ein Zugriff auf die Aufgaben erlauben, auflisten.
Für die Rechteüberprüfung wird der bereits bestehende Index task_principals verwendet.

**Comment by elioschmutz** [comment]
@phgross Wie verhält es sich bei folgendem Szenario?

- Dossier A (Berechtigt: og-demo-users)
 - Aufgabe A privat (Issuer: elio.schmutz, Responsible: philippe.gross)

Grundsätzlich würde es bedeuten, dass alle Benutzer in der Gruppe `og-demo-users` die Aufgabe A sehen und bearbeiten können (z.B. neu zuweisen). Gem. Konzept ist das auch i.O. weil eine private Aufgabe in einem bestehenden Dossier mit bestehenden Berechtigungen erstellt wurde.

Was bedeutet dies aber nun für diesen Issue hier? Soll die Aufgabe trotzdem nicht angezeigt werden? `task_principals` würde momentan `og-demo-users` und `philippe.gross` enthalten. D.h. der Index bringt nichts, wenn die Aufgabe nur von `elio.schmutz` und `philippe.gross` sichtbar sein soll.

Und was bedeutet " ein Zugriff auf die Aufgaben erlauben"? Ein Benutzer, welcher keinen Zugriff auf das Dossier hat, sieht auch die Aufgabe nicht. Hat ein Benutzer bereits vorher die Berechtigung auf dem Dossier, darf er auch die Aufgabe sehen. Dieser Punkt wird im Konzept explizit als Abgrenzung behandelt.

Gibt es überhaupt ein Dossier, in dem niemand berechtigt ist? Und falls ja, dann sollte die Aufgabe bereits jetzt nicht unter `alle Aufgaben` erscheinen, weil die entsprechende Permission fehlen würde.
