### ISSUE TITLE
Komische trennzeichen in docs

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4773]
Siehe https://docs.onegovgever.ch/admin-manual/meeting/mergefields/#metadaten-zu-einem-sitzungsteilnehmer-participant

![screen_shot_2018-08-22_at_13_52_04](https://user-images.githubusercontent.com/736583/44461861-de0fce00-a612-11e8-920b-0f6164807101.png)

**Comment by phgross** [comment]
@deiferni Das steht so in den rst files. Werden die generiert und hast es deshalb nicht einfach korrigiert?
