### ISSUE TITLE
Add catalog index and metadata containing file extension

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4794]
Add catalog index and metadata containing file extension for `opengever.document.document` and `ftw.mail.mail` types.

Extension should be stored in the format `.jpg`, `.tar.gz`, etc.. (including the leading dot).

This is needed in preparation for making the file extension the canonical source of truth for the file type - the MIME type should then be derived from the extension (not the other way round).

The index is helpful for quickly querying the catalog for a particular type (for example in upgrade steps, or also content stats). The metadata column, among other things, is required for determining the icon for documentish types.

**Comment by phgross** [comment]
Will be implemented via #4966 so i close this one
