### ISSUE TITLE
Dokumentlink funktioniert auf Mobile Link nicht

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4803]
Dokumentenlinks z.B. auf der Dossierübersicht funktionieren auf Mobile Geräten nicht (iPad/iPhone). Die Seite wird zwar neu geladen, aber man landet immer wieder auf dem aktuellen context.

**Comment by phgross** [comment]
Es gibt auch Probleme bei der Firefox Desktop Version (siehe https://extranet.4teamwork.ch/support/stadt-nidau/tracker-gever/95)

**Comment by phgross** [comment]
@bierik das Problem wird durch den Dokumenten-Tooltip verursacht. Entfernt man diese Funktionalität so funktioniert der Link wie gewünscht. 

Aus meiner Sicht solle der Tooltip auf Mobile Geräten sowieso deaktiviert werden ...

**Comment by bierik** [comment]
Duplikat von https://github.com/4teamwork/opengever.core/issues/4809
Und wird durch https://github.com/4teamwork/opengever.core/pull/5000 gefixt.

**Comment by phgross** [comment]
closed via #5000
