### ISSUE TITLE
Mobile Geräte: Mehrere Inhalte in ExtJS selektieren - wie?

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#4808]
- Tabelle in ExtJS: Ich habe nicht herausgefunden, wie ich mehrere Zeilen (auf iPad Pro) auswählen kann - SHIFT und/oder CTRL (Apple Tastatur) haben irgendwie keinen Unterschied gemacht, ich kann jeweils nur eine Zeile wählen

**Comment by phgross** [comment]
Wird im alten UI nicht mehr angepasst bzw. umgesetzt. Die Auswahl im neuen UI ist dann möglich bzw. in den Frontend User Stories festgehalten.
