### ISSUE TITLE
Mobile Geräte: Referenzierte Dokumente in Aufgaben nicht wählbar

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#4809]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

- Referenzierte Dokumente in Aufgaben: Sind nicht in Detailansicht anzeigbar, ein Touch bewirkt nichts (Seite wird neu geladen)

Getestet mit iPad Pro.

**Comment by phgross** [comment]
Vermutlich gleiches Problem wie #4803
