### ISSUE TITLE
Make Proposals movable

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4830]
https://community.4teamwork.ch/t/verschieben-von-antraegen-ermoeglichen/1343

At the moment proposals cannot be moved at all. We would like to make them movable for the following reasons:
- greatly improves usability, other content can be moved.
- it might happen that a dossier cannot be resolved when the resolver-rule is set to be `strict` (e.g. proposal created in main dossier, that dossier also has sub-dossier, to resolve the proposal should be moved into a sub-dossier, but cannot).

After a brief discussion the following suggestion emerged:

- Allow the proposal to be moved to any dossier
- The proposal document will also be moved as it is contained in the proposal
- If the proposal has an excerpt the excerpt should also be moved. At the moment the excerpt is locked in the dossier and cannot be edited or moved separately by a user.
- If the proposal has attachments and the proposal is moved to a different dossier we suggest to copy the attachments (and should let the user confirm this first). We would not allow cross-dossier references as that might trip up disposition.
- there could also be references to the proposal document or the excerpt. what to do in that case? leave behind a copy?

Pitfalls:
- currently the proposal remembers its `physical_path` which is used to send requests, we must make sure that this path is always kept up to date or switch to an oguid-based implementation.
- …

**Comment by jone** [comment]
@deiferni ist dies durch https://github.com/4teamwork/opengever.core/issues/6014 erledigt?

**Comment by deiferni** [comment]
Closed by https://github.com/4teamwork/opengever.core/pull/6223
