### ISSUE TITLE
Docs SPV nicht aktuell, neue Features gemäss Release Notes aufnehmen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4842]
Die folgenden Punkte gemäss https://onegovgever.ch/aktuell/aktuell/onegov-gever-release-2018.4 sollten auch in der Doku erwähnt werden, da es sich um neue Features handelt:

- In den Sitzungsvorlagen können neu wiederverwendete Zwischentitel vordefiniert werden.
- Statusänderungen der Anträge können neu alle kommentiert werden.
- Beim Erstellen eines Antrags kann neu ein bestehendes Dokument im Dossier als Antrag ausgewählt werden.
- Anträge und Traktanden haben neu das Feld „Beschreibung“.
- Neu befindet sich ein Button „Antrag erstellen“ beim Dokumenten-Tab eines Dossiers. Damit können - Anträge direkt mit mehreren Dokumenten als Anhang erstellt werden.
- Es können neu mehrere unterschiedliche Antragsvorlagen für Ad-Hoc Anträge konfiguriert werden.

Die anderen hier nicht erwähnten Punkte führen dazu das u.U. Screenshots uns bestehende Beschreibungen nicht mehr 100% zutreffen.

**Comment by livschal** [comment]
@deiferni  

- Punkte 3-5 findest du bereits im PR: ls-diverses-release-18-4
- Punkte 2 und 6 findest du im PR: ls-update-spv

Was daher noch fehlt ist Punkt 1: In den Sitzungsvorlagen können neu wiederverwendete Zwischentitel vordefiniert werden --> das sehe ich auf dev.onegovgever.ch nicht, was dort neu ist :)

**Comment by phgross** [comment]
@livschal Bsp für Punkt 1: http://localhost:8080/fd/vorlagen/meetingtemplate-1/view

**Comment by phgross** [comment]
@livschal Sorry das war der falsche Link. https://dev.onegovgever.ch/fd/vorlagen/meetingtemplate-1
