### ISSUE TITLE
Adding a template without file to a template dossiers causes error

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#485]
Adding a template without file to a template dossiers causes an error:

``` pytb
2014-08-15 10:08:30 ERROR Zope.SiteErrorLog 1408090110.730.682926890399 http://localhost:8080/mandant1/ordnungssystem/fuehrung/strategie-und-planung/dossier-5/document_with_template
Traceback (innermost last):
  Module ZPublisher.Publish, line 126, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 46, in call_object
  Module opengever.dossier.templatedossier.form, line 49, in __call__
  Module opengever.dossier.templatedossier.form, line 105, in create_document
  Module opengever.dossier.templatedossier.create, line 47, in create_in
AttributeError: 'NoneType' object has no attribute 'data'
```

The reason is that when copying the template document the code assumes the document actually has a `file`. This is easily fixed, however there are other issues preventing templates without a file from working properly:
- The [x] `Edit after adding` action currently launches external editor, which absolutely requires a file. This action would need to check for a `file`, and redirect to the standard `@@edit` view if there is none.
- Currently all metadata of copy of the template document will be reset to default values. This is the desired until now, because for example the `description` field may be used to describe the _template_ - that description would be wrong for the actual document (template instance).
  For templates without a file, the metadata however is the only thing of interest, so that behavior would need to be turned off

Furthermore it's questionable if this is an actual use case - so one might just disallow adding templates without files alltogether. However, this has its own set of problems:
- There needs to be a new validator that requires a `file` field - but only if the document is being added to a template dossier
- The existing [`FileOrPaper` validator](https://github.com/4teamwork/opengever.core/blob/42165df6d2db2af1320676bd674beb65f084c880/opengever/document/behaviors/metadata.py#L151) would need to be adapted for adding documents to template dossiers
- The [`FileOrTitle` validator](https://github.com/4teamwork/opengever.core/blob/bdcc5091856f2be33d239795a80ff55ef4718940/opengever/document/document.py#L60) would need to be adapted as well (for template dossiers).

The issues with these validators are the following:
- Schema invariants are on the schema level - therefore they cannot be used to perform different validation for the same content type being added to different containers
- Form-level validation [is possible](http://docs.plone.org/develop/addons/schema-driven-forms/customising-form-behaviour/validation.html#validating-in-action-handlers) by customizing the add form, but Add forms can only be customized for a particular portal type - the context (container) _cannot_ used as a discriminator

/cc @phgross

**Comment by phgross** [comment]
The bug which raises an AttributeError is solved for now with #3045. The consideration if a template should be a separate portal_type is still open, but there is a separate issue for that #486.
