### ISSUE TITLE
Committee.Title() accessor is dangerously defensive

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#4853]
The [`Committee.Title()` accessor](https://github.com/4teamwork/opengever.core/blob/c4f6bd9a8bbf83c2b406f14c77e777148f73e093/opengever/meeting/committee.py#L261-L265) fooled me big time today, by silently returning an empty string for the committee title (instead of complaining that my SQL <-> ZODB state was inconsistent).

```python
    def Title(self):
        model = self.load_model()
        if not model:
            return ''
        return model.title.encode('utf-8')
```

In my opinion, this is dangerously defensive, and unnecessarily so - `self.load_model()` should never fail, should it? Otherwise we want to know, and abort the transaction, not continue with invalid data.

**Comment by deiferni** [comment]
IIRC the this works around an issue with creation order of things, there may be a brief period where the plone object exists and is expected to have a title but we do not have the model yet.

But i agree this is an issue. We will/should tackle this by move primary field data from SQL to plone (See https://github.com/4teamwork/opengever.core/issues/3787 for example) and making data in SQL an index only.

**Comment by deiferni** [comment]
Will be fixed with https://github.com/4teamwork/opengever.core/issues/3787 eventually.
