### ISSUE TITLE
Batching on SOLR search: second batch not working

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4854]
Steps do reproduce: 
 - erweiterte Suche
 - Dossiers, Status: `in Bearbeitung`, Suche nach responsible
 - Suchen 
 - Wechsel auf zweiter Batch

Bsp: https://dev.onegovgever.ch/rk/@@search?object_provides=opengever.dossier.behaviors.dossier.IDossierMarker&responsible=zopemaster&review_state%3Alist=dossier-state-active

**Comment by lukasgraf** [comment]
@phgross could this be 4teamwork/opengever.core#4363 again? (Batching broken because heap size that is too small?)

**Comment by deiferni** [comment]
Fixed by https://github.com/4teamwork/opengever.core/pull/4863
