### ISSUE TITLE
Stop using catalog.reindexObject

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#4861]
`catalog.reindexObject` explicitly reindexes in Portal Catalog only, but it doesn't in Solr.
This leads to an inconsistent Solr index.

We should **always** use `obj.reindexObject()` instead of `catalog.reindexObject(obj)`

Wrong usage:
https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L90
https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L163
https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L217
https://github.com/4teamwork/opengever.core/blob/master/opengever/base/handlers.py#L44
https://github.com/4teamwork/opengever.core/blob/master/opengever/usermigration/creator.py#L84

Problem reported by customer:
https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/293

**Comment by deiferni** [comment]
Historically we've been using the catalog when we don't want to update the catalog metadata. Many upgrades may be affected. Also always updating metadata will make certain upgrades quite expensive given we still use the catalog. We might want to consider offering two different paths for certain upgrades as long as customers still use solr.

Might be a good idea to also check dependencies, especially `ftw.upgrade` 🤔.
