### ISSUE TITLE
Participants of a meeting not updated when Memberships change

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4876]
Currently when a meeting is created its participants are initialized https://github.com/4teamwork/opengever.core/blob/8746053de47e33eb297f4cb97d684ef2c05c5f02/opengever/meeting/model/meeting.py#L186-L192 and stored persistently in `Meeting.participants`. When memberships of those participants are changed at a later point the participants of a meeting are not updated correctly. 

Steps to reproduce:
1) Create a Meeting in a Committee that has Memberships that overlap the Meetings date
2) Modify Memberships of the Committee so that there are fewer Memberships at the meeting's date (e.g. remove memberships or shorten membership period)
3) Generate a protocol for the meeting, the protocol will still list the Members of the Memberships removed in step 2)

**Comment by Rotonen** [comment]
Oh wrong milestone, letting this one be for now, damn you ZenHub.
