### ISSUE TITLE
Fix viewlets depending on the new ui settings

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#4881]
Quick reproduction:
`bin/test -t test_editors_are_able_to_edit_and_checkout_a_document`

**Comment by phgross** [comment]
@Rotonen Should the test fail? or whats the not expected result? 

Could not reproduce a failing test with current master.

**Comment by Rotonen** [comment]
The tests should not fail, but there are viewlet rendering errors popping up on STDERR for me.

Will check that out again.

**Comment by Rotonen** [comment]
Cannot reproduce this one currently, but will provide an another reproduction once I spot this one again.

**Comment by Rotonen** [comment]
Must have been a stale cached fixture (user error) as cannot reproduce the whole category anymore.
