### ISSUE TITLE
Aktion `Sitzungsvorlage` überprüft Meeting Feature flag nicht

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#4905]
Im Vorlagenbereich ist es möglich eine Sitzungsvorlage hinzuzufügen, obwohl das Meeting-Feature deaktiviert ist.

<img width="881" alt="bildschirmfoto 2018-09-25 um 13 09 25" src="https://user-images.githubusercontent.com/485755/46010948-a0e0a500-c0c4-11e8-930c-cc980bdb0e33.png">

Korrektur für `2018.4-stable` nötig.

**Comment by deiferni** [comment]
check für aktion und auch im add-form einbauen
