### ISSUE TITLE
OGIP 46: Icon für persönliche Aufgabe

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#4950]
Im Rahmen des OGIP 46 wird ein neues Aufgaben-Icon für persönliche Aufgaben benötigt.

- [ ] Neues Icon für persönliche Aufgaben erstellen

Issuer: https://github.com/4teamwork/opengever.core/issues/4763

**Comment by bierik** [comment]
In Absprache mit @phgross wollen wir hier kein neues Icon. Das Problem mit einem zusätzlichen Icon, ist die vermischung von Unteraufgabe-Persönlich und Mandantenübergrefend-Persönlich.
