### ISSUE TITLE
OGIP 46: Neues Icon für persönliche Aufgaben verwenden

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#4951]
Requires: https://github.com/4teamwork/opengever.core/issues/4950

- [ ] Das neue Icon soll für private Aufgaben verwendet werden.

Issuer: https://github.com/4teamwork/opengever.core/issues/4763

**Comment by bierik** [comment]
Siehe https://github.com/4teamwork/opengever.core/issues/4950
