### ISSUE TITLE
Index filesize, filename and extension of documents

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#4966]
Use-cases:
- Display filesize and filename in document listings
- Query for large documents
- Use extension for mimetype icons 
- Query documents by type (extension)

Fields:
- filesize: indexed and stored
- filename: stored
- extension: indexed and stored

see also #4794
> Extension should be stored in the format .jpg, .tar.gz, etc.. (including the leading dot)

Maybe it's not necessary to store the filename because it can be generated from the title and the extension?

Metadata columns that can be dropped probably:
- `getObjSize`
- `getContentType`
- `getIcon`

**Comment by phgross** [comment]
- In the 2018.5 release we only want to add the three indexes and metadata but not using them anywhere (this will follow in a later release). 
 - Add an deferrable upgradestep which reindex those indexes and metadata
 - The upgradestep should be merged to the `changed` reindexing one

**Comment by Rotonen** [comment]
@phgross Adding and testing three unused indices is clear enough, but how should one roll here for the metadata, as that is a schema, and thus would get rolled into any new deployment?
