### ISSUE TITLE
Feature: Path in response of REST API

### ISSUE THREAD

**Issue by bierik** [4teamwork/opengever.core#4979]
When using the REST API in a frontend application (vue.js for example) there is no good way to store a unique identifier of a resource from GEVER.

In the RIS application, a business has a GEVER dossier. We persist the identifier of the dossier which is currently the URL. The problem is, that the URL also contains the cluster URL `https://ris.onegovgever.ch/` for example and in some circumstances the admin UID which could be something such as `/gs`. In general, it's a bad idea to persist URLs because they may change. So a better value to an identifier could be the path of the URL `/ordnungssystem/1/dossier-9`. This way the URL to the GEVER may change but the locator to the resource, the dossier, in that case, stays the same.
So the response of a GEVER resource (dossier, document, task, ...) should contain the path as well.

**Comment by phgross** [comment]
Add an additional attribute to GET `relative_path` which returns object location path relative to the Plone site root:
For example `ordnungssystem/bevoelkerung-und-sicherheit/einwohnerkontrolle/allgemeines/dossier-17` for https://dev.onegovgever.ch/fd/ordnungssystem/bevoelkerung-und-sicherheit/einwohnerkontrolle/allgemeines/dossier-17#overview

Siehe `SerializeToJson`  and `SerializeFolderToJson` in plone.restapi.
