### ISSUE TITLE
Sablon date strings not translated in user language.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4989]
In https://github.com/4teamwork/opengever.core/pull/4417 we have introduced custom format strings for dates in sablons. Unfortunately we use `strftime` and thus the servers locale. For that reason translated days/months will only and incorrectly return the english names.

While we hook into this we could think about also allowing non-zero padded numbers, as that **will** come up, too.

Proposed solution:  somehow find a way to reuse `i18nl10n.ulocalized_time` or some other translation mechanism provided by plone.

**Comment by Rotonen** [comment]
On a cursory glance, as locale setting is not thread safe in Python, we'd have to bring in either Babel [1] or pyICU [2] for getting localizable `strftime()` equivalents. The Plone tool does not do this for arbitrary time formatting strings.

I'm leaning towards Babel.

[1] http://babel.pocoo.org/en/latest/dates.html
[2] https://github.com/ovalhub/pyicu

**Comment by njohner** [comment]
From what I see from babel, we could then either use it to get locale date formatting, but in that case not using the setting from the registry, or we can specify a dateformat in the registry and use babel to generate a local date from that format. Problem here is that the format specification is different, so registry entries would need to be adapted.

**Comment by njohner** [comment]
Same thing for `pyICU`, except that documentation seems quite a bit worse.

**Comment by Rotonen** [comment]
As pyICU is just a thin wrapper over ICU, refer to the ICU documentation.

IIRC we discussed this one in a weekly and @lukasgraf did not want to introduce an another i18n layer.
