### ISSUE TITLE
Finish integration of opengever.ogds.models.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4990]
In https://github.com/4teamwork/opengever.core/pull/4690 we have copied `opengever.ogds.models` into this package. Some cleanup still remains:

Split out everything that is not strictly `ogds` related
- `__init__.py` there is a `BASE` which should be merged into `opengever.base.model.Base`
- `query.py` move query to a base module
- `testing.py` there is layer setup in there, it should be together with the other layers if still needed
- `types.py` move to base module
- marry `PloneOGDSService` and `OGDSService`
- ~~get rid of `OGDSService` and `ogds_service` respectively. it is not a service nor will it be in the near future.~~

**Comment by Rotonen** [comment]
The testing is already addressed by https://github.com/4teamwork/opengever.core/pull/4973
