### ISSUE TITLE
Make meeting model transparent as far as possible.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4993]
Refactor and push functionality to plone objects to make the meeting's model transparent as far as possible. This helps prepare the upcoming Migration to Plone Objects and Meeting/Meeting-Dossier merge.

_Extracted from https://github.com/4teamwork/opengever.core/issues/4466_

**Comment by phgross** [comment]
Wird in einem separaten OGIP 50 erarbeitet, ich schliesse diesen Issue.
