### ISSUE TITLE
Tag content with a source-specific interface

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#4994]
As sometimes it is necessary to process some already created data (e.g. to fix a bug) we need to figure out where certain content came from. At the moment this is not possible, or only possible due to a side-effect of a certain data-source. We've discussed to slap an interface that is source-specific on the content it created. The following sources could be affected:

- ech0147
- bundle
- api
- transported content (tasks, meeting)
- oneoffixx
- gever templates
- ?

Migration of existing content is not possible as the source cannot be detected reliably.

_This is a remnant from a discussion of todays weekly._

**Comment by Rotonen** [comment]
All the template systems we do or will integrate with.
