### ISSUE TITLE
Find and deduplicate overlaps of plonetheme.teamraum and opengever.core

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#5008]
_Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Split off from https://github.com/4teamwork/opengever.core/pull/4971

List of potential candidates where we can deduplicate:

* Search box
* Testing layer (currently the `plonetheme.teamraum` tests only apply the profile)

The testing layer one is a bit more involved, as applying that profile to all of our tests changes some transforms, but this is ultimately very good to do the same way we do in production.

**Comment by deiferni** [comment]
- merge `plonetheme.teamraum:default` with `plonetheme.teamraum:gever`
- merge `plonetheme.teamraum:default/mimetypes.xml` with `opengever.policy.base:mimetype/mimetypes.xml`, we can probably get rid of the `opengever.policy.base:mimetype` profile.

this means we call less setuphandlers, thus setup might be a tiny bit faster. also might be relevant for tests.

**Comment by deiferni** [comment]
No longer relevant with new UI.
