### ISSUE TITLE
OGIP 39: Speichern button not correctly styled

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5069]
Is: 
![bildschirmfoto 2018-11-09 um 11 20 52](https://user-images.githubusercontent.com/485755/48257119-f2918480-e411-11e8-938d-65042736e4b5.png)

should:
![bildschirmfoto 2018-11-09 um 11 23 41](https://user-images.githubusercontent.com/485755/48257118-f2918480-e411-11e8-97bd-7883a69c91fd.png)

The css class `context` does the trick (https://stackoverflow.com/questions/7609480/how-to-add-a-css-class-to-a-z3c-form-button)

**Comment by deiferni** [comment]
@phgross did you swap the should and is images here? otherwise i disagree as we would want to have one button green in this case, right 🤔?
