### ISSUE TITLE
OGIP 39: Bumblebee conversion not triggered correctly

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5070]
After saving a document as pdf, the bumblebee preview, does not work. Only if I trigger the conversion again via `Vorschau neu generieren` the preview shows up.

Example: https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-448/document-2066#overview

**Comment by deiferni** [comment]
could be related to https://github.com/4teamwork/opengever.core/issues/4999

**Comment by njohner** [comment]
This has been resolved in https://github.com/4teamwork/opengever.core/pull/5083
