### ISSUE TITLE
Make sure all decided proposals have a protocol excerpt

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5076]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Since https://github.com/4teamwork/opengever.core/pull/4837 we enforce returning an excerpt before deciding a proposal (and closing the corresponding meeting). This was not the case before and we might have proposals that do not have an excerpt. This was always like this, but as we now enforce to return a protocol, there is a growing risk that in the future we forget that some of the older proposals might not have an excerpt. It would therefore be safer to make sure that all decided `proposal`s have an excerpt.

- [x] write a maintenance script to list all decided proposals that lack an excerpt
- [x] decide what to do next. For now the idea would be to push the customers to correct that situation themselves.

**Comment by phgross** [comment]
Weiteres Vorgehen muss definiert werden.

**Comment by njohner** [comment]
Open points from @deiferni :

diese drei dinge hab ich mir notiert:
-    Verlangen wir neu bei Traktanden ohne Antrag einen Protokollauszug, falls ja gibt es (beschlossene) Traktanden ohne Antrag, die keinen Protokollauszug haben
-    Gibt es (beschlossene) Anträge in der Sitzung, die keinen Protokollauzug haben
-    Gibt es (beschlossene)Anträge im Ursprungsdossier, die keinen Protokollauszug haben

**Comment by njohner** [comment]
- Für Traktanden ohne Antrag verlangen wir keinen Protokollauszug
- Es gibt (beschlossene) Anträge in der Sitzung, die keinen Protokollauzug haben
- Es gibt (beschlossene) Anträge im Ursprungsdossier, die keinen Protokollauszug haben

**Comment by deiferni** [comment]
We've had a look a the situation and at the moment there are _hundreds_ of proposals without excerpt (as that was valid at some point, for some time). It is impossible to automatically create the excerpts for those proposals as they are user input.

Thus we'll have to support proposals without excerpt  as valid state in the future, even though we don't allow creating fresh ones in that state.
