### ISSUE TITLE
Missing description field in paragraph addform.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5090]
- missing description in paragraph addform (paragraph templates already have a description)
- description is not mentioned in docs at https://docs.onegovgever.ch/admin-manual/meeting/mergefields/#metadaten-zu-einem-traktandum-agendaitem

The paragraph addform does not show a description:
 
![screenshot 2018-11-14 at 10 24 32](https://user-images.githubusercontent.com/736583/48472906-8fc83080-e7f7-11e8-9dad-0164daed9b93.png)

but the edit form does:

![screenshot 2018-11-14 at 10 25 33](https://user-images.githubusercontent.com/736583/48472949-a4a4c400-e7f7-11e8-804e-ebfaf51941f0.png)

**Comment by njohner** [comment]
The description is already in the documentation, but the https://docs.onegovgever.ch/admin-manual/meeting/mergefields/#metadaten-zu-einem-traktandum-agendaitem is not up to date
