### ISSUE TITLE
Proposal workflows permits Contributor to view

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5091]
The current proposal workflow acquires the View permission which therefore allows `Contributor` to View proposals. This breaks the "rule" that a user which gets permitted on a dossier with a task only sees the related documents. 

Which means, Users which are only permitted on a dossier by a task, does also see all proposals, which is wrong.

**Comment by deiferni** [comment]
this has two consequences:
- if a task relates a proposal document, the proposal should also be visible to the task responsible
- the proposal listing from sql currently relied on view being inherited and has to implement security checks now
