### ISSUE TITLE
Document listings: link subdossier column.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#510]
![bildschirmfoto 2014-08-27 um 17 11 18](https://cloud.githubusercontent.com/assets/485755/4062478/22175648-2e00-11e4-9669-06d042632360.png)

The subdossier column in documentlisting should provide a link to the subdossier itself.

**Comment by deiferni** [comment]
we should load objects and then implement this in an object oriented manner. that way links can be genrated by each dossier which knows its parent. a redirect view is not necessary. objects only have to be loaded for the current batch, the performance impact should be neglegible.
