### ISSUE TITLE
Fight Flaky Tests in 2019.1

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5102]
Epic to track flaky test issues we want to tackle.

**Comment by jone** [comment]
Could someone provide more details about the problem?
Did someone try to pinpoint the commit using `git bisect`? If not: this would be very helpful and can be done quite easily with scripts and git 😉 .

**Comment by Rotonen** [comment]
@jone If you arrived here via something which had a query string or an anchor on the URL, the epic box does not render.

**Comment by jone** [comment]
Ah, I didn't realize that this is an epic; my zenhub didn't run. nvm.
