### ISSUE TITLE
Missing translation in file chooser in the document add form

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5115]
Translations are missing, probably for `z3c.form.widgets` for the `NamedBlobFile` fields.
For example in the document add form for the file, but also for the archival file: 

<img width="479" alt="screen shot 2018-11-16 at 11 46 37" src="https://user-images.githubusercontent.com/7374243/48634605-3eba6700-e9c6-11e8-9321-9acb94fff674.png">

**Comment by njohner** [comment]
😓 Ok did not know that the label here came from the browser and not from plone... I think we can just close that one, sorry

**Comment by deiferni** [comment]
right 👍.
