### ISSUE TITLE
API-Endpoint for bumblebee user salt

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5127]
GEVER should provide a REST-API-Endpoint for getting the user-salt of the current user.

**Background:**
The goal of the user salt is to be used for salting personal access token so that the URLs cannot be used by other users and that the application can control security and revoke access when necessary.
The user salts are applied to access tokens of urls which are handed out the user's browser, along with a signed cookie containing the user salt, which is shared with bumblebee.
A client needs to possess both, the user salt cookie and a URL with the access token in order to download a file from bumblebee.

**In summary:** 
The user salt should only be generated from the application which owns the documents and knows about the security. User salt and access tokens **must not** be created or changed by intermediate applications which are not in control of the security of the documents.

**Change request:**
We currently have applications which share the bumblebee secret and generate own user salts and access tokens. They must no longer generate user salts. The reason they are doing that is to make sure that a cookie exists even when the user never visits GEVER itself. We will have the same problem when we have a javascript frontend.

In order for intermediate applications or javascript frontends to be able to set the bumblebee user salt cookie when it is missing, GEVER (or more precise: ftw.bumblebee) needs to provide a REST API endpoint where a user can retrieve the cookie value for the bumblebee cookie. Authentication is out of scope here; application must be able to authenticate properly and impersonate as the correct user.

**Specification:**
- add a new REST API endpoint, named something like "bumblebee cookie"
- the endpoint delivers the cookie value (=signed user salt): https://github.com/4teamwork/ftw.bumblebee/blob/77c8fd42f0e9b16bec96d9bfe29955e66d5abcbe/ftw/bumblebee/viewlets/cookie.py#L32
- endpoint should be added to `ftw.bumblebee`

**Comment by deiferni** [comment]
@jone would the existing `@preview-session` endpoint do 😄?

**Comment by jone** [comment]
I wasn't aware about `@preview-session`; I think it is exactly what we need.
The RIS-Team will implement RIS against `@preview-session` in the next sprint, so let's see if it works.

**Comment by jone** [comment]
RIS runs now with the existing `@preview-session` endpoint and it works well. 🎉
