### ISSUE TITLE
Geplant Status Icon bei Aufgaben wird nicht korrekt dargestellt im IE

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5130]
In Aufgabenauflistungen erscheint das Status icon für den `geplant` Status abgeschnitten und, so vermute ich, zu gross. 

_(screenshot folgt noch)_

**Comment by Rotonen** [comment]
@phgross waiting for a screenshot.

**Comment by phgross** [comment]
It seems that this is no longer an issue, `planed Icon` looks fine in IE 11 and Edge.
