### ISSUE TITLE
OGIP 33: Schlagwortfilter bei Dossierauflistungen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5137]
Umsetzung gemäss [OGIP 33](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2528/document-23161#overview).

- [x] Schlagworte in Dossier Auflistungen darstellen
- [x] Schlagwortfilter
- [x] Anpassungen SOLR Konfiguration und Abfragen für Facetten-Suche (Anmerkung von @elioschmutz: wurde bereits implementiert)

**Comment by elioschmutz** [comment]
Genauere Spez besprochen mit @deiferni:

- Der Filter soll als Select2-Widget (wie die momentane Schlagwort-Auswahl im Edit-Form ist) umgesetzt werden. 
- Ausgewählte Schlagworte werden AND-Verknüpft
- Der Filter wird direkt neben den bisherigen Filter (gem. Mockup) angezeigt

**Comment by elioschmutz** [comment]
@deiferni Das Keywordwidget soll gem. Spez nur Schlagworte von den Dossiers innerhalb des aktuellen Repofolders anzeigen. Ein Index kann dazu nicht verwendet werden.

Frage: Soll das keywordwidget lazy sein oder nicht

Kannst du mir dazu ein paar Zahlen nennen, damit ich beurteilen kann,  ob das Keywordwidget lazy sein soll oder nicht. 

- Wieviele Keywords gibt es ungefähr pro Mandant?
- Wieviele Dossiers existieren normalerweise innerhalb eines Repo-Trees?

Meine Meinung und Einschätzung:
Ich finde es viel Benutzerfreundlicher, wenn das Keywordwidget direkt beim reinklicken zeigt, welche Keywords zur Auswahl zur Verfügung stehen.
Wenn es jedoch viele Keywords sind (> 100) wird das Widget sehr langsam.
Bei vielen Dossiers ist es weniger schlimm. Das Extrahieren der Keywords von den Brains sollte nur beim ersten Mal bisschen länger dauern, danach ist es gecached und wird mehr oder weniger instant zurückgegeben. Trotzdem muss immer über jedes Brain iteriert werden.

Alternativ könnte ich auch individuell entscheiden. Je nachdem wieviele Keywords insgesammt auf einem Mandanten existieren mache ich es lazy oder nicht.

Wie siehst du das?

**Comment by deiferni** [comment]
Ich würde es in einem ersten Schritt genau so machen, wie es auch beim Bearbeiten eines Dossiers ist.  So wie es ausschaut ist es dort nicht lazy. Ich nehme an du verwendest das gleiche Vocabulary von daher sollte der gleiche Cache hier auch ziehen. Soweit ich gesehen habe bezieht das Vocabulary seine Daten auch direkt aus dem Index des Katalogs. Ich würde davon ausgehen, dass der Index im normalen Betrieb im RAM ist. Falls wir damit Probleme haben können wir immer noch (d)eine Optimierung einbauen.

**Comment by elioschmutz** [comment]
Ok. Betr. Vocabulary stimmt es leider nicht ganz.

Das Vocabulary im Edit-Form zeigt alle Keywords von der ganzen Seite an. Deshalb kann der Distinct-Value vom Index verwendet werden. Dies ist nicht teuer.

Die Anforderung zum Filter ist jedoch, dass nur Keywords innerhalb der aktuellen Struktur angezeigt werden sollen. D.h. wir benötigen ein neues dynamisches Vocabulary welches seine Daten von einer Katalogabfrage bezieht und nicht vom Katalog-Index.

Dies ist leider etwas teurer...

**Comment by deiferni** [comment]
ah. bedeutet aber, der cache ist auf dem context, und benutzer-abhängig (unterschiedliche benutzer sehen dann je nach zugriff auch unterschiedliche keywords)? wie würdest du den cache invalidieren? Ich stelle mir das nicht ganz einfach vor 🤔.

ich würde trotzdem probieren es eager zu implementieren. Wenn du den Input immer aufgrund des aktuellen contextes validieren muss, hast du ja das erwähnte problem immer noch, einfach später, oder nicht?. 

falls sich mögliche performanceprobleme wirklich abzeichen wäre eine alternative strategie ein feature-flag einzubauen, mit dem man den schlagwortfilter einfach ausschalten kann. er wird ja auch immer geladen bei einer OP/einem dossier, das könnte unangenehm werden.

zur einer möglichen optimierung sehe ich 3 möglichkeiten:
- doch nicht nach context einschränken, immer alle schlagworte anzeige
- optimiertes vocabulary, das informationen auch direkt aus den katalog-indizes beschafft, muss aber bei bedarf evauliert werden. ich stelle mir vor, dass man aus dem path-index und dem `_unindex` des keyword-index evtl. etwas bauen könnte
- keywords der kinder auch im parent speichern. dies wäre dann aber nicht pro benutzer unterschiedlich, sondern global alle keywords der kinder.

zahlen sind schwierig, habe ich grad keine zur hand :(.
