### ISSUE TITLE
OGIP 21: PDF-Versand von Dokumenten

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5138]
_Harvest: `OneGov GEVER` - `Feature: PDF-Versand von Dokumenten - OGIP 21`_

Umsetzung gemäss [OGIP] (https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-1900/document-18940).

Genaue Spezifikation folgt noch ...

**Comment by Rotonen** [comment]
This should not get tackled before https://github.com/4teamwork/OfficeConnector/pull/307 gets merged.

**Comment by Rotonen** [comment]
As this will get implemented on top of the REST API, this will also rely on the PDF endpoint consistency from https://github.com/4teamwork/opengever.core/issues/5391.

**Comment by Rotonen** [comment]
I'd need to add a new payload type to Office Connector, but this is currently blocked by a refactoring of Office Connector and a sudden moratorium on new features landing onto

This opens up a good opportunity to rearchitect the way Office Connector interacts with document repositories, so as to extract and generalise parts of it with an aim to also, apparently, enable the functionality for Django projects too.

Iceboxing until we know more of the Office Connector and general architecture timelines.

**Comment by Rotonen** [comment]
@buchi, can you keep @phgross and @deiferni somewhat in the loop in regards to the OC refactoring progress?

Also the generalisation of the python/web side of Office Connector functionality should probably be projectified to establish a suitable marching order and a timeline here.

**Comment by Rotonen** [comment]
A very minimal branch exists. During sketching we spotted we'd have had to make the OC URLs and the handling thereof a bit more flexible to be able to pull this off without OC-side changes.

https://github.com/4teamwork/opengever.core/tree/jo-5138

**Comment by phgross** [comment]
wird im JIRA getracked (ROAD-1676)
