### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#5183]
_Harvest: Projekt - `Behebung Security Issues gemäss Security-Audit 2018` - `Issue Nr. 2`_

Currently we have jQuery 1.11.2 provided by plone.app.jquery which has an XSS vulnerablilty.
However only jQuery 3.x is receiving security updates.
We want to check if it's possible to update to the latest jQuery without much effort.

Procedure:
- Frist try to update to the latest 1.x: 1.12.4
- Use the [jQuery Migrate ](https://github.com/jquery/jquery-migrate/tree/1.x-stable) plugin to check if there are any issues.
- ~~If an update to 1.12.4 is successful, try to update to latest 3.x release: currently 3.3.1~~
- ~~Again check for issues with [jQuery Migrate](https://github.com/jquery/jquery-migrate) and have a look at the [upgrade guide](https://jquery.com/upgrade-guide/3.0/).~~

If there are issues that require more work than 1 day, provide a rough estimation what needs to be done.

**Comment by deiferni** [comment]
(gemäss https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/365)

**Comment by deiferni** [comment]
@phgross and me discussed this and we would like to jump to `1.12.4` only in a first step.

**Comment by Rotonen** [comment]
I've taken a stab at this and I cannot get the current `buildout.coredev` 4.3 tests to run for me. Additionally introducing a newer JQuery into `plone.app.jquery` broke some of the previously stable Robot tests.

The chances of accidental breakage and side effects are high.

**Comment by deiferni** [comment]
outdated.
