### ISSUE TITLE
Clean Up Response Headers

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#5185]
Currently some responses return HTTP headers that are not optimal in terms of security.

**Cache-Control**
Some responses do not contain a Cache-Control header (e.g. file_download_confirmation, breadcrumb_by_uid, tooltip). Set the header if it's missing.
For sensitive content:
`Cache-Control: no-cache, no-store, must-revalidate`
For assets:
`Cache-Control: public, max-age=31536000`

**Remove headers that disclose unnecessary information**
E.g.
- `Bobo-Exception-File`
- `Bobo-Exception-Type`

**Remove server version**
instead of `Server: Zope/(2.13.28, python 2.7.14, linux2) ZServer/1.1`
return `Server: Zope`

**Content-Security-Policy**
Define and implement an appropriate CSP.
E.g. only allow content from the site's own origin: `Content-Security-Policy: default-src 'self'`
If we have inline JS, can we avoid it? If not, can we allow it?

Implementation:
Implement a transform chain (plone.transformchain) that adds/removes/cleans "security"-related headers.
The transform chain should be called as late as possible (after plone.protect, order=9000, maybe even after plone.caching, order=12000).

**Comment by deiferni** [comment]
(gemäss https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/365)

**Comment by Rotonen** [comment]
Split this into three:
Cache-Control issue https://github.com/4teamwork/opengever.core/issues/5295
CSP issue https://github.com/4teamwork/opengever.core/issues/5296
