### ISSUE TITLE
Individuell zusammengestellte Tabellenansicht entsprechend in Excel ausgegeben

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#5186]
Umsetzen gemäss Eintrag in Feedbackforum, dass die individuell zusammengestellte Tabellenansicht entsprechend in Excel ausgegeben wird:

> In der persönlichen Übersicht können Administratoren Pendenzenlisten als PDF erstellen und User Exporte in Excel erstellen über Weitere Aktionen => Auswahl exportieren. Die Spalten in der Aufgabenübersicht lassen sich individuell verschieben und ausblenden. Der Export in Excel übernimmt jedoch jeweils die Darstellung/Ansicht gemäss Standard-Tabellenkonfiguration (fixe Reihenfolge, alle Spalten werden angezeigt etc.). 

https://feedback.onegovgever.ch/t/aufgaben-ueberwachen-pendenzenkontrolle-exporte-in-excel/1176

**Comment by deiferni** [comment]
Replaced by https://github.com/4teamwork/opengever.core/issues/5469.
