### ISSUE TITLE
SPV: Anhänge in Beilagen umbenennen

### ISSUE THREAD

**Issue by livschal** [4teamwork/opengever.core#5189]
Bitte gemäss https://feedback.onegovgever.ch/t/spv-beilagen-oder-anhaenge-zu-antraegen/907 erledigen:

> In GEVER sind verschiedene Begriffe für angehängte Dokumente in Gebrauch: Anhang, Verweise, Dokumente. In der Sitzungs- und Protokollverwaltung (Word-Version) ist ebenfalls die Rede von Anhängen im Zusammenhang mit Anträgen/Traktanden. Ein Kundenwunsch ist eingegangen wonach der Begriff “Anhänge” durch “Beilagen” ersetzt werden sollte. Frage: Welchen Begriff verwenden Sie um weiterführende Informationen (Dokumentationen, Berichte, Bilder, etc.) zu Geschäften zu beschreiben?

**Comment by Rotonen** [comment]
Does such a unification also work the same way conceptually in French as it works in German and English?
