### ISSUE TITLE
Zip-Export naming conflict.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5192]
If two or more attachments of a proposal have the same title/filename, or if the proposal document has the same title/filename as an attachment this causes a naming conflict within zip-export and grimlock import. Grimlocks zip import then always imports the first file.

Possible solutions:
- put attachments into an additional folder (Anhänge) + prefix them with a number (preferred). I think we could just change the paths in the metadata `.json` inside the zip and it should work fine even if there are additional folders, but i'm not quite certain. @phgross would this work in grimlock or do we need to keep the existing folder structure? 
- don't add a folder but prefix all files with an id and a type prefix (Antrag or Anhang)

⛑ **workaround**: rename attachment documents and/or proposal documents so that there are no more conflicts

**Comment by phgross** [comment]
put attachments into an additional folder and prefix them with a number should work in grimlock.

The following example worked:
```
                    "attachments": [
                        {
                            "checksum": "a074ceb35c3ac0d539b70e251fae4fd2496716afd4af68998d08876920fba6d4",
                            "file": "Traktandum 5/Anhang/1_Sitzungsregelement 1.docx",
                            "modified": "2018-10-16T13:41:50.381528+02:00",
                            "title": "04a ICT Schulen Nidau Medien und Informatik Konzept"
                        },
                        {
                            "checksum": "dbea864b0e131728c588a0f62e27e28597f849781888ac1e2ab82a0fbd937f47",
                            "file": "Traktandum 5/Anhang/2_Sitzungsregelement 1.docx",
                            "modified": "2018-11-08T15:25:40.031638+01:00",
                            "title": "Sitzungsregelement 1"
                        }
                    ],
```
