### ISSUE TITLE
Beiarbeiten der Metadaten bei E-Mail-Dateien im Eingangskorb nicht möglich

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#5198]
- Das Bearbeiten der Metadaten bei E-Mail-Dateien welche per D&D od. via Mail-In in den Eingangskorb von GEVER hochgeladen werden ist aktuell nicht mehr möglich -> Feld "Metadaten Bearbeiten" bleibt ausgegraut.

- Andere Dateien wie Word, Excel ect. hingegen sind davon nicht betroffen, sondern auschliesslich E-Mail-Dateien.

Getestet u. reproduziert unter -> https://dev.onegovgever.ch/fd/eingangskorb#documents-proxy
Ticket -> https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/484

**Comment by njohner** [comment]
This most likely stems from https://github.com/4teamwork/opengever.core/pull/4648, where we revoked the `Modify portal content` permission on inboxes for Administrators and Editors and made a new workflow for documents in inboxes, but forgot about mails.
