### ISSUE TITLE
Create plone content type for Period.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5200]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Currently handling of periods is not implemented so well. If users perform actions in the wrong order numbering of meetings will be incorrect. Manually correcting these errors is time-consuming and requires a programmer. We would like to improve the period implementation so that less errors can occur.

At the moment periods are kept in a relation SQL database. We're about to move SQL data to plone content types wherever possible. Periods are only relevant for committees and don't need to be available across admin-units for multi admin-unit meeting support. Thus periods should be converted to plone content types, the sql model can be removed. The following changes are necessary:

- create a plone content-type for `Period`, `opengever.meeting.period`
- schema fields: 
  - `title`
  - `date_from`
  - `date_to`
  - `decision_sequence_number` (only visible for `Manager`)
  - `meeting_sequence_number` (only visible for `Manager`)
- ~~create a two-state workflow. to find the relevant period for a meeting, we use the meeting's date.~~
- create a one-state workflow. to find the relevant period for a meeting, we use the meeting's date.
- instead of fetching the current period based on a SQL query, we must switch to catalog queries
- periods created within a committee belong to the committee
- migration SQL-> plone
- display hint (warning) on meeting-page when no period for meeting date exists
- display error when attempting to decide meeting without periods

out of scope:
- relation from meeting to period when holding the meeting, might be implemented when the meeting is a plone content-type
- Allow (whom? `Administrator` and `CommitteeAdministrator `?) to change the sequence numbers currently used in the period.

Part of https://github.com/4teamwork/opengever.core/issues/5106

some todos so i shall not forget:
- [x] implement tests for `Period.get_current()`
- [x] add period add form defaults (title, start/end)

**Comment by phgross** [comment]
Fachliches Review: 👍
