### ISSUE TITLE
Reiter "Meine Aufgaben" soll keine erledigten Aufgaben als Pendent auflisten

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5202]
Der Reiter meine Aufgaben soll keine Aufgaben im Status erledigt auflisten, sofern der Status `Pendent` aktiviert ist.

**Comment by Rotonen** [comment]
@phgross only on the personal overview tab, or on all of them?

https://github.com/4teamwork/opengever.core/commit/119bb9c6d21ed81385f7e7ebedf4a17943c4024c#diff-e737e0baa4cf2bf4512cb03ac84e82c8R47

Seems the split between pending and closed states was not thought of originally in the implementation - what's the actual desired end game here: simple exclusion from that category or providing more filters per default on the task tabs?
