### ISSUE TITLE
OGIP 42 - Webaktion in Action-Buttons

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5221]
_Harvest: `OneGov GEVER` - `Feature: Aktionen für Drittanwendungen - OGIP 42`_

Darstellungsort: `action-buttons` 

Die Webaktion wird in der Aktionenliste von Aufgaben, Dokumenten und anderen Inhalten mit einer Aktionsliste dargestellt. Dies funktioniert für Inhaltstypen die eine solche Aktionsliste darstellen (im Moment Aufgaben, Weiterleitungen, Anträge, Dokumente). Bei diesen Aktionen kann ein Icon verwendet werden (optional).
Bsp:
![image](https://user-images.githubusercontent.com/485755/50228900-5b710280-03a9-11e9-8b80-341b43d74901.png)

- [ ] Aufgaben und Weiterleitungen
- [ ] Dokumente
- [ ] Anträge

Umsetzung gemäss [OGIP 42](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-2622/document-23827)

**Comment by njohner** [comment]
resolved in #5407
