### ISSUE TITLE
Dokumentation von meeting Ablauf aktualisieren

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5224]
In https://github.com/4teamwork/opengever.core/pull/5101 we changed the way participants to a meeting are managed. Now participants to a meeting that do no longer have an active membership are displayed in the participants-tab with a red mark in front. They can be removed from the meeting by setting them to absent. This should be documented here:

https://docs.onegovgever.ch/user-manual/spv/sitzung-durchfuehren/

**Comment by livschal** [comment]
done, siehe https://github.com/4teamwork/opengever.core/pull/5457
