### ISSUE TITLE
Include type in favorites endpoint

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#5258]
The favorites endpoint should also return the portal type. This is needed for the new frontend which needs to determine the favorite icon.

The portal type should be included as the `@type` attribute, as in other endpoints.
E.g.
```json
  {
    "@id": "http://localhost:8080/fd/@favorites/zopemaster/1", 
    "@type": "opengever.repository.repositoryfolder",
    "admin_unit": "Finanzdepartement", 
    "favorite_id": 1, 
    "icon_class": "contenttype-opengever-repository-repositoryfolder", 
    "oguid": "fd:1339226669", 
    "position": 0, 
    "target_url": "http://localhost:8080/fd/resolve_oguid/fd:1339226669", 
    "title": "9.5. ICT", 
    "tooltip_url": null
  }
```

**Comment by lukasgraf** [comment]
@buchi IMHO this should be `portal_type`, not `@type`.

`@type` refers to the type of the item referenced by the `@id`. That type would be `favorite` or something though. A repositoryfolder's JSON representation doesn't have  a `favorite_id` or a `position` etc.
