### ISSUE TITLE
REST API Endpoint für Journaleinträge

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5259]
_Harvest: `Projekt - Umsetzung GEVER-RIS` - `GEVER-API`_

Aus einer Drittanwendung (RIS) möchten wir in einem GEVER-Dossier Journaleinträge anlegen.
Konkret holen wir über die REST API Dokumente ab und kopieren sie in einen anderen Mandanten im Zusammenhang mit dem Geschäftsprozess. Diesen Schritt möchten wir in beiden Systemen Journalisieren damit dies nachvollziehbar ist.

Ich stelle mir einen Endpoint vor der es ermöglicht, einen neuen Eintrag im Journal hinzuzufügen.

**Comment by deiferni** [comment]
in the next release we'll provide a specification (documentation first approach), @lukasgraf can help

**Comment by elioschmutz** [comment]
Meine Spezifikation sieht wie folgt aus:

- neuer Endpoint `POST .../@journal` welcher für `IJournalizable`-Objekte registriert wird
- Permission: `zope2.View`
- Es wird ein Journal-Eintrag vom Typ "Externer Eintrag" erstellt
- Payload: `title: String`, `comment: String`, `documents: Liste von OGUID`s
- Der Ersteller des Eintrages wird der Verwender der REST-API

- Response: `200 OK`

Dies deckt die Basisfunktionalität ab. Was sind genau die Funktionen welche unterstützt werden sollen? Beispiele:
- Kontakte hinzufügen (gem. [manueller Eintrag](https://github.com/4teamwork/opengever.core/blob/master/opengever/journal/entry.py#L22)
- Titel und Kommentar in mehreren Sprachen
- Variabler Journal-Typ:  soll vom Konsument selber gesetzt werden können (der Journal-Typ ist momentan ein übersetzbares Message-Objekt welches vor dem Titel angezeigt wird)
- Vordefinierte Journal-Typen: können in der Registry in verschiedenen Sprachen erfasst werden und anschliessend beim Konsumieren gesetzt werden.

**Comment by elioschmutz** [comment]
@jone @deiferni

**Comment by deiferni** [comment]
folgende Anpassungen würde ich machen:

Permission solltest du unbedingt auf `cmf.ModifyPortalContent` ändern.

Ich würde den ersten Wurf einfach halten und alle Journal-Einträge über die API als "Manuelle Einträge" betrachten. Also konkret am `ManualJournalEntryAddForm` orientieren, wir haben überall  diesen Knopf hineinprogrammiert 😉 mit dem du als Benutzer in einem Formular einen Journaleintrag hinzufügen kannst:
![screenshot 2019-02-20 at 10 53 28](https://user-images.githubusercontent.com/736583/53082789-e97a7e00-34fd-11e9-91a0-b69a4f146e93.png)

Ich schlage deshalb folgende kleinere Änderungen vor:
- Payload neu `category` (vocabulary-basiert), `comment` und `documents`
- Hinter `documents` verbirgt sich ein RelationValue, ich würde das analog setzen wie z.B. die `relatedItems`. Ich glaube die api will dort jeweils u.A. einen Pfad auf das Dokument und nicht eine OGUID 🤔. Bin aber nicht zu 100% sicher, am besten du klärst das noch kurz ab.
- Titel analog zum manuellen Journaleintrag autoamtisch zusammensetzen aus "Manueller Journaleintrag" + Kategorie

ansonsten aus meiner Sicht 👍. @jone deckt das eueren Use-Case so ab? Bitte um (👍 | 👎 | 💬 ).

**Comment by jone** [comment]
👍 Finde ich gut, vor allem auch dass es wie manueller Journaleintrag funktioniert.
Mehrsprachig ist momentan nicht gefordert, daher dies nicht machen.

**Comment by elioschmutz** [comment]
OK

Ich werden für die Eintragserzeugung auch gleich die Klasse `ManualJournalEntry` verwenden.

D.h. ich werde im Payload auch Kontakte und Users erlauben.

Betr. Dokumente, Kontakte und Users:

`ManualJournalEntry` benötigt Plone-Objekte und erzeugt daraus einen Journaleintrag. D.h. ich benötige für den API-Enpoint einen Object-Lookup. Ich werde die `@id`dazu verwenden.

Unklar ist für mich noch die `Benutzer` und `Kontakte`. So wie ich das sehe, gibt es im GEVER momentan keine Möglichkeit um Benutzer und Kontakte abzufragen. D.h. wir können auch keine Benutzer und Kontakte einem Journal-Eintrag hinzufügen. Sehe ich das richtig? Oder wie weiss die externe Anwendung, welche Kontakte und Benutzer es gibt?

Endgültige Spez:

* neuer Endpoint `POST .../@journal` welcher für `IJournalizable`-Objekte registriert wird
* Permission: `cmf.ModifyPortalContent`
* Es wird ein Journal-Eintrag vom Typ "Manueller Eintrag" erstellt
* Payload: `comment: String required`, `category: String` und `documents: Liste von Pfaden`
* Der Ersteller des Eintrages wird der Konsument
* Response: `200 OK`
* Response bei nicht vorhandener Kategorie oder Dokumenten: `400 Bad Request`

**Comment by deiferni** [comment]
Du kannst beim manuellen Journaleintrag ja auch keine Kontakte und Benutzer referenzieren, oder 🤔? Daher würde ich das vorerst ausblenden.

**Comment by elioschmutz** [comment]
Doch... 

<img width="585" alt="bildschirmfoto 2019-02-21 um 14 38 10" src="https://user-images.githubusercontent.com/557005/53172736-5cf7ba80-35e6-11e9-9163-f180e15c9691.png">

**Comment by deiferni** [comment]
Oh, sorry. Mit dem `IContactSettings.is_feature_enabled` natürlich, wir haben das per default nicht an 😂 .
Die User stehen in einem Vocabulary, d.h. externe App könnte die Werte des Vocabularies über die API abfragen und dem Endpoint mitgeben. Ist aber aus meiner Sicht nicht zwingend sondern optional und nur wenns grad "gäbig" geht.
