### ISSUE TITLE
Subdossier werden in Subdossier-Reitern nicht angezeigt -> betrifft nur der EDGE-Browser

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#5274]
- Subdossiers werden in Subdossier-Reitern nicht angezeigt -> betrifft nur den EDGE-Browser
- Extranet-Ticket -> https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/521

**Comment by jounsiboss** [comment]
- Hat sich erledigt -> s. Extranet-Ticket.

**Comment by deiferni** [comment]
bitte nur tickets eröffnen wenn das problem reproduziert werden kann. bitte schritte zum reproduzieren im ticket angeben.

**Comment by jounsiboss** [comment]
👍
