### ISSUE TITLE
Standard Plone REST API endpoint @types/opengever.dossier.businesscasedossier raises error

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#5283]
**Request:**
GET http://localhost:8080/fd/@types/opengever.dossier.businesscasedossier HTTP/1.1
Accept: application/json
Authorization: Basic [pwd]

**Response:**
HTTP/1.1 500 Internal Server Error
Server: Zope/(2.13.28, python 2.7.15, darwin) ZServer/1.1
Date: Wed, 23 Jan 2019 07:53:47 GMT
Content-Length: 1873
Content-Type: application/json
X-Frame-Options: SAMEORIGIN
```
{
  "message": "'str' object has no attribute 'params'",
  "traceback": [
    "File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/Publish.py\", line 138, in publish",
    "    request, bind=1)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/mapply.py\", line 77, in mapply",
    "    if debug is not None: return debug(object,args,context)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/Publish.py\", line 48, in call_object",
    "    result=apply(object,args) # Type s<cr> to step into published object.",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.rest-1.2.0-py2.7.egg/plone/rest/service.py\", line 23, in __call__",
    "    return self.render()",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-3.4.1-py2.7.egg/plone/restapi/services/__init__.py\", line 19, in render",
    "    content = self.reply()",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-3.4.1-py2.7.egg/plone/restapi/services/types/get.py\", line 53, in reply",
    "    self.request",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-3.4.1-py2.7.egg/plone/restapi/types/utils.py\", line 206, in get_jsonschema_for_portal_type",
    "    fti, context, request, excluded_fields=excluded_fields)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-3.4.1-py2.7.egg/plone/restapi/types/utils.py\", line 175, in get_jsonschema_for_fti",
    "    tagged_values=get_tagged_values(schemas, WIDGETS_KEY)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-3.4.1-py2.7.egg/plone/restapi/types/utils.py\", line 141, in get_tagged_values",
    "    if widget and widget.params:"
  ],
  "type": "AttributeError"
}
```

No troubles when using different type (e.g. http://localhost:8080/fd/@types/opengever.disposition.disposition)

**Comment by njohner** [comment]
seems also broken for other types.
* `opengever.document.document`
* `opengever.dossier.dossiertemplate`
* `opengever.meeting.meetingdossier`
* `opengever.meeting.proposaltemplate`
* `opengever.meeting.sablontemplate`
* `opengever.private.dossier`
* `opengever.private.folder`
* `opengever.repository.repositoryfolder`
* `opengever.task.task`
* `opengever.tasktemplates.tasktemplate`
* `opengever.workspace.folder`
* `opengever.workspace.workspace`

**Comment by njohner** [comment]
All the others work ok

**Comment by njohner** [comment]
So collecting the different errors we have:
* for fields `date_of_completion`, `reference_number`, `addable_dossier_types`, `receipt_date`, `allowed_ad_hoc_agenda_item_templates`, `expectedStartOfWork`: Fail in here https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/types/utils.py#L142, with `widget` being a string (`'ftw.datepicker.widget.DateTimePickerWidgetFactory'`) instead of a widget
* `start` and `deadline` defaults can't be json serialized (`datetime.date`)
* for field `classification`, we fail when getting the vocabulary:
  ```
  Traceback (innermost last):
    Module ZPublisher.Publish, line 138, in publish
    Module ZPublisher.mapply, line 77, in mapply
    Module ZPublisher.Publish, line 48, in call_object
    Module plone.rest.service, line 23, in __call__
    Module plone.restapi.services, line 19, in render
    Module plone.restapi.services.types.get, line 53, in reply
    Module plone.restapi.types.utils, line 210, in get_jsonschema_for_portal_type
    Module plone.restapi.types.utils, line 179, in get_jsonschema_for_fti
    Module plone.restapi.types.utils, line 123, in get_jsonschema_properties
    Module plone.restapi.types.adapters, line 80, in get_schema
    Module plone.restapi.types.adapters, line 260, in additional
    Module opengever.base.restricted_vocab, line 65, in __call__
    Module opengever.base.restricted_vocab, line 74, in get_allowed_choice_names
    Module opengever.base.restricted_vocab, line 106, in _acquire_value
    Module opengever.base.acquisition, line 50, in acquire_field_value
  ```

**Comment by njohner** [comment]
Branch with tests:
https://github.com/4teamwork/opengever.core/tree/nj_restapi

**Comment by elioschmutz** [comment]
The following issues are describing our problems:

- datetime serialization error: https://github.com/plone/plone.restapi/pull/618
- widget-string error: https://github.com/plone/plone.restapi/issues/664
- vocabulary error: not yet analyzed 

https://github.com/plone/plone.restapi/pull/618
