### ISSUE TITLE
Combination of rename and copy move patches may cause duplicate brains.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5291]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

The combination of 
https://github.com/4teamwork/opengever.core/blob/9e4e3ebd100194ed4552c799676719650d7a7034/opengever/base/browser/paste.py#L87
and 
https://github.com/4teamwork/ftw.copymovepatches/blob/3f2751527416a51074f7e0df8ac22ca9226aadcb/ftw/copymovepatches/cmfcatalogaware.py#L64-L129
seems to cause duplicate brains when copying and pasting a dossier that contains one document.

We could not reproduce it reliably across machines but i could just reproduce it for every copy and paste operation on my machine. Also the problem surfaces on customer deployments sometimes.

deactivating one of `self.rename_object(copied_obj)` or `ftw.copymovepatches` made the issue disappear.

we suspect that the optimisations in `ftw.copymovepatches` does not expect that an object is copied and moved in the same transaction.

Steps to reproduce:
- Checkout opengever.core, commit `e82c28b52`
- Import the attached zexport into a repository folder, e.g. `2. Bildung`: [zexport.zip](https://github.com/4teamwork/opengever.core/files/3032870/zexport.zip)
- Copy the imported dossier
- Paste the clipoard into any repository folder (can but does not have to be the same you copied from)
- The pasted dossier will appear duplicated as it creates inconsistent catalog entries (i.e. two brains result from queries)

**Comment by lukasgraf** [comment]
Was able to reproduce with those exact steps on my machine 👍 🎉
