### ISSUE TITLE
The *.xls extension has been dropped from mimetype registry.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5304]
For an unknown reason the *.xls file extension has been dropped from our mimetypes registry even though it should be included according to our mimetypes profile https://github.com/4teamwork/opengever.core/blob/e82c28b5249be768820f8c804caf284bdefc1b04/opengever/policy/base/profiles/mimetype/mimetypes.xml#L98-L108.

Also some entries seem to be duplicated:
![screenshot 2019-01-29 at 18 30 13](https://user-images.githubusercontent.com/736583/51927537-12728c00-23f4-11e9-837a-dffff89289e3.png)

The *.vsd und *.vsdx files seem also directly affected.

next steps:
- analyse what is going on and why the mimetype profile is not applied correctly
- decide how to fix, either quickly fix the excel and other missing/incorrect entries or fix the whole registry

See https://extranet.4teamwork.ch/support/gever-ai/tracker/334.

**Comment by deiferni** [comment]
(This may be a good opportunity to get rid of the extra mimetypes profile and put everything in the same location)

**Comment by elioschmutz** [comment]
Note:

Duplications

0: "Metalink file"
1: "Microsoft Word Document"
2: "Rich Text Format (RTF)"
3: "comic book archive"
4: "comic book archive"
5: "comic book archive"
6: "Kexi database file-based project"
7: "Comma-separated values"

**Comment by elioschmutz** [comment]
@deiferni die fehlenden Mimetypes: `*.vsd` und `*.vsdx` konnte ich nicht reproduzieren. Für das fehlende `xls` gibt es einen PR #5334

**Comment by deiferni** [comment]
Nein ich habe auch gerade gesehen, dass visio etc. in https://github.com/4teamwork/opengever.core/pull/5114 und https://github.com/4teamwork/ftw.bumblebee/pull/126 schon adressiert haben. Ich denke *.xls ist im Moment das einzige unmittelbare Problem.

**Comment by deiferni** [comment]
@elioschmutz kannst du für die Duplikate einen neuen Issue auftun? Ich würde vorschlagen wir fixen nur *`.xls` in `2019.1`. In einem zweiten Schritt müssen wir uns überlegen wie wir mit den von plone zur Verfügung gestellten mimetypes registry umgehen wollen. Ein möglicher Weg wäre, dass wir in Zukunft nur noch unsere eigenen mimetypes-registry führen und die von Plone bereitgestellten Types beim Setup komplett überschreiben, bzw. vorgängig purgen.
