### ISSUE TITLE
RuntimeError: Could not find sort index xxx

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#531]
```
/home/zope/eggs/Zope2-2.13.18-py2.7.egg/ZPublisher/Publish.py:126→ publish
/home/zope/eggs/Zope2-2.13.18-py2.7.egg/ZPublisher/mapply.py:77→ mapply
/home/zope/eggs/Zope2-2.13.18-py2.7.egg/ZPublisher/Publish.py:46→ call_object
/home/zope/eggs/ftw.tabbedview-3.3.11-py2.7.egg/ftw/tabbedview/browser/tabbed.py:152→ listing
/home/zope/eggs/ftw.tabbedview-3.3.11-py2.7.egg/ftw/tabbedview/browser/listing.py:109→ __call__
/home/zope/eggs/ftw.tabbedview-3.3.11-py2.7.egg/ftw/tabbedview/browser/listing.py:218→ update
RunTimeError: Could not find sort_index "['receipt_date', '']" in this tab configuration.
```

Some Errbit entries:
 - [sortable_tilte](https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/53fee4223838189186000bea)

- [task_id_checkbox_helper](https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/53e3950a383818c0600016e2)

- [delivery_date](https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/53bcea37383818806e001cae)

- [document_date](https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/53bce4cf383818806e001c55)

*search for `sort_index` fore more errors*

**Comment by phgross** [comment]
The problem is that the `groupBy` parameter contains a list instead of a string. 

See the request-parameter of a errbit error:
``` python
{
  "_dc" => "1421764127663",
  "dir" => "DESC",
  "dossier_state_filter" => "false",
  "ext" => "json",
  "groupBy" => "['', 'responsible']",
  "initialize" => "0",
  "mode" => "json",
  "old_view_name" => "overview",
  "searchable_text" => "2014",
  "sort" => "start",
  "tableType" => "extjs",
  "view_name" => "dossiers"
}
```

**Comment by phgross** [comment]
Will be solved with https://github.com/4teamwork/ftw.table/pull/39

**Comment by deiferni** [comment]
will be fixed in next ftw.table release (https://github.com/4teamwork/ftw.table/pull/39)
