### ISSUE TITLE
Create script to fix out-of-sync internal catalog data structures

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5314]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

We've had cases in production where some internal data structures of the `ZCatalog` are out of sync.

Specifically, `catalog._catalog.uids` and `catalog._catalog.paths` should be two mappings that should have the same length, and be mirrors of each other:

- `_catalog.uids` maps object paths (the catalog internally calls those `uid`s) to RIDs
- `_catalog.paths` maps RIDs to object paths

We have an issue in `ai` where there's an old path left over in the values of the `_catalog.paths` mapping, but it's not present as a key in `_catalog.uids`:

```python
(Pdb) # paths present as values in _catalog.paths but not as key in _catalog.uids
(Pdb) set(_catalog.paths.values()).difference(set(_catalog.uids.keys()))
set(['/ai/.../dossier-39505/dossier-49266'])    

(Pdb) len(_catalog.paths)
377622
(Pdb) len(_catalog.uids)
377620
(Pdb) _catalog._length.value
377622
```
*(Redacted to protect the innocent)*

From this PDB session it's also evident that there is a second, different problem: The lengths are off by two, not just one, but there's only one path that appears in `_catalog.paths` but not `_catalog.uids`. So this means there is also one path that appears twice in the values of `_catalog.paths` (two different RIDs mapped to the same path).

(I later confirmed this, `len(_catalog.paths.values()) - len(set(_catalog.paths.values())) == 1`).

The stock [`catalog.uncatalog_object(path)`](https://github.com/zopefoundation/Products.ZCatalog/blob/master/src/Products/ZCatalog/Catalog.py#L377-L407) is unable to fix this, because it bails and logs an error if it can't find an RID in `_catalog.uids`.

So we need to create a script that fixes these issues by carefully modifying those catalog internal data structures, and finally updating `_catalog._length` accordingly.

We already have an [unindex_duplicates_by_path.py](https://github.com/4teamwork/opengever.maintenance/blob/master/opengever/maintenance/scripts/unindex_duplicates_by_path.py) script that fixes similar cases, but it would need to be extended / rewritten to also takes these cases into account.

**Comment by deiferni** [comment]
https://github.com/4teamwork/ftw.copymovepatches/blob/3f2751527416a51074f7e0df8ac22ca9226aadcb/ftw/copymovepatches/browser/catalog_fixes.py may be a good starting point, too.

**Comment by deiferni** [comment]
As discussed yesterday, taking over based on https://github.com/4teamwork/opengever.maintenance/tree/lg-find-catalog-inconsistencies
