### ISSUE TITLE
OneOffixx: Standardwert für Vorlagengruppe

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#5322]
Text umbenennen im Dropdown "Vorlagengruppe": Anstattt "Kein Wert" --> "Alle Vorlagen"
Falls Favoriten --> "Favoriten" (siehe #5246)

**Comment by Rotonen** [comment]
Split the favorites stuff off into https://github.com/4teamwork/opengever.core/issues/5333 as that's clearly a feature request for 2019.2.
