### ISSUE TITLE
Mehrfache Anzeige des gleichen Mimetypes in der mimetypes_registry

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#5341]
Es gibt mehrere doppelte Mimetypes, welche jedoch nicht wirklich doppelt registriert sind. Die ID ist die gleiche. Sie werden lediglich mehrfach angezeigt. Das Problem kann mit einer neuen Plonesite reproduziert werden (kein GEVER). Somit ist dies wohl keine Fehlkonfiguration, sondern das aktuelle Verhalten der Mimetypesregistry.

Folgende Mimetypes werden in der `mimetypes_registry` mehrfach angezeigt:

0: "Metalink file"
1: "Microsoft Word Document"
2: "Rich Text Format (RTF)"
3: "comic book archive"
4: "comic book archive"
5: "comic book archive"
6: "Kexi database file-based project"
7: "Comma-separated values"

![](https://user-images.githubusercontent.com/736583/51927537-12728c00-23f4-11e9-837a-dffff89289e3.png)

Notes:
Ursprünglicher Issue: https://github.com/4teamwork/opengever.core/issues/5304

**Comment by phgross** [comment]
Problem scheint sich nicht auf die Benutzer auszuwirken --> close.
