### ISSUE TITLE
Use POST instead of GET for workflow transitions

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5348]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Transitions like `dossier-17/transition-resolve` are currently performed as `GET` requests.

Especially in the case of expensive transitions like recursive dossier resolution this can be a problem, because those GET requests are easily triggered by acciddent by someone copy & pasting links, browser URL prefetching, ...

We should make those POSTs instead.

**Comment by deiferni** [comment]
Verbs will be used correctly with new UI.
