### ISSUE TITLE
Benachrichtigungs-Einstellungen

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#5365]
- Die Bezeichnungen der Benachrichtigungs-Empfänger sind nicht gut resp. verständlich übersetzt (s.Anhang).

- Getestet wurde dies unter -> https://dev.onegovgever.ch/fd/@@personal-preferences

![bildschirmfoto 2019-02-11 um 10 22 38](https://user-images.githubusercontent.com/11310148/52554567-87c46080-2de7-11e9-870c-7a4fd618590d.png)

**Comment by phgross** [comment]
@jounsiboss in welchem Extranet Issue wurde das gemeldet? Was wären mögliche Alternativen?

**Comment by phgross** [comment]
Aus meiner Sicht ist diese Bezeichnung sinnvoll. Eine Aufgaben Erinnerung ist nicht ausschliesslich für den Auftragnehmer möglich sondern für alle Benutzer, also z.B. auch für den Vorgesetzten.
