### ISSUE TITLE
Dokumenten-Upload per D&D von Outlook nach GEVER im EDGE-Browser ungenügend

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#5381]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

- Es handelt sich offenbar um ein (Fehlverhalten) im EDGE-Browser, da ein D&D nicht akzeptiert und durchgeführt wird, solange sich der Mouse-Cursor nicht in der D&D-Area befindet.

- Die D&D-Area wird aber bereits angezeigt wenn sich der Mouse-Cursor noch ausserhalb der D&D-Area befindet, in Chrome z.B. ist dies besser gelöst.

- Es wurde intern diskutiert dies GEVER-seitig resp. die D&D-Area ggf. zu optimieren.

- Extranet-Ticket -> https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/562

![d d_edge](https://user-images.githubusercontent.com/11310148/52724359-7c239600-2faf-11e9-9000-e9c8e50e3eeb.gif)

**Comment by Rotonen** [comment]
This is an Edge bug (also present in IE11), tracked upstream Edge-side in https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/5184459/

We cannot tackle this with reasonable amounts of effort. Dropping pursuing this for now and bumping down to prio 2.

**Comment by phgross** [comment]
Solving this issues is not possible in a reasonable amounts of effort. The problem will be taken into account in the development of the new UI.

@jounsiboss bitte Extranet-Ticket entsprechend updaten ..n
