### ISSUE TITLE
Inconsistent content for 'preview_url' returned by the API

### ISSUE THREAD

**Issue by sebastianmanger** [4teamwork/opengever.core#5391]
# Summary

The API delivers inconsistent responses for the field "preview_url" depending on the called endpoint:

* The `@listing`-endpoint returns an URL containing the content of the PDF (<path>/pdf?access_token<...>)
* The `@detail`-endpoint (?) returns an URL containing the 'frame' for PDFJS which then displays the PDF (<path>/preview?access_token<...>)

# Example requests

## Listing endpoint

* Request: `https://lab.onegovgever.ch/ordnungssystem/fuehrung/gemeinderecht/dossier-13/@listing?name=documents&columns:list=preview_url`
* Relevant part of the response:
`"preview_url": "https://lab.onegovgever.ch/YnVtYmxlYmVl/api/v3/resource/gever_lab/foo/pdf?..."`

## Document detail endpoint

* Request: `https://lab.onegovgever.ch/ordnungssystem/fuehrung/gemeinderecht/dossier-13/document-35`
* Relevant part of the response:
`"preview_url": "https://lab.onegovgever.ch/YnVtYmxlYmVl/api/v3/resource/gever_lab/foo/preview?..."`

# Reasoning

RIS rolls its own PDF preview (included in RIS), so we always need the actual PDF content, not the PDFJS-preview.

**Comment by Rotonen** [comment]
You'd be fine with the API returning both in both cases - the framed from-GEVER-and-Bumblebee viewer and 'just the PDF'?

**Comment by sebastianmanger** [comment]
Yes. The issue to us is that different content is returned for the same attribute name ("preview_url"). The response with attribute name for the listing endpoint:
"preview_url": "https://lab.onegovgever.ch/YnVtYmxlYmVl/api/v3/resource/gever_lab/foo/pdf?..."
and for the detail endpoint:
"preview_url": "https://lab.onegovgever.ch/YnVtYmxlYmVl/api/v3/resource/gever_lab/foo/preview?...",

**Comment by jone** [comment]
I would expect these entries:
- `preview_url` containing `/preview?`, which delivers PDF.js (existing but inconsistent)
- `pdf_url` containing `/pdf?`, delivering the PDF directly (not existing yet)

In RIS we only need `pdf_url` since we ship our own PDF viewer.
