### ISSUE TITLE
Cannot navigate bumblebee overlays beyond pagination border

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#5393]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

1) Open a dossier with enough documents to paginate the documents tab
2) Open the Bumblebee overlay of a document from the documents tab
3) Navigating onto the last one at the pagination border will spew a javascript error and disallow navigating over the pagination border

Are we failing to cater to some baked in expectation from `ftw.showroom`?

https://github.com/4teamwork/ftw.showroom/blob/7a7feb58cfb965f5c90534e663091d749b49d3f7/ftw/showroom/resources/ftw.showroom.js#L466

The issue is `element` is undefined. Seems like we're not rendering the UUID (data tag) for the arrow button from beyond the pagination border?

**Comment by Rotonen** [comment]
Additionally when starting to browse from other pages than the last page, the first one does not have an arrow left.

**Comment by phgross** [comment]
Problem wurde im neuen UI korrigiert.
