### ISSUE TITLE
REST API Endpoint für Berechtigungen

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5395]
_Harvest: `Projekt - Umsetzung GEVER-RIS` - `Entwicklung`_

Die Anwendung RIS verwendet GEVER als Ablage für Dossiers und Dokumente und führt zusätzlich weitere Metadaten zu den Geschäften.

Aus Security-Sicht soll RIS sich grundsätzlich an GEVER anpassen und soll nicht widersprüchliche Security umsetzen.

Um dies so umzusetzen soll RIS GEVER nach gewissen Berechtigungen fragen können. Dies wird bereits so gehandhabt indem der Lesezugriff auf bestimmte Ordnungspositionen geprüft wird und dadurch grundsätzlich Zugriff auf bestimmte Bereiche freigeschaltet wird. Wir möchten aber auf weitere Berechtigungen prüfen können, wie "Bearbeiten".

Daher der Vorschlag, dass GEVER über einen REST-API-Endpoint Fragen zu Berechtigungen (oder Berechtigungsgruppen) zulässt. Über die API sollen die internen Plone-Berechtigungen nicht exponiert werden, sondern es soll so generalisiert werden dass es aus API-Sicht Sinn macht.

Mögliche Beispiele für Berechtigungen:
- Lesen
- Bearbeiten
- Hinzufügen je Typ
- Berechtigungen Ändern
- Löschen resp. in den Papierkorb verschieben
- Umbenennen
Sowie die "primären" Berechtigungen der verschiedenen Rollen; siehe https://docs.onegovgever.ch/admin-manual/rollenmodell/

Aus RIS-Sicht ist noch nicht klar, welche konkreten Berechtigungen benötigt werden. Die konkrete Liste der Berechtigungen soll sowieso aus GEVER-Sicht definiert werden.

**Comment by phgross** [comment]
outdated.
