### ISSUE TITLE
Solr REST Search Endpoint

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5406]
_Harvest: `Projekt - Umsetzung GEVER-RIS` - `GEVER API`_

RIS möchte nach Dokumenten in GEVER suchen können, z.B. nach Dokumentart oder Volltext. Wir haben dort Solr im Einsatz für GEVER.

Da aber der `@search`-Endpoint nur mit `portal_catalog` funktioniert benötigen wir hier eine Lösung, wie wir den Endpoint mit Solr kompatibel machen.

Der Vorschlag ist, ein neuer `@solr-search`-Endpoint zu bauen aus folgenden Gründen:
- `@search` funktioniert in einem Solr-Setup solange nicht `SearchableText` verwendet wird; das heisst wenn man mit und ohne Solr kompatibel sein will und keine Volltextsuche absetzt ist der bestehende `@search` Endpoint immer noch sinnvoll.
- Beim neuen Endpoint können wir mehr Solr-Query-Syntax verwenden und von der Katalog-Syntax abweichen und so mehr Möglichkeiten anbieten.

https://plonerestapi.readthedocs.io/en/latest/searching.html

@deiferni mir war nicht bewusst dass dies noch ein Problem ist. Können wir das schätzen und herausfinden, bis wann das in einen Release passt?
/cc @buchi

**Comment by deiferni** [comment]
for the record, we disucessed this last friday. we came to the conclusion that we want to implement this exactly as specified 😄.

@jone i recall you wanted to filter for something we might not have a solr-index for. what was that again? i'd suggest you open a separate issue if you recall.

**Comment by jone** [comment]
@deiferni It's the `document_type` index. I've added an issue: https://github.com/4teamwork/opengever.core/issues/5444
