### ISSUE TITLE
Ensure Solr is included for new SaaS deployments

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5409]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

We need to ensure that for newly created SaaS deployments, Solr is already included. Either by updating the policy template, or by extending from a new common `saas-deployment.cfg` in `gever-buildouts`.

**Comment by phgross** [comment]
No longer optional features:
 - bumblebee
 - casauth
 - activity feature

Change default:
 - `docproperty` -> True
 - `private_folder` -> True
 - `dossier_templates ` -> True

Remove:
 - `officeatwork`

**Comment by deiferni** [comment]
outdated.
