### ISSUE TITLE
Disable versioning for mails

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#541]
_E-Mails haben und brauchen keine Versionierung. Vollständig ausbauen und unterdrücken( Bemerkung es gibt alte mails aus Konsul, welche Versionen ausweisen)_

Todo:
- [ ] Upgradestep which removes the mail-behavior from the mail fti.

To clarify:
- What happens with the old versions of mails with multiple versions?

**Comment by phgross** [comment]
@lukasgraf weisst du hier den genauen Stand der Dinge? So viel ich weiss haben wir die Versionierung für Mails komplett deaktiviert, bin mir aber nicht sicher.

**Comment by lukasgraf** [comment]
Nein, meines Wissens noch nicht komplett deaktiviert. Es gibt definitiv noch Mails welche Versionen haben, und `IVersionable` ist für neue Mails AFAIK auch provided.

**Comment by deiferni** [comment]
we don't care any more.
