### ISSUE TITLE
@vocabularies/classification_classification_vocabulary returns wrong titles

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#5411]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Endpoint currently returns the the same value for `title` and `token`: `"unprotected", "confidential", "title": "classified"`. Expected titles are: `"Nicht klassifiziert", "Vertraulich", "Geheim"`.

**Comment by Rotonen** [comment]
The vocabulary in question provides gettext translation labels, not translated strings.

As per discussion with @buchi, the architecture of how to deal with translations in the front end is still open.

**Comment by Rotonen** [comment]
So what do we do with vocabularies providing gettext translation labels?

I see three options:
1) They need to return translated strings
2) We need to build separate vocabularies for the translated strings
3) We build a way to grab the translations into the frontend

Option two seems the least effort.

**Comment by phgross** [comment]
Currently blocked because of https://github.com/plone/plone.restapi/pull/744

**Comment by phgross** [comment]
Solved via #5725
