### ISSUE TITLE
Quickupload does not reload the tab after a successful upload after a failed upload

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#5419]
_Harvest: `OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Steps to reproduce:

1) Navigate to anywhere where you can quickupload
2) Upload something which will fail
3) Without dismissing the errors, upload a file, which will successfully upload
4) The tabbedview is not reloaded

It works fine, if the user first dismisses the errors.

**Comment by deiferni** [comment]
No longer relevant with new UI.
