### ISSUE TITLE
REST API Endpoint für Journaleinträge

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5428]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Auflisten von Journal-Einträgen:

- GET Endpoint für `IJournalizable` Objekte
- Permission `zope2.view`
- Pro Journal Eintrag sollen folgende Werte mitgegeben werden (am existierenden JournalTab orientieren):
  - time
  - title (bereits übersetzt)
  - actor_id
  - actor_fullname
  - comments
  - references enthält die Listen `documents` , `contacts` sowie `users`
- Batching gemäss `plone.restapi` https://plonerestapi.readthedocs.io/en/latest/batching.html

Siehe auch #5259

**Comment by Rotonen** [comment]
The journal is stored in an annotation. One can only fetch this as a whole. Why bother with the batching?

**Comment by phgross** [comment]
Das Journal kann sehr gross werden, es ist unnötig das Ganze zwischen backend und frontend hinzusenden ...
