### ISSUE TITLE
Do a documentation pass on the REST API endpoints

### ISSUE THREAD

**Issue by Rotonen** [4teamwork/opengever.core#5434]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

As wished through https://github.com/4teamwork/opengever.core/pull/5433, we currently have major gaps in our REST API documentation we should address.

Known gaps:

* Listings
* ~~Documents~~
* ~~Dossiers~~

And probably many more.

We should thus do a cleanup sweep of our REST API documentation as we now have, including, but not limited to, active internal clients depending on it.

**Comment by phgross** [comment]
@Rotonen what do you mean with?
 `Documents`
 `Dossiers`

**Comment by Rotonen** [comment]
We have no explicit examples of how to interact with those data types over the REST API.

**Comment by deiferni** [comment]
Ok we should document only the `@listing` endpoint in a first step as this is a major gap.

**Comment by Rotonen** [comment]
Maybe also ask any internal consumers for what they already use and where they would have found documentation useful?
