### ISSUE TITLE
Prevent tasks from being created as private or switched to private when feature is not enabled

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5441]
_Harvest: `OneGov GEVER` - `Feature: Persönliche Aufgaben - OGIP 46`_

Follow up from #5332 make sure the creation or switch to a private change is not possible when the feature is disabled, also via REST API.

**Comment by Rotonen** [comment]
This has hit a snag at how to do more complex contextful validations on the REST API.
