### ISSUE TITLE
Add document_type to Solr schema

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5444]
_Harvest: `Projekt - Umsetzung GEVER-RIS` - `aktueller Sprint`_ 

In RIS, I'd like to mark certain documents as [`RRB`](https://www.informatik.sg.ch/tools/glossar.handle__%7Bslash%7Dcontent%7Bslash%7Dapplikationen%7Bslash%7Dglossar%7Bslash%7Dinformatik%7Bslash%7Drrb.html).

The RIS application would set the `document_type` when it uploads the document through the REST API.

Later, we want to be able to find all RRB documents for one year. In order to do that, we would query the catalog for the `document_type` through the new [`@solr-search`](https://github.com/4teamwork/opengever.core/issues/5406) API endpoint.

**Comment by njohner** [comment]
`document_type` is not indexed in GEVER, so that means we need to add either a new index or as metadata

**Comment by njohner** [comment]
As discussed, an index would make more sense, as we might also want to be able to query by `document_type` on the catalog. Metadata is probably superfluous.

**Comment by njohner** [comment]
Also note that `document_type` is a keyword field, so we will need an SG specific vocabulary or something alike?
