### ISSUE TITLE
User-Berechtigung für @vocabularies-Endpint

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#5449]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Momentan kann der `@vocabularies`-Endpoint nur von einem  `Manager` oder `Site Administrator` verwendet werden.

Ein Gever-User kann somit keine Vocabularies abholen. Das Gever-UI benötigt jedoch die vocabularies.

- [x] überprüfen, ob die Berechtigung des `@vocabularies`-Endpoints auf die `zope2.View` geändert werden kann (security)
- [x] die Rollen für die Berechtigung `plone.restapi: Access Plone vocabularies` muss angepasst werden

**Comment by elioschmutz** [comment]
@phgross (@deiferni ) ist dieser Fehler intern bei euch bereits bekannt? Falls nicht, werde ich ihn demnächst angehen. Falls schon, wäre ich über paar Infos dankbar warum die Vocabularies nicht für alle Benutzer verfügbar sind.

**Comment by deiferni** [comment]
ich kann mich erinnern, dass @buchi und @lukasgraf dies vor kurzem diskutiert haben.
problem ist, wenn ich mich richtig erinnere, dass man nicht ohne weiteres alle vocabularies für alle benutzer zur verfügung stellen kann, sonst sehen die benutzer u.U. dinge, die sie nicht sollten. bitte noch zuwarten.

**Comment by elioschmutz** [comment]
@deiferni gibt es hierzu bereits Neuigkeiten?

**Comment by phgross** [comment]
Ich habe das Probleme und deren Konsequenzen mit @lukasgraf besprochen: 
Aus unserer Sicht ist es zwingend notwendig das alle Benutzer die `plone.restapi: Access Plone vocabularies` permission erhalten. Es muss aber sichergestellt werden, das dabei keine Daten zugänglich werden, die nicht für jedermann bestimmt sind. Ich habe deshalb die vorhanden Vocabularies geprüft und eingeordnet:

**Unproblematisch:**
```
- @vocabularies/opengever.task.bidirectional_by_reference",
- @vocabularies/plone.app.vocabularies.SupportedContentLanguages",
- @vocabularies/plone.app.vocabularies.AvailableContentLanguages",
- @vocabularies/plone.schemaeditor.VocabulariesVocabulary",
- @vocabularies/opengever.tasktemplates.active_tasktemplatefolders (listet alle Standardabläufe auf, nur Titel, daher unproblematisch)
- @vocabularies/plone.app.vocabularies.WeekdaysShort
- @vocabularies/classification_classification_vocabulary
- @vocabularies/plone.app.vocabularies.ImagesScales
- @vocabularies/lifecycle_archival_value_vocabulary
- @vocabularies/plone.app.vocabularies.CommonTimezones
- @vocabularies/opengever.base.ReferenceFormatterVocabulary
- @vocabularies/plone.app.vocabularies.Month
- @vocabularies/plone.app.vocabularies.WorkflowStates
- @vocabularies/opengever.meeting.LanguagesVocabulary
- @vocabularies/lifecycle_custody_period_vocabulary
- @vocabularies/opengever.dossier.type_prefixes
- @vocabularies/plone.app.vocabularies.WeekdaysAbbr
- @vocabularies/plone.app.vocabularies.UserFriendlyTypes
- @vocabularies/opengever.document.document_types
- @vocabularies/plone.app.vocabularies.Timezones
- @vocabularies/plone.app.vocabularies.Skins
- @vocabularies/plone.app.vocabularies.AllowableContentTypes
- @vocabularies/plone.app.vocabularies.Workflows
- @vocabularies/lifecycle_retention_period_vocabulary
- @vocabularies/opengever.task.unidirectional_by_reference
- @vocabularies/ftw.usermigration.post_migration_hooks
- @vocabularies/classification_public_trial_vocabulary
- @vocabularies/plone.app.vocabularies.AllowedContentTypes
- @vocabularies/ftw.usermigration.pre_migration_hooks
- @vocabularies/opengever.dossier.ValidResolverNamesVocabulary
- @vocabularies/plone.app.discussion.vocabularies.CaptchaVocabulary
- @vocabularies/plone.app.vocabularies.Actions
- @vocabularies/opengever.dossier.container_types
- @vocabularies/plone.contentrules.events
- @vocabularies/opengever.task.unidirectional_by_value
- @vocabularies/opengever.journal.manual_entry_categories
- @vocabularies/plone.app.vocabularies.Roles
- @vocabularies/plone.app.vocabularies.Groups
- @vocabularies/ftw.usermigration.mapping_sources
- @vocabularies/opengever.dossier.participation_roles
- @vocabularies/plone.app.discussion.vocabularies.TextTransformVocabulary
- @vocabularies/plone.app.vocabularies.Weekdays
- @vocabularies/plone.app.vocabularies.WorkflowTransitions
- @vocabularies/collective.quickupload.fileTypeVocabulary
- @vocabularies/Fields
- @vocabularies/collective.taskqueue.queues
- @vocabularies/plone.app.vocabularies.AvailableEditors
- @vocabularies/plone.app.vocabularies.PortalTypes
- @vocabularies/plone.app.controlpanel.WickedPortalTypes
- @vocabularies/opengever.meeting.ProposalTemplatesVocabulary
- @vocabularies/plone.app.vocabularies.SyndicationFeedTypes
- @vocabularies/plone.app.vocabularies.ReallyUserFriendlyTypes
- @vocabularies/plone.app.vocabularies.MonthAbbr
- @vocabularies/classification_privacy_layer_vocabulary
- @vocabularies/plone.app.vocabularies.Users
- @vocabularies/wicked.vocabularies.CacheConfigurationsOptions
- @vocabularies/plone.app.vocabularies.SyndicatableFeedItems
- @vocabularies/opengever.repository.RestrictedAddableDossiersVocabulary
- @vocabularies/cmf.calendar.AvailableEventTypes
```

**Funktionieren zurzeit nicht (werde ich noch genauer prüfen)**
```
- @vocabularies/wicked.vocabularies.BaseConfigurationsOptions
- @vocabularies/plone.app.content.ValidAddableTypes
- @vocabularies/Interfaces
- @vocabularies/Behaviors
- @vocabularies/opengever.tasktemplates.tasktemplates
- @vocabularies/http://www.imsglobal.org/vocabularies/iso5964_equivalences.xml
- @vocabularies/http://www.imsglobal.org/vocabularies/iso2788_relations.xml
````

**Schlagworte:**
Das bestehende User Interface listet bereits alle Schlagworte auf, und sind bereits jetzt durchsuchbar, die Benutzer sind entsprechend sensibilisiert.
```
- http://localhost:8080/fd/@vocabularies/ftw.keywordwidget.UnicodeKeywordVocabulary
- http://localhost:8080/fd/@vocabularies/plone.app.vocabularies.Keywords
```

**Gremien inkl. deren Mitglieder, Sitzungs- und Antragsvorlagen** 
m.E. unproblematisch, ist bereits für alle Benutzer ersichtlich. Der Titel aller Gremien ist nicht geheim, ebenso deren Vorlagen oder Mitglieder. Bei den Mitglieder sind zudem nur die Namen der Personen ersichtlich, keine weiteren Angaben.
```
- http://localhost:8080/fd/@vocabularies/opengever.meeting.CommitteeVocabulary
- http://localhost:8080/fd/@vocabularies/opengever.meeting.ActiveCommitteeVocabulary
- http://localhost:8080/fd/@vocabularies/opengever.meeting.MemberVocabulary
-http://localhost:8080/fd/@vocabularies/opengever.meeting.ProposalTemplatesForCommitteeVocabulary
http://localhost:8080/fd/@vocabularies/opengever.meeting.AdHocAgendaItemTemplatesForCommitteeVocabulary
- http://localhost:8080/fd/@vocabularies/opengever.meeting.MeetingTemplateVocabulary 
```

**Gruppen, Benutzer und OrgUnits**
Sind bereits via Kontakte Reiter (OGDS) und Amtswechsler ersichtlich.
```
- http://localhost:8080/fd/@vocabularies/plone.app.vocabularies.Groups
- http://localhost:8080/fd/@vocabularies/Group Ids
- http://localhost:8080/fd/@vocabularies/opengever.ogds.base.OrgUnitsVocabularyFactory
- http://localhost:8080/fd/@vocabularies/opengever.ogds.base.AssignedClientsVocabulary
- http://localhost:8080/fd/@vocabularies/opengever.ogds.base.OtherAssignedClientsVocabulary
- http://localhost:8080/fd/@vocabularies/plone.app.vocabularies.Users
```

**Vorlagen und Standardabläufe**
Sind bereits für alle ersichtlich.
```
- http://localhost:8080/fd/@vocabularies/opengever.tasktemplates.ResponsibleOrgUnitVocabulary
```

**Unklar:**
```
- http://localhost:8080/fd/@vocabularies/plone.app.vocabularies.Catalog (???)
- http://localhost:8080/fd/@vocabularies/plone.formwidget.relations.cmfcontentsearch
```

@lukasgraf @deiferni ich wäre froh wenn ihr meine Einschätzung prüfen und Feedback geben könntet. Thx.

**Comment by deiferni** [comment]
did spot some that raise an eyebrow, like:
- ftw.usermigration.*, not sure what is exposed here
- Fields, what is this?
- collective.taskqueue.queues, dito?
- plone.app.vocabularies.Users, that could expose all users. not sure we want that.

we could always overwrite the `@vocabularies` endpoint and filter out some that we're very sure that they do not need to be visible.

**Comment by lukasgraf** [comment]
> ftw.usermigration.*, not sure what is exposed here

Just registered adapters, like pre-migration hooks and their titles. -> Unproblematic.

> Fields, what is this?

List of zope.schema Field types -> Unproblematic.

> collective.taskqueue.queues, dito?

The `default` taskqueue queue and its name -> Unproblematic.

> plone.app.vocabularies.Users, that could expose all users. not sure we want that.

We already expose those through the OGDS contacts tab and autocomplete widgets. -> Unproblematic.

> `plone.formwidget.relations.cmfcontentsearch`

This is the [`CMFContentSearchSource`](https://github.com/plone/plone.app.relationfield/blob/master/plone/app/relationfield/source.py#L11-L46) vocabulary from `plone.app.relationfield`. It does not enumerate terms. It's search method would, once that were to be built in `plone.restapi`, allow to perform _restricted_ catalog searches. So nothing the `@search` endpoint doesn't already do.

@phgross ich teile daher deine Einschätzung 👍

**Comment by elioschmutz** [comment]
Wie geht es hier weiter?

Noch nicht besprochen wurden die Vocabularies, welche nicht funktionieren (siehe Einschätzung von @phgross am Anfang)

**Comment by phgross** [comment]
Die Berechtigung kann angepasst werden. Ich würde aber noch ein kurzen Software Test schreiben der prüft, das keine neuen Vocabularies mit heiklen Daten zugänglich sind. So etwas in der Art:

```
NON_SENSITIVE_VOCABUALRIES = [
 *alle aktuellen Vocabularies*
]

def test_vocabularies_endpoint_does_not_provide_sensitive_data(self):
  browser.open('@vocabularies)
  self.assertEqual(NON_SENSITIVE_VOCABUALRIES, browser.json)
```
