### ISSUE TITLE
Double-Check and re-enable template mimetypes.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5453]
In https://github.com/4teamwork/opengever.core/pull/5382 support for templates was removed. But it seems they are supported by OC, i just tested a `*.dotx` with @buchi. We should

- Verify that the other office templates actually work with OC
- Re-enable those that work, discuss those that don't

This has surfaced in https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/611.

**Comment by Rotonen** [comment]
Templates do work on Windows. They currently do not work on macOS.

**Comment by Rotonen** [comment]
Additionally editing restricted templates also works.
