### ISSUE TITLE
Readonly mode instead of downtime during release.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5462]
_Harvest: `OneGov GEVER` - `CR 2019.2 SG`_

Invest estimate into figuring the following things out:

- could we use `read_only` mode http://www.zodb.org/en/latest/reference/storages.html
- how, separate instance for releases, ...
- what to do gever-side, what happens if something tries to write in read-only mode, how can we handle this elegantly, can we disable some actions easily in read-only mode, maybe display a message on such instances, ...?

https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/624

**Comment by phgross** [comment]
Das Konzept der Phase 1 wurde erarbeitet (https://gever.4teamwork.ch/ordnungssystem/3/2/2/1/dossier-3587/document-30570). Das weitere Vorgehen wird nun an einer Besprechung definiert.
