### ISSUE TITLE
Also add keyword filter to document listings.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5464]
_Harvest: `OneGov GEVER` - `CR 2019.2 SG`_

In https://github.com/4teamwork/opengever.core/pull/5319 we have added a keyword filter to dossier-listings. We want to add it for document-listings, too. Only with solr as they use faceting to query.

- add filter-box to document listings
- add keyword column to document listings
- implement solr queries for document listings, https://github.com/4teamwork/opengever.core/pull/5319 has added some generic components

https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/626

**Comment by Rotonen** [comment]
Sorta tied to https://github.com/4teamwork/opengever.core/pull/5482 - if someone tackles this before that is merged, take a peek.
