### ISSUE TITLE
Allow creating task reminders for specific dates.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5468]
_Harvest: `OneGov GEVER` - `CR 2019.3 SG`_

Currently setting a task reminder is only possible via aliases (day before, same day, ...). The users want to be able to set a reminder for a specific date. This has the drawback that we cannot update the remind date automatically when the deadline changes.

- Add new option `Specific Date` to task-reminders which shows/hides a Date-Picker widget. Possibly in another field.
- Amend remind API and JS to require a specific date as input when aforementioned option is selected
- Do not recalculate remind date for the specific date option, always use the date that was selected by the user

See also https://github.com/4teamwork/opengever.core/issues/5467

https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/631

Spezifikation / Diskussion:
 - Keine Behandlung für Fristverkürzung und -verlängerung

Todos :
 - Neuer Reminder Typ  "absolut"
 - API Support
 - Aufgabendetailansicht
 - Akzeptieren Formular (Ist zurzeit noch ein z3c.form Feld, das Widget muss nun in dieses integriert werden).

Schätzung: 8 Pts. (nur API 3)

**Comment by lukasgraf** [comment]
I'm taking this over from @elioschmutz after being updated on his progress.

**Comment by phgross** [comment]
@elioschmutz @lukasgraf ist auf DEV anscheinend nicht deployed, ich sehe keine zusätzliche Reminder Möglichkeit ...

**Comment by elioschmutz** [comment]
@phgross ist auf dem lab...

**Comment by phgross** [comment]
@elioschmutz ok, dev bitte auch aktualisieren. Thx

**Comment by phgross** [comment]
Fachliches Review: 👍

**Comment by elioschmutz** [comment]
ok, ist aktualisiert
