### ISSUE TITLE
Dossier journal PDF generated twice

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5473]
Currently when `resolving` a dossier we create PDFs for journal and tasks. Those seem to be generated twice when i:

- create a dossier
- close it
- reopen it
- close it again

expected outcome:
the already existing PDF should be updated with a new version.

![screenshot 2019-03-07 at 09 40 38](https://user-images.githubusercontent.com/736583/53943546-9be54000-40bd-11e9-8757-2606f73a5f24.png)

as correctly suspected by @njohner the object is not reindexed correctly in the catalog and thus the marker interface is not in `object_provides`.

Possibly related with https://github.com/4teamwork/opengever.core/issues/5458.

**Comment by njohner** [comment]
I've already looked at the code yesterday, so I'll quickly fix that
