### ISSUE TITLE
xlsm kann nicht in Office Connector geöffnet werden

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5474]
<img width="538" alt="bildschirmfoto 2019-03-07 um 09 55 57" src="https://user-images.githubusercontent.com/7469/53944303-62adcf80-40bf-11e9-9d4e-0ae147890c50.png">

Fehler: Button "Auschecken und Bearbeiten" ist deaktiviert und kann nicht gedrückt werden.
Erwartung: Ich möchte dieses Dokument mit Office Connector bearbeiten.

Siehe auch #4180

**Comment by deiferni** [comment]
fixed by https://github.com/4teamwork/opengever.core/pull/5448 or https://github.com/4teamwork/opengever.core/pull/5454/
