### ISSUE TITLE
Platzhalter für OGIP55

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5477]
_Harvest: `OneGov GEVER` - `OGIP 55 - Dossierabschluss`_

Siehe https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3397
Genaue Spez. folgt.

**Comment by phgross** [comment]
OGIP 55 wurde umgesetzt und ist im kommenden Release 2019.2 enthalten.
