### ISSUE TITLE
Favoriten überschneiden Dokumente nach Tooltip anzeige

### ISSUE THREAD

**Issue by Linuexone** [4teamwork/opengever.core#5484]
Es gibt einen Fehler mit der Favoriten anzeige:

Wenn man eine etwas grössere Favoritenliste hat und diese über die Dokumente gehen funktioniert das.
Aber wenn man nun bei den Dokumenten vorher über das Tooltip "hovert" und danach die Favoritenliste öffnet, so überschneidet sich das "versteckte" Tooltip mit der Liste.

Siehe Screenshot und Gif (.mp4 in guter Quali im Ticket)

![favoriten uberlappen](https://user-images.githubusercontent.com/5165030/54037990-c0c1dc00-41bf-11e9-9692-a6808eeac2df.png)

![favouriten uberschneiden_kurz](https://user-images.githubusercontent.com/5165030/54038279-6e34ef80-41c0-11e9-8bc7-6b8d90a9a673.gif)

Ticket: https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/600
Dev: https://dev.onegovgever.ch/fd/ordnungssystem/bevoelkerung-und-sicherheit/einwohnerkontrolle#documents-proxy

**Comment by phgross** [comment]
Dieser Fehler wurde korrigiert, Problem ist auf dev.onegovgever.ch mit dem neuen Release 2019.2 nicht mehr reproduzierbar.
