### ISSUE TITLE
Ordering by keywords eliminates rows without keywords

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5489]
_Harvest: `Feature: Unterstützung bei der Dossierführung - OGIP 33`_  

- Create some dossiers in a listing
- add keywords to some but not all of them

![Screenshot 2019-03-11 at 15 22 16](https://user-images.githubusercontent.com/736583/54130954-ac751d80-4411-11e9-816b-7b8e55e12c17.png)

- Order by keywords column
![Screenshot 2019-03-11 at 15 23 32](https://user-images.githubusercontent.com/736583/54131001-c282de00-4411-11e9-82f8-abe84506a6f2.png)

- The items without any keywords disappear

Only catalog based listings are affected. This seems to have something to do with how KeywordIndex treats items with no keywords in a query.

Possible solutions:
- add a dummy entry for such items
- no longer make keywords sortable in tables

**Comment by phgross** [comment]
It does not make sense to sort on a column, which displays multiple values --> Solution: no longer make keywords sortable in tables.
