### ISSUE TITLE
Solr settings for filter

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5508]
_Harvest: `OneGov GEVER` - `Feature: Integration Solr`_ 

I feel like our current solr settings don't make much sense when we use solr for filtering in the tabbed view.
I think that for queries in that case we should set:
```
generateWordParts="0"
generateNumberParts="0"
```
The problem with the current settings is that if I search for some sort of label with hyphens in it, it will be split up and then the smaller parts will match unexpected things (see https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/612). This problem is emphasized by the fact that we're not sorting by relevance here.

I'm not completely sure how we would overwrite the settings just for the filter, but I think it would suffice to set a different `fieldType` (see `managed-schema` file in the `conf`)

I tried locally to use the settings above for all queries and it fixed the filtering problem.

**Comment by jounsiboss** [comment]
Wichtige Ergänzung eines Kunden:

"Wir haben festgestellt, dass Filtern mit Sonderzeichen auf Dossierebene (Filtern auf Ordnungsposition) funktioniert. Aber auf Dokumentebene (innerhalb von Dossier) nicht."

**Comment by phgross** [comment]
@buchi Kannst du hier Feedback geben? Ich kenne mich beim SOLR zu wenig aus.

**Comment by phgross** [comment]
Wurde analysiert (siehe Antworten im Extranet Ticket) und mit #5707 angepasst/korrigiert.
