### ISSUE TITLE
Extend listing endpoint with depth parameter

### ISSUE THREAD

**Issue by lvonlanthen** [4teamwork/opengever.core#5513]
_Harvest: `Projekt - Umsetzung GEVER-RIS` - `GEVER API`_

In RIS, we need to display only the immediate documents of a dossier, *without* the documents of subdossiers. An additional parameter for the `@listing` endpoint would be very helpful, similar to the `depth` query string parameter of the `@search` endpoint (https://plonerestapi.readthedocs.io/en/latest/searching.html?highlight=depth#query-options).

For our use case, we cannot use the `@search` endpoint as we need specific `columns` of the documents (e.g. `pdf_url` and `checked_out`), which are only available for the `@listing` endpoint.

### Update:
`path_depth` indexer has been introduced in ftw.solr https://github.com/4teamwork/ftw.solr/pull/132

Nur Solr Variante muss `depth` Parameter unterstützen.

**Comment by buchi** [comment]
Currently we don't have the depth indexed in Solr. This will require an additional field `path_depth` and reindexing all items. Though reindexing can and should be done without waking up all objects.

**Comment by jone** [comment]
This is not important anymore for RIS, since we'd like to make less requests for performance reasons, see #5618. Thus, we need to solve that in RIS.

**Comment by lukasgraf** [comment]
@phgross Kostenstelle `Projekt - Umsetzung GEVER-RIS - Entwicklung` gibts nicht mehr. Ich nehme `Projekt - Umsetzung GEVER-RIS - GEVER API`
