### ISSUE TITLE
Has children metadata

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#5527]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

For the new frontend we need to know if an object has children of the same type. This information should be available from the catalog in search results, particularly the `@listing` endpoint. Also a GET of an object should return this info.

Example questions we need to answer:
- Does a dossier have subdossiers?
- Is a repository folder a leaf node?
- Does a task have subtasks?

I propose to add a new boolean metadata column/Solr stored field `has_children` or `is_leafnode`.

Currently there's no need to know if an object has children of another type, e.g. if a dossier has documents. I'm not sure if there will be a need for that in the future.

`has_children` may be a little bit misleading as a dossier that contains only documents would have a value of `has_children=False`.

Suggestions welcome.

**Comment by deiferni** [comment]
something like `is_leaf_of_type` or `has_children_of_same_type` might work.

i would not use `has_children` or `is_leafnode` as a name without indicating that the type of the object is relevant. that way confusing is guaranteed. also if we need a proper `has_children` in the future we have even more naming issues as that name would then be taken.

**Comment by njohner** [comment]
Agreed. Similar would be `has_sametype_children`
Or to avoid confusion in the future, add a parameter: `has_children(same_type=True)`

**Comment by njohner** [comment]
Sorry, rereading the issue, we want a metadata, so obviously, adding a parameter is out of the question...
