### ISSUE TITLE
Runner für nächtliche Jobs implementieren

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5554]
_Harvest: `OneGov GEVER` - `OGIP 55 - Dossierabschluss`_

Ein soll ein Runner implementiert werden, der **wiederkehrende nächtliche Jobs** ausführt.

Es soll dazu einen [`zopectl.command`](https://github.com/4teamwork/opengever.core/blob/231e541b10ef074e7431ddea35f272166e5626f4/setup.py#L201) geben der wie folgt aufgerufen wird:
`bin/instance0 run_nightly_jobs`

_(Dazu wird ein Cron-Job eingerichtet werden, der den Job zu Beginn des Zeitfensters aufruft)_

Dieser Runner soll auszuführende Jobs auffinden, und die Jobs ausführen solange das **Zeitfenster** für nächtliche Jobs nicht abgelaufen ist. Das Zeitfenster muss konfigurierbar sein (Registry). Als default würde ich `00:00 – 05:00` vorschlagen.

Auszuführende Jobs soll der Runner finden, indem er nach `INightlyJobProvider` Adaptern sucht.

Ein Provider ist zum einen dafür verantwortlich, seine Jobs aufzulisten. Wie er diese genau managed ist dem Provider überlassen (interne oder externe Queue, oder Ad-Hoc basierend auf Queries, ...).

Zum anderen stellt der Provider die Logik bereit um einen Job auszuführen ("Arbeitsfunktion"). Die Iteration über die Jobs, und das Aufrufen der "Arbeitsfunktion" wird hingegen dem Runner überlassen, damit dieser die Ausführung der Jobs angemessen **koordinieren und ggf. auch abbrechen** kann.

Ein `INightlyJobProvider` adaptiert `context` und `request`, und:
- Listet seine einzelnen Jobs über eine `__iter__` Methode auf
- Implementiert ein `__len__` das (effizient!) seine Anzahl Jobs bestimmt
- Implementiert eine `run_job(args, interrupt_func)` Methode, welche den Job ausführt. 
Diese Methode bekommt als `interrupt_func` eine bound method des Runners, welche sie in regelmässigen Abständen aufrufen muss. Dies hat den Zweck, dass der Runner regelmässig die Ausführung des Jobs vorzeitig zu unterbrechen, falls das Zeitfenster überschritten wurde oder die Systemlast zu hoch ist (s.U.)

Desweiteren soll es noch eine spezifischere Form `IQueueBasedNightlyJobProvider` geben, welche:
-   Seine Jobs in einer persistenten Queue speichert (welche der Job Provider selbst verwaltet)
-   Eine `queue_job(args)` Methode implementiert, welche es erlaubt einen Job zu queuen
-   Die `run_job(args, interrupt_func)` Methode so implementiert, dass sie nach Abschluss den Job aus der Queue entfernt (das committen nach der Ausführung des Jobs übernimmt der Runner, Jobs sollen nie selbst committen).

Der Runner soll die Ausführung von Jobs dann geordnet abbrechen, wenn entweder das Zeitfenster überschritten ist, oder die Systemlast zu hoch ist. Diese beiden Bedingungen sollen sowohl vor dem Ausführen eines Jobs wie auch während der Ausführung eines (evtl. länger dauernden) Jobs mit Hilfe der `interrupt_func` geprüft werden.

Die Idee für die `interrupt_func` ist die folgende:
Der Runner implementiert eine Methode, z.B. `Runner.interrupt_if_necessary()`, welche diese beiden Bedingungen überprüft (Zeitfenster + Systemlast). Falls eine der Bedingungen verletzt ist, raised die Methode eine Exception.

Diese Methode wird der `INightlyJobProvider.run_job()` Methode mitgegeben, und von der `run_job` Methode wird erwartet, dass sie diese in regelmässigen Abständen aufruft, um den Control-Flow temporär an den Runner zurückzugeben. Dies könnte beispielsweise in einem for-loop in der `run_job` Methode passieren.

Wenn die `interrupt_func()` eine Exception raised, darf diese von der `run_job()` Methode natürlich nicht abgefangen werden. Der Control-Flow geht dann somit zurück zum Runner, welcher die Exception behandelt:
- Die laufende Transaktion wird aborted
- Aus der Exception wird der genaue Grund für den Early Abort entnommen (z.B. Diskspace < %5).
- Es wird manuell eine Message nach Sentry geloggt, die festhält dass:
  - Ein Early Abort stattgefunden hat
  - Den Grund für den Early Abort
  - Wieviele Jobs von welchem Typ dass übrig geblieben sind, und auf die nächste Nacht verzögert werden mussten.

Ansonsten soll der Runner nach der Ausführung jedes Jobs die transaction committen. Die Jobs müssen so implementiert werden, dass sie mit dieser Tatsache umgehen können.

Die Ausführung der Jobs im Runner sollte im Pseudo-Code etwa so aussehen:

```python
def execute_pending_jobs(self):
    job_providers = get_job_providers()
    for provider in job_providers:
        if len(provider) == 0:
            continue

        for job_args in provider:
            try:
                self.interrupt_if_necessary()
                provider.run_job(job_args, self.interrupt_if_necessary)
            except (TimeWindowExceeded, SystemLoadCritical) as exc:
                transaction.abort()
                message = self.format_early_abort_message(exc)
                self.log_to_sentry(message)

            transaction.commit()
```

**Comment by njohner** [comment]
resolved in https://github.com/4teamwork/opengever.core/pull/5566
