### ISSUE TITLE
Addable-Types in serialized context

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#5561]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Momentan muss über den Endpoint `@types` zusätzlich abgefragt werden, welche Inhalte hinzugefügt werden können.

Dies bedeutet, dass wir im Frontend immer zwei Requests machen müssen. Einmal für den Context selbst und einmal für die types. Da wir an verschiedenen Orten einen Check machen müssen, welche Inhalte hinzugefügt werden können, wird dieser Endpoint nun auch mehrmals aufgerufen.

Dazu kommt, dass der `@types` Endpoint eine Liste mit allen Typen zurückgibt mit der Info, ob er hinzugefügt werden kann oder nicht. D.h. die Liste muss zusätzlich noch gefiltert werden, bevor sie verwendet werden kann.

Zusätzlich fehlt die Information, um welchen Typ es sich genau handelt. Der Typ muss über die @id extrahiert werden.

- [ ] Die `addable_types` sollten direkt im serialisiertem Inhalt daherkommen. Und zwar nur die hinzufügbaren Typen.
- [ ] `@type` Attribut hinzufügen

Alternativ sollte der `@types` endpoint als Komponente mit `expand` geladen werden können.

Beispielresponse:

```
    GET /ordnungssystem/dossier-23
    Accept: application/json
```

```json
{
  "@context": "http://www.w3.org/ns/hydra/context.jsonld",
  "@id": "https://example.org/ordnungssystem/fuehrung/dossier-23",
  "@type": "opengever.dossier.businesscasedossier",
  "title": "Titel des Objekts",
  "addable_types": [
    {
      "@id": "http://localhost:8080/fd/@types/opengever.meeting.proposal",
      "title": "Antrag",
      "@type" "opengever.meeting.proposal"
    },
    {
      "@id": "http://localhost:8080/fd/@types/opengever.task.task",
      "title": "Aufgabe",
      "@type" "opengever.task.task"
    },
    {
      "@id": "http://localhost:8080/fd/@types/opengever.document.document",
      "title": "Dokument",
      "@type" "opengever.document.document"
    },
  ],
  "...": "..."
}
```

**Comment by elioschmutz** [comment]
@phgross wie siehst du das? Kann ich das so umsetzten?

**Comment by elioschmutz** [comment]
@all4manu FYI

**Comment by phgross** [comment]
Mit der neuen plone.restapi version (siehe #5774) ist der @types endpoint nun expandable (see https://github.com/plone/plone.restapi/issues/766).

**Comment by lukasgraf** [comment]
@elioschmutz wie oben beschrieben ist der `@types` endpoint jetzt expandable (siehe unterstes Beispiel auf https://plonerestapi.readthedocs.io/en/latest/expansion.html oder [dieser diff](https://github.com/plone/plone.restapi/pull/768/files#diff-054ed45c86d92bd317467a36cd418a72R128)).

*Nur* die hinzufügbaren Typen zurückzuliefern haben wir am Beethoven-Sprint besprochen, und vorerst abgelehnt 😜 Je nach User-Interface kann die Information nützlich sein (z.B. nicht hinzufügbare einfach ausgrauen und nicht verlinken), und es ist ein trivialer map/filter Einzeiler in JS um diese noch zu filtern.
