### ISSUE TITLE
Trennung von Workspace und Dossier

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#5563]
Momentan erbt ein Workspace von einem Dossier und verwendet das `IDossier` behavior.

- https://github.com/4teamwork/opengever.core/blob/master/opengever/workspace/workspace.py
- https://github.com/4teamwork/opengever.core/blob/master/opengever/core/profiles/default/types/opengever.workspace.workspace.xml#L34

es werden jedoch sozusagen keine Funktionen von einem Dossier verwendet. Auch die Felder, welche mit dem `IDossier` behavior daherkommen, werden nicht benötigt.

Dies führt nun dazu, dass wir überall irgendwelche Hooks schreiben müssen, welche Funktionen von einem Dossier für den Arbeitsraum wieder ausbauen.

Beispiel: Das Responsible-Feld (#5557) ist für ein Dossier required wird für den Arbeitsraum jedoch nicht benötigt. Nun müssen hooks geschrieben werden, welche den Responsible aufgrund des Creators setzten (#5559 ). Dies führt zum Schluss auch dazu, dass Teamräume nicht mehr mit dem Zopemaster erstellt werden können, weil es den Zopemaster nicht im OGDS gibt.

Momentan sieht es nicht danach aus, dass uns ein Erben vom Dossier hilft, im Gegenteil. Es schränkt uns ein und führt zu vielen unerwarteten Probleme.

Der Ansatz, dass Funktionalitäten vom Dossier wiederverwendet werden sollen finde ich grundsätzlich gut. Jedoch sehe ich den Weg eher mit Kompositionen anstatt mit Vererbung. 

Denn ein Workspace ist kein Dossier und deshalb sollte es auch nicht davon erben.

- [x] Workspace soll nicht mehr vom Dossier erben
- [x] Workspace soll das IDossier interface nicht mehr verwenden
- [x] WorkspaceFolder soll nicht mehr vom Dossier erben
- [x] WorkspaceFolder soll das IDossier interface nicht mehr verwenden

@maethu kannst du meine Vorgehensweise bestätigen oder kommentieren? Danke dir!

**Comment by maethu** [comment]
@elioschmutz Passt für mich!
