### ISSUE TITLE
Error when mutating document metadata if document is not checked out

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#5567]
Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`
#### Observed behaviour
When trying to send a `patch` request to a document in order to change its metadata, the endpoint throws the following error:

```
{
  "error": {
    "message": "Document not checked-out by current user.", 
    "type": "Forbidden"
  }
}
```

#### Expected behaviour
No error is thrown. Document metadata can be changed without having to checkout the document first.

**Comment by lukasgraf** [comment]
Cannot reproduce.

- Create document in GEVER
- Send `PATCH` with body `{"title": "foo"}`
- Document metadata gets changed.

Please provide steps to reproduce.

**Comment by phgross** [comment]
Kann so nicht reproduziert werden - wir schliessen diesen Issue vorerst.
