### ISSUE TITLE
REST-API Endpint für Teamraum-Teilnehmer

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#5589]
_Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`_

Teilnehmer in einem Teamraum werden momentan über die View `@@participants` verwaltet.

Die View ist bereits mit VueJS umgesetzt und macht asynchrone requests  auf den Endpoint `manage-participants`. Der Endpoint ist jedoch nicht im REST-Standard umgesetzt und somit für das neue GEVER-UI unbrauchbar (https://github.com/4teamwork/opengever.core/blob/master/opengever/workspace/participation/browser/manage_participants.py)

Damit Teilnehmer im neuen GEVER-UI korrekt verwaltet werden können, benötigen wir neue REST-API endpoints.

Vorschlag:

Eine Liste mit allen Teilnehmern und Einladungen.

```http
GET workspace/@participations
```

Response
```http
{
  "roles": [
    {
      "id": "WorkspaceGuest",
      "title": "Gast",
    },
    {
      "id": "WorkspaceMember",
      "title": "Teammitglied",
    },
    ...
  ],
  "items": [
    {
      "@id": "http://gever.ch/workspace/@participations/users/james.bond",
      "participant_fullname": "James Bond",
      "inviter_fullname": "",
      "role": "WorkspaceAdmin",
      "readable_role": "Admin",
      "editable": false,
      "pending": false,
    },
    {
      "@id": "http://gever.ch/workspace/@participations/users/max.muster",
      "participant_fullname": "Max Muster",
      "inviter_fullname": "James Bond",
      "role": "WorkspaceMember",
      "readable_role": "Teammitglied",
      "editable": true,
      "pending": false,
    },
    {
      "@id": "http://gever.ch/workspace/@participations/invitations/xyz",
      "participant_fullname": "Maria Meier",
      "inviter_fullname": "James Bond",
      "role": "WorkspaceMember",
      "readable_role": "Teammitglied",
      "editable": true,
      "pending": true,
    },
  ],
}
```

Eine Einladung hinzufügen
```http
POST workspace/@participations/invitation

{
  "userid": "max.muster",
  "role": "WorkspaceMember"
}
```

Die Rolle einer Einladung updaten
```http
PATCH workspace/@participations/invitations/xyz

{
  "role": "WorkspaceGuest"
}
```

Die Rolle eines Benutzers updaten
```http
PATCH workspace/@participations/users/max.muster

{
  "role": "WorkspaceGuest"
}
```

Eine Einladung löschen:

```http
DELETE workspace/@participations/invitations/xyz
```

Eine Beteiligung löschen:

```http
DELETE workspace/@participations/users/max.muster
```

@maethu @phgross könnt ihr meine Spez bitte genau durchschauen und mir eine Rückmeldung geben, ob meine Überlegungen korrekt sind? Habt ihr sonstigen Input?

Danke euch!

Issuer: https://github.com/4teamwork/gever-ui/issues/20

**Comment by phgross** [comment]
Was gibt der POST zurück, anscheinend irgendeine ID, das ist in der Spez. nicht ersichtlich, ich würde mir hier an der plonerest.api orientieren. 

Hätten wir dann zwei Endpoints, die eigentlich genau das selbe machen, kann man die andere View/endpoints ersetzen?

**Comment by maethu** [comment]
Genau POST müsste den record zurückgeben mit der Einladung.
Ansonsten sollte das passen.

**Comment by elioschmutz** [comment]
👍 danke euch!

@phgross ja, wir hätten dann zwei Endpoints. Die alte zu ersetzten ist möglich. Dazu müsste ich jedoch die momentane Vue-App für das klassische GEVER (btw. gibt es einen Begriff oder Codename für das alte und neue GEVER?) anpassen (https://github.com/4teamwork/opengever.core/blob/master/opengever/workspace/participation/browser/resources/app.js) 

Soll ich diese Anpassung ebenfalls vornehmen?
