### ISSUE TITLE
Regression: Resolving, reopening and resolving dossier again doesn't work in all cases

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5611]
_Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

There seems to be a regression where resolving a dossier, reopening and resolving it again doesn't work in all cases.

**Steps to reproduce**

- Create a dossier
- Create a subdossier inside that dossier
- Add a document to the subdossier
- Resolve the main dossier
- Reopen the main dossier
- Attempt to resolve the main dossier again

**Expected result**
- Main dossier should be resolved recursively

**Actual Result**
- `Fehler: Es sind nicht alle Dokumente und Aufgaben in Subdossiers abgelegt.`

![Screen Shot 2019-04-30 at 13 23 48](https://user-images.githubusercontent.com/405124/56959111-a287b500-6b4c-11e9-9d99-492a51677022.png)

**Comment by njohner** [comment]
Tried to reproduce. I can only reproduce with `journal pdf` enabled, which makes the error quite clear. When checking if there are documents in the main dossier, we do not filter out the journal and task PDFs:
https://github.com/4teamwork/opengever.core/blob/master/opengever/dossier/base.py#L245-L253
