### ISSUE TITLE
@types api endpoint should differ between add and edit form

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5646]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Currently when calling the `@types` endpoint on an object it uses the current context to fetch the result of context aware vocabularies. This works as expected when asking for information for an edit form, but is wrong when asking for information for the add form. 

Example: 
 - I have a repositoryfolder called `Repo 1` with the classification value `classified`
 - I  now ask the `@types` endpoint to give me the available values for the `classification` when adding a dossier to `Repo 1`. So i call `http://localhost:8080/fd/ordnungssystem/repo-1/@types/opengever.dossier.businesscasedossier` but the vocabulary returns all classification values instead of just `classified` 

Analysis:
 - in the RestrictedVocab `_acquire_value` method we differ between add and edit form, by checking on the `IDuringContentCreation` interface, so there should be a possibility (header) to define if i want the `@types` information for an edit or an add form.

**Comment by lukasgraf** [comment]
As discussed:
- It seems that in the most recent version of `plone.restapi` places links to vocabularies instead of inlining them:

```
        "classification": {
            "default": "classified",
            "description": "Grad, in dem die Unterlagen vor unberechtigter Einsicht geschützt werden müssen.",
            "title": "Klassifikation",
            "type": "string",
            "vocabulary": {
                "@id": "http://localhost:8080/fd/ordnungssystem/fuehrung/gemeinderecht/@vocabularies/classification_classification_vocabulary"
            }
        },
```

The vocabulary-links are context sensitive though, so that's good.

- We might want to introduce a `@type` (singular) endpoint in `plone.restapi` that will give you the schema for that specific object (**edit form**), whereas `container/@types/<portal_type>` can be used for the **add form**.

**Comment by phgross** [comment]
Wurde mit dem neuen schema endpoint und den entsprechenden Links für sources umgesetzt.
