### ISSUE TITLE
Delete document in a deactivated subdossier from main dossier

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5650]
Steps to reproduce:
* Create a dossier
* create a subdossier
* add a document to the subdossier
* trash the document
* deactivate the subdossier
* In the main dossier, in the trash, selected the document and delete it.
* Results in the error message`Sie haben keine Objekte ausgewählt.`

The behaviour is correct in the sense that a deactivated dossier should not be modifiable. The error message is confusing though and should instead say something like `The document {docname} cannot be deleted as it is in a deactivated dossier`

<img width="1320" alt="Screen Shot 2019-05-13 at 14 45 41" src="https://user-images.githubusercontent.com/7374243/57622499-07500000-758e-11e9-836a-39ee689ec56a.png">

See also https://extranet.4teamwork.ch/support/edk/tracker-support-gever-edk/136

**Comment by deiferni** [comment]
will be addressed separately in new UI.
