### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5668]
_Harvest: `OneGov GEVER` - `Kommunikation und Dokumentation`_

In the create proposal section (https://docs.onegovgever.ch/user-manual/spv/antrag-erfassen/)
- [ ]  `Beilagen können entweder aus einer bestehenden Vorlage angehängt werden` should rather read `Das Antragsdokument kann entweder aus einer bestehenden Vorlage angehängt werden` (also needs correction in French)
- [ ] In French version `img-saisir_requete_01.png` highlights the save button instead of the `A partir d'un modèle`
- [ ] Text about `Antragssteller` comes in the middle of the text about `Antragsdokument`, seems to make little sense

https://docs.onegovgever.ch/user-manual/spv/periode-abschliessen/
- [ ] Not sure the last part (point 4) makes much sense, as all agendaitems will need to be closed to close the meetings of the previous period??

SPV:
- [ ] Several snapshots in the French version of SPV are outdated because of changes in the translations (requête instead of demande/proposition)
- [ ] img-commission_et_membres-07.png shows the wrong commission
- [ ] img-saisir_requete_03.png shows the "save" button instead of "a partir d'un modèle"
- [ ] img-approbation_proces_verbal-01 highlight the button to create the protocol acceptance proposal.

Tasks:
- [ ] img-taches05.png attribuer à nouveau should be Ré-attribuer

Contacts:
- [ ] `In der Listendarstellung werden standardmässig *Nachname*,
*Vorname*, *E-Mail 1* und *Telefon Arbeit* dargestellt.` does not seem to reflect the reality.

Documents:
- [x] `Travailler les documents` should be `Editer les documents`

Overall:
- [x] Introduce links in the French documentation

**Comment by phgross** [comment]
Dokumentation wurde für die neue Oberfläche vollständig überarbeitet --> outdated.
