### ISSUE TITLE
Änderungen an Dokumenten in einem Zeitraum abfragen

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5672]
**Ausgangslage:**
RIS publiziert gewisse Dokumente aus gewissen Dossiers auf eine Website, basierend auf einer Whitelist pro Dossier. Wir starten mit rund 4500 Dossiers. Die Erwartungshaltung ist dass Änderungen im GEVER automatisch reflektiert werden. Sowohl das Ändern von Dokumenten in irgend einer Form, wie auch das Entfernen oder Verschieben von Dokumenten.

**Anforderungen:**
- Neues Geschäft mit neuer Liste von Dokumenten wird publiziert.
- Verändertes Dokument wird publiziert.
- Dokument, das in den Papierkorb verschoben wurde, wird von der Website entfernt.
- Dokument, das aus dem Dossier verschoben wurde, wird von der Website entfernt.

**Überlegungen:**
Wir haben bereits verschieden Strategie diskutiert, u.A. dass wir ein `@search`-Query mit `trashed=true` machen um gelöschte Dokumente zu finden und zu entfernen. Dies deckt aber das Problem mit dem Verschieben nicht ab (sofern das Query auf ein bestimmtes oder mehrere bestimmte Dossiers angewendet wird).

Weiter haben wir uns überlegt dass wenn wir geänderte Dossiers erkennen, wir dann einfach das Dossier komplett frisch publizieren können und alles "fehlende" automatisch löschen. Dazu brauchen wir aber einen date-index auf dem Dossier, welcher ändert wenn ein darin enthaltenes Dokument in irgend einer Weise ändert.

Allenfalls könnten wir alle Dokumente seit letzter Publikation des ganzen GEVERs abfragen, sowohl mit `trashed=False` and `trashed=True`. Darin sollten auch die Dokumente enthalten sein, die verschoben wurden. Die Herausforderung ist dann für RIS herauszufinden, dass ein Dokument vormals zu einem anderen Dossier gehört hat und entsprechend zu löschen.

Was sind eure Inputs dazu? Was ist eine sinnvolle Strategie die mit vernünftigem Aufwand umsetzbar ist?

**Comment by phgross** [comment]
outdated.
