### ISSUE TITLE
Upgradestep adding oneoffixx settings not working in release 2019.2

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5679]
_Harvest: `[0.322.3 / 17] Projekt - Integration Vorlagenmanagement OneOffixx in GEVER` - `Entwicklung`_

The upgradestep `20180912145057_add_a_registry_setting_for_oneoffixx_baseurl` is outdated and need to be removed in the 2019.2 release. Because the `IOneoffixxSettings` has been changed and no longer provides an field `base_url`.

**Comment by deiferni** [comment]
For the record: `20181012203011_make_oneoffixx_textline_configs_optional_so_they_can_be_unset` also attempts to set the `base_url` default value and also fails.
