### ISSUE TITLE
Editing Favorites in Firefox does not store changes made to title.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5693]
_Harvest: `[3.2.2.1] OneGov GEVER` - `Feature: Favoriten (OGIP 32)`_

Steps to reproduce:
- Open firefox, navigate to an OGG instance
- Make sure you have at least one favorite.
- Got o `/favorites-view`, i.e. click on `Übersicht` in the favorites drop-down menu
- Edit a favorite, change the title and save your changes

Actual outcome:
- The title won't be changed and thus does not appear changed in the listing
- In the console i can observe a `ReferenceError: event is not defined`

Expected outcome:
- The title changes should be persistent

**Comment by phgross** [comment]
funktioniert im neuen UI
