### ISSUE TITLE
Reiter "Meine Aufgaben" soll keine abgelehnten Aufgaben als Pendent auflisten

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5703]
Der Reiter meine Aufgaben soll keine Aufgaben im Status Abgelehnt auflisten, sofern der Statusfilter Pendent aktiviert ist.

Follow up für https://github.com/4teamwork/opengever.core/issues/5202, ersetzt https://github.com/4teamwork/opengever.ftw/issues/44.

**Comment by phgross** [comment]
Wurde im neuen UI umgesetzt.
