### ISSUE TITLE
Incorrect label when checking in a document from officeconnector with rest api enabled flag..

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5735]
The actual label:

![Screenshot 2019-06-19 at 16 09 23](https://user-images.githubusercontent.com/736583/59774855-736e0400-92b0-11e9-87cc-16b140904ff3.png)

The expected label:

![Screenshot 2019-06-19 at 16 10 41](https://user-images.githubusercontent.com/736583/59774902-8aacf180-92b0-11e9-9a0a-24baedd71aca.png)

Origin: https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/763

**Comment by deiferni** [comment]
@phgross you mentioned you wanna figure out if we need the separate journal entry for editing the file or if checkin/checkout would suffice.
IMO adding a separate entry when checking in should be doable with manageable effort.

**Comment by njohner** [comment]
Also see https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20445. Could probably be fixed at the same time

**Comment by phgross** [comment]
Fachliches Review 👍 (bestätigt durch Kunde)
