### ISSUE TITLE
Facetten Support im listing endpoint

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5738]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020`-`Entwicklung`_

Der Listing Endpoint sollte vie optionalen Parameter die Abfrage von Facetten Wertebereichen ermöglichen. 

Die Abfrage des Dossier-Listings Endpoints soll zusätzlich zu den Inhalten auch Werte-Bereiche von möglichen Facetten liefern. Also bspw. die häufigsten Federführenden der aktuellen Trefferliste.

**Comment by njohner** [comment]
* add parameter to listing endpoint: list of fields for which to return facets
* some crude validation of fields
* return facets and counts
