### ISSUE TITLE
Aufgaben listing endpoint soll fullname des responsibles und issuers zurückgeben

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5739]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020`-`Entwicklung`_

Siehe auch Kommentar von https://github.com/4teamwork/gever-ui/pull/272

**Comment by njohner** [comment]
It already returns both as `issuer_fullname` and `responsible_fullname`
