### ISSUE TITLE
Berechtigungscheck für GET Users Endpoint ändern

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5740]
Zurzeit enthält der `@users` endpoint der plone.restapi, ein Permission Check auf `Manage Portal` (siehe https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/users/get.py#L57) . Diese Permission ist `hard-coded` und müsste nun fürs GEVER angepasst werden. Da wir User Informationen für alle Benutzer zugänglich machen wollen.

**Comment by lukasgraf** [comment]
Refactoring of `@users` endpoint in `plone.restapi` has been done in plone/plone.restapi#772 (merged)
