### ISSUE TITLE
Listing endpoint fails for certain fields

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5755]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

Fields that are missing on a certain listing endpoint should return `None` for that field (according to the documentation). But for certain fields it will actually lead to an error instead. For example the following request will fail:
```
http://localhost:8080/fd/ordnungssystem/fuehrung/@listing?name=documents&columns:list=task_type
```

It seems that it's mainly a question of making the `transform`s safer like `translated_task_type`, but also the `create_list_item` function. Another option would be to have a list of available fields for each listing type, but that would be a pain to maintain...

**Comment by njohner** [comment]
Done together with refactoring. Wait for solr tests.

**Comment by phgross** [comment]
Fachliches Review: 👍
