### ISSUE TITLE
Review Persönliche Benachrichtigungseinstellung

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5762]
Ich habe mir die zwei neuen Settings angeschaut und getestet. Sieht soweit i.O. aus und funktioniert wie gewünscht.

Folgende Anpassungen möchte ich noch, die Labels un deren Erklärungen vereinfachen. Diese sind zwar technisch richtig, aber für den Benutzer verwirrend oder zu wenig verständlich. Weniger ist hier mehr. Bitte folgenden Vorschlag umsetzten:
```
**Benachrichtigung für eigene Aktionen aktivieren**
Standardmässig werden für selbst ausgeführte Aktionen keine Benachrichtigungen ausgelöst. Mit dieser Option kann dieses Verhalten verändert werden. Persönlich vorgenommenen Benachrichtigungseinstellungen pro Aktionstyp gelten dabei nach wie vor.

**Benachrichtigungen für Eingangskorb aktivieren**
Alle Benachrichtigungen aufgrund von Eingangskorbberechtigung aktivieren bzw. deaktivieren.
```

Zudem verursacht der Zugriff mittels Manager einen Fehler aus (https://sentry.4teamwork.ch/sentry/onegov-gever/issues/32580/) der sollte verhindert werden.

**Comment by njohner** [comment]
I'll book on
_Harvest: `OneGov GEVER` - `CR 2019.3 SG`_
as in the original issue (https://github.com/4teamwork/opengever.core/issues/5465)
