### ISSUE TITLE
Reset trashed documents

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#577]
A user can reset trashed documents to earlier versions in the document history. I think this should not be possible.

**Comment by phgross** [comment]
Resetting a trashed document is no longer possible in the newest version. 

<img width="863" alt="bildschirmfoto 2017-04-28 um 10 05 32" src="https://cloud.githubusercontent.com/assets/485755/25519939/3d9b0162-2bfa-11e7-840f-3be27ae0c670.png">
