### ISSUE TITLE
resolve_notification view should preserve URL parameters

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#5773]
The `resolve_notification` view should behave the same way as `resolve_oguid`.
When called by a client frontend, the browser automatically performs the redirect and the frontend does not have the possibility to add query parameters to the redirected URL. Thus it must add the required parameters to the `resovle_notification` URL.

BTW why is there a separate view for resolving notifications? For me it would make more sense to use `resolve_oguid` for this.

**Comment by phgross** [comment]
Vermutlich kann resolve_notification von resolve_oguid erben und sie um die eigene Funktion erweitern.
