### ISSUE TITLE
Increase Solr maximal memory to 1024m

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5781]
512m seems to be too low as default for solr maximal memory. Should be increase the default to 1024m, either generally for solr, or at least the default for Gever?

Default is set here: https://github.com/4teamwork/ftw.recipe.solr/blob/master/ftw/recipe/solr/defaults.py#L6

**Comment by deiferni** [comment]
outdated we configure solr memory everywhere.
