### ISSUE TITLE
Dokumentaktionen sollten als portal_actions zugänglich sein

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5786]
_Harvest:  `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Die Dokument Aktionen, also die Actions welche sowohl im Tooltip, Overlay und der Dokumentansicht dargestellt werden, (Kopie herunterladen, auschecken und bearbeiten, einchecken etc. ) sollten als im @actions endpoint zur Verfügung stehen und so auch via API zugänglich sein. Dabei sollen auch die Prüfungen, ob eine Aktion möglich ist, durchgeführt werden.

Erster Vorschlag: Aufnahme der Aktionen in die `portal_actions`. Um die Ansichten im klassischen UI nicht zu stören, wäre ein separate actions category sinnvoll, da dies keine Auswirkungen für das bestehende UI hat, da diese gar nicht erst geprüft und auch nicht gerendert werden.

Mögliche Alternative: Endpoint überschreiben.

An den bestehenden Konditionen sollen keine Änderungen gemacht werden.

**Comment by njohner** [comment]
I started on this issue, current state can be found here: https://github.com/4teamwork/opengever.core/tree/nj_actions

* I made a new actions category `file_actions`
* The new actions are all stored in this category.
* The idea is to group all the logic for the availability of document actions in a single class `FileActionAvailabilityChecker`. Most of the logic was available in `ActionButtonRendererMixin` and is being moved into the new class to clearly split up availability from rendering.

Some general remarks:
* The `actions` endpoint does not return the `url` of the action, which is kind of stupid. This means that actions that have an `id` that is different from their `url`, cannot be used as returned by the `actions` endpoint
* We have several actions that cannot be called simply with an url. For those at least, the frontend will have to know what to do when the action is available
* In the current frontend, we display different titles for the checkout actions depending on whether the document is already checked out. This could be handled by registering a different action for each case. I think that would be a bit overkill, but I might be wrong.

**Comment by deiferni** [comment]
the permutation matrix is unexpectedly high and there is some duplication in the bumblebee overlays which needs to go, will finish this on friday 😓.

**Comment by deiferni** [comment]
The tasks implemented with this issue should be ready for code review with the PR in https://github.com/4teamwork/opengever.core/pull/5847. Once it is merged it would be good to ping @all4manu as he is currently developing functionality that would need the actions.

**Comment by all4manu** [comment]
A get request to the actions endpoint on the plone site root fails with to following error:

```
{
  "message": "((<PloneSite at /fd>, <HTTPRequest, URL=http://localhost:8080/fd/@actions>), <InterfaceClass opengever.document.interfaces.IFileActions>, u'')",
  "traceback": [
    "File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/Publish.py\", line 138, in publish",
    "    request, bind=1)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/mapply.py\", line 77, in mapply",
    "    if debug is not None: return debug(object,args,context)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/ZPublisher/Publish.py\", line 48, in call_object",
    "    result=apply(object,args) # Type s<cr> to step into published object.",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.rest-1.2.0-py2.7.egg/plone/rest/service.py\", line 23, in __call__",
    "    return self.render()",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-4.3.0-py2.7.egg/plone/restapi/services/__init__.py\", line 21, in render",
    "    content = self.reply()",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-4.3.0-py2.7.egg/plone/restapi/services/actions/get.py\", line 58, in reply",
    "    return actions(expand=True)[\"actions\"]",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.restapi-4.3.0-py2.7.egg/plone/restapi/services/actions/get.py\", line 33, in __call__",
    "    actions = context_state.actions(category=category)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.memoize-1.1.2-py2.7.egg/plone/memoize/view.py\", line 47, in memogetter",
    "    value = cache[key] = func(*args, **kwargs)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/plone.app.layout-2.3.18-py2.7.egg/plone/app/layout/globals/context.py\", line 237, in actions",
    "    max=max,",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Products.CMFPlone-4.3.18-py2.7.egg/Products/CMFPlone/ActionsTool.py\", line 80, in listActionInfos",
    "    if check_condition and not ai['available']:",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/ActionInformation.py\", line 206, in __getitem__",
    "    value = self.data[key] = value(self._ec)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/Expression.py\", line 47, in __call__",
    "    res = compiled(econtext)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/zope.tales-3.5.3-py2.7.egg/zope/tales/expressions.py\", line 217, in __call__",
    "    return self._eval(econtext)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/Products/PageTemplates/Expressions.py\", line 155, in _eval",
    "    return render(ob, econtext.vars)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/Zope2-2.13.28-py2.7.egg/Products/PageTemplates/Expressions.py\", line 117, in render",
    "    ob = ob()",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/opengever.core/opengever/document/browser/actionbuttons.py\", line 34, in is_oc_direct_checkout_action_available",
    "    return self.ifileactions.is_oc_direct_checkout_action_available()",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/opengever.core/opengever/document/browser/actionbuttons.py\", line 22, in ifileactions",
    "    return getMultiAdapter((self.context, self.request), IFileActions)",
    "",
    "  File \"/Users/all4manu/Coding/4teamwork/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py\", line 109, in getMultiAdapter",
    "    raise ComponentLookupError(objects, interface, name)"
  ],
  "type": "ComponentLookupError"
}
```
