### ISSUE TITLE
teamraum ToDo: Responsible field

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5794]
Harvest: `[3.2.2.5 / 27] Projekt - OGIP 34 ToDo's` - `Entwicklung`

Es dürfen nur noch Benutzer zur Auswahl stehen, die dem Workspace zugeordnet sind.

Harvest: https://4teamwork.harvestapp.com/projects/16507031

Todo:
- Statt des Plone-Users Vocabularies soll die QuerySource für das `responsible` Feld verwendet werden
- Dazu muss im hartcodierten Mapping von Vocabularies für Felder das Feld `responsible` angepasst werden, so dass der entsprechende `@querysources` endpoint verwendet wird
- Dieser muss so verwendet werden, dass der Suchbegriff des Benutzers als `?query=` parameter an diesen Endpoint übergeben wird

Doku: https://plonerestapi.readthedocs.io/en/latest/vocabularies.html#querying-a-query-source

Elio - 02.10.2019
⚠️ #5811 Implementiert die Abfrage durch query-sources. Leider wurde dabei nicht beachtet, dass die Abfrage auch mit nicht existierenden Typen funktionieren muss, z.B. beim Hinzufügen von Inhalten. Diese Problematik wurde am 02.10.2019 im Daily besprochen, leider fehlten Schlüsselpersonen um das weitere Vorgehen bestimmen zu können. Deshalb muss das Ticket am nächsten Daily erneut aufgegriffen werden, wenn wenn @lukasgraf und @phgross Anwesend sind.

**Comment by phgross** [comment]
Need #5811

**Comment by phgross** [comment]
Ich bin davon ausgegangen, dass die Backend Arbeiten nun abgeschlossen seien und nur noch Frontend Arbeiten notwendig sind. Dem scheint nicht so. Ich tendiere deshalb dazu diese PBI aus dem Sprint zu entfernen. Kann jemand ein separaten Issue für die Backend Arbeiten erstellen?

**Comment by phgross** [comment]
Fachliches Review 👍
