### ISSUE TITLE
teamraum ToDo list enhancements

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5795]
- I would like to see how many open and closed ToDo's are there per list.
- I would like to filter ToDo's:
  - open / closed
  - My ToDo's
  - Over due ToDo's
  - My over due ToDo's
  - ToDo's by responsible 

Folgende Anpassungen:
- bei Progressbar Tooltip mit konkreter Anzahl ToDos 

Harvest: https://4teamwork.harvestapp.com/projects/16507031

**Comment by njohner** [comment]
See design from Florin for filters that should be available.
