### ISSUE TITLE
Test against a real Solr instance

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5797]
Right now, we're using mock tests and don't have any confidence that things that use Solr actually do work. For example, just recently copy & paste of dossiers got broken in master (see #5765) without any tests failing.

Using an actual Solr instance during tests involves a couple things:
- Including an `ftw.recipe.solr` based part in the test-buildout
- Configuring the Solr-Instance built by that part in a way that is both suitable for
  - Running tests locally
  - Running tests on Jenkins (e.g. pick a port provided by the PortAllocatorPlugin)
- Create a _launcher_ that is able to launch, observe and stop Solr in a robust and graceful way
- Include the appropriate ZCML configuration in tests to set up a connection to that Solr
- Include the `collective.indexing` patch during GEVER's tests, so that Solr actually gets invoked when reindexing. This will probably involve patching `c.indexing` so that it doesn't defer reinexing until the end of the transaction, but instead always does so immediately.
- Isolate the Solr Database contents between tests. For that, it should be possible to use [Solr's snapshot / replication / backup APIs](https://lucene.apache.org/solr/guide/7_6/making-and-restoring-backups.html)

Also see #4844 for some related discussions (though quite a few unrelated ones, hence the new issue).

**Time Box : 1 PT**

**Comment by phgross** [comment]
Wait until #5828 has been resolved.

**Comment by phgross** [comment]
outdated.
