### ISSUE TITLE
API Support für Anträge

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5799]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

- GET eines Antrags (bereits teilweise unterstützt)
- POST eines Antrags (teilweise unterstütz aber wohl noch fehlende Metadaten)
- PATCH eines Antrags

Als API Benutzer will ich die Details von Anträgen fetchen und auch neue Anträge erstellen. 

Diskussion:
 - [x] Alle Proposal Felder in Plone Schema implementieren inkl. Datenmigration 
 - [x] Eventhandler für Aktualisierung der SQL Daten
 - [x] Workflow-Status Änderungen
 - [x] Display workflow transition button discreet placeholders for submit/cancel when:
    - proposal contains checked out documents (submit/cancel)
    - proposal committee is inactive (submit)
- [x] (@njohner) custom proposal API `POST` that takes additional form data so that proposals can be created like from web-rendered form. must also create proposal document when proposal is created.
- [x] (@deiferni) make sure to trigger proposal state changes remotely. Makes states via api visible. Do the following:
  - create a view to trigger the state change, that also creates a history entry
  - no longer sync history via `@@receive-proposal-history`
  - affects:
    - `ProposalRemovedFromSchedule` (synced @@receive-proposal-history), triggers `proposal-transition-unschedule`
    - `ProposalScheduled` (synced @@receive-proposal-history), triggers `proposal-transition-schedule`
    - `ProposalDecided` (synced @@receive-proposal-history, during model.Proposal.decide), triggers `proposal-transition-decide`
     -  `ProposalRejected`
  - ~~render proposal state on overview, not model state.~~

Don't forget to:
- [x] drop `Proposal.is_editable_in_dossier`
- ~~[ ] maybe add abstract base for `ProposalTransitionController` and `TaskTransitionController`~~
- [x] drop ModelProxyTabbedView for proposals 
- ~~[ ] potentially get rid of `Proposal.WORKFLOW_STATE_TO_SQL_STATE`~~
- [x] get rid of sql proposal transition forms, or explicitly use for submitted proposal
- [x] drop `ProposalModel.is_submitted`
- [x] show warning for inactive committees on proposal overview
```python
        if not model.committee.is_active():
            api.portal.show_message(
                _(u'msg_inactive_committee_selected',
                  default=u'The selected committeee has been deactivated, the'
                  ' proposal could not been submitted.'),
                request=getRequest(), type='error')
```

**Comment by phgross** [comment]
Stand ist für das Team unklar: Wir besprechen und splitten ihn in einem Daily weiter auf.

**Comment by deiferni** [comment]
split, created the following additional issues:
- https://github.com/4teamwork/opengever.core/issues/5934
- https://github.com/4teamwork/opengever.core/issues/5935
- https://github.com/4teamwork/opengever.core/issues/5936
