### ISSUE TITLE
Solr Testing - Step 1

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5801]
_Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

- [x] collective.indexing aktivieren bei GEVER Tests
- [x] Review TestServer Solr PR vom RIS/Jones
- [x] Koordinieren der ExtractHandler Korrektur (https://github.com/4teamwork/ftw.solr/issues/137)
- [x] https://github.com/4teamwork/ftw.solr/issues/136 updaten und umsetzen.
- [x] PR von Jones überarbeiten (bumblebee-workaround entfernen) und mergen.

**Comment by lukasgraf** [comment]
Den branch von Jones einfach nur auf den `master` zu rebasen und den Bumblebee-Checksum-Workaround rauszuwerfen scheint nicht zu reichen. Ich habe dies auf meinem [jone-testserver-solr-hijacked-by-lg](https://github.com/4teamwork/opengever.core/tree/jone-testserver-solr-hijacked-by-lg) branch versucht, aber es scheitert eine Assertion, welche nach Inhalt im Solr sucht der nicht da ist: https://ci.4teamwork.ch/builds/265382/tasks/433112

Auf dem entsprechenden Inhalt über den laufenden Testserver manuell `@@solr-maintenance/reindex` aufzurufen führt aber dazu, dass der Inhalt korrekt indexiert wird, und nachher auch auffindbar ist. Meine erste Vermutung ist also, dass es sich um ein zeitliches / Reihenfolge-Problem handelt.
