### ISSUE TITLE
Unterstützen von Sources via API

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5811]
Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`

### Use Case 
Im neuen Frontend müssen wir für die Add und Edit Formularen von Dossiers, Aufgaben etc. die möglichen Werte für Felder wie responsible oder issuer abfragen und validieren können.

### Erklärung/Beschreibung
Aktuell bietet die plone.restapi keine Unterstützung für Sources. Wir verwenden aktuell aber bei diversen Felder Sources anstatt vocabularies. So returned der types endpoint für das Responsible Feld des Dossiers nur folgende Informationen:
``` json
        "responsible": {
            "choices": [],
            "description": "",
            "enum": [],
            "enumNames": [],
            "title": "Federführend",
            "type": "string",
            "widgetOptions": {
                "async": true
            }
        }
```

Source müssten ähnliche behandelt werden wie Vocabularies. Vocabularies werden von der restapi unterstützt und bieten zudem eine Filter Funktionalität, ähnliches müsste auch für sources zur Verfügung stehen.

Todos:
 - [x] Analyse (Unterschiede zum Vocabulary, wieso funktioniert es zurzeit nicht, Vorschlag wie könnte man es in der REST API platzieren)
 - [ ] "plone.restapi Team" Vorschlag unterbreiten bzw. Diskussion lancieren
 - [ ] Folge Issue für Umsetzung erstellen

### Diskussion Planning
 - [ ] types endpoint anpassen
 - [ ] zwei weitere Endpoints (`@sources`, `@querysource`) implementieren
 - [ ] plone.restapi PR
 - [ ] Doku
 - [ ] Im opengever.core sicherstellen, das __iter__ in jedem Fall eine leere Liste returned

**Comment by lukasgraf** [comment]
### Analyse

#### Ausgangslage in GEVER

Es stellt sich heraus dass der `@types` endpoint in `plone.restapi` [durchaus sources unterstützt](https://github.com/plone/plone.restapi/blob/6b459cacfc92f15f52a47e3dee373166b4b0df1c/src/plone/restapi/types/adapters.py#L259-L263). Es ist bloss so, dass die OGDS sources in GEVER welche von `BaseQuerySoure` erben keine sinnvolle implementierung von `__iter__()` haben:

```python

>>> source
<opengever.ogds.base.sources.AssignedUsersSource object at 0x11896ea90>
>>> 
>>> print list(source)
[]
>>> 
>>> source.search('lukas')
[<zope.schema.vocabulary.SimpleTerm object at 0x118d508d0>]
>>> 
>>> print list(source)
[<zope.schema.vocabulary.SimpleTerm object at 0x118d508d0>]
```

Die Implementierung [delegiert nach `self.terms.__iter__()`](https://github.com/4teamwork/opengever.core/blob/c3549abac7b8a6ccca13778125e9dfa6a9350ec8/opengever/ogds/base/sources.py#L50-L51) der source. `self.terms` ist aber keine wirkliche Reflektion der darunterliegenden terms, sondern nur eine temporäre Liste von terms in welche die `search()` schreibt. Der Inhalt ist daher völlig willkürlich, und hat soweit ich sehen kann auch keinerlei Beziehung zu den Implementierungen von `getTerm[byToken] - diese fetchen die entsprechenden Terms jeweils direkt.

Dementsprechend kann `BaseQuerySoure.__iter__()` eigentlich auch nirgends verwendet worden sein wo es eine Rolle spielt - dies hätte so gar nie richtig funktioniert.


Der Hintergrund dafür, dass das so implementiert wurde, ist vermutlich dass man verhindern wollte, dass ein call von `__iter__()` die u.U. riesige Liste von OGDS Usern zurückgibt.

#### Ausgangslage source / vocabulary interfaces

Um zu verhindern dass das vollständige Auflisten der source terms *nötig* ist, wurde [mit der `BaseQuerySoure`](https://github.com/4teamwork/opengever.core/blob/c3549abac7b8a6ccca13778125e9dfa6a9350ec8/opengever/ogds/base/sources.py#L33) das [`IQuerySource` Interface von `z3.formwidget.query`](https://github.com/zopefoundation/z3c.formwidget.query/blob/adfff5d5ae524597df51c50f1db2f05b3cf1797b/src/z3c/formwidget/query/interfaces.py#L4-L9) implementiert:


```python
@implementer(IQuerySource)
class BaseQuerySoure(object):
```

Dieses Interface ergänzt `IVocabularyTokenized` um eine `search()` Methode, welche die source durchsuchbar macht:


```python
class IQuerySource(IVocabularyTokenized):
    """A source that supports searching
    """

    def search(query_string):
        """Return values that match query."""
```

Weil aber [`IVocabularyTokenized`](https://github.com/zopefoundation/zope.schema/blob/144e300ced249185fa0eca42a9b7a598d13a9420/src/zope/schema/interfaces.py#L993-L1005) von [`IVocabulary`](https://github.com/zopefoundation/zope.schema/blob/144e300ced249185fa0eca42a9b7a598d13a9420/src/zope/schema/interfaces.py#L989-L990) erbt, und dieses wiederum von [`IIterableVocabulary`](https://github.com/zopefoundation/zope.schema/blob/144e300ced249185fa0eca42a9b7a598d13a9420/src/zope/schema/interfaces.py#L975-L986), muss eine `IQuerySource` streng genommen immer noch `__iter__()` implementieren, und alle terms der source auflisten können.

Eine `IQuerySource` kann also *zusätzlich* noch durchsucht werden, das Interface drückt aber nicht aus dass dies eine Source sein soll welche *nur* durchsucht werden kann (also nicht enumerierbar ist). Ein Interface welches dies ausdrückt gibt es in Plone nicht, soviel ich sehen kann.

In der Praxis könnte man `IQuerySource` aber wahrscheinlich so interpretieren, oder zumindest davon ausgehen, dass dieses Interface sehr stark signalisiert, dass es nicht sinnvoll ist die terms dieser Source aufzulisten, und dass `search()` die zu bevorzugende Methode ist, mit dieser Source zu interagieren.

#### Addressierung von Sources vs. Vocabularies

Vocabulary factories in Plone sind named utilities. Sources hingegen sind unnamed. Dies können also nicht über einen eindeutigen globalen Namen addressiert werden. Stattdessen müssen sources immer über ein konkretes Field addressiert werden. Siehe dazu auch der letzte Punkt (4) von [David Glick's Kommentar](https://github.com/plone/plone.restapi/issues/535#issuecomment-399669706).


### Lösungsvorschlag

Mit zwei zwei neuen Endpoints `@querysources` und `@sources` in `plone.restapi` sollten das Problem lösen:

- `<context>/@querysources/<fieldname>?query=...`
  Mit diesem Endpoint kann (auf einem bestimmten Kontext) die Source für das Feld `<fieldname>` durchsucht werden.
  Ein Link auf diesen Endpoint kann in der Response des `@types` endpoints eingebaut werden (als `querysource` property).


- `<context>/@sources/<fieldname>`
  Mit diesem Endpoint können (auf einem bestimmten Kontext) die Terms der Source für das Feld `<fieldname>` enumeriert werden (analog `@vocabularies`).
  Ein Link auf diesen Endpoint kann in der Response des `@types` endpoints eingebaut werden (als `source` property).
  Dieser Link würde aber nur verwendet für allgemeinere Sources, welche keine `IQuerySource` sind.

Diese Änderungen wären soweit keine Breaking Changes.

In einem nächsten Schritt könnte der `@types` endpoint so umgebaut werden, dass er keinerlei Terms mehr inline darstellt, sondern nur noch Links auf die entsprechenden Endpoints zurückgibt (zumindest im Default-Verhalten). Dies wäre dann aber ein Breaking change, und müsste entsprechend koordiniert werden.

Zusammengefasst würde für `Choice` Felder im vom `@types` endpoint zurückgegebenen Schema also jeweils ein Link auf einen von drei endpoints zurückgegeben werden:

```json
{"querysource": {
          "@id": "http://localhost:55001/plone/folder/@querysources/responsible"
        }
}
```

(Für `IQuerySource`. Endpoint muss mit `?query=...` aufgerufen werden und gibt Treffer zurück (batched))

---


```json
{"source": {
          "@id": "http://localhost:55001/plone/folder/@sources/otherfieldname"
        }
}
```
(Für sources die keine `IQuerySource` sind. Endpoint gibt alle Terms zurück (batched))

---

```json
{"vocabulary": {
          "@id": "http://localhost:55001/plone/folder/@vocabularies/plone.app.vocabularies.Users"
        }
}
```
(Für named Vocabularies, wie bisher. Endpoint gibt alle Terms zurück (batched))

---


Sobald im `@types` Endpoint für sources nicht mehr die terms inline enumeriert werden, könnte man aus meiner Sicht das `BaseQuerySoure.__iter__()` in GEVER kurzschliessen (`raise NotImplementedError`). So wäre sichergestellt, dass keine falsche Verwendung der Source mit miserabler Performance möglich ist.

In einem ersten Schritt könnte man einfach nach Sentry loggen, wenn `BaseQuerySoure.__iter__()` von irgend was verwendet wird. Kurzes lokales Testen ergab bei mir, dass das Dossier-Formular etc. alles auch ohne funktioniert - die einzige Verwendung die ich triggern konnte war der `@types` endpoint.

**Comment by phgross** [comment]
@lukasgraf Danke für die Analyse, dein Vorschlag finde icht gut 👍 

Ein Detail bin ich mir noch nicht sicher: Grundsätzlich wäre es ja auch möglich das queryen dem `@sources` Endpoint beizubringen, der Grund für zwei separate Endpoints `@querysources` und `@sources` liegt aber darin zu verhindern, dass man quasi defaultmässig die Terms enumeriert  oder was ist die Idee dahinter?

Würdest du die Anpassungen demnach gleich in der plone.restapi vorschlagen und implementieren?

**Comment by lukasgraf** [comment]
PR in `plone.restapi`: https://github.com/plone/plone.restapi/pull/791
