### ISSUE TITLE
Frontend Arbeiten des Teamraum im bestehenden  UI entfernen.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5815]
Harvest: `Projekt - OGIP 34 ToDo's`- `Entwicklung`

Das teamraum feature im bestehenden UI ist nirgends im Einsatz und Teamraum soll ausschliesslich via API und im neuen UI zur Verfügung stehen. Deshalb sollte die bestehende Frontend Implementierung im bestehenden UI entfernt werden.

**Comment by njohner** [comment]
Might need to move some tests to api tests...

**Comment by BlueSky9443** [comment]
https://4teamwork.atlassian.net/browse/GEVER-51
