### ISSUE TITLE
Dokumentkopie ausgecheckt

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5819]
Ausgangslage: Ein Dokument wurde von einem anderen Benutzer ausgecheckt.
Aktion: Ich kopiere das Dokument und füge es im gleichen Dossier ein.
Erwartet: Ich kann das neue Dokument auschecken.
Erhalten: Das neue Dokument ist auch vom gleichen Benutzer ausgecheckt wie das Original.

### Besprechung Planning 
 - Das Kopieren von ausgecheckten Dokumente soll verhindert werden
 - API soll das kopieren von solchen Dokumente auch nicht möglich sein

**Comment by phgross** [comment]
Geprüft ✅
