### ISSUE TITLE
Notifications endpoint should return actor and actor_label

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5834]
The current notifications endpoint only returns `@id`, `created`, `label`, `link`, `notification_id`, `read`, `summary`, `title`. This list should now be extended by the `actor_id` and the `actor_label` (ohne Organisationseinheit Zusatz)

**Comment by all4manu** [comment]
@lukasgraf, works perfectly in the frontend 👍

**Comment by lukasgraf** [comment]
@all4manu great, thanks for checking! 🎉
