### ISSUE TITLE
DocProperties in allen möglichen Dokumenten verwenden

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#5838]
Immer vermehrt taucht das Bedürfnis auf, alle möglichen DocProperties in Dokumenten, Anträgen und Protokollen zu verwenden. Auf https://docs.onegovgever.ch/admin-manual/docproperties/ ist bereits eine umfassende Liste der zV stehenden DocProperties. Diese können jedoch nicht im gewünschten Umfang verwendet werden. 

Hugo Rocha hat den Vorschlag gemacht, alle zV stehenden DocProperties besser zugänglich zu machen (für onsight und saas Kunden). Es macht wohl Sinn, alle zur Verfügung stehenden Felder im ldaptain zu befüllen und diese auch den Saas-Kunden zugänglich zu machen. Dies bedingt eine technische Erweiterung und bei den bestehenden Saas-Kunden eine kleine Migration, sofern diese Erweiterung erwünscht ist. 

In diesem Zusammenhang darf der Bezug zur möglichen Erweiterung des Kontaktmoduls nicht ganz ausser Acht gelassen werden.

**Comment by phgross** [comment]
@Suweber falls dieses Bedürfnis nach wie vor besteht, bitte JIRA Story erstellen und Erich zuweisen.
