### ISSUE TITLE
Get rid of non-api office connector features.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5848]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

We currently support non-api office connector features:
- non api based checkout and edit
- non api based upload

We have discussed that we would like to get rid of these features and make office connector via api the one and only default. Getting rid of that would mean to:
- Get rid of logic and different code paths for api and zem
- Possibly also adapt OfficeConnector and remove logic there
- Get rid of registry flags and adapt https://gever.4teamwork.ch/vorlagen/opengever-dossier-templatefolder/document-22875#overview

❗️ The estimate only refers to the `opengever.core` side - OfficeConnector changes will need to be initiated/tracked by the person doing this, but are not part of the estimate.

**Comment by njohner** [comment]
I don't see what to adapt in https://gever.4teamwork.ch/vorlagen/opengever-dossier-templatefolder/document-22875, the `api_enabled` flag is not mentioned is the checklist.

**Comment by njohner** [comment]
Created issue in OfficeConnector: https://github.com/4teamwork/OfficeConnector/issues/336

**Comment by njohner** [comment]
This is done, but we wait to make sure all clients have the new version of OC installed

**Comment by phgross** [comment]
Fachliches review 👍
