### ISSUE TITLE
User Fullnames in Listing- and Users Endpoints do not match

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#5857]
Maybe this is only a "Sturm im Wasserglas" and happens only on my machine. So far I couldn't reproduce this on lab.onegovgever.ch.

#### Steps to reproduce
1. Call `@listing?name=dossiers&ts=1561700261077&b_start=0&b_size=20&sort_order=ascending&search=&columns:list=responsible_fullname&facets:list=responsible_fullname`

2. Call `http://localhost:8080/fd/@users/carmen.albrecht` or `http://localhost:8080/fd/@users/philippe.gross`

#### Expected result
The names should match, i.e. both endpoints should return `Albrecht Carmen` or `Gross Philippe` respectively.

#### Actual result

| Users endpoint | Listing endpoint
| --- | ---
| `"fullname": "Carmen Albrecht"` | `"responsible_fullname": "Albrecht Carmen"`
| `"fullname": "Abeggle Philippe"` | `"responsible_fullname": "Gross Philippe"`

**Comment by phgross** [comment]
@all4manu ich kann diesen Issue sowohl auf dev.onegovgever.ch wie auch lokal nicht reproduzieren.
