### ISSUE TITLE
Link auf erweiterte Suche: Fehlerhaft wenn Suchfeld Umlaute enthält

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5859]
Reproduzieren:
 1. LiveSearch `Müller` eintippen
 2. Enter
 3. Auf Link erweiterte Suche
=> IE zeigt 400 Bad Request Seite. Fehler tritt nur im IE auf.

![Bildschirmfoto 2019-08-09 um 15 50 20](https://user-images.githubusercontent.com/485755/62783788-6eae1b00-babd-11e9-85c0-c1e5d7a877bd.png)

https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20437

**Comment by njohner** [comment]
Deployed on dev
