### ISSUE TITLE
Erinnerungen bei Weiterleitungen führt zu Fehler

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5862]
Zurzeit erlaubt mir GEVER bei Weiterleitungen eine Erinnerung zu definieren, führt aber im Backend zu einem Fehler.

Da in GEVER aber Weiterleitungen aber keine Frist kennen, macht das Setzten einer Erinnerung keinen Sinn und sollte verhindert werden.

**Comment by deiferni** [comment]
outdated.
