### ISSUE TITLE
path_depth Upgradestep dupliziert Einträge im Solr

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5863]
Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`

Das Update auf den `2019.4.0rc1` beinhaltet ein Problem, was dazu führt, das der Solr für alle Objekte doppelte Einträge führt. Das Problem ist einfach in der LiveSearch oder der Suceh ersichtlich.

Ich konnte die Probleme mit einem Update von `2019.3.0` auf `2019.4.0rc1` reproduzieren. Nach dem Ausführen von `IndexPathDepthInSolrForAllObjects` (https://github.com/4teamwork/opengever.core/blob/master/opengever/core/upgrades/20190625184855_index_path_depth_in_solr_for_all_objects/upgrade.py) tritt der Fehler auf.

Todos Sprint 6: 
 - [x] Solr version down pinnen
 - [x] 4tw gever clear/rebuild

**Comment by deiferni** [comment]
we strongly suspect that solr versions are incompatible and that we need to reindex. @buchi has more info and steps to reproduce.

**Comment by buchi** [comment]
Der Fehler tritt generell auf, wenn von Solr 7.x auf Solr 8.x aktualisiert wird. Jegliches Reindizieren von vorhandenen Dokumenten führt zu Duplikaten.

Das Problem kann wie folgt reproduziert werden:

```shell
docker volume create solr
docker run --name solr772 -d -p 8983:8983 -v solr:/opt/solr/server/solr solr:7.7.2
docker exec -it --user=solr solr772 bin/solr create_core -c gettingstarted

# Add document with id "1"
curl 'http://localhost:8983/solr/gettingstarted/update?_=1566284153424&commitWithin=1000&overwrite=true&wt=json' \
  -H 'Content-type: application/json' \
  --data-binary '{"add": {"doc": {"id": "1", "title_s": "Foo"}}}'

# Search returns one item
curl 'http://localhost:8983/solr/gettingstarted/select?q=*:*'

docker stop solr772
docker run --name solr820 -d -p 8983:8983 -v solr:/var/solr/data -t solr:8.2.0

# Update document with id "1"
curl 'http://localhost:8983/solr/gettingstarted/update?_=1566284153424&commitWithin=1000&overwrite=true&wt=json' \
  -H 'Content-type: application/json' \
  --data-binary '{"add": {"doc": {"id": "1", "title_s": "Bar"}}}'

# Search returns two items
curl 'http://localhost:8983/solr/gettingstarted/select?q=*:*'
```

**Comment by buchi** [comment]
Gemäss Solr Doku sollte nach einem Major-Update immer komplett reindiziert werden.

https://lucene.apache.org/solr/guide/8_1/reindexing.html#reindexing-strategies

"If you have not changed your schema as part of an upgrade from one minor release to another (such as, from 7.x to a later 7.x release), you can often skip reindexing your documents. However, when upgrading to a major release, you should plan to reindex your documents because of the likelihood of changes that break back-compatibility."

**Comment by phgross** [comment]
@deiferni Falls sowieso ein kompletter Reindex durchgeführt wird, wäre evtl. die Korrektur von #5831 sinnvoll.

**Comment by buchi** [comment]
Es gibt zwei Möglichkeiten:
	- Clear and Rebuild über GEVER
	- Replikation von Solr zu Solr

Clear and Rebuild:
	- Einfacher und automatisierbar
	- Je nach Grösse dauert es sehr lange
	- Konsole Skript für "Clear and Rebuild"
	- Evtl. mit Backup über REST API

Solr Data Import:
	- Zweite Solr Instanz nötig

Upgrades sollten nicht zeitgleich mit GEVER Releases eingespielt werden
Standardmässig Clear and Rebuild, ausser bei sehr grossen Mandanten (HBA, KAPO)

Solr Data Import Konfiguration:

Request Handler:
```xml
  <requestHandler name="/dataimport" class="solr.DataImportHandler">
    <lst name="defaults">
      <str name="config">solr-data-config.xml</str>
    </lst>
  </requestHandler>
```

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<dataConfig>
  <document>
    <entity name="Solr" processor="SolrEntityProcessor"
            url="http://127.0.0.1:10130/solr/ogg"
            query="*:*"
            fl="*,ignored_version_:_version_,ignored_path_parent:path_parent,ignored_sequence_number_string:sequence_number_string"
            sort="UID asc"/>
  </document>
</dataConfig>
```

Vorgehen:
Gever.4teamwork.ch auf aktuellste Solr Version (z.Z. 8.2.0) upgraden
SaaS-Kunden
On-Premise von nächstem Release

**Comment by deiferni** [comment]
See https://github.com/4teamwork/ftw.solr/issues/140 for a first step

**Comment by lukasgraf** [comment]
@deiferni PR that implements console scripts for Solr maintenance (4teamwork/ftw.solr#140) has been merged (not released yet though).

**Comment by deiferni** [comment]
Weiteres Vorgehen mit @combine-space besprochen, Ticket im Sysadmin-Tracker https://extranet.4teamwork.ch/betrieb/tracker/901.

Weiteres Vorgehen hier mit @phgross besprochen:
- Wir bleiben bis 2019.4 bei Solr 7.x
- Wir belassen 4tw gever auf Solr 8.x, Clear-and-Rebuild wurde schon gemacht

**Comment by deiferni** [comment]
I have hit a wall upgrading our RED system with https://github.com/4teamwork/opengever.core/issues/5957. Could not fix it today, more tomorrow.

**Comment by deiferni** [comment]
all done here, see https://github.com/4teamwork/opengever.ftw/issues/93.
