### ISSUE TITLE
Quartalsbericht: Exportierte Excel Sheets um Antwortzeiten ergänzen

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5869]
Die zum Zweck der Quartalsberichts exportierten Excel-Sheets enthalten zur Zeit nur Statistiken über die Inhalte.

Diese sollen ergänzt werden um Statistiken zu den Antwortzeiten (pro Mandant, pro Monat).

(Es geht hier um den Export von Rohdaten - nicht Grafiken!)

Da die Daten als Zeitserie vorliegen und daher aggregiert werden müssen, muss definiert werden welche Statistischen Aggregate pro Bucket (Monat) gewünscht sind: z.B. Durchschnitt, Median, Max, Min, 95. Perzentil.

Philipp klärt dies noch ab.

**Comment by phgross** [comment]
Pro:
> Aktuell wird er nicht mehr benötigt.
