### ISSUE TITLE
MockTestCase aktualisieren / entfernen

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5883]
Damit auf `ftw.testing` 2.0 (noch nicht released) aktualisiert werden kann, müssen die MockTestCase-basierten Tests geprüft oder entfernt werden.
Dies ist beschrieben im Upgrade Guide: https://github.com/4teamwork/ftw.testing#upgrading-from-ftw-testing-1-x-to-2-0

Solange `ftw.testing` in GEVER nicht aktualisiert wird besteht kein Handlungsbedarf 😉

Siehe: https://github.com/4teamwork/ftw.testing/pull/40

**Comment by phgross** [comment]
ROAD-1438
