### ISSUE TITLE
Builder: "changed" setzen

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#5884]
Damit wir in RIS von ["modified" auf "changed" umstellen können](https://github.com/4teamwork/ris/issues/1630), müssen wir in der [RIS GEVER-Fixture](https://github.com/4teamwork/ris/blob/master/gever/fixture.py) anstatt des modified-dates das changed-date beim Erstellen von Inhalten vorbestimmen können. 

Dies funktioniert aber nicht.
```python
bin/instance debug
>>> from zope.component.hooks import setSite
>>> from ftw.builder import Builder, create
>>> from datetime import datetime
>>> setSite(app.platform)
>>> session.current_session = session.factory()
>>> doc = create(Builder('document').having(changed=datetime(2000, 1, 1)))
>>> doc.changed
datetime.datetime(2019, 8, 23, 13, 56, 44, 950327, tzinfo=<UTC>)
```

Ich hätte erwartet das `changed` am Schluss 1.1.2000 ist, es ist aber "heute".

**Comment by njohner** [comment]
Yes changed gets set during object creation. We would need to handle this specifically. Or you could simply freeze before creating, which is what we do to have the correct modification and changed dates
