### ISSUE TITLE
Docxcompose: also update docproperties in header and footer.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5894]
https://extranet.4teamwork.ch/support/kath.-konfessionsteil-st.gallen/tracker/24

Tracking issue for https://github.com/4teamwork/docxcompose/issues/36.

Requested by @andresoberhaensli.

**Comment by deiferni** [comment]
@phgross ist auf dev und zur abnahme bereit

**Comment by phgross** [comment]
Review: funktioniert soweit gut 👍
