### ISSUE TITLE
Also provide doc-property for creator.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5895]
Currently only `document_author` is available as docproperty. We should also provide docproperties for the creator. Also, we should provide the same docproperties for the creator user as we already do for the current user:

- ogg.document.creator.userid
- ogg.document.creator.title
- ogg.document.creator.firstname
- ogg.document.creator.lastname
- ogg.document.creator.department
- ogg.document.creator.department_abbr
- ogg.document.creator.directorate
- ogg.document.creator.directorate_abbr
- ogg.document.creator.email
- ogg.document.creator.email2
- ogg.document.creator.url
- ogg.document.creator.phone_office
- ogg.document.creator.phone_fax
- ogg.document.creator.phone_mobile
- ogg.document.creator.salutation
- ogg.document.creator.description
- ogg.document.creator.address1
- ogg.document.creator.address2
- ogg.document.creator.zip_code
- ogg.document.creator.city
- ogg.document.creator.country

Requested by @andresoberhaensli.

**Comment by andresoberhaensli** [comment]
So long as we're pulling the document creator's name, we might as well include a maximum of their other properties listed on https://docs.onegovgever.ch/admin-manual/docproperties/list/#doc-properties-aktueller-benutzer. 

There are numerous scenarios when using templates and SPV in GEVER where this information would be crucial to have.

**Comment by phgross** [comment]
Fachliches Review 👍 

@andresoberhaensli FYI: Properties werden im nächsten Release zur Verfügung stehen.
