### ISSUE TITLE
Darstellungs-Fehler: Überschneidung durch drunterliegendes Grafikelement

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#5898]
- Die Grafiküberschneidung triff auf, sobald das Tooltip aufgerufen wird (s.GIF).

- Dieses Verhalten konnte ebenfalls auf unserem Testsystem (DEV) reproduziert werden -> https://dev.onegovgever.ch/[…]/dossier-563#documents-proxy

Extranet-Ticket -> https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/822

![überschneidung_bei_tooltip](https://user-images.githubusercontent.com/11310148/63843309-7a875180-c986-11e9-9d2f-ce23a46ff76f.gif)

**Comment by phgross** [comment]
Fachliches Review:
- Wird eine Zeile selektiert dargestellt, so bleibt die Markierung bestehen und ist anschliessend über den Menüs. 

![Bildschirmfoto 2019-12-02 um 07 49 17](https://user-images.githubusercontent.com/485755/69936558-69dffd80-14d8-11ea-9041-84d2dc3147c1.png)
