### ISSUE TITLE
Listing endpoint überarbeiten und catalog Support entfernen.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5901]
Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`

Follow up aus vergangenen sprint plannings: der listing endpoint benötigt refactoring.

Zu dem kann der catalog Support entfernen werden., der Listing Endpoint muss neu nur noch für Deployments mit aktiviertem Solr funktionieren

Todos

- [ ] Refactoring
- [x] Remove catalog implementation

**Comment by njohner** [comment]
For refactoring part, after quick discussion with @lukasgraf I'd propose
- use `namedtuple`s for the items in `FIELDS` or maybe drop `FIELDS` altogether and write this in a more object-oriented way. This would allow to group the methods used for certain fields together, like translations, dealing with dates, and so on...
- Maybe only keep the mapping in `FIELDS` when it is non-standard?
- extract some of the functionality to methods and add docstrings.

**Comment by njohner** [comment]
Done, but wait to test with new solr tests.
