### ISSUE TITLE
Missing metadata/properties in REST API GET of document

### ISSUE THREAD

**Issue by buchi** [4teamwork/opengever.core#5905]
Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`

The following metadata or properties are needed by the frontend and should be returned by the REST API GET endpoint for documents:
- `checked_out`
- `is_locked`
- `containing_dossier`
~- `containing_subdossier`~
- `dossier_review_state`
- `trashed`
- `is_shadow_document`
- `get_current_version_id` ->  `current_version`

Used for the document detail view.

Notes:
- Consider whether we should namespace these properties (additional properties which are not DX fields)

**Comment by phgross** [comment]
Fachliches Review: 👍
