### ISSUE TITLE
Can't D&D upload certain documents, docproperty update fails.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5906]
- Drag-Drop the attached document into a dossier 
[broken.docx](https://github.com/4teamwork/opengever.core/files/3569843/broken.docx)
- Comment out https://github.com/collective/collective.quickupload/blob/master/collective/quickupload/browser/quick_upload.py#L754-L757 to have a local traceback
- ```
  Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module opengever.base.quickupload, line 63, in quick_upload_file
  Module collective.quickupload.browser.quick_upload, line 769, in quick_upload_file
  Module opengever.base.quickupload, line 89, in __call__
  Module opengever.base.command, line 23, in execute
  Module opengever.base.monkey.patches.default_values, line 150, in createContentInContainer
  Module plone.dexterity.utils, line 185, in addContentToContainer
  Module Products.BTreeFolder2.BTreeFolder2, line 455, in _setObject
  Module zope.event, line 32, in notify
  Module zope.component.event, line 24, in dispatch
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 588, in subscribers
  Module zope.component.event, line 32, in objectEventNotify
  Module zope.component._api, line 136, in subscribers
  Module zope.component.registry, line 321, in subscribers
  Module zope.interface.adapter, line 588, in subscribers
  Module opengever.document.handlers, line 53, in document_moved_or_added
  Module opengever.document.handlers, line 60, in _update_docproperties
  Module opengever.dossier.docprops, line 70, in update
  Module opengever.dossier.docprops, line 94, in update_doc_properties
  Module opengever.dossier.docprops, line 120, in write_properties
  Module docxcompose.properties, line 232, in update_all
  Module docxcompose.properties, line 387, in update
  Module docxcompose.properties, line 368, in get_runs_for_update
  Module docxcompose.properties, line 349, in separate_run
  IndexError: list index out of range
```

**Comment by njohner** [comment]
Yes we do not handle Complex Fields with missing separate field: https://github.com/4teamwork/docxcompose/blob/master/docxcompose/properties.py#L351-L353
😅

**Comment by deiferni** [comment]
It seems to happen in production, see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/41308/ for example. My failing document is als one from our gever.

**Comment by njohner** [comment]
Documentation says:
* Optionally, a <w:fldChar> element with an attribute fldCharType value of separate, which separates the field fron its field result.

So I think that when we don't have a `separate`, it means we don't have a value, which means we should not update.

**Comment by njohner** [comment]
This was fixed in https://github.com/4teamwork/docxcompose/pull/44 and new version of docxcompose was released.
