### ISSUE TITLE
Add support for multiple apps in GEVER UI

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5908]
Harvest: `[3.2.2.5 / 27] Projekt - OGIP 34 ToDo's` - `Entwicklung`

## Create a concept for multiple apps.

- Write up a conceptual description of an "app" that can be switched. An app has (at least):
  - Title
  - Logo
  - URL-Space
  - Colors
  - Navigation (-customizations)
  ...

## Create implementation of that concept based on the following requirements

- Add teamraum icon (https://gever.4teamwork.ch/ordnungssystem/3/1/2/1/dossier-3104?SearchableText=icons#documents-proxy)
- Replace GEVER with "teamraum" all small letters
- ~Use teamraum color as primary color (ask @phgross), which one it now is.~

<img width="439" alt="Screen Shot 2019-09-03 at 18 55 26" src="https://user-images.githubusercontent.com/437933/64193367-e8e37c80-ce7c-11e9-845f-b9f20aba27c3.png">

- Remove "Kontakte", "Vorlagen", "Eingangskorb" and "Ordnungssystem"
- Add Teamräume (Root folder)
- The navigation shows all teamraums I'm a member off (can at least read).
<img width="304" alt="Screen Shot 2019-09-03 at 18 57 08" src="https://user-images.githubusercontent.com/437933/64193340-dbc68d80-ce7c-11e9-9920-5d5e03b577c6.png">

**Comment by elioschmutz** [comment]
Meeting mit @buchi 

# Allgemein
Eine interne App kann sowohl eine eigenständige App (Teamraum) wie auch eine "Sub-App" (SPV) sein.

## Suche
Die Suche im GEVER soll alle Inhalte innerhalb des aktuellen GEVER's sowie der Sub-Apps zurückgeben. Eine Suche auf einem Dossier findet bei aktivierter SPV also auch Sitzungen. Der Teamraum läuft immer auf eigener Instanz. Diese Inhalte werden somit nicht gefunden.

Eine Sub-App (SPV) läuft immer auf der gleichen Installation wie das Haupt-GEVER. Eine Sub-App ist eine Art Subsite. Folgendes trifft zu Sub-Apps zu:
- eigene Navigation (ohne Ordnungssystem, z.b. mit Gremien...)
- eigenes Icon
- Suche in SPV verwendet GEVER-Suche
- Favoriten über das gesamte GEVER

# Fragen
- Sind GEVER-Mandanten eigene Apps oder ist das GEVER als ganzes mit allen Mandaten eine App?

# Konzept Implementation

## App-Objekt

Das App-Objekt soll mit diesen Attributen dem Frontend zur Verfügung stehen: 

- `title`: Titel (OneGov GEVER)
- `logo_url`: Logo (www.gever.ch/logo.jpg)
- `app_url`: URL (www.gever.ch)
- `main_color`: Hauptfarbe ('ccddaa')
- `group`: Welche Gruppe darf diese App benutzen? (`TeamraumUser`)
- `active`: Ist diese App für den aktuellen Benutzer verfügbar? (Ist er generell berechtigt?) (boolean) - Das Frontend zeigt nicht aktive Apps nicht an.
- `restricted_access`: Definiert, wo diese App verwendet werden kann (`intern`, `extern`) - Anhand vom Attribut `access_from` kann das Frontend entscheiden, was für eine Meldung dargestellt werden soll. Eine eingeschränkte App wird im Frontend dargestellt, kann jedoch nicht asugewählt werden
- `access_from`: Zugriff von extern oder intern? (`extern`, `intern`)
 
## Anpassungen am Portal (@buchi)
- [ ] Applikationen können im Portal erfasst werden (siehe Punkt `App-Objekt`)
- [ ] Portal weiss, welcher Benutzer welche App benutzen darf und setzt die entsprechenden Attribute (`active`, `restricted_access `)
- [ ] Portal setzt `access_from` je nachdem von wo der Benutzer auf das Portal zugreift
- [ ] OGDS nicht mehr anbinden. Die Gruppen sollen direkt über die AD abgefragt werden
- [ ] für öffentliches Portal: Jede Applikation, egal ob intern oder extern soll zurückgegeben werden, jedoch mit Flag, ob die App extern verwendet werden kann oder nicht. Dadurch ist es möglich im Frontend dem Benutzer einen entsprechenden Hinweis anzuzeigen, dass die App zwar verfügbar ist, jedoch nicht von extern verwendet werden darf/kann (siehe Punkt `App-Objekt`)

GEVER:
- [ ] (Buchi) Beim Login gibt das Portal eine Liste mit allen Applikationen und deren Metadaten zurück. Die Apps werden auf dem User-Objekt gespeichert (genauer Speicherort muss noch definiert werden)
- [ ] (Elio) @config-Endpoint liest die Apps vom User-Objekt aus und gibt diese zurück
- [ ] (Elio) Apps müssen für Dev/Test einfach konfigurierbar sein (beim Entwickeln will man nicht mehrere GEVER-Installation und ein Portal aufsetzten um Multi-Apps testen zu können)

GEVER-UI (Elio):
- [ ] erhält vom @config endpoint alle Apps und entscheidet anhand der URL welche App momentan aktiv ist
- [ ] aktuelle App wird im Store gespeichert (wird bereits so gemacht)
- [ ] Umsetzungsvariante: jede App gem. UI-Context erfassen und bestimmte Komponenten (z.B. NavigationDrawer) über das App-Objekt steuern

# Zeitplan

- Backend erst bis ~Mitte Oktober möglich (oder erst für Innovation-Day - 28.10.2019)
- Frontend wäre früher möglich. Statische Konfig für Übergangszeit wäre nötig

**Comment by elioschmutz** [comment]
Zeitplan besprochen mit @phgross per Slack:

- Frontend soll wie geplant in diesem Sprint umgesetzt werden. Als App-Konfiguration wird anstatt des Wertes im @config Endpint eine statische Konfiguration verwendet welche sowohl für das Development wie auch für uilab funktioniert
- das Backend wird später umgesetzt

**Comment by phgross** [comment]
Fachliches Review: 👍
