### ISSUE TITLE
Membership listing 

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5909]
- Don't show name and ID twice. Full-name is enough.
- Don't show the ID at all in no column
- Filter for text (in fullname),  type and role. 

<img width="1332" alt="Screen Shot 2019-09-03 at 19 00 24" src="https://user-images.githubusercontent.com/437933/64193486-1defcf00-ce7d-11e9-992f-c725fef99b6d.png">

Harvest: https://4teamwork.harvestapp.com/projects/20370764

**Comment by njohner** [comment]
filter as for other content:
- facets for type and role
- search for text

Might be two views by then (one for membership and one for members)

**Comment by BlueSky9443** [comment]
Achtung bei gleichlautenden Vor- und Nachnamen. Die Teilnehmerin oder der Teilnehmer müssen in der Übersicht klar identifiziert werden können (Mail oder Benutzername)
