### ISSUE TITLE
Membership: button placement

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5910]
Currently the button is not visible:
<img width="1680" alt="Screen Shot 2019-09-03 at 19 03 08" src="https://user-images.githubusercontent.com/437933/64193667-82ab2980-ce7d-11e9-9c81-e39f8968f442.png">

Maybe this could be a question for Florin, where to place it. IMHO it could be directly after the last row or use the PLUS sign.

Harvest: https://4teamwork.harvestapp.com/projects/20370764

**Comment by njohner** [comment]
Ask Florin for placement

**Comment by deiferni** [comment]
outdated.
