### ISSUE TITLE
External invitations

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5911]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

**See https://github.com/4teamwork/opengever.core/issues/5911#issuecomment-561137361**

- As a teamraum owner I would like to invite another person (unregistered), in order to share some documents with this person. I expect the on boarding happens automatically for new users, which are clicking on the invitation link. 

- As teamraum owner I would like to enter a E-Mail address, to which the invitation goes to.

- A teamraum owner I can't see already registered members, which are not member of the current teamraum

Harvest: https://4teamwork.harvestapp.com/projects/20370764

**Comment by maethu** [comment]
First Use-Case:
- Teamraum and Portal are running in the same zone/place (Ignore all issues regarding firewalls, connection issues, etc.
- Invite external people with the GEVER-UI, which leads to new User on the portal
- On-Boarding incl. Mail / registration happens on the Portal.
- We could use the current invitation implementation form my.teamraum.com or the internal invitations implemented already in gever on the portal.

**Comment by maethu** [comment]
What needs to be implemented on the GEVER side.

UI:
- List current roles on Teamraum + Invitations (from Portal) -> Assume a Endpoint provides the necessary informations:
   - E-Mail address of inviter
   - E-Mail address of the invited person
   - Role of invited person
   - Timestamp of invitation
- Invite new person by email address and role (Portal endpoint)
- Edit role of open invitation (Portal endpoint) and users with local role (GEVER API)
- Remove invitation (Portal endpoint) / User with local role (GEVER API)

**Comment by maethu** [comment]
Abgrenzung zu #6041 :

Die aktuelle Teamraum implementation sieht wie folgt aus:
Beispiel aus https://bve.teamraum.ch/projects/230-10588-sanierung-fahrbahn-zuerichstrasse-bernstrasse-muenchenbuchsee-moosseedorf#participants

<img width="1160" alt="Screen Shot 2019-11-11 at 17 18 34" src="https://user-images.githubusercontent.com/437933/68602826-588e6d00-04a7-11ea-86b1-4848e1cf4ec7.png">

Einladen:
- Beim Einladen von Benutzer können globale Admins (Site Administrator) bestehende Benutzer suchen und einladen.
- Neue, oder bestehende Benutzer per E-Mail Adresse einladen
- Rolle zuweisen
- Kommentar eingeben
<img width="1135" alt="Screen Shot 2019-11-11 at 17 19 17" src="https://user-images.githubusercontent.com/437933/68602963-a5724380-04a7-11ea-86b4-5a4bc2460138.png">

Ähnlich stelle ich mir das auch im Teamraum vor mit dem Unterschied, dass "internes Einladen" nicht sinnvoll ist. Entweder werden dem Benutzer per "Freigabe" die nötigen Rechte erteilt, oder per Einladung mit E-Mail Adresse.
<img width="1135" alt="Screen Shot 2019-11-11 at 17 19 17" src="https://user-images.githubusercontent.com/437933/68603046-d783a580-04a7-11ea-8623-e7a2fbeae69c.png">

**Comment by buchi** [comment]
Eine Einladung wird im Teamraum gespeichert und enthält u.a. folgende Metadaten:
- uid
- recipient (userid)
- recipient_email
- role
- inviter (userid)
- timestamp (created)

Der Recipient (userid) kann unbekannt sein, falls zur E-Mailadresse (`recipient_email`) kein Benutzer gefunden wird.

Der Teamraum versendet eine E-Mail mit Einladungslink z.B. https://teamraum/@@invitations/:uid

Beim Aufruf des Einladungslink sind folgende Fälle möglich:

1. Falls nicht eingeloggt und unbekannte E-Mail -> Redirect auf Registrierungsseite des Portals
    mit den Parameteren E-Mail, Redirect URL, Timestamp, Signatur
    z.B. https://portal/register?email=<email>&redirect_url=<url>&ts=<ts>&sig=<sig>
    Die Form des Registrierungslinks muss mit dem Portal koordiniert werden.
   Siehe auch https://github.com/4teamwork/ianus/issues/2

2. Falls nicht eingeloggt und E-Mail eines bekannten Benutzers -> Login

3. Falls eingeloggt, Einladung mit Benutzer verknüpfen und alle pendenten Einladungen anzeigen
    Alle ausstehenden Einladungen (ohne recipient) mit der gleichen recipient_email mit dem Benutzer verknüpfen.
    Bei Annahme od. Ablehnung einer Einladung -> Einladung löschen

4. Unbekannte, abgelaufene Einladung -> 404

Registrierung beim Portal:
Nach der Registrierung hat der Benutzer eine gültige Session am Portal.
Es erfolgt ein Redirect zurück zum Teamraum auf die Redirect URL.

Redirect URL: z.B. Einladungslink mit Parameter login=1
Bei Aufruf der Redirect URL -> Login (2) -> Einladung mit Benutzer verknüpfen (3) 

Benutzererstellung:
Die Benutzer werden lokal durch das Authentisierungsplugin beim ersten Login erstellt.
Alternativ kann die lokale Benutzererstellung deaktiviert werden.
In diesem Fall werden die Benutzer über ein externes System (LDAP) eingebunden.

**Comment by deiferni** [comment]
Diskussion mit Christoph:
- nur eine aktive Einladung pro E-Mail
- erneut einladen optional

- Zwei separate Auflistungen für Einladungen und Teilnehmer
- Teilnehmer listet alle Principals auf, die Zugriff auf Teamraum haben
- "Zugriff" Tab nur noch für Admins sichtbar

**Comment by njohner** [comment]
What still needs to be done:
- [ ] Add tests for the different cases handled by `my-invitations/accept`
- [ ] Test the different cases with the adapted portal
- [ ] adapt invitation listing (frontend and backend)
- [ ] Rework / remove the `invitation` PATCH endpoint. For now this for example allows to change the `recepient`

**Comment by deiferni** [comment]
adapt listings so that terms are also listed as an object (i.e. `{'token': 'foo', 'title': 'bar'}`) instead of just the flat token/value.

**Comment by all4manu** [comment]
Die Anpassungen hier (=> zwei neue Endpoints für invitations und participations) haben Auswirkungen auf den `@my-workspace-invitations` endpoint. Offenbar wird dieser verwendet um zu prüfen ob der angemeldete User selbst irgendwo eingeladen ist.

Jetzt wird beim Aufruf von diesem Endpoint der folgende Fehler geworfen:

```
{
  "message": "'recipient_email'",
  "type": "KeyError"
}
```

**Comment by deiferni** [comment]
@all4manu das Problem entsteht wegen alten Einladungen und wird durch https://github.com/4teamwork/opengever.core/pull/6134 behoben.

**Comment by deiferni** [comment]
Ersetzt mit
https://github.com/4teamwork/opengever.core/issues/6169
https://github.com/4teamwork/opengever.core/issues/6141
