### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5912]
- As responsible person for the teamraum installation on the customer site, I would like to be able to create and on board new users on my own. 

- As responsible person for the teamraum installation on the customer site, I would like to assign users to existing teamraums. This could be either thru invitation or a different mechanism, which makes sure the user gets the right permissions. 

Harvest: https://4teamwork.harvestapp.com/projects/20370764

**Comment by maethu** [comment]
What we need on the GEVER side for the first implementation:
- A link, which jumps to the portal

**Comment by njohner** [comment]
Over AppSwitcher

**Comment by phgross** [comment]
Wird mit #6041 abgedeckt.
