### ISSUE TITLE
Connect GEVER dossier with a teamraum

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5914]
- As canton employer and GEVER user I would like to share some documents from a GEVER dossier with a external person (not employed by the canton) in a teamraum, in order to work together on those documents.

- Shared documents are checkout and therefore protected from modifications in GEVER.
- After the work in the teamraum is done, I'm able to move those documents back from the teamraum into GEVER.
- As GEVER user I need to see weither a document is shared via teamraum (indicated with a link, or a symbol)

Harvest: https://4teamwork.harvestapp.com/projects/20370764

**Comment by maethu** [comment]
We assume that that GEVER and Teamraum are using the same Portal.

**Comment by jone** [comment]
Wird durch OGIP 63 gelöst.
