### ISSUE TITLE
Deletion policy in teamraum

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5915]
- Documents can be deleted (trashed)
- folders can be deleted (trashed)
- A teamraum can be deleted (trashed) - only by the owner of the teamraum, or a Admin (Responsible person of the application or zopemaster)

Harvest: https://4teamwork.harvestapp.com/projects/20370764

**Comment by njohner** [comment]
As in GEVER:
- Move to trash
- Soft delete if configured to be allowed.
- In GEVER this is only possible for `document`s
- This also has to be allowed for `workspacefolder` (move to trash and soft delete)
- See `ftw.trash` for inspiration on problems with recursive untrashing and such

In separate issue delete teamraum. This is a real trash. Add warning, danger zone, ask to type the name of the teamraum or something to confirm. (estimate 3)

**Comment by deiferni** [comment]
delete has been implemented.
