### ISSUE TITLE
teamraum overview

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#5916]
- As team member I would like to see what happened lately on the overview, in order to know what I have to checkout first.
  - I would like to the see who uploaded or modified which documents recently
  - I would like to see who created or modified ToDo's recently
  - I would like to see who invited and show accepted invitations recently
- As a teamraum owner I would like to set and see the purpose of this teamraum. 

In my optionen we could basically adapt the current dossier overview, with on important change:
- Instead of having "pending tasks", there needs to be a activity stream

Vorerst nur eine Übersicht nur für den Teamraum mit folgenden Elementen:
- Dossier-Metadaten
- Beschreibung
- zuletzt bearbeitete Dokumente

Harvest: https://4teamwork.harvestapp.com/projects/20370764

**Comment by maethu** [comment]
In my optionen we could basically adapt the current dossier overview, with on important change:
- Instead of having "pending tasks", there needs to be a activity stream


Priority 1:
Adapt GEVER Dossier view for Teamraum, but don't show "pending tasks".

Priority 2:
Add activity stream as described in the description of the issue.

**Comment by phgross** [comment]
Fachliches Review 👍
