### ISSUE TITLE
clearup if having get_workspace_user_ids and ManageParticipants.get_participants makes sense

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5918]
We currently have to different ways of getting a very similar information about the users of a workspace:
* `get_workspace_user_ids` (basically checks if that user has any local role with view permissions in the workspace by walking up the acquisition chain from the `context`)
* `ManageParticipants.get_participants` (users with local_roles on the `Workspace`)

`get_workspace_user_ids` is what is used by the `WorkspaceMembersSource`s, which means that user with local roles set via `sharing` will be available as `ToDo` responsibles. Is that what we want? For now it does not seem to be ok because the local roles that can be assigned by `sharing` do not have view permission.
And do we want to use `get_workspace_user_ids` or `ManageParticipants.get_participants` as source for the users set as watchers on the `ToDo`s? We need to clear that up a bit, and see whether we need the two methods or not.

**Comment by phgross** [comment]
https://4teamwork.atlassian.net/browse/CA-1923
