### ISSUE TITLE
Memory-Verbrauch für archival_checker_script optimieren

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5925]
Das Script soll so angepasst werden, dass der Memory-Verbrauch linear ist.

Vermutlich kann für das Memory-Problem dieselbe Strategie wie in https://github.com/4teamwork/opengever.core/blob/master/opengever/bundle/sections/garbage_collect.py verwendet werden (garbage collecten, setSite() hook, etc.)

https://github.com/4teamwork/opengever.maintenance/blob/master/opengever/maintenance/scripts/archival_file_checker.py

**Comment by phgross** [comment]
Soeben ausgeführt auf dem produktiven System, funktioniert wie gewünscht!
