### ISSUE TITLE
Freezegun in plone.restapi ausbauen

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5928]
Für das Time-Freezing in `plone.restapi` verwenden wir `freezegun`.

Dies hat leider in Vergangenheit schon mehrmals Probleme verursacht, und führt jetzt neu zu einem weiteren Problem, weil `freezegun` (oder Time-Freezing im allgemeinen) nicht thread-safe ist.

Mein Vorschlag wäre daher, `freezegun` aus `plone.restapi` wieder auszubauen, und stattdessen auf andere Art und Weise sicherzustellen, dass die Tests und die durch Tests generierten Examples stabile timestamps enthalten.

Die Verwendung von time-freezing in den `plone.restapi` tests hält sich in Grenzen: Abgesehen von den `test_documentation` JSON examples gibt es nur einen test der failed wenn man es ausbaut, und der entsprechend angepasst werden müssten:

`test_brain_summary_includes_all_metadata_fields`
```python
Failure in test test_brain_summary_includes_all_metadata_fields (plone.restapi.tests.test_serializer_summary.TestSummarySerializers)
Traceback (most recent call last):
  File "/Users/lukasgraf/Plone/python/parts/opt/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/Users/lukasgraf/src/plone.restapi/src/plone/restapi/tests/test_serializer_summary.py", line 186, in test_brain_summary_includes_all_metadata_fields
    summary,
  File "/Users/lukasgraf/Plone/python/parts/opt/lib/python2.7/unittest/case.py", line 835, in assertDictEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Users/lukasgraf/Plone/python/parts/opt/lib/python2.7/unittest/case.py", line 410, in fail
    raise self.failureException(msg)
AssertionError: {'getURL': u'http://nohost/plone/doc1', 'total_comments': 0, 'Title': u'Lorem Ip [truncated]... != {'getURL': u'http://nohost/plone/doc1', 'total_comments': 0, 'Title': u'Lorem Ip [truncated]...
Diff is 1963 characters long. Set self.maxDiff to None to see it.
```

Meine Idee wäre dementsprechend folgendes:
- Für die `test_documentation` tests einen Helper schreiben, der beim Speichern der JSON examples auf das filesystem die sich ändernden Timestamps durch statische timestamps ersetzt. Diesen Helper würde ich versuchen so zu machen, dass er prüft, dass
  - der Format-String für den ersetzten Timestamp derselbe ist
  - TZ-awareness und TZ-offset ebenfalls gleich bleiben
- Für den failenden test würde ich auf dem Objekt einfach `modified`, `created`, etc. entsprechend auf statische Werte setzen.

**Comment by phgross** [comment]
Ist erledigt.
