### ISSUE TITLE
Aufgabe an ein Team delegieren ##27685##

### ISSUE THREAD

**Issue by hugorocha74** [4teamwork/opengever.core#5929]
Harvest: https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/175 

Ausgangslage gemäss betroffener User:

Seit einiger Zeit gibt es die "Teams", die als Aufgabenempfänger eingesetzt werden können. Beim Delegieren einer Aufgabe kann kein Team ausgewählt werden. Dies erstaunt mich und ich finde keine logische Erklärung dafür. Sollte doch möglich sein?

Aktuelle GEVER Version beim betroffenen Kunden: 2019.2.1

Problem konnte sowohl auf sales.onegovgever.ch wie auch auf https://dev.onegovgever.ch reproduziert werden.

Fall-Reproduktion - DEV-Umgebung, Mandant «Amt für Informatik»:
[Test - Aufgabe an Team delegieren.pdf](https://github.com/4teamwork/opengever.core/files/3605453/Test.-.Aufgabe.an.Team.delegieren.pdf)

Extranet-Ticket: https://extranet.4teamwork.ch/support/gemeinde-koeniz/tracker/175

**Comment by phgross** [comment]
Fachliches Review 👍
