### ISSUE TITLE
API Support für Anträge - Verlauf/ProposalHistory

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5934]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Als API Benutzer will den Verlauf eines Antrags sehen. 

- [x] custom proposal API `GET` that contains proposal history. suggested to implement similar to task responses, see example: https://github.com/4teamwork/opengever.core/blob/master/opengever/api/task.py#L13-L22
- [x] BaseResponse für Anträge und eingereichte Anträge verwenden, ProposalHistory durch BaseResponse ersetzen.

**Comment by njohner** [comment]
After having a good look at the code I think this will require quite some refactoring. The main things we need to handle are:
- The `message` field. We have one class per record type (subclassing `BaseHistoryRecord`), each defining a `message`, which is a translated string and gets used in the `proposaloverview.pt`. If we use `BaseResponse`s instead, we do not want to store the messages on the response objects (as they are stored in the annotations). I'd simply propose a mapping from response type to message (similar to what is done for activities).
- The `css_class` will have to be handled similarly to the `message` field above.
- Syncing the history between the proposal and the submitted proposal. I think this could be handled using a `needs_syncing` attribute on the response and an event handler for `ResponseAddedEvent`, although it's not straightforward and we have to be careful not to end up in a syncing loop. A possible solution would be:
  - We make a class for the proposal responses with correct defaults for the syncing depending on the response type, something like:
    ```
    class ProposalResponse(BaseResponse):
        def __init__(self, type, text, needs_syncing=None):
            if needs_syncing is not None:
                 self.needs_syncing = needs_syncing
            else:
                if type == `reopened`:
                    self.needs_syncing = True
                else:
                    self.needs_syncing = False
    ```
  - In the event handler we specifically set `needs_syncing` to False to make sure, we don't enter a syncing loop:
    ```
    def sync_proposal_response(context, event):
        if event.response.needs_syncing:
            obj = ... // find the object where to sync to
            IResponseContainer(obj).add(ProposalResponse(response.type, response.text, False))
    ```
- Some `HistoryRecord`s also generate an activity when added, this can also be handled in the event handler

With that I think we can delete the whole `ProposalHistory` class and the various classes for `HistoryRecord`s, which should make this much leaner...

**Comment by njohner** [comment]
PR is almost ready, so we still need the review and corrections. I expect that to take some time and give some discussions, so maybe a 3.

**Comment by phgross** [comment]
Fachliches Review: 👍 

Sieht gut aus, ausführliche Test sind erst mit er Umsetzung der Detailansicht für Anträge möglich.
