### ISSUE TITLE
@cancelcheckout not documented 

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5947]
The API documentation about documents https://docs.onegovgever.ch/dev-manual/api/documents/#dokumente is missing a chapter about the @cancelcheckout endpoint.

**Comment by phgross** [comment]
@njohner ich finde das neue Kapitel nicht, hast du die Doku nicht publiziert?

**Comment by njohner** [comment]
Sorry, forgot to publish the docu. It's done now: https://docs.onegovgever.ch/dev-manual/api/documents/

**Comment by phgross** [comment]
Fachliches review: 👍
