### ISSUE TITLE
Bumblebee overlay fails in certain cases

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#5962]
It seems that the bumblebee overlay sometimes fails (https://sentry.4teamwork.ch/sentry/onegov-gever/issues/31191/) because it cannot retrieve the version metadata. My guess is that in certain circumstances there is no `History` for the document, `getHistoryMetadata` will return an empty list instead of a history object (or whatever is returned normally)...

This could stem from https://github.com/plone/Products.CMFEditions/blob/master/Products/CMFEditions/ZVCStorageTool.py#L426-L428, though I have not checked that it really was this method that was called...

**Comment by deiferni** [comment]
Issue no longer present in sentry.
