### ISSUE TITLE
@querysources change in plone.restapi breaking Volto

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5969]
My recent change in plone/plone.restapi#791 had some unintended consequences where it breaks the Volto user interface (see [this comment](https://github.com/plone/plone.restapi/pull/791#issuecomment-538904096) and the discussion below).

This issue is mainly a placeholder to manage time commitment for this Sprint in SCRUM.

**Comment by phgross** [comment]
Am nächsten Daily, besprechen/schätzen/laden
