### ISSUE TITLE
Pass date format-string to docxcompose

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5972]
See also https://github.com/4teamwork/docxcompose/issues/47. Currenlty docxcompose always uses server locale to format strings. We either want german or french format strings. So either hardcode them or pass the format string to docxcompose.

We already keep a format  string in our settings, but currenlty only for sablon/meeting related things. See https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/interfaces.py#L14-L17.

**Comment by phgross** [comment]
Kann bei der Definition der Word Vorlagen gelöst werden - ist deshalb nicht notwendig.
