### ISSUE TITLE
REST API Schema-Intent Konzept in opengever.core umsetzen 

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5973]
_Harvest: `Projekt - Umsetzung Neues User Interface GEVER 2019/2020` - `Entwicklung`_

Der Vorschlag in https://github.com/4teamwork/opengever.core/issues/5968#issuecomment-539090849 soll in Zukunft in `plone.restapi` umgesetzt werden.

Wir werden dazu in `plone.restapi` den Vorschlag machen, dies wie beschrieben zu implementieren. Da dies aber eine relativ fundamentale Anpassung ist, ist damit zu rechnen dass noch einiger Diskussionsbedarf besteht, und die Umsetzung nicht in nächster Zeit erfolgen kann.

Daher wollen wir die Umsetzung dieses Konzeptes vorerst in `opengever.core` prototypen. Es soll dazu das Konzept wie beschrieben umgesetzt werden, aber ohne Änderungen in `plone.restapi` vorzunehmen, sondern indem die nötigen Services in GEVER entsprechend überschrieben und angepasst werden.

Folgende Anpassungen sollen gemacht werden:

### Weitere Aufruf-Syntax  für `@sources`, `@querysources` und `@vocabularies` einführen

Für diese drei Endpoints soll eine neue Aufruf-Syntax eingeführt werden, welche die Add-Semantik wiederspiegelt:

![sources_add](https://user-images.githubusercontent.com/405124/66383845-06e15700-e9be-11e9-8b0f-207e46620896.png)
![querysources_add](https://user-images.githubusercontent.com/405124/66385344-a0aa0380-e9c0-11e9-90de-300a398ceb72.png)
![vocabularies_add](https://user-images.githubusercontent.com/405124/66385356-a6074e00-e9c0-11e9-8794-e4a4a1dab21b.png)

_(Siehe Vorschlag im referenzierten Ticket)._

Die Endpoints müssen also überschrieben und so umgebaut werden, dass sie entweder 1 oder 2 Pfad-Parameter akzeptieren.
- 1 Parameter: Der parameter ist `field_name`. Dies impliziert **edit** intent
- 2 Parameter: Die Parameter sind `portal_type` und `field_name`, in dieser Reihenfolge. Dies impliziert **add** intent

Abhängig von der Aufruf-Syntax soll das Schema, von dem die Source, Querysource oder Vocabulary geholt wird, unterschiedlich bestimmt werden:
- **edit** - es soll der `portal_type` des `context` ausgelesen werden
- **add** - es soll der `portal_type` Pfad-Parameter verwendet werden

Über den `portal_type` wird dann die FTI geholt, und darüber das Schema, etc.. (muss voraussichtlich nicht angepasst werden).

### Neuen endpoint `@schema` einführen

  - Soll möglichst viel von der Implementierung von `@types/(portal_type)` aus `plone.restapi` erben
  - Soll aber _nur_ das serialisieren von Schemas anbieten, nicht das auflisten von existierenden / addable types

  - Im Gegensatz zu `@types/(portal_type)` soll es aber zwei Formen des Aufrufs geben:

Intent: **edit**
 ![schema_edit](https://user-images.githubusercontent.com/405124/66384321-dbab3780-e9be-11e9-8d5b-bcf9d0401930.png)

Intent: **add**
![schema_add](https://user-images.githubusercontent.com/405124/66384334-dea62800-e9be-11e9-9600-e9bf012bc4ee.png) 

  - Bei der Serialisierung des Schemas soll dann der Intent erhalten bleiben, wenn Vocabulary-like URLs konstruiert werden:
    - Bei **add** soll auf `(container)/@sources/(portal_type)/(field_name)` verlinkt werden
    - Bei **edit** soll auf `(context)/@sources/(field_name)` verlinkt werden
    _(analog für `@vocabularies` und `@querysources`)_

Voraussichtlich werden folgende Arbeiten nötig sein:

- `@sources`, `@querysources` und `@vocabularies` endpoints überschreiben
- Sicherstellen dass diese Endpoints auch auf dem `IPloneSiteRoot` verfügbar sind (dann aber nur mit **add** Intent verwendbar)
- Neuen `@schema` endpoint registrieren (für `IPloneSiteRoot` und `IContentish`)
- Die Logik für die Schema-Generierung aus `plone.restapi` für den `@schema` endpoint wiederverwenden, aber anpassen. Dazu werden vermutlich einige Funktionen aus [`plone.restapi.types.utils`](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/types/utils.py) kopiert, gewrapped oder monkey-patched werden müssen.

**Comment by lukasgraf** [comment]
Schätzung des verbleibenden Aufwands (siehe Tasks im verlinkten Draft-PR): 3 Story Points

**Comment by njohner** [comment]
Frontend: 5 SP
- Use the `schema` endpoint
- Treat add and edit forms separately
- no hardcoded vocabularies

**Comment by phgross** [comment]
Das ganze müsste ja nun auch im Frontend verwendet werden. Sonst haben wir keine Aussage ob das Konzept wie gewünscht funktioniert. Ich verschiebe den Issue deshalb wieder ins Todo.

**Comment by phgross** [comment]
Dieser Issue wurde umgesetzt und wird nun im UI in allen Formularen verwendet. Funktioniert wie gewünscht.
