### ISSUE TITLE
XLS Report, Zip Export, PDF Export should also handle relative_paths

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5974]
The listing actions `Als Zip-Datei exportieren`, `Auswahl exportieren` and `Auswahl drucken (PDF)` should also work with realtive paths passed in the `paths` parameter.

Views:
- `zip_selected` (Als Zip-Datei exportieren, Documents Tab)
- `document_report` (Auswahl exportieren, Documents Tab)
- `pdf-dossier-listing` (Auswahl drucken, Dossiers Tab)

Should fix https://github.com/4teamwork/gever-ui/issues/479

**Comment by lukasgraf** [comment]
Sentry Issue for ZIP-Export:  https://sentry.4teamwork.ch/sentry/onegov-gever/issues/9124/

**Comment by phgross** [comment]
Fachliches Review: 👍
