### ISSUE TITLE
Reordering objects via plone.restapi creates unicode ids, should use bytestring ids.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#5980]
This issue is very similar to https://github.com/4teamwork/opengever.core/issues/5957. When reordering objects in `plone.restapi` in https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/deserializer/mixins.py#L36-L43 unicode ids are used to update ordering via the `OFS.interfaces.IOrderedContainer` interface. We are of the opinion those ids should be `ascii` instead. The ids used for ordering are later output in a call to `objectIds` where bytestrings are expected. The result of a call to `objectIds` may be used for traversal by the client where unicode paths will fail. Thus we should use bytestring ids to call the reordering methods as they perform no internal conversion. Next steps to take here would be:
- decide how/where to fix this, can we fix it in `plone.restapi`, should we provide a migraiton in `plone.restapi`?
- should we override the functionality here until we can fix it upstream?
- should we provide our own migration to fix or does `plone.restapi` provide such migrations?

**Comment by njohner** [comment]
We fix it in `opengever.core`, then @lukasgraf will discuss the issue with Timo at the ploneconf.

**Comment by deiferni** [comment]
we have discussed this a moment ago. we will create issue  and probably also PR to fix in `plone.restapi`. timo will also start a discussion about the uprgade path that we want to take here. iirc we tend to not upgrade by default as an upgrade would have to inspect all orderable content items but we expect that most content won't actually be affected.

**Comment by deiferni** [comment]
I have attempted to reproduced this locally with `plone5.2` and `python3.7` and `python2.7` with the following steps:

- have used https://github.com/4teamwork/ftw.testing as it already provides base plone5.2 and python3.7 buildout.cfg files.
- setup a new plone site, create one parent folder and some pages in it.
- inspect `objectIds` of folder in debug shell
- reorder content via rest api, move one item down
```js
{
    "ordering": {"obj_id": "page3", "delta": 1}
}
```
- inspect `objectIds` again

plone5.2 + python3.7, no issues as python3 string implementation defaults to unicode

plone5.2 + python2.7: the list returned by a call to `objectIds` will contain mixed unicode and bytestrings. Calls to `keys` and `objectIds` are affected, the `ExtednedPathIndex` is not affected as it relies on `getPhysicalPath`.

```python
from AccessControl.SecurityManagement import newSecurityManager
from zope.component.hooks import setSite

plone = app.unrestrictedTraverse('Plone')
user = app.acl_users.getUser('admin')
user = user.__of__(app.acl_users)
newSecurityManager(app, user)
setSite(plone)

folder = plone.unrestrictedTraverse('folder/')
folder.objectIds()
>>> ['page1', 'page2', 'page4', u'page3']

folder.keys()
>>> ['page1', 'page2', 'page4', u'page3']

folder['page3'].getId()
>>> 'page3'

catalog = plone.portal_catalog._catalog
pi = catalog.indexes['path']
list(pi._index.keys())
>>> [None, 'Members', 'Plone', 'aggregator', 'events', 'folder', 'front-page', 'news', 'page1', 'page2', 'page3', 'page4']
list(pi._unindex.values())
>>> ['/Plone/front-page', '/Plone/news', '/Plone/news/aggregator', '/Plone/events', '/Plone/events/aggregator', '/Plone/Members', '/Plone/folder', '/Plone/folder/page1', '/Plone/folder/page2', '/Plone/folder/page3', '/Plone/folder/page4']

folder['page3'].getPhysicalPath()
('', 'Plone', 'folder', 'page3')
```
