### ISSUE TITLE
Freigabe erkennt keine Eingabe mit Umlauten

### ISSUE THREAD

**Issue by jounsiboss** [4teamwork/opengever.core#5983]
- Bei der Suche in der "Freigabe" werden Eingaben welche "Umlaute" enthalten nicht gefunden.

![freigabe_umlaute](https://user-images.githubusercontent.com/11310148/66483696-e391d700-eaa5-11e9-845c-1bf10b059f52.png)

GEVER (DEV) -> https://dev.onegovgever.ch/fd/ordnungssystem/gesundheit/praevention/allgemeines/dossier-707
Extranet-Issue -> https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/857

**Comment by phgross** [comment]
Fachliches Review 👍
