### ISSUE TITLE
Auflistung von Anträgen (Backend)

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5989]
Abfragen von Anträgen via @listing endpoint sollte möglich sein für https://github.com/4teamwork/gever-ui/issues/543.

Metadaten: 
- Titel
- Antragsteller (issuer)
- review_state
- created
- containing_dossier
- committtee*

* Ist zurzeit noch nicht indexiert - m.E. aber zwingend notwendig

**Comment by njohner** [comment]
Im `responsible` indexieren

**Comment by njohner** [comment]
I'd wait here that the refactoring of the listing endpoint is done:
https://github.com/4teamwork/opengever.core/issues/5901

**Comment by phgross** [comment]
Fachliches Review: 👍
