### ISSUE TITLE
Keywords contain null-title for GET on Dossier

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5991]
A REST API `GET` request for a dossier lists the `keywords` field with `null` values for the terms titles:

### Steps to reproduce

- Create a dossier
- Add at least one keyword
- Do a REST API `GET`request on that dossier

### Actual behavior

Keywords contain `null` for their title, only the token contains a value:

```json
{ "...": "...",
  "items_total": 2,
  "keywords": [
    {
      "title": null,
      "token": "Wichtig"
    }
  ]
} 
```

### Expected behavior

The `title` property of terms should contain the human readable display title. In the case of keywords that would be the same value. (If the underlying vocabulary is not _titled_, the serialization should default to the same value as the `token`, and still produce a `title`)

---

The reason seems to be that the following code in `ftw.keywordwidget` creates a `SimpleVocabulary` that has terms with `token` and `value`, but `title` set to `None:
```python
        self.vocab = SimpleVocabulary.fromItems(
            [(as_keyword_token(x), x) for x in self.keywords])
```
https://github.com/4teamwork/ftw.keywordwidget/blob/master/ftw/keywordwidget/vocabularies.py#L112-L113

**Comment by lukasgraf** [comment]
This is the issue that's responsible for the problem seen in 4teamwork/gever-ui#544

**Comment by phgross** [comment]
Fachliches Review: 👍
