### ISSUE TITLE
Listing Endpoint: Support für PersonalDossiers

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#5992]
Aktuell gibt es keine Möglichkeit Dossiers innerhalb der persönlichen Ablage via listing Endpoint abzufragen. Es sind die gleichen Metadaten gewünscht, wie dies auch beim Dossier der Fall ist.
Auf listing endpoint mit `name=dossier` auch die PersonalDossiers zurückschicken

**Comment by elioschmutz** [comment]
Der Listingendpoint gibt persönliche Dossiers bereits zurück:

<img width="1190" alt="Bildschirmfoto 2019-10-25 um 16 45 59" src="https://user-images.githubusercontent.com/557005/67580649-f7e0ff80-f746-11e9-97e1-7270fbe8b879.png">

**Comment by phgross** [comment]
Kann ich via UI nicht testen, werden ich nach den Frontend arbeiten prüfen.
