### ISSUE TITLE
Autocompletion for non-ASCII Keywords leads to UnicodeDecodeError

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#5999]
### Steps to reproduce

- Make sure to use the new GEVER UI
- Create or pick a dossier
- Choose "Metadaten bearbeiten" from the three dots menu
- For the `Schlagwörter` field, try to add a new Keyword containing non-ASCII characters, like `Büroeinrichtung`

### Actual Results
- On the backend requests to the `@vocabularies` endpoint fail with an `UnicodeDecodeError`:

```
2019-10-21 10:08:25 ERROR Zope.SiteErrorLog 1571645305.390.804353664029 http://localhost:8081/fd/@vocabularies/plone.app.vocabularies.Keywords
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.rest.service, line 23, in __call__
  Module plone.restapi.services, line 21, in render
  Module plone.restapi.services.vocabularies.get, line 54, in reply
  Module plone.restapi.serializer.vocabularies, line 45, in __call__
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```
- Typing out and saving the new keyword still (kinda) works in the GEVER UI. Not sure whether this is desirable.
- Once saved, the keyword with non-ASCII gets rendered in QP:

![keywords](https://user-images.githubusercontent.com/405124/67188348-6a22ae80-f3ec-11e9-9ea5-20312496f974.png)
This seems to be a separate bug in `gever-ui`, see 4teamwork/gever-ui#577

### Expected Results

- Adding new keywords with non-ASCII characters works without raising exceptions, and they get displayed properly afterwards

**Comment by lukasgraf** [comment]
PR in `plone.restapi`: plone/plone.restapi#826

**Comment by lukasgraf** [comment]
This issue is technically done, but a new problem surfaced that prevents adding new keywords alltogether. The fix for that issue is pending at 4teamwork/opengever.core#6046

Estimated remaining work: `To small to estimate`

**Comment by phgross** [comment]
Fachliches Review 👍
