### ISSUE TITLE
Journaleinträge Office Connector

### ISSUE THREAD

**Issue by hugorocha74** [4teamwork/opengever.core#6003]
Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`

Ausgangslage:
Es wird in GEVER ein Eintrag ins Journal geschrieben, wenn die Speichern-Funktion im Office (z.B. Word) genutzt wird. Da man während des Schreibens eines Dokuments oft speichert, wird das Journal mit diesen Informationen überflutet. Es sollte so sein, dass nicht jede "Speichern"-Aktion journalisiert wird. Damit wird das Journal nur unübersichtlich und mit unnötigen Daten gefüllt. 

Analyse:
Hierbei handelt es sich um ein generelles Verhalten bei der Dokumenten-Bearbeitung auf GEVER, welche durch vergangene OC und GEVER-Release eingeführt wurde. Dies wurde wohl mit dem OC-Feature, welches das sofortige Hochladen der Änderungen bei jeder Zwischenspeicherung ermöglicht eingeführt.

Weitere Schritte:
Überprüfen ob das hier beschriebene OC-Feature wieder rückgängig gemacht werden soll.

[Ansicht Journaleinträge.pdf](https://github.com/4teamwork/opengever.core/files/3766513/Ansicht.Journaleintrage.pdf)

Ref. Ticket: https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20445

Vorgeschlagene Lösung:
- Hochladen nicht mehr im Journal separat aufführen.
- Vorerst keine Migration

**Comment by phgross** [comment]
Fachliches Review: 👍
