### ISSUE TITLE
Geschäftsdossier - Metadaten - Lange Stichwörter - x nicht sichtbar

### ISSUE THREAD

**Issue by hugorocha74** [4teamwork/opengever.core#6004]
Ausgangslage:
Es wurde festgestellt, dass sich lange Stichwörter nicht entfernen lassen da das "x" (Funktion Ausschneiden) nicht sichtbar ist im GUI.

Lösung:
Eventuell müsste bei einem nächsten Release folgendes geändert werden:
- x vorne beim Stichwort platzieren
- Fenster verbreitern

Ref.Ticket: https://extranet.4teamwork.ch/support/gever-ai/tracker/379

Screenshot:

![image](https://user-images.githubusercontent.com/50739403/67470343-dfd98500-f64d-11e9-8cb1-b7c582d6e5fe.png)

**Comment by deiferni** [comment]
Wir im neuen UI gelöst.
