### ISSUE TITLE
Revert to version via API does not do the right thing.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6008]
GEVER currently provides its own functionality to revert a document, which is currently not called/used by plone.restapi's revert functionality.

**Comment by phgross** [comment]
@all4manu ist es aufwändig, dies für das neue Frontend freizuschalten?

**Comment by all4manu** [comment]
@phgross denke höchstens ein `2`. Soll ich den Issue zu mir nehmen?

**Comment by phgross** [comment]
Ja gerne, dann ist es erledigt und wir wissen gleich ob alles in Ordnung ist mit der API

**Comment by phgross** [comment]
@all4manu hat man den Frontend Teil nun implementiert oder noch nicht?

**Comment by all4manu** [comment]
> @all4manu hat man den Frontend Teil nun implementiert oder noch nicht?

@phgross ist umgesetzt und bereit für tech review

**Comment by phgross** [comment]
Fachliches Review 👍
