### ISSUE TITLE
Anhänge zu Anträgen aus der Sitzungsansicht bearbeiten

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#6013]
_Harvest: `[0.366 / 21] Projekt - OGIP 56, OGIP 57 und Erweiterungen SPV` - `Erweiterungen SPV`_

- In Antrag/Sitzungsansicht auf Dokumentübersicht einer Beilage Hinweis, dass Dokument gesperrt ist um "entsperren" Button ergänzen:

<img width="999" alt="Screenshot 2020-01-08 at 16 46 00" src="https://user-images.githubusercontent.com/736583/71992935-8c330c80-3236-11ea-8bf8-bb34bda23748.png">

- Danach natürlich Bestätigung, dass Entsperrung gewünscht durch Benutzer 
- Dokument entsperren ist irreversibel, sobald das Dokument einmal entsperrt wurde, kann man das nicht mehr rückgängig machen
- Im Moment gibt es Funktionalität, die ein Aktualisieren der Beilagen erlaubt (Antrag mit Anhang erstellen, einreichen, Dokument im Dossier editieren, Antragsübersicht sieht dann so aus: 
<img width="635" alt="Screenshot 2020-01-08 at 16 52 34" src="https://user-images.githubusercontent.com/736583/71993573-9efa1100-3237-11ea-9ac4-56b912094b1c.png">)
Dies ist nach entsperren nicht mehr sinnvoll und muss deaktiviert werden.
- Es gibt ein model, welches die zwei Dokumente verbindet https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/model/submitteddocument.py

Siehe auch https://extranet.4teamwork.ch/crm/opportunities/1375.

> Antragsdokumente können nach der Einreichung von den Gremienverantwortlichen bearbeitet werden. Das ist wichtig. Dagegen sind die Anhänge zu Anträgen nicht bearbeitbar. Die Gremienverant-wortlichen können deshalb keine Fehler nachträglich korrigieren. Zudem können neue Anhänge und neue Versionen von Anhängen nachgereicht werden, ohne, dass die Gremienverantwortlichen etwas dagegen tun können. Massnahme: Neu sollen die Gremienverantwortlichen die Anhänge manuell entsperren und dann bearbeiten können. So könnten sie auch allfällig fälschlich nachgereichte Versionen rückgängig machen.
> Stellungnahme 4tw:
> Wir erachten den Vorschlag als sinnvoll. Die Entsperrung müsste manuell durch den Gremienver-antwortlichen geschehen. Ein manuell entsperrtes Dokument, bleibt anschliessend entsperrt. 
> Da der Gremienverantwortliche über aktualisierte Beilagen benachrichtigt wird, könnte er dann z.B. neue Versionen zurücksetzen oder wieder überarbeiten.

**Comment by jone** [comment]
Test nicht erfolgreich.
- `hugo.boss`
- https://dev.onegovgever.ch/fd/sitzungen/committee-8/submitted-proposal-80/document-1860#overview
-> Link "Entsperren" nicht sichtbar.

- dev nicht akutell?
- habe ich mit dem richtigen Benutzer getestet?

**Comment by elioschmutz** [comment]
@jone ist auf lab eingespielt, nicht auf dev...

**Comment by jone** [comment]
Funktioniert aus meiner Sicht.
