### ISSUE TITLE
Verschieben von Anträgen

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#6014]
Harvest: `[0.366 / 21] Projekt - OGIP 56, OGIP 57 und Erweiterungen SPV` - `Erweiterungen SPV` 

Bearbeitete Anträge können nicht in ein anderes Dossier/Subdossier verschoben werden.

Stellungnahme 4tw:
Dieses Thema ist im Feedbackforum diskutiert worden. Die Gemeinde Nidau setzt sich stark für die Funktionalität ein, dass Anträge innerhalb des Dossiers verschoben werden können. Köniz hat sich ebenfalls für eine Umsetzung ausgesprochen.

**Comment by njohner** [comment]
- Only allow to move in the same dossier (into subdossiers), because of attached documents and so on
- Don't forget to update the SQL
- Also make sure that moving a dossier containing a proposal works correctly

**Comment by deiferni** [comment]
currently dossiers with proposals (in submitted state?) in the cannot be moved at all.

**Comment by elioschmutz** [comment]
@deiferni Dossiers with proposals can be moved:

![screen2](https://user-images.githubusercontent.com/557005/72989608-e31c1280-3dee-11ea-8a12-b9957168a28f.gif)

**Comment by elioschmutz** [comment]
Es gibt diverse Probleme bei der Umsetzung dieses Issues:

1. #6211 Das Contenttreeewidget funktioniert nicht wie gewünscht. Es ist möglich ein Proposal immer in ein anderes Dossier zu verschieben. Der Issue muss erst diskutiert und eine Lösung besprochen werden
2. Das Contenttreewidget erlaubt es momentan nicht, einen Inhalt in das Root-Dossier zu verschieben. Ich sehe keine einfache Möglichkeit, dies zu ändern. Über das Autocomplete wäre es möglich, aber das funktioniert generell nicht wie es sollte (siehe Punkt 1). Es werden nur Dossiers unterhalb des Root-Dossiers angezeigt. Das verhalten ist Hardcodiert https://github.com/plone/plone.formwidget.contenttree/blob/master/plone/formwidget/contenttree/widget.py#L95. 
3. #6212 Dossiers mit eingereichten Anträgen können verschoben werden (nicht wie von @deiferni vermutet, dass dies eingeschränkt wird)

**Comment by Suweber** [comment]
@elioschmutz Hab ich das richtig verstanden: Es ist möglich, Anträge in ein anderes Hauptdossier zu verschieben, aber nicht innerhalb des Dossiers ein anderes Subdossier?

**Comment by elioschmutz** [comment]
@Suweber nein, nicht ganz. Momentan ist es möglich, ein Antrag überall hin zu verschieben. 

Mit meiner Anpassung wird dies dann nicht mehr möglich sein. Ein Antrag kann danach nur noch innerhalb seines Hauptdossiers verschoben werden können.

**Comment by jone** [comment]
@Suweber wie besprochen: könntest du das reviewen? Merci!

**Comment by Suweber** [comment]
Issue unvollständig, da Antrag in Dossier via Elemente verschieben "nur" via manuell Eingabe verschoben werden kann. Dossierbaum erscheint nicht. 
Da wir nur innerhalb des betroffenen Dossiers verschieben, macht es Sinn das betroffene Dossier bzw. die Subdossiers direkt anzuzeigen. 
![image](https://user-images.githubusercontent.com/31923504/73862560-fee7d580-483e-11ea-971a-1edd5b81de09.png)

**Comment by elioschmutz** [comment]
@Suweber Salut su, in welchem Dossier testest du genau? Hat es subdossiers? Bei mir funktioniert es:

![screen1](https://user-images.githubusercontent.com/557005/73873821-a3274780-4852-11ea-99fa-f674724d4bf0.gif)

Aber es gibt ein bekanntes Problem mit dem Widget: Das Root-Dossier kann nicht angewählt werden. Siehe Warnung im PR: https://github.com/4teamwork/opengever.core/pull/6223 und hier der Issue dazu: https://github.com/4teamwork/opengever.core/issues/6224 

Das Problem ist leider nicht einfach zu lösen und müsste wohl noch im Team besprochen werden. Ich kann nicht beurteilen, ob dies kritisch für den Abschluss ist oder nicht.

**Comment by Suweber** [comment]
@elioschmutz spielt es eine Rolle, welchen Status der Antrag hat? Ich habs hier versucht: https://dev.onegovgever.ch/fd/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-530#proposals

**Comment by elioschmutz** [comment]
@Suweber nein, es spielt keine Rolle.

Genau, dort wo du testest tritt genau der oben beschriebene Fall auf. Es gibt keine Subdossiers. Der Antrag könnte also nur in das Hauptdossier verschoben werden. Das Widget zeigt das Hauptdossier jedoch nicht an. Wenn du ein Subdossier erstellst, sollte dieses angezeigt werden...

**Comment by Suweber** [comment]
stimmt, das Subdossier wird nun angezeigt. Merci! Es ist wohl nicht möglich eine Hilfe einzublenden im Sinne von "keine Subdossiers vorhanden"?

**Comment by elioschmutz** [comment]
Von Haus aus gibt es leider nichts. Ich kann es per JS "reinhacken". Eine andere Möglichkeit haben wir momentan nicht... Alternativ übernehmen wir es so wie es ist und werden das Problem dann mit dem Issue https://github.com/4teamwork/opengever.core/issues/6224 lösen...

Wie seht ihr das? @jone @Suweber

**Comment by jone** [comment]
@Suweber ich würde es tendenziell mal so sein lassen, weil meine Einschätzung ist dass es relativ Aufwändig ist, einen Mehrwert zu schaffen. Ist das für dich so ok?

**Comment by Suweber** [comment]
ok, ich kann in der Dokumentation ja extra einen Hinweis einbauen, dass im Dossier Subdossier vorhanden sein müssen (um diese anzuzeigen).

**Comment by jone** [comment]
Ja, wir dokumentieren das. Damit ist dieses PBI abgeschlossen 👍
