### ISSUE TITLE
Aus Antrag direkt Aufgaben erteilen 

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#6015]
Harvest: `[0.366 / 21] Projekt - OGIP 56, OGIP 57 und Erweiterungen SPV` - `Erweiterungen SPV`

- Neue action "Aufgabe erstellen" auf `Proposal`
- Dabei Pre-Fill der Verweise der Aufgabe mit Antragsdokument + Beilagen des Antrags

Aus dem Antrag sollten direkt Aufgaben erteilt werden können (z.B. Einladung Mitberichtsverfahren; Genehmigungsverfahren Anträge); so müssten nicht immer wieder alle Dokumente (Antrag mit Beilagen) zusammengesucht /-gestellt werden.

Stellungnahme 4tw:
Diese Ergänzung ist sinnvoll und mit geringem Aufwand umzusetzen. Wir haben den entsprechen-den Issue bereits erfasst. Wir schlagen vor, per Default immer alle Dokumente (Anträge, Anhänge, Protokollauszüge) der Aufgabe anzuhängen. Der Auftraggeber kann vor dem Senden nicht benötigte Dokument entfernen.

**Comment by njohner** [comment]
- There is already such an action in the meeting view (`AgendaItem`)
- This should be for the `Proposal`, not the `SubmittedProposal`
- Should also give a new action in the new UI (action on the proposal in a listing and in the proposal detail view)

**Comment by jone** [comment]
https://github.com/4teamwork/gever-ui/issues/837 may be related if both are meant to be implemented in the new UI.

**Comment by all4manu** [comment]
#### Abgrenzung

Da im neuen UI noch keine Detail Ansicht für Proposals existiert, beschränkt sich dieses PBI auf das bestehende UI.

#### Erkenntnisse

- Aufgabe wird auf Ebene vom Dossier erstellt
- Antrag selbst wird ebenfalls bei den Verweisen hinzugefügt (prefilled, damit der User ihn auch wieder entfernen kann) => Nice to have: Falls zu komplex, nicht umsetzen

**Comment by jone** [comment]
Die Umsetzung im neuen UI wurde abgegrenzt und extrahiert nach: https://github.com/4teamwork/gever-ui/issues/842 (kann noch nicht umgesetzt werden da die Ansicht Antrag noch fehlt)

**Comment by jone** [comment]
In Absprache mit Su nehmen löschen wir die Anforderung "Antrag selbst wird ebenfalls bei den Verweisen hinzugefügt".
Grund: es besteht ein Fehlerpotential bei mandantenübergreifenden Aufgaben.
Überlegung: dem Empfänger der Aufgabe ist vor allem das Primärdokument des Antrags wichtig, das muss verknüpft sein. Der Antrag selbst interessiert ihn weniger.

@elioschmutz reicht dir das?

**Comment by jone** [comment]
Ich kann nicht testen weil ich die Aktion nicht finde.
- https://dev.onegovgever.ch/fd/sitzungen/committee-10/submitted-proposal-43#overview
- `hugo.boss`

**Comment by elioschmutz** [comment]
@jone siehe Nachricht von @njohner `This should be for the Proposal, not the SubmittedProposal`

**Comment by njohner** [comment]
@elioschmutz I also tried on Dev on a proposal and could not find the action. Is this deployed on dev?

**Comment by njohner** [comment]
@jone @elioschmutz Ok seems dev is not up to date, this works on lab:
https://lab.onegovgever.ch/ordnungssystem/fuehrung/gemeinderecht/uebergeordnete-erlasse/dossier-72/proposal-3

**Comment by elioschmutz** [comment]
yes, I only updated lab, as it is usual...

**Comment by jone** [comment]
Aus meiner Sicht ok.

**Comment by jone** [comment]
Ich bin nicht mehr sicher ob wir es auf dem Antrag im Quelldossier machen sollen oder auf dem Antrag in der Sitzung. Jetzt ists auf dem Quelldossier gemacht. @Suweber wir müssen das noch kurz besprechen.
