### ISSUE TITLE
SOLR Support für Relstorage/Oracle backends

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6023]
Im ftw.solr soll das Indexieren von Dokumente welche im Relstorage abgelegt sind ermöglicht werden. 

Siehe auch https://gever.4teamwork.ch/ordnungssystem/0/220/1/dossier-3818/document-31964?SearchableText=Solr+zug

Problematik: Blobs im Moment über Filesystem. Funktioniert nicht einfach so mit Relstorage. Eventuell mit Blob-Cache lösbar. Unklar wie Deployment mit zwei Servern aussieht. Master-Slave SOLR? ... mit @buchi abklären.

**Comment by lukasgraf** [comment]
Closed via 4teamwork/ftw.solr#149

Follow up issue: https://github.com/4teamwork/opengever.core/issues/6107
