### ISSUE TITLE
@solrsearch endpoint should return facets label/title

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#6026]
We ran into an issue with the new gever-ui when querying the `@solrsearch` endpoint. In order to keep the backend calls to a minimum, we use the facet information returned from the endpoint to build a list of facets the user can further refine the results with.

Currently, the endpoint only returns the token values for each item per facet. This puts us in a difficult position regarding translations. We expected to receive the facet information in the same way the `@listing` endpoint returns them: 

```json
{
  facets: {
    facet_name: {
      token_value: {
        count: 1,
        label: "Translated value",
      },
    },
  }
}
```

This would make the translation situation much easier in the frontend for the following cases:

- Some facets (i.e. document_type) are actually dynamic, which means they can be customized for different GEVER installations.
- Some facets (i.e. users) aren't finite lists, so we cannot translate them in a static file.
- If the items for a particular facet change (i.e. new ones are added), there is no risk that we forget to update the frontend.

**Comment by phgross** [comment]
Fachliches Review 👍
