### ISSUE TITLE
Group management

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#6029]
- As responsible person for the teamraum installation on the customer site, I would like to be able to create groups and assign members to the group 

- As responsible person for the teamraum installation on the customer site, I would like to assign users to existing teamraums. This could be either thru invitation or a different mechanism, which makes sure the user gets the right permissions.

**Comment by maethu** [comment]
In GEVER we need to implement the following feature

- Assign groups to teamraum and folders in teamraum in a "sharing" view

Also see:
- #6028 (Sharing view for teamraum)
- #6027 (Sharing view for folders in teamraum)

**Comment by phgross** [comment]
Wird mit #6041 abgedeckt.
