### ISSUE TITLE
Adjustment in the navigation on the left

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#6032]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

There should be a header "Teamräume", indicating this is the list of teamräume I can access.

**Comment by phgross** [comment]
Ich stelle mir eine Darstellung wie beispielsweise bei den Favoriten vor. z.B. so
<img width="310" alt="Bildschirmfoto 2019-12-03 um 08 28 13" src="https://user-images.githubusercontent.com/485755/70029252-f0fba700-15a6-11ea-9f39-936362bb4df9.png"> (natürlich mit anderen Icons)

**Comment by phgross** [comment]
@all4manu ich sehe keine Veränderung? wo ist das eingespielt.

**Comment by phgross** [comment]
@all4manu sorry, never mind was in the tech review not in the review column.
