### ISSUE TITLE
Freigaben Verwalten im Teamraum

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#6041]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

- Einem globalen Admin (Aktuell Site Administrator Rolle), soll es möglich sein Gruppen und Benutzer direkt auf einem Arbeitsraum, oder Ordner zu berechtigen
Bsp: https://bve.teamraum.ch/projects/akov/@@sharing 
![Screen Shot 2019-11-11 at 17.06.33.png](https://images.zenhubusercontent.com/558d47bf4f7a08fbb7f37023/8ee01ff4-c399-43c6-942c-8ffb297516a1)

- Unterbrechen der Berechtigungen soll, wie in Plone Standard ebenfalls zu verfügung stehen, so dass gewisse Bereiche z.B für ein Gremium vom Rest des Teamraumes abgeschottet werden können (closed user groups)
<img width="1113" alt="Screen Shot 2019-11-11 at 17 16 48" src="https://user-images.githubusercontent.com/437933/68602687-17965880-04a7-11ea-968b-723bd359b896.png">

- Teamraum Ersteller / Teamraum Admins können nur Freigaben manipulieren, welche bereits auf dem Teamraum gesetzt sind. Es darf kein Zugriff auf globale Gruppen und Benutzer möglich sein. Dadurch kann ansonsten auf Benutzerinformationen zugegriffen werden, welche gar nicht im Teamraum beteiligt sind. Beispiel: Auf eine Ordern, sollen nur noch die Benutzer Hans und Peter Zugriff haben. Im UI dürfen nur die Benutzer zur Verfügung stehen, welche ebenfalls auf dem übergeordneten Teamraum Zugriff haben.

Ich stelle mit vor, dass dies wie die aktuellen Freigaben in Plone funktionieren. Mit dem Unterschied, dass ich als Teamraum-Admin/Ersteller nur auf die BenutzerZugriff habe, welche bereits Berechtigt sind. Neue Benutzer kann ich als Teamraum-Admin nur über Einladungen hinzufügen.

Die Benutzer und Gruppenverwaltung geschieht ausschliesslich über das Portal.

Dieses Ticket ersetzt:
- #6029 
- #6028 
- #6027 
- #5912

**Comment by all4manu** [comment]
Um Punkt 1 zu erfüllen muss die `sharing` action auf Stufe Workspace für Berechtigte Personen (globale Admins, etc.) im @actions Endpoint geliefert werden. Z.Z. kommt diese action nur auf Stufe von Ordnern.

Um Punkt 3 zu erfüllen muss im Backend sichergestellt werden, dass der @sharing Endpoint nur User zurückliefert, welche bereits auf dem Workspace berechtig sind.

**Comment by all4manu** [comment]
Folgendes ist mir noch aufgefallen, was wir vielleicht irgendwie handeln müssen im GUI:

- Wenn ein Ordner Rollen erbt, dann werden alle User vom Parent angezeigt ausser der Workspace Ersteller.
- Unterbricht man die Vererbung, so werden keine User mehr angezeigt - auch nicht der Workspace Ersteller, obwohl der immer noch Zugriff hat.
- Fügt man nun im Ordner mit der unterbrochenen Vererbung einen User manuell hinzu, so verliert der Workspace Ersteller die Berechtigung auf diesen Ordner.

**Comment by phgross** [comment]
Folgende Dinge sind mir aufgefallen:
 - Den Begriff `Freigaben` finde ich nicht so passend, eher `Zugriff` ?
 - Auf einem grossen Screen ist das `?`-Symbol extrem weit weg
 - Im Readonly Modus hat man trotzdem das Gefühl man könne checkboxes aktivieren
 - Den Edit Modus kann ich gar nicht testen, scheint nicht zu funktionieren, angemeldet als manager 🤔  

@all4manu können es evtl. am nami gleich zusammen anschauen.

**Comment by phgross** [comment]
Fachliches Review: 
 - Sharing Form erscheint und zeigt die aktuellen Zugriffsberechtigungen korrekt an.
 - Der Bearbeitungsmodus funktioniert nicht. Bsp. https://teamraum-lab.4teamwork.ch/workspaces/workspace-23/folder-5 als philippe.gross lässt sich keine Gruppe finden.

**Comment by jone** [comment]
- Die Rollen sind nicht auf Deutsch übersetzt. Erwartet: "Besitzer", "Admin", "Teammitglied", "Gast".

**Comment by jone** [comment]
Stufe Teamraum:
- Bearbeiten funktioniert nicht
- Übersetzungen der Rollen ist falsch

Stufe Ordner:
- Radio statt Checkbox: es sollte nur 1 Rolle pro Person ausgewählt werden können, da Teamraum-Rollen aufeinander aufbauen.
- Die vererbten Rollen sollten sichtbar sein. Allenfalls auch so, dass ich jemandem der auf Teamraum nur "Gast" hat, auf einem bestimmten Ordner "Teammitglied" haben kann. Eine "schwächere" Rolle kann ich aber nicht wählen, solange die Vererbung nicht unterbrochen ist.
- Ich kann Personen auswählen, die gar nicht im Teamraum sind. Dies verletzt die Spez.
- Macht es Sinn, `Angemeldete Benutzer` darzustellen?

Getestet mit:
- https://lab.onegovgever.ch/workspaces/workspace-33
- https://lab.onegovgever.ch/workspaces/workspace-33/folder-16
- `hugo.boss` / `zopemaster`

**Comment by njohner** [comment]
the backend on lab was not up to date and there was a bug in the `sharing` endpoint that did not work correctly when used in conjunction with `ftw.lawgiver` (see https://github.com/4teamwork/ftw.lawgiver/pull/95). With this the issues reported above are fixed:
Stufe Teamraum:
[x] Bearbeiten funktioniert nicht. 
[x] Übersetzungen der Rollen ist falsch

Stufe Ordner:
[x] Die vererbten Rollen sollten sichtbar sein. Allenfalls auch so, dass ich jemandem der auf Teamraum nur "Gast" hat, auf einem bestimmten Ordner "Teammitglied" haben kann. Eine "schwächere" Rolle kann ich aber nicht wählen, solange die Vererbung nicht unterbrochen ist.
[x] Ich kann Personen auswählen, die gar nicht im Teamraum sind. Dies verletzt die Spez.

There was also a bug, when the local roles inheritance is blocked on a workspace folder, that users with rights on the workspace could not be found and given rights to on the folder. This is fixed in https://github.com/4teamwork/opengever.core/pull/6117

For the last question (*Macht es Sinn, `Angemeldete Benutzer` darzustellen?*), this is only visible for managers and that is how it is in all of GEVER. I'd leave it as is for now.

**Comment by phgross** [comment]
Fachliches Review:

 - Müssten die Rollen nun nicht auch übersetzt sein? 
 - `Angemeldete Benutzer` wird immer noch dargestellt, aber nur für den Manager erachte ich nicht als kritisch.

**Comment by njohner** [comment]
Sorry, totally my bad. Seem lab was not up to date. So now translations should work. `Angemeldete Benutzer` is still there. I'd leave it for now.

**Comment by jone** [comment]
Wie am Review besprochen machen wir eine Folgestory mit einer neuen Spez und brechen diese ab.
