### ISSUE TITLE
OneOffixx Integration kompatibel machen mit neuer API Version 

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6044]
Harvest: https://extranet.4teamwork.ch/support/gever-st-gallen/tracker/885/view

Authentisierung funktioniert noch, andere API calls scheinen nicht mehr zu funktionieren. 

Muss auf SG-Server "getestet" werden.
Kommuikation mit Sevitec.
Wir rechnen mit minimalen Anpassungen am Endpoint.

**Comment by robertmuehsig** [comment]
Ich hab mit Herrn Buchberger gerade telefoniert und vermute das es folgende Änderungen bedarf (allerdings bin ich kein Phyton Entwickler)

https://github.com/robertmuehsig/opengever.core/commit/0e85c4c4436030e287e81cf7f4746dea287ea608

Vermutlicher Grund für die API Fehler:

Die Datasource Id wird evtl. nicht richtig gefunden. TenantInfo hatte früher ein Array an "TenantInfo"-Elementen zurückgegeben in dem ein Array an "Datasource"-Elemente drin war. Dieses übergeordnete Array gibt es nicht mehr. Die Rückgabe bei "TenantInfo" ist jetzt in dieser Form:

```
{
  "datasources": [
    {
      "name": "PRIMARY",
      "id": "afb5591b-cf28-438e-a07e-f739fc988ad3",
      "isPrimary": true,
      "_links": {
        "self": {
          "href": "https://..../webapi/api/v2/DatasourceInfo/afb5591b-cf28-438e-a07e-f739fc988ad3"
        }
      }
    },
    {
      "name": "ZZZZZZZ",
      "id": "cc968ba1-7dd2-4257-bbf2-41cb50791f33",
      "isPrimary": false,
      "_links": {
        "self": {
          "href": "https://.../webapi/api/v2/DatasourceInfo/cc968ba1-7dd2-4257-bbf2-41cb50791f33"
        }
      }
    },
    {
      "name": "YYYYYY",
      "id": "33b6d25e-d107-4e44-abab-0d9dbb68cdcd",
      "isPrimary": false,
      "_links": {
        "self": {
          "href": "https://.../webapi/api/v2/DatasourceInfo/33b6d25e-d107-4e44-abab-0d9dbb68cdcd"
        }
      }
    },
    {
      "name": "XXXXX",
      "id": "a35a66ba-96d0-4739-995b-4fccb5cbb3c7",
      "isPrimary": false,
      "_links": {
        "self": {
          "href": "https://.../webapi/api/v2/DatasourceInfo/a35a66ba-96d0-4739-995b-4fccb5cbb3c7"
        }
      }
    }
  ],
  "_links": {}
}
```

Ihr Code ist aktuell auch optimistisch, daher die "ToDos". In OneOffixx können mehrere Datasources definiert werden, eine ist jedoch stets mit `"isPrimary: true"` markiert. In der Theorie kann es aber "Prod" und "Test" z.B. auf einer Umgebung geben.

Ansonsten als Basis-URL nun immer `/api/v2/` anstelle von `/api/v1/` verwenden & als scope `oo_WebApi`.

**Comment by phgross** [comment]
Danke @robertmuehsig für den Hinweis. Hat sich bei der Repräsentation der Favoriten ebenfalls etwas verändert?

**Comment by robertmuehsig** [comment]
Eigentlich nicht - wenn allerdings keine korrekte DatasourceId gefunden wird, geht der Aufruf auch nicht.

Von meinem iPhone gesendet

Am 12.11.2019 um 17:46 schrieb Philippe Gross <notifications@github.com>:

﻿

Danke @robertmuehsig<https://github.com/robertmuehsig> für den Hinweis. Hat sich bei der Repräsentation der Favoriten ebenfalls etwas verändert?

**Comment by phgross** [comment]
Fachliches Review: 👍 

Gemäss Kunde ist die Integration so in Ordnung.
