### ISSUE TITLE
Retrieving Preview URL for Document History not working

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#6049]
When querying for a specific document version over the `@history` endpoint, we receive the wrong preview URL, i.e. always the URL for the current version.

### Example

1. GET request on `https://lab.onegovgever.ch/ordnungssystem/umwelt/wasserversorgung/allgemeines/dossier-109/document-595` returns

```
{
  ...
  "pdf_url": "https://lab.onegovgever.ch/YnVtYmxlYmVl/api/v3/resource/gever_lab/d00fd5b8d6ebc1ec4d2e9ec0a69a2b5245717e3a69c93b1a65e58fad5467c497/pdf?access_token=XdW3Dl3kgXzQV74H5zE3X66zwxnxpvyaN9LufSJNyQM%3D&bid=41LMhZAFTEW5yNXkhPV5Og"
}
```

2. GET request on `https://lab.onegovgever.ch/ordnungssystem/umwelt/wasserversorgung/allgemeines/dossier-109/document-595/@history/0` returns

```
{
  ...
  "pdf_url": "https://lab.onegovgever.ch/YnVtYmxlYmVl/api/v3/resource/gever_lab/d00fd5b8d6ebc1ec4d2e9ec0a69a2b5245717e3a69c93b1a65e58fad5467c497/pdf?access_token=XdW3Dl3kgXzQV74H5zE3X66zwxnxpvyaN9LufSJNyQM%3D&bid=3hAGMvlLTCWQQqjAwrnhCQ"
}
```

It looks to me that those two URL's should be different but only part of the `access_token` is different.

Issue in gever-ui: https://github.com/4teamwork/gever-ui/issues/634

**Comment by phgross** [comment]
Fachliches Review: 👍
