### ISSUE TITLE
Upgrade to ftw.testing 2.x

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#6064]
We should eventually upgrade to `ftw.testing = 2.x`.

For that, we need to fix all mock tests, which won't work anymore with the updated `MockTestCase` in `ftw.testing >= 2.x`.

See [Upgrading from ftw.testing 1.x to 2.0](https://github.com/4teamwork/ftw.testing#upgrading-from-ftw-testing-1-x-to-2-0) for _some_ guidance on what needs to be done.

**Comment by deiferni** [comment]
ported to jira.
