### ISSUE TITLE
Kein Favoriten-Menü trotz Favoriten Buttons

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#6094]
Im Team ist der Favoriten Knopf zwar sichtbar und funktioniert, aber es hat noch kein Menü für Favoriten. Z.Z. wird der Favorit im Gever-UI angezeigt.

<img src="https://user-images.githubusercontent.com/5048550/69808848-cd241400-11e8-11ea-804a-f8b5c214cd1a.png" width="250px" />

=> Müssen Favoriten von Gever und Teamraum getrennt gemanaged werden? D.h. Gever-UI zeigt nur Gever Favoriten und Teamraum zeigt nur Teamraum Favoriten?

**Comment by phgross** [comment]
Funktioniert nun.
