### ISSUE TITLE
ToDo Detail Ansicht: Kalender Widget funktioniert nicht richtig

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#6110]
2 Punkte:
- Klicken auf "Dezember 2019" schliesst das Widget
<img width="445" alt="Screen Shot 2019-12-04 at 13 57 07" src="https://user-images.githubusercontent.com/437933/70144354-08698b80-169e-11ea-8ccd-ed6e31cb514a.png">

- Ich kann das Datum nicht manuell eingeben. (Sollte wie beim Bearbeiten möglich sein)

**Comment by BlueSky9443** [comment]
on hold

**Comment by phgross** [comment]
Kann nicht reproduziert werden.
