### ISSUE TITLE
ToDo zuweisen mittels `@`

### ISSUE THREAD

**Issue by maethu** [4teamwork/opengever.core#6111]
Ein ToDo sollte direkt beim Hinzufügen auch einer Person zugeordnet werden können. 

So richtig cool wäre die Variante von Florin vorgeschlagen mittels `@` Symbol. 

Als minimal Variante würde es aber reichen, wenn das Auswahl-Feld ebenfalls direkt zur Verfügung stehen würde.

**Comment by BlueSky9443** [comment]
https://4teamwork.atlassian.net/browse/GEVER-88
