### ISSUE TITLE
Create script to remove versioned journal entries

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#6116]
Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`

Until recently, the journal entries from`ftw.journal` got versioned, and therefore multiplied, whenever a new version of a document was created.

This was suppressed in #5652, but existing peristent data structures still exist, and need to be cleaned up. These versioned journal entries are unnecessary because with our custom revert mechanism in GEVER, we only ever revert the blob, and actively discard all versioned metadata anyway.

We therefore need a script that removes these versioned journal entries from the version storage.

**Comment by jone** [comment]
Refinement:
- Script vorhanden (@lukasgraf bitte ergänzen)
- ggf. Memory-Optimierungen machen
- Anhand Daten Appenzell testen.

**Comment by lukasgraf** [comment]
WIP script to delete journal entries from historic versions is on a branch in `opengever.maintenance`:
https://github.com/4teamwork/opengever.maintenance/blob/lg-delete-journal-from-historic-versions/opengever/maintenance/scripts/delete_journal_from_historic_versions.py
