### ISSUE TITLE
unicode error in user-details view

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6119]
Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`

Seems there is a group with umlaut in fmh and that we do not handle that correctly in the `@user-details` view. See Sentry:

see https://sentry.4teamwork.ch/sentry/onegov-gever/issues/53093/

**Comment by deiferni** [comment]
sentry issue is gone. solved in the meantime.
