### ISSUE TITLE
Admin und OrgUnit Schema erweitern um Flag `hidden`

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6128]
_Harvest: ` [0.322.3 / 43] Projekt - Umsetzung OGIP 60 "Mandanten ausblenden"`_

Gemäss https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3838/document-32058

 - [ ] Schemas um Flag erweitern inkl. Upgradestep
 - [ ] ogds_service erweitern, so dass auch diese Informationen zugänglich ist

**Comment by jone** [comment]
@njohner ist das "ready for refinement"?

**Comment by phgross** [comment]
Review: 👍(durch die anderen Issues geprüft).
