### ISSUE TITLE
`Hidden` OrgUnits ignorieren bei Aufgaben-Auftragnehmer 

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6129]
_Harvest: ` [0.322.3 / 43] Projekt - Umsetzung OGIP 60 "Mandanten ausblenden"`_

Gemäss https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3838/document-32058

> **Auftragnehmer einer Aufgabe/Weiterleitung:**
> Benutzer von nicht sichtbaren Mandanten sollen bei der Auswahl nicht erscheinen. Technisch gesehen sind diese Benutzer aber nach wie vor valid und können so z.B. via API nach wie vor als Auftragnehmer einer Aufgabe verwendet werden.
Das gleiche gilt für Eingangskörbe von nicht sichtbaren Mandanten.

Probably a one liner in `opengever.ogds.base.OrgUnitsVocabularyFactory`

**Comment by jone** [comment]
@njohner ist das "ready for refinement"?

**Comment by phgross** [comment]
@njohner 
Fachliches Review:
 - Benutzer werden korrekt limitiert. Ich denke aber das gleich sollte auch für den Eingangskorb von hidden-org-units der Fall sein. Auf Dev ist aber `Eingangskorb: Steuerverwaltung` nach wie vor auswählbar.

**Comment by phgross** [comment]
Fachliches Review: 👍
