### ISSUE TITLE
Hidden `OrgUnits` im Hutwechsler nicht anbieten

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6130]
_Harvest: ` [0.322.3 / 43] Projekt - Umsetzung OGIP 60 "Mandanten ausblenden"`_

Gemäss https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3838/document-32058

> Nicht sichtbare Mandanten sollen auch im Amtswechsler (Hutwechsler) nicht erscheinen.

This will probably be resolved with https://github.com/4teamwork/opengever.core/issues/6129

**Comment by jone** [comment]
@njohner ist das "ready for refinement"?

**Comment by phgross** [comment]
Review: 👍 

Funktioniert wie gewünscht auf dev.
