### ISSUE TITLE
Hidden `OrgUnits` im AppSwitcher nicht anbieten

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6131]
_Harvest: ` [0.322.3 / 43] Projekt - Umsetzung OGIP 60 "Mandanten ausblenden"`_

Gemäss https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3838/document-32058

> Nicht sichtbare Mandanten sollen auch im Amtswechsler (Hutwechsler) nicht erscheinen.

Umsetzung müsste im neuen Portal: wird im neuen Portal enthalten sein und über die Schnittstelle verfügbar.

**Comment by jone** [comment]
@njohner ist das "ready for refinement"?

**Comment by njohner** [comment]
Yes, we just need the corresponding change in ianus.

**Comment by jone** [comment]
> For the new UI we just need the corresponding change in ianus. Apart from that yes, ready

I made an issue in Ianus: https://github.com/4teamwork/ianus/issues/54
Since we need to add the apps to the portal manually at the moment and it is only used for the app switcher, we could easily start by just not adding those gever clients att the moment.

**Comment by njohner** [comment]
So the change has been made in ianus. So I guess we can simply close this? Especially if the plan is to simply not add the apps in the portal, there is no real need to test it

**Comment by phgross** [comment]
Review: nicht notwendig.
