### ISSUE TITLE
Teamraum: Teilnehmer, Einladungen, Rollen

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6141]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

#### Personae
- Besitzer (Analog Dossier `responsible`, default: Creator)
- Rolle Admin
- Rolle Teammitglied
- Rolle Gast
- Site Administrator

#### Anforderungen
- Grundsätzlich ist ein Teamraum "geschlossen": nur berechtigte Teilnehmer sehen ihn.
- Jeder Teilnehmer hat nur eine Rolle von `Admin`, `Teilnehmer`, `Gast`.
- **Besitzer:**
  -  Kann vom Site Administrator geändert werden.
  - Wird in der Übersicht angezeigt.
  - Keine Aktivitäten / Berechtigungen
  - Kann (im Moment) nicht geändert werden (später vom Site Administrator).
- **Rolle Admin:** 
  - Besitzer ist immer auch Admin. / Mind. 1 Admin pro Teamraum.
  - Auf Teamraum:
    - Kann einladen (E-Mail).
    - Kann Einladungen löschen.
    - Kann Teilnehmer aus dem Raum entfernen.
    - Kann die Rolle anderer Teilnehmer ändern.
    - Kann eigene Rolle nicht ändern.
    - Kann sich nicht selber aussperren.
  - Auf Ordner:
     - Modus "Berechtigungen übernehmen"
       - Nur lesende Darstellung der Berechtigungen
     - Modus "Eigene Berechtigungen"
       - Kann Rollen auf Ordner definieren aus dem Set der Teilnehmer des Raumes (keine zusätzlichen Teilnehmer).
     - Kann sich nicht selber aussperren.
  - Kann Inhalte hinzufügen, bearbeiten, löschen.
- **Rolle Teammitglied:**
  - Kann Inhalte hinzufügen, bearbeiten, löschen
- **Rolle Gast:**
- **Alle Rollen:**
  - Sieht die Teilnehmer (Read Only) mit Rollen (auf Ordner und Teamraum).
  - Kann Inhalte lesen.
- **Site Administrator:**
  - ~~Kann den Besitzer des Raumes ändern. (späteres PBI)~~
  - ~~Kann bestehende Benutzer und Gruppen in Teamraum hinzufügen~~

#### Illustration

![image](https://user-images.githubusercontent.com/7469/70995483-ee35a180-20d0-11ea-95ec-b78d32df9cf2.png)

#### Abgrenzung
- Journalisierung ist abgegrenzt.

**Comment by deiferni** [comment]
Diskussion mit Manu, Vorschlag für Endpoints:

- @participants GET anpassen
- @invitations GET anpassen
- neue @actions endpoint actions: "Unterbruch Vererbung", "Neue Einladung"

```python
class TestParticipationGetForManu(IntegrationTestCase):

    @browsing
    def test_list_all_current_participants_and_invitations(self, browser):
        self.login(self.workspace_owner, browser)

        response = browser.open(
            self.workspace.absolute_url() + '/@participants',
            method='GET',
            headers=http_headers(),
        ).json

        self.assertItemsEqual(
            [
                {
                    u'@id': u'http://nohost/plone/workspaces/workspace-1/@participants/beatrice.schrodinger',
                    u'@type': u'virtual.participations.user',
                    u'is_editable': True,  # _ac_local_roles_block and "delegateRoles" permission
                    u'participant_fullname': u'Schr\xf6dinger B\xe9atrice (beatrice.schrodinger)',
                    u'role': {
                        'token': 'WorkspaceGuest',
                        'title': 'Guest',
                    },
                    u'participant_email': 'kathi.barfuss@gever.local',
                }
            ])



class TestInvitationGetForManu(IntegrationTestCase):

    @browsing
    def test_invitation_listing_for_a_workspace(self, browser):
        self.login(self.workspace_owner, browser)

        iid = getUtility(IInvitationStorage).add_invitation(
            self.workspace,
            self.regular_user.getProperty('email'),
            self.workspace_owner.getId(), 'WorkspaceGuest')

        response = browser.open(
            self.workspace.absolute_url() + '/@invitations',
            method='GET',
            headers=self.api_headers,
        ).json

        self.assertItemsEqual([
            {
                u'@id': u'http://nohost/plone/workspaces/workspace-1/@invitations/{}'.format(iid),
                u'@type': u'virtual.participations.invitation',
                u'inviter_fullname': u'Fr\xf6hlich G\xfcnther (gunther.frohlich)',
                u'participant_email': 'kathi.barfuss@gever.local',
                u'role': {
                    'token': 'WorkspaceGuest',
                    'title': 'Guest',
                },
                u'state': 'pending',
            }], response)
```

**Comment by deiferni** [comment]
reminder to self, we should update this issue with tasks from https://github.com/4teamwork/opengever.core/issues/5911#issuecomment-566139660

**Comment by all4manu** [comment]
Restschätzung: 5

**Comment by jone** [comment]
Ich teste das dann auf dev.teamraum.ch sobald verfügbar.

**Comment by jone** [comment]
Was wurde hier noch gemacht? Ist mir nicht klar.
Bitte mind. Diff am Review zeigen.

**Comment by jone** [comment]
@all4manu es steht noch "undefined" bei der Rollen auswahl. Können wir das noch korrigieren?

![Bildschirmfoto 2020-01-27 um 15.24.27.png](https://images.zenhubusercontent.com/5598fe764f7a08fbb7f39324/c37e8f2f-7f22-4c4e-bcad-0ddbffff928d)

**Comment by all4manu** [comment]
> Was wurde hier noch gemacht? Ist mir nicht klar.
> Bitte mind. Diff am Review zeigen.

@jone zur Info: Dies ist nur der Sammel-Issue für alle Teamraum Freigabe Issues. Das Diff ist der Issue #6167.

**Comment by jone** [comment]
👍
