### ISSUE TITLE
Teamraum Erstellung und Speicherung

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6154]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

PBI ist Teil des [OGIP 63 - Schnittstelle Teamraum und OneGov GEVER](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023) 

User Stories 
> * Als Sachbearbeiterin möchte ich zu einem Geschäftsdossier einen Teamraum eröffnen können, 
ich gewisse Dokumente zusammen mit Dritten erarbeiten kann.
> * Als Sachbearbeiter/In möchte ich sehen können, wenn zu einem Geschäft ein oder mehrere Teamräume eröffnet wurden,	damit ich mich auch über die Zusammenarbeit mit Dritten informieren kann.

> In aktiven Geschäftdossiers steht die Aktion «Teamraum eröffnen» zur Verfügung. Eine Erstellung auf Stufe Subdossier erachten wir nicht als sinnvoll und wird deshalb nicht angeboten. > Die Erstellung soll mehr stufig erfolgen:
> * Schritt 1: Teamraum erstellen, Formular mit Titel und Beschreibung.
> * Schritt 2 : Dokumente übertragen (siehe separate Beschreibung der Aktion im OGIP). Dieser Schritt ist optional und kann übersprungen werden. 

Todos:
 - [x] Erweitern von Dossier-GET mit Teamraum Information. (PR: https://github.com/4teamwork/opengever.core/pull/6250)
 - [x] Feature Flag (PR: https://github.com/4teamwork/opengever.core/pull/6241)
 - [x] API Endpoint für Erstellung und Speicherung des Teamraums (z.B. `@create-remote-workspace`) (PR: https://github.com/4teamwork/opengever.core/pull/6254)
 - [ ] Schutz mit Berechtigung (#6192)
 - [x] Formular für die Erstellung des Teamraums 
 - [x] Nach Erstellung weiterleitung auf Dokument-Reiter des GEVER-Dossiers, so dass man dann direkt Dokumente übertragen kann (andere Story).
- [x] Eigener Endpoint für `@linked-workspaces' (PR: https://github.com/4teamwork/opengever.core/pull/6265)
- [x] Error Handling wenn Teamraum-Installation nicht verfügbar ist. GEVER muss weiterhin verfügbar sein (siehe Diskussion in https://github.com/4teamwork/opengever.core/issues/6155) Vorschlag: Teamraum Auflistung in separatem Request. Vereinfacht Error Handling, Vereinfacht handling Timeout-Problematik. (PR: #6266 )

Abgrenzung:
 - ~Schritt 2: Dokumente übertragen wird in einem separaten PBI behandelt.~
 - Das übertragen von Dokumenten wurde aus dieser Story entfernt (ursprünglich als Wizard angedacht). Stattdessen leiten wir einfach auf das Dokumente-Tab des Dossiers weiter, wo man mittels #6156 die Dokumente übertragen kann. Ein hinweis wäre toll, ist aber komforstufe.

![x1](https://user-images.githubusercontent.com/7469/71903913-64c03f00-3165-11ea-81b1-20403d18d350.png)

**Comment by jone** [comment]
Refinement:
Da wir grundsätzlich noch keinen Wizard haben und die Auswahl von Items immer auch Probleme birgt (paginierung etc.) habe ich das Übertragen von Dokumenten aus dieser Story entfernt. Dies kann in einem folgeschritt über den Dokumente-Reiter gemacht werden. Daher leiten wir auch dort hin.
Überlegung: wir könnten dann ein Hinweis machen, z.B. Pfeil mit Hilfetext "übertragen sie hier Dokumente in den Teamraum" oder sowas. Ist aber hier in der Story noch nicht drin.

**Comment by elioschmutz** [comment]
remaining estimating time: 5 SP

**Comment by jone** [comment]
Gemäss Diskussion in https://github.com/4teamwork/opengever.core/issues/6155 muss hier auch berücksichtigt werden dass das GEVER-UI robust ist und nicht agrad abstürzt wenn der teamraum nicht erreichbar ist.

**Comment by elioschmutz** [comment]
@jone ist bereits in den Todos weiter oben ergänz 👍

**Comment by elioschmutz** [comment]
Zu besprechen mit @lukasgraf :

**Endpoint `@create-linked-workspace`**

Default response: JSON Repr. vom erstellten Teamraum.
Error Handling:

**Endpoint `@linked-workspaces`**

Default response: 
Error Handling:

**Sonstiges**

**Comment by njohner** [comment]
Just one comment/question. We also handle errors for the `@create-linked-workspace` endpoint right?

**Comment by elioschmutz** [comment]
Yes, this is a general error handling for all workspace-specific requests...

**Comment by jone** [comment]
Könnten wir beim Formular für den Teamraum den Titel des Dossiers als Default-Wert nehmen?
Wenn ich bereits ein Dossier in GEVER habe und dazu einen Teamraum erstellen will ist die Wahrscheinlichkeit hoch dass ich den gleichen oder einen ähnlichen Titel für den Teamraum verwende wie das Dossier schon hat.

**Comment by jone** [comment]
- [ ] Bitte noch Komma entfernen
```diff
- Der Teamraum wurde erfolgreich erstellt. Um Dokumente in den Teamraum zu kopieren, wechseln Sie bitte in den Dokumente-Tab und markieren Sie die gewünschten Dokumente.
+ Der Teamraum wurde erfolgreich erstellt. Um Dokumente in den Teamraum zu kopieren wechseln Sie bitte in den Dokumente-Tab und markieren Sie die gewünschten Dokumente.
```

**Comment by jone** [comment]
![Bildschirmfoto 2020-02-24 um 14.57.48.png](https://images.zenhubusercontent.com/5598fe764f7a08fbb7f39324/d446f47c-52ec-47aa-a97f-d6f46e5658ff)

**Comment by jone** [comment]
Wir sind noch etwas unsicher wegen der Komma-Regel, aber ich denke wir lassen es mal so. Könnten aber das Komma auch wieder reinmachen..
