### ISSUE TITLE
Darstellung von Teamräumen im Dossier

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6155]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

PBI ist Teil des [OGIP 63 - Schnittstelle Teamraum und OneGov GEVER](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023) 

User Stories 
> * Als Sachbearbeiter/In möchte ich sehen können, wenn zu einem Geschäft ein oder mehrere Teamräume eröffnet wurden,	damit ich mich auch über die Zusammenarbeit mit Dritten informieren kann.

> Für alle Benutzer soll jederzeit sichtbar sein, ob ein Geschäft zurzeit ebenfalls in einem oder mehreren Teamräumen bearbeitet wird. Deshalb sollen sie entweder in einem separaten Reiter «Teamräume» oder in der Dossier-Übersicht aufgelistet werden. 
Mit einem Klick auf den Titel soll ein Wechsel in den entsprechenden Teamraum möglich sein, sofern ich dazu berechtigt bin. Zudem stehen pro Teamraum die Aktionen «Dokumente übertra-gen», «Dokumente zurückführen», «Teamraum abschliessen» zur Verfügung.

**Comment by jone** [comment]
@all4manu ist das aus UI-Sicht genügend klar damit wirs im Refinement besprechen können?

**Comment by jone** [comment]
Annahme: Vocabulary der Räume ist bereits voorhanden.

**Comment by elioschmutz** [comment]
Kann auf dev.teamraum.ch getestet werden. Der Benutzer philippe.gross hat im Dossier https://dev.teamraum.ch/fd/ordnungssystem/fuehrung/kommunikation/allgemeines/dossier-1 einen verlinkten Arbeitsraum:

<img width="839" alt="Bildschirmfoto 2020-02-11 um 07 57 17" src="https://user-images.githubusercontent.com/557005/74216268-26f29100-4ca4-11ea-962a-48dc24f5b5e7.png">

**Comment by jone** [comment]
@elioschmutz wieso sehe ich den Teamraum als `hugo.boss` nicht?

**Comment by elioschmutz** [comment]
Weil der Benutzer wohl keine Berechtigung für den Teamraum hat...

**Comment by elioschmutz** [comment]
Er muss ein Teilnehmer sein.

**Comment by jone** [comment]
Ok. Das heisst wir haben eine Live-Schnittstelle. Was passiert wenn teamraum gewartet wird und nicht läuft? Kann ich dann GEVER noch benutzen?

**Comment by elioschmutz** [comment]
Nein, würde momentan einen Fehler raisen wenn auf das Dossier zugegriffen wird.

**Comment by jone** [comment]
Ok. Können wir den Fehler abfangen?
Ich habe mir keine Live-Schnittstelle vorgestellt. Wenn wir also mehr machen als bestellt muss das auch robust sein.

**Comment by elioschmutz** [comment]
🤔ok... ja, wir könnten bei einem Error einfach eine leere Liste zurück geben... erstmal...

**Comment by jone** [comment]
@elioschmutz Kannst du eine Rest-Schätzung machen für Varianten:
1) Leere Liste
2) Fehlermeldung für Benutzer ("Teamraum ist momentan nicht erreichbar.")
?

**Comment by elioschmutz** [comment]
Ja, kann ich gerne machen. Aber nach mir gehört dies nicht in diesen Issue. Dieser Issue behandelt das Anzeigen der verlinkten Teamräumen. Nach mir kommt dies in den Issue, wo der Store und die Endpoints umgesetzt werden müssen. Das wäre der Issue #6154 . Dieser ist jedoch allgemein noch WIP. Teile davon wurden bereits umgesetzt, aber noch nicht alles... wie siehst du das?

**Comment by jone** [comment]
@elioschmutz ah, ja, passt für mich. Kannst du die entsprechenden Issues updaten?

**Comment by jone** [comment]
Fehlerbehandlung wenn teamraum nicht erreichbar wird hier behandelt: https://github.com/4teamwork/opengever.core/issues/6154#issuecomment-584512561

Ich finde die Darstellung gut so ✅
