### ISSUE TITLE
(META) Dokumente übertragen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6156]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

> :warning: **Aufgesplittet:** Story wurde in #6197 und #6198 aufgesplittet.

Harvest: OGIP 63 Projekt (ist zurzeit noch nicht eröffnet)

PBI ist Teil des [OGIP 63 - Schnittstelle Teamraum und OneGov GEVER](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023) 

User Stories 
> * Als Sachbearbeiterin Sachbearbeiter/In möchte ich einzelne Dokumente in den Teamraum transferieren können, damit ich diese Dritten zur Verfügung stellen und evtl. mit ihnen weiterbearbeiten kann.

> Wie bereits in Schritt 2 der Teamraum Eröffnung soll es auch zu einem späteren Zeitpunkt mög-lich sein, GEVER Dokumente in den Teamraum zu übertragen. Dabei wird eine Kopie inkl. Meta-daten erstellt. Diese wird technisch nicht verlinkt, ein zurückführen von Änderungen als neue Version oder ähnliches ist deshalb nicht möglich. 
Es wird nur die aktuelle Version kopiert, frühere Versionen werden nicht übertragen. Sind aus-gewählte Dokumente zurzeit ausgecheckt wird der Benutzer darauf hingewiesen und die Über-tragung abgebrochen.

#### Todos
 - Aktion Dokumente übertragen bei bestehenden Teamraum => Backend #6156
 - ~Zusätzlicher Schritt bei der Teamraum Erstellung aus GEVER Dossier~
 - Neuer Endpoint (auf Dossier) für Auflistung der verknüpften Teamräume  => Backend #6156
 - API Endpoint für Dokumente Übertragung => Backend #6156
 - Schutz mit Berechtigung (#6192) => Backend #6156

#### Klärung
- Die Aktion soll in einer Art und Weise umgesetzt werden, dass zuerst die Dokumente ausgewählt werden, die in einen Teamraum übertragen werden sollen, und dann die Aktion.
- Geschätzt wird eine serielle Erstellung der Dokumente durch das Frontend (7. Dokumente - 7 requests des Frontends an GEVER die proxied werden auf Teamraum).
- Aktion "Dokument in Teamraum übertragen" auch darstellen wenn noch gar kein verknüpfter Tearaum vorhanden? Entscheid: Aktion wird nicht dargestellt, solange nicht mindestens 1 Teamraum existiert (unter Berücksichtigung der Security).

#### Offene Fragen
- Wie wird dem User der Ziel-Teamraum (Auswahl der Destination) präsentiert?

**Comment by jone** [comment]
Story aufsplitten in Frontend und Backend und nochmals refinen lassen.

**Comment by jone** [comment]
Refinement:
Die hohe und diverse Schätzung hat gezeigt dass Unklarheiten bestehen.
Daher wird die Story in Backend (#6197) und Frontend (#6198) **aufgesplittet**.
