### ISSUE TITLE
Dokumente zurückführen

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6157]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

PBI ist Teil des [OGIP 63 - Schnittstelle Teamraum und OneGov GEVER](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023) 

User Stories 
> * Als Sachbearbeiter/In möchte ich Dokumente aus dem Teamraum ins GEVER Dossier übertragen können, damit ich geschäftsrelevante Dokumente, welche im Teamraum erarbeitet wurden, im GEVER ablegen kann.

> Ähnlich wie beim übertragen von Dokumenten in den Teamraum, soll auch das zurückführen von geschäftsrelevanten Dokumenten ermöglicht werden. Dabei werden Dokumente inkl. deren Metadaten ins GEVER kopiert und als neue, separate Dokumente erstellt. Es wird nur die aktuelle Version des Teamraum Dokuments kopiert, frühere Versionen werden nicht übertragen. Sind ausgewählte Dokumente zurzeit in Bearbeitung, wird der Benutzer darauf hingewiesen und die Übertragung abgebrochen.

Todos:
 - API Endpoint Liste von Teamraum-Dokumente
 - Aktion Dokumente zurückführen bei bestehenden Teamraum
 - API Endpoint für Dokumente Zurückführung
 - Schutz mit Berechtigung (#6192)

**Comment by jone** [comment]
Funktioniert wie erwartet.
