### ISSUE TITLE
Dossier/Teamraum Abschluss

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#6158]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

PBI ist Teil des [OGIP 63 - Schnittstelle Teamraum und OneGov GEVER](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023) 

User Stories 
> * Federführende/r möchte ich auf offene Teamraum hingewiesen werden, wenn ich ein Dossier abschliessen will, damit ich prüfen kann, ob noch geschäftsrelevante Dokumente im Teamraum abgelegt sind, und ich ggf.   die Teamräume abschliessen kann.
> * Als Sachbearbeiter/In möchte ich ein Teamraum abschliessen können, wenn die Projektphase (Zusammenarbeit mit Dritten) beendet ist bzw. der Teamraum nicht mehr benötigt wird.

Todos:
 - Weitere Dossierabschluss Regel
 - Teamraum Status aktiv/abgeschlossen

**Comment by jone** [comment]
Zu klären: teamraum workflow ist anscheinend noch nicht implementiert.

**Comment by jone** [comment]
Diskussion:
1. Ich bin der Meinung dass der Abschluss des _teamraum_s ein teamraum Problem ist, nicht ein Schnittstellen Problem. Resp. man kann m.E. nicht darauf eingehen ob es ein GEVER Dossier gibt.
2. m.E. muss die Dossier-Abschluss-Regeln der Status der Teamräume nicht prüfen sondern einfach darauf hinweisen dass es Teamräume sind.

**Comment by jone** [comment]
In Absprache mit Christoph nehmen wir das raus.
Der Teamraum-Abschluss wird in einem separaten Teamraum PBI behandelt.
