### ISSUE TITLE
GEVER Walenstadt - Wechsler Frontend

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#6162]
Auf walenstadt.onegovgever.ch scheint der Wechsel zum Frontend nicht korrekt zu funktionieren. Kunde meldet endlos drehend Schlaufe in allen Bereichen. Aktuell kann Kevin Mollet gar nicht auf die neue Umgebung zugreifen. 
4tw kann auch nicht via Zopemaster auf Frontend-Ansicht Walenstadt zugreifen. 
Bitte dringend anschauen.

**Comment by Suweber** [comment]
Bei anderen Saas-Kunden kann die Frontend-Ansicht problemlos angezeigt werden.

**Comment by deiferni** [comment]
Vorerst behoben, siehe https://github.com/4teamwork/gever-ui/issues/805.
