### ISSUE TITLE
Teamraum Anpassung Teilnehmer @participations Endpoint

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#6166]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

Aus

- **Rolle Admin:** 
  - Besitzer ist immer auch Admin. / Mind. 1 Admin pro Teamraum.
  - Auf Teamraum:
    - Kann einladen (E-Mail).
    - Kann Einladungen löschen.
    - Kann Teilnehmer aus dem Raum entfernen.
    - Kann die Rolle anderer Teilnehmer ändern.
    - Kann eigene Rolle nicht ändern.
    - Kann sich nicht selber aussperren.

Umsetzung vorerst:
- [x] `DELETE` auf `@parcipations` endpoint erlauben für `Delegate WorkspaceAdmin role`
- [x] im `DELETE` verhindern, dass Admin sich selber löscht
- [x] `PATCH` auf `@parcipations` endpoint erlauben für `Delegate WorkspaceAdmin role`, nur Rolle anpassbar
- [x] im `PATCH` verhindern, dass Admin eigene Rolle ändern kann und sich so aussperrt, `is_editable` auf `False`

**Comment by deiferni** [comment]
everything mentioned here seems to be already implemented 🤔 

![good_news](https://user-images.githubusercontent.com/736583/71590487-f78b2900-2b28-11ea-8d18-2c7048c1b7de.gif)

**Comment by all4manu** [comment]
@deiferni not quite sure if really quite everything works. A `DELETE` to `http://localhost:8081/fd/workspaces/workspace-4/@participations/umlaut.peter` returns `204 No Content` but the user is not removed.

Is it me, or is something not working?
