### ISSUE TITLE
Teamraum-Ordner Anpassung Teilnehmer @participations Endpoint 

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#6167]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

Aus

- **Rolle Admin:** 
  - Besitzer ist immer auch Admin. / Mind. 1 Admin pro Teamraum.

  - Auf Ordner:
     - Modus "Berechtigungen übernehmen"
       - Nur lesende Darstellung der Berechtigungen
     - Modus "Eigene Berechtigungen"
       - Kann Rollen auf Ordner definieren aus dem Set der Teilnehmer des Raumes (keine zusätzlichen Teilnehmer).

Umsetzung vorerst:
- [x]  Alle Anpassungen von https://github.com/4teamwork/opengever.core/issues/6166 sollen auch für den Ordner verfügbar sein, falls Vererbung unterbrochen. Also `DELETE` und `PATCH` endpoints.
- [x] Falls Vererbung nicht unterbrochen, Read-Only Darstellung der Rollen analog Parent.
- [x] Separate action für Vererbung Unterbrechen, Unterbruch Vererbung aufheben
- [x] Vererbung unterbrechen über `POST` an separaten Endpoint (`@role_inheritance`), geschützt durch `Delegate WorkspaceAdmin role`, payload z.B.: (erledigt durch: https://github.com/4teamwork/opengever.core/pull/6190)
```
{'blocked': True}
```
- [x] ~Bei Unterbruch Vererbung Bisherige-Rollen automatisch hinterlegen~
- [x] Beim `POST` auf `@role_inheritance` kann mittels Flag entschieden werden ob die Rollen vom übergeordneten Ordner kopiert werden oder nicht. Per default werden diese nicht kopiert.
  - [x] Werden die Rollen kopiert, so werden alle übergeorneten Rollen als lokale Rollen definiert
  - [x] Werden die Rollen nicht kopiert, so wird lediglich die Admin Rolle bzw. die Rolle vom User, welcher das `POST` durchführt, als lokale Rolle definiert
```json
{ "blocked": true, "copy_roles": true }
```
- [x] Bei entfernen Unterbruch Vererbung alle lokalen Rollen entfernen
- [x] `POST` für neue @participations soll nur bestehende Benutzer des Teamraums erlauben
- [x] Vokabular für erlaubte Benutzer, immer durch Parent weiter eingeschränkt
- [x] Wird eine Beteiligung entfernt, müssen diese Beteiligungen auch für alle selbst-gemanagte Unterordner gelöscht werden

**Comment by deiferni** [comment]
I have created a PR with https://github.com/4teamwork/opengever.core/pull/6190 that implements the `@role_inheritance` endpoint. The checkboxes are ticked off to reflect the current state of what is imlemented and what still needs to be done.

**Comment by jone** [comment]
Funktioniert aus meiner Sicht wie erwartet.
(Es funktioniert nicht bei älteren lokalen Rollen die über die vordere Implementation mit Rollen-Hint erfasst sind).
