### ISSUE TITLE
Build `@@invitations` / `@@invitations?uid` View

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#6169]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

Extract from https://github.com/4teamwork/opengever.core/issues/5911#issuecomment-561137361, Replaces leftover work from https://github.com/4teamwork/opengever.core/issues/5911.

Der Teamraum versendet eine E-Mail mit Einladungslink z.B. https://teamraum/@@invitations/:uid

Beim Aufruf des Einladungslinks sind folgende Fälle möglich:

1. Falls nicht eingeloggt und unbekannte E-Mail -> Redirect auf Registrierungsseite des Portals
    mit den Parameteren E-Mail, Redirect URL, Timestamp, Signatur
    z.B. https://portal/register?email=<email>&redirect_url=<url>&ts=<ts>&sig=<sig>&users_group=<users_group>
    Unter `users_group` soll die user-gruppe der OrgUnit von Teamraum in der URL mitgegeben werden (am besten wahrscheinlich die volle DN).
    Die Form des Registrierungslinks muss mit dem Portal koordiniert werden. Den Lead hat das Portal. Siehe auch https://github.com/4teamwork/ianus/issues/2
 Das Portal erstellt den User im LDAP, das auch inTeamraum (GEVER) angebunden ist.

2. Falls nicht eingeloggt und E-Mail eines bekannten Benutzers -> Login
    Danach Fall 3.

3. Falls eingeloggt:
    - GEVER erstellt den Benutzer im OGDS
    - Einladung mit Benutzer verknüpfen und alle pendenten Einladungen anzeigen
    - Alle ausstehenden Einladungen (ohne recipient) mit der gleichen recipient_email mit dem Benutzer verknüpfen.
    Bei Annahme od. Ablehnung einer Einladung -> Einladung löschen

4. Unbekannte, abgelaufene Einladung -> 404

Registrierung beim Portal:
Nach der Registrierung hat der Benutzer eine gültige Session am Portal.
Es erfolgt ein Redirect zurück zum Teamraum auf die Redirect URL.

Redirect URL: z.B. Einladungslink mit Parameter login=1
Bei Aufruf der Redirect URL -> Login (2) -> Einladung mit Benutzer verknüpfen (3) 

Benutzererstellung:
- Das Portal erstellt den Benutzer in einem LDAP, das ebenfalls im Teamraum (GEVER) angebunden ist
- Der Teamraum (GEVER) erstellt den angegebenen Benutzer beim ersten Aufruf der redirect_url mit login=1 im OGDS
~Die Benutzer werden lokal durch das Authentisierungsplugin beim ersten Login erstellt.~
~Alternativ kann die lokale Benutzererstellung deaktiviert werden.~
~In diesem Fall werden die Benutzer über ein externes System (LDAP) eingebunden.~

Es müssen auf Teamraum (GEVER) Seite folgende Ansichten gebaut werden:

- `@@invitations` / `@@invitations?uid` Ansicht
  - Listet in der erste Variant pendente Einladungen des eingeloggten Benutzers auf
  - Listet in der zweiten Variante pendente Einladungen des Benutzers, plus über die E-Mail Addresse der referenzierten Einladung vernküpfte, pendente Einladungen.
  - Über diese View kann eine dieser Einladungen entweder aktzeptiert oder abgelehnt werden.
  - Akzeptieren: Dem Benutzer entspreche local roles auf dem referenzierten Teamraum zuweisen, dann Einladung löschen
  - Ablehnen: Einladung löschen.

- Einladungs-Mail versenden:
  - Nach dem Erstellen einer Einladung in Teamraum (GEVER) soll an den in der Einladung angegeben E-Mail Adresse ein Mail versendet werden, das den Kommentar der Einladung plus den Einladungs-Link enthält.

**Comment by jone** [comment]
Wie besprochen: da wegen Portal nicht einfach installierbar teste ich es nicht, dafür gibts das `demo`-Label.
