### ISSUE TITLE
GEVER sr-aargau.onegovgever.ch via Zopemaster nicht erreichbar

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#6172]
SR Aargau erkundigt sich nach dem Wechsler fürs neue Frontend. Es scheint nicht zu funktionieren (kein Zugriff). Gemäss P. Gross ist Beta jedoch aktiviert worden. Ich kann leider via Zopemaster nicht darauf zugreifen. Dreht unendlich. Hat evtl. einen Zusammenhang mit https://github.com/4teamwork/opengever.core/issues/6162, welcher vorerst gelöst wurde.

**Comment by deiferni** [comment]
Habe es kurz angeschaut, scheint zu klappen. Können es sonst nächste Woche kurz genauer anschauen.

**Comment by deiferni** [comment]
Heute besprochen. Vermutlich Edge. Schliesse issue vorerst, hoffe passt so.
