### ISSUE TITLE
Migration Arbeitsräume (Zug, Bern, Wetzikon) auf teamraum

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6174]
Arbeitsräume in der OneGov Box auf teamraum migrieren. Vorgehen (z.B. OGG Bundle) besprechen. Arbeitsräume verfügen aktuell über mehr Funktionen als der MVP (Version 1).

**Comment by BlueSky9443** [comment]
on hold
Zug will noch keine Migration

**Comment by phgross** [comment]
Wird in separaten JIRA EPICs behandelt.
