### ISSUE TITLE
RestAPI teamraum für weitere Geschäftsverwaltungen erweitern / optimieren

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6175]
teamraum soll auch für andere Geschäftsverwaltungen als OGG als Kollaborationserweiterung  und Rückführung von Dokumenten dienen. Akutelle Anforderung BVE mit AXIOMA.

Basis siehe Anforderungen [OGIP63](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023?SearchableText=ogip+63#overview

**Comment by BlueSky9443** [comment]
on hold

**Comment by phgross** [comment]
Die API ist öffentlich und steht auch anderen Integratoren (möglicher weise anderen GEVER Anbieter) zur Verfügung.
