### ISSUE TITLE
Workspace cleanup.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#6176]
We've committed some sins in the last few days. This ticket shall collect them all in case we want to repent:

- Documentation for workspaces api is no longer correct/does not exist.
  - accepting/declining invitations is described in https://docs.onegovgever.ch/dev-manual/api/workspace/workspace_invitations/
  - docs for `@invitations` seem to be missing
  - IMO naming is confusing at the moment, there is `@my-workspace-invitations`, `@invitations` and `@workspace-invitations`. i think not all of these endpoints are used any more. figure out what is used and what is obsolete, delete appropriately and update docs
- Remove leftovers of the first workspace implementation(s) which are still here. Also see https://github.com/4teamwork/opengever.core/issues/5815
  - Figure out what is actually used, drop unused things
  - **Discussion needed**: How to deal with maintainability, i.e. should we leave a very minimal old ui intact for `zopemaster` administrative tasks.
- **Discussion needed** Drop `workspace_owner` from test fixture and tests as IIRC the concept no longer exists. the owner is now an ordinary admin and no longer a special role.
- Drop `InvitationRoleAssignment` as it seems no longer in use with https://github.com/4teamwork/opengever.core/pull/6183

**Comment by jone** [comment]
@deiferni kannst du das fürs refinement vorbereiten? Bitte genau auflisten was gemacht werden muss.

**Comment by deiferni** [comment]
I have extracted https://github.com/4teamwork/opengever.core/issues/6346 from this issue
