### ISSUE TITLE
Teamraum: Dev-Installation mit neuem Portal

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6181]
Harvest: `[3.2.4 / 2] Projekt - teamraum 2019` - `Entwicklung`

#### Problematik
- https://dev.onegovgever.ch/ läuft mit dem alten Portal
- https://dev.onegovgever.ch/ soll weiterhin mit dem alten Portal laufen da unsere Kunden im Moment nur das alte Portal einsetzen und die Kompatibilität sichergestellt werden muss
- Teamraum-Einladungen benötigen das neue Portal, daher können wir die Funktionalität auf dev im Moment nicht testen

Siehe https://github.com/4teamwork/opengever.core/issues/6169

#### Vorschlag
- dev.teamraum.ch einrichten mit:
  - (Möglicherweise) einer GEVER Installation
  - Einer Teamraum-Installation
  - Einem Ianus-Portal
  - Dem neuen GEVER-Frontend für mindestens die Teamraum-Installation, bzw. auch die GEVER-Installation falls vorhanden

#### Abgrenzung

- Für die Installation sollten keine bestehenden GEVER-Inhalte entfernt werden

**Comment by njohner** [comment]
Extranet ticket for setup by operations: https://extranet.4teamwork.ch/betrieb/tracker/923

**Comment by jone** [comment]
#### Planning:
- **Probleme**:
  - Neues Portal + Neues Frontend funktioniert nicht mit mehreren Mandanten.
  - Aktuelles Setup ist kompliziert und kann nicht vom Team gewartet werden.
- **Massnahmen**:
  - interdisziplinäres Team wird zusammengestellt (1 GEVER Repräsentant, 1 Betrieb Repräsentant).
  - PO setzt das Team auf
- **Zielsetzung**:
  - dev.teamraum.ch: neues Portal, neues UI, 2 Mandanten (GEVER / Teamraum)
  - dev.onegovgever.ch: altes Portal, neues UI, 2 Mandanten (GEVER / GEVER)
  - Konzept beschreibt Architektur (wie, wieso)
  - Komplexität wird reduziert, so dass das Team (GEVER / Betrieb) dies selbständig warten können.
  - Dokumentation (Rewrite Rules etc.)
  - Weitere Massnahmen sind als Issue erfasst.

**Comment by jone** [comment]
Bumblebee funktioniert noch nicht als `hugo.boss` auf https://dev.teamraum.ch/tr/workspaces/workspace-2/document-2 (Neues UI).
Ich vermute dass das Bumblebee-Feature-Flag nicht aktiviert wurde.

**Comment by jone** [comment]
- [ ] Die Einladung funktioniert noch nicht:
https://sentry.4teamwork.ch/sentry/onegov-gever/issues/59218/
`Workspace installation can only have a single enabled org_unit`

- [ ] Ist es möglich, den Absender der Einladungs-Mails von `OneGov GEVER` nach `teamraum` zu ändern?

**Comment by njohner** [comment]
- [ ] Ist es möglich, den Absender der Einladungs-Mails von OneGov GEVER nach teamraum zu ändern? We could overwrite the mailer for workspaces (we actually already do): https://github.com/4teamwork/opengever.core/blob/master/opengever/activity/mailer.py#L91-L93

**Comment by BlueSky9443** [comment]
Bitte Browsertab auf teamraum® anpassen
![image](https://user-images.githubusercontent.com/56879539/74159426-139be300-4c1c-11ea-8b64-5800ace8b200.png)

**Comment by BlueSky9443** [comment]
Beim ersten Mal dev.teamraum.ch starten kam die Meldung "Seit über 10 Jahren gibt es die alte GEVER-Oberfläche". Könnten wir für teamraum weglassen.

**Comment by BlueSky9443** [comment]
Accept: https://dev.teamraum.ch/tr/workspaces/workspace-3/@@my-invitations/accept?invitation=eyJpaWQiOiI3OGM0YzY0NzQzMzQ0MGM2OTA5YjNjNzBjMWIwNmE4YSJ9.XkFtJw.-im-sjCvK3iK3aQ77SOVwT6RGMw

Dieser Link führt zu 
![image](https://user-images.githubusercontent.com/56879539/74160141-3bd81180-4c1d-11ea-9f2e-2c6c2f14ae73.png)

es dreht immer noch.

**Comment by njohner** [comment]
The frontend somehow makes a request to https://dev.teamraum.ch/@config instead of something like https://dev.teamraum.ch/tr/@config .

**Comment by lukasgraf** [comment]
Bumblebee-Problem wurde durch `PreserveProxyHost On` in der VHost-Config verursacht: Dies wird mit https://git.4teamwork.ch/misc/puppet/merge_requests/200 korrigiert (kann aus meiner Sicht gemerged werden).

**Comment by all4manu** [comment]
Die Rewrite Rule für @@my-invitations war falsch und ist nun für dev.teamraum.ch korrigiert. 1x erfolgreich getestet.

**Comment by all4manu** [comment]
Wenn der User neu registriert werden muss, gibt es z.Z. noch einen Fehler beim Erstellen. Gemäss Buchi sei ev. das LDAP falsch angebunden:

<img src="https://user-images.githubusercontent.com/5048550/74319813-dd777400-4d7f-11ea-88e7-8616b8a21e7d.png" width="300px" />

**Comment by jone** [comment]
> Wenn der User neu registriert werden muss, gibt es z.Z. noch einen Fehler beim Erstellen. Gemäss Buchi sei ev. das LDAP falsch angebunden:

Heisst das Buchi löst das Problem? Er ist ja PO Portal 🤔

**Comment by lukasgraf** [comment]
Bumblebee funktioniert nun auf `dev.teamraum.ch`. Gab zwei Gründe dass es nicht funktioniert:
- War gar nicht aktiviert
- Proxy-Regeln im VHost waren falsch (siehe https://git.4teamwork.ch/misc/puppet/merge_requests/200)

Es klappt es (getestet auf `fd` und `tr`, altes und neues UI, für existierende und neue Dokumente).

**Comment by lukasgraf** [comment]
Konnte das Problem mit dem Portal ebenfalls noch beheben - die Konfiguration des registration backend's hat gefehlt.

Folgende drei Zeilen mussten im `.env` des Portals hinzugefügt werden (danach `touch tmp/restart.txt` um es neu zu starten):

```
DJANGO_AUTH_REGISTRATION_BACKEND=LDAPRegistrationBackend
DJANGO_AUTH_LDAP_USER_OBJECTCLASS=top,person,organizationalPerson,inetUser,inetOrgPerson
DJANGO_AUTH_LDAP_GROUP_MEMBER_ATTR=uniqueMember
```

**Comment by lukasgraf** [comment]
@jone aus meiner Sicht funktionieren jetzt die beiden Punkte (Bumblebee + Registrierung). Magst Du nochmals ein Review machen?

**Comment by BlueSky9443** [comment]
Bin ich denn schon drin! Es funktioniert! Congrats!

**Comment by jone** [comment]
✅ Jetzt funktioniert die Installation aus meiner Sicht 🎉 Da @BlueSky9443 auch schon erfolgreich getestet hat schliesse ich das PBI.
