### ISSUE TITLE
Querying @solrsearch endpoint returns error

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#6184]
_Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

#### Steps to reproduce

Send GET request as follows:

```
http://localhost:8081/fd/@solrsearch?start=0&rows=25&q=gever&fl=%40id%2C%40type%2Ctitle%2Csnippets%2Cbumblebee_checksum%2Cpreview_image_url%2Cchecked_out%2Cfilename%2Ccontaining_dossier&fq=&hl=on&facet=on&facet.field:list=portal_type
```

#### Expected result

"Normal" response with search result.

#### Actual result

Server returns `500 Internal Server Error` with body

```
{
  "message": "'OGSolrDocument' object has no attribute 'UID'", 
  "type": "AttributeError"
}
```

UI Issue: https://github.com/4teamwork/gever-ui/issues/828.

**Comment by njohner** [comment]
The issue is that snippets require the UID on the solr document.
Draft PR: https://github.com/4teamwork/opengever.core/pull/6216

**Comment by jone** [comment]
Funktioniert auf lab.
