### ISSUE TITLE
Deployment 2019.6 4tw

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6186]
- Backports auf 2019.6
- Release 2019.6 erstellen
- Deployen auf rot und gelb
- Deployen 4tw
  - inkl. Solr migration von 7 auf 8

**Comment by lukasgraf** [comment]
### Stand
- Backports auf `2019.6` sind erstellt  
- Release `2019.6` ist erstellt
- Release `2019.6` mit Upgrade von Solr 7 auf 8 wurde erfolgreich auf auf GELB eingespielt (nach [kleineren Fixes](https://github.com/4teamwork/opengever-deployments/pull/34))
- PR für Bump von `opengever.ftw` auf 2019.6 ist erstellt, und kann deployed werden: 4teamwork/opengever.ftw#100

### Verbleibend
- 4teamwork/opengever.ftw#100 mergen und deployen

**Comment by lukasgraf** [comment]
Release `2019.6` wurde erfolgreich auf 4tw GEVER deployed, und das Upgrade von Solr 7.x auf 8.4 verlief problemlos.
