### ISSUE TITLE
Analyse: was ist notwendig für Teamraum Standalone Installation?

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6187]
Ziel: Abklären, was alles notwendig ist für eine Standalone Teamraum Installation.
Themen wie Ordnungssystem, Kontakte OGDS, etc.

Lieferobjekt: Liste von empfohlenen Massnahmen / PBIs.

**Comment by BlueSky9443** [comment]
https://4teamwork.atlassian.net/browse/GEVER-47
