### ISSUE TITLE
Security für Schnittstelle GEVER / teamraum

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6192]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

### Gist
- Auf Seite GEVER neue Berechtigung zum Benutzer der Schnittstelle
- Auf Seite GEVER neue Rolle zur Berechtigung
- Standardmässig nicht vergeben (allenfalls aber für Dev)
- Alle Schnittstellen auf Seite GEVER schützen

### Auszug aus OGIP
> #### 5.8.1	Authentisierung
> Die Kommunikation zwischen GEVER und teamraum wird immer von Seite GEVER her aufge-baut und erfolgt über HTTP. Für die Authentisierung dieser Verbindung wird ein Service-Benutzer mit einem API-Token auf Seite teamraum eingerichtet. Dieses API-Token wird dann auf Seite GEVER konfiguriert. Die Verbindung wird mit diesem API-Token aufgebaut und anschlies-send wird mit dem «Impersonate» Feature auf Seite teamraum auf die Security des im Moment angemeldeten Benutzers gewechselt. Das heisst dass einerseits vorerst Aktionen über die Schnittstelle ausgelöst werden können, die durch einen realen Benutzer ausgelöst werden. An-dererseits heisst das, das Benutzer, die die Schnittstelle benutzen, auf beiden Systemen (GEVER und teamraum) den gleichen Benutzer haben müssen mit entsprechender Berechtigung.
> #### 5.8.2	GEVER Berechtigung
> Auf Seite GEVER wird die Benutzung der Schnittstelle GEVER <> teamraum mittels einer Be-rechtigung und einer dazugehörigen Rolle geschützt. Standardmässig haben Benutzer diese Rolle nicht, sie wird entweder über das LDAP- oder AD-Plugin an alle Benutzer vergeben (analog «Member») oder aber über eine Gruppe einem bestimmten Benutzerkreis vergeben. Es ist wich-tig, dass das Recht, Dokumente aus dem GEVER zu exportieren kontrolliert vergeben werden kann.
> #### 5.8.3	Teamraum Berechtigung
> Für die Schnittstelle wird auf Seite teamraum keine spezifische Berechtigung eingeführt: es gel-ten die gleichen Berechtigungen, wie wenn der Benutzer die Aktion manuell übers UI durchführen würde.
>

**Comment by jone** [comment]
@lukasgraf ich habe im OGIP 63 das Thema Security ergänzt. Könntest du mir Feedback geben 1. ob das so sinnvoll ist aus technischer Sicht und 2. was es noch benötigt damit wir "Ready for planning" sind? Merci!

**Comment by lukasgraf** [comment]
@jone tiptop, passt so für mich 👍 Aus meiner Sicht `ready for planning`.

**Comment by jone** [comment]
Merci für die Einschätzung!

**Comment by njohner** [comment]
I'd say remaining 0.5

**Comment by jone** [comment]
Da technisch ist das schwierig für mich als PO dies abschliessend zu reviewen. Daher ist das für mich so erledigt.
