### ISSUE TITLE
Testumgebung Schnittstelle auf dev.teamraum.ch

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6196]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

Mit #6181 wurde dev.teamraum.com eingerichtet. Mit OGIP 63 wird eine Schnittstelle zwischen GEVER und Teamraum implementiert. Die Schnittstelle soll auf dev.teamraum.ch getestet werden können, daher muss ein GEVER in die Teamraum-Umgebung installiert werden (bislang nicht Teil von #6181).

Todo:
- Installation GEVER auf dev.teamraum.ch

**Comment by elioschmutz** [comment]
Wurde bereits durch #6205 konfiguriert.

**Comment by jone** [comment]
Als `hugo.boss` ist unter https://dev.teamraum.ch/fd/ordnungssystem/raumplanung-bau-und-verkehr/mobilitaet/velo-und-fussverkehr/dossier-22 der Button "Teamraum hinzufügen" ausgegraut.
Müsste der Hugo noch eine Rolle erhalten?

**Comment by elioschmutz** [comment]
@jone nein, das Feature kommt erst mit einem späteren PR. Dieser Issue zeigt nur, dass die Verbindung funktioniert... 

Testen mit `philippe.gross` mit dem Dossier https://dev.teamraum.ch/fd/ordnungssystem/fuehrung/kommunikation/allgemeines/dossier-1

**Comment by jone** [comment]
Ok. Ich denke am besten warte ich hier noch mit testen.

**Comment by jone** [comment]
Schnittstelle auf dev funktioniert; im Rahmen von #6154 getestet.
