### ISSUE TITLE
Dokumente übertragen (Backend)

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6197]
_Harvest: `[3.2.2.5 / 59] OGIP 63 - Schnittstelle Teamraum / GEVER` - `Entwicklung`_

Gesplittet von #6156 in Backend und Frontend

_**Nur BACKEND in diesem Issue**_

PBI ist Teil des [OGIP 63 - Schnittstelle Teamraum und OneGov GEVER](https://gever.4teamwork.ch/ordnungssystem/3/2/2/5/dossier-3982/document-33023) 

User Stories 
> * Als Sachbearbeiterin Sachbearbeiter/In möchte ich einzelne Dokumente in den Teamraum transferieren können, damit ich diese Dritten zur Verfügung stellen und evtl. mit ihnen weiterbearbeiten kann.

Es soll möglich sein, GEVER Dokumente in den Teamraum zu übertragen. Dabei wird eine Kopie inkl. Meta-daten erstellt. Diese wird technisch nicht verlinkt, ein zurückführen von Änderungen als neue Version oder ähnliches ist deshalb nicht möglich. 
Es wird nur die aktuelle Version kopiert, frühere Versionen werden nicht übertragen. Sind aus-gewählte Dokumente zurzeit ausgecheckt wird der Benutzer darauf hingewiesen und die Über-tragung abgebrochen.

#### Todos
 - Aktion Dokumente übertragen bei bestehenden Teamraum
 - action in new category `folder_actions` for example, so that the action is only for the new UI.
 - ~Neuer Endpoint (auf Dossier) für Auflistung der verknüpften Teamräume~
 - API Endpoint für Dokumente Übertragung
 - ~Schutz mit Berechtigung (#6192)~

Auf Seite des GEVER-Backends muss ein neuer REST API Endpoint gebaut werden, der folgendes macht:

- Name: `@copy-documents-to-workspace`
- Registriert auf: Dossiers

- Erwartet folgende Parameter:
  - Eine Referenz auf den Ziel-Teamraum (muss im Storage für die verlinkten Teamräume irgendwie auflösbar sein)
  - Eine Referenz auf ein Dokument im entsprechenden Dossiers (Referenz könnte z.B. ein Pfad sein, oder eine UID)

- Prüft die Parameter wie folgt:
  - Der referenzierte Teamraum muss bereits mit diesem Dossier verlinkt sein
  - Das referenzierte Dokument muss:
    - lesbar sein (existieren, Benutzer hat View-Permission)
    - darf nicht ausgecheckt sein

- Der Endpoint tritt nachher als TUS-Client gegenüber dem Teamraum auf, und lädt das Dokument hoch
  (Als Beispiel für TUS-Client können die [Tests in plone.restapi angeschaut werden](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/tests/test_tus.py), oder auch die [Implementierung im opengever.apiclient](https://github.com/4teamwork/opengever.apiclient/blob/f9fb52ff14d02b5b94a20015d62daee5495c0564/opengever/apiclient/client.py#L85-L116))

- Nach dem Upload gibt der Endpoint Informationen über den Erfolg oder Misserfolg des Uploads zurück.

#### Klärung
- Geschätzt wird eine serielle Erstellung der Dokumente durch das Frontend (7. Dokumente - 7 requests des Frontends an GEVER die proxied werden auf Teamraum).

**Comment by jone** [comment]
@lukasgraf könntest du von Seite Backend her die Story ergänzen damit wir sie besser Schätzen können?

Hinweis: wir haben den TUS-Upload bereits implementiert: https://github.com/4teamwork/opengever.apiclient/blob/f9fb52ff14d02b5b94a20015d62daee5495c0564/opengever/apiclient/client.py#L85-L116

Mich interessiert ob wir es auch so machen können und wenn nicht wieso nicht resp. was wir mit einer anderen Variante gewinnen.

Merci für deine Einschätzung!

**Comment by lukasgraf** [comment]
@jone hab die Story ergänzt (neuer Abschnitt im Bereich "Todos"). Vorerst mal hohe Flughöhe, aber sollte zum Schätzen reichen denke ich.

**Comment by elioschmutz** [comment]
# Implementation

- Endpoint-Name: `@copy-document-to-workspace`
- Request-Method: `POST`
- Permission: `View` => Der Benutzer muss auf dem Teamraum Dokumente hinzufügen können. Auf Seite GEVER reicht jedoch die `View` Berechtigung
- Verfügbar für: Dossiers und Subdossiers. Das Subdossier verwendet das Hauptdossier für die verfügbaren Arbeitsräume
- Parameter: 
  - `workspace_uid`: UID eines Workspaces
    - muss mit dem aktuellen Dossier verlinkt sein
  - `document_uid`: UID eines Dokuments, welches kopiert werden soll
    - darf nicht ausgecheckt sein
    - muss ich innerhalb des Hauptdossiers oder eines seiner Subdossier befinden
    - der Benutzer benötigt `View` Berechtigung auf dem Dokument
- Response bei Erfolg: 200 OK mit dem erstellen Dokument als JSON
- Response bei Fehler: Gem. aktuellem Error-Handling wird ein 502 Bad Gateway mit allen Details zum Service-Fehler zurückgegeben.
- Neue `folder_buttons` action: `copy_documents_to_workspace`

**Offene Frage:** der `@tus-upload` Endpoint von der Plone REST-API erlaubt es nicht, zusätzliche Metadaten wie z.B: Titel oder Beschreibung direkt hinzuzufügen. Wir müssen somit einen weiteren Request auf das erstellte Dokument ausführen um die Metadaten zu Updaten. Das heist, wir machen 4 Requests für das Erstellen eines Dokuments. Wie soll hier das Error-Handling implementiert werden, falls dabei etwas schief geht? Soll das erstellte Dokument wieder gelöscht werden? Oder soll einfach der Fehler zurückgegeben werden? Das Interaktionsdiagramm soll das veranschaulichen.

## Übersicht der neuen Implemenation
![Main](https://user-images.githubusercontent.com/557005/74523311-27499100-4f1d-11ea-8a78-192e5bf36dde.jpg)

## Interaktionsdiagramm
![Copy Documents dto Workspace](https://user-images.githubusercontent.com/557005/74525796-4bf43780-4f22-11ea-98f0-274d4fb13ad4.jpg)

@lukasgraf @njohner @deiferni: Bitte überprüft mein Konzept. Ich wäre froh, wenn jemand meine Frage betr. Error-Handling beantworten könnte. Danke euch!

**Comment by lukasgraf** [comment]
@elioschmutz ich würde nichts rückgängig machen oder löschen. Also nicht versuchen, Transaktionalität herzustellen, wo keine ist.

Stattdessen würde ich in der Response den Fehler zu zurückgeben, dass klar ist, ob Request 1,2,3 oder 4 gescheitert ist, und wie genau. Wenn ein Fehler auftritt bei einem dieser Requests, würde ich das auch nach Sentry loggen - dann können wir ggf. hinterlassene Daten von Hand korrigieren.

**Comment by jone** [comment]
✅ Funktioniert aus meiner Sicht auf dev.teamraum.ch wie erwünscht. Fehlerverhalten konnte ich nicht testen; ich gehe davon aus dass dies in der Entwicklung entsprechend sorgfältig gemacht wurde.
