### ISSUE TITLE
Neues Feld filing_no in Solr-Schema hinzufügen

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#6203]
Harvest: `[0.220.1 / 72] Projekt - Umsetzung Modul Enterprise Search SOLR OneGov GEVER Kt. Zug`

Bei Installationen mit aktiviertem `IFilingNumber` behavior (ZG) ist es möglich, in der TabbedView auch nach `filing_no` zu sortieren.

Dies führt dazu, dass auch queries an Solr geschickt werden, die z.B. nach `filing_no` sortieren. Dazu muss dieses Feld in Solr existieren, sonst gibt es einen Fehler.

(Siehe https://basecamp.com/2768704/projects/14549453/todos/408873015)

### Steps to reproduce

- Auf einer Installation mit aktiviertem `IFilingNumber` behavior in einer Dossier-Auflistung nach Ablagenummer sortieren
- In der TabbedView Filter-Box nach einem Begriff filtern

---

Dementsprechend muss `filing_no` als Feld in's Solr-Schema aufgenommen werden.

Gemäss Besprechung mit @buchi müsste das aus unserer Sicht funktionieren, dieses Feld in das Standard-Schema in `opengever.core` aufzunehmen. Bei Installationen wo es nicht verwendet wird, wird es halt nicht befüllt.

Für Installationen welche aber das `IFilingNumber` behavior aktiviert haben (ZG), und Solr bereits installiert wurde zu einem Zeitpunkt wo das Feld noch nicht im Schema war, muss das Feld für die entsprechenden Objekte reindexed werden (atomic update).

Diese Änderung muss nach dem merge auf den `2019.6-stable` branch backported werden.

**Comment by all4manu** [comment]
#### Abgrenzung
RIS Installationen sollen nicht aktualisiert werden.

**Comment by lukasgraf** [comment]
Umgesetzt, backported, auf Zug ROT aktualisiert, `filing_no` field reindexed und getestet - funktioniert aus meiner Sicht.
