### ISSUE TITLE
API Language inconsistent

### ISSUE THREAD

**Issue by all4manu** [4teamwork/opengever.core#6210]
Calling the backend with 'fr-ch' does not always return the results in French.

#### To reproduce
(Use own Authorization header)

On the local dev machine it is working as expected:
```bash
curl --request GET 'http://localhost:8081/fd/ordnungssystem/bevoelkerung-und-sicherheit/einwohnerkontrolle/dossier-43/@schema/opengever.dossier.businesscasedossier' \
--header 'Accept: application/json' \
--header 'Authorization: <auth>' \
--cookie 'I18N_LANGUAGE=fr-ch'
```

On lab it returns the data in German:
```bash
curl --request GET 'https://lab.onegovgever.ch/ordnungssystem/umwelt/wasserversorgung/allgemeines/dossier-109/@schema/opengever.dossier.businesscasedossier' \
--header 'Accept: application/json' \
--header 'Authorization: <auth>' \
--cookie 'I18N_LANGUAGE=fr-ch'
```

It correctly returns the data in French if we change the cookie to only 'fr':
```bash
curl --request GET 'https://lab.onegovgever.ch/ordnungssystem/umwelt/wasserversorgung/allgemeines/dossier-109/@schema/opengever.dossier.businesscasedossier' \
--header 'Accept: application/json' \
--header 'Authorization: <auth>' \
--cookie 'I18N_LANGUAGE=fr'
```

#### Expected Result

API returns data in French if we call it with 'fr-ch'.

Gever-UI Issue: https://github.com/4teamwork/gever-ui/issues/804.

**Comment by phgross** [comment]
Scheint kein Problem mehr zu sein, Übersetzungen im neun UI funktionieren wie gewünscht.
