### ISSUE TITLE
ContentTreeWidget vom Move-Items Formular verwendet die falsche Queries für die Abfrage

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#6211]
Die `move_items`-View rendert ein Formular mit einem `ContentTreeWidget`. Das Widget stellt ein Navigations-Baum zur Verfügung sowie eine Autocomplete-Suche (https://github.com/4teamwork/opengever.core/blob/master/opengever/dossier/move_items.py#L210)

![screen1](https://user-images.githubusercontent.com/557005/73074323-a79a4a80-3eb9-11ea-958d-5dae5c8f4b8a.gif)

Die View entschiedet nun anhand der ausgewählten Elemente, welches Formular bzw. welche Queries schlussendlich verwendet werden sollen (https://github.com/4teamwork/opengever.core/blob/master/opengever/dossier/move_items.py#L218)

Wollen wir z.B. ein Dokument in einem Vorlagenordner verschieben, wird der Vorlagen path source binder mit den angepassten Queries verwendet. Ein Dokument in einem Vorlagenordner darf nur in ein anderen Vorlagenordner verschoben werden.

Wird nun das Autocomplete-Widget für die Suche verwendet, funktioniert diese Implementation nicht mehr. `plone.formwidget.autocomplete` macht XHR Requests auf die `@@autocomplete-search` View (https://github.com/plone/plone.formwidget.autocomplete/blob/master/plone/formwidget/autocomplete/widget.py#L126) auf dem Widget der `move_items`-View. Dabei werden die aktuell ausgewählten Elemente nicht mehr mitgeschickt. Die `move_items`-View geht somit davon aus, dass es sich nun um kein Template-Item handelt und lädt das normale Formular mit den normalen Queries. Das gleiche geschieht mit der TreeView (klick auf  "hinzufügen...") welche die `@@contenttree-fetch` View ansteuert.

Das bedeutet, die Autocomplete-View gibt nun alle Dossiers zurück und nicht nur Template-Dossiers.

![screen1](https://user-images.githubusercontent.com/557005/73074900-f1376500-3eba-11ea-93e9-7558cc27d5db.gif)

# Lösungsansätze

Ich sehe momentan zwei mögliche Lösungsansätze:

1. Patch für  https://github.com/plone/plone.formwidget.autocomplete/blob/master/plone/formwidget/autocomplete/widget.py#L126 erstellen, damit `self.request.form` mitgeschickt wird.

2. Eine eigene Action-View (z.B. `move_items`, `move_template_items`, `move_proposal_items`) für jedes Tab erstellen, welches speziell behandelt werden muss. (Default, Templates, Proposals)

**Comment by njohner** [comment]
Just a comment is that we need a solution that can then be used with the new frontend

**Comment by elioschmutz** [comment]
The new frontend is not affected by this issue.

**Comment by phgross** [comment]
The new frontend is not affected by this issue.
