### ISSUE TITLE
Check permissions on subdossiers in resolve preconditions

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6213]
When a user has permission to resolve a main dossier but not some of the subdossiers, there will be an error during dossier resolution. Instead we should check that in the preconditions check and give the user useful feedback when he does not have the permissions on all the subdossiers.

See https://github.com/4teamwork/opengever.sg/issues/373

Sentry https://sentry.4teamwork.ch/sentry/onegov-gever/issues/31719/

**Comment by lukasgraf** [comment]
Only dossiers that *need* to be resolved need to be checked for the necessary permission (or role). So, we need to skip already resolved dossiers, inactive ones, etc..

**Comment by phgross** [comment]
Ins JIRA überführt: https://4teamwork.atlassian.net/browse/GEVER-118
