### ISSUE TITLE
Verschieben in Root vom ContentTreeWidget nicht möglich

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#6224]
Das ContentTreeWidget rendert ein Autocomplete Widget und einem Button zum Rendern eines Overlays mit einer Baumstruktur auf der Basis eines NavigationTree Queries.

Das Widget benötigt zwei Verschiedene Endpoints, `@@contenttree-fetch` und `@@autocomplete-search`. Der `@@autocomplete-search` Endpoint funktioniert wie gewünscht und gibt alle Objekte welche dem Query entsprechen zurück. Der `@@contenttree-fetch` funktioniert generell auch wie er soll, sofern man keine grossen Einschränkungen im NavigationTree hat.

Möchte man jedoch die Navigation in einem Dossier mit allen Subdossiers einschränken (https://github.com/4teamwork/opengever.core/pull/6223) ist es nicht möglich, das Hauptdossier selbst auszuwählen.

Wird der Button für die Baumstruktur gedrückt, wird der `@@contenttree-fetch` Endpoint per AJAX nach Elementen abgefragt. Initial wird dabei der Root-Pfad vom Source-Binder als Query-Root verwendet (Beim Beispiel vom `DossierPathSourceBinder` wäre dies das Hauptdossier des jeweiligen Kontextes). Der Endpoint gibt nun alle Objekte welche dem Navtree-Query entsprechen zurück, welche sich direkt innerhalb des Root-Pfades befinden. Wir anschliessend ein Objekt im Browser angeklickt, wird der Pfad vom angeklickten Objekt als Root-Pfad verwendet und dessen Kinder werden nachgeladen und gerendert. So erhält man die gewohnte Baumstruktur.

Mit dieser Implementation ist es jedoch nicht möglich, das Root-Objekt selbst anzuwählen. Im Beispiel vom `DossierPathSourceBinder` wäre dies wieder das Hauptdossier. Es kann alles innerhalb dieses Dossiers angewählt werden, aber nicht das Dossier selbst.

Siehe: https://github.com/plone/plone.formwidget.contenttree/blob/master/plone/formwidget/contenttree/widget.py#L98 => Es werden immer die Kinder des Root-Objektes oder des angeklickten Objektes im Browser abgefragt.

# Lösungsvorschläge

Die `Fetch` (https://github.com/plone/plone.formwidget.contenttree/blob/master/plone/formwidget/contenttree/widget.py#L36) view vom `ContenttreeWidget` erweitern und das Javascript anpassen. 

Dies is nicht ganz einfach und scheint mir auf den ersten Blick etwas hackisch.

**Comment by phgross** [comment]
Problem existiert in der neuen Benutzeroberfläche nicht mehr.
