### ISSUE TITLE
O365: 3rd party checkin-in

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6229]
_Harvest: `[0.322.3 / 40] Projekt - Integration Office Online in OneGov GEVER (OGIP 58)` - `Anpassung Checkout/Checkin`_

Ursprung: #6189
Basiert auf: #5993

### Hintergrund
Mit OGIP 58 wird Office Online integriert. Dies ermöglicht es den Benutzern ein Dokument auszuchecken und dann anschliessend in O365 mit real-time co-authoring zusammen zu bearbeiten. Anschliessend wird das Dokument wieder eingecheckt.

### Anforderung
Das Prinzip ist hier dass das Dokument initial automatisch vom ersten Benutzer ausgecheckt wird und ausgecheckt bleibt, bis der letzte Benutzer das Dokument schliesst. Es wird dann automatisch vom letzten Benutzer eingecheckt.

Daher ist es notwendig, dass O365 ein Dokument Benutzer "B" einchecken kann, auch wenn es von Benutzer "A" ausgecheckt wurde.

### Implementierungsvorschlag
- Die entsprechende Stelle in [`CheckinCheckoutManager.is_checkin_allowed()`](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L130-L131) muss so angepasst werden, dass die [WOPI View](https://github.com/4teamwork/opengever.core/blob/tb-wopi/opengever/wopi/browser/wopi.py#L241-L244) das Dokument auch einchecken kann, wenn dies durch einen anderen Benutzer geschieht als derjenige, der das Dokument ursprünglich ausgecheckt hat. Evtl. ein kwarg `force=False` oder `collaborative=False`, das von der WOPI View dann verwendet werden kann.
- Da ein `PutFile` erst stattfindet, wenn der letzte Bearbeiter das Dokument schliesst, werden wir uns anschauen müssen, wie man am besten rausfindet, ob der aktuelle Benutzer dies darf. Eventuell ist dies aber sowieso schon sichergestellt, weil er sonst gar keine gültigen Credentials (Auth-Token und/oder Lock-Token) hätte, um die WOPI View zu triggern.

**Comment by lukasgraf** [comment]
`ready-for-refinement`

**Comment by lukasgraf** [comment]
Remaining estimate: 2

**Comment by jone** [comment]
Cool, funktioniert Tip Top im Happy Path 😎

**Comment by jone** [comment]
@lukasgraf hab noch etwas weiter getestet. Ich denke es gibt noch race-conditions mit office connector und office online, z.B. wenn man beide gleichzeitig startet.

Mich dünkt dass man mit Office-Online auch bearbeiten kann wenn das Dokument bereits durch Office Connector gelockt ist (unterschiedliche Benutzer).
Das kann dann dazu führen dass beide nicht mehr entsperren.

Ist das dir bekannt?
Wenn wir relativ einfach einen Check einbauen können so dass Office Online nicht starten kann wenn das Dokument mittlerweile ausgecheckt ist würde ich das machen.
Wenns ein grundsätzliches und aufwändigeres Problem ist müssen wir überlegen ob wir das einfach in Kauf nehmen.
Der Benutzer kann mindestens das Dokument wieder einchecken - es kann aber dazu führen dass nicht jede Änderung gespeichert werden kann.

**Comment by lukasgraf** [comment]
@jone ist mir so nicht bekannt, hab ich aber auch so fies tatsächlich nicht getestet. Ich kann mir aber vorstellen wie's zustande kommt, da das launchen des OfficeConnector ziemlich entkoppelt abläuft, und auch recht langsam ist.

Wollen wir es so machen, dass Du das morgen kurz demonstrierst, und wir entscheiden dann wie wir weiter vorgehen wollen? (Neue Issue, in Kauf nehmen, ...)

**Comment by jone** [comment]
Ich habs nochmals getestet.
Voraussetzung: `hugo.boss`, `stefanie.muster` und [eingechecktes dokument](https://lab.onegovgever.ch/ordnungssystem/gesellschaftliches/maerkte-und-chilbi/allgemeines/dossier-220/document-727/).

- Hugo öffnet Detailansicht Dokument (im alten UI)
- Stefanie öffnet Detailansicht Dokument (im alten UI)
- Hugo drückt auf "Auschecken und Bearbeiten"
  - Office Connector macht ein Checkout
- Stefanie drückt auf "Mit Office Online bearbeiten"
  - Office Online öffnet ohne erfolgreiches Checkout
- Stefanie schliesst Office Online
- Hugo schliesst Office Connector

State ist komisch, siehe z.B.: https://lab.onegovgever.ch/ordnungssystem/gesellschaftliches/maerkte-und-chilbi/allgemeines/dossier-220/document-726

**Comment by jone** [comment]
Das zuletzt beschriebene Problem wird nach https://github.com/4teamwork/opengever.core/issues/6347 ausgelagert.
Damit ist dieses Issue m.E. abgeschlossen.
