### ISSUE TITLE
O365: Versionierung und Journalisierung

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6230]
_Harvest: `[0.322.3 / 40] Projekt - Integration Office Online in OneGov GEVER (OGIP 58)` - `Anpassung Journalisierung`_

Ursprung: #6189
Basiert auf: #5993

### Hintergrund
Mit der Office Online Integration können Benutzer Dokumente kollaborativ erarbeiten. Das heisst mehrere Benutzer erarbeiten gleichzeitig ein Dokument.

### Anforderung
Wenn eine Version kollaborativ erarbeitet wird soll nach Checkin ersichtlich sein, welche Benutzer an dieser Version gearbeitet haben. Im Minimum durch Kommentar.
Es muss nicht ersichtlich sein, welche Teile des Dokuments von wem Erarbeitet wurde (also Wort-basiert), sondern nur an welcher Version wer beteiligt war.

Analog gilt das gleiche für die Journal-Einträge: auch hier soll ersichtlich sein, wer alles mitgearbeitet hat.

### Implementierungsvorschlag

- Irgendwie müssen alle Benutzer, die an der Bearbeitung des Dokuments teilgenommen haben, bestimmt werden. Weil nicht jede Änderung eines Benutzers in einem `PutFile` resultiert, müssen wir uns anschauen, wie wir diese Liste bekommen können:

  - Gemäss [WOPI Doku für `PutFile`](https://wopi.readthedocs.io/projects/wopirest/en/latest/files/PutFile.html#putfile) müsste es einen Header geben, der die Liste der Bearbeiter enthält:
    > `X-WOPI-Editors` – A comma-delimited string of UserId values representing all the users who contributed changes to the document in this PutFile request.
  - Falls dieser Header aus irgend einem Grund nicht funktioniert, müssten wir sie beim Absprung (Action zum Bearbeiten des Dokuments in OfficeOnline) aus GEVER irgendwie tracken
- [`CheckinCheckoutManager.checkin()`](https://github.com/4teamwork/opengever.core/blob/master/opengever/document/checkout/manager.py#L160) so anpassen, dass diese Liste von Bearbeitern dem Checkin-Kommentar hinzugefügt wird.

Durch diese Anpassung wird der Kommentar sowohl als Checkin-Kommentar für die Version, wie auch im Journal verwendet werden. Der "Actor" wird aber an beiden Orten jeweils nur der User sein, der das Dokument eingecheckt hat.

Vorschlag für das Format: `Bearbeitet durch: Hans Muster, Peter Müller. <manuell eingegebener checkin-Kommentar, falls vorhanden>`

**Comment by lukasgraf** [comment]
`ready-for-refinement`

**Comment by lukasgraf** [comment]
Remaining estimate: 2

**Comment by jone** [comment]
Getestet, funktioniert.
Wir haben uns geeinigt dass der Journal-Eintrag und die Version immer dem letzten Bearbeiter gehört und die anderen im Kommentar ausgewiesen werden.
