### ISSUE TITLE
O365: Office Integration finalisieren

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6231]
_Harvest: `[0.322.3 / 40] Projekt - Integration Office Online in OneGov GEVER (OGIP 58)` - `Implementation WOPI-Schnittstelle`_

Ursprung: #6189

### Ziel
Ziel ist es, die Office Online Integration mit WOPI zu finaliseren. Die Implementation steht im PR #5993 bereits zur Verfügung.

Was ist noch nötig an Tests, Dokumentation, etc.?

### Todos

- PR #5993 reviewen

  - Für ein Review ist es vermutlich nötig, den branch auszuchecken und zu testen
  - Zum testen gibt es zwei Möglichkeiten:
    - Lokal, mit einem reverse tunnel via `rlab`
    - Auf `lab.onegovgever.ch` ab branch deployen (müsste zuerst aktualisiert werden)
    - Deployment ist in der [Doku](https://github.com/4teamwork/opengever.core/blob/tb-wopi/docs/intern/wopi/index.rst) beschrieben
  - GEVER-seitig müssen zum Installieren zwei Registry-Einträge gesetzt werden, `IWOPISettings.discovery_url` und `IWOPISettings.enabled`)

- PR mergen und auf `dev` deployen und konfigurieren (PO macht das Review auf `dev`)
- Für das Deployen auf `dev` muss evtl. noch die Domain freigeschaltet werden

**Comment by lukasgraf** [comment]
@jone 
Für ein Refinement braucht es aus meiner Sicht noch folgendes:

- Eine Beschreibung (High-Level), wie die Integration mit OO / WOPI funktioniert.
  _Wenn eine solche Beschreibung schon existiert (im OGIP, oder in Doku von Microsoft), bitte entweder hier in diese Issue reinkopieren oder entsprechend verlinken._

- Der PR #5993 muss finalisiert werden, damit klar ist welche Arbeiten schon gemacht sind, und welche noch ausstehen:
  - [PR-Checkliste](https://github.com/4teamwork/opengever.core/blob/master/.github/pull_request_template.md) anwenden, und fehlende Punkte ergänzen oder begründen.
  - Technische Dokumentation scheint zu fehlen. Wir brauchen etwas in einem ähnlichen Stil wie die [Doku für die OneOffix Integration](https://intern.onegovgever.ch/oneoffixx/).
  - Angabe dazu, was in diesem PR genau umgesetzt wird, und was nicht. U.a.:
     - Welche Aspekte der WOPI durch den PR implementiert werden, und welche nicht (ggf. aus dem OGIP kopieren, falls diese Angaben noch stimmen)
     - Ob die Implementierung für das alte Frontend, das neue, oder beides ist. Bzw. was bezüglich des User-Interfaces in diesem PR gemacht wurde, und ob noch etwas fehlt.

  - Erläuterung dazu, wie der PR getestet werden kann, bevor er gemerged wird. Lokal wird wahrscheinlich schwierig, wenn der WOPI Host von aussen erreichbar sein muss. Wie kann der PR stattdessen getestet werden?

Danach sollten wir in der Lage sein, zu bestimmen was jetzt genau noch fehlt / gemacht werden muss.

**Comment by jone** [comment]
@lukasgraf der #5993 wurde aktualisiert. Könntest du nochmals eine Einschätzung machen?

**Comment by lukasgraf** [comment]
@jone der PR sieht aus meiner Sicht gut aus!
Ich habe diesen Issue, und die anderen beiden, noch mininal ergänzt. Die Vorschläge sind nicht viel detailierter als "Wir müssen uns noch anschauen wie wir dies und das lösen können", aber müsste aus meiner Sicht für ein Refinement reichen.

**Comment by lukasgraf** [comment]
Dies ist umgesetzt:
- PR  #5993  wurde reviewed und gemerged
- Nötige Anpassungen bzgl. Lock-Token Mismatches wurden in #6309 gemacht
- Aktion auf der GEVER-UI Seite ist in https://github.com/4teamwork/gever-ui/pull/1003 umgesetzt
- Deployed auf `lab`, z.Z. konfiguriert auf die O365 Cloud Testumgebung
  _(Action wurde TTW auch im Classic UI eingebaut, für mehr Flexibilität beim Testen. Dies wird auf echten Systemen nachher nicht so sein)_

**Comment by jone** [comment]
>  (Action wurde TTW auch im Classic UI eingebaut, für mehr Flexibilität beim Testen. Dies wird auf echten Systemen nachher nicht so sein)

@lukasgraf Ich meinte dass dies auch im alten UI verfügbar sein sollte. Ich nehme an dass sie es in SG auch auf nicht-UI-Pilot-Mandanten benutzen möchten. Stand irgendwo dass wir es nur im neuen wollen? 🤔
