### ISSUE TITLE
Handling of teamraum deployments

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6234]
For now we make no distinction between deployments that are gever or teamraum, although teamraum deployments might for example not have any repository. This leads at least to one issue with the `GET` on the plone site (https://github.com/4teamwork/opengever.core/pull/6226) as we assume that we always have a GEVER deployment. Potentially there are other places in the code where we would need to handle teamraum deployments differently.

Moreover the frontend might want to know whether a certain deployment is a teamraum or a gever. Maybe we could have a flag or something and also add it in the config endpoint??

**Comment by phgross** [comment]
The @config enpdoint provides now a flag if its a teamraum or a gever deployment.
