### ISSUE TITLE
Policytemplates: single-threaded

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6238]
_Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Bei der letzten generierten Policy gab es ein Problem weil von Seite Betrieb davon ausgegangen war dass die Policies ab jetzt im neuen Stil mit Single-Threaded und neuem `ftw.monitor` installiert werden, dies aber noch nicht in den Policy templates umgesetzt ist.

Frage: Wollen wir neu Policies immer single-threaded machen?

Wenn ja schlage ich vor die policy templates zu aktualisieren anhand Beispiel: https://github.com/4teamwork/opengever.bgdemo/pull/2

@lukasgraf ist das (jetzt) sinnvoll? Ist das dann ready for planning?

**Comment by lukasgraf** [comment]
@jone yep, aus meiner Sicht sinnvoll, und ready für planning.

**Comment by jone** [comment]
Anscheined bereits umgesetzt.
