### ISSUE TITLE
Document Tab in inbox with filter shows documents in forwardings

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6244]
In the document tab of the inbox, we do not list documents in forwardings (https://github.com/4teamwork/opengever.core/blob/master/opengever/inbox/browser/tabs.py#L78-L79). As soon as a filter is applied (`searchableText`), all documents in the inbox are searched instead.
Steps to reproduce:
- go to https://dev.onegovgever.ch/fd/eingangskorb#documents-proxy
- filter for `test`

**Comment by njohner** [comment]
Problem is here: https://github.com/4teamwork/opengever.core/blob/master/opengever/tabbedview/catalog_source.py#L80-L82
We get something like `'path': {'query': '/fd/eingangskorb', 'depth': 1}` and we only take the query, not the depth

**Comment by phgross** [comment]
Problem existiert in der neuen Oberfläche nicht mehr.
