### ISSUE TITLE
"Live-Suche": Dokument wird nicht gefunden

### ISSUE THREAD

**Issue by sebastianmanger** [4teamwork/opengever.core#6246]
Das Dokument "Iusto ab sequi error" im Dossier https://ris.onegovgever.ch/kr/ordnungssystem/kantonsrat/sitzungen/dossier-1196#documents-proxy wird in der Suche im Header nicht gefunden.

Das Problem ist innerhalb von RIS identifiziert worden: https://github.com/4teamwork/ris/issues/1442#issuecomment-580691507

RIS verwendet für die Dokument-Suche (innerhalb von RIS) den SOLR-Such-Endpoint der API, das Dokument wird auch da nicht gefunden (https://ris.onegovgever.ch/ris-kr/gremium/3000/dokumente).

Bitte abklären: ist das ein Fehler in der Suche, oder wende ich das falsch an?

**Comment by njohner** [comment]
`solr-maintenance` showed no difference, so it seems the document was indexed in solr. At first I did not find it because I searched `lusto` but it actually is `Iusto` with a capital `i`, not an `l`. 
I now find it. Any other examples of this?
I did touch the document while testing, so it might have gotten reindexed now. But still, it was in solr from the start.
So other example welcome...

**Comment by sebastianmanger** [comment]
From https://github.com/4teamwork/ris/issues/1442#issuecomment-583268052:

When searching "terminplanung_ws", this document is not found: https://gever.sg.ch/skrr/ordnungssystem/sitzungen/dossier-14989/document-40250#overview

But I guess there are also issues in RIS. I'll talk to the PO (@jone / @fguyer).

**Comment by njohner** [comment]
This is the issue with tokenization of special characters, i.e. during indexing the filename gets split and during search it seems we do not split the search terms at underscores, hence the search does not match as soon as we get to the underscore. More info here https://github.com/4teamwork/opengever.core/issues/5508

**Comment by njohner** [comment]
We are conscious of this and decided with SG that the setting we have now was what the wanted. So I'd close the issue for now.
