### ISSUE TITLE
Make sure that listings returns the same results from catalog and solr

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6247]
`GeverCatalogTableSource` switches between catalog queries and solr queries depending on whether the a filter is used (searchable_text). We recently had one issue in the inbox where filtering in the documents tab would display more items than when not filtering, because the `depth` argument was not handled when switching to the solr search (https://github.com/4teamwork/opengever.core/pull/6245). Looking at the code there is a good chance that we have other such issues:
- `exclude_searchroot` is not handled in the `solr_results` (see comment from @elioschmutz https://github.com/4teamwork/opengever.core/pull/6245) 
- ...

**Comment by njohner** [comment]
In the future only solr will be used for listings: https://4teamwork.atlassian.net/browse/GEVER-207

**Comment by phgross** [comment]
We only use solr for listings now.
