### ISSUE TITLE
Teilnehmer - Infos zu teamraum Teilnehmerinnen und Teilnehmer erfassen anstelle von Kontakt

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6251]
Im alten teamraum haben wir das Tab "Kontakt". Dies dient hauptsächlich zum Erfassen von zusätzlichen Informationen wie Telefon, Mail ev. weitere Kontaktmöglichkeiten.

**Comment by jone** [comment]
Siehe OGIP 59

**Comment by BlueSky9443** [comment]
https://4teamwork.atlassian.net/browse/GEVER-89
