### ISSUE TITLE
Neues Teamraum Demo Deployment: demo.teamraum.ch

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6258]
_Harvest: `[3.2.4 / 2] Projekt - teamraum 2019`_

Demo-Umgebung für Kunden und Interessenten erstellen
**To Do**
- Eigene Umgebung `demo.teamraum.ch` erstellen
- vorerst nicht mit `demo.onegovgever.ch` verbinden, aber auf selbem server, ie ipet/sia (wird dann mit https://github.com/4teamwork/opengever.core/issues/6271 verbunden)
- Eigenes OGDS (nicht im selben Verbund wie `demo.onegovgever.ch`)
- Neues Portal muss von Betrieb installiert werden

**Planned usage**
- Pro Kunde 1 teamraum®
- Wir estellen ein separater Teamraum pro Kunde
- Das onboarding passiert dann via Einladungen
- Kunden können keine neue Teamräume erstellen (also sie sind nur WorkspaceAdmin und WorkspaceUser, nicht WorkspaceCreator)
- update immer zusammen mit SaaS kunden bei minor gever/teamraum release.

**Abhängkeit**
- Marke teamraum® anstelle von OneGov GEVER anzeigen: https://github.com/4teamwork/opengever.core/issues/6260

**Umsetzung**
- We make a separate repository (otherwise we would need to reorganise change the `demo` policy, while it is already set-up and running)

**Comment by BlueSky9443** [comment]
Integration in bestehende demo.onegovgever.ch Umgebung
Kein Onboarding analog Demo GEVER über Webseite notwendig, teamraum Onboarding ausreichend

**Comment by BlueSky9443** [comment]
@deif: Ich weise den Issue Dir zur Triage zu. Ziel wäre es den Issue im nächsten Refinement zu besprechen und in den Sprint 15 zu laden.

**Comment by deiferni** [comment]
punkte mit @njohner diskutiert:
- wie dev.teamraum.ch kombo gever + teamraum, oder nur teamraum? empfehlung nur teamraum und dann evtl. mit https://demo.onegovgever.ch/ zusammenhängen.
- nur eine/wenige gruppen im ldap, ersten benutzer laden wir als admin ein, zugriff ist aber auf einen teamraum eingeschränkt
- will man das erstellen von teamräumen auch für externe in der demo erlauben? dann funktioniert obiger ansatz nicht.
- marke teamraum schon in https://github.com/4teamwork/opengever.core/issues/6260 erfasst
- update immer zusammen mit SaaS kunden bei minor gever/teamraum release. server äuä ipet/sia.

**Comment by all4manu** [comment]
Vorerst noch nicht im gleichen Verbund wie demo gever installieren. Sobald die beiden Systeme miteinander kommunizieren können wir demo teamraum "platten".

Stichwort: Neues Portal -> Wird benötigt, damit der Teamraum funktioniert.

**Comment by njohner** [comment]
Aller Kommentaren wurden in der Beschreibung oder in neuen Issues übernommen

**Comment by elioschmutz** [comment]
# Spez für das neue Deployment

## Developer
- [ ] neues Päckli: Vorschlag Name: `opengever.demoteamraum`
- [ ] LDAP-Konfiguration:
  - Users-Base: ou=Users,ou=TeamraumDemo,ou=OneGovGEVER,dc=4teamwork,dc=ch
  - Groups-Base: ou=Groups,ou=TeamraumDemo,ou=OneGovGEVER,dc=4teamwork,dc=ch
- [ ] Admin-Unit (gem. dev.teamraum.ch): `tr`
- [ ] Org-Unit (gem. dev.teamraum.ch):
  - users_group_id: `tr_benutzer`
  - inbox_group_id: `tr_benutzer`
- [ ] Lokale Rollen (gem. dev.teamraum.ch):
  - Gruppe `tr_workspace_creators` => `WorkspacesCreator``
  - Gruppe `tr_benutzer` => `WorkspacesUser``
 
⚠️ sicher, dass wir die Demo-Benutzer mit Standard-Passwort verwenden wollen? Oder benötigen wir hier ein neues Set and Benutzer?

## Betrieb
- [ ] Neues Portal Installieren und Konfigurieren
- [ ] Bumblebee-App einrichten: `teamraum_demo`
- [ ] VHost einrichten für `demo.teamraum.ch` (siehe VHost von dev.teamraum.ch auf mut)
  - [ ] GEVER Deployment: `11-demo.teamraum.ch` => plone-site: `tr`
  - [ ] GEVER-UI: `99-gever-ui-demo.teamraum.ch`
  - [ ] `demo.teamraum.ch` redirect auf `/tr/workspaces`
  - [ ] Kein `geverui` Cookie-Handling. Es soll immer das neue GEVER-UI geladen werden
  - [ ] Bumblebee-Redirect einrichten
  - [ ] Portal-Redirects einrichten
  - [ ] Gever-Redirects einrichten
- [ ] Postgres-DB erstellen: `ogds_teamraumdemo`
- [ ] LDAP-OU für Gruppen und Benutzer `TeamraumDemo` erstellen gem. `TeamraumDEV` 

@4teamwork/gever es ist mein erstes GEVER-Deployment. Kann bitte jemand meine Task-Liste reviewen und mir eine Rückmeldung geben, ob noch was fehlt, oder ob alles i.O. ist? Danke euch!

**Comment by elioschmutz** [comment]
@4teamwork/gever kann mir bitte jemand meine Spez reviewen?

**Comment by njohner** [comment]
LGTM. Just some comments:
- For the users, we have a new LDAP branch, so we start from scratch. Instead of having the classic demo users, I think a few personal users for the ones who will be creating new workspaces for the interested clients would be better. I don't think we want external users to connect with Hugo Boss and be allowed to create new workspaces...
- I'm also not sure about the server. As it is not linked to `demo.onegovgever.ch` I'd rather have that demo installation not on SaaS servers.

**Comment by elioschmutz** [comment]
Der Teamraum kann unter demo.teamraum.ch getestet werden.

Momentan existieren folgende Benutzer:

- hugo.boss => demo10 (WorkspaceUser)

**Comment by BlueSky9443** [comment]
https://demo.teamraum.ch/workspaces

Wurde diese Version grundsätzlich einmal geprüft?

Mit hugo.boss kann ich keinen teamraum erstellen = Test schwierig. Der Wunsch war, dass zumindest ich für die Demo-Kunden je einen teamraum erstellen kann.

Das Layout links sieht sehr nach GEVER aus
![image.png](https://images.zenhubusercontent.com/5db81a69a2fd04000141d728/a90d2921-daac-4392-8a73-3f16e05fa893)

Danke.

**Comment by njohner** [comment]
- I created a `christoph.brutsch` user who has the permissions to create new workspaces. 
- It looks like GEVER because it is GEVER... We don't have any Teamraum specific look for now.

**Comment by BlueSky9443** [comment]
Sorry, it is not GEVER for our customer! 
![image](https://user-images.githubusercontent.com/56879539/75985054-d90c2a00-5eeb-11ea-9f59-9211a3d26440.png)

**Comment by njohner** [comment]
There is an open issue for that: https://github.com/4teamwork/opengever.core/issues/6260

**Comment by jone** [comment]
> There is an open issue for that: #6260

@njohner nope, the navigation of demo.teamraum.ch is in GEVER-mode (e.g. has a dashboard); that it is not the same. demo is just not yet configured properly. should look the same as dev 😉

**Comment by njohner** [comment]
Ah sorry, didn't know we had a teamraum specific look. But I now see we do.

**Comment by elioschmutz** [comment]
I'll take a look, thanks @niklaus for creating the user

**Comment by elioschmutz** [comment]
@BlueSky9443 der App-Switcher wird nun korrekt dargestellt:

<img width="680" alt="Bildschirmfoto 2020-03-06 um 13 12 48" src="https://user-images.githubusercontent.com/557005/76082697-3e275480-5fac-11ea-9454-70ed2944e513.png">

**Comment by elioschmutz** [comment]
@BlueSky9443 hast du nun alles, um demo.teamraum.ch zu testen? oder fehlt noch etwas?

**Comment by BlueSky9443** [comment]
@elioschmutz 

- Dateivorschau ist nicht aktiviert.

- Einladung funktioniert nicht

**Comment by elioschmutz** [comment]
@BlueSky9443 

- [x] Dateivorschau
Die Vorschau funktioniert nun wie gewünscht
- [ ] Einladungen 
Die Mails werden korrekt verschickt, landen jedoch zum Teil im Spam-Ordner.
Es gibt jedoch noch ein Problem beim Annehmen der Einladung für einen noch nicht registrierten Benutzer (On-Boarding) mit dem neuen Portal und den Rewrite Rules. Leider habe ich das heute nicht mehr geschafft. Ich bin mit den entsprechenden Mitarbeitern in Kontakt (@combine-space @lukasgraf @buchi ) [Slack-Discussion](https://4teamwork.slack.com/archives/C060FEYKA/p1583762054016500)

**Comment by elioschmutz** [comment]
@BlueSky9443 alle offenen Punkte sind erledigt. Die Demo-Plattform kann nun final getestet werden.

**Comment by BlueSky9443** [comment]
Einladungsmail aus demo.teamraum.ch landete bei marco.baumgartner@4teamwork.ch noch im SPAM. Ansonsten hat der Einladungsprozess geklappt.

**Comment by jone** [comment]
Bez. SPAM: könnt ihr das noch mit Ops klären ob alles richtig konfiguriert ist (DKIM oder was auch immer).

**Comment by elioschmutz** [comment]
@combine-space die Emails der Einladungen landen fast immer im Spam-Ordner. Kannst du überprüfen, ob alles korrekt konfiguriert ist? Danke dir!

**Comment by combine-space** [comment]
Habe das Mail analysiert. Die Einladung wird mit der Einlader-Email-Adresse via den MTA von gev01p versendet, das kann so nicht funktionieren.
Richtig wäre: mit einer noreply Adresse senden und die Adresse des Einladers als reply-to.

**Comment by jone** [comment]
Welches ist die Absender-Adresse?

**Comment by combine-space** [comment]
Es muss einfach eine Adresse sein, welche der zu sendenden Domain entspricht, z.B. noreply@demo.teamraum.ch.

**Comment by jone** [comment]
> Es muss einfach eine Adresse sein, welche der zu sendenden Domain entspricht, z.B. [noreply@demo.teamraum.ch](mailto:noreply@demo.teamraum.ch).

Ja finde ich gut. Aber was wird bis jetzt verwendet?

**Comment by elioschmutz** [comment]
Sie wird doch von `info@demo.teamraum.ch` versendet:

<img width="612" alt="Bildschirmfoto 2020-03-17 um 15 22 51" src="https://user-images.githubusercontent.com/557005/76865589-39438a00-6863-11ea-9904-692381d1647d.png">

```
Received: from CO1NAM11HT211.eop-nam11.prod.protection.outlook.com
 (2603:10a6:20b:110::24) by AM7P189MB0742.EURP189.PROD.OUTLOOK.COM with HTTPS
 via AM7PR04CA0014.EURPRD04.PROD.OUTLOOK.COM; Fri, 13 Mar 2020 15:00:21 +0000
Received: from CO1NAM11FT048.eop-nam11.prod.protection.outlook.com
 (2a01:111:e400:3861::34) by
 CO1NAM11HT211.eop-nam11.prod.protection.outlook.com (2a01:111:e400:3861::390)
 with Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.2814.13; Fri, 13 Mar
 2020 15:00:20 +0000
Authentication-Results: spf=pass (sender IP is 194.182.164.197)
 smtp.mailfrom=demo.teamraum.ch; msn.com; dkim=none (message not signed)
 header.d=none;msn.com; dmarc=bestguesspass action=none
 header.from=demo.teamraum.ch;compauth=pass reason=109
Received-SPF: Pass (protection.outlook.com: domain of demo.teamraum.ch
 designates 194.182.164.197 as permitted sender)
 receiver=protection.outlook.com; client-ip=194.182.164.197;
 helo=gev01p.4teamwork.ch;
Received: from gev01p.4teamwork.ch (194.182.164.197) by
 CO1NAM11FT048.mail.protection.outlook.com (10.13.175.148) with Microsoft SMTP
 Server (version=TLS1_2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id
 15.20.2814.13 via Frontend Transport; Fri, 13 Mar 2020 15:00:20 +0000
X-IncomingTopHeaderMarker:
 OriginalChecksum:D04B387C269693B640BDD6730175910E044F31F6947B33E2CABE10A61B286945;UpperCasedChecksum:45EBDFBAD526DB76ABEE4B15F60A9C5A9D41EB0BDDDF2DCF4DA3E6EFE5D12E7A;SizeAsReceived:519;Count:8
Received: from gev01p.4teamwork.ch (localhost [127.0.0.1])
	by gev01p.4teamwork.ch (Postfix) with ESMTP id 93A43104FEE7
	for <elio_schmutz@msn.com>; Fri, 13 Mar 2020 16:00:18 +0100 (CET)
Message-Id: <20200313160018.25433.1028496311@gev01p.4teamwork.ch>
Content-Type: multipart/related;
 boundary="===============1906387517274792595=="
From: =?utf-8?q?Teamraum?= <info@demo.teamraum.ch>
To: elio_schmutz@msn.com
Subject: Einladung zum Teamraum "test"
Date: Fri, 13 Mar 2020 16:00:18 +0100
X-IncomingHeaderCount: 8
Return-Path: info@demo.teamraum.ch
X-MS-Exchange-Organization-ExpirationStartTime: 13 Mar 2020 15:00:20.2540
 (UTC)
X-MS-Exchange-Organization-ExpirationStartTimeReason: OriginalSubmit
X-MS-Exchange-Organization-ExpirationInterval: 1:00:00:00.0000000
X-MS-Exchange-Organization-ExpirationIntervalReason: OriginalSubmit
X-MS-Exchange-Organization-Network-Message-Id:
 58325985-f195-4997-9fc2-08d7c75f3fce
X-EOPAttributedMessage: 0
X-EOPTenantAttributedMessage: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa:0
X-MS-Exchange-Organization-MessageDirectionality: Incoming
X-Forefront-Antispam-Report: EFV:NLI;
X-MS-Exchange-Organization-AuthSource:
 CO1NAM11FT048.eop-nam11.prod.protection.outlook.com
X-MS-Exchange-Organization-AuthAs: Anonymous
X-MS-PublicTrafficType: Email
X-MS-Office365-Filtering-Correlation-Id: 58325985-f195-4997-9fc2-08d7c75f3fce
X-MS-TrafficTypeDiagnostic: CO1NAM11HT211:
X-MS-Exchange-EOPDirect: true
X-Sender-IP: 194.182.164.197
X-SID-PRA: INFO@DEMO.TEAMRAUM.CH
X-SID-Result: PASS
X-MS-Exchange-Organization-PCL: 2
X-Microsoft-Antispam: BCL:0;
X-OriginatorOrg: outlook.com
X-MS-Exchange-CrossTenant-OriginalArrivalTime: 13 Mar 2020 15:00:20.0602
 (UTC)
X-MS-Exchange-CrossTenant-Network-Message-Id: 58325985-f195-4997-9fc2-08d7c75f3fce
X-MS-Exchange-CrossTenant-Id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa
X-MS-Exchange-CrossTenant-FromEntityHeader: Internet
X-MS-Exchange-CrossTenant-RMS-PersistedConsumerOrg:
 00000000-0000-0000-0000-000000000000
X-MS-Exchange-Transport-CrossTenantHeadersStamped: CO1NAM11HT211
X-MS-Exchange-Transport-EndToEndLatency: 00:00:01.3739186
X-MS-Exchange-Processed-By-BccFoldering: 15.20.2814.005
X-Microsoft-Antispam-Mailbox-Delivery:
	abwl:0;wl:0;pcwl:0;kl:0;iwl:0;dwl:0;dkl:0;rwl:0;ucf:0;jmr:0;ex:0;auth:1;dest:J;OFR:SpamFilterAuthJ;ENG:(5062000262)(9000001)(9010001)(9030001)(5061607266)(5061608174)(4900115)(8390131)(8377080)(8383139)(8403011)(58390011)(98390011)(8399029)(4920090)(6375004)(4950130)(4990090)(9140004);RF:JunkEmail;
X-Message-Info:
	qoGN4b5S4yp/BoeS/qwdFvJ0oGDj0PQPGTBwBidDZ5mUJt0O6WukoRGtXNjv8fPdDiiZKL+iTi3hGTaNfxvwWuZGsVJyQxOTNcBnlS8LnBC7SyVUBVH3vegyDovzl3WAqwP+78fY71w0Dl0GrIIzkAcNGKSYvQaxUVHD1Eyj65dQd0J+xfUyN/Gxn6cfgFaoB2YFQYnf9mOUhhZSETNEvg==
X-Message-Delivery: Vj0xLjE7dXM9MDtsPTA7YT0wO0Q9MjtHRD0yO1NDTD02
X-Microsoft-Antispam-Message-Info:
	=?utf-8?B?SXJocjV0dDFEeVlZckVKZXQ4Yko1TnBJdFU3aFlKTnpiYXdyVlJTZ1Q4S20r?=
 =?utf-8?B?MC9RbngrOUFqUDQ1d1JJclNGMVVaL0xaa0oxazRFVGkvNUpUOFlNRndIMlhN?=
 =?utf-8?B?eWYzOStFWXd6Z2lDbWN2R3VDZzBvdzhZWkRMUnMvVkxna1NaNHpEd3VXcGdo?=
 =?utf-8?B?dG9TSGN5Z3A2ZHlXRzRtWmlkRFhlaGpNRml4RUNkOW1hamlibHk2RkZtbmdn?=
 =?utf-8?B?dFM3dTYzd2I1aGFhZE9zcWc0dmpJNUZuUjBuNUlCOCtzakQ1QUMyZjJKRjBZ?=
 =?utf-8?B?WFdQWE5GYVhDYjR3UzI3SmpYeDMxYXZKWXd2M1ArTnVGY1FtSXBRRGZjWUFZ?=
 =?utf-8?B?T0FaeUpla2x0Zm1YVXdMRWN3K093TTZ6QmhEUXBETEx2cFFkWlFMZEo3b3Za?=
 =?utf-8?B?ZFNLNVEzdk1TOWhUTTZMaFBoMm5nVVRKTHUySi9PZmxDVm1mNXAwc1JPSUlK?=
 =?utf-8?B?WCsybVg4dWRlVVFDSWdPaWxnN0gyUUJkN01rYTR3bFI5MGNMSUpqd2NvdnZx?=
 =?utf-8?B?bVRaekVPUUJPVE5EN2IrVVZ4VW8zYVlCRjNxbmFibVExbHpuTk5KMzRRajdZ?=
 =?utf-8?B?TktYTWhJREMwOGxORU5IeFV0cmJaQXd0Qm1oMU54dStTQVAzczZpaHpHOC9U?=
 =?utf-8?B?cGU2a0QvbWkvdXRnQnhCTVpNSkFCWHRjTXVxTnMxcDNBb2VqYzQwMUN0cHlV?=
 =?utf-8?B?K1pHSktUSjdCRTMwRFUxZXRTMWpkR2FRYlEvTnJUWEg2WVluRUFzaGpLRTdw?=
 =?utf-8?B?MU9pOTlIRFYxVzBURmxVRlBNTmphdTduc2JtSm5Pd2t2d0R0Y1NNakd3UWRF?=
 =?utf-8?B?eXczcXZVRWRxbzBNMXU0MGRVS0xyRHcrM0ZwMEhsU0NnZGVLejBYTUo2Tk5N?=
 =?utf-8?B?MkU1KzI0WWNpK3FQRkF6SmlGSms1OFVjaG1EaFVtZi9jekdpc2M1NFhxU1Vz?=
 =?utf-8?B?Zk1xaHdNbVpLSHBnTFRVbXFyeWRQTzQ2SElhVDRVUHJIRWo1cXdIMU1uWVZu?=
 =?utf-8?B?L0lSV2sxNFF4b1FSdU9vZ205NGxTMzJobmRZbHF4THFKbEw1SHhpcFplSkpr?=
 =?utf-8?B?R3B3MXVHczEvek5ZdGEwTFp6YWdLWWRHdDNCUlJOM1J5ODUybVovbXU4Ym1O?=
 =?utf-8?B?OVkrV1FMUS9BZlpZcTRLQ3Yzck80eUhSR2h2VFVSTURxMkhpenF2MmxqZ0dr?=
 =?utf-8?B?aVpMcy9DUWZ3UDFGWlhXNW04Sms2WDNHRlQ5MU0wTXRrZm5YUnFhZkxmSWFW?=
 =?utf-8?B?UlJIOWtNVWdkbm5mcHJrWXdqL1RXb1VlWlJxdCt4RnVWTWs2VElFbkI5TWdk?=
 =?utf-8?B?SUZXa0wzNWVRbmtiaUdETVlZU1grSzdtNEl6TFRvVkthT0JwRkZBY1V6Z1Jk?=
 =?utf-8?B?UVdVTFBsdmxVaW9RTHJFcnE2UmlKU1MvZGVFUU44TC9WOFdXVkVoSjNYR1RW?=
 =?utf-8?Q?6PAzvgzP?=
MIME-Version: 1.0

--===============1906387517274792595==
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: quoted-printable

<html xmlns=3D"http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dutf-8"></=
head>
<h1 style=3D"text-align: center; margin: 0 0 10px 0; font-family: Arial, sa=
ns-serif; font-size: 24px; line-height: 125%; color: #333333; font-weight: =
normal;">Sie wurden von zopemaster (zopemaster) in den Teamraum &quot;test&=
quot; eingeladen.</h1>

   =20

    <p>Accept: https://demo.teamraum.ch/workspaces/workspace-2/@@my-invitat=
ions/accept?invitation=3DeyJpaWQiOiJlMWZlM2FmZjQ2NzA0ODRmYjk3YTRiODFjNzUyZG=
MzNCJ9.XmugAg.04VSE-gEJCGLwRC2o5k0q_jzIq4</p>

</html>

--===============1906387517274792595==--
```

**Comment by combine-space** [comment]
Also laut dem Einladungsmail, welches ich von Christoph erhalten habe, wird die Einladung vom Einlader (christoph.bruetsch@4teamwork.ch) gesendet:

```
Delivered-To: adrian.chuck@4teamwork.ch
Received: by 2002:a2e:8e85:0:0:0:0:0 with SMTP id z5csp4040063ljk;
        Tue, 17 Mar 2020 05:01:34 -0700 (PDT)
X-Google-Smtp-Source: ADFU+vugWXmINyGV+oiIUKn0fUgorkVL9Rcec6wzNS8snpBGrCUsiaUYX1MvyOxBBfFki0kd7Oeo
X-Received: by 2002:a17:906:3145:: with SMTP id e5mr3825680eje.361.1584446494476;
        Tue, 17 Mar 2020 05:01:34 -0700 (PDT)
ARC-Seal: i=1; a=rsa-sha256; t=1584446494; cv=none;
        d=google.com; s=arc-20160816;
        b=jsxRKzHavAb5+Yddcmn88dl+nzye68OrdHHmLhxmVcUohZL/P4aXoOR8MdVeCGyUlI
         NneBRcYlrazhfTzJC2Wcu3pS5s9ZVlqdH7gJG0WpSWYDfXGR+UEnP5a5bwB7nJixmYYJ
         irMKg0Uwdy2GfkluDY1nJbOspMocOZO1pRCK9mr/gHK4SQnqSkeTcVvifI1MVLZwMFUy
         UybGYivb/njXxWe/7yJ9BQYuP4JisAT9SYpCgVmmXExL1XXrpIsVikUK8BzVbxebl5rG
         0h9Psu1k38+ZDcOiTgnKXriwG3NPzw1e/gDuW+MNLxPPP0FfCka9YzTc2e4S1yBeFlGQ
         cVHw==
ARC-Message-Signature: i=1; a=rsa-sha256; c=relaxed/relaxed; d=google.com; s=arc-20160816;
        h=date:subject:to:from:mime-version:message-id;
        bh=dXSKxL3UDkVZfpWUmj395sSh1uLtvwAJVZHZ1xbTLM0=;
        b=VaRRh/DPJCn+8rzfZ7TLXRsYsR09qocAtmkGMGsaJM0PdSbkIUQF0pvGS42j/qImp7
         OMNit65c6FOUneTl3jVR7sl1zXte0Y6xR1zeWJ44ImbmVQ83ovl7K/K06PVs6i6T1BtE
         5EgmlpJ/Q1EB58vGk2TUspEMwuSyesZ5e/kQ3ShRFdNdtOL+oFUBa7QbAgeB1E402x7K
         oUeUxJQK6mrIkelU/ivzDdgnTNRhduro8ZVII9xZyy0WJUIVQGuOjiW4RFAE/WF0BM7y
         8fIp5thely9Tj5g2mH2fHG6Z3xSnE9LljhrHcHU7fqJBog1JkqR+GD4OA9dRBQqVMDw5
         DpSQ==
ARC-Authentication-Results: i=1; mx.google.com;
       spf=softfail (google.com: domain of transitioning christoph.bruetsch@4teamwork.ch does not designate 194.182.164.197 as permitted sender) smtp.mailfrom=christoph.bruetsch@4teamwork.ch
Return-Path: <christoph.bruetsch@4teamwork.ch>
Received: from gev01p.4teamwork.ch (gev01p.4teamwork.ch. [194.182.164.197])
        by mx.google.com with ESMTPS id u16si2309583edo.74.2020.03.17.05.01.34
        for <adrian.chuck@4teamwork.ch>
        (version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
        Tue, 17 Mar 2020 05:01:34 -0700 (PDT)
Received-SPF: softfail (google.com: domain of transitioning christoph.bruetsch@4teamwork.ch does not designate 194.182.164.197 as permitted sender) client-ip=194.182.164.197;
Authentication-Results: mx.google.com;
       spf=softfail (google.com: domain of transitioning christoph.bruetsch@4teamwork.ch does not designate 194.182.164.197 as permitted sender) smtp.mailfrom=christoph.bruetsch@4teamwork.ch
Received: from gev01p.4teamwork.ch (localhost [127.0.0.1]) by gev01p.4teamwork.ch (Postfix) with ESMTP id 0ACA5104FEF6 for <adrian.chuck@4teamwork.ch>; Tue, 17 Mar 2020 13:01:34 +0100 (CET)
Message-Id: <20200317130133.25466.1437950180@gev01p.4teamwork.ch>
Content-Type: multipart/related; boundary="===============4272564921950593094=="
MIME-Version: 1.0
From: Brutsch Christoph <christoph.bruetsch@4teamwork.ch>
To: adrian.chuck@4teamwork.ch
Subject: Einladung zum Teamraum "Demo für unsere interessierten Kunden"
Date: Tue, 17 Mar 2020 13:01:33 +0100

--===============4272564921950593094==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: quoted-printable

<html xmlns=3D"http://www.w3.org/1999/xhtml">

    <h1 style=3D"text-align: center; margin: 0 0 10px 0; font-family: Arial=
, sans-serif; font-size: 24px; line-height: 125%; color: #333333; font-weig=
ht: normal;">Sie wurden von Brutsch Christoph (christoph.brutsch) in den Te=
amraum "Demo f=C3=BCr unsere interessierten Kunden" eingeladen.</h1>

   =20
     =20
        <p>Einladung zum neuen teamraum. </p>
     =20
   =20

    <p>Accept: https://demo.teamraum.ch/workspaces/workspace-1/@@my-invitat=
ions/accept?invitation=3DeyJpaWQiOiI2NDA5NDgwMTkxZGI0MmMwODE2NTI0NjJjYjA2Zj=
BhYyJ9.XnC8HQ.fz-0AdWyt2nYyOOVZ8uvvvNnbBE</p>

</html>

--===============4272564921950593094==--
```

**Comment by elioschmutz** [comment]
Aha... liegt daran, dass ich die Einladungen mit dem Zopemaster verschickt habe.

Ok, das Problem liegt im `opengever.activity`: https://github.com/4teamwork/opengever.core/blob/master/opengever/activity/mailer.py#L82

Wir schicken die Mails mit dem aktuellen Benutzer. Normalerweise hat der Benutzer auch eine E-Mailadresse von der aktuellen Domain.

Hier ist das natürlich nicht der Fall, weil wir mit unseren Benutzern arbeiten.

@jone wie soll ich hier fortfahren? Es gibt folgende Möglichkeiten:
V1: Neuer Issue erstellen und später behandeln (ist wohl eher ungünstig)
V2: Direkt einen Fix im `opengever.activity`, damit immer die Portal-Adresse verwendet wird. Gilt dann generell für Aktivitäten was u.U. nicht erwünscht ist
V3: die E-Mailadresse von @BlueSky9443 anpassen auf `chrstoph.brutsch@demo.teamraum.ch`

**Comment by elioschmutz** [comment]
Btw. @combine-space auch meine von `info@demo.teamraum.ch` verschickte Adresse landete bei mir im Spam Ordner...

**Comment by lukasgraf** [comment]
@elioschmutz @combine-space @jone ich befürchte, wir könnten (bzgl. Spam-Folder) hier auf diesen Issue mit SPF stossen:
https://github.com/4teamwork/opengever.sg/issues/116

**Comment by elioschmutz** [comment]
Besprochen im Daily: Wir ändern `opengever.activity` damit die Mails immer mit der Systemadresse versendet werden.

**Comment by elioschmutz** [comment]
PR: https://github.com/4teamwork/opengever.core/pull/6334

**Comment by elioschmutz** [comment]
@BlueSky9443 die Mails werden nun immer mit der Portal-Adresse verschickt. Momentan: `noreply@demo.teamraum.ch`. Meine Testmails habe ich korrekt empfangen. Kannst du bitte noch mit deinem Account überprüfen, ob es auch bei dir funktioniert? Danke dir!

**Comment by jone** [comment]
Bei @phgross ist es im Spam-Folder gelandet.
Was ist noch nicht gut?

**Comment by elioschmutz** [comment]
@lukasgraf danke für deinen Hinweis. Es handelt sich hier um unser Demo-Deployment, nicht das von St. Gallen. Es läuft auch auf unserem Server: `gev01p.4tamwork.ch`. Soweit ich den Issue von johni verstehe, handelt es sich dort um ein Problem bei St. Gallen, nicht bei uns.

@combine-space kannst du den Mailversand nochmals genauer analysieren? Warum landen die Mails immer noch im Spam-Ordner?

**Comment by BlueSky9443** [comment]
@combine-space Ich habe ein @gmx.ch in den demo.teamraum.ch eingeladen. Landete im normalen Posteingang. Anmelden hat einwandfrei funktioniert.
Momentan scheint es so, dass nur @4teamwork.ch im Spam landen.

**Comment by combine-space** [comment]
Ich habe das Problem mit dem Einladungs-Mail, welches im Spam landen nochmals angeschaut. Es scheint, dass vor allem Mails mit Ziel google/ gmail.com noch getagged werden. Tests auf andere Domains waren erfolgreich. Hier noch weitere Tests, welche belegen, dass alles korrekt eingerichtet ist (BATV und DKIM sind bei uns nicht im Einsatz) und wir nicht geblacklisted sind:

* http://www.allaboutspam.com/email-server-test-report/?key=A303F0FA9065451A66D8DCB2FF8E88B7
* https://mxtoolbox.com/SuperTool.aspx?action=smtp:demo.teamraum.ch&newAppVersion=1
* https://talosintelligence.com/reputation_center/lookup?search=demo.teamraum.ch

**Comment by BlueSky9443** [comment]
Aus meiner Sicht können wir für die Demo-Umgebung so starten. Die wenigen Kunden können wir ja informieren, dass ev. das Mail auch im Spam landet.

**Comment by elioschmutz** [comment]
Ok. Danke @combine-space für die Abklärungen

@BlueSky9443 Ich habe das Ticket wieder in die "Review" Spalte verschoben. Kannst du das Ticket schließen, wenn aus deiner Sicht alles i.O. ist?

**Comment by jone** [comment]
Aus Sicht GEVER-Team ist die Story umgesetzt.
Das E-Mail-Problem stellen wir im Betriebs-Ticket noch fertig: https://extranet.4teamwork.ch/betrieb/tracker/923
