### ISSUE TITLE
Smoke Testing (vHosts, RewriteRules)

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6259]
_Harvest: `[3.2.2.1] OneGov GEVER` - `Softwarepflege (Refactoring/Bug)`_

Ursprung: https://github.com/4teamwork/opengever.core/issues/6181

### Ziel
Qualitätssicherung, dass nach einem Change an dem Integration-Code (vHost) die Anwendung noch funktioniert.

**Comment by lukasgraf** [comment]
Closed via #6283
