### ISSUE TITLE
Marke teamraum® - alle optischen OneGov GEVER Spuren auf teamraum® wechseln

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6260]
_Harvest: `[3.2.4 / 2] Projekt - teamraum 2019`_

z.B.
![image.png](https://images.zenhubusercontent.com/5db81a69a2fd04000141d728/2dfd2459-6024-40dc-91df-02c700cba56d)

![image.png](https://images.zenhubusercontent.com/5db81a69a2fd04000141d728/491cd01d-117e-4529-a15f-28fe689d8921)

**Comment by jone** [comment]
@BlueSky9443 bitte konkret spezifizieren.

**Comment by BlueSky9443** [comment]
- Browsertab mit teamraum® anpassen
- Hilfe ausblenden (aktuell keine Informationen zum teamraum® vorhanden. Folgen.)
- ev. Release-Hinweis mit teamraum® ergänzen. Früher oder später führt teamraum® ein Eigenleben

**Comment by all4manu** [comment]
@jone, Header kann via https://vue-meta.nuxtjs.org/ konfiguriert werden. Der Hilfe Button und der Release Hinweis sollte eigentlich auch relativ einfach angepasst werden können.

Fragen:
- gehört das 'Ⓡ' dazu?
- Soll im "Footer" einfach "Teamraum created by 4teamwork" stehen?

**Comment by BlueSky9443** [comment]
- Ⓡ gehört für mich dazu, da es sich um das einzige Produkt ist, welches registriert wurde
- Footer: guter Vorschlag mit teamraum®

**Comment by BlueSky9443** [comment]
https://4teamwork.atlassian.net/browse/GEVER-50
