### ISSUE TITLE
Hilfe - Neue Tour für teamraum® anbieten

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6261]
Beim ersten Mal starten und unter Hilfe kommt die GEVER UI Tour

![image.png](https://images.zenhubusercontent.com/5db81a69a2fd04000141d728/2e3c065a-f20f-4215-955c-ad9083ead93d)

**Comment by jone** [comment]
@BlueSky9443 Inhalt der Tour?

**Comment by BlueSky9443** [comment]
https://4teamwork.atlassian.net/browse/GEVER-85
