### ISSUE TITLE
WorkspaceClient Service-Keys pro Deployment

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#6263]
Es muss sichergestellt werden, dass ein Service-Key für den WorkspaceClient nicht für ein falsches Deployment verwendet wird. Konkret darf es nicht geschehen, dass ein Testsystem auf den produktiven Teamraum zugreift.

Momentan wird auf einem Teamraum ein Service-Key erstellt und in einem Ordner auf dem Filesystem abgelegt. Im GEVER-Deployment gibt man anschließend die URL zum Teamraum über eine Umgebungsvariable im Buildout an. Der `WorkspaceClient` sucht sich anschließend selbst den richtigen Key für die Konfigurierte URL aus allen abgelegten Schlüsseln auf dem FS.

Wenn nun auf einem Server mit installiertem Test und Prod-System vergessen geht, die Teamraum-URL für das Test-System anzupassen, wird sich das Test-GEVER auf dem produktiven Teamraum anmelden können und Inhalte anschauen und manipulieren können, sofern der User vom Testsystem auch auf dem Produktivsystem berechtigt ist.

Wir benötigen eine Lösung für eine sichere Trennung der Keys.

Ideen?

**Comment by lukasgraf** [comment]
Das aktuelle Verhalten hier ist so:
- Private Keys werden pro Cluster im `~/.opengever/ftw_tokenauth_keys` serverweit abgelegt
  (z.B. `teamraum_dev.json` und `teamraum_prod.json`)
- Die KeyRegistry lädt alle Keys, welche sie in diesem Verzeichnis findet. Über die `token_uri` ist eindeutig bestimmt, für welches Zielsystem ein Key gültig ist
- Wenn der WorkspaceClient eine Verbindung auf eine URL aufzubauen versucht, schaut die KeyRegistry ob sie für die Ziel-URL einen passenden Key hat, und verwendet diesen
- Die URL des angebundenen Teamraum-Deployments wird pro Deployment über eine Umgebungsvariable definiert

Dies habe ich so vorgeschlagen, um die Konfiguration der OGIP63 Integration für weitere Mandanten in einem Cluster möglichst einfach zu halten. Sie muss so einmal für einen Cluster gemacht werden, und für weitere Mandanten die hinzukommen funktioniert es einfach.

Damit eine Verbindung auf einen falschen Teamraum hergestellt wird, müssen also mehrere verschiedene Faktoren zutreffen:
- PROD und TEST laufen dem dem gleichen Server (was sowieso eine ganz schlechte Idee ist)
- Jemand hat blind ein `.cfg` für ein PROD deployment kopiert und daraus ein TEST deployment gemacht, _ohne_ die Teamraum URL anzupassen
- Der verwendete User existiert sowohl auf TEST als auch PROD
- Die Teamraum-Integration auf diesem falsch konfigurierten TEST deployment wurde nie wirlich getestet

Dies setzt aus meiner Sicht schon ziemlich viel nachlässiges Verhalten voraus.

Man könnte es nun so machen, dass der Pfad zum Key pro deployment konfiguriert werden muss. Dies hilft aber überhaupt nichts, wenn dann einfach ein PROD-buildout mit dem Pfad zu diesem Key kopiert wird, ohne diesen Pfad anzupassen.

Man könnte nun den Key pro deployment in das Deployment kopieren. Dies wäre aber deutlich aufwändiger bei Erstellen eines neuen Deployments, schwieriger zu automatisieren, und äusserst mühsam, falls dieser Key mal geändert werden muss. Und auch ein solcher Ansatz schützt nicht davor, dass jemand den falschen Key dort reinkopiert.

Mit `ftw.tokenauth` kann die [Verwendung eines Keys auf einen bestimmten IP-Range eingeschränkt](https://github.com/4teamwork/ftw.tokenauth#ip-range-restrictions) werden. Dies fände ich ehrlichgesagt eine sinnvollere Massnahme. Aber auch das nützt halt nichts, wenn PROD und TEST auf demselben Server laufen.

**Comment by jone** [comment]
Merci für die Erklärung. Mir war es vor allem wichtig dass wir alle Aspekte berücksichtigen. Das Shared-Verzeichnis bringt hier schon einen Nutzen in der einfachen Pflege, das sehe ich.

Das ist für mich so in Ordnung, wir lassen das so wie es ist.

Merci!
