### ISSUE TITLE
demo.onegovgever.ch mit demo.teamraum.ch verknüpfen

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6271]
**Timeline: Erst nach Ostern**
Ziel mit OGIP63 `demo.onegovgever.ch` mit `demo.teamraum.ch` verbinden (Pro Kunden ein teamraum® verknüpft mit einem GEVER)

- demo.teamraum.ch "platten"

**Comment by phgross** [comment]
Wurde gemacht.
