### ISSUE TITLE
Erweiterung API für Vertragsmanagement

### ISSUE THREAD

**Issue by PhilRoethlisberger** [4teamwork/opengever.core#6280]
_Harvest: ` [3.2.2.5 / 5] Projekt - Entwicklung Vertragsmanagement ` - `GEVER-API`_

### Ziel 
Ich sehe im Vertragsmanagement (VM) nur Verträge aus Dossiers, auf die ich im GEVER berechtigt bin.

Lösung gemäss Diskussion/Lösung in Issu des VM:
https://github.com/4teamwork/vertragsmanagement/issues/137

### Implementierungsvorschlag

> Dieser Implementierungsvorschlag ist bereits [durch Dokumentation (docs first) beschrieben](https://docs.onegovgever.ch/allowed-roles-and-users-preview/dev-manual/api/allowed_roles_and_principals/), welche sich auf dem`lg-allowed-roles-and-principals` branch befindet.

Es soll ein **neuer API Endpoint `@allowed-roles-and-principals`** eingeführt werden:

Methode: `GET`
Name: `@allowed-roles-and-principals`
Für: `Products.CMFCore.interfaces.IContentish`
Permission: `opengever.api.ViewAllowedRolesAndPrincipals`

Mit diesem Endpoint soll ein Client die `allowedRolesAndPrincipals` für dieses Objekt abfragen können. Um diese zu bestimmen, kann `Products.CMFPlone.CatalogTool. allowedRolesAndUsers` verwendet werden. _(Der Marker-String `user:` im Output dieses Funktion soll durch `principal:` ersetzt werden, da es sich um User oder Gruppen handeln kann)._

Es soll eine neue Permission eingeführt werden, mit welcher der Endpoint geschützt wird. Diese werden wir dann dem RIS-Service-User zuweisen:

```xml
<permission id="opengever.api.ViewAllowedRolesAndPrincipals"
            title="opengever.api: View AllowedRolesAndPrincipals" />
```

Weiter soll der Output des `@users` Endpoints (bereits [überschrieben](https://github.com/4teamwork/opengever.core/blob/master/opengever/api/users.py#L5) in GEVER)  ergänzt werden um die Information, welche tatsächlichen `roles_and_principals` der User hat. Dazu kann `catalog._listAllowedRolesAndUsers(user)` verwendet werden.

### Todo
- Neue `opengever.api.ViewAllowedRolesAndPrincipals` Permission
- Neuer `@allowed-roles-and-principals` Endpoint
- `@users` Endpoint um `roles_and_principals` ergänzen

**Comment by lukasgraf** [comment]
@jone done - ready for planning aus meiner Sicht (hab die Spezifikation gleich in den Body eingearbeitet).

**Comment by phgross** [comment]
Ins JIRA überführt: https://4teamwork.atlassian.net/browse/GEVER-15
