### ISSUE TITLE
Unauthorized if using the `WorkspaceClient`

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#6282]
_Harvest: `[3.2.4 / 2] Projekt - teamraum 2019`_

The `WorkspaceClient` handles authentication tokens for each user using `ftw.tokenauth`. If a token is expired, it will automatically renew the token which works fine: https://github.com/4teamwork/opengever.core/blob/master/opengever/workspaceclient/session.py#L16

`ftw.tokenauth` is cleaning up all expired tokens after issuing a new token. If there is no token in the token-storage of `ftw.tokenauth` it will not raise a 401 with the `token expired` messagee. See: See: https://github.com/4teamwork/ftw.tokenauth/issues/14

That means, we're no longer able to renew an expired token as soon as a new token (for the current user in another thread or for a new user) is issued. We end up in an anonymous api call which will raise a default 401.

We need to fix this either in `ftw.tokenauth` or in GEVER.

**Comment by elioschmutz** [comment]
Entscheid: Bei einem 401 grundsätzlich immer ein neues Token anfordern.

**Comment by jone** [comment]
✅ ist für mich ok; ich habe den Fall jeztt nicht reproduziert da schwierig.
