### ISSUE TITLE
Webaction to publish  document from gever to webpage

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6284]
For the presentation for WTO Fribourg on 11.02 we need to show that we can publish documents directly from GEVER to a website. Plan is to register a webaction for documents that links to a form on the website. Submitting that form will then GET the document from Gever and publish it.

OPTY: https://extranet.4teamwork.ch/crm/opportunities/1491

**Comment by phgross** [comment]
Wird via JIRA Projekt für die GEVER Einführung behandelt.
