### ISSUE TITLE
solr keywords in livesearch lead to errors

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6290]
Steps to reproduce:
- in the livesearch search for "foo AND bar" -> no results
- hit *enter* -> 💥 

Possible fix: lowercase the user search phrase?
See: https://sentry.4teamwork.ch/sentry/onegov-gever/issues/62134/

**Comment by deiferni** [comment]
Duplicate of https://github.com/4teamwork/opengever.core/issues/5937
