### ISSUE TITLE
Traktandenliste aus SPV kann nicht in App hochgeladen werden

### ISSUE THREAD

**Issue by Suweber** [4teamwork/opengever.core#6302]
Im Zip-File fehlt die Traktandenliste. Bei einer letzten Anpassung ist die Traktandenliste aus dem json-File "verschwunden". Bitte die Traktandenliste, welche in der SPV generiert wird wieder für den Import in die Sitzungs-App berücksichtigen. 
![image](https://user-images.githubusercontent.com/31923504/76059318-d3abef80-5f7e-11ea-9338-b9469f3d71c7.png)

**Comment by deiferni** [comment]
mittlerweile behoben.
