### ISSUE TITLE
Demo - Verantwortlicher zu ToDo zuweisen fehlerhaft

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6308]
https://demo.teamraum.ch/workspaces/workspace-1/todolist-1/todo-1
![image](https://user-images.githubusercontent.com/56879539/76205098-de25ed80-61f9-11ea-8b92-3c2f9909f4e9.png)

Ich wollte mich als Verantwortlicher für diese Aufgabe auswählen
![image](https://user-images.githubusercontent.com/56879539/76205140-f138bd80-61f9-11ea-833b-56967c9eb377.png)

**Comment by elioschmutz** [comment]
@BlueSky9443 das Zuweisen funktioniert nun. Das LDAP war nicht mit dem OGDS in Sync. Das Problem ist nun behoben.
