### ISSUE TITLE
Download Disposition removal protocol fails

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6315]
We get unicode errors when downloading the removal protocal. Steps to reproduce:
- go to https://sales.onegovgever.ch/ordnungssystem/bevoelkerung-und-sicherheit/einbuergerungen/allgemeines/disposition-4
- click download removal protocol

See https://sentry.4teamwork.ch/sentry/onegov-gever/issues/63983/

**Comment by phgross** [comment]
Fehler kann nicht mehr reproduziert werden.
