### ISSUE TITLE
Dossierjournal-PDF erst bei Aussonderung erstellen

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6316]
Diskussion aus: https://community.4teamwork.ch/t/dossierabschluss-pdfs-von-dossierjournal-ausblenden/1644

### Problem

Beim Dossier-Abschluss wird das Dossierjournal-PDF erstellt.
Wenn das Dossier wieder eröffnet und abgeschlossen wird gibt es mehrere PDFs.
Die User möchten das PDF eigentlich gar nicht im GEVER sehen.

### Vorschlag

Anstatt bei Dossier-Abschluss wird das Dossierjournal-PDF erst beim Erstellen des Angebots für die Aussonderung erstellt.

### Todo

- 

@phgross könntest du eine Einschätzung abgeben ob das so einfach möglich ist, resp. ob es zu Problemen führt. Wenn möglich kannst du gerne hier kurz ergänzen was konkret zu tun ist. Merci!

**Comment by phgross** [comment]
Aus technischer Sicht könnte die Generierung des Dossierjournal-PDFs auch bei der Aussonderung passieren, da alle Daten welche für das Dossierjournal PDF notwendig wären, bis zur Vernichtung des Dossiers bestehen bleiben. Ich würde aber als Zeitpunkt nicht die Erstellung des Angebots, sondern eher den Statuswechsel [`Angebot abliefern`](https://docs.onegovgever.ch/admin-manual/aussonderung/#angebot-abliefern) verwenden um die PDFs generieren.

Abzuklären:
 - Konsequenterweise müssten aber auch die Generierung des Aufgaben PDFs gleicht gehandhabt werden. 
 - Wie gehen wir mit bereits vorhanden PDFs um? Können bereits existierende Dokumente einfach ignoriert werden oder müssen diese entfernt werden? 
 - Muss die Generierung der PDFs ebenfalls in einem Nightlyjob abgehandelt werden? Ich würde vorerst darauf verzichten - beim Dossierabschluss waren vor allem die PDF-Konvertierungsjobs und Requests problematisch oder wie siehst du das @lukasgraf 

Todo's:
 - Generierung der PDFs aus dem Aussonderungsprozess triggern anstatt beim Dossier-Abschluss Job
 - Feature Flags entfernen oder deprecaten
 - (löschen von existierenden Dokumente)

**Comment by phgross** [comment]
Ins JIRA überführt: https://4teamwork.atlassian.net/browse/GEVER-64
