### ISSUE TITLE
Listing of Workspaces in dossier respects view permissions

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6317]
When a workspace is linked to a dossier, only users that have permission on that workspace will see it in the listing. This will certainly lead to confusion, several workspaces being created for the dossier and so on.

### Implementation
- The listing does a `@search` on the client, so there is no easy way to do an unrestricted search.
- We have the list of UDIs in the storage, so we know how many linked workspaces there are

### Proposed solutions:
- Also return the expected number of workspaces, so the frontend can display a warning when the user does not see all linked workspaces?
- Have a service user allowing to do an unrestricted search?
- Also store URLs in the storage, but then we'd need to keep it up to date somehow??

**Comment by phgross** [comment]
Wurde mit https://4teamwork.atlassian.net/browse/CA-1180 umgesetzt.
