### ISSUE TITLE
OfficeOnline, OfficeConnector und andere Bearbeitungs-Flows auseinanderhalten

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#6319]
_Harvest: `[0.322.3 / 40] Projekt - Integration Office Online in OneGov GEVER (OGIP 58)` - `Anpassung Journalisierung`_

Die unterschiedlichen Möglichkeiten, ein Dokument auszuchecken, zu bearbeiten und wieder einzuchecken, sollen so auseinandergehalten werden, dass sie sich gegenseitig nicht in die Quere kommen können. Dies unabhängig vom neuen oder klassischen UI, da wir davon ausgehen müssen, dass der Benutzer hin- und herwechselt.

Dies bedeutet:

- Wenn ein Dokument **via OfficeOnline in Bearbeitung** ist, müssen Aktionen die für andere Bearbeitungs-Flows gedacht sind, **deaktiviert** sein:
  - **Normales Einchecken**
  - **Checkout widerrufen** _(evtl. möchte man das noch Erlauben, muss noch abgeklärt werden)_
  - **Erneut bearbeiten** (mit dem OfficeConnector)

  Das Dokument kann also nur *automatisch* über den OfficeOnline-Flow eingecheckt werden (durch den finalen Unlock-Request auf die WOPI view).

  - Ausnahme: **Force Checkin** für Administratoren soll immer noch möglich sein
  - Risiko: Wenn der OfficeOnline-Flow aus irgend einem Grund nicht korrekt beendet wird (WOPI client schickt keinen finalen Unlock-Request), dann wird der Benutzer das Dokument nicht mehr selbstständig einchecken können.
_Eine Möglichkeit dies in Zukunft ein wenig besser zu behandeln, wäre, das Einchecken nach Ablauf eines Timeouts von z.B. 30min nach dem letzten `PutFile` zu erlauben. Microsoft empfiehlt IIRC auch, Locks irgendwann auslaufen zu lassen._

- Wenn ein Dokument **normal ausgecheckt** wurde, darf die **Aktion "Mit OfficeOnline bearbeiten" nicht zur Verfügung** stehen

### Umsetzung
Die Unterscheidung zwischen einem "normalen" Checkout, wie wir Ihn bisher hatten, und einem durch OfficeOnline wird über ein Flag `ICheckinCheckoutManager.checkout(collaborative=False)` gesteuert. Mit `collaborative=True` ist es ein kollaborativer Checkout (wird nur von der `edit_in_office_online` action gemacht).

- Ein **kollaborativer Checkout** impliziert ein **shared Lock** (_locking auf der Ebene des GEVER-Checkout Mechanismus_)
  Bearbeitungsmechanismen, die Annehmen dass sie ein exklusives Lock haben, dürfen nicht stattfinden

- Ein **"normaler" Checkout** impliziert ein **exklusives Lock**.
  Bearbeitungsmechanismen, die von einem shared Lock ausgehen, dürfen nicht stattfinden

**Comment by lukasgraf** [comment]
Kann auf https://lab.onegovgever.ch reviewed werden.

**Comment by jone** [comment]
Funktioniert aus meiner Sicht korrekt. Ich habe diverse Variante durchprobiert.
