### ISSUE TITLE
Dateivorschau - Beim erstmaligen teamraum Start nicht aktiv

### ISSUE THREAD

**Issue by BlueSky9443** [4teamwork/opengever.core#6327]
https://demo.teamraum.ch/workspaces/workspace-1

Wenn ich den teamraum in einem Browser starte, ist die Dateivorschau nicht aktiv. Ich muss 1 Dokument anklicken, so dass die anderen Dokumente funktionieren.

![image](https://user-images.githubusercontent.com/56879539/76856812-591f8180-6854-11ea-9671-25157dfa065c.png)

**Comment by njohner** [comment]
I could also reproduce this, even though the PDFs have already been stored in bumblebee. Reloading does not work either.

**Comment by BlueSky9443** [comment]
https://4teamwork.atlassian.net/browse/GEVER-48
