### ISSUE TITLE
SPV: Include missing styles from Request documents (Antrag) when appending Word documents using Sablon

### ISSUE THREAD

**Issue by andresoberhaensli** [4teamwork/opengever.core#6330]
Request documents are mostly edited by users of various skill levels, which can result in the "unwanted" creation or inclusion of new text styles (especially via copy-paste from other documents). 

If these styles are not defined in the original top document, Word will revert those to the default font and just apply the formatting from the original style, which can result in unexpected results in the final documents (Protokoll and Protokollauszug).

To minimize these issues, we should automatically import any style present in a request document that is missing in the top document into the merged final document. 

This would also simplify the template creation process, making it more accessible altogether for end-users.

**Comment by andresoberhaensli** [comment]
Mentions for notification:
@Suweber 
@deiferni

**Comment by deiferni** [comment]
We can't do this as we don't really know which protocol header will be used when we create a proposal. they are only coupled very loosely,
