### ISSUE TITLE
Improve error message when attempting to move documents locked by OC.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#6335]
When attempting to move documents that are locked via WebDAV the error message seems to be confusing to users. They will see the following error:

![Screenshot 2020-03-18 at 14 52 09](https://user-images.githubusercontent.com/736583/76967763-2050dc80-6928-11ea-8cb8-c7c66c5c5c4c.png)

- the message mention copy but they are inside the move handler, this should be updated https://github.com/4teamwork/opengever.core/blob/6e4c7be39b168522824f8b6f0ecc146ed9f4b95f/opengever/dossier/move_items.py#L186-L202
- the message mentions webdav, which is maybe a bit too technical. it should mention "officeconnector" instead.

Also should have a look at messages in the new UI of course.

**Comment by phgross** [comment]
Ins JIRA überführt: https://4teamwork.atlassian.net/browse/GEVER-117
