### ISSUE TITLE
API endpoints for SQL objects do not match an URL in the classic UI

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6339]
For https://github.com/4teamwork/gever-ui/issues/966 and https://github.com/4teamwork/gever-ui/issues/967 we introduce api endpoints to get the data for SQL only objects see  https://github.com/4teamwork/opengever.core/pull/6326 . This endpoints have an URL that does not match any view, only an API endpoint. Hence switching UI on these types of objects will fail.

Proposed solution is to have traversal for these objects on the plone side, using `SQLWrapperBase`. This allows to map user to a real path, as we have already done for `team`s and using a monkey patch we can fix the `PloneRESTWrapper. publishTraverse` so as to correctly handle finding the REST-API endpoint for these SQL objects.

The proposed solution works but:
- teams and users are mapped to a path in the `contact_folder`
- Teamraum deployments do not have a `contact_folder`

Also we'd still need to fix the functional tests, which do not include a `contact_folder` and hence fail all over the place (every time a user detail is needed...)

**Comment by phgross** [comment]
Ins JIRA überführt: https://4teamwork.atlassian.net/browse/GEVER-67

(Issue bleibt noch offen - da Potential fürs Nachladen)
