### ISSUE TITLE
Broken documentation on master

### ISSUE THREAD

**Issue by njohner** [4teamwork/opengever.core#6340]
With https://github.com/4teamwork/opengever.core/pull/6303 we broke our documentation.
Steps to reproduce:
- build the public documentation locally
- `api/schemas/*.inc` files get updated
- you'll get warnings that the markup is not ok in some `*.inc` files, i.e. if you push the changes tests would fail.

<img width="1440" alt="Bildschirmfoto 2020-03-26 um 08 44 13" src="https://user-images.githubusercontent.com/557005/77622125-002fa780-6f3e-11ea-82f6-4035618a7737.png">

**Comment by lukasgraf** [comment]
Internal docs als got broken with #5993 - I'm not yet sure how documentation tests didn't catch those.

**Comment by deiferni** [comment]
_(i've taken the liberty to put this into the tip of product backlog, docs are important. @phgross can override this, of course 😉)_

**Comment by elioschmutz** [comment]
Der Fehler von @lukasgraf in PR https://github.com/4teamwork/opengever.core/pull/5993 wird durch #6351 behoben.

**Comment by elioschmutz** [comment]
Alle Fehler scheinen wieder behoben zu sein. Ich erhalte keine Warnungen mehr und das Publizieren hat auch funktioniert.

Kann das noch jemand bestätigen? Evt. @njohner ?

**Comment by njohner** [comment]
Intern docu is fixed thanks, but public docu is still broken (the thing with the `api/schemas/*.inc` mentioned above)

**Comment by phgross** [comment]
Hier gibt es aus fachlicher Sicht nichts zu reviewen ...
