### ISSUE TITLE
Dokumente von stornierten Dossiers in Suche nach wie vor auffindbar

### ISSUE THREAD

**Issue by fguyer** [4teamwork/opengever.core#6342]
**Problembeschreibung**: 
Wird ein Dossier in GEVER storniert, ist es über die Suche nicht mehr auffindbar. Die darin enthaltenen Dokumente werden mir jedoch in der Suche noch angezeigt. Das Verhalten ist aus meiner Sicht unlogisch. 

**Zum Reproduzieren:**
Aufgefallen ist mir das ganze in der RIS-Dokumentensuche. Ich hatte ein Geschäftsdossiers in GEVER storniert und das zugehörige Geschäft in RIS entfernt. Meine Erwartung war anschliessend, dass die Dokumente des stornierten Geschäftsdossiers nicht mehr angezeigt werden. Anschliessend habe ich die Dokumente auf dem GEVER-Mandant gesucht und gefunden. Das Dossier selbst jedoch nicht. Habe das dann mit @njohner kurz besprochen und erstelle hier nun den Issue 😄.

**Comment by deiferni** [comment]
Wir haben es anders gelöst, stornierte Dossiers erscheinen nun auch in der Suche.
