### ISSUE TITLE
Office Online kann Checkout machen während OO Checkout existiert

### ISSUE THREAD

**Issue by jone** [4teamwork/opengever.core#6347]
_Harvest: `[0.322.3 / 40] Projekt - Integration Office Online in OneGov GEVER (OGIP 58)` - `Anpassung Checkout/Checkin`_

Ursprung: https://github.com/4teamwork/opengever.core/issues/6229#issuecomment-603067699

### Problematik

Wenn ein Dokument bereits mit Office Online ausgecheckt ist, kann ein andere Benutzer Office Online für dieses Dokument starten, obwohl dies nicht möglich sein sollte. Die Aktion erscheint zwar bei einem neuen Laden nicht mehr, aber wenn der zweite Benutzer die Seite bereits geladen hat bevor der erste Benutzer ein OO checkout macht ist die Aktion bereits da.

### Reproduktion

- Hugo öffnet Detailansicht Dokument (im alten UI)
- Stefanie öffnet Detailansicht Dokument (im alten UI)
- Hugo drückt auf "Auschecken und Bearbeiten"
  - Office Connector macht ein Checkout
- Stefanie drückt auf "Mit Office Online bearbeiten"
  - Office Online öffnet ohne erfolgreiches Checkout
- Stefanie schliesst Office Online
- Hugo schliesst Office Connector

Zum reparieren:

- Wenn ich dann als Stefanie nochmals mit Office Online bearbeite und schliesse wird es u.U. eingeckt. Konkret hat es bei mir erst beim 2ten Versuch geklappt.

**Comment by phgross** [comment]
Hi @lukasgraf  ich habe es kurz auf dem SG Testsystem getestet, die Bearbeitung der Dokumente via Office Online, klappt soweit gut und auch das verhindern der OC Action, falls das Dokument bereits online bearbeitet wird. Ich stelle aber fest, dass die Dokumente nicht automatisch wieder eingecheckt werden, sobald ich die Bearbeitung im Office Online beende. Ist das ein Auswirkung dieser Anpassung?

**Comment by phgross** [comment]
Soeben noch auf lab überprüft: dort kann ich die Probleme nicht reproduzieren.

**Comment by phgross** [comment]
@lukasgraf never mind, war wohl ein Problem mit meinen Socks-proxy Tunnels etc. 🙈 Erich konnte die Probleme nicht reproduzieren. Anpassung aus meiner Sicht i.O.

**Comment by phgross** [comment]
Review 👍
