### ISSUE TITLE
Wording anpassem für "wird gerade in OfficeOnline bearbeitet".

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#6349]
Das Wording der Meldung für ein ausgechecktes Dokument, das in OfficeOnline bearbeitet wird, kann in gewissen Situationen ein bisschen verwirrend sein.

Zu Zeit wird die Meldung folgendermassen dargestellt:

![Screenshot 2020-03-24 at 15 39 27](https://user-images.githubusercontent.com/405124/77438273-e4b18900-6de5-11ea-9abd-6c46c0b178bb.png)

---

![Screenshot 2020-03-24 at 15 40 01](https://user-images.githubusercontent.com/405124/77438290-ea0ed380-6de5-11ea-8fe7-d3f48cd17b9e.png)

---

Der dargestellte User (bzw. die Formulierung "von mir") bezieht sich auf den User, der das Dokument initial ausgecheckt hat. Inbesondere dann, wenn dieser User OfficeOnline aber bereits wieder geschlossen hat (aber andere Mit-Bearbeiter haben es noch offen), ist diese Meldung verwirrend.

Vorschlag: `Dieses Dokument wird gerade in Office Online bearbeitet (ausgecheckt durch Peter Muster).`

**Comment by phgross** [comment]
Die Benutzer scheinen damit kein Probleme zu haben - Issue wird geschlossen.
