### ISSUE TITLE
TabbedView fulltext filtering isn't batched when using Solr

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#6350]
When Solr is enabled, the TabbedView fulltext filtering **hard-limits results to 50 entries**, with no batching, and cuts off any results beyond that.

Extranet Ticket: https://extranet.4teamwork.ch/extern/opengever-kanton-zug/sprint-backlog/20477/

![Screenshot 2020-03-24 at 16 00 33](https://user-images.githubusercontent.com/405124/77440478-a49fd580-6de8-11ea-9e5e-14950fcca511.png)

### Steps to reproduce

- Set up GEVER from `master`
- Enable Solr
- Create more than 50 dossiers (e.g. by importing a bundle)
- Visit the repository root
- Switch to the `Dossiers` tab (classic UI)
- Filter for something that will produce more than 50 results

### Expected behavior
- All results are accessible, preferrably batched, and respecting the user's dynamic batch size settings

### Actual behavior
- Only the first 50 results are shown, no batching, and the user interface suggests that there's only exactly 50 results.

---

### First analysis

This seems to happen mainly for two reasons:
- Batching support simply isn't implemented for Solr results in the table source. Solr results are [hard limited to 50 entries](https://github.com/4teamwork/opengever.core/blob/999f5cff4b88844e63bf426398b91368a8117897/opengever/tabbedview/catalog_source.py#L124-L127) and no batching aware datastructure (like a `plone.batching.Batch` or a `LazyMap`, with .actual_result_count`) is being returned
- For some reason, even if that is corrected, a custom sort method gets applied to the result batch. The [`default_custom_sort` will eliminate a `Batch` wrapper](https://github.com/4teamwork/ftw.table/blob/master/ftw/table/catalog_source.py#L26-L46) and turn the batch items into a plain list, destroying any batching information. I don't quite understand yet why custom sorting is being run on batched results anyway - that can't work properly.

In addition:

- TabbedView queries via Solr are [hacked into the existing `GeverCatalogTableSource`](https://github.com/4teamwork/opengever.core/blob/999f5cff4b88844e63bf426398b91368a8117897/opengever/tabbedview/catalog_source.py#L18-L31) using a conditional, instead of a dedicated `SolrTableSource`. That leads to inheriting a lot of behavior, much of which doesn't make sense for Solr.

**Comment by deiferni** [comment]
classic ui, close.
