### ISSUE TITLE
Documents in a Subdossier can't be selected for a new proposal

### ISSUE THREAD

**Issue by nerm1ne** [4teamwork/opengever.core#6352]
When a user wants to create a proposal in a “sudossier” he can only pick a document from the **main** "dossier".

Extranet Ticket: https://extranet.4teamwork.ch/support/stadt-nidau/tracker-gever/175

### Steps to reproduce on dev:

* Selected the subdossier “Vorbereitungen”
* created a new proposal
* at the point "Antragsdokument” the option "bestehendes Dokument” selected and clicked on "hinzufügen..." to select a document

Link to the Subdossier: https://dev.onegovgever.ch/fd/ordnungssystem/ressourcen-und-support/personal/pensionskasse/verwaltungskommission/dossier-555/dossier-556#subdossiers

### Expected behavior
* I can select the document "Vernehmlassung - Beschluss zur Revision des ..." from the "Subdossier" an create the proposal
### Actual behavior
* I can only select the documents from the **main** "Dossier"
### Problems
If a user is searching the document by a word there will be shown all documents which includes the word. It needs to be possible from them to select only the documents from the dossier/subdossier in which they are creating the application
### Workaround:
* at the point Antragsdokument" the creator of the proposal has to put in the name of de document instead of clicking on "hinzufügen..." after a short time there will be a dropdown menu where the creator can select the document:

![2020-03-25 13_28_40-Vorbereitung — Finanzdirektion (FD) (Dev)](https://user-images.githubusercontent.com/60182915/77541721-556baa80-6ea5-11ea-9c3d-31c378b7ad91.png)

**Comment by deiferni** [comment]
_i've taken the liberty to put this bug into the tip of the backlog as it affects a recently introduced feature, as always @phgross can override this_

**Comment by phgross** [comment]
Ins JIRA überführt: https://4teamwork.atlassian.net/browse/GEVER-68

(Bleibt noch offen, wird evtl. nachgeladen)
