### ISSUE TITLE
Login über das neue UI erstellt keinen Benutzer-Order

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/opengever.core#6365]
Wird ein Benutzer erstmalig über das neue UI eingeloggt wird kein Benutzer-Ordner erstellt.

## Aktivierter Benutzer-Order im `portal_membership`-Tool
<img width="807" alt="Bildschirmfoto 2020-04-01 um 15 26 11" src="https://user-images.githubusercontent.com/557005/78142383-287f4080-742d-11ea-8915-4e2d55cdb733.png">

## Kurzanalyse:
Der Member-Ordner wird über `member_tool.createMemberArea` erstellt. Diese Funktion wird z.B. beim Standardlogin ausgeführt:
  1. Redirect nach `loged_in` bei erfolgreichem Login https://github.com/plone/Products.CMFPlone/blob/4.4.x/Products/CMFPlone/skins/plone_login/login_form.cpt.metadata#L9
  2. Login über Members-Tool: https://github.com/plone/Products.CMFPlone/blob/4.4.x/Products/CMFPlone/skins/plone_login/logged_in.cpy#L46
  3. Member-Folder wird erstellt: https://github.com/plone/Products.PlonePAS/blob/master/src/Products/PlonePAS/tools/membership.py#L669

Jedes PAS-Plugin muss diesen Ordner selbst erstellen, falls ein Benutzer korrekt eingeloggt wurde. 

## Auswirkungen auf unsere Deployments
`ftw.casauth` wird bei produktiven Systemen verwendet. Es implementiert die Funktion bereits: `https://github.com/4teamwork/ftw.casauth/blob/master/ftw/casauth/plugin.py#L143``, leider funktioniert es nicht mit dem neuen UI, nur wenn das alte UI verwendet wird.

Auch andere Auth-Plugins wie das `JWT Authentication Plugin` welches von der [Plone-REST-API ](https://github.com/plone/plone.restapi/blob/master/src/plone/restapi/services/auth/login.py#L18)verwendet wird erstellt kein Ordner. Dieser Endpoint wird z.B. bei einem lokalen dev-deployment verwendet.

## Reproduktion
1. dev.teamraum.ch/fd/private/manage_main => userfolder von `hugo.boss` löschen
2. dev.teamraum.ch/fd => login mit hugo.boss und neuem UI
3. Auf "Meine Ablage" navigieren. Der Benutzerfolder existiert nicht

4. dev.teamraum.ch/fd => auf das alte UI wechseln und wieder zurück auf das neue
5. der Benutzerfolder ist nun erstellt

![screen3](https://user-images.githubusercontent.com/557005/78150398-89137b00-7437-11ea-9cdd-8ecf7494cce3.gif)

Oder 

- Login über `@login`-Endpoint der Plone-REST-API (lokales dev-deployment verwendet diesen Endpiont)
- Login über das Plone Standard Login erstellt ein Benutzerordner unter /private

**Comment by njohner** [comment]
Hum, pretty sure I discussed that one with @all4manu some time ago, I thought there should already be an issue for it. Couldn't find it though... Manu?

**Comment by all4manu** [comment]
I created an issue here https://github.com/4teamwork/gever-ui/issues/919, but maybe it's better if it's in the core repo...

**Comment by phgross** [comment]
Problem kann auf dev nicht mehr reproduziert werden.
