### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#647]
```
/home/zope/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/ConflictResolution.py:237→ tryToResolveConflict
/home/zope/eggs/opengever.core-3.4.1-py2.7.egg/opengever/base/monkeypatch.py:151→ DexterityContent_getattr
```

https://github.com/4teamwork/opengever.core/blob/master/opengever/base/monkeypatch.py#L151

There seems to be an issue with our dexterity backport during conflictresolution. As discussed with @lukasgraf this should be further investigated.

The errbit error is here: https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/543678f5383818ed920000de

**Comment by phgross** [comment]
Dieser Monkeypatch sollte entfernt werden können. Nach dem Update auf Dexterity 2.0
