### ISSUE TITLE
error when pasting object id disallowed

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#648]
Instead of raising an error we should notify the user.

https://errbit.4teamwork.ch/apps/524d6966383818361b00175b/problems/544f93c6383818f6d1000098
https://errbit.4teamwork.ch/apps/534f83dc38381851ab005bcd/problems/544fc00f383818c7ee00003f

**Comment by lukasgraf** [comment]
Duplicate: #612
