### ISSUE TITLE
xlssource can't handle lower-case writings of the language mappings

### ISSUE THREAD

**Issue by shylux** [4teamwork/opengever.core#707]
For instance here https://github.com/4teamwork/opengever.core/blob/master/opengever/setup/sections/xlssource.py#L16 the term "Vertraulich" is recognised but "vertrauchlich" throws an error.

Should be fixed, but has low priority since we can also fix it in the xlsx source.

**Comment by phgross** [comment]
Thats not longer an issue, because the current ordnungsystem.xlsx defines the value range and its only possible to select a valid entry.
