### ISSUE TITLE
analysis creating "remote"-content 

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#709]
when executing "remote-requests" on the same plone instance the view that resolves the request performs an unrestricted traverse to resolve the view, see:
https://github.com/4teamwork/opengever.core/blob/master/opengever/ogds/base/utils.py#L223

It then calls the following method wich creates content by bypassing permission checks:
https://github.com/4teamwork/opengever.core/blob/master/opengever/ogds/base/transport.py#L138
`obj = createContent(self.portal_type, title=self.title)`

Traversing unrestricted is necessary because of 09e34ca18564744120428ae9b9964f76ed56f980. Can we add permission checks to the create content method, i.e. by using `plone.api`?

**Comment by maethu** [comment]
The transporter has been rewritten. 
An there is now a test, which checks, if the user actually can add new content:
https://github.com/4teamwork/opengever.core/blob/8b3edc2073adf4fda715b6487764744abaac43e9/opengever/base/tests/test_transport.py#L95

The actual test happens in https://github.com/4teamwork/opengever.core/blob/19035622291ae59dc55d2a82f6e50b055ef973ab/opengever/base/transport.py#L174 --> `addContentToContainer` checks for the add permission.

**Comment by maethu** [comment]
IMHO this can be closed.
