### ISSUE TITLE
Clear end date when reopening dossiers and/or subdossiers

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#727]
According to FR http://feedback.onegov.ch/t/dossier-wiedereroffnen-feld-ende-leeren/70, reopened dossiers and/or subdossiers should have an "empty" end date

**Comment by phgross** [comment]
Wurde mit #2670 gelöst. 

@phabegger die Anpassung ist im 2017.1 Release enthalten (siehe  https://onegovgever.ch/aktuell/aktuell/onegov-gever-release-2017.1) könnte man demnach noch im Feedback Forum aktualisieren.
