### ISSUE TITLE
opengever.meeting todos

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#728]
- [x] Status-messages bei Änderungen/Updates
- [x] Bessere Proposal-History (Mehr Informationen anzeigen, z.B. welche Dokumente nachgereicht wurden)

- [x] Word-Dokumentgenerierung (Vorprotokoll/Protokoll). @deiferni schaut mit @senny.
- [x] Ablage Protokolle?
- [x] `/members` view auf plone site verschieben. @phgross 

Styling
---------
- [x] Antrag hinzufügen/bearbeiten, Autosize-Textfelder erstellen, analog `pre_protocol` view

Bugs/Kleineres
--------------------
- [x] Nicht geplante Anträge -> Nicht trakdandierte Anträge
- [x] portal-message level warn scheint grün gestyled - grundsätzliches theme-problem?
- [x] Icons im moment kapput. @phgross schaut mit @bierik.
- [x] CommitteeContainer ist auch für Anonyme sichtbar
- [x] Vorprotokoll generieren/aktualisieren, tests für abbrechen-button
- [x] Abschnitte / paragraphs werden nicht ins Inhaltsverzeichnis des Vorprotokolls aufgenommen
- [x] Vorprotokoll generieren, titel fehlt, abbrechen funktioniert nicht
- [x] Redirect auf korrektes Tab. (CommitteeContainer, add-member)
- [x] Ausgangslage Immer bearbeitbar
- [x] Feld Rechtsgrundlage für Antrag hinzufügen
- [x] Hinzufügen bei Committee nicht übersetzt
- [x] Tab Komitees umbenennen nach Sitzungen/Sitzungsverwaltung
- [x] Inbox - Dokumente, "Submit additional Documents" sichtbar
- [x] "Submit additional Documents" noch nicht übersetzt
- [x] Zeitlich überschneidende Memberships deaktivieren
- [x] Dokumente nachreichen nicht mehr möglich erst ab status "beschlossen"
- [x] Navigation bei Kommissionen: Evtl. kein Ordnungssystem Portlet mehr

**Comment by lukasgraf** [comment]
[ ] Abschnitte / paragraphs werden nicht ins Inhaltsverzeichnis des Vorprotokolls aufgenommen

**Comment by deiferni** [comment]
Move to basecamp.
