### ISSUE TITLE
Prevent adding disallowed subtypes by manually crafting urls.

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#729]
It is possible to add dossiers to structural repository folders (containing other repository folders) by simply modifying the add-url. We should find a way to reliably prevent bypassing add-rules rules.

**Comment by phgross** [comment]
Das Hinzufügen von Dossiers in nicht Leaf-Node Ordnungspositionen ist nicht mehr möglich, beim Versuch via URL Anpassung, erscheint die Meldung `Unzureichende Berechtigung`.
