### ISSUE TITLE
Advanced search: Add field "creator" when searching for documents

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#753]
Cf. http://feedback.onegov.ch/t/erweiterte-suche-suche-nach-dem-ersteller-eines-dokumentes/81

**Comment by phgross** [comment]
Die erweitere Suche wird mit dem neuen UI, gründlich überarbeitet. Ich schlage vor, dass wir diese Anpassung auch gleich dort umsetzten. Ich habe die Anforderung in den Use Stories aufgenommen.
