### ISSUE TITLE
Tabs not clickable when overlaid by watermark icon

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#760]
![screen shot 2015-02-24 at 17 32 30](https://cloud.githubusercontent.com/assets/736583/6353756/89e4dff0-bc4b-11e4-8271-6c92624a707d.png)

If there is no filter-box the watermark-icon may overlay tabs. These tabs are not clickable.

**Comment by phgross** [comment]
Bitte bei Gelegenheit korrigieren?

**Comment by phgross** [comment]
@bierik bitte korrigieren.
