### ISSUE TITLE
Let themes register themselves instead of depending on them

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#77]
Currently, in order to set up an OpenGever client with a particular theme, you need a policy package that
- pulls in the Python package as a dependency in `setup.py` and
- runs the correct GS profile from that theme package.

This means that it's not possible to easily test a policy with a theme it wasn't originally intended for by just adding that theme to your buildout.

As a solution, we could let `opengever.setup` define a setuptools entry point `theme` that can be used by theme packages to register themselves (dependency inversion).

For example:

```
      [opengever.setup]
      theme = profile-plonetheme.teamraum:gever
```

This entry point in `plonetheme.teamraum` would cause `opengever.setup` to list `plonetheme.teamraum` as a selectable theme in the OpenGever client setup screen, and run the `profile-plonetheme.teamraum:gever` after setting up the client.

**Comment by phgross** [comment]
This is no longer an issue, because we only support one theme, currently `plonetheme.teamraum`, which is a hard dependency from opengever.core.
