### ISSUE TITLE
Dashboard, Desktop Integration for opengever.core

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#78]
In `opengever.phvs` we have a  separate integration for the dashboard and the personal_overview. On the one hand the site root is linked to the dashboard, on the other hand there is a portal tab 'Arbeitsplatz' which brings a desktop functionality, a favorite listing, and the tabs from the `personal_overview`:
![bildschirmfoto 2013-07-12 um 10 58 40](https://f.cloud.github.com/assets/485755/787197/5acf65c8-ead3-11e2-9b33-a05087d1e053.png)

I think this feature should be moved in to opengever.core as an extra feature. So installations, without needing a dashboard like zug, aren't affected to this change.

@lukasgraf @phabegger: what you think ?

**Comment by deiferni** [comment]
we are currently discussing what to do with the dashboard. i suggest we open new issues when a decision has been made.
