### ISSUE TITLE
Drag'n drop of files: Use creation date of uploaded file as document date of file

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#796]
C.f. feedback http://feedback.onegov.ch/t/datumsubernahme-bei-dokumenten-upload/15

**Comment by livschal** [comment]
aus diesem beitrag ist inzwischen dieser thread dazugekommen https://feedback.onegovgever.ch/t/dokumentdatum-aufsplitten-in-aenderungs-und-erstellungsdatum/114 und auf basis davon wird nun der ogip 27 erstellt. ich schliesse daher diesen issue.
