### ISSUE TITLE
Move checkin/checkout menu to left side

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#809]
![screen shot 2015-03-23 at 15 20 37](https://cloud.githubusercontent.com/assets/736583/6781782/7803dac2-d170-11e4-8249-2183d850b487.png)

Currently a prototype implementation can be found here: https://github.com/4teamwork/opengever.core/tree/deif-checkin-checkout-menu-left-side

**Comment by phgross** [comment]
Wir verzichten vorerst auf diese Anpassung, da das Menü mit den im OGIP 9 überflüssig wären.

Mit den Kunden (ZG) noch genauer absprechen.
