### ISSUE TITLE
Products.PloneHotfix20121106 does not work with plone.protect >= 2.0

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#825]
`Products.PloneHotfix20121106.crypto_oracle_protect.py` patches `plone.protect.authenticator._verify` with a method with an invalid signature when used with plone.protect >= 2.0.

**Comment by lukasgraf** [comment]
@deiferni we won't need that Hotfix anymore though once we upgrade to Plone 4.3.x (or even 4.2.3). See http://jone.github.io/plone-hotfixes/

**Comment by deiferni** [comment]
yeah ...  i'm sure we'll update to plone 4.3 soon™ :smirk:.

this means though that we cannot deploy opengever.core release 4.3.0 in its current state (which is what i just wanted to do). if we find an easy workaround i'd suggest to implement it as temporary fix until we manage to upgrade to plone 4.3.

**Comment by deiferni** [comment]
as discussed, we will try to upgrade to plone 4.2.3 for opengever 4.3

**Comment by deiferni** [comment]
Fixed in https://github.com/4teamwork/kgs/pull/53
