### ISSUE TITLE
CSRF-hint-page not translated

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#837]

**Comment by phgross** [comment]
![bildschirmfoto 2015-04-07 um 14 30 13](https://cloud.githubusercontent.com/assets/485755/7023100/ae79a960-dd32-11e4-87b7-6032a9ad77bd.png)

See https://dev.onegovgever.ch/fd/@@confirm-action?original_url=http

**Comment by phgross** [comment]
Fixed via #859
