### ISSUE TITLE
Show paging navigation also at the bottom of table listings 

### ISSUE THREAD

**Issue by phabegger** [4teamwork/opengever.core#840]
C.f. http://feedback.onegovgever.ch/t/navigationselemente-fuer-seitenwechsel-auch-unterhalb-einer-auflistung-zur-verfuegung-stellen/66

**Comment by phabegger** [comment]
Dies betrifft prinzipiell alle Auflistungen von Inhalten in Tabellen - kann dies grundsätzlich gelöst werden, oder muss dies pro Listing aktiviert werden?

**Comment by phgross** [comment]
@bierik bitte prüfen ...

**Comment by phabegger** [comment]
Stand hier? Kann das evtl. jemand anders umsetzen?

**Comment by elioschmutz** [comment]
Ja, das ist ganz einfach möglich.

Die Frage ist, ob wir das generell im Modul ``ftw.tabbedview`` lösen oder nur für das GEVER.

Ich bin für generell im Modul ``ftw.tabbedview``. 

@jone was meinst du dazu? Spricht was dagegen?

**Comment by jone** [comment]
@elioschmutz ich meinte dass wir sowieso alle Templates überschrieben haben im GEVER, das heisst wir müssen es sowieso im GEVER machen.
Ich würde es daher in der Tabbedview vorerst nicht machen, weil kein konkreter Kundenwunsch vorliegt.

**Comment by elioschmutz** [comment]
das `generic.pt` nicht. dies wird u.A. vom Journal-Tab verwendet.

**Comment by elioschmutz** [comment]
Also das ``generic.pt`` von ``ftw.tabbedview`` wird im GEVER immer noch als Standard-Template für Listing verwendet. Danach gibt es das generic mit filter und das generic mit bumblebee-view-chooser.

Bei einer GEVER-Spezifischen Lösung müssen wir zusätzlich auch das Default-Template ``generic.pt`` überschreiben.

Ist das OK?

**Comment by elioschmutz** [comment]
@phgross wie ist hier der Stand? Wie geht es da weiter? Ist das Ticket noch aktuell?
