### ISSUE TITLE
Owner should not be managed by any workflow

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#863]
For example: 
https://github.com/4teamwork/opengever.core/blob/master/opengever/dossier/profiles/default/workflows/opengever_dossier_workflow/definition.xml#L36

Fix the following workflows:
- [x] document
- [x] contact
- [x] dossier
- [x] templatedossier
- [x] forwarding
- [x] inbox
- [x] mail
- [x] repository
- [x] repositoryroot
- [x] task

**Comment by phgross** [comment]
- Workflow Definitionen anpassen
- Tests korrigieren und evtl. erweitern
- Upgradesteps (Workflow update & reindexObject)
 - Manuelles Testen
