### ISSUE TITLE
Synchronize length limits between SQL and Plone models

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#893]
Currently, many SQL columns are limited in length, but the corresponding `zope.schema` fields in Plone are unlimited.

This leads to problems when values from Plone fields are written to SQL on databases that don't do automatic data truncation like MySQL.

These length limits need to be synchronized by factoring out the length into common constants and using those in the SQL model definitions as well as the `zope.schema` models in Plone.

**Comment by phgross** [comment]
- Analyse bestehender Inhalt
- zope schema: limite definieren
- Anpassung SQL Schemas (SchemaMigrationen)
- OGDS Sync (cropping)
