### ISSUE TITLE
Make sure ++resource++kukit.js is always disabled

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#899]
We currently need to disable `++resource++kukit.js` manually (because it leads to issues with inline validation) after setting up a new deployment.

We instead should create
- a hook that does this after setting up a new deployment
- a script that we can run on an existing deployment that checks whether it's already disabled, and if not, disables it

**Comment by phgross** [comment]
The earlier theme had disabled the `kukit.js` by default, see https://github.com/4teamwork/izug.basetheme/blob/b526093aa8704a0f163b43d7c922a9a5e9c8d703/izug/basetheme/profiles/default/jsregistry.xml#L7

**Comment by phgross** [comment]
Wurde mit dem Plone 4.3 Update behoben.
