### ISSUE TITLE
Create a zopemaster user in OGDS

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#901]
im moment erstellen wir für zopemaster keinen ogds-benutzer. dies führt dazu, dass man dies im code speziell behandeln muss, bzw., dass sich an manchen stellen opengever darauf verlässt, dass ein ogds-benutzer vorhanden ist und dann fehler wirft.

wir schlagen vor beim setup auch für zopemaster einen ogds-benutzer anzulegen. dies hat den vorteil, dass man auch ein label für diesen benutzer vergeben kann z.B. Systembenutzer.

**Comment by lukasgraf** [comment]
Wir haben beschlossen dies nicht zu machen.
