### ISSUE TITLE
Adding meeting types should not be possible when feature is disabled

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#907]
Currently, if the meeting feature flag is disabled, the meeting types only get [filtered in the menu](https://github.com/4teamwork/opengever.core/blob/bf07ab826bacd99eb9ca6cf1d8fa6f7b8b360ee8/opengever/dossier/menu.py#L16-L18), but they are still in the `allowedContentTypes`.

This fact also lead to a [change being necessary in the `opengever.ai`](https://github.com/4teamwork/opengever.ai/commit/042bc99db111c717c0f591546a7ce66375406d4c) tests which now expect proposals in the addable types, even though the feature is not yet enabled in that policy.

Instead the respective meeting types should actually not be addable if the feature is disabled. We already have a mechanism in place to check dynamically created `allowedContentTypes` constraints - the [`ConstrainTypesDecider`]( https://github.com/4teamwork/opengever.core/blob/master/opengever/dossier/base.py#L234-L269). It shouldn't be too hard to also use this for the meeting types in **Dossiers** and on the **Plone Site**.

**Comment by deiferni** [comment]
Unfortunately we call the adapter ourself by overriding `allowedContentTypes`. Thus can implement this change for dossiers only.
