### ISSUE TITLE
Add tests, proper logging and small cleanup for the LDAP synchronisation.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#92]
With the PR #83, the ldap synchronisation was completely rebuilded. 
Some tasks are still open and should be implemented for the next release:
- [x] Tests, hard to write. skip.
- [x] Proper logging
- [ ] Cleanup, see comments in the PR #83

**Comment by phgross** [comment]
@lukasgraf gibts da noch was zu tun oder kann man diesen Issue schliessen?

**Comment by lukasgraf** [comment]
Still open. The idea is to have an actual OpenLDAP setup up during tests, and test against that.

**Comment by phgross** [comment]
Bis auf die Tests mit einem "echten LDAP" im Hintergrund wurden alle Cleanup-Arbeiten umgesetzt. Da in letzter Zeit fast oder gar keine Probleme beim LDAP Sync auftraten, lohnt sich der Aufwand für ein solches Testsetup nicht. Falls in Zukunft allenfalls wieder Probleme oder Schwierigkeiten auftreten, kann man auf diesen Issue zurückkommen.
