### ISSUE TITLE
CSRF protection blocks RemoteRequests.

### ISSUE THREAD

**Issue by phgross** [4teamwork/opengever.core#924]
Mandantenübergreifende requests (siehe helper [dispatch_request](https://github.com/4teamwork/opengever.core/blob/1c16c101a066f8c77d5a6d7cf6a50cfa7e7c0bb6/opengever/base/request.py#L33)) werden vom plone.protect aktuell nicht akzeptiert.

@jone gibt es eine Möglichkeit all diese Requests, als ok einzustufen? Evtl. über den Request Layer [`IInternalOpengeverRequestLayer`](https://github.com/4teamwork/opengever.core/blob/master/opengever/ogds/base/interfaces.py#L117)?

**Comment by jone** [comment]
Ich würde den ``IInternalOpengeverRequestLayer`` (``dispatch_request`` ist ja auf der Quell-Instanz, das Problem aber auf der Ziel-Instanz).

Das könnte man gut [_global_unprotect](https://github.com/4teamwork/opengever.core/blob/990bac51244efa434bb922dc5fc07a0fa32b6c04/opengever/base/protect.py#L71) machen:

```python
if IInternalOpengeverRequestLayer.providedBy(self.request):
    alsoProvides(self.request, IDisableCSRFProtection)
```

**Comment by phgross** [comment]
@Jone Danke für's Feedback. Noch ne frage würdest du die Anpassung im [_global_unprotect](https://github.com/4teamwork/opengever.core/blob/990bac51244efa434bb922dc5fc07a0fa32b6c04/opengever/base/protect.py#L71) implementieren oder eher im [OGDS Plugin](https://github.com/4teamwork/opengever.core/blob/master/opengever/ogds/base/Extensions/plugins.py#L37) ?

**Comment by jone** [comment]
Das OGDS Plugin würde auch ganz gut passen, wahrscheinlich eher dort..
