### ISSUE TITLE
Unify definition of autoincrementing SQL columns

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#927]
We currently use both `Column(..., primary_key=True)` and `Column('id', Integer, Sequence('id_seq'), primary_key=True)` to achieve auto incrementing columns. We need to unify how we define these columns, and plan how to migrate / "reset" sequence counters after the migration to PostgreSQL.

**Comment by deiferni** [comment]
Betrifft die Tabellen:

- activities
- notifications
- resources
- notification_defaults
- watchers

Mit Oracle **muss immer** eine ``Sequence`` fürs auto-increment verwendet werden, siehe: http://sqlalchemy.readthedocs.org/en/rel_0_7/dialects/oracle.html?highlight=sequence.

Bei Postgres ist es auch möglich named sequences anzugeben, siehe http://sqlalchemy.readthedocs.org/en/rel_0_7/dialects/postgresql.html?highlight=sequence. Bei MySQL werden sequences ignoriert, da nicht unterstützt.

Bestehende Postgres Datenbanken werden so migriert, dass für die oben genannten Tabellen der von SqlAlchemy generierte server-default entfernt wird. Ebenso wird der owner der entsprechenden sequence entfernt. Damit ist das Schema auf dem Stand der anderen, schon mit initialer ``Sequence`` erstellten Tabellen.
