### ISSUE TITLE
Antrags Ansicht: Eingereichte Dokument Version darstellen

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#936]
Wenn ein Antrag mit Dokumenten eingereicht wird, werden diese ins `SubmittedProposal` kopiert. Wird das Dokument im Dossier daraufhin verändert, werden die Dokumente im Antrag nicht automatisch aktualisiert, dies muss manuell gemacht werden.

Ich würde vorschlagen beim Antrag dieselbe Ansicht zum aktualisieren wie auch beim Dokument darzustellen:

Dokument:
![screen shot 2016-02-24 at 15 22 45](https://cloud.githubusercontent.com/assets/736583/13288048/71ec20aa-db0a-11e5-9eeb-8a923d1e4da2.png)

Antrag:
![screen shot 2016-02-24 at 15 23 15](https://cloud.githubusercontent.com/assets/736583/13288064/85d668a0-db0a-11e5-875b-d5a334cdcf29.png)

**Comment by phabegger** [comment]
Evtl. genügt es für dne Moment, den Timestamp der Einreichung darzustellen.

**Comment by elioschmutz** [comment]
@deif Kannst du bitte das Problem, bzw. Auftrag genauer spezifizieren...

**Comment by deiferni** [comment]
@elioschmutz done

**Comment by elioschmutz** [comment]
:+1: super! danke
