### ISSUE TITLE
portal-message level warn scheint grün gestyled - grundsätzliches theme-problem?

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#938]

**Comment by phgross** [comment]
@deiferni hast du hierzu noch mehr Informationen, Screen Shot URL?

Eine generelles Probleme ist es nicht:
![bildschirmfoto 2015-06-29 um 08 21 34](https://cloud.githubusercontent.com/assets/485755/8402107/0f263a94-1e38-11e5-86d5-d8152a527cfa.png)

**Comment by deiferni** [comment]
Ja, ich kanns so reproduzieren:

- Antrag mit einem angehängten Dokument einreichen
- Dokument für den gleichen Antrag nachreichen, feuert Warnung https://github.com/4teamwork/opengever.core/blob/master/opengever/meeting/command.py#L297

Styled ist das dann so:

![screen shot 2015-06-29 at 08 54 00](https://cloud.githubusercontent.com/assets/736583/8402559/76741a96-1e3c-11e5-98b6-6604aeeb745f.png)

Auf der markup-Seite scheint auf den ersten Blick alles in Ordnung zu sein.

![screen shot 2015-06-29 at 08 54 07](https://cloud.githubusercontent.com/assets/736583/8402558/765ceede-1e3c-11e5-9684-bdf634684413.png)
