### ISSUE TITLE
Subdossier-Tiefe: DefaultConstrainTypeDecider sollte Registry-Eintrag maximum_dossier_depth verwenden

### ISSUE THREAD

**Issue by deiferni** [4teamwork/opengever.core#955]

**Comment by lukasgraf** [comment]
Stellt sich heraus dass dies ein Benutzer-Fehler (im weitesten Sinn) war: Anpassen des Registry-Eintrags alleine reicht nicht, es muss auch der `ConstrainTypeDecider` überschrieben werden.

Der `DefaultConstrainTypeDecider` sollte allerdings so angepasst werden, dass er die Verschachtelungstiefe vom Registry-Eintrag ausliest statt hardcodierte Werte zu verwenden.

**Comment by deiferni** [comment]
wie grad mit @phgross diskutiert, wir sind der meinung, dass man für `opengever.dossier.businesscasedossier` und `opengever.private.dossier` das gleiche setting brauchen kann
