### ISSUE TITLE
Manage all Office Mimetypes in Mimetype Registry

### ISSUE THREAD

**Issue by lukasgraf** [4teamwork/opengever.core#980]
Currently, we're missing a couple of the standard Office mimetypes from our mimetype registry setup, for example the types for macro enabled formats like`*.xlsm` or `*.docm`.

We should include all the types listed in http://blogs.msdn.com/b/vsofficedeveloper/archive/2008/05/08/office-2007-open-xml-mime-types.aspx to make sure all those types get a proper icon.

Requires an upgrade step that fetches all the `opengever.document.document` objects of the affected types and reindexes their `getIcon` metadata / index.

**Comment by phgross** [comment]
Fixed via #1017
